### ISSUE TITLE
Fetchmail config displayed in logs

### ISSUE THREAD

**Issue by kaiyou** [Mailu/Mailu#10]
The fetchmail configuration file is currently displayed in logs, including passwords. This should not happen.

**Comment by adi90x** [comment]
Still happening , fetchmail display everything in STDOUT.

` print(fetchmailrc) line 69`  in fetchmail/fetchmail.py

**Comment by kaiyou** [comment]
Oh. This must have been reintroduced in a later commit. Will fix it today, thanks.

**Comment by adi90x** [comment]
Is it possible to keep it when DEBUG = true ?
