### ISSUE TITLE
setup guide should include DKIM key DNS setup

### ISSUE THREAD

**Issue by ghost** [Mailu/Mailu#1002]
While there is an amazing DKIM gui in the security settings of the admin page, the setup guide should reference that you'll need to regenerate DKIM keys and put them in DNS.

A line in https://mailu.io/1.6/setup.html would be appropriate or lines in the docker-compose and kubernetes sections.

I guess adding lines in https://mailu.io/1.6/dns.html wouldn't hurt, since it is DNS...

thoughts?

**Comment by kaiyou** [comment]
Definitely agreeing on both the setup and DNS docs. Any PR is welcome on the matter :)

**Comment by toxik-io** [comment]
I've also added some unrelated stuff on access denied errors (dunno why having DOMAIN be the first HOSTNAMES entry works... but it does.
