### ISSUE TITLE
SMTP Auth slow (takes 10 seconds all the time)

### ISSUE THREAD

**Issue by filipe-paredes** [Mailu/Mailu#1007]
With or without SSL, the authentication takes always 10 seconds to complete, be it with valid or invalid credentials.
Couldn't find any logs that explain what's the issue. But I can see through the logs the request arriving at the Frontend and then a pause of 10 seconds, then finally logs show up on the SMTP container which quickly replies back to the Frontend.

I deployed 3 days ago the mailu setup following the instructions for Docker Compose.

Any hints on what I should be looking for?

**Comment by kaiyou** [comment]
Could you try and restart your front and smtp containers? See if it related to anything like container name resolution.

**Comment by filipe-paredes** [comment]
I have restarted them already. Even destroyed all containers and recreated them from docker-compose, no luck.
Going inside each container I can ping and resolve the hostnames. And its instantaneous.

The scenario I'm testing is to send an email. Although the authentication takes 10 seconds, it succeeds and the email is sent. Its really just the weird problem of slow authentication. Everything else, SSL with Let's Encrypt, DKIM, SPF, etc. seems to be working fine.

Could it be related with "Authentication rate limit (per source IP address)" setting from the Mailu setup config tool? Where is this configured afterwards, in Postfix?

**Comment by filipe-paredes** [comment]
I have tried to recreate from scratch the mailu stack with compose again even with a different database (postgre instead of sqlite) but the same problem continues to happen.
I notice then that mailu_front_1 is actually calling mailu_admin_1 on http://admin/internal/auth/email to perform the authentication.
If I configure a different URL on the nginx configuration, the error during authentication is immediate. Which leads me to believe those 10 seconds are actually in mailu_admin_1 when the /internal/auth/email endpoint is called.

I have been looking at the web application in mailu_admin_1 but I'm seeing Python for the first time in my life :P

**Comment by hoellen** [comment]
On which hardware do you run your Mailu instance? It could be the calculation of the password hash. You could try in your `.env` file another password scheme.

corresponding section in `.env`:
```
# Default password scheme used for newly created accounts and changed passwords
# (value: PBKDF2, BLF-CRYPT, SHA512-CRYPT, SHA256-CRYPT)
PASSWORD_SCHEME=PBKDF2
```
_caution: If you change this value, you need to change the password for your user account._

Do you also have those problems with IMAP (i.e. receiving emails)?

**Comment by filipe-paredes** [comment]
@hoellen, thanks for the suggestion.
I tried with PBKDF2 and even with MD5, both of them show a slight improvement but in the order of 200 or 500ms. But the 10 seconds delay during the authentication still remained.

Also noticed something interesting, logging in from the Admin UI is immediate.
The 10 seconds delay seems to be only when authenticating from /internal/auth/email

**Comment by filipe-paredes** [comment]
So the problem seems to be the rate limiter used in the /internal/auth/email endpoint.

In the file https://github.com/Mailu/Mailu/blob/1.6/core/admin/mailu/internal/views/auth.py there is a rate limiter defined in line 11-14. If I replace it with @utils.limiter.exempt the authentication is immediate.

Guaranteed nobody else is calling this endpoint. Only me a few time every 10 minutes.

My configuration for the code app.config["AUTH_RATELIMIT"] returns the string "10000/minute;60000/hour". I also tried with "10/minute;60/hour" and the behavior remain, 10 seconds wait before the authentication succeeds.

Any idea if its a misconfiguration or a bug in the rate limiter?

**Comment by kaiyou** [comment]
It could be a bug with the limiter. Maybe your redis container, which is used by the limiter, has an issue?

**Comment by kaiyou** [comment]
Any news?

**Comment by hcderaad** [comment]
Might it be that Flask is using the wrong IP address here and actually block/delay the internal IP for all requests? Some googling (yes, yes, I know, this is something to be taken with at least a pinch of salt) gave me these results:
https://stackoverflow.com/questions/3759981/get-ip-address-of-visitors-using-flask-for-python/16502990

https://github.com/mattupstate/flask-security/blob/4049c0620383f42d37950c7a35af5ddd6df0540f/flask_security/utils.py#L65

I get the delayed SMTP transaction warning from mxtoolbox with my vanilla mailu setup as well. Will investigate further over the weekend.

**Comment by kaiyou** [comment]
Normally, Flask should use the proper fields for rate limiting since we explicitly provide it, so I doubt the linked thread is related.

**Comment by kaiyou** [comment]
I am closing this as stale, feel free to reopen
