### ISSUE TITLE
Not receiving any mails on newest "latest"

### ISSUE THREAD

**Issue by RaymondSchnyder** [Mailu/Mailu#101]
Good morning dear People from mailu,

thanks to your help i can now Access the webinterface and send mails, but im not receiving any mails.

When i send myself a mail with the same address, i get the mail. But when i send it from other mail addresses, roundcube doesnt want to Show me any mail.

Is there a possibilty to check some log files?

Greetings

Raymond

**Comment by kaiyou** [comment]
You can check the log files by running  : 

```
docker-compose logs -f
```

You can also check the logs for a specific service or set of services:

```
docker-compsoe logs -f smtp imap
```

Could you paste logs for SMTP and IMAP when you send the failing email?

**Comment by RaymondSchnyder** [comment]
When I send a mail from mailu to another mail, it works as it should and i can see log entries.
but if I send a mail from an another mail to my mailu Installation, i dont get any log entries and it seems that "i dont get the mail".

Heres the complete log with the folowing steps executed:
1. Login into roundcube
2. Send a mail to home address
3. send a mail from home address to mailu Installation

http://pastebin.com/rteU6wZY

**Comment by kaiyou** [comment]
Actually, does your company use the domain ``domain.com``? If not, you should setup a proper domain in Mailu. In that domain configuration (how you configure it highly depends on your provider and hoster but let's say that you can edit the zone file), you should be able to add an entry to the zone file.

If you named your server (``HOSTNAME`` in the configuration) ``mail.mydomain.com``, then you should have at least a ``A`` record in the DNS to the IP address of the server, which should also be the IP you setup as ``BIND_ADDRESS``:

```
mail.mydomain.com.    IN    A    a.b.c.d
```

Then, for every domain that you want your server to serve, you must have an ``MX`` record, pointing to the hostname:

```
mydomain.com.    IN    MX    10 mail.mydomain.com.
```

The number (10) is the priority of the record. If you have a backup mail server, you should setup a second ``MX`` entry and adjust priorities.

**Comment by kaiyou** [comment]
Here you go : https://github.com/Mailu/Mailu/wiki/Setup-your-DNS

**Comment by RaymondSchnyder** [comment]
Ive already set up my DNS like this, but im not getting any mails. Its very strange. I can send mails, but noone can send mails to me

**Comment by kaiyou** [comment]
If your domain MX points to your mail server public IP address, could you check that port ``25`` is indeed available from the Internet at that IP address?

**Comment by RaymondSchnyder** [comment]
netstat -plunt
`Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN      17253/docker-proxy
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      9983/nginx -g daemo
tcp        0      0 127.0.0.1:8443          0.0.0.0:*               LISTEN      17273/docker-proxy
tcp        0      0 127.0.0.1:8000          0.0.0.0:*               LISTEN      17840/docker-proxy
tcp        0      0 127.0.0.1:993           0.0.0.0:*               LISTEN      17529/docker-proxy
tcp        0      0 0.0.0.0:3939            0.0.0.0:*               LISTEN      409/sshd
tcp        0      0 0.0.0.0:43110           0.0.0.0:*               LISTEN      372/rpc.statd
tcp        0      0 127.0.0.1:3306          0.0.0.0:*               LISTEN      7179/mysqld
tcp        0      0 127.0.0.1:587           0.0.0.0:*               LISTEN      17234/docker-proxy
tcp        0      0 127.0.0.1:143           0.0.0.0:*               LISTEN      17559/docker-proxy
tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN      360/rpcbind
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      9983/nginx -g daemo
tcp        0      0 127.0.0.1:8080          0.0.0.0:*               LISTEN      17282/docker-proxy
tcp        0      0 127.0.0.1:465           0.0.0.0:*               LISTEN      17243/docker-proxy
tcp6       0      0 :::3939                 :::*                    LISTEN      409/sshd
tcp6       0      0 :::51588                :::*                    LISTEN      372/rpc.statd
tcp6       0      0 :::111                  :::*                    LISTEN      360/rpcbind
tcp6       0      0 :::21                   :::*                    LISTEN      26620/vsftpd
udp        0      0 0.0.0.0:57949           0.0.0.0:*                           372/rpc.statd
udp        0      0 0.0.0.0:959             0.0.0.0:*                           360/rpcbind
udp        0      0 127.0.0.1:972           0.0.0.0:*                           372/rpc.statd
udp        0      0 0.0.0.0:111             0.0.0.0:*                           360/rpcbind
udp6       0      0 :::47588                :::*                                372/rpc.statd
udp6       0      0 :::959                  :::*                                360/rpcbind
udp6       0      0 :::111                  :::*                                360/rpcbind
`
Port check:

> http://i.imgur.com/JEQZPH0.png

**Comment by kaiyou** [comment]
Indeed, it seems that you did not change the ``BIND_ADDRESS`` to your public IP address in the ``.env`` file: all your services are listening on ``127.0.0.1``, which is not available publicly. You should either set your public IP address there if the machine has one, or the local network address if you are behind a firewall with port forwards.

**Comment by RaymondSchnyder** [comment]
@kaiyou Indeed you are right, i have BIND_Address on "127.0.0.1". Im a fucking Idiot.
Sorry, i installed mailu so many times, i forgot this. Okay, i put in the public IP and if it doesnt works again, i reopen this ticket. Sorry mate

**Comment by RaymondSchnyder** [comment]
Actually i have a little question, do i need to reinstall everything or just to restart docker?

**Comment by kaiyou** [comment]
You just need to change the ``BIND_ADDRESS`` in your ``.env`` then run:

```
docker-compose up -d
```

This will recreate the required containers properly.

**Comment by RaymondSchnyder** [comment]
Im so sorry for wasting your time. Thank you very much for the help. Now it should work, if it doesnt work, i reopen the issue. Thank you very much. :-)

**Comment by RaymondSchnyder** [comment]
Okay after i "fixxed" my issue, the "/admin" Location doesnt work anymore. The reverse Proxy in nginx cant reach it. /webmail does work fine...

**Comment by kaiyou** [comment]
What do you mean by "doesn't work"? do you have a specific error code?
Could you check that the container is actually up?

```
docker-compose ps
```

**Comment by RaymondSchnyder** [comment]
nginx 502 error code (Im at work, so i cant write all the time with all Details, sorry)
the Container is up.

**Comment by kaiyou** [comment]
This is weird indeed. Could you paste the output of ``docker-compose ps`` and ``docker-compose logs --tail=50 http admin``?

**Comment by RaymondSchnyder** [comment]
Here:
http://pastebin.com/WiD6kxVA

I dont get why he tries to Redirect to ""http://172.18.0.11:80/admin/"  thats not even my IP... wtf

**Comment by kaiyou** [comment]
``172.18.0.11`` is the internal Docker IP of the admin container. The container seems to be running, but not serving anything on port 80.

Could you export specifically the admin container logs?

```
docker-compose logs --tail=50 admin
```

Also, I suspect that maybe one container was not recreated properly and that nginx has memorized an old IP address for the admin container. Could you try and restart nginx?

```
docker-compose restart http
```

Thanks.

**Comment by RaymondSchnyder** [comment]
Admin logs:
http://pastebin.com/PukyaMb8

nginx restarted properly and without Errors.

**Comment by kaiyou** [comment]
I strongly suspect that something went wrong when the containers were recreated. Could you try again after restarting nginx. If that does not work, could you try and bring the whole stack down and back up?

```
docker-compose down
docker-compose up -d
```

This will recreate every container and will make sure that no cache is kept anywhere that could cause this behaviour.

**Comment by RaymondSchnyder** [comment]
@kaiyou did your commands,  still "502 Bad Gateway"

http://pastebin.com/Z2ai4n3L log from HTTP

**Comment by kaiyou** [comment]
The latest logs look irrelevant to the issue, maybe someone trying to access the server using HTTPS on an HTTP port for instance. I still do not understand the root cause of the issue. Could you run the following again:

```
docker-compose logs --tail=10 -f admin http
```

Then while the command is running, try and trigger the 502 error. Then export the resulting logs.

Also:

```
docker inspect mailu_admin_1
docker inspect mailu_http_1
```

**Comment by RaymondSchnyder** [comment]
LOL now it works as expected? wtf.
i did only the log command above and reloaded the site and it works?!
strange...

**Comment by kaiyou** [comment]
I suspect that the last 502 you got was your browser's cache and that refiring the stack fixed the issue as expected.

The basic issue is simple: when ``nginx`` starts, it resolves every IP address required for backend (here, the internal Docker IP address of the admin container). Then it caches that IP and uses it for every request.

When you changed your ``.env`` file and restarted the entire stack, Nginx was probably recreated before the admin container, thus learning the old IP address of the admin container, which was later recreated and changed IP. Restarting Nginx should have solved the issue however.

Anyway, I will try and avoid this kind of issue using dependencies in the Docker Compose file.
