### ISSUE TITLE
Expose sieve port: 4190 to the wild ?

### ISSUE THREAD

**Issue by tuxBurner** [Mailu/Mailu#1016]
Hello i am currently running mailu 1.6 and i am loving it 😍

I found this plugin for thunderbird which helps managing the sieve rules: https://github.com/thsmi/sieve.

I know that i can manage the sieve rules in the webmailer (roundcube), which is totally fine for me.
But when trying the plugin i recognized that sieve port: 4190 is not exported to the web.

Is there a specific reason, i.e. security concerns, for this, or am i the first one finding this out ?

I can help to export the port by a pull request.

Keep on with this excellent project.

Greetings tuxBurner

**Comment by hoellen** [comment]
The problem is, that we do the authentication through nginx reverse proxy. And nginx unfortunately doesn't support the sieve protocol.
Here are some more information: #497 and #428

**Comment by tuxBurner** [comment]
Okay than i can close the issue thanks for the reply @hoellen

**Comment by charno** [comment]
Hi @hoellen,

At https://forum.nginx.org/read.php?29,287586,292632#msg-292632 there is a proposed patch for nginx that enables sieve forwarding. I don't know how you build nginx, but maybe it would be an option to include this patch? Or maybe put some pressure on the nginx devs to finally include this in mainline?

**Comment by elandorr** [comment]
I'd like to express my interest in this as well. This is related to https://github.com/Mailu/Mailu/issues/1328 anyhow, which is an itch that keeps on itching. Mailu's a bit too unorganized for an inexperienced user to dig into the setup, so I don't know your reasoning, but getting rid of the reverse would fix both.

Is there a way to view sieve scripts directly? The docs don't mention sieve at all. All we have are the filters in the web UI.

I just found this old issue: https://github.com/Mailu/Mailu/issues/1452

**Comment by ghostwheel42** [comment]
@elandorr this is the reasoning behind not exposing sieve: https://github.com/Mailu/Mailu/pull/428#issuecomment-967195644
It would be really cool to have sieve proxying in nginx, but we didn't want to build it ourselves because this would force us to update the patch when nginx is updated.

**Comment by elandorr** [comment]
@ghostwheel42 I see.

> Our security model is that ALL communication goes via front. 

If you can be bothered: Why? What's the benefit of that?

And do you know where we can see the scripts? I try not to mess with things that aren't in the docs so please excuse if it's obvious.

**Comment by ghostwheel42** [comment]
@elandorr sorry for the delay.
I'M fairly new to the project - the model was not made by me.
But it makes sense to keep the number of "interaction points" with the outside world small - less chances for errors.
> And do you know where we can see the scripts?

The sieve scripts are handled by dovecot. Dovecot saves them in the mail folder.
The scripts can be found in the mailu storage path: `...storage/mail/email@address/sieve/...`
