### ISSUE TITLE
Adding the following entry to the FAQ [Enhancement]

### ISSUE THREAD

**Issue by RaymondSchnyder** [Mailu/Mailu#102]
```
# How do I activate DKIM?

Go into the Domain Panel, choose the Domain you want to enable DKIM for, click the first Icon on the left side, and click on the top right on the "Regenerate Keys" Button. It will generate the DKIM Entry for you.
```

Just a Suggestion, because i didnt got it a Long time before i found out how to generate the keys.

I hope this is not pure trash and bullshit

Greetings
Raymond

**Comment by kaiyou** [comment]
Yes, of course, feel free to edit the Wiki :)

**Comment by yuracher** [comment]
I get an "Internal Server Error" error after clicking on the "Regenerate Keys" Button. And I see no related messages using "docker-compose logs" command. How can I debug/fix it?

**Comment by renay** [comment]
> I get an "Internal Server Error" error after clicking on the "Generate keys" Button. And I see no related messages using "docker-compose logs" command. How can I debug/fix it?

I have the same problem, do you have the solution of this problem?

**Comment by yuracher** [comment]
If you use russian language then please try to switch to english.

**Comment by kaiyou** [comment]
Yes, this is a strange but probably easy-fix bug due to russian language probably missing some bits. Unfortunately none of us had time to investigate yet, so any help is welcome.

**Comment by kaiyou** [comment]
#943 is better suited for this discussion though

**Comment by LinuxCuba** [comment]
The keys are generated, but mailu postfix you do not send the emails signing dkim. I don't see any mechanisms in postfix's configuration to sign outgoing emails. They can explain this situation.
