### ISSUE TITLE
Kuebernetes Admin UI URL in redirect loop

### ISSUE THREAD

**Issue by trilitheus** [Mailu/Mailu#1021]
I'm attempting to get this set up on Kubernetes to evaluate.

Unfortunately, when trying to hit the admin, I get in a redirect loop to /admin/ui/

```
$ curl -I -L https://mail.example.com/admin/ui/                                                            

HTTP/1.1 301 MOVED PERMANENTLY
Date: Wed, 15 May 2019 19:15:56 GMT 
Content-Type: text/html; charset=utf-8
Content-Length: 291 
Connection: keep-alive
Location: https://mail.example.com/admin/ui/
Strict-Transport-Security: max-age=15724800; includeSubDomains
...
...
...
HTTP/1.1 301 MOVED PERMANENTLY
Date: Wed, 15 May 2019 19:15:58 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 291
Connection: keep-alive
Location: https://mail.example.com/admin/ui/
Strict-Transport-Security: max-age=15724800; includeSubDomains

curl: (47) Maximum (50) redirects followed
```

I think this is a combination of the admin flask app and the nginx-ingress redirects (although that may be wrong as I've no experience with flask)

I'm using a previously installed nginx-ingress (from https://github.com/kubernetes/kops/blob/master/addons/ingress-nginx/v1.6.0.yaml) and am running kubernetes as this is Kubernetes installed via KOPS on AWS.

The ingresses seem to be configured correctly, SSL certs in palce etc and annotiation prefix made sure to match.

This does not appear to be a http -> https loop, all redirects are to and from https

Any assistance would be greatly appreciated.

**Comment by hacor** [comment]
Late reply, but anyway.
I figured out the error you have and a PR is created. 

You can see it's only a minor change in the `mailu-admin-ui-ingress` and the `mailu-admin-static-ingress`

Hopefully this solves your problem!
All the best,

Hacor

**Comment by trilitheus** [comment]
Hi I can confirm that ths changes have sorted this particular issue - may thanks for the update

**Comment by micw** [comment]
@trilitheus Could you check if https://github.com/Mailu/Mailu/pull/1117 solves this issue too on nginx? I have changed the admin ui to listen on /admin/ui so that no path rewriting is required. This makes it more portable between different ingress controllers.
