### ISSUE TITLE
Wrong instruction of Mailu configuration for docker stack

### ISSUE THREAD

**Issue by kaznak** [Mailu/Mailu#1022]
[Mailu configuration](https://mailu.io/1.6/setup.html) gave me the following instruction for docker stack.

```
mkdir -p //mailu/{redis,certs,data,dkim,mail,overrides/rspamd,filter,dav,webmail}
```

But after docker stack deploy, Docker rejects the mailu_front container repeatedly and emits following error messages:

> "invalid mount config for type "bind": bind source path does not exist: /mailu/overrides/nginx"

Docker shows this error message with `docker stack ps mailu --no-trunc`.

I think the mkdir instruction is wrong and have to be the follwing:

```
mkdir -p //mailu/{redis,certs,data,dkim,mail,overrides/{rspamd,nginx},filter,dav,webmail}
```

Thank you.

**Comment by hoellen** [comment]
This is already fixed on master. But its not deployed on the setup page. I will create a backport PR for the 1.6 branch. Thanks for reporting. 
See #964 and #1025.

**Comment by kaznak** [comment]
Thank you for fixing it!
