### ISSUE TITLE
Is there any better practice to make a black-hole address?

### ISSUE THREAD

**Issue by kaznak** [Mailu/Mailu#1026]
I set up mailu stack recently and want to make an address which dedicates to send mail and discards all received stuff.
But I could not find a right way, so I periodically remove all of the files under the directory, such as /mailu/mail/<blackhole@example.com>, of the address by crond.

This approach seems to be very dirty.
I am searching for another better solution.

Thank you.

**Comment by kaiyou** [comment]
This looks like a really specific use case that should be supported using custom delivery scripts.

I would advise you create a sieve script that juts discards emails to that address, or that you create a dead alias for it.

Feel free to reopen if required.
