### ISSUE TITLE
Set sending quotas per user?

### ISSUE THREAD

**Issue by binaryfire** [Mailu/Mailu#1031]
Hi all

We're currently using Virtualmin for email. It's been rock solid, but we'd like to be able to move to a docker solution to make maintenance and upgrading easier. Also rainloop has a much nicer UI than roundcube.

The only thing we need that I can't find information on is whether we can set sending rate limits and monthly quotas per user in mailu. Is this possible? We're providing email as part of a hosting service, so this is a must for us.

Thanks!

**Comment by hoellen** [comment]
This kind of quota is not supported, yet. Currently you can _only_ set a quota for the storage size of the user.

**Comment by Nebukadneza** [comment]
Hi There,

The `Mailu`-Project is currently in a bit of a bind! We are short on man-power, and we need to judge if it is possible for us to put in some work on this issue.

To help with that, we are currently trying to find out which issues are actively keeping users from using `Mailu`, which issues have someone who want to work on them — and which issues may be less important. These a less important ones could be discarded for the time being, until the project is in a more stable and regular state once again.

In order for us to better assess this, it would be helpful if you could put a **reaction on this post** (use the :smiley: icon to the top-right).
- 👍️ if you **need this** to be able to use Mailu. Ideally, you’d also be able to test this on your installation, and provide feedback …
- 🎉 if you find it a **nice bonus**, but no deal-breaker
- 🚀 if you want to **work on it yourself**!
We want to keep this **voting open for 2 weeks** from now, so please help out!
