### ISSUE TITLE
helm chart for kubernetes (feature request)

### ISSUE THREAD

**Issue by mildred** [Mailu/Mailu#1032]
I'm filing this because having helm chart for kubernetes would be nicer than having to modify the kubernetes files by hand.

**Comment by WebSpider** [comment]
I wouldn't mind working on this a bit.
Disclaimer: I would be using this to learn about setting up helm charts.

Anyone else working on this?

**Comment by micw** [comment]
Hi, i have a work-in-progress helm chart at https://github.com/micw/charts/tree/mailu/incubator/mailu. Runs on my prod server.

**Comment by kaiyou** [comment]
@micw how do you feel about the current version of your helm chart?

**Comment by outbackdingo** [comment]
url no longer exists .. relocated to mailu .... 0 values.yml example?

**Comment by outbackdingo** [comment]
does anyone have a reasonable "values.yml fort editing, which would "complete" this chart ? im lost and cannot deploy

**Comment by micw** [comment]
@outbackdingo Please comment about the in the chart repo, not here. Thank you!
