### ISSUE TITLE
Switch existing setup from sqlite3 to remote mysql

### ISSUE THREAD

**Issue by radoslav-stefanov** [Mailu/Mailu#1037]
Hello,

Is mysql option for database server available yet? I tried to migrate my existing test setup from sqlite3 to mysql by adding the necessary variables to mailu docker-compose env file, but I can't make it work for now.

I have uploaded sql3 data to the mysql db and verified that mailu has access to that db. Maybe containers have to be re-created? ```docker-compose down && docker-compose up``` doesnt seem to do the trick.

I am wondering if there is any existing guide how to do it? Or if you could give hint with a few notes.

Thanks!

**Comment by eduardocostabr** [comment]
I had the same issue.
Solved it this way: created a configuration from setup.mailu.io to use sqlite. 
Then, started it, add my first user... and all those stuff (checked also if the TLS was working...)

After, I stopped the docker instance, and I've used this script I found on github to convert the file in /mailudata/data/main.db, this way:

script: https://github.com/vwbusguy/sqlite-to-mysql/blob/master/python/sqlite3-to-mysql.py

sqlite3 main.db .dump | ./sqlite3-to-mysql.py -u mailu -p passwordhere -d mailu > ./file.sql

Then, I removed all the part of granting permission to the user (already done it beforehand),
and changed the order of two tables in the sql file (not so sure now, but I think the first was domain and the seccond user) because of some key.

Then, I've changed the .env file to use my mysql instance.

#DB_FLAVOR=sqlite
DB_FLAVOR=mysql
DB_USER=mailu
DB_PW=password
DB_HOST=10.1.1.3
DB_NAME=mailu

Then removed the .db stuff from sqlite, changed some data in sql to be sure what database I am using, and so far (two hours hahaha) its working.

**Comment by kaiyou** [comment]
Thank you for sharing. It is indeed pretty straightforward. We should add some documentation on the topic.

**Comment by Nebukadneza** [comment]
Hi There,

The `Mailu`-Project is currently in a bit of a bind! We are short on man-power, and we need to judge if it is possible for us to put in some work on this issue.

To help with that, we are currently trying to find out which issues are actively keeping users from using `Mailu`, which issues have someone who want to work on them — and which issues may be less important. These a less important ones could be discarded for the time being, until the project is in a more stable and regular state once again.

In order for us to better assess this, it would be helpful if you could put a **reaction on this post** (use the :smiley: icon to the top-right).
- 👍️ if you **need this** to be able to use Mailu. Ideally, you’d also be able to test this on your installation, and provide feedback …
- 🎉 if you find it a **nice bonus**, but no deal-breaker
- 🚀 if you want to **work on it yourself**!
We want to keep this **voting open for 2 weeks** from now, so please help out!

**Comment by Mikeatme** [comment]
@eduardocostabr How did you manage to connect to your SQL-Server / check the connection?

> Then removed the .db stuff from sqlite, changed some data in sql to be sure what database I am using, and so far (two hours hahaha) its working.

I managed to migrate my sqlite-data to my mysql-server (with some issues with the CHECK in the ported .sql-file) and a changed to DB-Variables in the mailu.env file to 

#DB_FLAVOR=sqlite
DB_FALVOR=mysql
DB_USER=mailu
DB_PW=*my super secret password*
DB_HOST=*public.server.ipv4.address*
DB_NAME=mailu

but when I do a docker-compose down && docker-compose up -d and check the logs of the admin container, it still user sqlite
`docker logs -f mailu_admin_1`
`INFO  [alembic.runtime.migration] Context impl SQLiteImpl.`

Does anyone have an Idea on this?

**Comment by eduardocostabr** [comment]
Hi,

there is a typo in your configuration, and sorry, but cant help, as I haven't touched Mailu for a while now. I just update it time to time to keep it running safely.

DB_**FALVOR**=mysql
DB_USER=mailu
DB_PW=my super secret password
DB_HOST=public.server.ipv4.address
DB_NAME=mailu

**Comment by Mikeatme** [comment]
@eduardocostabr 
Oh my goodness. You're right. This is a bit akward. It works just like a charm. 
Have a nice day <3

**Comment by Diman0** [comment]
I think it is a good idea to add this to the documentation. 

> I had the same issue.
> Solved it this way: created a configuration from setup.mailu.io to use sqlite.
> Then, started it, add my first user... and all those stuff (checked also if the TLS was working...)
> 
> After, I stopped the docker instance, and I've used this script I found on github to convert the file in /mailudata/data/main.db, this way:
> 
> script: https://github.com/vwbusguy/sqlite-to-mysql/blob/master/python/sqlite3-to-mysql.py
> 
> sqlite3 main.db .dump | ./sqlite3-to-mysql.py -u mailu -p passwordhere -d mailu > ./file.sql
> 
> Then, I removed all the part of granting permission to the user (already done it beforehand),
> and changed the order of two tables in the sql file (not so sure now, but I think the first was domain and the seccond user) because of some key.
> 
> Then, I've changed the .env file to use my mysql instance.
> 
> #DB_FLAVOR=sqlite
> DB_FLAVOR=mysql
> DB_USER=mailu
> DB_PW=password
> DB_HOST=10.1.1.3
> DB_NAME=mailu
> 
> Then removed the .db stuff from sqlite, changed some data in sql to be sure what database I am using, and so far (two hours hahaha) its working.

**Comment by Diman0** [comment]
With the new [config-export](https://mailu.io/master/cli.html#config-export)/config-import tool. You can create a complete database dump in yml format and import it in the new postgresql/maria deployment.

It is already available on master and will be part of 1.9. Basically you do:
1. On your existing sqlite deployment create the export
docker-compose exec admin flask mailu config-export ....
2. Stop you sqlite deployment.
3. Via setup.mailu.io create your new docker-compose.yml and mailu.env file for the different database system.
4. Start the new deployment.
5. Import the configuration
docker-compose exec admin flask mailu config-import ....
