### ISSUE TITLE
Nginx Container keeps crashing

### ISSUE THREAD

**Issue by PascalKu** [Mailu/Mailu#1041]
Hey there,

my front mailu nginx container keeps crashing from beginning.

Logs:

> front_1_4c6574f54aa2 | nginx: [emerg] invalid number of arguments in "location" directive in /etc/nginx/nginx.conf:85
>mailu_front_1_4c6574f54aa2 exited with code 1

**Comment by PascalKu** [comment]
Dont know but setting a parameter in mailu.env fixed it... Just added /webmail to an empty line.

**Comment by pirate** [comment]
For anyone else finding this via google, the offending lines to fix are:
```ini
###################################
# Web settings
###################################

# Path to redirect / to
WEBROOT_REDIRECT=/webmail

# Path to the admin interface if enabled
WEB_ADMIN=/admin

# Path to the webmail if enabled
WEB_WEBMAIL=/webmail
```
If any of those are empty they will need to be filled in.
