### ISSUE TITLE
Some Errors with DNS

### ISSUE THREAD

**Issue by w3hr** [Mailu/Mailu#1046]
Im using Mailu and used the "Generate Domain Keys" function to use DKIM and DMARC. I Added this to my Domains records but google says that they cannot validate the signature and it will land in spawn folder.

i got the following errors:

1. temperror (no key for signature)
2. <ip> is neither permitted nor denied by best guess record for domain of user@example-domain.de

and also DKIM: | 'FAIL' mit Domain domain.de

how can i fix this ?

**Comment by kaiyou** [comment]
Could you check your dkim using `dig` and provide some feedback?

**Comment by kaiyou** [comment]
Closing as stale
