### ISSUE TITLE
"Operation timed out" when sending email to external address

### ISSUE THREAD

**Issue by diwangs** [Mailu/Mailu#1047]
Hello folks,

I recently had a Mailu instance deployed on GCP. Everything (webmail, admin ui, HTTPS, receiving email, etc.) work except sending emails to my gmail and outlook account. 

To be clear, I can successfully send email to another address in my domain (me@mydomain.me -> anotherme@mydomain.me) but not to external address.

When I look at my SMTP log, this is what's written
```
smtp_1       | postfix/smtp[286]: connect to alt1.gmail-smtp-in.l.google.com[209.85.144.27]:25: Operation timed out
smtp_1       | postfix/smtp[286]: connect to alt1.gmail-smtp-in.l.google.com[2607:f8b0:400d:c0e::1a]:25: Address not available
smtp_1       | postfix/smtp[286]: connect to alt2.gmail-smtp-in.l.google.com[2607:f8b0:400c:c06::1b]:25: Address not available
smtp_1       | postfix/smtp[286]: AC08FFEB14: to=<mygmail@gmail.com>, relay=none, delay=580, delays=520/0.06/60/0, dsn=4.4.1, status=deferred (connect to alt2.gmail-smtp-in.l.google.com[2607:f8b0:400c:c06::1b]:25: Address not available)
```

I left the IPv6 address blank in my `mailu.env`, so I think that's why the IPv6 SMTP address says "Address not available". But I don't fully understand why the IPv4 SMTP says "Operation timed out".

There's an issue with similar symptoms (#712), and GCP does block port 25, but I already mapped the docker's port 25 to port 26 in my VM, so that shouldn't be an issue.
```
mailu mailu # netstat -lntu
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
tcp6       0      0 :::443                  :::*                    LISTEN     
tcp6       0      0 :::993                  :::*                    LISTEN     
tcp6       0      0 :::995                  :::*                    LISTEN     
tcp6       0      0 :::587                  :::*                    LISTEN     
tcp6       0      0 :::110                  :::*                    LISTEN     
tcp6       0      0 :::143                  :::*                    LISTEN     
tcp6       0      0 :::80                   :::*                    LISTEN     
tcp6       0      0 :::465                  :::*                    LISTEN     
tcp6       0      0 :::22                   :::*                    LISTEN     
tcp6       0      0 :::26                   :::*                    LISTEN
```
---
I'm using CoreOS and all traffic is allowed on all ports (no firewall)

Can somebody shed some light to this problem? Thanks!

**Comment by kaiyou** [comment]
Mapping the port in Docker is meant for incoming connections. Outgoing connections will still fail and there is really no solution if your provider blocks port 25.

You need to be able to reach other MX over TCP/25 for sending mail.

**Comment by luatnd** [comment]
I does not use GCP, tried a vultr VPS instead and port 25 is not blocked:
```
$ netstat -lntu
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
tcp        0      0 207.148.71.68:993       0.0.0.0:*               LISTEN     
tcp        0      0 207.148.71.68:995       0.0.0.0:*               LISTEN     
tcp        0      0 207.148.71.68:587       0.0.0.0:*               LISTEN     
tcp        0      0 207.148.71.68:110       0.0.0.0:*               LISTEN     
tcp        0      0 207.148.71.68:143       0.0.0.0:*               LISTEN     
tcp        0      0 207.148.71.68:80        0.0.0.0:*               LISTEN     
tcp        0      0 207.148.71.68:465       0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN     
tcp        0      0 207.148.71.68:25        0.0.0.0:*               LISTEN     
tcp        0      0 207.148.71.68:443       0.0.0.0:*               LISTEN     
tcp6       0      0 :::22                   :::*                    LISTEN     
udp        0      0 127.0.0.53:53           0.0.0.0:*                          
udp        0      0 207.148.71.68:68        0.0.0.0:*  
```

```
$ dc logs -f  smtp

postfix/smtp[716]: connect to mx.yandex.ru[77.88.21.249]:25: Operation timed out
postfix/smtp[716]: connect to mx.yandex.ru[2a02:6b8::311]:25: Address not available
postfix/smtp[716]: D0F9218020A: to=<***@yandex.com>, relay=none, delay=32, delays=0.43/0.07/31/0, dsn=4.4.1, status=deferred (connect to mx.yandex.ru[2a02:6b8::311]:25: Address not available)
postfix/smtp[692]: connect to mail.***.fun[207.148.71.68]:25: Operation timed out
postfix/smtp[692]: CEA86180217: to=<double-bounce@mail.***.fun>, orig_to=<SRS0=cdQl=2M=mail.***.fun=double-bounce@***.fun>, relay=none, delay=30, delays=0.05/0.03/30/0, dsn=4.4.1, status=deferred (connect to mail.***.fun[207.148.71.68]:25: Operation timed out)
```

Can anyone point this out?

**Comment by sekroots** [comment]
Hello, 

is there any solution to this issue? 

bash-5.0# postqueue -p
postqueue: warning: Mail system is down -- accessing queue directly
-Queue ID- --Size-- ----Arrival Time---- -Sender/Recipient-------
A4C3CC01969 573 Mon Feb 20 16:53:24 [r.santana@XXX.cloud](mailto:r.santana@XXX.cloud)
(connect to alt2.gmail-smtp-in.l.google.com[2a00:1450:4025:c03::1b]:25: Address not available)
[rxx@gmail.com](mailto:rxx@gmail.com)

A5D87C017F5 596 Sat Feb 25 14:26:57 [devops@XXX.cloud](mailto:devops@XXX.cloud)
(connect to alt4.gmail-smtp-in.l.google.com[74.125.200.26]:25: Operation timed out)
[rxx@gmail.com](mailto:rxx@gmail.com)

47072C018F7 801 Sat Feb 25 14:56:52 [devops@XXX.cloud](mailto:devops@XXX.cloud)
(connect to alt4.gmail-smtp-in.l.google.com[74.125.200.27]:25: Operation timed out)
[rixx@gmail.com](mailto:rixx@gmail.com)

18DE1C017FE 577 Sat Feb 25 14:33:46 [devops@XXX.cloud](mailto:devops@XXX.cloud)
(connect to alt4.gmail-smtp-in.l.google.com[74.125.200.26]:25: Operation timed out)
[ricardoaugusto.sek@gmail.com](mailto:ricardoaugusto.sek@gmail.com)
(connect to aspmx3.googlemail.com[142.251.9.27]:25: Operation timed out)
[r.souza@XXX.group](mailto:r.souza@XXX.group)

8E59FC01963 565 Mon Feb 20 14:55:52 [me@mail.XXX.cloud](mailto:me@mail.XXX.cloud)
(connect to alt2.aspmx.l.google.com[2a00:1450:4025:c03::1a]:25: Address not available)
[r.souza@XXX.GROUP](mailto:r.souza@XXX.GROUP)
(delivery temporarily suspended: connect to alt2.gmail-smtp-in.l.google.com[2a00:1450:4025:c03::1b]:25: Address not available)
[rxx@gmail.com](mailto:rxx@gmail.com)

01774C018A2 570 Mon Feb 20 14:51:05 [devops@XXX.cloud](mailto:devops@XXX.cloud)
(connect to alt2.gmail-smtp-in.l.google.com[2a00:1450:4025:c03::1b]:25: Address not available)
[rxx.sek@gmail.com](mailto:rxx.sek@gmail.com)
(connect to alt1.aspmx.l.google.com[2a00:1450:4013:c16::1a]:25: Address not available)
[r.souza@XXX.GROUP](mailto:r.souza@XXX.GROUP)
