### ISSUE TITLE
Send mail from printer without TLS

### ISSUE THREAD

**Issue by blogwebpl** [Mailu/Mailu#1054]
My printer does not support TLS. How can I send mail from printer on port 25 using Mailu ?

**Comment by kaiyou** [comment]
You could add your printers address to the trusted network list, thus it will be able to use Mailu as an open relay. Be wary of the consequences of opening this.

**Comment by kaiyou** [comment]
Did this solve your issue?

**Comment by blogwebpl** [comment]
Yes. I added my printers address to the trusted network list.
