### ISSUE TITLE
Max Quota per user

### ISSUE THREAD

**Issue by fabiorauber** [Mailu/Mailu#106]
It would be nice if Mailu implemented a Max Quota field by domain name, which could be only changed by an Administrator, bounding the manager to only set quota up to this maximum. A similar feture is found in ViMbAdmin (http://www.vimbadmin.net/).

**Comment by kaiyou** [comment]
This sounds easy enough to implement, thanks for the idea!

**Comment by fabiorauber** [comment]
Humm, let's see:

- If the administrator lowers the quota, I think the quota already set before should be maintained, but increasing it should be forbidden.
- Like the other question, existing settings should be maintained. The Max should only apply to new quotas.
- I think the default should be no Max Quota (infinite quota).

**Comment by kaiyou** [comment]
Almost implemented on my side. I will push in a couple days if I find some time.

**Comment by radoslav-stefanov** [comment]
I know this is closed, but it still might be useful to some people considering this page comes up on Google.
You can implement rate limiting by integrating some external service like policyd and override main postfix config.
It would be great if someone can add this to mailu though.
