### ISSUE TITLE
NGINX: Announce SMTP AUTH capabilities 

### ISSUE THREAD

**Issue by atl285** [Mailu/Mailu#1060]
Some clients need to get information about SMTP AUTH support. Mailu doesn't offer this to clients. You can see it, if you connect via Telnet to Port 587, for example:

```
root@4a57a68ae91d:/# telnet mail.test-system.com 587
Trying xxx.xxx.xxx.xxx...
Connected to mail.test-system.com.
Escape character is '^]'.
220 mail.test-system.com ESMTP ready
EHLO test
250-mail.test-system.com
250 STARTTLS
```

The client expect something like this `250-AUTH PLAIN` from postfix:

```
root@4a57a68ae91d:/# telnet mail.test-system.com 587
Trying xxx.xxx.xxx.xxx...
Connected to mail.test-system.com.
Escape character is '^]'.
220 mail.test-system.com ESMTP ready
EHLO test
250-mail.test-system.com
250-AUTH PLAIN
250 STARTTLS
```

In the Mailu setup this can be delivered from the NGINX proxy configuration. To get this, please insert a line with `smtp_capabilities ` within the server block. For server listen on port 587 the example is shown here:

```
    server {
      listen 587;
      listen [::]:587;

      starttls only;

      protocol smtp;
      smtp_capabilities "AUTH PLAIN";
      smtp_auth plain;
    }
```

...or for server listen on 465 here:

```
    server {
      listen 465 ssl;
      listen [::]:465 ssl;
      protocol smtp;
      smtp_capabilities "AUTH PLAIN LOGIN";
      smtp_auth plain login;
    }
```

**Comment by kaiyou** [comment]
Indeed we should expose at least the minimum for authentication. I do not have means to write the code, so could add these in a PR?

**Comment by HorayNarea** [comment]
This is not needed, see nginx documentation: https://nginx.org/en/docs/mail/ngx_mail_smtp_module.html#smtp_capabilities

> The authentication methods specified in the smtp_auth directive […] are automatically added to this list […]

The reason you are not seeing these capabilities in your test with telnet ist because they only get send once a STARTTLS session is initiated, this is the standard way to enforce TLS before sending passwords

**Comment by kaiyou** [comment]
My bad then, thanks for correcting

**Comment by atl285** [comment]
> The reason you are not seeing these capabilities in your test with telnet ist because they only get send once a STARTTLS session is initiated, this is the standard way to enforce TLS before sending passwords

You're right. I thought, that normally STARTTLS doesn't enforce TLS before sending. It's like telling the client to prefer TLS encryption.

I've done some more tests and found out, that the most problems are related to the ciphers. The problematic java code required the offer of `250-AUTH ...` extension to send the authentication credentials. But it stuck in the handshake. So there was no chance to see the extension offer in TLS connection. This is fixed now. Thanks for your time.

I'm not the expert in SMTP, but all the readings about configurations of postfix and so, bought me to another question: You noticed that port 25 should only used for server to server communication. But it seems that many clients and implementations use it als fallback port. So wouldn't it be a security benefit to add PLAIN authentication to port 25? The configuration would be as following:

```
    # SMTP is always enabled, to avoid losing emails when TLS is failing
    server {
      listen 25;
      listen [::]:25;

      ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
      ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:ECDHE-RSA-AES128-GCM-SHA256:AES256+EECDH:DHE-RSA-AES128-GCM-SHA256:AES256+EDH
      starttls on;

      protocol smtp;
      smtp_auth none plain;
    }
```
So it can used additional to send mails via (START)TLS encryption without any restrictions. Or see you some security issues?

**Comment by kaiyou** [comment]
It is a design choice not to support authentication on port 25. We hope this way, less users will send their credentials in plaintext by mistake.

**Comment by atl285** [comment]
Ok, thanks.
