### ISSUE TITLE
send email to gmail from my server?

### ISSUE THREAD

**Issue by Jiangshan00001** [Mailu/Mailu#1061]
could the postfix be configured to send mail using  587 port?

**Comment by kaiyou** [comment]
Postfix is meant to send email to other MTA. The SMTP standard is that MTA accept incoming connections on port 25/TCP.

Are you thinking of a specific use case where an MTA does not support delivery on port 25?

**Comment by Jiangshan00001** [comment]
how to support 465 port?
because for some mail server, 25 port is not supported.

**Comment by kaiyou** [comment]
Do you have any example? I have never crossed a server that did not accept MTA traffic over 25/TCP. I would not even know how they signal this given that MX does not include ports, as opposed to SRV.

**Comment by diwangs** [comment]
I think he's talking about his port 25, not the receiving end. Similar to #1047

**Comment by SimplySynced** [comment]
I'm also having this same issue.  I think this may be the ISP blocking 25 coming back on that port.  I know when I checked mine using port checker I have a response saying it is open.  However I get the same issue trying to send to gmail accounts.   i can send to other accounts created in the org.  The outgoing is trying to use 25.  I read a couple things about trying to use 587 enabling submission within postfix itself but that didn't work.  I've also updated the server exposed to use smtps as well.  still when it tries to send out it always tries to reach google on port 25.  Is this something that can be changed or is this a case where a smtp relay will be needed?

**Comment by diwangs** [comment]
CMIIW, but I think there's no way to change that and the more preferable solution is just to use a relay service like Mailgun or Sendgrid.

Fortunately, the current master branch already had this capability (#958), you just have to supply it with the correct RELAYHOST, RELAYUSER, and RELAYPASSWORD in your mailu.env

**Comment by SimplySynced** [comment]
I'll try just using one of those then. I did speak withmy ISP and they stated its not blocked and can you see me shows its not blocked.

**Comment by SimplySynced** [comment]
I've added sendgrid relayhost user and password and still not giving me a send.  I've gone and tried to manually add settings I found on sendgrid into the main.cf files but it still doesn't send.

**Comment by kaiyou** [comment]
There are two different issues being mentioned here: how you receive and how you send emails. Receiving is done by having other mails severs connecting to your port 25 and sending and is done by having yours connecting to other main servers port 25.

Any basic provide that offers you a public IP for your server has no reason to block incoming connections, which is what portchecker and others are checking. This accounts for incoming emails only.

Outgoing emails use outgoing connections to port 25, which many isp block in an effort to avoid spam coming from infected machines among their clients.

If this is the case, first try to have your ISP lift it. Then outgoing emails will work natively. If you cannot, then using a relay is probably your only chance. You should be aware that antispam settings can be more tricky in that setup, plus your relay provider can then read all your outgoing emails.

**Comment by kaiyou** [comment]
That said, Mailu currently only supports connecting to a relay host on port 25, so you would first need to provide support for connection on port 465 or 587 and a relay service that supports this.

**Comment by hcderaad** [comment]
Any ETA for that fix (being able to actually use relayhost/user/password) to reach a released version of Mailu instead of requiring an update to the master dev branch? This is my main blocking issue for finally moving to mailu with my primary mailserver. If there is anything to test/verify, please respond and I'd be happy to take a look at it and perform tests/debugging.

**Comment by kaiyou** [comment]
We should be discussing publishing a new release branch in the coming days or weeks now, the blocking prs are merged :)

**Comment by kaiyou** [comment]
Is there anything to add here?

**Comment by sekroots** [comment]
Any solution to this issue?

bash-5.0# postqueue  -p
postqueue: warning: Mail system is down -- accessing queue directly
-Queue ID-  --Size-- ----Arrival Time---- -Sender/Recipient-------
A4C3CC01969      573 Mon Feb 20 16:53:24  r.santana@XXX.cloud
(connect to alt2.gmail-smtp-in.l.google.com[2a00:1450:4025:c03::1b]:25: Address not available)
                                         rxx@gmail.com

A5D87C017F5      596 Sat Feb 25 14:26:57  devops@XXX.cloud
(connect to alt4.gmail-smtp-in.l.google.com[74.125.200.26]:25: Operation timed out)
                                         rxx@gmail.com

47072C018F7      801 Sat Feb 25 14:56:52  devops@XXX.cloud
(connect to alt4.gmail-smtp-in.l.google.com[74.125.200.27]:25: Operation timed out)
                                         rixx@gmail.com

18DE1C017FE      577 Sat Feb 25 14:33:46  devops@XXX.cloud
(connect to alt4.gmail-smtp-in.l.google.com[74.125.200.26]:25: Operation timed out)
                                         ricardoaugusto.sek@gmail.com
      (connect to aspmx3.googlemail.com[142.251.9.27]:25: Operation timed out)
                                         r.souza@XXX.group

8E59FC01963      565 Mon Feb 20 14:55:52  me@mail.XXX.cloud
(connect to alt2.aspmx.l.google.com[2a00:1450:4025:c03::1a]:25: Address not available)
                                         r.souza@XXX.GROUP
(delivery temporarily suspended: connect to alt2.gmail-smtp-in.l.google.com[2a00:1450:4025:c03::1b]:25: Address not available)
                                         rxx@gmail.com

01774C018A2      570 Mon Feb 20 14:51:05  devops@XXX.cloud
(connect to alt2.gmail-smtp-in.l.google.com[2a00:1450:4025:c03::1b]:25: Address not available)
                                         rxx.sek@gmail.com
(connect to alt1.aspmx.l.google.com[2a00:1450:4013:c16::1a]:25: Address not available)
                                         r.souza@XXX.GROUP
