### ISSUE TITLE
Welcome e-mail

### ISSUE THREAD

**Issue by fabiorauber** [Mailu/Mailu#107]
Another useful feature for Mailu would be a warm welcome e-mail, to be sent to new users created with the admin system. It could be customized by the Administrator (or Domain Manager, maybe), and could be optional at the time of the user creation.

**Comment by kaiyou** [comment]
Great idea indeed. How it is configured is another question.
If a global welcome message may be configured, then either it will be configured in the ``.env`` file, or we need a dedicated configuration storage.

If we go for the dedicated configuration storage, then what should we store there exactly? how should we ensure that configuration values are properly documented and migrated when required?

I like the idea but implications are reaching quite far in Mailu's design and I would prefer to discuss this further as part of the architecture change planned for release 1.5.

**Comment by fabiorauber** [comment]
I thought it could be stored in the Admin database, and sent out when the user is created within the interface. Is that possible?

**Comment by kaiyou** [comment]
It is indeed possible. The question I raised is: how should it be stored in the admin database. We do not have anything to store global configuration yet. And the question is more complicated that it seems (how should we initialize values, how should handle format changes, etc.)

**Comment by hadifarnoud** [comment]
I think the only values needed is IMAP and SMTP settings and username.
