### ISSUE TITLE
How to migrate all my emails from CPanel to Mailu

### ISSUE THREAD

**Issue by blueray453** [Mailu/Mailu#1072]
When I asked the prospective providers to transfer my emails, they said and I quote -

> We offer free data migration service if you are using cPanel control panel with your current hosting company (most companies use cPanel, such as GoDaddy/HostGator/etc) and are planning to purchase any of our cPanel packages (Linux Shared, VPS/Cloud with cPanel control panel).

I have CPanel in my current hosting, however I am feeling a little locked down as the prospective provider is saying that I must have CPanel. 

Now, I want to migrate all my CPanel email to Mailu (installed in a VPS). How can I do that?

**Comment by kaiyou** [comment]
Sorry about the delay. Do you have any export feature from cPanel? If not it might prove somehow difficult if you have many accounts.

If you do or if you have very few accounts, copy/pasting users to Mailu or importing a CSV should be easy. Then it is a matter of syncing the mailboxes, probably using imapsync.

**Comment by cupcakearmy** [comment]
```
E-mail account usernames and passwords are stored in files named passwd and shadow in the following directory structure:

/$HOME/$USER/etc/$DOMAIN/

where:
    $HOME is the actual account home directory;
    $USER is the cPanel account user, and;
    $DOMAIN is the actual domain in question.

Passwords are stored in shadow in this directory in salted MD5 format. There is no way to make them human-readable, but the file can be copied and the passwords will still work.

The actual mailboxes are stored in the following format:

/$HOME/$USER/mail/$DOMAIN/$MAILBOX

where $MAILBOX is the name of the mailbox user as defined in cPanel. $MAILBOX is a directory containing all of the files related to the actual mail account data.

You can copy the files and directories from the etc and mail directories from one cPanel account to another, or from one server to another. Make sure to apply the ownerships of the destination account to the files and directories. Also, make sure to move the following files out of the way before logging into cPanel on the destination account:

/$HOME/$USER/.cpanel/email_accounts.cache
/$HOME/$USER/.cpanel/email_accounts.yaml

These files will automatically be created when you log into cPanel.
```

This is what cpanel tells me. Is there any updates on this?

Thanks :)

**Comment by cupcakearmy** [comment]
If anyone is still searching: this was my solution for migrating accounts at least

https://mailu.io/1.7/cli.html#config-update

**Comment by kaiyou** [comment]
If you have any more details, we could create a migration section in the docs

**Comment by cupcakearmy** [comment]
I talked to some peeps in matrix and I was also able to migrate the dovecot maildir from cpanel to mailu. I just suggested there that I'd be happy to write a small migration guide for you guys in the docs :)

https://matrix.to/#/!RJFCFtixHgPhzacdhW:tedomum.net/$1578669540413925qPVHp:matrix.org?via=matrix.org&via=ring0.de

**Comment by Nebukadneza** [comment]
Hi There,

The `Mailu`-Project is currently in a bit of a bind! We are short on man-power, and we need to judge if it is possible for us to put in some work on this issue.

To help with that, we are currently trying to find out which issues are actively keeping users from using `Mailu`, which issues have someone who want to work on them — and which issues may be less important. These a less important ones could be discarded for the time being, until the project is in a more stable and regular state once again.

In order for us to better assess this, it would be helpful if you could put a **reaction on this post** (use the :smiley: icon to the top-right).
- 👍️ if you **need this** to be able to use Mailu. Ideally, you’d also be able to test this on your installation, and provide feedback …
- 🎉 if you find it a **nice bonus**, but no deal-breaker
- 🚀 if you want to **work on it yourself**!
We want to keep this **voting open for 2 weeks** from now, so please help out!

**Comment by Diman0** [comment]
Hi There,

we see this issue had only little attention 😟. As much as it pains us: In order to get the current issues a bit more manageable for us, we decided to close it. 👋👋

We hope that no one feels offended by doing so. Should the issue get really pressing in the future, please feel free to re-open it.

Thank you for your patience and understanding, 🙇
- Your Mailu Team

p.s. migrating email from another email server is not really in scope for mailu. However for any other people who find this issue, a very easy to use tool is imapsync. https://github.com/imapsync/imapsync
It allows to migrate any email from any email server to another email server via IMAP protocol
