### ISSUE TITLE
Add possibility to REJECT emails matching an alias

### ISSUE THREAD

**Issue by sbias** [Mailu/Mailu#1077]
Would be nice to be able to add an alias to be rejected with a reason. Currently you can add an alias without any destination, but that result in a "450 4.1.1 <xxx@xxx>: Recipient address rejected: unverified address: Address lookup failure" soft bounce. I'd like to answer with a hard 5xx error.

**Comment by HorayNarea** [comment]
Could you elaborate what problem you are trying to solve by that?

**Comment by sbias** [comment]
I have a few catch-all domains running, but - of cause - some of the addresses are listed in some spammer-lists already. Before i switched to mailu i added this in the recipient_access with REJECT which solved my problem. Now i try to find a way to replicate this in mailu.

**Comment by Nebukadneza** [comment]
Hi There,

The `Mailu`-Project is currently in a bit of a bind! We are short on man-power, and we need to judge if it is possible for us to put in some work on this issue.

To help with that, we are currently trying to find out which issues are actively keeping users from using `Mailu`, which issues have someone who want to work on them — and which issues may be less important. These a less important ones could be discarded for the time being, until the project is in a more stable and regular state once again.

In order for us to better assess this, it would be helpful if you could put a **reaction on this post** (use the :smiley: icon to the top-right).
- 👍️ if you **need this** to be able to use Mailu. Ideally, you’d also be able to test this on your installation, and provide feedback …
- 🎉 if you find it a **nice bonus**, but no deal-breaker
- 🚀 if you want to **work on it yourself**!
We want to keep this **voting open for 2 weeks** from now, so please help out!

**Comment by sbias** [comment]
- keep stale bot happy - :(

**Comment by Diman0** [comment]
I also do not understand what you want to achieve. However the multimap filter from rspamd might be useful. 
See for more information https://mailu.io/master/antispam.html#how-can-i-block-emails-from-a-domain

Do you think this filter is useful?

**Comment by ghostwheel42** [comment]
> I also do not understand what you want to achieve.

Hi, sbias wants to reject a single recipient address nope@example.com while using a catch-all *@example.com
Rejecting an address can be achieved by adding "error:no such user" as nexthop in postifix' transport table.
I think it would be a nice feature to block some addresses while still using the catch-all for everything else.

Alex

**Comment by ghostwheel42** [comment]
@sbias: When starting to implement the 5xx reject I tested the "empty alias config" you mentioned.
my mailu setup (master) already returns a 5.1.1 error in this case. So it seems there's nothing to do anymore?

This is my setup:
```
disabled@0v.de -> *empty*
%@0v.de -> foo@0v.de
```

The mail to disabled@0v.de is rejected like this:
```
<disabled@0v.de>: host *redacted* said: 550 5.1.1
   <disabled@0v.de>: Recipient address rejected: User unknown in virtual
   mailbox table (in reply to RCPT TO command)
```
