### ISSUE TITLE
Architecture of the central container

### ISSUE THREAD

**Issue by kaiyou** [Mailu/Mailu#108]
Some changes are ongoing regarding the overall architecture and it feels necessary to expose some ideas and see if anyone has a better solution.

From the latest discussions, it has arised that:
- the monolythic admin interface is hard to maintain and audit;
- we need a way to launch tasks, both on-demand and scheduled;
- we need a place to centralize critical concerns like managing Docker operations.

From what I gather, what seem like a best long-term option is:
- a Web-based REST API in the admin container, no UI or anything fancy, maybe a CLI;
- a Celery worker with all Docker-related tasks in a separate container, handling certificates, restarts, updates, etc. accessing data using the API ;
- or a Apscheduler worker inside the API ;
- a static admin interface served by the frontend or a third container, talking to the REST API;
- a Redis broker for tasks;
- Dovecot and Postfix querying the API instead of the database ;
- Maybe an authentication socket for Dovecot to allow for more authentication sources (external source) ;
- the same SQLite database for data, which could then be moved to anything else compatible with SQLAlchemy.

One remaining question about accessing the API easily. I suggest that a wheel is prepared at build time and served through the API for clients to install dynamically upon startup. This will ensure that code is kept in a single place but all clients share the same model and API reference.

**Comment by kaiyou** [comment]
Also, more and more configuration items are being exposed. The question is raised (see #107 for instance) about the storage system for these configuration items.

Some will still need to be stored in the ``.env`` file for conainers to access them easily. Or containers could load them dynamically using the API.

Question is: how complex should that system be in order to remain flexible while not being over-engineered too much (I would prefer not to create another bloated e-mail distribution).

**Comment by kaiyou** [comment]
I narrowed down the choice of framework for the central API to these three. Any feedback is welcome:
- https://github.com/nicolaiarocci/eve/
- https://github.com/timothycrosley/hug
- http://www.django-rest-framework.org/

**Comment by kaiyou** [comment]
Given the probably breaking changes that this will cause, I am renaming release ``1.5`` to ``2.0`` and will later create a separate ``1.5`` for remaining features and bugs.

**Comment by abnerjacobsen** [comment]
Have you looked at https://github.com/zalando/connexion ? It is based on Flask, works with Python 2.7 / 3.x and uses Swagger for documentation, testing, automatic parameter validation and other useful features.

I am using it in a project similar to Mailu but for site hosting (source code soon to be released) and I am very satisfied with the features offered by Connexion.

**Comment by kaiyou** [comment]
I will have a look, I did not consider it at first due to the significantly smaller community. Thank you for the feedback.

**Comment by kaiyou** [comment]
This is by far outdated
