### ISSUE TITLE
Deliver to gmail w/o being Spam

### ISSUE THREAD

**Issue by boldt** [Mailu/Mailu#1081]
I configured a test domain with a new server and mailu. Now, I'm trying to deliver mail to gmail, such they are not classified as spam. I copied all configurations provided by mailu to my DNS:

* SPF
* DKIM
* DMARC

Additionally I configured the Reverse DNS (PTR).

## Test with http://www.appmaildev.com/de/dkim

All checks passed:

![Screenshot_20190724-073251~2](https://user-images.githubusercontent.com/750793/61769355-48645c00-adea-11e9-9116-f410eb63248c.png)

## Test with https://www.mail-tester.com

All checks passed:

![2019-07-24 08_02_33-Ergebnis des Spam-Tests](https://user-images.githubusercontent.com/750793/61769373-55814b00-adea-11e9-865a-224ce1129685.png)
## Result in gmail

It is classified as spam: Gmail said, it' similar to previous spam mails, which is the default message for all spam mails.

![2019-07-24 08_10_14-Clipboard](https://user-images.githubusercontent.com/750793/61769460-a002c780-adea-11e9-9020-2b79c784bc22.png)

**Comment by kaiyou** [comment]
This could be related to so many issues:
- you actually sending spam (even for testing) to gmail
- your mail topic or mail body being too generic and identical to actual spam
- attachment if any
- your IP address having bad reputation from external reputation bases (check Talos for instance)

**Comment by boldt** [comment]
* I tried different types of mails, not just simple test mails, all w/o attachments. Thus, it cannot be spam and cannot be to generic.
* Talos says everything is fine

I'm running out of any idea. Do you have further ideas?

**Comment by liquidat** [comment]
Have you checked your status in [Google postmaster](https://postmaster.google.com/)? That might give you a better idea of what is going on.

**Comment by boldt** [comment]
Because it is just a test domain, Google postmaster does not have enough information to report anything yet.

Yesterday I send another test mail, which again was classified as spam. Since I configured rua and ruf for the DMARC record, I got a DMARC mail from google. The [DMARC Report Analyer](https://mxtoolbox.com/DmarcReportAnalyzer.aspx) shows, that SPF, DKIM and DMARC are passed:

![Bildschirmfoto von 2019-08-07 19-01-43](https://user-images.githubusercontent.com/750793/62642400-ebb68480-b945-11e9-88a0-323de9e34b7d.png)

I'm still open for any idea.

**Comment by liquidat** [comment]
Not sure if something is visible in there - but how about pasting the received headers to a pastebin/gist of your choice and linking it here?

**Comment by boldt** [comment]
I tested it again today, et voila, my mails are not filtered as junk any more.

**Just an idea**: My first test-mail to google had a wrong DKIM configuration. Thus, maybe google blacklisted my server for some time and not its done...

**Comment by boldt** [comment]
I just realized, that I had a typo in my PTR record 😳

**Comment by kaiyou** [comment]
Does fixing the ptr fix the delivery?

**Comment by boldt** [comment]
It did very well.
Now i switched the EHLO and PTR domain, and they are marked as spam again.

**Comment by kaiyou** [comment]
Which is normal, right? Is there any issue left with Mailu?

**Comment by boldt** [comment]
It's not really "normal" (I also updated all DNS entries, etc).

Anyway, this seems to be a Google issue, since I can deliver to other big providers w/o any problem. So, no issue with mailu.
