### ISSUE TITLE
Not able to use addtional paramaters for command line

### ISSUE THREAD

**Issue by HarshulJethwani** [Mailu/Mailu#1095]
Usage: flask mailu [OPTIONS] COMMAND [ARGS]...

  Mailu command line

Options:
  --help  Show this message and exit.

Commands:
  admin          Create an admin user
  advertise      Advertise this server against statistic services.
  alias          Create an alias
  alias-delete   delete alias
  config-update  sync configuration with data from YAML-formatted stdin
  domain
  setlimits      Set domain limits
  setmanager     Make a user manager of a domain
  user           Create a user
  user-delete    delete user
  user-import    Import a user along with password hash.

It doesn't show the additional parameters such as:

    comment
    quota_bytes
    global_admin
    enable_imap
    enable_pop
    forward_enabled
    forward_destination
    reply_enabled
    reply_subject
    reply_body
    displayed_name
    spam_enabled
    spam_threshold

**Comment by kaiyou** [comment]
Additional parameters will be shown when using `--help` on a specific command. This is Python click behavior.
