### ISSUE TITLE
Fetchmail cannot write to database

### ISSUE THREAD

**Issue by kaiyou** [Mailu/Mailu#110]
Since the fetchmail user was changed to ``fetchmail``, it cannot write to database anymore.
It would be simpler to just use ``root`` there, the database is exposed but we do not have much of a choice for now.

**Comment by kaiyou** [comment]
Issue was introduced in commit https://github.com/Mailu/Mailu/commit/42cfc50bd87f93a56c8078c2cedd6a007f3d40f7

**Comment by pe2mbs** [comment]
This is the traceback 

Traceback (most recent call last):
  File "/fetchmail.py", line 84, in <module>
    run(connection, cursor)
  File "/fetchmail.py", line 74, in run
    """, (error_message.split("\n")[0], user_email))
sqlite3.OperationalError: unable to open database file

**Comment by pe2mbs** [comment]
And another traceback, it seems to be related to the permissions of the main.db the file is owned by root and had 0644 i changed it now to 0664 to see if the problem disapprears
 
Traceback (most recent call last):
  File "/fetchmail.py", line 84, in <module>
    run(connection, cursor)
  File "/fetchmail.py", line 74, in run
    """, (error_message.split("\n")[0], user_email))
sqlite3.OperationalError: attempt to write a readonly database

**Comment by pe2mbs** [comment]
changing the attributes didn't fix it
