### ISSUE TITLE
Certificates not Issuing 

### ISSUE THREAD

**Issue by jbonnett92** [Mailu/Mailu#1100]
Hi,
I am trying to install the mail server and the certificate manager reports that there is a order created although I never get a certificate issued to me.

All pods have started successfully.

I have checked that the certificate manager is working by using it in another namespace / program. I did get a certificate issued.

**Comment by kaiyou** [comment]
Could you specify which version you are running and provide some logs? I am not a k8s expert but you currently give very little to go with

**Comment by kaiyou** [comment]
Closing as stale, feel free to reopen
