### ISSUE TITLE
Send Email from anywhere

### ISSUE THREAD

**Issue by RexProg** [Mailu/Mailu#1103]
how can i config mailu to send email from any client?

**Comment by kaiyou** [comment]
Mailu is meant for being able to sent mail from anywhere. Could you specify your requirements?

**Comment by RexProg** [comment]
I received the following message when trying to send an email
```
The server response was: 5.7.1
: Sender address rejected: Access denied
```

**Comment by kaiyou** [comment]
Were you authenticated while sending?

**Comment by RexProg** [comment]
![image](https://user-images.githubusercontent.com/23130739/62823385-721cd180-bba5-11e9-919a-2c88875092f7.png)
Yes
I use smtper.net for testing

**Comment by boldt** [comment]
Port 25 is to deliver/receive mail from other mail servers. Try port 465 with SSL/TLS (as shown in your screenshot). You can also try port 587 (with STARTTLS).

**Comment by RexProg** [comment]
port 587:
![image](https://user-images.githubusercontent.com/23130739/62824534-f034a480-bbb4-11e9-8d10-1835ee85f0d4.png)
port 465:
![image](https://user-images.githubusercontent.com/23130739/62824560-3c7fe480-bbb5-11e9-8792-9b5670d099b9.png)

**Comment by pirate** [comment]
@RexProg you may find my overrides setup useful here: https://github.com/Mailu/Mailu/issues/1096

**Comment by RexProg** [comment]
@pirate i create your overrides in /mailu/overrides and /mailu/data/overrides, then start docker again, but I still have that problem

**Comment by pirate** [comment]
Can you post the exact contents of your overrides here with the sensitive info redacted/replaced so we can verify it matches what you're actually trying to do.

**Comment by RexProg** [comment]
postfix.cf:
```
# Relatively lax restrictions on sending (only secure if all sasl users are trusted, do not use wit$
smtpd_relay_restrictions = permit_mynetworks, permit_sasl_authenticated, defer_unauth_destination
smtpd_sender_login_maps = pcre:/overrides/sender_logins, socketmap:unix:/tmp/podop.socket:senderlog$
sender_dependent_relayhost_maps = texthash:/overrides/relay_hosts
smtp_sasl_auth_enable = yes
smtp_sasl_security_options = noanonymous
smtp_sasl_password_maps = texthash:/overrides/sasl_passwd
```

sender_logins:
```
# Authorize only the admin@mydomain.com smtp user to send from any address on any domain
/.*/                                          admin@mydomain.app
# Authorize the admin@otherdomain.com user to send from any @otherdomain.com address
/.^*@mydomain.app/     admin@mydomain.app
```
relay_hosts:
```
# Any mail sent from @yetanotherdomain.com gets relayed via mailgun instead of being handled locally
@mydomain.app          [mail.mydomain.app]:587
```

**Comment by pirate** [comment]
So just to verify:
1. You are able to log into the admin GUI with the `admin@mydomain.app` account
2. You are able to log into the webmail interface / IMAP with the `admin@mydomain.app` username and password
3. You are able to log into SMTP with that same `admin@mydomain.app` username and password locally & remotely
4. You are able to send email from `admin@mydomain.app` once logged in via SMTP
5. You are **not** able to send email from other addresses when logged in via SMTP with `admin@mydomain.app`

Are all of those true? Or am I missing something?  If not, you'll have to get everything #1-#4 working before #5 will work.

**Comment by RexProg** [comment]
@pirate 
1.true
2.true
3.4.i log into smtp by telnet, is it enough?, what should I do? 
5.yes I can't

**Comment by pirate** [comment]
When you log in using SMTP via telnet, are you typing in your `admin@mydomain.app` username+password and authenticating, or are you just testing in client mode without typing in any credentials?  (If you you're not already using authentication, you can follow this guide to login with your password and we can test things from there https://fabianlee.org/2017/06/22/ubuntu-testing-authenticated-smtp-over-tlsssl/)

**Comment by kaiyou** [comment]
Seriously, overriding the conf is probably *not* the solution here. First question, @RexProg, what source mail address are you trying to send from? It looks like the same as the login. In that case, please ignore the overriding part, which will only allow unexpected behaviors on your setup: use those only if you want accounts to be able to impersonate other users.

Then, on port 465, it looks like your tester does not support TLS, only Srarttls. So I first suggest you test with another tool.

Finally on the authentication problem on port 587, it looks like your tool does not try to authenticate before passing submission commands. Again I would try with another tool.

**Comment by kaiyou** [comment]
@RexProg I had a look at your testing tool, it is an online tool, and you gave it your admin password. I would recommend using a local testing tool only, especially for admin accounts. In the present case I would recommend you quickly change your password in case the people managing smtper.net decide to use it.

@pirate, please refrain from recommending overrides or complex setups before we understand the issue properly. Here I am pretty sure that @RexProg is not trying to do any non standard impersonation, at least it does not seem so from the screenshots an messages.

**Comment by RexProg** [comment]
telenet works correctly from another server
but i still can't send email by smtper.net

**Comment by RexProg** [comment]
> Finally on the authentication problem on port 587, it looks like your tool does not try to authenticate before passing submission commands. Again I would try with another tool.
i use that tool to show you what i'm sending
i use system.net.mail.smtpclient in dotnet project that give me an error like smtper.net

>would recommend you quickly change your password
thank you for your advice

**Comment by kaiyou** [comment]
Could you post the .net code snippet and corresponding stack trace?

**Comment by RexProg** [comment]
![image](https://user-images.githubusercontent.com/23130739/62833418-a5b63500-bc53-11e9-9852-dcaf453f8691.png)

**Comment by kaiyou** [comment]
You leaked the password in the screenshot.

However the code looks right. The api is documented as obsolete but the stream and authentication should be fine.

In order to try and help you, could you at least post a full stack trace (remove the try catch and paste the trace from the debugger) and if possible logs from the front and postfix containers of your setup?

**Comment by RexProg** [comment]
Stack Trace:
```
   at System.Net.Mail.MailCommand.CheckResponse(SmtpStatusCode statusCode, String response)
   at System.Net.Mail.MailCommand.Send(SmtpConnection conn, Byte[] command, MailAddress from, Boolean allowUnicode)
   at System.Net.Mail.SmtpTransport.SendMail(MailAddress sender, MailAddressCollection recipients, String deliveryNotify, Boolean allowUnicode, SmtpFailedRecipientException& exception)
   at System.Net.Mail.SmtpClient.Send(MailMessage message)
   at SimpleSMTP.Program.Main(String[] args) in C:\Users\RexProg\source\repos\SimpleSMTP\SimpleSMTP\Program.cs:line 25
```
Message:
`The SMTP server requires a secure connection or the client was not authenticated. The server response was: 5.7.1 Authentication required`

>if possible logs from the front and postfix containers of your setup
how can i access these logs?

**Comment by pirate** [comment]
Sorry, I misunderstood "send from any client" as "send from any source address", @RexProg you definitely don't need those overrides if it's just a connection/auth issue.

**Comment by kaiyou** [comment]
@RexProg you can access the logs by running `docker-compose logs smtp front --tail=100 -f`

**Comment by kaiyou** [comment]
Anyway here is probably the culprit: https://docs.microsoft.com/en-us/dotnet/api/system.net.mail.smtpclient.usedefaultcredentials?view=netframework-4.8#System_Net_Mail_SmtpClient_UseDefaultCredentials

**Comment by RexProg** [comment]
![image](https://user-images.githubusercontent.com/23130739/62848891-ab168c80-bcf2-11e9-86b4-25d12717380f.png)

**Comment by RexProg** [comment]
>Anyway here is probably the culprit

i try user UseDefaultCredentials before setting Credentials but it has same result
anyway i don't think it has any effect
![image](https://user-images.githubusercontent.com/23130739/62848990-0cd6f680-bcf3-11e9-81c4-df34538658c7.png)

**Comment by kaiyou** [comment]
It seems like your client library does not try to authenticate before initiating the mail submission. This is probably an issue with your code, but I am not an expert enough with dotnet to help you with the library, you'll probably have more luck on specialized support forums.

**Comment by RexProg** [comment]
the problem was solved using MailKit
thank you very much
