### ISSUE TITLE
Server name "antivirus" hardcoded in services/rspamd/conf/antivirus.conf

### ISSUE THREAD

**Issue by micw** [Mailu/Mailu#1109]
The server name should be resolved agains HOST_ANTIVIRUS. PR follows.

**Comment by boldt** [comment]
See #884 #940 #1101

**Comment by micw** [comment]
I have read through all services because I'm creating a clean helm chart from scratch. That one is currently the only one that is really hardcoded and cannot be overridden by a HOST_* or *_ADDRESS var. So I'd really appreciate to have this in 1.7, otherwise I will not be able to enable clamav on k8s.
