### ISSUE TITLE
Service status / Docker error

### ISSUE THREAD

**Issue by gizocz** [Mailu/Mailu#111]
Admin / Service status return the following error:

An error occurred while talking to the Docker server.
400 Client Error: Bad Request ("b'client is newer than server (client API version: 1.24, server API version: 1.23)'")

I tried to add version="auto" (see https://docker-py.readthedocs.io/en/latest/api/#version-mismatch) in admin/mailu/dockercli.py, but i got another error:

An error occurred while talking to the Docker server.
'com.docker.compose.service'

What is wrong?
thank you

**Comment by kaiyou** [comment]
It seems that you are not running the recommended Docker version. Which version are you running? Are you using CoreOS (which is known not to use the latest Docker version)?

**Comment by gizocz** [comment]
$ docker version
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.6.3
 Git commit:   b9f10c9
 Built:        Wed, 20 Jul 2016 16:34:52 -0700
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.6.3
 Git commit:   b9f10c9
 Built:        Wed, 20 Jul 2016 16:34:52 -0700
 OS/Arch:      linux/amd64

$ docker-compose version
docker-compose version 1.8.0, build unknown
docker-py version: 1.9.0
CPython version: 2.7.12+
OpenSSL version: OpenSSL 1.0.2h  3 May 2016

$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description: Debian GNU/Linux 7.11 (wheezy)
Release: 7.11
Codename: wheezy

$ dpkg -l | grep docker
ii  docker-compose                      1.8.0-2
ii  docker.io                           1.11.2~ds1-6
ii  python-docker                       1.9.0-1
ii  python-dockerpty                    0.4.1-1

**Comment by kaiyou** [comment]
Oh, then Wheezy has Docker 1.11 with API 1.23, I did not know about that. Could you and upgrade Docker from the official repositories maybe or do you have production running on the same server?

**Comment by gizocz** [comment]
Actualy, there is no Docker in Debian Wheezy. I have instlled Docker from
unstable repository (see https://packages.qa.debian.org/d/docker.io.html).
I will try the docker from https://get.docker.com/ ...

**Comment by curry684** [comment]
You should never use the unstable repositories in production. Instead, for frequently updating packages,  always prefer the vendor-supplied Debian repositories, like for Docker https://docs.docker.com/engine/installation/linux/debian/.

**Comment by gizocz** [comment]
I tried a docker from https://get.docker.com/ and it not help. There was
still the error:

An error occurred while talking to the Docker server.
'com.docker.compose.service'

But then I "did something" (reboot, upgrade another packages, containers,
..) and now it works. I do not know, what helps :(

**Comment by kaiyou** [comment]
After upgrading to the latest docker, maybe you did not load the freshly installed Docker, which rebooting has accomplished?

**Comment by gizocz** [comment]
I rebooted my server (I upgraded also the Linux kernel).
