### ISSUE TITLE
Reduce running user privileges

### ISSUE THREAD

**Issue by vogelfreiheit** [Mailu/Mailu#1115]
Seems like gunicorn and other things are running as root when it could be trivial to move to a dedicated non privileged user. Even under a container, root is root as far as kernel ABI is involved (a typical misconception with container security...). Dropped capabilities don't do much against a sizable amount fo kernel vulnerabilities perfectly reachable via NET_RAW and MKNOD (both enabled by default in docker containers).

Worth a separate issue would be including outgoing e-mail encryption or encryption at rest with a given user's pubkey (for all non PGP encrypted inbound email). 

:-)

**Comment by kaiyou** [comment]
This is a duplicate of #1009, but I definitely agree we have much progress to accomplish on the matter.

**Comment by vogelfreiheit** [comment]
Let me know if you need some help and testing, I will have time the next few weeks every now and then.
