### ISSUE TITLE
DKIM signature sometimes invalid

### ISSUE THREAD

**Issue by micw** [Mailu/Mailu#1118]
During my test phase, I exchanged emails with several DKIM enabled email accounts. Most DKIM signatures have been valid. But we had cases where DKIM signatures where invalid, other mails between the same accounts had been valid.

I will add a few examples.

**Comment by micw** [comment]
This is a mail at the recipients end, DKIM failed:

```
Delivered-To: <test1@wyraz.net>
Return-Path: <dario@kanojo.de>
Received: from mail.wyraz.net ([10.42.0.246])
	by mail.wyraz.net with LMTP
	id rYynJwNdXF2kAAAAufgoIA
	(envelope-from <dario@kanojo.de>)
	for <test1@wyraz.net>; Tue, 20 Aug 2019 20:50:11 +0000
Received: from mail.ghostdub.de (ghostdub.de [95.216.78.222])
	by mail.wyraz.net (Postfix) with ESMTP id 441BBD60302
	for <test1@wyraz.net>; Tue, 20 Aug 2019 20:50:11 +0000 (UTC)
Received: from authenticated-user (PRIMARY_HOSTNAME [PUBLIC_IP])
	by mail.ghostdub.de (Postfix) with ESMTPA id E638B24C0C94
	for <test1@wyraz.net>; Tue, 20 Aug 2019 20:50:09 +0000 (UTC)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=kanojo.de; s=dkim;
	t=1566334210; h=from:from:sender:reply-to:subject:subject:date:date:
	 message-id:message-id:to:to:cc:mime-version:mime-version:
	 content-type:content-type:
	 content-transfer-encoding:content-transfer-encoding:
	 in-reply-to:in-reply-to:references:references;
	bh=1NEmyKEMLqLHR5J28m8ruO+rd/+Vr/uzGoDw2BRogZk=;
	b=DkhGDko/wtMClOkBWpfOdNpcevPwLPVvVorExW6pC17y90J69nGaYy18DwWf1QJbwiL/SH
	3WpwrkcqJzaNRZSRIEkcnlsnKVFh4rFTkYXYYR7o8DuSwwqRWNXt3EmIsTRzINVRqPeJ51
	6srtPfcMO+9/ipabqzOHFdcqyDl0NQE=
Subject: Re: Eine weitere Testmail
To: Test1 <test1@wyraz.net>
References: <7826f9ec-d102-00b4-7977-4e6bb3f4cec2@wyraz.net>
From: Dario Ernst <dario@kanojo.de>
Message-ID: <41045c26-92e0-dfa4-3cf4-0ea784e26878@kanojo.de>
Date: Tue, 20 Aug 2019 22:50:08 +0200
MIME-Version: 1.0
In-Reply-To: <7826f9ec-d102-00b4-7977-4e6bb3f4cec2@wyraz.net>
Content-Type: text/plain; charset=utf-8
Content-Language: de-AT-frami
Content-Transfer-Encoding: quoted-printable
Authentication-Results: mail.wyraz.net;
	dkim=fail (body hash did not verify) header.d=kanojo.de header.s=dkim header.b=DkhGDko/;
	dmarc=pass (policy=reject) header.from=kanojo.de;
	spf=pass (mail.wyraz.net: domain of dario@kanojo.de designates 95.216.78.222 as permitted sender) smtp.mailfrom=dario@kanojo.de
X-Spamd-Bar: ----

dkim test reply blafu

On 8/20/19 10:08 PM, Test1 wrote:
> Hi,
>=20
> hoffe, jetzt geht mein DKIM auch.
>=20
> Gr=C3=BC=C3=9Fe,
>=20
> Michael.
>=20
>=20
```

**Comment by Nebukadneza** [comment]
Hi,

sorry for the late data-feed — here’s the exact mail and headers from the send-side:
```
Subject: Re: Eine weitere Testmail
To: Test1 <test1@wyraz.net>
References: <7826f9ec-d102-00b4-7977-4e6bb3f4cec2@wyraz.net>
From: Dario Ernst <dario@kanojo.de>
Message-ID: <41045c26-92e0-dfa4-3cf4-0ea784e26878@kanojo.de>
Date: Tue, 20 Aug 2019 22:50:08 +0200
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101
 Thunderbird/60.7.0
MIME-Version: 1.0
In-Reply-To: <7826f9ec-d102-00b4-7977-4e6bb3f4cec2@wyraz.net>
Content-Type: text/plain; charset=utf-8
Content-Language: de-AT-frami
Content-Transfer-Encoding: 8bit

dkim test reply blafu

On 8/20/19 10:08 PM, Test1 wrote:
> Hi,
> 
> hoffe, jetzt geht mein DKIM auch.
> 
> GrÃ¼ÃŸe,
> 
> Michael.
> 
> 
```

**Comment by Nebukadneza** [comment]
Also, a interesting observation in that testing session was: When sending a mail from our Mailu-installations to google, google always showed DKIM as good/valid … and I guess they’re quite picky?

**Comment by kaiyou** [comment]
Do you have any news on this? I do not experience any issue with DKIM while having had bots sending hourly test emails to various providers for the past year.

**Comment by elandorr** [comment]
I can confirm. This fails consistently. You can easily check using https://mxtoolbox.com/deliverability.

**Comment by Nebukadneza** [comment]
I tried this for a fresh installation on a demo-setup, as well as my productive system, and i get DKIM passes on mxtoolbox, mail-tester and from gmail.
Could the ones of you who are experiencing this problem maybe elaborate a bit on their setup, or gather logs of mailu when it goes wrong — ideally together with the headers on receiving side ….

Thanks a bunch!

**Comment by Nebukadneza** [comment]
Hi There,

The `Mailu`-Project is currently in a bit of a bind! We are short on man-power, and we need to judge if it is possible for us to put in some work on this issue.

To help with that, we are currently trying to find out which issues are actively keeping users from using `Mailu`, which issues have someone who want to work on them — and which issues may be less important. These a less important ones could be discarded for the time being, until the project is in a more stable and regular state once again.

In order for us to better assess this, it would be helpful if you could put a **reaction on this post** (use the :smiley: icon to the top-right).
- 👍️ if you **need this** to be able to use Mailu. Ideally, you’d also be able to test this on your installation, and provide feedback …
- 🎉 if you find it a **nice bonus**, but no deal-breaker
- 🚀 if you want to **work on it yourself**!
We want to keep this **voting open for 2 weeks** from now, so please help out!

**Comment by Diman0** [comment]
I also just tested it and cannot replicate the problem. I am closing this issue. If the issue comes back feel free to open a new issue and we will continue there.
