### ISSUE TITLE
Admin / Delete User => Internal Server Error

### ISSUE THREAD

**Issue by gizocz** [Mailu/Mailu#112]
When I add and then delete an user in Admin / Mail Domains / Users, I got "Internal Server Error". The user is actually deleted. I tried stable and latest version with the same result.

logs:
admin_1      | [2016-11-11 13:31:47 +0000] [13] [ERROR] Error handling request /admin/user/delete/test%40gitima.cz
admin_1      | Traceback (most recent call last):
admin_1      |   File "/usr/local/lib/python3.5/site-packages/gunicorn/workers/sync.py", line 135, in handle
admin_1      |     self.handle_request(listener, req, client, addr)
admin_1      |   File "/usr/local/lib/python3.5/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
admin_1      |     respiter = self.wsgi(environ, resp.start_response)
admin_1      |   File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 2000, in __call__
admin_1      |     return self.wsgi_app(environ, start_response)
admin_1      |   File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1991, in wsgi_app
admin_1      |     response = self.make_response(self.handle_exception(e))
admin_1      |   File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1567, in handle_exception
admin_1      |     reraise(exc_type, exc_value, tb)
admin_1      |   File "/usr/local/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
admin_1      |     raise value
admin_1      |   File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1988, in wsgi_app
admin_1      |     response = self.full_dispatch_request()
admin_1      |   File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1641, in full_dispatch_request
admin_1      |     rv = self.handle_user_exception(e)
admin_1      |   File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1544, in handle_user_exception
admin_1      |     reraise(exc_type, exc_value, tb)
admin_1      |   File "/usr/local/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
admin_1      |     raise value
admin_1      |   File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1639, in full_dispatch_request
admin_1      |     rv = self.dispatch_request()
admin_1      |   File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1625, in dispatch_request
admin_1      |     return self.view_functions[rule.endpoint](**req.view_args)
admin_1      |   File "/usr/local/lib/python3.5/site-packages/flask_login/utils.py", line 228, in decorated_view
admin_1      |     return func(*args, **kwargs)
admin_1      |   File "/app/mailu/admin/access.py", line 27, in wrapper
admin_1      |     return callback(function, args, kwargs, dargs, dkwargs)
admin_1      |   File "/app/mailu/admin/access.py", line 18, in callback
admin_1      |     return function(*args, **kwargs)
admin_1      |   File "/app/mailu/admin/access.py", line 104, in wrapper
admin_1      |     return function(*args, **kwargs)
admin_1      |   File "/app/mailu/admin/views/users.py", line 67, in user_delete
admin_1      |     flask.url_for('.user_list', domain_name=user.domain.name))
admin_1      |   File "/usr/local/lib/python3.5/site-packages/sqlalchemy/orm/attributes.py", line 237, in __get__
admin_1      |     return self.impl.get(instance_state(instance), dict_)
admin_1      |   File "/usr/local/lib/python3.5/site-packages/sqlalchemy/orm/attributes.py", line 584, in get
admin_1      |     value = self.callable_(state, passive)
admin_1      |   File "/usr/local/lib/python3.5/site-packages/sqlalchemy/orm/strategies.py", line 533, in _load_for_state
admin_1      |     (orm_util.state_str(state), self.key)
admin_1      | sqlalchemy.orm.exc.DetachedInstanceError: Parent instance <User at 0x7f111b838160> is not bound to a Session; lazy load operation of attribute 'domain' cannot proceed
admin_1      | 172.19.0.7 - - [11/Nov/2016:13:31:47 +0000] "POST /admin/user/delete/test%40gitima.cz HTTP/1.0" 500 - "-" "-"

**Comment by kaiyou** [comment]
I can reproduce indeed. I will investigate this later. Thank you for reporting.

The bug happens when generating the redirection message, so there is no critical impact. It is probably related to ``user.domain.name`` (trying to access the domain of a deleted user sounds bad).
