### ISSUE TITLE
Logging dissapeared

### ISSUE THREAD

**Issue by muhlemmer** [Mailu/Mailu#1120]
In the past I've implemented some logging during start-up in PR #810, in order to close related issue #588. At the time resolving host-names was still done in each `start.py` and we passed the `log` into tenacity retry.

Somewhere along the lines of MailuStart and later socrate, `log(ging)` is no longer used. This results in quite some unused orphans:

https://github.com/Mailu/Mailu/blob/13d6cf2fdbcf9b4e3bd31d5f8db467ee340cbc74/core/dovecot/start.py#L12

https://github.com/Mailu/Mailu/blob/13d6cf2fdbcf9b4e3bd31d5f8db467ee340cbc74/core/nginx/config.py#L10

https://github.com/Mailu/Mailu/blob/13d6cf2fdbcf9b4e3bd31d5f8db467ee340cbc74/core/postfix/start.py#L13

https://github.com/Mailu/Mailu/blob/13d6cf2fdbcf9b4e3bd31d5f8db467ee340cbc74/services/rspamd/start.py#L9

https://github.com/Mailu/Mailu/blob/13d6cf2fdbcf9b4e3bd31d5f8db467ee340cbc74/services/unbound/start.py#L8

https://github.com/Mailu/Mailu/blob/13d6cf2fdbcf9b4e3bd31d5f8db467ee340cbc74/webmails/rainloop/start.py#L9

https://github.com/Mailu/Mailu/blob/13d6cf2fdbcf9b4e3bd31d5f8db467ee340cbc74/webmails/roundcube/start.py#L8

Currently only ClamAV has some simple logging in `start.py`.

## What to do?

I believe that the (attempted) resolving of host deserves some logging. If no, containers might fail or freeze without any apparent reason. But in which scope belongs the logger?

Most projects I worked on, the logger is set from the main package, not in an imported package. And passed down to any imports that need a (configured) logger.

However, what I understand from [`socrate`'s readme](https://github.com/Mailu/socrate/blob/master/README.md), its intended scope in config parsing / daemon utilities. So it could parse the log-level from the environment and perhaps expose a logger to calling packages?

So what would be best?
1. Keep the logger initialization in `start.py` or `configuration.py` of the services. Pass it down to socrate, perhaps podop (was still a personal TODO) and some jinja template logging?
2. Initialize the logger in socrate and import it into podop and `start.py`?

If we decide that the `log` definition in `start.py` won't be used, we need to cleanup above mentioned garbage :).

CC: @Mailu/contributors

**Comment by kaiyou** [comment]
I am intuitively in favor of 2. This keeps complexity in the external package and that falls in the intended scope.

**Comment by Nebukadneza** [comment]
Hi There,

The `Mailu`-Project is currently in a bit of a bind! We are short on man-power, and we need to judge if it is possible for us to put in some work on this issue.

To help with that, we are currently trying to find out which issues are actively keeping users from using `Mailu`, which issues have someone who want to work on them — and which issues may be less important. These a less important ones could be discarded for the time being, until the project is in a more stable and regular state once again.

In order for us to better assess this, it would be helpful if you could put a **reaction on this post** (use the :smiley: icon to the top-right).
- 👍️ if you **need this** to be able to use Mailu. Ideally, you’d also be able to test this on your installation, and provide feedback …
- 🎉 if you find it a **nice bonus**, but no deal-breaker
- 🚀 if you want to **work on it yourself**!
We want to keep this **voting open for 2 weeks** from now, so please help out!

**Comment by nextgens** [comment]
That's how it works now.
