### ISSUE TITLE
Proxy rspamd through admin ui for security reasons

### ISSUE THREAD

**Issue by micw** [Mailu/Mailu#1121]
Currently the security of rspamd on kubernetes relies on a feature available on nginx ingress. If the ingress does not support that annotation, rspamd will be exposed unprotected. It would be better if the admin ui proxies rspamd and adds authentification.

**Comment by kaiyou** [comment]
The front container is supposed to handle authentication, even for HTTP backends. Maybe it is time we get back to exposing Mailu web traffic through an internal nginx? I am starting to think it would avoid a lot of drama related to complex ingress configuration on k8s.
