### ISSUE TITLE
Redis address parsing is done in init_app

### ISSUE THREAD

**Issue by muhlemmer** [Mailu/Mailu#1125]
This was added in #1107:

https://github.com/Mailu/Mailu/blob/f3f0c3190be9ab9b53a29c5b0326fc9a4602df46/core/admin/mailu/configuration.py#L11-L12

While, `REDIS_ADDRESS` is now only resolved in `init_app`. (#940). We took care of that in:

https://github.com/Mailu/Mailu/blob/f3f0c3190be9ab9b53a29c5b0326fc9a4602df46/core/admin/mailu/configuration.py#L116-L117

I believe DEFAULT_CONFIG should be like:

https://github.com/Mailu/Mailu/blob/4c25c83419be128fb12591721627a718ec23f69d/core/admin/mailu/configuration.py#L12-L13

We are now in the process of backporting #940 to 1.7. PR #1107 was not backported. Therefore 1.7 will look like the last snippet.

CC @mildred, @kaiyou

**Comment by kaiyou** [comment]
I rebranched, so I'll provide a quick PR to fix this.
