### ISSUE TITLE
Implement Managesieve in dovecot

### ISSUE THREAD

**Issue by fabiorauber** [Mailu/Mailu#113]
Brainstorming and comparing against my current solution (dovecot + roundcube based), would it be easy to enable managesieve protocol in dovecot, and enable it in rainloop or roundcube, so that the user has control of his own filters?

**Comment by kaiyou** [comment]
I believe it is enabled already and available from roundcube. Some work might be required for rainloop.

**Comment by kaiyou** [comment]
4e84fd1f6ae17e40f625fc6e4f177a4134fb1412 did fix this for Rainloop, should be working on ``master``.
