### ISSUE TITLE
Rainloop Webmail - Authentication fails if you have a special character in your password

### ISSUE THREAD

**Issue by Angedestenebres** [Mailu/Mailu#1139]
In the admin interface, you can define a new password and you can put a special character like `è`.

It works fine with admin interface but it doesn't work at all with the Rainloop webmail. If you try to log in, you will have a message to indicate that the authentication fails, see screenshoot in french:

![Capture d’écran de 2019-08-25 10-57-56](https://user-images.githubusercontent.com/21110485/63647853-904b0b80-c727-11e9-9938-d66a1e10ca4e.png)

**Comment by fldu** [comment]
Same for me with "password" ...

**Comment by Angedestenebres** [comment]
@fldu My issue is about the password with a special character not the username (even if hidden in my screenshot).

and if your password is "password" it should work afaik :)

**Comment by fldu** [comment]
@Angedestenebres no, i checked, but maybe a variable was added and I didn't set it... for the moment i rolled back and it works

**Comment by kaiyou** [comment]
Really, standard password should work, if they do not, then your setup is probably broken somewhere. Please open a separate issue if you struggle with it or come and discuss it on our matrix chan.

**Comment by kaiyou** [comment]
After much debugging, this issue definitely seems to be related to the way nginx talks to the admin container and send the password. It all seem to boil down to https://www.python.org/dev/peps/pep-3333/#unicode-issues and https://tools.ietf.org/html/rfc2616.html

From my overall understanding, nginx accepts an utf8 password from the client, then sends it on the wire as is. However, Werkzeug then goes and follows the standard, so it read the incoming bytestring as ISO-8859-1, in lack of anything more precise. Then Python exposes it as a `str` object, which is inherently UTF-8 based.

I am testing a fix on my instance. I will come back with a PR if it runs fine. Spoiler, it includes some `.encode("iso8859-1").decode("utf8")` nonsense :smile:

**Comment by micw** [comment]
@kaiyou I ran tcpdump on my admin container and logged in using the password xäöüßx. In the header sent from nginx, I can see
```
Auth-Pass: x....x
```
Seems the non-ascii chars in my password are entirely striped out...

**Comment by kaiyou** [comment]
Are they stripped out or is it tcpdump that only renders ASCII? Please look at the hex dump of tcpdump.

So far, decoding then reencoding works pretty good on our server. I will PR tomorrow.

**Comment by kaiyou** [comment]
Here is the commit : https://forge.tedomum.net/tedomum/mailu/commit/0ad6b1972bcf20046fc5ea75bdbdb3fd19ed7da4
