### ISSUE TITLE
POP3 Server ?

### ISSUE THREAD

**Issue by Ndrou** [Mailu/Mailu#114]
Hello,

It seems POP3 server is not enabled in the lastest version. That should be done with Dovecot, right?

How to enable it ?

Thanks

**Comment by kaiyou** [comment]
You are right, Mailu is clearly missing pop3 support. It will be trivial to add to ``latest``, backporting to ``stable`` might be possible.

**Comment by kaiyou** [comment]
I just pushed this. I will deploy on the test server as soon as the build finishes. Could you test?
I will push this tomorrow to stable if it does not introduce any major bug to the Dovecot behaviour. Services will not be exposed unless users update their ``docker-compose.yml``.

**Comment by Ndrou** [comment]
I just tested it, it seems to work :)

Very good reactivity ! Thanks :)

**Comment by kaiyou** [comment]
Ok, I tested most other features and it does not seem to impact the IMAP service. I will backport it to stable.
