### ISSUE TITLE
403 forbidden on /admin and /webmail

### ISSUE THREAD

**Issue by gregf** [Mailu/Mailu#1140]
I used the web config generator for 1.7 and 1.6, each time when I go to mail.mydomain.com/admin/ or /webmail/ I get a 403 forbidden message. I tried to give docker 5-10 minutes to do it's thing wondering if something was just starting up and nothing. 

Logs to nginx show it as well.

xxx.71.240.xxx - - [26/Aug/2019:23:25:15 +0000] "GET /admin/ HTTP/1.1" 403 162 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"

**Comment by muhlemmer** [comment]
Have you checked suggestions in: https://mailu.io/1.7/faq.html#access-denied-errors?

(Sorry the styling is a bit off, I fixed it in PR #1141)
