### ISSUE TITLE
Mailu on NAS should get its own IP

### ISSUE THREAD

**Issue by frostbeule** [Mailu/Mailu#1149]
First of all, I'm new to using docker, so this might be easy, but to me it is not:

I'm running mailu on my QNAP NAS. QNAP has implemented a virtual switch. In short, this means that a container can also get an IP-Adress from the network that you are in, so the container behaves - in some way - as if it was the only exposed application on a seperate computer. I belive it is best to show the result with an image:
![Netzwerk_Virtueller_Switch_bearbeitet](https://user-images.githubusercontent.com/54725356/64050472-699e3200-cb78-11e9-95fd-b7d95b65c35d.png)

Now anyone in the network can reach the apache-container by entering its ip-Adress (RED-Network.48). This is archived because the apache-container has the following network-configuration in the docker-compose-file:
`  default
    driver: qnet
    ipam:
      driver: qnet
      options:
        iface: "eth0"`
In case of the Apache-Container this is easy because it is no application with several containers.
I am now wondering how it would be possible to archive something similar for mailu.
My goal would be that it gets its own IP. This would even avoid port-conflicts because the Mailu-Server then would only listen to requests that come on the Mailu-IP.
I belive all that has to be done is to put the correct part from mailu in a second network and then configure it to take requests from that side only, but how?
Or is it something that is not possible?

**Comment by kaiyou** [comment]
You could create a second network named public with the qnap ipam driver at the end of the compose file. Then add in the front container:

```
networks:
  - default
  - public
```

This way the front container will get its IP from the qnap driver.

**Comment by muhlemmer** [comment]
@kaiyou, you beat me as I was writing.

I would like to add that the except for `front` the other containers should not be exposed inside your network. They should reside on a private (Docker) network. Or else anybody in the network would be able to send mail without authentication. Or worse, if you forward SMTP ports directly to the postfix container, an open relay.

And I believe you need:
````
networks:
  default:
  public:
    external: true
````

**Comment by frostbeule** [comment]
Thank you for your Ideas.
I specified this networks:

> networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.203.0/24
  public:
    driver: qnet
    ipam: 
      driver: qnet
      options:
        iface: "eth0"

> 
and put the front-container into public and default network.
The good news is: The container got an IP-Adress, and I can also access it.
The weird news which I don't understand is: It somehow ignores all port-mappings that are set in the front-container.
For example I had to choose a different port for the web-interface (because port 80 is already occupied from the NAS-Webinterface)
And what is also not good: It now reacts on two IP-Adresses: The one from the NAS plus the one it got itself.
Is there any chance that it does not react on the NAS-IP? I belive the easiest way would be to delete all port-mappings, but maybe there is a better way?

**Comment by frostbeule** [comment]
I did some experiments with settings and came to a point that is working, so I'd like to share them:

First, you need to remove all Port-Settings in the front-container (makes sense, as it is getting its own IP nothing needs to forward to it)
Second, add a new network to the network-section:
Either

>   public-dhcp:
>     driver: qnet
>     ipam:
>       driver: qnet
>       options:
>         iface: "eth0"

or

>   public-static:
>     driver: qnet
>     ipam:
>       driver: qnet
>       options:
>         iface: "eth0"
>       config:
>         - subnet: 192.168.80.0/23
>           gateway: 192.168.80.254

(See https://qnap-dev.github.io/container-station-api/qnet.html for reference)
Adjust the iface, subnet and gateway according to your setup.
I would not recommend to go for the dhcp-option, reasons follow.

For the front-container, edit the network-section so that it looks like this:

>     networks:
>       default:
>       public_static:
>         ipv4_address: 192.168.80.119

This way, the front-container is reachable with the IP 192.168.80.119, but the other containers can reach it within the default-network.
I would not go for the dhcp-network because everytime you restart the container it got a new MAC-Adress, so it will get a new IP-Adress. The problem with using
mac_address: xx:xx:xx:xx:xx 
for the front-container is that - in my case - it only had an effect on the default-network, but not on the public one.

This leaves just one problem open: When I also used the resolver, it seemed as if the resolver got confused (i cant really explain, but I got this feeling from the terminal output, unfortunately I did not save the output), but since I did not need it I just disabled the resolver and now it seems stable.

**Comment by Nebukadneza** [comment]
Hi There,

The `Mailu`-Project is currently in a bit of a bind! We are short on man-power, and we need to judge if it is possible for us to put in some work on this issue.

To help with that, we are currently trying to find out which issues are actively keeping users from using `Mailu`, which issues have someone who want to work on them — and which issues may be less important. These a less important ones could be discarded for the time being, until the project is in a more stable and regular state once again.

In order for us to better assess this, it would be helpful if you could put a **reaction on this post** (use the :smiley: icon to the top-right).
- 👍️ if you **need this** to be able to use Mailu. Ideally, you’d also be able to test this on your installation, and provide feedback …
- 🎉 if you find it a **nice bonus**, but no deal-breaker
- 🚀 if you want to **work on it yourself**!
We want to keep this **voting open for 2 weeks** from now, so please help out!

**Comment by Diman0** [comment]
Hi There,

we see this issue had only little attention 😟. As much as it pains us: In order to get the current issues a bit more manageable for us, we decided to close it. 👋👋

We hope that no one feels offended by doing so. Should the issue get really pressing in the future, please feel free to re-open it.

Thank you for your patience and understanding, 🙇
- Your Mailu Team
