### ISSUE TITLE
SMTP: Helo command rejected

### ISSUE THREAD

**Issue by Ndrou** [Mailu/Mailu#115]
Hi,

When I try to send a email from Windows, i have this error:

```
'504 5.5.2 <DESKTOPN7L10I2>: Helo command rejected: need fully-qualified hostname'
```

It seems to be due by `smtpd_helo_restrictions`.

Have a good day!

**Comment by kaiyou** [comment]
Are you using Submission, SMTPS or SMTP? I will try and reproduce from a Windows machine that does not have an FQDN. Maybe we need to losen restrictions a bit.

**Comment by Ndrou** [comment]
I use SMTPS, I have the same issue on all computers on my network.

**Comment by kaiyou** [comment]
Indeed, I switched from applying restrictions to everyone to applying only to remote servers connecting to port 25. Could you test with Postfix from ``latest``?

**Comment by Ndrou** [comment]
It seems to be OK ;)

Thanks

**Comment by curry684** [comment]
This is not really a solution as my customers are still getting these problems now trying to use Mailu as their outgoing SMTP server from Outlook. I think the HELO restrictions are pretty pointless anyway, every spammer is using a faked FQDN anyway so it's now just a hindrance to non-technical end users.

I vote for removing both HELO restrictions (`reject_non_fqdn_helo_hostname` and `reject_invalid_helo_hostname`) unless someone knows pressing reasons to require them.

**Comment by curry684** [comment]
Forgot to mention @kaiyou :)

**Comment by kaiyou** [comment]
Sorry, just started a new job and not so efficient as the last couple of months.

I do agree about HELO restrictions being quite useless nowadays. Still, I already removed them for SMTP connections on ports 465 and 587. Why would clients connect to port 25 to send emails?

**Comment by kaiyou** [comment]
Nevermind, I had another look at the configuration and the check is indeed almost useless. I do not have access to my editor right now, but feel free to post a pull request for simply disabling the HELO checks for good.

**Comment by curry684** [comment]
I'm pretty sure I also encountered the issues on 465 and 587 while reproducing a complaint   ;)

**Comment by kaiyou** [comment]
It did happen on ports 465 and 587 until 3e85bb2d7381c42bdc75db9c6400c4503cc8dd78 I believe.

**Comment by curry684** [comment]
Quite possible I tried both stable and latest and encountered it on stable, which is indeed before that commit.

**Comment by kaiyou** [comment]
Just merged your changes into stable. Thank you!
