### ISSUE TITLE
Timezone in containers

### ISSUE THREAD

**Issue by micw** [Mailu/Mailu#1154]
Hello,

I have seen that timezones are not set for containers. This causes logs to have wrong timestamps and email "received" headers have wrong timezones.

It should be possible to set the timezone for all containers. The setting should be exposed and described in the .env file.

**Comment by atl285** [comment]
On my own server I passthrough the timezone to every container via volume:

```
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
```

So I only have to take care of the timezone for host system.

**Comment by Nebukadneza** [comment]
Hi There,

The `Mailu`-Project is currently in a bit of a bind! We are short on man-power, and we need to judge if it is possible for us to put in some work on this issue.

To help with that, we are currently trying to find out which issues are actively keeping users from using `Mailu`, which issues have someone who want to work on them — and which issues may be less important. These a less important ones could be discarded for the time being, until the project is in a more stable and regular state once again.

In order for us to better assess this, it would be helpful if you could put a **reaction on this post** (use the :smiley: icon to the top-right).
- 👍️ if you **need this** to be able to use Mailu. Ideally, you’d also be able to test this on your installation, and provide feedback …
- 🎉 if you find it a **nice bonus**, but no deal-breaker
- 🚀 if you want to **work on it yourself**!
We want to keep this **voting open for 2 weeks** from now, so please help out!

**Comment by Nebukadneza** [comment]
Thank you for your offer, @atl285 !

**Comment by DjVinnii** [comment]
It is possible to install the tzdata package and provide the timezone in the .env file. I could make a PR for this if wanted.

**Comment by skironDotNet** [comment]
changing TZ in mailu.env doesn't seem to have any effect

**Comment by skironDotNet** [comment]
Actually the timezone setting is in WebUI (roundcube)

**Comment by micw** [comment]
The issue was about the timezone within the container (e.g. for logs and mail headers). The timezone used for the webmail might be a different thing that is probably not container-specific but user-specific (different users may use different time zones).
