### ISSUE TITLE
Virus mails should not be siliently discarded

### ISSUE THREAD

**Issue by micw** [Mailu/Mailu#1155]
Currently Mailu virus-scans emails in rspamd. If a virus is found, it is marked vie X-Virus header. In dovecot sieve, these mails gets silently rejected.

This behaviour has a number of drawbacks. A mail system should never silently discard emails,  especially not in default config. The sender will not know about the issue, the recipient will never know that there was an email. Discarding on the pressence of the header would also discard emails that elsewehere got this header, making the behaviour more inconsistent.

A better solution is to reject virus emails in the smtp dialogue. So the email never enters the mail system and is "someone else's problem" ;-) Usually the sender will receive a bounce.

Things to be changed:
- in rspamd antivirus.conf: add ``` action = "reject" ```
- in admin/mailu/internal/templates/default.sieve remove the discard of mails with X-Virus.

**Comment by kaiyou** [comment]
Silently discarded maybe not, but certainly not rejected imho.

Rejecting explicitly means advertising one's detection capability to an adversary, which is very precious information when delivering targeted payloads to a target company for instance.

We can discuss about notifying admins or the recipient, which sounds more reasonable.

**Comment by micw** [comment]
@kaiyou Would you be OK with making `action` configurable until we have a better solution?

**Comment by micw** [comment]
I have created a pull request that allows to toggle between current behaviour (discard) and my proposed behaviour (reject). The PR also adds some doc about the current behaviour.

I'd leave this Issue open until we have discussed (and implemented) an alternative solution (e.g. 'discard_and_notify' which notifies the postmaster or 'quarantine' or something else).

**Comment by micw** [comment]
Closed with #1259
