### ISSUE TITLE
SMTP mail queue is not persistent

### ISSUE THREAD

**Issue by muhlemmer** [Mailu/Mailu#1161]
While writing some proposals for Mailu storage, I actually found that the `/queue` directory for postfix is not defined as a volume. This might result in a loss of mail in case of container shutdown/crash/reboot.

https://github.com/Mailu/Mailu/blob/1f0b45e47b44d892305c59521a6b30386048370c/core/postfix/conf/main.cf#L14

In the blame I found a commit that added this in the configuration, but the Dockerfile or `docker-compose.yml` never got updated. I believe this still needs to be done.

Related: #211

**Comment by micw** [comment]
It also needs to be added at docs/kubernetes/smtp.yaml
