### ISSUE TITLE
dovecot: auth_default_realm does not seem to work

### ISSUE THREAD

**Issue by tobiaslangner** [Mailu/Mailu#1165]
Hey folks. We're trying to migrate our existing dovecot/postfix combo to mailu using docker-compose. So far, most things worked out of the box, which is great. What we haven't gotten to work yet is to allow the users to authenticate with dovecot with their bare username "foobar" instead of "foobar@example.net" as they are used to in our old installation (which would be great for a seemless transition).

From what I can tell from [here](https://docs.iredmail.org/authenticate.without.domain.name.html), this can be achieved by setting the dovecot configuration option `auth_default_realm`. Hence we've added
```
auth_default_realm = example.net
auth_realms = example.net
```
to the file that gets mounted into `/overrides/dovecot.conf` in the imap container and indeed `doveconf` in the imap container correctly shows those variables set. Unfortunately, logging in through either roundcube or other mail clients with the plain usernames does not work while appending `@example.net` makes it work, meaning that the above settings apparently don't seem to be used correctly. 

Digging a bit around in the configurations, it seems that dovecot within mailu uses a podop backend for authentication. Could this be the reason that that the aforementioned settings might not be used at all?

1. Is there an easy way to allow authentication without needing to enter the full username?
2. Why does dovecot use podop for authentication and not just a regular authentication framework, e.g. using a postgres DB backend?

Thanks,

  Tobias

**Comment by kaiyou** [comment]
More generally dovecot is not responsible for authentication, but the admin api is.

For this to work you would have to both add the behavior to the admin api used by nginx, then implement the same behavior for dovecot account db as accessed through podop. It is doable but will require some python scripting and rebuilding the admin image, not just overriding configuration.

**Comment by kaiyou** [comment]
Also we use podop to forward all calls to a single api that handles all the diversity of connecting to backends and the complexity of backend schemas, which is a lot easier to achieve in Python using an ORM than in multiple configuration styles in various mail software.

**Comment by kaiyou** [comment]
Closing this in favor of the discussion around #1344
