### ISSUE TITLE
ClamAv

### ISSUE THREAD

**Issue by adi90x** [Mailu/Mailu#117]
Hello,
it seems that clamav is using almost all RAM and more than 50% of CPU some time, is it a well know issue ? 
Is there a way to reduce this ? or maybe replace ClamAv ? 

Regards,

**Comment by kaiyou** [comment]
RAM is a known issue and there is not much that can be done on the matter except loading database signatures everytime, which would only make deliveries smaller.

Regarding CPU, I have no such issue however, are you continuously delivery e-mails or is ClamAV consuming CPU even when idling?

There are projects to make ClamAV optional and/or even replaceable, I will keep this topic open to keep track of them.

**Comment by adi90x** [comment]
Did you ever see `https://github.com/maliceio` seems they are building docker images of almost all antivirus, may give user a choice of different AV ?

**Comment by kaiyou** [comment]
As I understand it, the Malice project is very similar to Virustotal or IRMA. They pop a container for each antivirus check, which is not suitable for a mail server handling frequent incoming email. But I will have a look at their Dockerfiles, thank you!
