### ISSUE TITLE
Is mailu.io down?

### ISSUE THREAD

**Issue by Jakob-em** [Mailu/Mailu#1172]
It seems like mailu.io is down.

**Comment by muhlemmer** [comment]
Jup, seeing that too. This is really not my week, everything is just collapsing. I'll get on to it now...

**Comment by muhlemmer** [comment]
It's back... I was using traefik:latest for reverse proxy and apparently they release 2.0, which has some incompatible options with the old 1.7. Downgraded to 1.7 for now.

**Comment by Jakob-em** [comment]
Okay thanks for the info
