### ISSUE TITLE
Server side delivery rules

### ISSUE THREAD

**Issue by ldericher** [Mailu/Mailu#1186]
Hi Mailu :)

I really like the containerized approach of Mailu. However, I did not yet migrate to my own Mailu instance as I'm missing a "killer feature", as stated in the title.

Currently I'm running `maildrop` for this ~ I can put together some regexes so maildrop delivers certain mails into IMAP subdirectories. Simple example:

```
if (/^To:.*noreply@github\.com/:ih)
{
  DESTDIR="$MAILDIR/.GitHub"
}
```

I would love taking part in such an improvement to Mailu, I just have no idea where to start in this project. 

- Could/Should this be integrated into any existing container?
- A new container dedicated to run maildrop (or similar)?
- How to plug in a new per-user config page in admin interface?

**Comment by kaiyou** [comment]
This is intended to be implemented as sieve, and I believe there are already open issues about making sieve available to users properly. Currently sieve scripts are delivered by the admin container so they could be exposed through the webui easily.

**Comment by ldericher** [comment]
Thanks for mentioning "sieve" in this context! #497 is actually solved and I can confirm it working on test.mailu.io! :heart:
