### ISSUE TITLE
Allowing postfix to check a TLS/SSL connection if port 25 fails

### ISSUE THREAD

**Issue by jasonkolodziej** [Mailu/Mailu#1187]
Running this in the cloud, almost always port 25 is closed. Is there a way to fix how postfix approaches moving to another port that is open? I was testing DKIM.

```
Sep 30 16:41:30 mail postfix/smtpd[128]: disconnect from localhost[127.0.0.1] quit=1 commands=1
Sep 30 16:41:31 mail postfix/smtp[289]: connect to mail.appmaildev.com[13.67.59.48]:25: Operation timed out
Sep 30 16:41:31 mail postfix/smtp[289]: A4EDF75B1: to=<test-ac88bd75@appmaildev.com>, relay=none, delay=574, delays=543/0.06/30/0, dsn=4.4.1, status=deferred (connect to mail.appmaildev.com[13.67.59.48]:25: Operation timed o
ut)
```

**Comment by jasonkolodziej** [comment]
This is using a GCP Instance.

**Comment by kaiyou** [comment]
There is no alternative no: SMTP between MTA uses port 25. This is basically the reason why it is blocked in so many places, in an effort to fight off some spam. If you cannot open connections to remote port 25, you won't be able to host a proper MTA. You could use a relay that exposes an interface on a different port, at best.
