### ISSUE TITLE
Mailu+kubernetes+traefik ingress

### ISSUE THREAD

**Issue by nalakawula** [Mailu/Mailu#1189]
This is not an issue.
Can some one point me any online tutorial to setup mailu in k8s with traefik?

Thanks

**Comment by micw** [comment]
I will do that setup in the next 1-2 weeks and provide documentation.

**Comment by bh90210** [comment]
I'd love to see such guide as well as I have been struggling to accomplice a setup with the same tooling following available documentation and my k8s knowledge fails me.

Also any pointers are also welcome :eyes:

**Comment by micw** [comment]
The current release will not work well with traefik (it has a strong binding to some nginx ingress features), so you will have to use the master version.

I have created a helm chart which is currently at https://github.com/micw/charts/tree/mailu/incubator/mailu. My plan was to contribute it to the official helm charts but they do not accept any new charts and require contributors to host the charts themself (which indeed makes sense). I will setup a helm repo for mailu soon.

If you are using helm, please try this chart. It should work out of the box. Feedback is highly appreciated. The README is not 100% complete, so please look into values.yaml if you miss something.

**Comment by ook** [comment]
FYI, I'm working on a Mailu 1.7 deployment with Traefik2.0.1. Ingoing email are working, but I still have problem to authenticate against imap.

**Comment by micw** [comment]
ook, are you about to replace the internal nginx with traefik?

**Comment by ook** [comment]
So far, I don't use the internal nginx container.

**Comment by micw** [comment]
How do you plan to provide starttls on port 25 without nginx?

**Comment by ook** [comment]
I was considering https://github.com/containous/traefik/issues/5688#issuecomment-544628901 (or using the nginx in last solution)

**Comment by micw** [comment]
The issue's resolution is, not to do STARTTLS in traefik but to plain TCP ingress and let the backend do the STARTTLS stuff. So you will have to stick with nginx at the end. With this, I cannot see how using traefik's TCP ingress brings any advantage.

To come back to the original issue request: We need to distinguish between "using mailu along with an existing traefik (1.x, 2,x) http/https ingress controller" (which is what most people probably will need) and "replacing mailu's internal nginx with traefik2" (which I personally cannot see any reason for).

**Comment by bh90210** [comment]
I agree that most will want a fully nginxed mailu along traefik, this is also what I need as well.

I am looking at your chart, is it working atm? haven't tried yet.

**Comment by micw** [comment]
Yes, it is working. You need to clone it from git since there's no chart repo yet.
Let me know if you need any advice or miss features.

**Comment by kaiyou** [comment]
Also, please.. please be careful when going around the nginx. Keep in mind that it is running most of the auth stuff currently.

**Comment by ook** [comment]
@micw I'm testing your helm charts (will open a PR to let set `storage-class` instead of `storage-path`). It seems the `certificates` volume (named `certs`, mounted in front pod) is not created from it. Can you advise on how to create it / fix it in the chart? Thanks.

**Comment by micw** [comment]
@ook I have just committed some fixed to the last merged PR (it did fail for me with some template errors, seems I overlooked this in my review). Would you try it again?
If you use the repo, please update and use version 0.0.2. It also contains storage-class.

**Comment by ook** [comment]
Ok. Storage-class works. Still problem with `certs`, maybe because I use a pre01 certmanager? Mailu/helm-charts/issues/6

**Comment by ook** [comment]
I confirm your helm chart is fully functional for my cluster (k8s v1.13.10, nginx from mailu docs + your helm chart, storage via glusterfs, all on baremetal). Thank you. 👍

**Comment by kaiyou** [comment]
That sounds so nice. Thanks for the feedback and cuddos @micw :D

**Comment by micw** [comment]
@ook Thank you for the feedback. I'll release an improved version in the next days that contains health checks for all services.

**Comment by micw** [comment]
Closing this now, please add further feedback and issues for the helm chart at https://github.com/Mailu/helm-charts
