### ISSUE TITLE
Password managers are not usable because of missing site title on login page

### ISSUE THREAD

**Issue by d-Rickyy-b** [Mailu/Mailu#1192]
In version 1.7 there is no title on the login page of the admin webinterface. This prevents me from using my password manager's (KeePass 2) auto-type feature, because it checks for the window's title. Which is simply the name of the browser, because the tab's title is empty.

![grafik](https://user-images.githubusercontent.com/5798157/66253916-6d246a80-e76f-11e9-9e59-39575b3c014b.png)

Could you set a title such as "Mailu login" or similar? That would be awesome.

**Comment by hoellen** [comment]
The title is now set on master (#1180).
