### ISSUE TITLE
403 Forbidden Nginx

### ISSUE THREAD

**Issue by syahwanius** [Mailu/Mailu#1199]
Hello i was new for using mailu
im trying to install mailu on my office and i was following tutorial from this link https://mailu.io/1.5/compose/setup.html (already set TLS setting bind ip etc)
but when im open the domain i was like this

![image](https://user-images.githubusercontent.com/54254371/66451125-40c96080-ea85-11e9-88b7-f0aa48d0ae44.png)

can someone help me? thanks

**Comment by kaiyou** [comment]
First off, as mentioned on the top of the tutorial page, you are reading deprecated documentation, as we are currently running with a 1.7 stable branch.

Also, before we can help you, you would need to provide some details, starting with your environment (especially your TLS flavor and setup) and a couple logs from the front containers.

Usual suspects would be the front container struggling to generate dh params (solved in 1.7) and certificates not being properly setup.

**Comment by syahwanius** [comment]
> First off, as mentioned on the top of the tutorial page, you are reading deprecated documentation, as we are currently running with a 1.7 stable branch.
> 
> Also, before we can help you, you would need to provide some details, starting with your environment (especially your TLS flavor and setup) and a couple logs from the front containers.
> 
> Usual suspects would be the front container struggling to generate dh params (solved in 1.7) and certificates not being properly setup.

Thanks for your rply, now im using this link https://setup.mailu.io/1.7/  , bind address was my ip use to mailu, what **Subnet of the docker network. This should not conflict with any networks to which your system is connected** stand for? im using /24 (255.255.255.0) when i saw on my putty or can im using the same address as IPv4 but im add /24?

**Comment by micw** [comment]
@syahwanius This error indicates that your DNS is not working properly - that's an issue out of mailu's scope.
