### ISSUE TITLE
Internal Server Error when delete a Fetched accounts

### ISSUE THREAD

**Issue by gizocz** [Mailu/Mailu#120]
In admin, when I add a Fetched accounts and then I delete it, I will get "Internal Server Error".

Logs:
admin_1      | [2016-11-22 10:16:00 +0000] [12] [ERROR] Error handling request /admin/fetch/delete/1
admin_1      | Traceback (most recent call last):
admin_1      |   File "/usr/local/lib/python3.5/site-packages/gunicorn/workers/sync.py", line 135, in handle
admin_1      |     self.handle_request(listener, req, client, addr)
admin_1      |   File "/usr/local/lib/python3.5/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
admin_1      |     respiter = self.wsgi(environ, resp.start_response)
admin_1      |   File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 2000, in __call__
admin_1      |     return self.wsgi_app(environ, start_response)
admin_1      |   File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1991, in wsgi_app
admin_1      |     response = self.make_response(self.handle_exception(e))
admin_1      |   File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1567, in handle_exception
admin_1      |     reraise(exc_type, exc_value, tb)
admin_1      |   File "/usr/local/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
admin_1      |     raise value
admin_1      |   File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1988, in wsgi_app
admin_1      |     response = self.full_dispatch_request()
admin_1      |   File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1641, in full_dispatch_request
admin_1      |     rv = self.handle_user_exception(e)
admin_1      |   File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1544, in handle_user_exception
admin_1      |     reraise(exc_type, exc_value, tb)
admin_1      |   File "/usr/local/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
admin_1      |     raise value
admin_1      |   File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1639, in full_dispatch_request
admin_1      |     rv = self.dispatch_request()
admin_1      |   File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1625, in dispatch_request
admin_1      |     return self.view_functions[rule.endpoint](**req.view_args)
admin_1      |   File "/app/mailu/admin/access.py", line 104, in wrapper
admin_1      |     return function(*args, **kwargs)
admin_1      |   File "/usr/local/lib/python3.5/site-packages/flask_login/utils.py", line 228, in decorated_view
admin_1      |     return func(*args, **kwargs)
admin_1      |   File "/app/mailu/admin/access.py", line 27, in wrapper
admin_1      |     return callback(function, args, kwargs, dargs, dkwargs)
admin_1      |   File "/app/mailu/admin/access.py", line 18, in callback
admin_1      |     return function(*args, **kwargs)
admin_1      |   File "/app/mailu/admin/views/fetches.py", line 58, in fetch_delete
admin_1      |     flask.url_for('.fetch_list', user_email=fetch.user.email))
admin_1      |   File "/usr/local/lib/python3.5/site-packages/sqlalchemy/orm/attributes.py", line 237, in __get__
admin_1      |     return self.impl.get(instance_state(instance), dict_)
admin_1      |   File "/usr/local/lib/python3.5/site-packages/sqlalchemy/orm/attributes.py", line 584, in get
admin_1      |     value = self.callable_(state, passive)
admin_1      |   File "/usr/local/lib/python3.5/site-packages/sqlalchemy/orm/strategies.py", line 530, in _load_for_state
admin_1      |     (orm_util.state_str(state), self.key)
admin_1      | sqlalchemy.orm.exc.DetachedInstanceError: Parent instance <Fetch at 0x7fbae1253198> is not bound to a Session; lazy load operation of attribute 'user' cannot proceed

admin version:
82efd56fe25c        mailu/admin:latest

**Comment by kaiyou** [comment]
Indeed, this seems related to #112, I should be able to fix quickly.

**Comment by kaiyou** [comment]
The build is in progress, please confirm that the bug is fixed on your side so that I can backport this to stable as well:

https://hub.docker.com/r/mailu/admin/builds/bib5dwahbr6apxnt9buh2eh/

**Comment by gizocz** [comment]
now it works. thank you.
