### ISSUE TITLE
nginx override fails

### ISSUE THREAD

**Issue by boldt** [Mailu/Mailu#1205]
I need to add one more Cipher Suite to my mailu cofiguration. My idea:

1. Override with default config
2. Edit config

### 1. Override with default config

I downloaded the [tls.conf](https://github.com/Mailu/Mailu/blob/4733f15c0ca50d9fabbc7fe6d351763186666f3e/core/nginx/conf/tls.conf) and copied it to my [overrides folder](https://mailu.io/master/faq.html#how-can-i-override-settings):

```
$ROOT/overrides/nginx/tls.conf
```

If I restart my container, i get

```
front_1       | nginx: [warn] duplicate value "TLSv1.1" in /overrides/tls.conf:1
front_1       | nginx: [warn] duplicate value "TLSv1.2" in /overrides/tls.conf:1
front_1       | nginx: [emerg] "ssl_ciphers" directive is duplicate in /overrides/tls.conf:2
```

The container is hanging in a restart loop.

### Related issues

* #944

**Comment by ofthesun9** [comment]
put your tls.conf in $ROOT (/mailu)
modify your docker-compose.yml to mount your modified file to /conf/tls.conf in the front container:
front:
....
  volumes:
....
      - /mailu/tls.conf:/conf/tls.conf

**Comment by boldt** [comment]
Yes, that's what I'm doing already and it's working well. 

Anyway, that's not how it's described in the docs.

**Comment by kaiyou** [comment]
Just added this to the faq.

**Comment by nazar-pc** [comment]
Just hit this as well, but it is annoying to copy the whole file rather than overriding a few configuration keys.
