### ISSUE TITLE
error looking up **.**.**.**.list.dnswl.org: server fail

### ISSUE THREAD

**Issue by boldt** [Mailu/Mailu#1206]
In my rspamd **_history_** tab see plenty of the following messages:

![Bildschirmfoto von 2019-10-10 18-05-14](https://user-images.githubusercontent.com/750793/66586236-92a6df00-eb88-11e9-8ce9-19eeaf313e8a.png)

**Comment by muhlemmer** [comment]
Are you running with or without the unbound DNS server?

If not, it is possibly related to #554. For that we have included unbound in #681.

**Comment by muhlemmer** [comment]
Ooh wait, cancel that. These seem forward lookups against reverse-DNS records. Whoever is sending you mail has not set its Reverse DNS records correctly.

**Comment by boldt** [comment]
> Ooh wait, cancel that. These seem forward lookups against reverse-DNS records. Whoever is sending you mail has not set its Reverse DNS records correctly.

That sounds feasible!

**Comment by kaiyou** [comment]
These indeed look like quite normal warnings, which in fact influence spam classification. I am closing, feel free to reopen.
