### ISSUE TITLE
Recommended firewall setup for this config?

### ISSUE THREAD

**Issue by dm17** [Mailu/Mailu#1212]
Have you setup UFW or similar on your host? Do you not recommend a firewall? Are there security enhancements you've done outside of this repo to your host?
Thanks!

**Comment by micw** [comment]
I have an iptables firewall (debian with iptables-persistent) where I have only SSH open. Kubernetes (which I use) and probably docker too opens exposed ports automatically.

**Comment by dm17** [comment]
> I have an iptables firewall (debian with iptables-persistent) where I have only SSH open. Kubernetes (which I use) and probably docker too opens exposed ports automatically.
> 
> Edit: PS: it should not be scope of this project to recomment or document firewall settings other than the fact that mail ports needs to be open.

I raised this issue because as I understand it one needs special configuration to use a firewall with docker services. This is what I'm referring to, but perhaps it is only applicable to UFW:
https://askubuntu.com/questions/652556/uncomplicated-firewall-ufw-is-not-blocking-anything-when-using-docker

**Comment by Nebukadneza** [comment]
Hi There,

The `Mailu`-Project is currently in a bit of a bind! We are short on man-power, and we need to judge if it is possible for us to put in some work on this issue.

To help with that, we are currently trying to find out which issues are actively keeping users from using `Mailu`, which issues have someone who want to work on them — and which issues may be less important. These a less important ones could be discarded for the time being, until the project is in a more stable and regular state once again.

In order for us to better assess this, it would be helpful if you could put a **reaction on this post** (use the :smiley: icon to the top-right).
- 👍️ if you **need this** to be able to use Mailu. Ideally, you’d also be able to test this on your installation, and provide feedback …
- 🎉 if you find it a **nice bonus**, but no deal-breaker
- 🚀 if you want to **work on it yourself**!
We want to keep this **voting open for 2 weeks** from now, so please help out!

**Comment by Nebukadneza** [comment]
Hi There,

we see this issue had only little attention 😟. As much as it pains us: In order to get the current issues a bit more manageable for us, we decided to close it. 👋👋

We hope that no one feels offended by doing so. Should the issue get really pressing in the future, please feel free to re-open it.

Thank you for your patience and understanding, 🙇
- Your Mailu Team
