### ISSUE TITLE
Ship stock MariaDB images from setup

### ISSUE THREAD

**Issue by muhlemmer** [Mailu/Mailu#1217]
Currently we do not provide any images for MariaDB or mySQL. However, in order to provide a full choice to our users we can provide these options in setup. Just like laid out in #1216, we will only provide the Official [MariaDB](https://hub.docker.com/_/mariadb) and [mySQL](https://hub.docker.com/_/mysql) images in `docker-compose.yml`.

**Comment by Nebukadneza** [comment]
Hi There,

The `Mailu`-Project is currently in a bit of a bind! We are short on man-power, and we need to judge if it is possible for us to put in some work on this issue.

To help with that, we are currently trying to find out which issues are actively keeping users from using `Mailu`, which issues have someone who want to work on them — and which issues may be less important. These a less important ones could be discarded for the time being, until the project is in a more stable and regular state once again.

In order for us to better assess this, it would be helpful if you could put a **reaction on this post** (use the :smiley: icon to the top-right).
- 👍️ if you **need this** to be able to use Mailu. Ideally, you’d also be able to test this on your installation, and provide feedback …
- 🎉 if you find it a **nice bonus**, but no deal-breaker
- 🚀 if you want to **work on it yourself**!
We want to keep this **voting open for 2 weeks** from now, so please help out!

**Comment by Nebukadneza** [comment]
Hi There,

we see this issue had only little attention 😟. As much as it pains us: In order to get the current issues a bit more manageable for us, we decided to close it. 👋👋

We hope that no one feels offended by doing so. Should the issue get really pressing in the future, please feel free to re-open it.

Thank you for your patience and understanding, 🙇
- Your Mailu Team

**Comment by Diman0** [comment]
I agree this would be a good feature

**Comment by Diman0** [comment]
After further consideration and discussing this in the last regular mailu meeting, we have decided not to go through with this.
We will only ship Mailu with a working SQLite database (default option).

For using an external database the user must configure this for himself. Maintaining a database server is a task that requires knowledge of the database server software. Mailu is  a Mail solution. As the contributing guide lines already state: Beyond mail, we include features that mail is dependent on in some way, not the other way around. It is already possible to configure external DB servers in setup.mailu.io.
