### ISSUE TITLE
Rename user

### ISSUE THREAD

**Issue by jacekmigacz** [Mailu/Mailu#1218]
Hi,

I'd like to change From address to more official.
I've created nick@foo.bar account for everyone and then aliases for each, like first.last@foo.bar.
Is it possible to rename account and change nick@foo.bar to first.last@foo.bar?

P.S.
For now, my workaround is edit reply-to address.

Any hints would be greatly appreciated,
Thanks.

**Comment by kaiyou** [comment]
Unfortunately, it is not possible to rename an email address currently, and against the principle that an email address is the immutable base for users and all things on top.
What you could do as a workaround is editing the database directly, then renaming the folder in your `mail` data path. It is pretty unlikely that this is ever supported in the web ui though.

**Comment by jacekmigacz** [comment]
Thanks @kaiyou. Editing users in my SQLite backend is what I did in deed.
