### ISSUE TITLE
RFC: Delete instance ID file

### ISSUE THREAD

**Issue by muhlemmer** [Mailu/Mailu#1219]
For statistics we are using `/mailu/data/instance`. In replicated situations, this either need to be shared on a network filesystem or if it is kept local, we will have double usage counts. It adds complexity for something simple.

I want to propose moving it into `mailu.env`. Setup can generate the instance ID when generating the file.

A second option would be the database, in that case it value would be upgrade-proof. It might be overkill to create a table for this though. But perhaps, with eye on the future we can start be defining a key/value table called `config` and store it in there.

**Comment by kaiyou** [comment]
All for moving to mailu.env, since we now generate configuration from the config tool.

**Comment by Nebukadneza** [comment]
Hi There,

The `Mailu`-Project is currently in a bit of a bind! We are short on man-power, and we need to judge if it is possible for us to put in some work on this issue.

To help with that, we are currently trying to find out which issues are actively keeping users from using `Mailu`, which issues have someone who want to work on them — and which issues may be less important. These a less important ones could be discarded for the time being, until the project is in a more stable and regular state once again.

In order for us to better assess this, it would be helpful if you could put a **reaction on this post** (use the :smiley: icon to the top-right).
- 👍️ if you **need this** to be able to use Mailu. Ideally, you’d also be able to test this on your installation, and provide feedback …
- 🎉 if you find it a **nice bonus**, but no deal-breaker
- 🚀 if you want to **work on it yourself**!
We want to keep this **voting open for 2 weeks** from now, so please help out!

**Comment by Nebukadneza** [comment]
Hi There,

we see this issue had only little attention 😟. As much as it pains us: In order to get the current issues a bit more manageable for us, we decided to close it. 👋👋

We hope that no one feels offended by doing so. Should the issue get really pressing in the future, please feel free to re-open it.

Thank you for your patience and understanding, 🙇
- Your Mailu Team
