### ISSUE TITLE
Roundcube: support multiple DB backends

### ISSUE THREAD

**Issue by muhlemmer** [Mailu/Mailu#1226]
Roundcube currently has a SQLite file under: `/mailu/webmail/roundcube.db`. In order to allow for distributed deployment targets better, it should be possible to configure it to use an external database instead.

Config should be rendered in the setup as follows:

- User selects default `sqlite` DB backend --> use `roundcube.db`
- User selects stock PostgreSQL or MariaDB --> configure default connection parameters (pending #1216 and #1217)
- User selects external DB --> custom connection parameters

**Comment by micw** [comment]
Could roundcube use the same mysql database that mailu admin uses or would they interfere with each other?

**Comment by micw** [comment]
@muhlemmer What do you think about this solution?

https://github.com/micw/Mailu/commit/253e261a362f139240d6e67c50f4dcdfa7b71339

**Comment by mamiapatrick** [comment]
Hello
i'm facing the same issues, cannot configure roundcube to use external database  i got a message for a database error connection failed with $config['db_dsnw'] = 'sqlite:////data/roundcube.db'; somes updates on that issue?

**Comment by muhlemmer** [comment]
@micw I think the approach is good. And it could go into a PR. I think at first only document the capabilities in the reference docs and merge it like that.
And when we get around to #1216, #1217, integrate it into setup.

**Comment by muhlemmer** [comment]
When I replied I wasn't aware that #1268 was already submitted and merged. Looked over it. This issue can be closed.
