### ISSUE TITLE
Automatic reply not sent for aliases

### ISSUE THREAD

**Issue by kaiyou** [Mailu/Mailu#123]
As reported by @gizocz:

> It works for users emals. But not for an alias:
>
>imap_1       | Nov 23 20:06:39 lmtp(gizo@gitima.cz): Info:
>VrfOFs/2NVjpAAAAqusTng: sieve:
>msgid=<CAGYk4S2_TiX9aWS2VmoqetMzjH5PkVDhgzadwUXXoeY6=efkgQ@mail.gmail.com>:
discarding vacation response for implicitly delivered message; no known
(envelope) recipient address found in message headers (recipient=<
gizo@gitima.cz>, and no additional `:addresses' are specified)

**Comment by kaiyou** [comment]
The reason why the vacation is not sent is because vacation messages in Sieve are not designed to be sent when the original message is implicitely delivered (alias, etc.) I still agree this could be a nice feature.

I think we have three options here:
1. do not allow this kind of vacation message to be sent
2. dynamically add a header including the original recipient in the LMTP session and use ``lda_original_recipient_header`` and ``sieve_vacation_use_original_recipient`` in Dovecot
3. disable recipient checks in the vacation function

Option 1 is undesirable of course. Option 2 adds some complex configuration to the LMTP session: the only way to add this kind of headers it to use dynamic header filters. Option 3 contradicts the Sieve standard, but maybe our global configuration set enough constraints to avoid mail loops and so.

Still not sure what is the best course of action.

**Comment by kaiyou** [comment]
See section 4.5 of the following for option 3 : https://tools.ietf.org/html/rfc5230#page-6

**Comment by kaiyou** [comment]
Could you try this once the build is ready?

**Comment by gizocz** [comment]
The autoreply message now work. But in the From header there is the real
email, not the alias. If someone send e.g. a bug report to
webmaster@jesenickymaraton.cz, then the sender receive an auto-reply "out
of office" message from an unknown email, e.g. martin.lazar@gitima.cz. The
sender does not know martin.lazar and does not know why hi received the
message.

**Comment by kaiyou** [comment]
I believe that is the intended behaviour. If you send an email to a given alias and only one person is unavailable, you would naturally only expect to get an email from that person. The weird part is getting an email from someone that you did not explicitely contact in the first place and is a necessary consequence when sending vacation replies to aliases.

For that last reason, I will try and make this configurable in a next patch (enable or disable vacation replies for aliases).
