### ISSUE TITLE
CardDAV/CalDAV intergration with Roundcube

### ISSUE THREAD

**Issue by 0pera** [Mailu/Mailu#1230]
I've noticed that Mailu 1.7 has radicale and roundcube intergrated, and I know thers is a plugin is quite popular in roundcube offcial plugin repository call "roundcube/carddav".
It will be very good to see them works together so the webmail and the mail client will be able to have the same address book.

**Comment by muhlemmer** [comment]
@kaiyou; according the project core values, we do not intend to support Calendar applications. #1298 adds only CardDav. For the moment I've prevented auto close of this issue, as it requests both CardDav and CalDav.

I did this to verify with you: Should this be kept open for eventual CalDav plugin or close upon #1298 merge?

**Comment by Nebukadneza** [comment]
Hi There,

The `Mailu`-Project is currently in a bit of a bind! We are short on man-power, and we need to judge if it is possible for us to put in some work on this issue.

To help with that, we are currently trying to find out which issues are actively keeping users from using `Mailu`, which issues have someone who want to work on them — and which issues may be less important. These a less important ones could be discarded for the time being, until the project is in a more stable and regular state once again.

In order for us to better assess this, it would be helpful if you could put a **reaction on this post** (use the :smiley: icon to the top-right).
- 👍️ if you **need this** to be able to use Mailu. Ideally, you’d also be able to test this on your installation, and provide feedback …
- 🎉 if you find it a **nice bonus**, but no deal-breaker
- 🚀 if you want to **work on it yourself**!
We want to keep this **voting open for 2 weeks** from now, so please help out!

**Comment by Diman0** [comment]
There is currently a PR #1326 that allows to install additional plugins for roundcube. This should cover your additional feature request to add support for caldav.

**Comment by Diman0** [comment]
I will close this issue. The more generic issue #545  can be used for further discussion.
