### ISSUE TITLE
Alias change using CLI only active after restart?

### ISSUE THREAD

**Issue by oli-ver** [Mailu/Mailu#1233]
I am using a python script in a cron job to recreate an alias with round about 30 mail addresses every night with the following commands:

```
docker-compose exec admin flask mailu alias-delete my-alias@domain.com
docker-compose exec admin flask mailu alias my-alias domain.com 'mail1@other-domain.com,mail2@third-domain.com'
```

It seems this mail address can be used only after a restart (docker-compose restart). I have tried to reproduce the issue with setting my mail address 30 times in another alias, but for the new address it did not occur.

For now I will restart the environment in the cron job, but I don't think this should be necessary. Did someone experience similar issues?

**Comment by kaiyou** [comment]
I have not experienced it. What type of database are you using? Could you check that the record is indeed in database after running the command?

I suspect some kind of file locking black magic if you are using SQLite.

**Comment by oli-ver** [comment]
I am using postgresql. I think for now I will close this issue as it’s not reproducible. If it happens again I will reopen it again.
