### ISSUE TITLE
Forwarding emails using an alias sometimes fails with error code 550

### ISSUE THREAD

**Issue by oli-ver** [Mailu/Mailu#1234]
Currently forwarding Mails using aliases sometimes fails with the following error message:

```
<target-Mailserver-ip> said: 550-<Mailserver-ip-address> is not allowed to
   send mail from <sender-domain>. Help at/Hilfe unter 550 www.mfaq.info (in reply to
   RCPT TO command)
```

I think according to the sender rewriting scheme the mail header needs to change when forwarding mails:

https://en.wikipedia.org/wiki/Sender_Rewriting_Scheme

Is it possible that this is not the case?

I am using mailu 1.7.

**Comment by kaiyou** [comment]
We do not currently implement SRS properly, there is still #328 open on the matter.

Any help on this is welcome :)

**Comment by oli-ver** [comment]
Ah ok. Let’s discuss the next steps in this issue then.
