### ISSUE TITLE
open relay over IPv6

### ISSUE THREAD

**Issue by gizocz** [Mailu/Mailu#1235]
When enabled IPv6 in Mailu configuration, it create an open relay over IPv6 (IPv4 is ok).

I know, there is a FAQ and a danger notice in the setup wizard: _"Docker currently does not expose the IPv6 ports properly"_. But there is no a (big red) security warning about the open relay.

Using docker-ipv6nat solve the issue. It's looks like related to #332 (for IPv4).

**Comment by kaiyou** [comment]
We could add a big warning in the setup tool indeed.

**Comment by micw** [comment]
Till 1.8 we should at least the warning (and probably description how to use docker-ipv6nat)
@gizocz A PR to the docs is highly appreciated

**Comment by muhlemmer** [comment]
Uhh, the setup has a red warning about + a link to the FAQ:

![image](https://user-images.githubusercontent.com/5411563/80873290-1f012680-8cc0-11ea-9ddf-ede362e56717.png)

https://mailu.io/1.7/faq.html#how-to-make-ipv6-work

Put it there myself :innocent:, and running the setup since.

**Comment by Nebukadneza** [comment]
Haha, nice one. Since @muhlemmer already did this a long time ago in #886 , and I believe this should be quite clear, I’m taking the liberty of closing this.
