### ISSUE TITLE
Change Spam Settings

### ISSUE THREAD

**Issue by arnydo** [Mailu/Mailu#1238]
Hello,

I am looking for tips on adjusting the spam settings.

I would like to have all email go through the spam filter to be rated but essentially allow everything through...no rejecting/greylisting.

I have done the following:

- Changed Spam filter tolerance
- Turned off spam filtering

However, depending on the rating, spam is still rejected, etc.

Any ideas?

**Comment by kaiyou** [comment]
Very (very) high rated spam is still rejected directly by rspamd to avoid filling spam dirs with bulk email.

You can change this behavior by overriding the rspamd config.

**Comment by arnydo** [comment]
I was able to edit the config file and change the threshholds. Using the GUI doesn't seem to be working. Rspamd config just resets back to what the config file says.

**Comment by kaiyou** [comment]
Indeed using the GUI does not work, and will not work since written config is not persisted. I am closing this as answered.

**Comment by d-Rickyy-b** [comment]
I was wondering just today why some mails were rejected and didn't reach my mailbox even though I disabled spam filtering for that mailbox. I find it a bit misleading that spam is still filtered even though the "enable spam filter" checkbox is disabled.

Could you please document this behavior in a way that it's easier to find. And maybe you could link me some resource on how to configure rspamd to not filter certain mailboxes. Or is the only way to raise the general spam threshold?
