### ISSUE TITLE
ERROR: for mailu_front_1  Cannot start service front

### ISSUE THREAD

**Issue by evil4u** [Mailu/Mailu#1246]
I have this issue on  a fresh installed Debian 10

ERROR: for mailu_front_1  Cannot start service front: driver failed programming external connectivity on endpoint mailu_front_1 (fad77ba2db63b415b8889e8370dc0afbf2813ff63a649b4a70561750737a496d): Error starting userland proxy: listen tcp [::1]:995: bind: cannot assign requested address

ERROR: for front  Cannot start service front: driver failed programming external connectivity on endpoint mailu_front_1 (fad77ba2db63b415b8889e8370dc0afbf2813ff63a649b4a70561750737a496d): Error starting userland proxy: listen tcp [::1]:995: bind: cannot assign requested address
ERROR: Encountered errors while bringing up the project.

ss -lntp
State      Recv-Q     Send-Q         Local Address:Port         Peer Address:Port                                       
LISTEN     0          128                  0.0.0.0:22                0.0.0.0:*        users:(("sshd",pid=477,fd=3))     
LISTEN     0          128                     [::]:22                   [::]:*        users:(("sshd",pid=477,fd=4))

Could some one assist me on this please.

Thanks

**Comment by evil4u** [comment]
This is a new server with minimum setup.

**Comment by evil4u** [comment]
Fixe. I had to remove ::1 and all is working fine :)

**Comment by DmitriyRyazanovsky** [comment]
> Fixe. I had to remove ::1 and all is working fine :)

Hello, I'm facing the same problem, can you please explain in more detail what exactly you deleted?
