### ISSUE TITLE
Rancher Catalog

### ISSUE THREAD

**Issue by adi90x** [Mailu/Mailu#125]
Hello, 

I started using Rancher to maintain all my containers.
They have a pretty good feature call catalog in order to start a stack of services ( basically a docker-compose file ) and proving all environnement variable in the UI.
I built the catalog for myself, ( still testing it thought ) ,but if anyone is interested let me know I will push it to a public repo !

Have a good day,

**Comment by fabiorauber** [comment]
I'm interested =D

**Comment by kaiyou** [comment]
Depends how the catalog is stored in Rancher. Is it avaiable simply as a Yaml file or equivalent?

**Comment by adi90x** [comment]
Hello, 

Just push a first version to : https://github.com/adi90x/Rancher-Mailu.git

@kaiyou : I guess it could be add to mailu official repo , as it is a single folder.

@fabiorauber : If you can try it and confirm it work ? Plus , I can add another version with support for jwilder/nginx + letsencrypt ?

Enjoy, easy setup !

**Comment by kaiyou** [comment]
Given the structure, I would rather publish it in a separate repository, but I will gladly create ``mailu/rancher`` if you want!

**Comment by adi90x** [comment]
Why not ! it could be easier for everyone I guess

**Comment by adi90x** [comment]
Not really sure of how to push everything to mailu/Rancher  ( and never work on shared project ) do you have any advice/best practices ?

**Comment by kaiyou** [comment]
You should now have commit access to the ``Mailu/Rancher`` repository. There are many ways to manage a shared project. You are for sure the most knowledgeable around here regarding Rancher and technical aspects, so I suggest that you simply commit and push directly to the repository.

You are also more than welcome to handle pull requests if any. Also, I setup a Gitter a couple days ago, will add a link to the readme, feel free to join.

**Comment by adi90x** [comment]
Perfect I just push everything to Mailu/Rancher
