### ISSUE TITLE
webmail(roundcube) triggered imap authentication rate limit

### ISSUE THREAD

**Issue by 0pera** [Mailu/Mailu#1251]
when I tried to view a email contained several images, some images failed to load and then roundcube reported IMAP connection failed.

after refreshing the page, an error like "AUTHENTICATE PLAIN: A0003 NO Authentication rate limit from one source exceeded" is reported.

looks like roundcube had triggered the authentication limit, how to overwrite the "AUTH_RATELIMIT" setting for the webfront?

**Comment by micw** [comment]
You need to set the gobal auth limit. The problem is that the webmail creates a new imap session on each click, so it easily exhauses the rate limit.
see also #634 and #1195
