### ISSUE TITLE
Whitelist local addresses/domains in rspamd

### ISSUE THREAD

**Issue by cobrafast** [Mailu/Mailu#1254]
Emails sent between local email accounts still get filtered through rspamd and might get moved to junk folders or even rejected.

IMO this shouldn't be happening. Emails between local accounts should _always_ be delivered to inbox, even if they're malformed and look like spam.

Mailu should notice an email can be internally routed and completely bypass rspamd.

Is there a potential workaround for now?

**Comment by cobrafast** [comment]
Apparently Mailu is running all outgoing emails through rspamd. Can this be deactivated?

**Comment by kaiyou** [comment]
There is not workaround and this is considered a feature. You might be running a multi-tenant Mailu instance and have people send spam to each other. So every mail goes through the spam filter.
