### ISSUE TITLE
Regenerate DKIM keys

### ISSUE THREAD

**Issue by adi90x** [Mailu/Mailu#126]
Hello , 
It seems that DKIM are not update in the admin interface when you regenerate keys for a 2nd domains.
I did not try for my main mail domain thought.

Regards,

**Comment by kaiyou** [comment]
Hello, thanks for reporting.

Could you describe the steps to reproduce? I am not sure what you mean by the "second domain". Does it happen when you generate DKIM for more than one domain, or when you generate keys on a domain for the second time?

**Comment by adi90x** [comment]
I setup a second virtual domain in mailu, and I needed to regenerate domain key for this domain.
And DKIM public key is not update.

**Comment by kaiyou** [comment]
Did you fix the bug?

**Comment by adi90x** [comment]
Think I just mingled between dev and prod so closing this issue
