### ISSUE TITLE
 status=bounced (mail for mydomain.io loops back to myself)

### ISSUE THREAD

**Issue by iohenkies** [Mailu/Mailu#1260]
Hi,

I have two VPSes with Docker and one of them is running mailu. Awesome stuff, good work. One problem though, is that I can't get mail off the host itself with the (logical) error:

`mail postfix/smtp[28481]: warning: host mail.mydomain.io[108.70.80.1]:25 greeted me with my own hostname mail.mydomain.io`
`mail postfix/smtp[28481]: warning: host mail.mydomain.io[108.70.80.1]:25 replied to HELO/EHLO with my own hostname mail.mydomain.io`
`mail postfix/smtp[28481]: 8C91D6EBC: to=<alert@mydomain.io>, orig_to=<root@mail.mydomain.io>, relay=mail.mydomain.io[108.70.80.1]:25, delay=0.01, delays=0/0/0/0, dsn=5.4.6, status=bounced (mail for mydomain.io loops back to myself)`

These are alerts from OSSEC for instance, that should be able to be send from the host via postfix. I think the error is logical, and can't be solved with changing mydestination setting in main.cf, or adding aliases on the host, because however you change it: mail for this domain is being handled by containers on this host.

I hope I'm making sense and that I'm not the first one with this problem.

**Comment by kaiyou** [comment]
What is weird is that your mail server has the same hostname as your host, despite the host and Mailu being two different logical entities.

You could use a different hostname for Mailu, or specify a different helo name when sending mails from the host.

Also, if the source address is one handled by your Mailu instance, I would recommend authenticating.

**Comment by iohenkies** [comment]
Awesome, this was so simple, just a thinking flaw on my part: it seems solved. Many thanks!

It seems I'm having a problem that all authentication fails for a short while (all accounts ask their password again), but I'll troubleshot some more and else open a ticket.

**Comment by kaiyou** [comment]
Should I close this one then?

**Comment by iohenkies** [comment]
Sure, thanks again.
