### ISSUE TITLE
Root CA

### ISSUE THREAD

**Issue by blogwebpl** [Mailu/Mailu#1262]
Hello. Is there possibility to install Root CA in /mailu/certs ?

**Comment by kaiyou** [comment]
If you wish to add a root ca to verify outbound connections, it is not implemented no.

However, you would mostly need to add it to the smtp container, so I guess a custom image would do, or a volume mount of your root cert to the standard Alpine path.

**Comment by micw** [comment]
closed (answered, no further activity)
