### ISSUE TITLE
[OpenShift] Issue on OpenShift Container Platform

### ISSUE THREAD

**Issue by farhadmn** [Mailu/Mailu#1264]
Hi, 
I am getting this error, when I run the image on OpenShift. 

`
usage: gunicorn [OPTIONS] [APP_MODULE]
--
  | gunicorn: error: argument -w/--workers: expected one argument

`

**Comment by kaiyou** [comment]
Could you be a bit more specific about your setup? What did you deploy exactly?

**Comment by micw** [comment]
Closed due to inactivity
