### ISSUE TITLE
[Question] Spam Problems?

### ISSUE THREAD

**Issue by MikkelDK** [Mailu/Mailu#1265]
Hi,

After I have installed mailu via docker. and I got some-weird spam.

Do I need to ignore them, or can I block them some-else spam?

- As you see on the screenshot looks pretty **weeird** - Can I do something for fix this? or just ignore it?
![screenshot](http://vps.lindhost.eu/get5/chrome_Jmx2aDfy8g.png)

**Comment by Nebukadneza** [comment]
To me, this looks like pretty normal spam. It’s rejected with a relatively high score, which means that your rspamd is doing what we hired it for ….
Is there anything specific that strikes you as particularly odd? Otherwise i’d say ignore and be glad rspamd does what it does ^_^.

**Comment by micw** [comment]
It has an internal source IP address, always the same sender and lots of non-local receipients. I'd say you are the source of that spam (either a hacked system on that IP or your mailu itself it it's an open relay)

**Comment by MikkelDK** [comment]
Can I close the open relay?

tor. 21. nov. 2019 11.35 skrev micw <notifications@github.com>:

**Comment by micw** [comment]
first investigate and find out what exactly is going on

**Comment by iohenkies** [comment]
Yes check https://mxtoolbox.com/diagnostic.aspx for sure.

Also I believe I read somewhere that enabling IPv6 will create an open relay with Docker.

**Comment by MikkelDK** [comment]
Danke guys!

I got it fixed with disable IPv6 fully (since I don't use it)
And **Open Relay is now closed! ;-D**

**Yeah, I did use docker** - but I had used the setup page > https://setup.mailu.io/1.7 

- **Bug with setup page** ..if you **DON'T** enable Enable IPv6 via tick. It will still show **::1** on docker-compose.yml :'(

Thanks, guys <3
