### ISSUE TITLE
Can't add custom Webserver files

### ISSUE THREAD

**Issue by undercoverturbo** [Mailu/Mailu#1272]
I am new to docker and mailu. Just managed to setup everything on a fresh Debian 10 install.
I can't figure out, how to setup mailu, so that I can host a Website on the same machine as well.
E.g.: mail.mydomain.com/webmail leads to mailu, as it currently does (using mailu/roundcube)
       www.mydomain.com leads to my Website.
I have no idea if this is implemented, not working, or if I just can't figure it out.

**Comment by undercoverturbo** [comment]
I forgot to mention, I am using mailu/roundcube.

**Comment by undercoverturbo** [comment]
I now figured out, when adding a volume with my server files like this:
  - "/mailu/website:/var/www/html"
in the docker-compose.yml as a volume in webmail, I can reach my website under www.mydomain.com/webmail/website
When I now edit the mailu.env to have WEBROOT_REDIRECT=/webmail/website the website still can't be reached at www.mydomain.com/
It seems to be redirecting to www.mydomain.com/website which does not work.
So I have a solution, but it is not nice at all.
Maybe you can still help me out a bit? :)

**Comment by kaiyou** [comment]
Mailu is a mail server, it is not meant to expose specific items on its own webserver. You really should either: use a reverse proxy (see https://mailu.io/1.7/reverse.html for details) and expose othter containers or apps through it, or use specific IP addresses for different servies.

**Comment by undercoverturbo** [comment]
Thanks for the answer.
I now have 2 Servers running, separating the Services as you suggested.

**Comment by Nebukadneza** [comment]
Hi There,

The `Mailu`-Project is currently in a bit of a bind! We are short on man-power, and we need to judge if it is possible for us to put in some work on this issue.

To help with that, we are currently trying to find out which issues are actively keeping users from using `Mailu`, which issues have someone who want to work on them — and which issues may be less important. These a less important ones could be discarded for the time being, until the project is in a more stable and regular state once again.

In order for us to better assess this, it would be helpful if you could put a **reaction on this post** (use the :smiley: icon to the top-right).
- 👍️ if you **need this** to be able to use Mailu. Ideally, you’d also be able to test this on your installation, and provide feedback …
- 🎉 if you find it a **nice bonus**, but no deal-breaker
- 🚀 if you want to **work on it yourself**!
We want to keep this **voting open for 2 weeks** from now, so please help out!

**Comment by Nebukadneza** [comment]
Hi There,

we see this issue had only little attention 😟. As much as it pains us: In order to get the current issues a bit more manageable for us, we decided to close it. 👋👋

We hope that no one feels offended by doing so. Should the issue get really pressing in the future, please feel free to re-open it.

Thank you for your patience and understanding, 🙇
- Your Mailu Team
