### ISSUE TITLE
Docker rspamd - Can't change actions and configs

### ISSUE THREAD

**Issue by portneo-tech** [Mailu/Mailu#1273]
Hello, 
after I installed and configured the mailu stack with docker I can't make changes in the "rspamd" like actions and editing files (ex. lists)

Could it be a permission problem? 
I use your compose.yml which was created with your web configurator. 

Thanks for help. 
<img width="864" alt="error rspamd" src="https://user-images.githubusercontent.com/37145498/69723569-312bd700-111a-11ea-9761-c65a84876e07.png">

**Comment by kaiyou** [comment]
The rspamd web ui is not meant for editing the config. You should use overrides for this, see: https://mailu.io/1.7/reverse.html#override-mailu-configuration
