### ISSUE TITLE
How do I allow external hosts to send from a mailu domain

### ISSUE THREAD

**Issue by Helmi** [Mailu/Mailu#1276]
Hi,

scenario is a domain managed by MailU is also used on a ticket system. SPF and DKIM are set for the ticket system to allow sending from my domain managed by mailu. Works as long as the ticket system doesn't send to a mailu mailbox. Then the email is rejected due to the sender adress being used (from the domain managed by Mailu).

What is the way to allow certain hosts/networks etc. to use the domain? Does mailu not use DNS (SPF/DKIM) for that?

**Comment by kaiyou** [comment]
This is normal, and you should not share MX between two different mail servers for the same domain. I would suggest you either use a separate domain, or you setup the ticket system to check emails against Mailu using IMAP.

**Comment by Nebukadneza** [comment]
Hi There,

The `Mailu`-Project is currently in a bit of a bind! We are short on man-power, and we need to judge if it is possible for us to put in some work on this issue.

To help with that, we are currently trying to find out which issues are actively keeping users from using `Mailu`, which issues have someone who want to work on them — and which issues may be less important. These a less important ones could be discarded for the time being, until the project is in a more stable and regular state once again.

In order for us to better assess this, it would be helpful if you could put a **reaction on this post** (use the :smiley: icon to the top-right).
- 👍️ if you **need this** to be able to use Mailu. Ideally, you’d also be able to test this on your installation, and provide feedback …
- 🎉 if you find it a **nice bonus**, but no deal-breaker
- 🚀 if you want to **work on it yourself**!
We want to keep this **voting open for 2 weeks** from now, so please help out!

**Comment by Nebukadneza** [comment]
Hi There,

we see this issue had only little attention 😟. As much as it pains us: In order to get the current issues a bit more manageable for us, we decided to close it. 👋👋

We hope that no one feels offended by doing so. Should the issue get really pressing in the future, please feel free to re-open it.

Thank you for your patience and understanding, 🙇
- Your Mailu Team
