### ISSUE TITLE
gunicorn

### ISSUE THREAD

**Issue by baturorkun** [Mailu/Mailu#1277]
gunicorn service consumed my CPU power reckless. I checked  that admin docker use gunicorn for admin tools. i want to stop gunicorn so i think need to stop "admin" docker. Actually i don't need aynı admin panel just need smtp and imap services. if i stop admin docker, is there any problem about running  main email services.

**Comment by micw** [comment]
The admin provides an endpoint for all authentication, so it's needed and the auth requests are causing the load you see.

**Comment by baturorkun** [comment]
hi micw
which authentication?  including smtp and imap authentications.? i checked the dockers and i saw nginx is rproxy so i think i need nginx docker  for smtp and imap auths

**Comment by micw** [comment]
nginx is calling the admin app which acts as auth server (https://nginx.org/en/docs/mail/ngx_mail_auth_http_module.html#protocol).

**Comment by micw** [comment]
BTW, others already pointed out that the gunicorn workers are the bottleneck of mailu. If it's an issue to you, you could check out if it works better with meinheld workers (https://github.com/mopemope/meinheld, https://fgimian.github.io/blog/2018/05/17/choosing-a-fast-python-api-framework/)

**Comment by Nebukadneza** [comment]
Hi There,

The `Mailu`-Project is currently in a bit of a bind! We are short on man-power, and we need to judge if it is possible for us to put in some work on this issue.

To help with that, we are currently trying to find out which issues are actively keeping users from using `Mailu`, which issues have someone who want to work on them — and which issues may be less important. These a less important ones could be discarded for the time being, until the project is in a more stable and regular state once again.

In order for us to better assess this, it would be helpful if you could put a **reaction on this post** (use the :smiley: icon to the top-right).
- 👍️ if you **need this** to be able to use Mailu. Ideally, you’d also be able to test this on your installation, and provide feedback …
- 🎉 if you find it a **nice bonus**, but no deal-breaker
- 🚀 if you want to **work on it yourself**!
We want to keep this **voting open for 2 weeks** from now, so please help out!

**Comment by Nebukadneza** [comment]
Hi There,

we see this issue had only little attention 😟. As much as it pains us: In order to get the current issues a bit more manageable for us, we decided to close it. 👋👋

We hope that no one feels offended by doing so. Should the issue get really pressing in the future, please feel free to re-open it.

Thank you for your patience and understanding, 🙇
- Your Mailu Team
