### ISSUE TITLE
Why noTimestamp template?

### ISSUE THREAD

**Issue by thiagoalmeidasa** [Mailu/Mailu#128]
First of all, that isn't a critic, just a question. Why you use a non Timestamp template on postfix? https://github.com/Mailu/Mailu/blob/master/postfix/rsyslog.conf#L2

I was trying to do something about #116  and started analyzing and plotting postfix log and get errors in my tools because I had no timestamp in log entries.

What's your reason to do not use timestamp in rsyslog conf?

**Comment by kaiyou** [comment]
Hello, sorry for the delay.

Mailu is supposed to run as a set of Docker containers. Docker is responsible for logging, not containers that should simply output their logs to stdout. We use ``rsyslog`` in some containers when software only supports syslog logging and not standard output.

If you want to display timestamped logs, simply use the ``--timestamps`` (or ``-t``) flag for ``docker logs`` of ``docker-compose logs``.

**Comment by thiagoalmeidasa** [comment]
Thanks for the answer. I'll try to plot with docker-compose timestamps.
