### ISSUE TITLE
Roundcube 1.4 - Password with non-ASCII chars login failure

### ISSUE THREAD

**Issue by HorayNarea** [Mailu/Mailu#1281]
I just tried the new Roundcube 1.4.1 image from master on a small semi-production setup and it turns out that login fails (as if you entered the wrong password) if your password contains a german Umlaut (ä, ü, ö) :disappointed:

Maybe related to #1139?

Or it's this issue https://github.com/roundcube/roundcubemail/issues/4624? But that issue is so old, why didn't it occur before 1.4 :/

**Comment by micw** [comment]
@kaiyou Can be closed?

**Comment by HorayNarea** [comment]
I tried the current master images, this works now fine.
