### ISSUE TITLE
Can't access /admin dashboard

### ISSUE THREAD

**Issue by odinis** [Mailu/Mailu#1286]
Hello. as title says, I'm out of options. Please help me out:

- Running mailu with docker-compose 1.7 configured with setup.mailu.io. 
- Attached to an existing docker network. 
- Using external haproxy on pfsense.
- Each container has it's own IP address. 
- webmail container is accessible from network entering direct IP4.
- admin container is not, following with path /admin. 

What settings should be used in this scenario for either direct container admin access or frontend IP setup?

**Comment by kaiyou** [comment]
All of mailu should only be accessed through the front container. So first make sure that all reverse proxying and routing is done to that container.

Then, most mistakes are due to the tls settings. Could you detail a bit more how you set it all up?
