### ISSUE TITLE
can't login to rainloop or roundcube

### ISSUE THREAD

**Issue by samouds** [Mailu/Mailu#129]
Hello,

I'm trying to setup the mailu with rainloop, but when I try to login to rainloop using an account that I created I get an error : Authentication failed

Ajax response : {"Action":"Login","Result":false,"ErrorCode":102,"ErrorMessage":"","ErrorMessageAdditional":"","Time":347}

Any idea ?

**Comment by kaiyou** [comment]
Could you export logs from Rainloop and Dovecot when you try to authenticate ?

```
docker-compose logs --tail=0 -f imap webmail
```
