### ISSUE TITLE
Roundcube updated version

### ISSUE THREAD

**Issue by d-fens** [Mailu/Mailu#130]
Security issue impacting roundcube, unsure if this impacts mailu, but better to raise now.

https://roundcube.net/news/2016/11/28/updates-1.2.3-and-1.1.7-released

> Included is a fix for a recently reported security issue when using PHP’s mail() function. It has been discovered by Robin Peraglie using RIPS and more details along with a CVE number will be pulished shortly.
> 
> See the full changelog for 1.2.3 in the wiki. Version 1.1.7 is a security update fixing the mail() issue and thus only relevant to Roundcube installations not having an SMTP server configured for mail delivery.

**Comment by kaiyou** [comment]
I just pushed the update to ``master`` and cherry pick in stable tomorrow if nothing broke, thank you!
