### ISSUE TITLE
Increasing DKIM key size to 2048

### ISSUE THREAD

**Issue by abelhooge** [Mailu/Mailu#1301]
As it stands right now the automatically generated DKIM key is of a length of 1024. 

According to multiple articles, including one from [techrepublic](https://www.techrepublic.com/article/how-to-increase-your-dkim-key-to-2048-bits-for-google-apps/), a key size of less than 2048 is considered by some providers as inadequate. 

Changing the default generation key size should not cause any problems with backward compatibility, since it would only affect newly generated keys and not already existing ones. 

I'm interested to see if there is any support for this and whether there are any interesting perspectives on this matter.

**Comment by kaiyou** [comment]
Agreed. We would need to check that the provided DNS entries are still valid though.

I remember that larger key size means multiple DNS records sometimes.

**Comment by kaiyou** [comment]
Cc @t0mra when you find the time to make a PR :)

**Comment by bidetaggle** [comment]
Hi, sorry if my question is stupid. When will it be merged in the branch 1.7? Or can I make the same PR for this branch? 😊

**Comment by kaiyou** [comment]
It will probably never be merged in 1.7, unless we find it is blocking in many cases. We like to keep our stable branches stable. But 1. there is a PR in progress to start releasing often and smaller 2. we should be releasing 1.8 soonish? it would sound good anyway.
