### ISSUE TITLE
Postfix pod ceased to work

### ISSUE THREAD

**Issue by ook** [Mailu/Mailu#1304]
I have a mailu setup working perfectly for a big month on a k8s (v1.13.10) cluster of 5 nodes (hosting 4 domains, 8 accounts, dozens of aliases). Persistence is done via glusterfs.

5 days ago, the postfix stopped to worked: the pod is accessible (can get a `bash` session from it, send `postfix` commands) but impossible to get an answer on the port 25: the port is open, but nothing get from it (no SMTP header, or response to HELO commands). The front pod is working: I get the SMTP banne (I guess it's the nginx mailmode proxy that answer), and the SMTP session hang after sending `RCPT TO:` command.
When I try to delete the postfix pod, it get stuck in Terminating state, with forever event: `  Normal  Killing  5m2s (x81 over 166m)  kubelet, rancher2-solitude  Killing container with id docker://postfix:Need to kill Pod`. I have to restart the docker on the node to get rid of it (even `kubectl delete --force --grace-period=0` just remove from etcd, but not from docker, so the port is still in use)
If you can advise, I take all proposition. I'll keep this deployment some days for investigation then rip it off.

**Comment by marjak93** [comment]
We are having the same issue after our pods pulled new Mailu images today. The nginx pods are reporting upstream timeout errors when attempting to contact the postfix pod. The ports are open, but no response. No error output in the postfix pod either.

**Comment by ook** [comment]
Oh, interesting. Maybe the image wasn't correctly tagged.  I'll dig and force previous image. Thank you for the hint.

**Comment by kaiyou** [comment]
Do you have any feedback here? I could imagine this is due to postfix failing to contact the admin API. Any timeout maybe?

**Comment by ook** [comment]
@kaiyou so I clean the previous install and made a brand new one, with master images and latest helm files version. I have thousand of:
```
Jan 20 14:58:09 mail postfix/smtpd[16191]: connect from localhost[127.0.0.1]
Jan 20 14:58:09 mail postfix/smtpd[16191]: disconnect from localhost[127.0.0.1] quit=1 commands=1
```
(every 5s) from postfix pod, 

```
Jan 20 14:59:47 pop3-login: Info: Aborted login (no auth attempts in 0 secs): user=<>, rip=127.0.0.1, lip=127.0.0.1, secured, session=<vpLcipOcRYF/AAAB>
```
from dovecot, as often.
From front I have:
```
2020/01/20 15:00:51 [error] 13#13: *3607 mailu-admin.mailu.svc.cluster.local could not be resolved (110: Operation timed out), client: 127.0.0.1, server: , request: "GET /auth/email HTTP/1.0", host: "127.0.0.1"
2020/01/20 15:00:53 [error] 12#12: *3611 mailu-admin.mailu.svc.cluster.local could not be resolved (110: Operation timed out), client: 127.0.0.1, server: , request: "GET /auth/email HTTP/1.0", host: "127.0.0.1"
2020/01/20 15:00:55 [error] 12#12: *3612 46.38.144.17 could not be resolved (110: Operation timed out) while in resolving client address, client: 46.38.144.17, server: 0.0.0.0:25
2020/01/20 15:01:04 [error] 12#12: *3617 mailu-admin.mailu.svc.cluster.local could not be resolved (110: Operation timed out), client: 127.0.0.1, server: , request: "GET /auth/email HTTP/1.0", host: "127.0.0.1"
2020/01/20 15:01:06 [error] 12#12: *3618 46.38.144.202 could not be resolved (110: Operation timed out) while in resolving client address, client: 46.38.144.202, server: 0.0.0.0:25
```
HTH.

**Comment by kaiyou** [comment]
Looks like DNS is failing on the front container. Do you have a kubedns, coredns, or any other DNS server running?

**Comment by ook** [comment]
`kube-dns` is correctly working (used by other stack in the same cluster, different namespaces, used via helm, too)

```
kube-dns-58bd5b8dd7-bchcr                 3/3     Running            0          6h22m
kube-dns-58bd5b8dd7-l2xdb                 3/3     Running            0          15d
```

`mailu-admin` service does exist in the namespace `mailu` :
```
mailu-admin                                              ClusterIP   10.43.248.84    <none>        80/TCP                                                                              7d2h
```
And the endpoint match the admin pod.
The mailu-admin.mailu.svc.cluster.local is correctly resolved from outside `mailu-front` (even from another namespace)

Note: from `mailu-front`, I can't get "inner" dns resolution, but the resolv.conf is the same from a "working" pod, pointing to `kube-dns`.
I'm pretty lost… Something could hide the resolv.conf file?

**Comment by kaiyou** [comment]
Yes. Could you check the live `/etc/nginx/nginx.conf` on the admin container? The resolver is specified manually in there so that nginx does explicit resolution at runtime. The value is written at startup from what is read in the resolv.conf, but maybe something is wrong there.

**Comment by ook** [comment]
Sadly, resolvers in `nginx.conf` are correct:

```
bash-5.0# grep resolver nginx.conf
    resolver 10.43.0.10 valid=30s;
    resolver 10.43.0.10 valid=30s;
```
(same as in `/etc/resolv.conf`)

**Comment by kaiyou** [comment]
I have no decent explaination for this bug. Could you exec inside the front container, install a `dig` client and try to resolve manually against the configured resolvers?

**Comment by UbiquitousBear** [comment]
@kaiyou assuming this is related to my issue, resolving appears to work fine, for me it happens intermittently. Killing the pod and restarting it fixes the issue

**Comment by UbiquitousBear** [comment]
Using tcpdump in the front image, I found that there's significant latency between RCPT TO and internal postfix getting the call. I can't yet account for this, but internal postfix looks healthy once the connection is established.

**Comment by Nebukadneza** [comment]
Hi There,

The `Mailu`-Project is currently in a bit of a bind! We are short on man-power, and we need to judge if it is possible for us to put in some work on this issue.

To help with that, we are currently trying to find out which issues are actively keeping users from using `Mailu`, which issues have someone who want to work on them — and which issues may be less important. These a less important ones could be discarded for the time being, until the project is in a more stable and regular state once again.

In order for us to better assess this, it would be helpful if you could put a **reaction on this post** (use the :smiley: icon to the top-right).
- 👍️ if you **need this** to be able to use Mailu. Ideally, you’d also be able to test this on your installation, and provide feedback …
- 🎉 if you find it a **nice bonus**, but no deal-breaker
- 🚀 if you want to **work on it yourself**!
We want to keep this **voting open for 2 weeks** from now, so please help out!

**Comment by ook** [comment]
TBH, I'm now pretty sure it was relative to kube-system canal issues and / or coredns issues. Meanwhile I reinstall mailu on a baremetal server via docker-compose: everythings are fine for me.
