### ISSUE TITLE
nginx proxy: /webmail ok and secure, /admin fails.

### ISSUE THREAD

**Issue by dmenne** [Mailu/Mailu#1313]
Mailu Version 1.7, everything works fine when ports are accessed via ssh portforwarding.
With the nginx proxy below, access to `/webmail` works fine and is https. 
Access to `https://xxx.de/admin` forwards to `http://localhost:8443/admin/ui/` and gives: 

`400 Bad Request (The plain HTTP request was sent to HTTPS port).`

In Log: 
`front_1      | 2020/01/12 09:45:23 [info] 10#10: *3561 client sent plain HTTP request to HTTPS port while reading client request headers, client: 192.168.203. 1, server: , request: "GET /admin/ui/ HTTP/1.1", host: "localhost:8443"   `

I know that admin is handled slightly different because of security constraints. How to troubleshoot?

I suspect it has to do with:

> Using an external letsencrypt program, it tends to happen people copy the whole letsencrypt/live directory containing symlinks. Symlinks do not resolve inside the container and therefore it breaks the TLS implementation.

I also do not fully understand this sentence:

>When you are not using the embedded letsencrypt option from Mailu, you cannot make use of it’s symlink functionality in the letsencrypt/live directory. 

With a nginx proxy, do I "use the embedded letsencrypt"?

```
server {

  server_name XXX.de; # managed by Certbot
  location /admin {
    proxy_pass https://localhost:8443/admin;
  }

  location /webmail {
     proxy_pass https://localhost:8443/webmail;
  }
  listen [::]:443 ssl; # managed by Certbot
  listen 443 ssl; # managed by Certbot
  ssl_certificate /etc/letsencrypt/live/XXX.de/fullchain.pem; # managed by Certbot
  ssl_certificate_key /etc/letsencrypt/live/XXX.de/privkey.pem; # managed by Certbot
  include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
  ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
```

**Comment by dmenne** [comment]
See #848 
proxy_set_header Host $http_host;

Please add this to the documentation of the reverse proxy settings, this has cost me two days of my live for a line of code.

**Comment by kaiyou** [comment]
You are more than welcome to provide a PR to add it to the docs :)
