### ISSUE TITLE
Mail send to gmail always into spam?

### ISSUE THREAD

**Issue by nguamay** [Mailu/Mailu#1314]
Hi bro. 
My issue is: When I send a mail from Mailu to other accounts Gmail, my mail always into spam or junk.  How can I improve it?

This mail server is the first time I work, so I don't have experience with administering mail servers. Please help me.
Thanks all

**Comment by kaiyou** [comment]
You could mostly make sure that you:
- have a decent ip address for sending main, see Talos or spamhouse for testing
- make sure your reverse DNS is setup and consistent with forward records
- setup dmarc, spf and dkim, see https://mailu.io/1.7/dns.html
- build some reputation by using the mail server daily even if it is not optimal at first
- keep that reputation by not sending spam obviously

**Comment by nguamay** [comment]
![image](https://user-images.githubusercontent.com/11470118/72414718-74630780-37a5-11ea-885c-0a99674620f5.png)
![image](https://user-images.githubusercontent.com/11470118/72414984-1125a500-37a6-11ea-89df-55f9ed393fa1.png)
I see my server is full setup dmarc, spf, dkim. 
I've checked my address by test-mail. And i think it's not bad.

**Comment by kaiyou** [comment]
Did you actually copy those SPF, dkim and dmarc records to your DNS zone?

This needs to be done manually and the exact steps depend on your DNS hosting.

**Comment by kaiyou** [comment]
Do you have any feedback on the issue?

**Comment by nguamay** [comment]
> Did you actually copy those SPF, dkim and dmarc records to your DNS zone?
> 
> This needs to be done manually and the exact steps depend on your DNS hosting.

Yes i did. and I also did it again, but my mail still into box spam. :((

**Comment by kaiyou** [comment]
Could you dump us the mail headers on the gmail side so we can find out what is wrong exactly? 

Also I am reopening the issue as it is not resolved.

**Comment by nguamay** [comment]
![image](https://user-images.githubusercontent.com/11470118/72594196-78c02980-3939-11ea-8256-b711b6fa27ba.png)
![image](https://user-images.githubusercontent.com/11470118/72594341-bf158880-3939-11ea-8e06-53c801481c52.png)
these are mail i have just send and Header i check on Googletoolbox

**Comment by kaiyou** [comment]
Unfortunately every test passed, so there is not much more that can be traced back to an issue with Mailu.

Either your email address, domain, or IP address probably has a history of sending spam.

If your reverse DNS is fine as well, I could only suggest getting a different IP address. Could you maybe post a Talos and spamhaus report?

**Comment by nguamay** [comment]
hi bro.
![image](https://user-images.githubusercontent.com/11470118/72697054-1d787c00-3b71-11ea-840d-3bc07910b8f8.png)
![image](https://user-images.githubusercontent.com/11470118/72697121-54e72880-3b71-11ea-8833-37e2f713d263.png)
Those are my checking.

**Comment by exic** [comment]
After all, you can try to contact the provider (Gmail) and ask for help there. I had issues with t-online.de because they had IP ranges blocked, but they did unblock my server's IP after asking.

**Comment by kaiyou** [comment]
Any news about this?

**Comment by Nebukadneza** [comment]
Hi There,

The `Mailu`-Project is currently in a bit of a bind! We are short on man-power, and we need to judge if it is possible for us to put in some work on this issue.

To help with that, we are currently trying to find out which issues are actively keeping users from using `Mailu`, which issues have someone who want to work on them — and which issues may be less important. These a less important ones could be discarded for the time being, until the project is in a more stable and regular state once again.

In order for us to better assess this, it would be helpful if you could put a **reaction on this post** (use the :smiley: icon to the top-right).
- 👍️ if you **need this** to be able to use Mailu. Ideally, you’d also be able to test this on your installation, and provide feedback …
- 🎉 if you find it a **nice bonus**, but no deal-breaker
- 🚀 if you want to **work on it yourself**!
We want to keep this **voting open for 2 weeks** from now, so please help out!

**Comment by Nebukadneza** [comment]
Hi There,

we see this issue had only little attention 😟. As much as it pains us: In order to get the current issues a bit more manageable for us, we decided to close it. 👋👋

We hope that no one feels offended by doing so. Should the issue get really pressing in the future, please feel free to re-open it.

Thank you for your patience and understanding, 🙇
- Your Mailu Team
