### ISSUE TITLE
Dovecot: podop authentication issues

### ISSUE THREAD

**Issue by youngnicks** [Mailu/Mailu#1317]
Everything was working fine until late yesterday. I noticed the master tag of dovecot was updated around the time it stopped working. Dovecot is running but I am unable to log in due to the following error:

```
ERROR:asyncio:_GatheringFuture exception was never retrieved
future: <_GatheringFuture finished exception=Exception(503)>
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/podop/dovecot.py", line 86, in process_lookup
    key, ns=(self.user if key_type == "priv" else None)
  File "/usr/lib/python3.7/site-packages/podop/table.py", line 35, in get
    raise Exception(request.status)
Exception: 503
```

I tried restarting and redeploying everything but that did not resolve the issue. This makes me think that it is related to the latest master release.

**Comment by youngnicks** [comment]
It looks like `start.py` in dovecot and postfix is using `ADMIN_ADDRESS` environment variable, however, the `mailu-config` ConfigMap uses `HOST_ADMIN` to store the host address. Adding `ADMIN_ADDRESS: "admin-mailu-mailserver.svc.cluster.local"` resolved the issue.

Should the `start.py` scripts be updated or the `ADMIN_ADDRESS` environment variable be added?

**Comment by hanscees** [comment]
I have installed mailu yesterday in a test environment.

When sending email from roundcube without attachment all is fine.
If I add an attachment I get:
"authentication error" and also 

Connection to storage server failed.
Server Error: AUTHENTICATE PLAIN: A0003 NO Authentication rate limit from one source exceeded

Could this be related? 
In troubleshooting I do miss a general description of how the different parts are glued together. 
What is the reddis used for? 

Also, no idea howto make two email domains with identical users (a common user-case).

**Comment by Nebukadneza** [comment]
Hi There,

The `Mailu`-Project is currently in a bit of a bind! We are short on man-power, and we need to judge if it is possible for us to put in some work on this issue.

To help with that, we are currently trying to find out which issues are actively keeping users from using `Mailu`, which issues have someone who want to work on them — and which issues may be less important. These a less important ones could be discarded for the time being, until the project is in a more stable and regular state once again.

In order for us to better assess this, it would be helpful if you could put a **reaction on this post** (use the :smiley: icon to the top-right).
- 👍️ if you **need this** to be able to use Mailu. Ideally, you’d also be able to test this on your installation, and provide feedback …
- 🎉 if you find it a **nice bonus**, but no deal-breaker
- 🚀 if you want to **work on it yourself**!
We want to keep this **voting open for 2 weeks** from now, so please help out!

**Comment by mappjzc** [comment]
I have meet the same problem.
![image](https://user-images.githubusercontent.com/2921251/103256221-5814a680-49c7-11eb-8e11-9e8546e162b6.png)
It seems the rainloop host have been ban.And I think this rate don't mind sucessed or failed.Each request will be counted.
So when I visit too many times in rainloop like flush page or I operate  too many mail in same time .It will count many times,and  "NO Authentication rate limit from one source exceeded" happend.
I want to know if it can setting white list.The rainloop host must be attach in the white list with no limit.
And for the rainloop's login limit.It is better checked by rainloop self.

**Comment by mappjzc** [comment]
I used default setting. that 10 times for each min.
And when I delete 4 mail together in rainloop.It sucessed.
And when I delete 5th mail.I will see the red  words "Authentication failed" on the mail list in rainloop.
I guess it must be count 2 times in each delete.

**Comment by adri66** [comment]
Hi, 
I hope these informations can help someones
I get the error on the dovecot container logs
`ERROR:asyncio:_GatheringFuture exception was never retrieved
future: <_GatheringFuture finished exception=ClientConnectorError(ConnectionKey(host='192.168.203.8', port=80, is_ssl=False, ssl=None, proxy=None, proxy_auth=None, proxy_headers_hash=None), ConnectionRefusedError(111, "Connect call failed ('192.168.203.8', 80)"))>
`
After a network inspect, I found that the IP 192.168.203.8 is related to the smtp container.
I try that and it solve my problem
`docker-compose restart smtp
docker-compose restart imap`

The problem came after a change of AUTH_RATELIMIT in the env file and a full restart of mailu
One other things to know, the frontend is proxied with caddy.

Thank you for the work of the mailu team 😄 
Adri
