### ISSUE TITLE
Value of HOST_ANTISPAM is confusing.

### ISSUE THREAD

**Issue by frgomes** [Mailu/Mailu#1325]
```python
./core/dovecot/start.py:27:os.environ["ANTISPAM_ADDRESS"] = system.resolve_address(os.environ.get("HOST_ANTISPAM", "antispam:11334"))
./core/postfix/start.py:31:os.environ["ANTISPAM_ADDRESS"] = system.resolve_address(os.environ.get("HOST_ANTISPAM", "antispam:11332"))
```

At first glance, the code looks like incorrect for a newbie like me.
In fact, the code is correct. The only "problem" is that the same symbol ``HOST_ANTISPAM`` is playing two roles, which is confusing and conceptually incorrect since a symbol should play one and only one role.

Also, the documentation states that it should be port 11334, which is misleading, since it must be 11332 in the case of container ``smtp``.

**Comment by micw** [comment]
Antispam has 2 addresses, so only one works and things break when ANTISPAM_ADDRESS is set. This was addressed and fixed in the current master and will work again on 1.8.

**Comment by micw** [comment]
(closing because it's fixed in the master)
