### ISSUE TITLE
Rspamd

### ISSUE THREAD

**Issue by adi90x** [Mailu/Mailu#133]
Hello, 
I am not sure if it is normal or not but path are not the same in rspamd between master and stable branch while files content seems to be the same.

Using latest , my rspamd containers always restart with log showing : 
`Error relocating /usr/lib/libglib-2.0.so.0: pthread_setname_np: symbol not found` 
`tail: can't open '/var/log/rspamd/rspamd.log': No such file or directory`
`tail: no files`

But using rspamd stable version works perfectly (even thought all other containers are in latest version )!

**Comment by tronicum** [comment]
thanks. just had that problem, too.

**Comment by benbender** [comment]
I just experienced the same problem in a different image with rspamd and found a solution. You have to update musl and musl-utils to fix the error.

```
FROM alpine:edge

#We have to upgrade musl, or rspamd will not work =(
RUN echo 'http://dl-cdn.alpinelinux.org/alpine/edge/testing' >> /etc/apk/repositories && \
	apk add --no-cache --upgrade musl musl-utils && \
	apk add --no-cache rspamd rsyslog
```

**Comment by adi90x** [comment]
Adding : 
`RUN touch /var/log/rspamd/rspamd.log`  to the rspamd dockerfile enable container to be up and running although there is still an issue in logs : 
`Error relocating /usr/lib/libglib-2.0.so.0: pthread_setname_np: symbol not found` ...

**Comment by kaiyou** [comment]
Thank you for the feedback and sorry for the late replies recently.

It does sound like ``musl`` had to be rebuilt to link properly to glib. Thank you @benbender. I do not have access to my favourite editor, would anyone be able to make a pull request for a temporary fix upgrading ``musl`` in the Dockerfile ?

**Comment by kaiyou** [comment]
Thank you, a fix was merged in ``master``. I will have access to my personal computer tonight and can check that it is working before cherry-picking in ``stable``.

**Comment by kaiyou** [comment]
It seems to be fixed upstream, I just removed the fix from master. I will try and rebuild stable.

**Comment by kaiyou** [comment]
Just finishes rebuilding, it runs fine on my test server and laptop. Can anyone else check before we close the bug?

**Comment by adi90x** [comment]
Just pull it from Docker Hub,  work fine too !

**Comment by kaiyou** [comment]
Perfect, still waiting for Dovecot build to finish (unrelated failure due to inconsistent ABI builds on Alpine) and I will close this. Stable branch should be fine too.
