### ISSUE TITLE
Discussion: Create issue templates for github

### ISSUE THREAD

**Issue by micw** [Mailu/Mailu#1331]
We currently have many unstructured issue report, mixed with support requests and feature requests. For many we don't even know the affected Mailu version. We should create issue templates for the type of issues we'd like to support (bugs and feature requests at least) and define mandatory information we require.
We should also decide if we accept support requests in the issue tracker (IMO we should point to the chat here and close support request issues).

**Comment by Nebukadneza** [comment]
Hej,

in the meeting linked above, we discussed a very rough draft of how the template could look like. Before opening a PR, maybe it’d make sense to discuss it in here. The draft (with some things filled out a bit more):

```
Thank you for opening an issue with Mailu. Please understand that issue are meant for bugs and enhancement-requests — for user-support questions, please first try to reach out to us on the [Matrix Chat](https://matrix.to/#/#mailu:tedomum.net).

To be able to help you best, we need some more information …

## Before you open your issue
- [ ] Check if no issue or pull-request for this exists
- [ ] Check documentation and FAQ <add link>
- Please understand `Mailu` is made by volunteers in their free time — be concise, civil and accept that delays can occur.

## Description
Please describe what the bug is. A rough guideline can be:
- a brief description what you did to trigger it
- a brief description of what did, in fact, happen
- a brief description of what you expected to happen

## Environment & Versions
Please tell us what environment you run this on:
- what architecture (X86, ARM)
- which deployment method: Compose/Stack/Kubernetes <Todo: add hint how to find out>
- versions of your system-services (docker/docker-compose versions, …) <Todo: add hint how to find out>

## Replication Steps
Please describe how we can reproduce the unwanted behavior (in case of a bug)

## Logs
<Todo: write something: If applicable, describe / link to documentation how to get logs. Tell user to scan logs for private information>
```

This is just a first base for discussion. I’m not sure it makes sense to go this verbose in the first … another approach would be go for a very lean, slim description and see if that already blocks off most under-described issues without pressing the user and her/his thoughts into a tight corset.
What do you think which way is better?

For the record, there are some issue templates used by other projects collected here:
https://github.com/stevemao/github-issue-templates
https://github.com/devspace/awesome-github-templates

**Comment by liquidat** [comment]
I would like to have some more structure in the issues. And the template is good enough I'd say to start with. We can still update it if we realize that we have special requirements.

**Comment by Diman0** [comment]
I created a PR for a bug template. I'd say we first merge this and configure it as the issue template. After that we can always make changes to it.
