### ISSUE TITLE
Roundcube managesieve fails on IPv6

### ISSUE THREAD

**Issue by PhilRW** [Mailu/Mailu#1336]
I have assigned a globally-routable IPv6 network to the docker-compose stack. Rainloop sieve management works correctly but Roundcube fails. Looking at the logs, Roundcube attempts to connect to sieve via IPv6. Hard-coding $imap to the IPv4 address of the imap docker container allows Roundcube sieve to function properly. I believe it is related to this in the debug log of imap:

`DEBUG:root:Table get passdb/[username redated] is {'allow_nets': '192.168.203.0/24', 'nopassword': 'Y', 'password': None}`

Using version 1.7.

**Comment by PhilRW** [comment]
My current workaround is setting the POD_ADDRESS_RANGE to the same value as SUBNET6.

**Comment by PhilRW** [comment]
Ignore that. That breaks SMTP.

**Comment by kaiyou** [comment]
Just reviewer your PR, this should be on its way :)
