### ISSUE TITLE
Support for usernames without domain part (default domain)

### ISSUE THREAD

**Issue by warmanton** [Mailu/Mailu#1339]
Looks like that current version of Mailu-1.7 does not support usernames without domain part i.e. with default domain. It is very hard to migrate from some old mail system where 1000 users have configured their MUA without domain name.

Perhaps this is a feature request to have some default domain which is used if user provide username without "@somedomain.com" but "username@somedomain.com" should work too.

**Comment by Nebukadneza** [comment]
Hi There,

The `Mailu`-Project is currently in a bit of a bind! We are short on man-power, and we need to judge if it is possible for us to put in some work on this issue.

To help with that, we are currently trying to find out which issues are actively keeping users from using `Mailu`, which issues have someone who want to work on them — and which issues may be less important. These a less important ones could be discarded for the time being, until the project is in a more stable and regular state once again.

In order for us to better assess this, it would be helpful if you could put a **reaction on this post** (use the :smiley: icon to the top-right).
- 👍️ if you **need this** to be able to use Mailu. Ideally, you’d also be able to test this on your installation, and provide feedback …
- 🎉 if you find it a **nice bonus**, but no deal-breaker
- 🚀 if you want to **work on it yourself**!
We want to keep this **voting open for 2 weeks** from now, so please help out!

**Comment by Diman0** [comment]
After discussing this during the last meeting, we decided we do not want to support this feature.  We do not support  email addresses without the domain part. Using a full email address is a requirement for using Mailu.

**Comment by nathanielhourt** [comment]
I wanted this. So I wrote it myself. Diff from branch `2.0`:

```diff
diff --git a/core/admin/mailu/configuration.py b/core/admin/mailu/configuration.py
index bc91c332..c420ecd2 100644
--- a/core/admin/mailu/configuration.py
+++ b/core/admin/mailu/configuration.py
@@ -36,6 +36,7 @@ DEFAULT_CONFIG = {
     'SECRET_KEY': 'changeMe',
     'DOMAIN': 'mailu.io',
     'HOSTNAMES': 'mail.mailu.io,alternative.mailu.io,yetanother.mailu.io',
+    'DEFAULT_LOGIN_DOMAIN': '',
     'POSTMASTER': 'postmaster',
     'WILDCARD_SENDERS': '',
     'TLS_FLAVOR': 'cert',
diff --git a/core/admin/mailu/sso/forms.py b/core/admin/mailu/sso/forms.py
index c01ef572..99bc704e 100644
--- a/core/admin/mailu/sso/forms.py
+++ b/core/admin/mailu/sso/forms.py
@@ -5,7 +5,7 @@ import flask_wtf
 class LoginForm(flask_wtf.FlaskForm):
     class Meta:
         csrf = False
-    email = fields.StringField(_('E-mail'), [validators.Email(), validators.DataRequired()], render_kw={'autofocus': True})
+    email = fields.StringField(_('E-mail'), [validators.DataRequired()], render_kw={'autofocus': True})
     pw = fields.PasswordField(_('Password'), [validators.DataRequired()])
     pwned = fields.HiddenField(label='', default=-1)
     submitWebmail = fields.SubmitField(_('Sign in'))
diff --git a/core/admin/mailu/sso/views/base.py b/core/admin/mailu/sso/views/base.py
index b2e6027f..6f976ce5 100644
--- a/core/admin/mailu/sso/views/base.py
+++ b/core/admin/mailu/sso/views/base.py
@@ -42,6 +42,8 @@ def login():
                 destination = app.config['WEB_WEBMAIL']
         device_cookie, device_cookie_username = utils.limiter.parse_device_cookie(flask.request.cookies.get('rate_limit'))
         username = form.email.data
+        if not '@' in username and app.config['DEFAULT_LOGIN_DOMAIN']:
+            username = username + '@' + app.config['DEFAULT_LOGIN_DOMAIN']
         if not utils.is_app_token(form.pw.data):
             if username != device_cookie_username and utils.limiter.should_rate_limit_ip(client_ip):
                 flask.flash('Too many attempts from your IP (rate-limit)', 'error')
```

After that, edit your `mailu.env` and add your default domain:

```
# Default domain for usernames if one is not entered manually
DEFAULT_LOGIN_DOMAIN=mymaildomain.com
```

#WorksForMe
