### ISSUE TITLE
Aliases don't work if the alias address is also an account

### ISSUE THREAD

**Issue by cobrafast** [Mailu/Mailu#1342]
As title says, aliases don't forward any emails if the original address is also an account.
An incoming email is correctly delivered to the account but not forwarded to the alias addresses.

Perhaps aliases are the wrong tool for what I'm trying to achieve but on my old Froxlor-based setup it did work this way.

Example:
```
Account: bob@domain.com
Alias:   bob@domain.com -> foo@elsewhere.net, bar@example.org
```
Incoming email to `bob@domain.com` in mailbox but not forwarded to foo or bar.

**Comment by hoellen** [comment]
As you already thought, you're using the wrong tool for it. What you're searching is the feature "auto-forwarding". If you log in to the admin page with `bob@domain.com` you can set the e-mail addresses `foo@elsewhere.net` and `bar@example.org` for forwarding. If Bob should also get the mails you need to check "Keep a copy of the emails".

**Comment by cobrafast** [comment]
Thanks, that worked.
