### ISSUE TITLE
Unable to use external mail apps

### ISSUE THREAD

**Issue by Bencey** [Mailu/Mailu#1353]
Hi, Im trying to connect my email to an external application EG thunderbird and i am using the details in client setup. But when I am clicking add the application says failed to connect to the server

I have port fowarded but still happens. Any idea why? Thanks

**Comment by kaiyou** [comment]
No specific idea unfortunately, you would need to provide a bit more details about your setup. Could you paste the specific error from Thunderbird?

Also, can you access your email through the Webmail? could you check that everything is running fine, e.g. :

```
ss -lntp
docker-compose ps
```

**Comment by Bencey** [comment]
Figured it out, Make sure if you are using cloudflare that you disable the proxy on the A record as it only proxies http
