### ISSUE TITLE
Garbled text on iOS

### ISSUE THREAD

**Issue by iohenkies** [Mailu/Mailu#1356]
Hi all,

This has been happening since I transferred all my mail to Mailu.

I’ve got quite a lot of filed mail and folders. Whenever I move a message to one of my filed mail folders, after moving the message and opening it from its new folder, the text appears to be garbled / scrambled when I open the email from my iPad or iPhone. Looking at the same message on my laptop mail client and from the webmail, all is good.

I think it only happens when there is a image (like in a signature) in the email. Is this an encoding issue? How to solve it?

Example message from iOS device:

```
Hey = iohenkies, 

Bedankt = voor je inzicht. Weet ik dat ik daar mijn tijd niet aan moet = besteden. 
Werkse en tot de volgende = borrel!

Met vriendelijke groet,
-- 
Company 	=
 Micha=C3=ABl Veentjer=E2=80=A2Sales team
```

All the = and about the entire last line appear scrambled.

**Comment by iohenkies** [comment]
Hi all. Nobody seeing this behavior?

**Comment by Bones-IOS** [comment]
> Hi all. Nobody seeing this behavior?

I do on my IOS Devices with Apple Mail.  OSX behaves fine using the same iCloud mailbox.!?!?

Example: Excerpt from a recent email sent from my gmail account

“today is demolition day for my neighbor’s leaning styrofoam wall.  We’re going to rebuild a common one with a real foundation and stones.  Six weeks of dust!”

Excerpt after moving the above sent email to an iCloud mailbox in my IOS Mail app:

“today is demolition day f= or my neighbor=E2=80=99s leaning styrofoam wall.  We=E2=80=99re going t= o rebuild a common one with a real foundation and stones.  Six weeks of= dust!”

I think it’s pretty well what you experience.  I am shocked there not more reports.

**Comment by iohenkies** [comment]
For me it makes it unworkable. As you can see: no reactions or other reports. I’ll be moving from Docker (compose) to Kubernetes soon for all my workloads and will then move to something different for my mail as well.

**Comment by Nebukadneza** [comment]
Hi There,

The `Mailu`-Project is currently in a bit of a bind! We are short on man-power, and we need to judge if it is possible for us to put in some work on this issue.

To help with that, we are currently trying to find out which issues are actively keeping users from using `Mailu`, which issues have someone who want to work on them — and which issues may be less important. These a less important ones could be discarded for the time being, until the project is in a more stable and regular state once again.

In order for us to better assess this, it would be helpful if you could put a **reaction on this post** (use the :smiley: icon to the top-right).
- 👍️ if you **need this** to be able to use Mailu. Ideally, you’d also be able to test this on your installation, and provide feedback …
- 🎉 if you find it a **nice bonus**, but no deal-breaker
- 🚀 if you want to **work on it yourself**!
We want to keep this **voting open for 2 weeks** from now, so please help out!

**Comment by Diman0** [comment]
I cannot replicate this with Thunderbird. Do you have the same issue with non Apple email clients?

**Comment by iohenkies** [comment]
Thanks for the reply. As mentioned in the OP, this is only on (all) iOS device. On the Apple mail client this is no problem and via webmail all is good as well.

**Comment by Bones-IOS** [comment]
I agree.
The corruption only happens (for me) when the email is moved to a folder and then reopened from that folder.
Going to the Google or iCloud sites, one finds the emails as they were received.

Here’s an example:

On iCloud:
Hello, all.  The problem with the schedule has been corrected and 2020 is now also available.  Sorry for the confusion; it was my mistake and I was distracted over the last few days.
With Kind Regards,

On my iPad:
Hello, all.  The problem with the schedule has been c= orrected and 2020 is now also available.=C2=A0 Sorry for the=C2=A0confusion= ; it was my=C2=A0mistake and I was distracted over the last few days.
With Kind Reg= ards,

Any suggestions would be appreciated.

**Comment by Diman0** [comment]
This sounds like a bug in the iOS mail client. I'm not sure how we can assist you. Maybe you can create a support ticket on the Apple forum?
As an alternative you could perhaps try alternative email apps on your iOS device.

**Comment by iohenkies** [comment]
The problem as described by Bones is exactly my problem as described in the OP.

This is in my opinion not a bug in iOS as this is only when the backend is mailu. I've supported many iOS devices in the past and never encountered this issue before. This is really only with mailu.

**Comment by HorayNarea** [comment]
I can't replicate this with Apple Mail on iOS 14.0.1 with Mailu 1.7

Which iOS/Mailu Versions are you using @iohenkies and @Bones-IOS ?

**Comment by iohenkies** [comment]
For me it is iOS 13.7 (I can update, no problem) and Mailu 1.7. Please try with multiple accounts as well. Moving a message from account A into a folder in account B and then opening that folder and message.

**Comment by ofthesun9** [comment]
I reproduced it as well (Need to move an email to another account (Gmail here) to trigger the bug.

**Comment by Diman0** [comment]
Can you compare the raw source of the email before and after moving the email?
Maybe the content-type has changed when moving the email?
Of course the same comparison should also be made when a different email client (e.g. webmail) is used to do this action.

@ofthesun9 what version do you use of iOS? @HorayNarea  cannot replicate on iOS 14.0.1.

**Comment by HorayNarea** [comment]
> Please try with multiple accounts as well. Moving a message from account A into a folder in account B and then opening that folder and message.

I tried moving a mail from/to a mailu account to/from a gmail account, no corruption happening :/

**Comment by ofthesun9** [comment]
I am on iOS 13.7
Spark (another mail client on iOS) is reading ok the "corrupted" mail...

**Comment by Diman0** [comment]
Have any of you tried to update your iOS 13 apple device to iOS 14? Does this resolve the issue with the apple mail client?

**Comment by iohenkies** [comment]
I've updated to iOS 14. For existing emails it is not solved, which is actually undesirable on itself since there are so many. For new emails moving to folders I have to wait and see the next couple of days.

**Comment by Bones-IOS** [comment]
Hello guys,
Since updating to 14.0.1, Mail is behaving properly.  Messages moved to various folders now stay as received in the inboxes.  Messages moved to folders before the update are still corrupted.
On the Gmail and iCloud servers, the messages are all good.
So, it looks like the IOS mail app was corrupting the messages when being moved to a folder.  Due to the minimum amount of people complaining about the problem, I tend to believe that the app itself got corrupted somehow.?!?!  My spouse’s iPad never got the problem.

**Comment by iohenkies** [comment]
It seems I’ve got the same results! I do like to point out though, that although this has been solved by an iOS update, this issue was only with the Mailu backend and I’m absolutely positive of that because I have a lot of different mail accounts and domains.

Any chance we can get the messages that were moved before the update and got corrupted, fixed?
