### ISSUE TITLE
Add ability to specify SMTP port

### ISSUE THREAD

**Issue by PhilRW** [Mailu/Mailu#1357]
Some relayed domains may live on machines that accept SMTP on a nonstandard port, e.g., port 2525. This would allow users to relay for domains by appending `:port` to the hostname or IP address.

**Comment by SomeGeek** [comment]
Is it possible to add an option for mark a server as lmtp?

**Comment by PhilRW** [comment]
I think in that case we'd want to rewrite the UI a bit to account for transport, host, and port.
