### ISSUE TITLE
Insufficient input validation in  /internal endpoint

### ISSUE THREAD

**Issue by sbias** [Mailu/Mailu#1361]
It seems like it is possible to crash a thread of flask by sending an invalid utf-8 username.
As far as i can see, this can not be used to gain access (should be validated).

Here are logs to reproduce this.

[error] 56#56: *1312970 auth http server 127.0.0.1:8000 did not send server or port while in http auth state, client: xx.xx.xx.xx, server: 0.0.0.0:25, login: "xxxxxxxxx\ufffdn@xxxx.xxxx"

GET /internal/auth/email HTTP/1.0" 500 290 "-" "-"

ERROR in app: Exception on /internal/auth/email [GET]
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python3.7/site-packages/flask_limiter/extension.py", line 544, in __inner
    return obj(*a, **k)
  File "/app/mailu/internal/views/auth.py", line 18, in nginx_authentication
    headers = nginx.handle_authentication(flask.request.headers)
  File "/app/mailu/internal/nginx.py", line 45, in handle_authentication
    user_email = raw_user_email.encode("iso8859-1").decode("utf8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xed in position 6: invalid continuation byte

xx.xx.xx.xx - - [xx/xx/xxxx:xx:xx:xx +0000] "GET /internal/auth/email HTTP/1.0" 500 290 "-" "-"

**Comment by kaiyou** [comment]
I confirm this cannot be used to gain access.

Did you encounter this during normal use of Mailu? If not I am in favor of just dropping non-utf8 usernames

**Comment by sbias** [comment]
I get this a few times a day. In fact this report is a real case.
I don't want to drop any usernames at all, maybe better errorhandling is a solution? UnicodeDecodeError is a quite explicit exception. catch it and return a 404?

**Comment by kaiyou** [comment]
Yep, probably the best fix :)

**Comment by Nebukadneza** [comment]
Hi There,

The `Mailu`-Project is currently in a bit of a bind! We are short on man-power, and we need to judge if it is possible for us to put in some work on this issue.

To help with that, we are currently trying to find out which issues are actively keeping users from using `Mailu`, which issues have someone who want to work on them — and which issues may be less important. These a less important ones could be discarded for the time being, until the project is in a more stable and regular state once again.

In order for us to better assess this, it would be helpful if you could put a **reaction on this post** (use the :smiley: icon to the top-right).
- 👍️ if you **need this** to be able to use Mailu. Ideally, you’d also be able to test this on your installation, and provide feedback …
- 🎉 if you find it a **nice bonus**, but no deal-breaker
- 🚀 if you want to **work on it yourself**!
We want to keep this **voting open for 2 weeks** from now, so please help out!

**Comment by sbias** [comment]
Why stale-bot is targeting this? This is a bug and should be resolved sometime. Just closing does not fix the issue

**Comment by HaleyACS** [comment]
I get that error quite often too BTW.
Any chance we could address it?
