### ISSUE TITLE
Strange behavior of user updated_at field

### ISSUE THREAD

**Issue by sbias** [Mailu/Mailu#1363]
I have mailboxes with updated_at date of today. After some testing i found that this field is updated once a mailbox is receiving a new mail. Can somebody confirm this?

I use the default sqlite backend.
EDIT:

seems like /internal/dovecot/quota/* endpoint is updating the user entry and refreshing the changed_at date for that row.

**Comment by kaiyou** [comment]
This is long time regression. I will update recommendations in the security adviso and we need to check how to avoid this using sqlalchemy.

**Comment by Nebukadneza** [comment]
Hi There,

The `Mailu`-Project is currently in a bit of a bind! We are short on man-power, and we need to judge if it is possible for us to put in some work on this issue.

To help with that, we are currently trying to find out which issues are actively keeping users from using `Mailu`, which issues have someone who want to work on them — and which issues may be less important. These a less important ones could be discarded for the time being, until the project is in a more stable and regular state once again.

In order for us to better assess this, it would be helpful if you could put a **reaction on this post** (use the :smiley: icon to the top-right).
- 👍️ if you **need this** to be able to use Mailu. Ideally, you’d also be able to test this on your installation, and provide feedback …
- 🎉 if you find it a **nice bonus**, but no deal-breaker
- 🚀 if you want to **work on it yourself**!
We want to keep this **voting open for 2 weeks** from now, so please help out!

**Comment by sbias** [comment]
Why stale-bot is targeting this? This is a bug and should be resolved since it makes the updated_at field completly useless. Past has shown that it might be security related to know when a account has modified. Just closing does not fix the issue.
