### ISSUE TITLE
Cannot add additional aliases

### ISSUE THREAD

**Issue by vogelfreiheit** [Mailu/Mailu#1365]
I have a domain with an associated alternative name that has stopped working in the UI: when I click on the New alias button, nothing actually happens.

```
HTTP/1.1 302 FOUND
Server: nginx/XXX
Date: Fri, 14 Feb 2020 15:48:41 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 285
Connection: keep-alive
Location: http://XXX/ui/alias/list/affectedomain.tld
Vary: Cookie
Set-Cookie: XXX; HttpOnly; Path=/
Strict-Transport-Security: max-age=31536000
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
X-Permitted-Cross-Domain-Policies: none
X-XSS-Protection: 1; mode=block
Referrer-Policy: same-origin
```

Looking at the request and response headers, it seems some redirection is happening. I have not changed anything lately. The reverse proxy nginx config has been exactly the same all the time.

**Comment by Nebukadneza** [comment]
Hi There,

The `Mailu`-Project is currently in a bit of a bind! We are short on man-power, and we need to judge if it is possible for us to put in some work on this issue.

To help with that, we are currently trying to find out which issues are actively keeping users from using `Mailu`, which issues have someone who want to work on them — and which issues may be less important. These a less important ones could be discarded for the time being, until the project is in a more stable and regular state once again.

In order for us to better assess this, it would be helpful if you could put a **reaction on this post** (use the :smiley: icon to the top-right).
- 👍️ if you **need this** to be able to use Mailu. Ideally, you’d also be able to test this on your installation, and provide feedback …
- 🎉 if you find it a **nice bonus**, but no deal-breaker
- 🚀 if you want to **work on it yourself**!
We want to keep this **voting open for 2 weeks** from now, so please help out!

**Comment by Nebukadneza** [comment]
Hi! I just tried to reproduce this on `master` and 1.7 … and couldn’t make the issue happen. Additionally you didn’t report back. If you have any details, such as the logs from `admin`, please feel free to reopen this.

we see this issue had only little attention 😟. As much as it pains us: In order to get the current issues a bit more manageable for us, we decided to close it. 👋👋

We hope that no one feels offended by doing so. Should the issue get really pressing in the future, please feel free to re-open it.

Thank you for your patience and understanding, 🙇
- Your Mailu Team

**Comment by Bambie07** [comment]
Sorry for writing to a closed issue.

I got the same problem with one of my domains hosted with mailu. With alle other domains alias creation works. In my case there was an alias limit set in the admin ui. Increasing the limit solved the problem. Maybe it's possible to implement a message which says "alias limit reached" when trying to create another one. Maybe the mailbox limit is also affected (not tested)?

mailu with docker and version 1.7 used
