### ISSUE TITLE
Request a delivery receipt

### ISSUE THREAD

**Issue by IT-MBiT** [Mailu/Mailu#1369]
Hi! Thank you very much for your replay about "Maximum number of connections from user+IP exceeded" it works fine!
We have another problem... When we send an e-mail with a "request of delivery receipt" return notification don't arrive and we don't know how... We don't know if request is not sended or if notification is "trashed" when arrive by our server.
How we can resolve this problem?

**Comment by Nebukadneza** [comment]
Hi There,

The `Mailu`-Project is currently in a bit of a bind! We are short on man-power, and we need to judge if it is possible for us to put in some work on this issue.

To help with that, we are currently trying to find out which issues are actively keeping users from using `Mailu`, which issues have someone who want to work on them — and which issues may be less important. These a less important ones could be discarded for the time being, until the project is in a more stable and regular state once again.

In order for us to better assess this, it would be helpful if you could put a **reaction on this post** (use the :smiley: icon to the top-right).
- 👍️ if you **need this** to be able to use Mailu. Ideally, you’d also be able to test this on your installation, and provide feedback …
- 🎉 if you find it a **nice bonus**, but no deal-breaker
- 🚀 if you want to **work on it yourself**!
We want to keep this **voting open for 2 weeks** from now, so please help out!
