### ISSUE TITLE
Image option error on new install.

### ISSUE THREAD

**Issue by Phrenzy** [Mailu/Mailu#1371]
I'm trying to setup Mailu on a new 18.04 instance in AWS. My docker version is 19.03.6. My docker-compose version is 1.17.1.

I used the Mailu setup page to generate the setup files. When I run the command "docker-compose -p mailu up -d," I get the following error:

ERROR: Invalid interpolation format for "image" option in service "webdav": "${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}radicale:${MAILU_VERSION:-1.7}"

I did some playing around in the docker-compose.yml file and I got some progress. I changed all the image lines, such as:

image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}roundcube:${MAILU_VERSION:-1.7}

to 

image: mailu/roundcube

I was able to get past the issue and get a little further in the process, but I am concerned if I got my install to work in that manner, I may have something misconfigured. 

Is this an issue on my end? Or has an update to docker-compose causing an issue with your config files? Or is this a completely different issue?

I really like what you got going on here and I look forward to getting my install up and running. Thank you.

**Comment by ToBoNaToR3** [comment]
Did you install docker-compose with apt or the official way on the docker docs? If you used apt, try to remove docker- compose and install it as described in the official docker Docs [https://docs.docker.com/compose/install/](https://docs.docker.com/compose/install/) 
I had the same issue some days ago and this solved it for me.

**Comment by Phrenzy** [comment]
Installing docker-compose in the way you suggested solved my issue. Thank you.
