### ISSUE TITLE
Setup utility v1.6 redirects to v1.7

### ISSUE THREAD

**Issue by ss89** [Mailu/Mailu#1372]
I wanted to upgrade my mailu in multiple steps from 1.5 to 1.6 and afterwards to 1.7 (if everything went smooth).

However the setup utility (https://setup.mailu.io/1.6/) redirects to https://setup.mailu.io/1.7/ right away.

Due to that, i tried to upgrade to 1.7 right away, which resulted in roundcube greeting me with authentication errors. imap authentication via mail client didn't work as well. So it seems that upgrading from 1.5 to 1.7 doesn't seem to be possible in one step? At least the documentation doesn't seem to mention something.

Action that should be taken:
* Remove redirect from 1.6 to 1.7
* Write more detailed upgrade instructions, especially for stuff that might not seem obvious.

**Comment by flowgunso** [comment]
While I agree with you the 1.6 to 1.7 redirection is confusing, upgrading from 1.5 to 1.7 in a single step without going through 1.6 is possible. I just did.

#904 mentions the authentication issues you have faced, which I've faced too.

Be cautious that the Docker subnet created matches the one written in your `docker-compose.yml` and `mailu.env`. Also, the `PASSWORD_SCHEME` from 1.5 is `SHA512-CRYPT`.

**Comment by ss89** [comment]
Did the upgrade today. Aside some adjustment i had to do in dovecot (because i did come from a plain dovecot before with a maildir layout and option LAYOUT=fs) everything went quite smooth. I had issues with google mail relay, but got them solved by using the right env vars.
