### ISSUE TITLE
Roundcube: Authentication credentials invalid

### ISSUE THREAD

**Issue by ferllings** [Mailu/Mailu#1375]
Hello,

I have an authentication issue with roundcube:
I created a fresh mailu (master) install using the helm chart.
I can login admin and roundcube using the admin account.
Then I created a new user 'ferllings': I can login admin but not roundcube:
front log:
```
 10.42.0.1 - - [25/Feb/2020:08:21:16 +0000] "GET /health HTTP/1.1" 204 0 "-" "kube-probe/1.16"                             │
│ 2020/02/25 08:21:20 [info] 12#12: *700 client 10.42.0.100:57654 connected to 0.0.0.0:10143                                │
│ 2020/02/25 08:21:20 [info] 12#12: *700 client login failed: "Authentication credentials invalid" while in http auth state │
│ , client: 10.42.0.100, server: 0.0.0.0:10143, login: "ferllings@xxxx.net"                                               │
│ 127.0.0.1 - - [25/Feb/2020:08:21:20 +0000] "GET /auth/email HTTP/1.0" 200 0 "-" "-"                                       │
│ 10.42.0.1 - - [25/Feb/2020:08:21:21 +0000] "GET /health HTTP/1.1" 204 0 "-" "kube-probe/1.16"
```

roundcube log:
```
│ 10.42.0.1 - - [25/Feb/2020:08:25:17 +0000] "GET / HTTP/1.1" 200 2691 "-" "kube-probe/1.16"                                │
│ 10.42.0.101 - - [25/Feb/2020:08:25:17 +0000] "POST /?_task=login HTTP/1.1" 401 2830 "http://mail.xxx.net/?_task=logi │
│ n" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:73.0) Gecko/20100101 Firefox/73.0"                                   │
│ 10.42.0.1 - - [25/Feb/2020:08:25:22 +0000] "GET / HTTP/1.1" 200 2692 "-" "kube-probe/1.16"
```

Of course I changed the password to be sure, and I even resinstalled mailu.

Am I missing something?

Thanks for your help.

**Comment by rouja** [comment]
Hi,

Could you test the user authentication against the basic auth endpoint of the admin pod to be sure the user is ok ? 

```
kubectl -n $MAILU_NAMESPACE get po |grep admin
kubectl -n $MAILU_NAMESPACE exec -it $MAILU_ADMIN_POD /bin/bash
curl -I -u "$USER@$DOMAIN:$USER_PASSWORD" http://127.0.0.1/internal/auth/basic
```
The last command should return something like **HTTP/1.1 200 OK**. If you receive something like **HTTP/1.1 401 UNAUTHORIZED**, It probably means that your user/password isn't good or that something went wrond when you created your user.

**Comment by ferllings** [comment]
It returns: HTTP/1.1 200 OK

**Comment by elfrinjo** [comment]
Did you turn off IMAP or POP3? For what I see, at least rainloop needs both of them and returns Auth failed when one of them is missing

**Comment by rouja** [comment]
Hello,

The user seems ok. Which ingress are you using (nginx, traefik..) ?

Could you give the output of this command please :

```
kubectl -n "$NAMESPACE" get po,svc,ingress,deployment
```

**Comment by ferllings** [comment]
> Did you turn off IMAP or POP3? For what I see, at least rainloop needs both of them and returns Auth failed when one of them is missing

Thanks @elfrinjo that was it !! I had pop3 disabled
