### ISSUE TITLE
roundcube didn't listen on port 80

### ISSUE THREAD

**Issue by mamiapatrick** [Mailu/Mailu#1376]
Hello,

I deploy mailu on my kubernetes cluster. I choose roundcube as webmail but I notice that I cannot login in webmail and when try to debuging I enter into the shell of roundcube pod. It seems that the pod refused connection on port 80...I try "curl on localhost" and connection is refused. It is weird and I don't know why because the Apache conf listen on port 80 and there a virtualhost in the site enabled. Do someone already face this issue

**Comment by rouja** [comment]
Hi,

It works on my k8s cluster.

How did you install mailu on your k8s cluster ? Did you use the helm chart : https://github.com/Mailu/helm-charts ? 

Could you give the output of this command please : 
```
kubectl -n "$NAMESPACE" get po,svc,ingress,deployment
```

**Comment by mamiapatrick** [comment]
Hello @rouja i finally install another roundcube, the official image and set it up to work with mailu. Thanks
