### ISSUE TITLE
Overriding master.cf Settings does not seem to work

### ISSUE THREAD

**Issue by vanthome** [Mailu/Mailu#1378]
I created the file `postfix.master` with the following content and tested that it can be applied using `postconfig -Me`:

`10025/inet="10025 inet n       -       n       -       -       smtpd -o smtpd_sasl_auth_enable=yes -o smtpd_client_restrictions=reject_unlisted_sender,permit -o smtpd_reject_unlisted_recipient=no -o cleanup_service_name=outclean"`

I also checked that it's mapped in the container under `/overrides/postfix.master`.

The issue is that it does not seem to be applied.

**Comment by mathew3** [comment]
hey @vanthome, I have a similar issue with overriding postfix's `master.cf` with `postfix.master`. Have you checked the logs after restarting postfix?

`docker-compose logs -f smtp`

**Comment by Alivekeep** [comment]
I have solution for this:

Need just overrride a config line without "" symbols, like that:

`10025/inet=10025 inet n - n - - smtpd -o smtpd_sasl_auth_enable=yes -o smtpd_client_restrictions=reject_unlisted_sender,permit -o smtpd_reject_unlisted_recipient=no -o cleanup_service_name=outclean`

and after that, script start.py will parse file and apply command to **postconf**


Examples:

Your case, from start.py script eye:

`postconf -Me "10025/inet="10025 inet n - n - - smtpd -o smtpd_sasl_auth_enable=yes -o smtpd_client_restrictions=reject_unlisted_sender,permit -o smtpd_reject_unlisted_recipient=no -o cleanup_service_name=outclean""` - you see mistake?)

My case, from start.py script eye:
`postconf -Me "10025/inet=10025 inet n - n - - smtpd -o smtpd_sasl_auth_enable=yes -o smtpd_client_restrictions=reject_unlisted_sender,permit -o smtpd_reject_unlisted_recipient=no -o cleanup_service_name=outclean"`

**Comment by mathew3** [comment]
Another less sophisticated way that worked for me, is to create your own postfix configs (`main.cf` and/or `master.cf`) and copy them inside the container running postfix (`mailu_smtp_1`) to `/etc/postfix/`. Then you need to reload postfix `postfix reload && postfix status`.

I entered the container with `docker exec -it mailu_smtp_1 /bin/bash` and copied the configs from a mounted volume, but can be done via a script as well and surely there are other ways

I haven't tested @Alivekeep 's approach yet, but seems like more elegant solution. Anyway, this might be useful, if you are creating postfix's content filter for example and need to execute a script after receiving an email

**Comment by Nebukadneza** [comment]
Hi There,

The `Mailu`-Project is currently in a bit of a bind! We are short on man-power, and we need to judge if it is possible for us to put in some work on this issue.

To help with that, we are currently trying to find out which issues are actively keeping users from using `Mailu`, which issues have someone who want to work on them — and which issues may be less important. These a less important ones could be discarded for the time being, until the project is in a more stable and regular state once again.

In order for us to better assess this, it would be helpful if you could put a **reaction on this post** (use the :smiley: icon to the top-right).
- 👍️ if you **need this** to be able to use Mailu. Ideally, you’d also be able to test this on your installation, and provide feedback …
- 🎉 if you find it a **nice bonus**, but no deal-breaker
- 🚀 if you want to **work on it yourself**!
We want to keep this **voting open for 2 weeks** from now, so please help out!
