### ISSUE TITLE
unsupported dictionary type: pcre

### ISSUE THREAD

**Issue by ferllings** [Mailu/Mailu#1379]
Hello,

Still on my mailu fresh install, I have an error when trying to send email from roundcube:

Roundcube error is
```
SMTP Error: [451] 4.3.0 Error: queue file write error
```

And when I look at the postix logs, I found:
```
postfix/smtpd[528839]: connect from 10-42-0-101.mailu-front.default.svc.cluster.local[10.42.0.101]                                               
postfix/cleanup[528842]: error: unsupported dictionary type: pcre                                                                                
postfix/smtpd[528839]: 31DB96A000D: client=10-42-0-100.mailu-roundcube.default.svc.cluster.local[10.42.0.100], sasl_method=XCLIENT, sasl_username=contact@id
postfix/cleanup[528842]: warning: pcre:/etc/postfix/outclean_header_filter.cf is unavailable. unsupported dictionary type: pcre                  
postfix/cleanup[528842]: warning: pcre:/etc/postfix/outclean_header_filter.cf lookup error for "Received: from mail.xxxx.net
postfix/cleanup[528842]: warning: 31DB96A000D: header_checks map lookup problem -- message not accepted, try again later
postfix/cleanup[528842]: 425956A000D: message-id=<20200228101927.425956A000D@mail.xxx.net>
postfix/qmgr[174]: 425956A000D: from=<double-bounce@mail.xxx.net>, size=1147, nrcpt=1 (queue active)
postfix/smtpd[528839]: disconnect from 10-42-0-100.mailu-roundcube.default.svc.cluster.local[10.42.0.100] ehlo=2 xclient=0/1 mail=1 rcpt=1 data=0/1 rset=0/1
postfix/lmtp[528843]: 425956A000D: to=<postmaster@xxx.net>, orig_to=<postmaster>, relay=mailu-dovecot[10.43.99.120]:2525, delay=0.22, delays=0.06/0.08/
postfix/bounce[528844]: warning: 425956A000D: undeliverable postmaster notification discarded
postfix/qmgr[174]: 425956A000D: removed
postfix/smtpd[527942]: connect from localhost[127.0.0.1]
postfix/smtpd[527942]: disconnect from localhost[127.0.0.1] quit=1 commands=1
postfix/smtpd[527942]: connect from localhost[127.0.0.1]
```

Thanks for your help

**Comment by ferllings** [comment]
No idea why it happened.

I simply restarted the postfix container and the error is gone.

**Comment by ferllings** [comment]
I reopen this issue as it comes back after few hours until I restart the postfix instance.

**Comment by ferllings** [comment]
I noticed the module isn't loaded in postfix:
```
# postconf -m
btree
cidr
environ
fail
hash
inline
internal
memcache
pipemap
proxy
randmap
regexp
socketmap
static
tcp
texthash
unionmap
unix
```

**Comment by zxpower** [comment]
I just stumble on this, too.

Helped not restarting, but recreating the container.

**Comment by zxpower** [comment]
Some updates - even with container recreation after some time `pcre` is again missing from `postconf -m` entries.

Also noticed that for some reason - after this if you happen to restart the container `post-install` complains that it cannot find file `/etc/postfix/postfix-files` file. While if the container is recreated then the file exists.

**Comment by ferllings** [comment]
Yes, that's exactly it.
I scheduled an email send every morning, to monitor the server.
It works for few days, then the error comes back with no specific reason.

**Comment by zxpower** [comment]
Something cleans out `/etc/postfix` directory from  configs. When the condition kicks in then contents of the folder is like this:
```
-rw-r--r--    1 root     root          3250 Apr 18 17:04 main.cf
-rw-r--r--    1 root     root          1927 Apr 18 17:04 master.cf
-rw-r--r--    1 root     root           923 Apr 18 17:04 outclean_header_filter.cf
```

**Comment by zxpower** [comment]
This error becoming really annoying because we use Mailu on production system. I tried to downgrade just SMTP container to version 1.6 - but it also didn't helped. After certain time - got the same situation.

Any ideas @kaiyou ?

**Comment by ferllings** [comment]
@zxpower Any progress on your side?

**Comment by zxpower** [comment]
@ferllings nope.

Did a couple of tries with pulling fresh images, removing everything (including pruning volumes), but no luck. ~24h and again `/etc/postfix` is empty, `postconf -m` lacks `pcre` module and I'm getting `SMTP Error: [451] 4.3.0 Error: queue file write error`.

Also googled around - but unfortunately can't find cause for missing `pcre` module.

Now setting up some monitoring for the containers to see what exactly goes wrong.

**Comment by zxpower** [comment]
Still no updates, but I solved my problem by creating a crontab script that checks `/etc/postfix` directory in `smtp` container every 5 minutes. If it has less files than default - it sends me and email, so I can then restart the containers.

**Comment by zxpower** [comment]
Also I've a sneaking suspicion that it's not the `smtp` container causing problems, but some other - because if map `/etc/postfix` to host directory then SMTP isn't crashing, but instead there is some weird behaviour for `spam`, `admin` and `imap` containers. Unfortunately due to production system - I had no time to investigate more...

**Comment by Nebukadneza** [comment]
Hi There,

The `Mailu`-Project is currently in a bit of a bind! We are short on man-power, and we need to judge if it is possible for us to put in some work on this issue.

To help with that, we are currently trying to find out which issues are actively keeping users from using `Mailu`, which issues have someone who want to work on them — and which issues may be less important. These a less important ones could be discarded for the time being, until the project is in a more stable and regular state once again.

In order for us to better assess this, it would be helpful if you could put a **reaction on this post** (use the :smiley: icon to the top-right).
- 👍️ if you **need this** to be able to use Mailu. Ideally, you’d also be able to test this on your installation, and provide feedback …
- 🎉 if you find it a **nice bonus**, but no deal-breaker
- 🚀 if you want to **work on it yourself**!
We want to keep this **voting open for 2 weeks** from now, so please help out!
