### ISSUE TITLE
Missing GnuPG lib – required by Roundcube‘s Enigma plugin

### ISSUE THREAD

**Issue by deze333** [Mailu/Mailu#1384]
Webmail client RoundCube doesn't allow editing identities (ie, setting email signature) unless its Enigma plugin is configured. Enigma requires GnuPG installed.

Error looks like this:

```
SERVICE CURRENTLY NOT AVAILABLE! Error No. [600]
```

Adding GnuPG library to **`webmails/roundcube/Dockerfile`** and rebuilding `webmail` container solves the problem:

```bash
RUN apt-get update && apt-get install -y \ 
      zlib1g-dev libzip4 libzip-dev \ 
      python3-jinja2 \ 
      gnupg2 \ # <-- added
      # the rest follows as is...
```

**Comment by Nebukadneza** [comment]
I think this is what’s currently worked on in #1338 …, so I guess this’ll come in soon.

**Comment by Nebukadneza** [comment]
#1338 is merged and should solve this. Thus, closing …
