### ISSUE TITLE
I can receive emails, but can't send emails  (err: Address not available) ?

### ISSUE THREAD

**Issue by gilasraafi421** [Mailu/Mailu#1386]
Hi everyone,
This is my log in the smtp

> Mar 06 02:28:36 mail postfix/smtp[406]: connect to gmail-smtp-in.l.google.com[2404:6800:4003:c03::1a]:25: Address not available
Mar 06 02:28:36 mail postfix/smtp[407]: connect to ASPMX.L.GOOGLE.COM[2404:6800:4003:c04::1a]:25: Address not available
Mar 06 02:28:37 mail postfix/smtpd[185]: connect from localhost[127.0.0.1]
Mar 06 02:28:37 mail postfix/smtpd[185]: disconnect from localhost[127.0.0.1] quit=1 commands=1
Mar 06 02:29:06 mail postfix/smtp[406]: connect to gmail-smtp-in.l.google.com[74.125.24.26]:25: Operation timed out
Mar 06 02:29:07 mail postfix/smtp[407]: connect to ASPMX.L.GOOGLE.COM[172.217.194.27]:25: Operation timed out
Mar 06 02:29:07 mail postfix/smtp[407]: connect to ALT2.ASPMX.L.GOOGLE.COM[2607:f8b0:4003:c12::1b]:25: Address not available
Mar 06 02:29:07 mail postfix/smtp[407]: connect to ALT1.ASPMX.L.GOOGLE.COM[2607:f8b0:400e:c04::1b]:25: Address not available 

Thank you

**Comment by gilasraafi421** [comment]
[#1047](https://github.com/Mailu/Mailu/issues/1047)

**Comment by sekroots** [comment]
Is there any solution to this issue?

**Comment by nnhhuu** [comment]
same problem here !!!
