### ISSUE TITLE
is roundcube db configurable?

### ISSUE THREAD

**Issue by mamiapatrick** [Mailu/Mailu#1388]
Hello,
i want to know how is possible to configure roundcube db. For now the db is setup on $config['db_dsnw'] = 'sqlite:////data/roundcube.db'; and i got a message for a database error so cannot access to webmail

**Comment by Nebukadneza** [comment]
As for the configuration, that is currently work in progress in #1268 .
As for your error, can you elaborate a bit on your setup? Which versions are you using, and what is the exact error you’re seeing?

**Comment by myteksp** [comment]
Hey there.
Same question here.
Running on k8s 1.7 with external mariaDB.
Error within the roundcube instance:
Initializing database
ERROR: SQLSTATE[HY000] [1045] Access denied for user 'roundcube'@'192.168.0.201' (using password: YES)
ERROR: Failed to connect to database

**Comment by micw** [comment]
The database is configurable with the PR mentioned above. The helm chart is not ready (but there's a branch with my latest tests). Did not find the time to finish it yet.

**Comment by myteksp** [comment]
> The database is configurable with the PR mentioned above. The helm chart is not ready (but there's a branch with my latest tests). Did not find the time to finish it yet.

My bad. Didn't read til the end.
For anybody wondering - successfully deployed with external mariaDb with following in the config.yaml

DB_FLAVOR: "mysql"
DB_USER: "mailu"
DB_HOST: "mysql.default.svc.cluster.local"
DB_NAME: "mailu"
DB_PW: "SECRET"
ROUNDCUBE_DB_USER: "mailu"
ROUNDCUBE_DB_PW: "SECRET"
ROUNDCUBE_DB_NAME: "mailu"

**Comment by micw** [comment]
Thank you for positive feedback, I  close the issue now
