### ISSUE TITLE
Where to enable BAYES spam filtering?

### ISSUE THREAD

**Issue by dmenne** [Mailu/Mailu#1391]
I am using Roundcube Webmail 1.4.2, and now have 200 mails in Learned, so I expected that bayes filtering would jump in, but none came up. I also could not find any BAYES__ weights in rspamd symbols. 

![2020-03-07 11_56_21-mail menne-biomed de_admin_antispam_ - Rspamd Web Interface](https://user-images.githubusercontent.com/506275/76142240-ef40f400-606b-11ea-9aee-2f0b2c9ed22e.png)

**Comment by Nebukadneza** [comment]
Hi,

can you have a look  at the `antispam` container logs? There should be a line informing you about bayes status if it’s not checking yet, keep your eye open for something like
```
bayes_classify: skip classification as ham class has not enough learns: <xx>, <yyy> required
```
Also keep in mind bayes needs hams too, not only spam …. Please do get back if you find anything unexpected …

**Comment by dmenne** [comment]
Thanks, @Nebukaneza, I had forgotten about the hams:

skip classification as ham class has not enough learns: 53, 200 required

**Comment by Nebukadneza** [comment]
glad you could clear it up ^_^
