### ISSUE TITLE
RELAYNETS should not be subject to greylisting

### ISSUE THREAD

**Issue by curry684** [Mailu/Mailu#140]
I have whitelisted our hosting ranges in the `RELAYNETS` property of the `.env` file. Initially this works fine, sending anything unauthenticated from a non-listed host properly results in:
```
220 my.host.name ESMTP Postfix
HELO anything.nl
250 my.host.name
MAIL FROM:test@whatever.com
250 2.1.0 Ok
RCPT TO:anyone@gmail.com
454 4.7.1 <anyone@gmail.com>: Relay access denied
quit
221 2.0.0 Bye
```
Retrying the same thing from a whitelisted host however results in:
```
220 my.host.name ESMTP Postfix
HELO anything.nl
250 my.host.name
MAIL FROM:test@whatever.com
250 2.1.0 Ok
RCPT TO:anyone@gmail.com
250 2.1.5 Ok
DATA
354 End data with <CR><LF>.<CR><LF>
Subject: Test

Is this spam?
.
452 4.7.1 Try again later
```
Retrying the same transaction some time later does get the mail through.

Greylisting should also be explicitly disabled from relay networks as the whole point of a relay net is to allow applications and clients that are not MTAs themselves (consider a contact form in a web app) to send email, and they can neither authenticate nor retry - it should be fire&forget.

**Comment by kaiyou** [comment]
I agree, currently whitelisted IP addresses for relay nets are hardcoded and they should be copied from the environment variable. Thank you for reporting.

**Comment by askz** [comment]
Is there a workaround for this?

**Comment by kaiyou** [comment]
Not for now, marking as a bug so that I get it fixed sooner.
