### ISSUE TITLE
recipient_delimiter is limited to one character

### ISSUE THREAD

**Issue by eleith** [Mailu/Mailu#1400]
recipient_delimiter in both postfix and dovecot (2.3+) support multiple characters being used ( see: http://www.postfix.org/postconf.5.html#recipient_delimiter) 

for example: `recipient_delimeter = +-` would lead to accepting `username-string@domain.com` and `username+string@domain.com` 

however, mailu doesn't support this (email addresses get bounced). yet, this can be worked around by using the sql like syntax in the admin settings, so i don't think this isn't a blocker.

but i think it is worth considering one of two options

1) updating documentation to clarity that only one character is supported
2) fix the root issue causing delimiters to not work with `RECIPIENT_DELIMITER= +-` in `mailu.env`

any ideas where to start looking if one were to attempt (2) ?

**Comment by Nebukadneza** [comment]
Hi There,

The `Mailu`-Project is currently in a bit of a bind! We are short on man-power, and we need to judge if it is possible for us to put in some work on this issue.

To help with that, we are currently trying to find out which issues are actively keeping users from using `Mailu`, which issues have someone who want to work on them — and which issues may be less important. These a less important ones could be discarded for the time being, until the project is in a more stable and regular state once again.

In order for us to better assess this, it would be helpful if you could put a **reaction on this post** (use the :smiley: icon to the top-right).
- 👍️ if you **need this** to be able to use Mailu. Ideally, you’d also be able to test this on your installation, and provide feedback …
- 🎉 if you find it a **nice bonus**, but no deal-breaker
- 🚀 if you want to **work on it yourself**!
We want to keep this **voting open for 2 weeks** from now, so please help out!

**Comment by nextgens** [comment]
This has been fixed a while ago. I run ``RECIPIENT_DELIMITER=+-`` here.
