### ISSUE TITLE
can't subscribe to notification for releases (ex: 1.8)

### ISSUE THREAD

**Issue by eleith** [Mailu/Mailu#1402]
with github, you can subscribe to be notified of new releases (or watch all conversations... which is a bit noisy). but since there are no packaged releases on the github project, it won't work.

is their a way a preferred method for users to subscribe to release notifications? perhaps docker hub works? (though i'ld prefer github or rss / blog)

**Comment by Nebukadneza** [comment]
Hi There,

The `Mailu`-Project is currently in a bit of a bind! We are short on man-power, and we need to judge if it is possible for us to put in some work on this issue.

To help with that, we are currently trying to find out which issues are actively keeping users from using `Mailu`, which issues have someone who want to work on them — and which issues may be less important. These a less important ones could be discarded for the time being, until the project is in a more stable and regular state once again.

In order for us to better assess this, it would be helpful if you could put a **reaction on this post** (use the :smiley: icon to the top-right).
- 👍️ if you **need this** to be able to use Mailu. Ideally, you’d also be able to test this on your installation, and provide feedback …
- 🎉 if you find it a **nice bonus**, but no deal-breaker
- 🚀 if you want to **work on it yourself**!
We want to keep this **voting open for 2 weeks** from now, so please help out!

**Comment by Diman0** [comment]
This is a great idea. There should be a mechanism that you can use to be informed when there is a new release.

**Comment by lub** [comment]
short update: the current plan is to use the github releases to notify about new releases with a disclaimer, that the release tag is only for informational purposes and the commits for the actual images may differ, because we currently don't plan to do/tag point releases (neither on github nor on docker hub).

**Comment by lub** [comment]
We have now started doing this:

https://github.com/Mailu/Mailu/releases/tag/1.8-rc

Thank you for opening the issue :)
