### ISSUE TITLE
renew cert. deprecation of ACMEv1 requests

### ISSUE THREAD

**Issue by aicpp** [Mailu/Mailu#1406]
First of all, thank you for good product, which allow me to have my own mail server.
Recently, I got email from noreply@letsencrypt.org with warn about deprecation of ACMEv1 requests, which uses by mailu cerbot.

> According to our records, the software client you're using to get Let's
> Encrypt TLS/SSL certificates issued or renewed at least one HTTPS certificate
> in the past two weeks using the ACMEv1 protocol. Here are the details of one
> recent ACMEv1 request from each of your account(s):
> 
> Client IP address:  95.216.173.195
> 
> User agent:  CertbotACMEClient/0.25.1 (certbot; Alpine Linux v3.8) Authenticator/standalone Installer/None (certonly; flags: n hook) Py/2.7.15
> 
> Hostname(s):  "mail._domain.tld_"
> 
> Request time:  2020-02-27 13:23:21 UTC
> 
> Beginning June 1, 2020, we will stop allowing new domains to validate using
> the ACMEv1 protocol. You should upgrade to an ACMEv2 compatible client before
> then, or certificate issuance will fail. For most people, simply upgrading to
> the latest version of your existing client will suffice. You can view the
> client list at: https://letsencrypt.org/docs/client-options/
> 
> If you're unsure how your certificate is managed, get in touch with the
> person who installed the certificate for you. If you don't know who to
> contact, please view the help section in our community forum at
> https://community.letsencrypt.org/c/help and use the search bar to check if
> there's an existing solution for your question. If there isn't, please create
> a new topic and fill out the help template.
> 
> ACMEv1 API deprecation details can be found in our community forum:
> https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1
> ...

So, how to solve this problem?
Should I fix it by myself in "front" docker container, which have /letsencrypt.py script invokes certbot?
Or it will be fixed generally in mailu and I update it later (howewer, I don't know how).

Version of certbot in my "front" container: 0.25.1.

**Comment by kaiyou** [comment]
It should and will be fixed generally in Mailu. We need to update the certbot library in the front container. If you can provide a pull request that does just that, it would help a lot.

**Comment by ofthesun9** [comment]
@aicpp , could you please to update your front container (docker-compose pull ; docker-compose up -d)
Current nginx:1.7 includes certbot 0.35.1 (released in june 2019)
Could you confirm whether this issue still remains ?

**Comment by aicpp** [comment]
@ofthesun9 , I make your steps and didn't see any updates.
Commands:
```
docker-compose pull
docker-compose up -d
```
didn't update nginx and certbot versions.

Also, I try to force renew my cert and it's successfully renewed, but I suppose that will get another mail from letsencrypt about this issue.

To force renew, I connected to `mailu/nginx:1.6` container and add `--force-renewal` argument to `letsencrypt.py` script (and return back after test).

Check versions in logs:
`docker-compose logs | grep ': nginx/'`
    nginx/1.14.2

`docker-compose exec front tail -n 1000 /var/log/letsencrypt/letsencrypt.log | grep 'certbot version'`
    0.25.1

**Comment by ofthesun9** [comment]
Yes, front:1.6 (alpine:3.8) includes certbot 0.25.1
My advice would be to switch to 1.7 ;-)

**Comment by aicpp** [comment]
Thank you very much! I upgraded to 1.7 and got newer versions of nginx and cerbot.
