### ISSUE TITLE
Internal server error on setup.mailu.io (V1.7)

### ISSUE THREAD

**Issue by bd8392** [Mailu/Mailu#1407]
The setup-utility is not working anymore =( tried to setup new mailu...

**Comment by muhlemmer** [comment]
Hi, I'm the administrator of that server. I'm currently on the road, a COVID19 pre-lockdown effort to try to get home.

I hope to be able to take a look tomorrow. My apologies. 

On 16 March 2020 11:43:04 EET, bd8392 <notifications@github.com> wrote:
>The setup-utility is not working anymore =( tried to setup new mailu...
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Mailu/Mailu/issues/1407

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by bd8392** [comment]
Okay No problem! Take your time and be safe!

**Comment by Setsuneh** [comment]
Hi,

Do you have a specific online delivery time?

Thank you again for all

**Comment by bd8392** [comment]
No I'm just building up my servers right now, and try to do it as fast as possible because I'm switching from hosted mail to yours :-)...in the next two weeks would be nice, but don't hassle...be safe against the coronavirus first...if you need any help let me know...I also have a question to the deployment: I saw that in the docker stack, unbound is not included...is it because it is not needed, or not possible to deploy? Do I need unbound for dnssec? Cause I wanna use all your amazing features :-)

**Comment by muhlemmer** [comment]
Server is back online. Sorry for the wait...

**Comment by bd8392** [comment]
No problem! Thanks for all :-)

**Comment by EthraZa** [comment]
it's happening today:
`https://setup.mailu.io/1.7/submit 500`

Let me ask something else, there is any roadmap or tentative date to the 1.8 release?
Thank you
