### ISSUE TITLE
hash.sha256_crypt.verify takes 5s and 10s on 2.2 and 2.6GHz CPU respectively

### ISSUE THREAD

**Issue by cruwe** [Mailu/Mailu#1408]
First, thank you very much for developing mailu and making it available to the general public.

On both IMAP via evolution as well as on roundcube, I noted long delays before successful login.

For lack of better understanding on how to debug Python, I inserted print()-statements into `core/admin/mailu/internal/nginx.py` and `core/admin/mailu/models.py` and traced the delay to the invocation of `hash.sha256_crypt.verify(password, self.password)`, which took 9-10s on a KVM virtualized instance on an 2.2GHz Atom and 4-5s on bare-metal 2.6GHz i7.

I managed to reduce the time by 1/2 when using `MD5-CRYPT` as `PASSWORD_SCHEME` instead of `SHA512-CRYPT`.

I consider both checks too long by at least one order of magnitude. Is this a severe configuration error on my part or just an inefficiency of some libaries?

Thank you for your consideration, cheers!
Christopher

**Comment by HorayNarea** [comment]
__NEVER EVER EVER EVER USE `MD5-CRYPT`__, it is only supported for backwards compatibility!

Try using `PBKDF2` instead.

**Comment by HorayNarea** [comment]
> took 9-10s on a KVM virtualized instance on an 2.2GHz Atom and 4-5s on bare-metal 2.6GHz i7

Which CPU are you emulating in KVM? Maybe the relevant crypto-instructions are not supported and therefore it's really slow.

Atom CPUs are generally really bad at crypto, it is not supposed to run fast on them :D

**Comment by cruwe** [comment]
Thanks for the hint on MD5, @HorayNarea. I just wanted to take a peek on the performance and promptly changed it back after seeing the improvement.

Initially, I suspected the Atom/KVM combination (KVM emulating IvyBridge IBRS from "copy host configuration") as well for the reasons you posted, but the absolute times even on a  bare metal (no KVM, Intel i7 2-cores, 2.6GHz, Hyperthreading) do not seem right. 

On all thee hosts, I just benchmarked shaXXX performance with some c&p'ed lines of Perl. 
The KVM host (hoare) and guest (knuth) perform equally well (or bad):
```
[cjr@hoare:/home/cjr]
$ ./benchmarker 
Benchmark: running sha1, sha256, sha512 for at least 3 CPU seconds...
      sha1:  3 wallclock secs ( 3.02 usr +  0.00 sys =  3.02 CPU) @  5.63/s (n=17)
    sha256:  3 wallclock secs ( 3.19 usr +  0.00 sys =  3.19 CPU) @  4.39/s (n=14)
    sha512:  3 wallclock secs ( 3.14 usr +  0.00 sys =  3.14 CPU) @  2.55/s (n=8)
```
```
cjr@knuth:~$ ./benchmarker 
Benchmark: running sha1, sha256, sha512 for at least 3 CPU seconds...
      sha1:  3 wallclock secs ( 3.11 usr +  0.02 sys =  3.13 CPU) @  5.43/s (n=17)
    sha256:  3 wallclock secs ( 3.15 usr +  0.01 sys =  3.16 CPU) @  4.11/s (n=13)
    sha512:  3 wallclock secs ( 3.21 usr +  0.02 sys =  3.23 CPU) @  2.48/s (n=8)
```
The numbers are so close that apparently, in- our out of KVM virtually makes no difference.

The machine I used for comparison performs better by exactly the factor of 2 I observed in the logs:
```
[cjr@ritchie:/home/cjr]
$ ./benchmarker 
Benchmark: running sha1, sha256, sha512 for at least 3 CPU seconds...
      sha1:  3 wallclock secs ( 3.13 usr +  0.00 sys =  3.13 CPU) @ 11.82/s (n=37)
    sha256:  3 wallclock secs ( 3.13 usr +  0.00 sys =  3.13 CPU) @  9.58/s (n=30)
    sha512:  3 wallclock secs ( 3.12 usr +  0.00 sys =  3.12 CPU) @  5.77/s (n=18)
```

I do not know if I interpret the numbers correctly, but 1/5s, 1/9s -> 0.2/s, 0.111/s, which is slower by one order of magnitude. Still does not seem right.

In any case, thanks for taking an interest.
Cheers!

**Comment by micw** [comment]
> **NEVER EVER EVER EVER USE `MD5-CRYPT`**, it is only supported for backwards compatibility!
> 
> Try using `PBKDF2` instead.

Don't. Hash functions with high computing costs are not suitable for session-less services since the has must be compared on every single request. This slows down your whole system. Use something like APR1 if you expect reasonable performance. See https://www.endpoint.com/blog/2016/02/09/bonked-by-basicauth-because-bcrypt for an example.

**Comment by cruwe** [comment]
I do not know about PBKDF2, but if it is like bcrypt, I get the idea. Doesn't bcrypt _intentionally_ slow down hash comparison to swamp attackers?

**Comment by micw** [comment]
Yes. It consumes lots of CPU/memory by intent.

I have created a proposal to solve the issue (#1411), having both, performance for valid users and slowdown+protection against attacks.

**Comment by HorayNarea** [comment]
> Yes. It consumes lots of CPU/memory by intent.

Sorry, thats wrong for PBKDF2… it's even vulnerable to GPU/FPGA/ASIC based bruteforce since it does not require much memory:


> One weakness of PBKDF2 is that while its number of iterations can be adjusted to make it take an arbitrarily large amount of computing time, it can be implemented with a small circuit and very little RAM, which makes brute-force attacks using application-specific integrated circuits or graphics processing units relatively cheap.

from https://en.wikipedia.org/wiki/PBKDF2#Alternatives_to_PBKDF2

**Comment by Nebukadneza** [comment]
Hi There,

The `Mailu`-Project is currently in a bit of a bind! We are short on man-power, and we need to judge if it is possible for us to put in some work on this issue.

To help with that, we are currently trying to find out which issues are actively keeping users from using `Mailu`, which issues have someone who want to work on them — and which issues may be less important. These a less important ones could be discarded for the time being, until the project is in a more stable and regular state once again.

In order for us to better assess this, it would be helpful if you could put a **reaction on this post** (use the :smiley: icon to the top-right).
- 👍️ if you **need this** to be able to use Mailu. Ideally, you’d also be able to test this on your installation, and provide feedback …
- 🎉 if you find it a **nice bonus**, but no deal-breaker
- 🚀 if you want to **work on it yourself**!
We want to keep this **voting open for 2 weeks** from now, so please help out!

**Comment by cruwe** [comment]
Sorry for the delay, the mail-notice got swampend. I do not _need_ it per se, It might be a deal breaker for a larger user base on the same server, which I do not have. It also opens an avenue for DoS.

**Comment by nextgens** [comment]
This has been addressed.

1.8 uses PBKDF2 and master will use bcrypt+sha256 with a credential cache and a rate limiter
