### ISSUE TITLE
Mailu configuration : Internal Server Error

### ISSUE THREAD

**Issue by xirius** [Mailu/Mailu#1409]
Mailu configurator (https://setup.mailu.io/1.7/submit_flavor) for Docker doesn't work:

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Comment by JunTVDE** [comment]
still not working

**Comment by Nebukadneza** [comment]
as a very very temporary remedy, until the admin who has access to the `setup.mailu.io` box finds some time, I have a temporary setup instance running:

https://mailusetup.chickenkiller.com/

With the risk that I didn’t do everything 100% correctly, and this a very very dodgy setup … you can use it :sweat_smile: :sweat_drops: . But … it’s a emergency remedy …

**Comment by muhlemmer** [comment]
Hi, server is back up. Sorry for any inconvenience.

We should look into giving ssh access to more members of the team. Perhaps by posting public keys to the Mailu/infra project?

cc: @kaiyou, @Nebukadneza

**Comment by muhlemmer** [comment]
This was a dupe of #1407, where I did respond yesterday I wasn't able to take action.

**Comment by David00** [comment]
Thanks @muhlemmer! Looks like it works now.

**Comment by kaiyou** [comment]
Thanks @muhlemmer, I was thinking moving the setup and docs back to a server i have access to and can run an cron to update and reset both everyday. What do you think?

**Comment by MythreyaK** [comment]
Hello, I tried to access the configuration tool, and the error seems to have reappeared.

**Comment by Nebukadneza** [comment]
I’d like to close this one, as we still have https://github.com/Mailu/infra/issues/2 to track maintainer-access to the infra-boxes …
