### ISSUE TITLE
DNS resolution issues

### ISSUE THREAD

**Issue by golyalpha** [Mailu/Mailu#1415]
I'm having issues with DNS resolution timing out on incoming and outgoing mails, resulting in emails not being sent out, and incoming mails being rejected.
Here are incoming logs:
```
smtp_1       | Mar 20 22:40:15 mail postfix/smtpd[512]: NOQUEUE: reject: RCPT from unknown[185.70.40.135]: 450 4.1.8 <[REDACTED]@protonmail.com>: Sender address rejected: Domain not found; from=<[REDACTED]@protonmail.com> to=<[REDACTED]> proto=ESMTP helo=<mail-40135.protonmail.ch>
```
Here are outgoing logs:
```
smtp_1       | Mar 20 22:56:08 mail postfix/smtpd[1005]: connect from mailu_front_1.mailu_default[192.168.203.5]
smtp_1       | Mar 20 22:56:09 mail postfix/smtpd[1005]: 63AF641D13: client=mailu_webmail_1.mailu_default[192.168.203.10], sasl_method=XCLIENT, sasl_username=[REDACTED]
smtp_1       | Mar 20 22:56:09 mail postfix/cleanup[1014]: 63AF641D13: replace: header Received: from [REDACTED] (mailu_webmail_1.mailu_default [192.168.203.10])??by [REDACTED] (Postfix) with ESMTPA id 63AF641D13??for <[REDACTED]@protonmail.com>; Fri, 20 Mar 2020 22:5 from mailu_webmail_1.mailu_default[192.168.203.10]; from=<[REDACTED]> to=<[REDACTED]@protonmail.com> proto=ESMTP helo=<[REDACTED]>: Received: from authenticated-user (PRIMARY_HOSTNAME [PUBLIC_IP])??by [REDACTED] (Postfix) with ESMTPA id 63AF641D13??for <[REDACTED]@protonmail.com>; Fri, 20 Mar 2020 22:56:08 +0000 (UTC)
smtp_1       | Mar 20 22:56:09 mail postfix/cleanup[1014]: 63AF641D13: message-id=<35ba4bc6528273a4e4dbc0d0ff7fc42a@[REDACTED]>
smtp_1       | Mar 20 22:56:09 mail postfix/qmgr[172]: 63AF641D13: from=<[REDACTED]>, size=1124, nrcpt=1 (queue active)
smtp_1       | Mar 20 22:56:09 mail postfix/smtpd[1005]: disconnect from mailu_webmail_1.mailu_default[192.168.203.10] ehlo=2 xclient=0/1 mail=1 rcpt=1 data=1 quit=1 commands=6/7
smtp_1       | Mar 20 22:56:34 mail postfix/smtp[1018]: 63AF641D13: to=<[REDACTED]@protonmail.com>, relay=none, delay=26, delays=0.72/0.19/25/0, dsn=4.4.3, status=deferred (Name service error for name=protonmail.com type=MX: Malformed or unexpected name server reply)
```

Could this be an issue with the DNS server in use? If so, is there a way I can change it without diving into the containers? (I have no issues with DNS resolution anywhere else on that system)

**Comment by golyalpha** [comment]
I ended up modifying the docker-compose file to point DNS to 1.1.1.1 instead of the .254 docker IP.

**Comment by HorayNarea** [comment]
Because Mailu includes a local DNS resolver on that IP that is __needed__ for rspamd… if you use public resolvers then DNSBL won't work correctly since the DNSBL-providers ratelimit based on resolver IP, so 1.1.1.1 and 8.8.8.8 are wery likely never getting anything useful from them…

See for example https://mailu.io/1.7/faq.html#rspamd-dns-query-blocked-on-multi-uribl-com for a little more information

**Comment by golyalpha** [comment]
Yeah, I later on figured that out, and added the resolver (I orignally disabled it in the configurator). Now I'm having a different issue.

What is an issue now, is when services (Self-hosted Sentry, Nextcloud and Phabricator instances in this case) using the Mailu host as their mailing service receive connection timeouts because Nginx tries to resolve the apparently poorly configured reverse DNS record, and fails. That failure is not a problem for receiving mails, and I've noticed that Thunderbird usually doesn't have a problem either, but it is causing connection timeouts on the aforementioned services.

**Comment by Jab2870** [comment]
Hi,

I appear to be having the same issue when attempting to receive emails:

```
smtp_1      | Apr 06 13:55:01 mail postfix/smtpd[573]: disconnect from localhost[127.0.0.1] quit=1 commands=1
smtp_1      | Apr 06 13:55:10 mail postfix/anvil[162]: statistics: max connection rate 2/60s for (smtp:185.70.40.18) at Apr  6 13:50:22
smtp_1      | Apr 06 13:55:10 mail postfix/anvil[162]: statistics: max connection count 1 for (smtp:185.70.40.18) at Apr  6 13:50:09
smtp_1      | Apr 06 13:55:10 mail postfix/anvil[162]: statistics: max cache size 2 at Apr  6 13:50:09
smtp_1      | Apr 06 13:55:10 mail postfix/smtpd[128]: connect from mailu_front_1.mailu_default[192.168.203.2]
smtp_1      | Apr 06 13:55:10 mail postfix/smtpd[128]: NOQUEUE: reject: RCPT from mail1.protonmail.ch[185.70.40.18]: 450 4.1.1 <redacted@redacted.com>: Recipient address rejected: unverified address: Address lookup failure; from=<redacted@redacted.com> to=<redacted@redacted.com> proto=ESMTP helo=<mail1.example.com>
smtp_1      | Apr 06 13:55:10 mail postfix/smtpd[128]: disconnect from mail1.protonmail.ch[185.70.40.18] ehlo=2 xclient=0/1 mail=1 rcpt=0/1 rset=1 quit=1 commands=5/7
smtp_1      | Apr 06 13:55:31 mail postfix/smtpd[573]: connect from localhost[127.0.0.1]
smtp_1      | Apr 06 13:55:31 mail postfix/smtpd[573]: disconnect from localhost[127.0.0.1] quit=1 commands=1
```

I am using the unbound server, as produced by the setup utility:

```
  resolver:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}unbound:${MAILU_VERSION:-1.7}
    env_file: mailu.env
    restart: always
    networks:
      default:
        ipv4_address: 192.168.203.254
```

To clarify, I am currently able to send emails but not receive them.

**Comment by golyalpha** [comment]
@Jab2870 I worked around it by setting the DNS resolution timeout to 5s in the mail section of the nginx image and rebuilding it.

**Comment by Nebukadneza** [comment]
Hi There,

The `Mailu`-Project is currently in a bit of a bind! We are short on man-power, and we need to judge if it is possible for us to put in some work on this issue.

To help with that, we are currently trying to find out which issues are actively keeping users from using `Mailu`, which issues have someone who want to work on them — and which issues may be less important. These a less important ones could be discarded for the time being, until the project is in a more stable and regular state once again.

In order for us to better assess this, it would be helpful if you could put a **reaction on this post** (use the :smiley: icon to the top-right).
- 👍️ if you **need this** to be able to use Mailu. Ideally, you’d also be able to test this on your installation, and provide feedback …
- 🎉 if you find it a **nice bonus**, but no deal-breaker
- 🚀 if you want to **work on it yourself**!
We want to keep this **voting open for 2 weeks** from now, so please help out!

**Comment by golyalpha** [comment]
Any updates on this?
