### ISSUE TITLE
forward email: Unroutable email address

### ISSUE THREAD

**Issue by gizocz** [Mailu/Mailu#142]
Another problem with auto-forward in admin: some mail servers (e.g. email.cz) do not accept the forwarded email with error: "451 4.4.8 Unroutable email address. (in reply to MAIL FROM command)". Its looks like there is a generated FROM address (mail@dbb503b654ec.gitima.cz in my case) which has no DNS record. Emails forwarded by roundcube filter does not have this generated FROM address and is accepted by all tested servers.

The forwarded emails are accepted by google:
Delivered-To: gizocz@gmail.com
Return-Path: <mail@dbb503b654ec.gitima.cz>
Received-SPF: pass (google.com: best guess record for domain of mail@dbb503b654ec.gitima.cz designates 185.8.236.166 as permitted sender) client-ip=185.8.236.166;
Authentication-Results: mx.google.com;
       dkim=pass header.i=@cesnet.cz;
       spf=pass (google.com: best guess record for domain of mail@dbb503b654ec.gitima.cz designates 185.8.236.166 as permitted sender) smtp.mailfrom=mail@dbb503b654ec.gitima.cz;
       dmarc=pass (p=NONE dis=NONE) header.from=cesnet.cz
Received: from dbb503b654ec (mailu_imap_1.mailu_default [172.19.0.2]) by mail.gitima.cz (Postfix) with ESMTP id D544F20973 for <gizocz@gmail.com>; Mon,
  2 Jan 2017 23:16:43 +0000 (UTC)
Delivered-To: gizo@gitima.cz

**Comment by kaiyou** [comment]
It does not look like a generated address but the short hostname of your Docker container. It should not happen however, probably the Dovecot Sieve configuration.

**Comment by kaiyou** [comment]
After the many bugs that we encountered with forwarding, I just switched to handling forwads as aliases with local copy in Postfix directly. The bug should be fixed in ``master`` (18834de56e2bb62e97150ca9ee8b117d24937609)
