### ISSUE TITLE
Localhost keeps connecting/disconnecting to postfix

### ISSUE THREAD

**Issue by mathew3** [Mailu/Mailu#1424]
In my smtp's container logs (`docker-compose logs -f smtp`) there is a process connecting (disconnecting) to postfix from localhost approx. every 30s. I suppose it's some monitoring check but I haven't found any detailed documentation on it.

It's not really an issue but it's polluting my logs. Is there any way to omit them or at least prolong the timeout by overriding postfix's config? Thanks. I'm running Mailu v1.7

Logs:

```
{"log":"Mar 28 11:24:48 stash postfix/smtpd[17196]: connect from localhost[127.0.0.1]\n","stream":"stdout","time":"2020-03-28T11:24:48.639131068Z"}
{"log":"Mar 28 11:24:48 stash postfix/smtpd[17196]: disconnect from localhost[127.0.0.1] quit=1 commands=1\n","stream":"stdout","time":"2020-03-28T11:24:48.639532049Z"}
{"log":"Mar 28 11:25:19 stash postfix/smtpd[17196]: connect from localhost[127.0.0.1]\n","stream":"stdout","time":"2020-03-28T11:25:19.038847399Z"}
{"log":"Mar 28 11:25:19 stash postfix/smtpd[17196]: disconnect from localhost[127.0.0.1] quit=1 commands=1\n","stream":"stdout","time":"2020-03-28T11:25:19.04100036Z"}
```

**Comment by ofthesun9** [comment]
Hello,
Yes, it is the healthcheck mechanism which is defined for some services (not only postfix btw). Default is an interval of 30s.
You can override it (and even disable it) if you modify your docker-compose.yml:
See the relevant documentation for [healthcheck](https://docs.docker.com/compose/compose-file/#healthcheck)

**Comment by mathew3** [comment]
@ofthesun9 great, thanks! I'm closing this
