### ISSUE TITLE
Troubleshooting DKIM

### ISSUE THREAD

**Issue by pigeonflight** [Mailu/Mailu#1428]
I'm using 1.7 and I've setup DKIM, regenerated the keys and updated my nameservers.
My mail is still rejected.
According to mxtoolbox the issues is
```
Body Hash Did Not Verify
```

Based on some reading it looks like I may need to change a setting in rspamd.
If a change to rspamd is required where do I make the change? If it isn't an rspamd
issue, can I get some guidance on what might be causing this.

**Comment by dexidenova** [comment]
Hello everyone, I have same problem too.
my messages get spammed because of "DKIM not signed"
I give you my instance configs and hope it help.

> I've change my TLD to "mydomain.com" and my IP to "123.456.789.101"

[Mailu output.txt](https://github.com/Mailu/Mailu/files/4432608/Mailu.output.txt)

**Comment by airstep** [comment]
Same for me after testing in http://mxtoolbox.com I had "DKIM Signature Body Hash Verified"

As for example it was like this values:

Dkim Public Record:
`v=DKIM1; k=rsa; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDEyOagwbIJUKEIB81lS6XepvVZ310e6KhQlJcb04AA1Mi6udFsDoHIp6BLDEMjgec0CXwMdh3pR0BW6gDiHSF68w9uWYWZySJyVxVFHXg4u7PUBkbYKWT0L5bwBqvkDnnppsG2N/SuRrUHmX0Dm3duGebbCrp+VnDYGfIdEF/5xwIDAQAB`

Dkim Signature (in red color):
`v=1; a=rsa-sha256; c=relaxed/relaxed; d=mine.shop; s=dkim; t=1586581373; h=from:from:reply-to:subject:subject:date:date:message-id:message-id: to:to:cc:mime-version:mime-version:content-type:content-type: content-transfer-encoding:content-transfer-encoding; bh=7zPquDCtZyzOA5PY0kmGl8Aq5WV/QI7GoaYVVezsWQc=; b=fXk44vyq1KdNJvDSUqyVlWTqZG9J0xRhv4OC639ZdPyzRr70BJiHtbZulKp8rH27CRqtKg PJatI3z1SfopkVtMMdxHPfCA1reG8bhQmxFNiIMwL7pN4KlnErm5OcDiDgepRwQ6SxVlqz UYa5wqhyxVFYGQ8GEfAsxT29i/6pE3Q=`

**Comment by AndrewSav** [comment]
@dexidenova I'm not sure what's wrong with how mxtoolbox checks dkim... try this:

```bash
echo -ne "tested\r\n" > body
echo -ne "$(sha256sum body | sed 's/ .*$//; s/../\\x&/g')" > b.bin
base64 b.bin
```
This will net you:

```text
5pxN3n2CFDfOxHrsNUcJZYJcUK2jOAh/BgwKLV4RoT4=
```

Which is exactly what your `bh=` value is. I'm not sure why mxtoolbox thinks that it's wrong.

**Comment by airstep** [comment]
ABOUT DKIM RECORD CHECK
The DKIM Check tool will perform a DKIM record test against a domain name and selector for a valid published DKIM key record. DomainKeys Identified Mail (DKIM) defines a domain-level digital signature authentication framework for email by permitting a signing domain to assert responsibility for a message in transit. DKIM authenticates the reputation and identity of the email sender and their email signing practices for additional handling (i.e. does email get delivered, quarantined, or rejected). DKIM authentication of a message is validated via a cryptographic signature and querying the signer’s domain to retrieve a public key. This tool tests the ability to retrieve the DKIM public key using a domain and a selector.

**Comment by airstep** [comment]
https://mxtoolbox.com/dmarc/email-delivery/email-messages-not-getting-delivered?lm=NAV-PD

**Comment by AndrewSav** [comment]
@airstep so.... did it help you?

**Comment by airstep** [comment]
> @airstep so.... did it help you?

I didn't try anymore...

**Comment by pigeonflight** [comment]
I can say that I've tested this with other mail servers (non-mailu) without being flagged by mxtoolbox and Google. I'm not sure what else to change for this to work.

**Comment by muhlemmer** [comment]
@pigeonflight: can you send an email to admin@test.mailu.io and mention this Issue in the subject? This way we can check the headers on the receiving part.

Note: the sender e-mail address will be visible in a semi-publicly accessible mailbox. (The login details are public, but it can't be scraped easily). The mailbox is emptied on a regular base.

**Comment by Nebukadneza** [comment]
Hi There,

The `Mailu`-Project is currently in a bit of a bind! We are short on man-power, and we need to judge if it is possible for us to put in some work on this issue.

To help with that, we are currently trying to find out which issues are actively keeping users from using `Mailu`, which issues have someone who want to work on them — and which issues may be less important. These a less important ones could be discarded for the time being, until the project is in a more stable and regular state once again.

In order for us to better assess this, it would be helpful if you could put a **reaction on this post** (use the :smiley: icon to the top-right).
- 👍️ if you **need this** to be able to use Mailu. Ideally, you’d also be able to test this on your installation, and provide feedback …
- 🎉 if you find it a **nice bonus**, but no deal-breaker
- 🚀 if you want to **work on it yourself**!
We want to keep this **voting open for 2 weeks** from now, so please help out!

**Comment by parisni** [comment]
Hi, I have the same trouble: `DKIM Signature Body Hash Verified	` on both https://mxtoolbox.com/ and  https://www.appmaildev.com/site/testfile/dkim 
I would be glad to send a mail to  admin@test.mailu.io to dig this.

Note: Whenever I click on regenerate in the admin ui, nothing appens, not sure if this is related, but this sound strange
