### ISSUE TITLE
Dovecot recognize .dovecot.sieve as a mail folder

### ISSUE THREAD

**Issue by senilio** [Mailu/Mailu#143]
I keep getting the following error in the logs from the imap container:
imap_1       | Jan 03 10:14:03 imap(user@domain.com): Error: stat(/mail/user@domain.com/.dovecot.sieve/tmp) failed: Not a directory

I'm also seeing a "dovecot" dir in my mail client, with a "sieve" subdir, which corresponds with this.

Looks like we've hit this issue:
https://dovecot.org/list/dovecot/2009-October/043593.html

all dot-files/dirs are automatically recognized as mail folders. Possible solutions:
- add maildir_stat_dirs=yes to the dovecot config. 
- move existing dot-files out of the maildir

**Comment by kaiyou** [comment]
I cannot reproduce this locally, did you import existing maildirs in Mailu maybe ?

**Comment by senilio** [comment]
Yes I did, as the matter of fact :) Can that explain this kind of behavior?

This is what it looks like in OSX Mail.app: https://i.imgur.com/7ys0ghq.png

**Comment by kaiyou** [comment]
Sieve is the IMAP mail filtering system, implemented as Pigeonhole in Dovecot. That ``.dovecot.sieve`` is the user configuratoin file.

Normally, the ``.dovecot.sieve`` should be a symbolic link to something in the ``sieve`` directory. That kind of configuration is specific, also maybe your ``.dovecot.sieve`` is a directory, or maybe the ``sieve`` directory did not exist in your previous mail server.

Could you check these?

**Comment by senilio** [comment]
It is a link: https://i.imgur.com/ltOI4Q6.png

I've just let the link and the sieve directory be automatically created by mailu. They did not exist before.

I guess I could "reset" all dovecot related files in my maildir, and let them be generated again. I'm pretty sure they all come from my old install.

**Comment by kaiyou** [comment]
I just read the documentation for ``maildir_stat_dirs`` (https://wiki2.dovecot.org/MailLocation/Maildir) and it seems indeed that storing non-directory files beginning with dots is discouraged by Dovecot.

Still, the default for the ``sieve`` configuration value does store such a "file" (a symlink actually) in the maildir : 

```
sieve = file:~/sieve;active=~/.dovecot.sieve
```

Since I cannot reproduce, I wonder if the difference of behaviour could be explained by the filesystem. I am running on Btrfs only.

**Comment by senilio** [comment]
I'm running on ext4 (rw,relatime,seclabel,data=ordered).

I manually added "maildir_stat_dirs=yes" in dovecont.conf and restarted the container, and it did help the issue.

**Comment by kaiyou** [comment]
Ok, could you wait and check if it has a significant impact on performance ? If not, I see no reason why we should not include it in the Dovecot configuration.

**Comment by senilio** [comment]
Sure, I will run it for a while and report back. Thanks!

**Comment by senilio** [comment]
Not much to report on performance. I'm only running 6 mail accounts though. It may be noticeable on a system with a lot more accounts, which is hard for me to test. To be safe, perhaps it could be added as an optional setting in .env.

**Comment by kaiyou** [comment]
Thank you for testing. I am including it in the Dovecot config.
