### ISSUE TITLE
nginx- default config

### ISSUE THREAD

**Issue by PiotrFerenc** [Mailu/Mailu#1431]
How to override default configuration? I try to run with default config.

my step 
copy default conf
`docker cp mailu_front_1:/etc/nginx/nginx.conf overrides/nginx/nginx.conf`
run docker-compose
` docker-compose up -d`

`nginx: [emerg] "user" directive is not allowed here in /overrides/nginx.conf:2`
 

 

 
[nginx.conf.txt](https://github.com/Mailu/Mailu/files/4429340/nginx.conf.txt)

**Comment by ofthesun9** [comment]
Hello !
The file /overrides/nginx.conf is inserted in the /etc/nginx/nginx.conf . I guess that you should only put "additional" directives in this file.

If you want to "fully" overrides the nginx.conf, you should grab a copy of the file found in /conf/nginx.conf, modify this file as you wish, and modify your docker-compose.yml to mount your modified file in /conf/nginx.conf. 

The file found in /conf/nginx.conf  is parsed during container start and is used to generate the /etc/nginx.conf

That being said, you could also consider to a use another reverse proxy to listen your 80 and 443 ports, do the ssl stuff, and keep your mailu-nginx unchanged. See the [reverse proxy](https://mailu.io/1.7/reverse.html#using-an-external-reverse-proxy) and the [mail TLS flavour](https://mailu.io/1.7/compose/setup.html#tls-certificates) documentation.

**Comment by PiotrFerenc** [comment]
Hello :) it's a live! thanks :) 

How to :
1. run
` docker-compose up -d`
2. copy template file 
` docker cp mailu_front_1:/conf/nginx.conf nginx/nginx.conf `
3. Update docker-compose. yml (in nginx/volumes) 
 `- "/mailu/nginx/nginx.conf:/conf/nginx.conf"`
4. update nginx/nginx.conf  if you wont
4. stop all containers
`docker stop $(docker ps -a -q)`
5. run 1.

DONE!

check logs container front
`docker logs -f mailu_front_1`
bash of container front 
`docker exec -it mailu_front_1 /bin/bash`
