### ISSUE TITLE
Access to webmail through multiple domains

### ISSUE THREAD

**Issue by Jab2870** [Mailu/Mailu#1434]
Hi,

I originally set up mailu for a single domain and it works perfectly However, I have recently added another domain in the admin settings and to the env file. The hostname now looks like this:

```
HOSTNAMES=mail.domain.one,mail.domain.two
```

I have re-started docker but I don't seem to be able to access the webmail at `mail.domain.two/webmail`. Am I missing something?

Thanks

**Comment by muhlemmer** [comment]
1. Did you setup [DNS](https://mailu.io/1.7/dns.html) `A` record for `mail.domain.two`?
2. See [FAQ entry](https://mailu.io/1.7/faq.html#changes-in-env-don-t-propagate) Changes in `mailu.env` are only picked up by `docker-compose` if you bring down the project completely and bring it back up. Restart won't work:

````
docker-compose down && docker-compose up -d
````

If you have `TLS_FLAVOR=letsencrypt` you have to wait for the new certificates to be requested. You can monitor the process by:

````
docker-compose logs -f front
````

**Comment by Jab2870** [comment]
Thanks for your help. I had been running

```
docker-compose restart
```

Apparently that is different. I am quite new to docker. Thanks for your help.
