### ISSUE TITLE
How to teach Bayes ham and spam

### ISSUE THREAD

**Issue by dmenne** [Mailu/Mailu#1438]
The requirement for 200 ham for Bayes classification is not easy to meet with low-volume servers. rspamd works reasonably for the usual viagnigeria spam, but it fails completely for the dozens of requests per day to submit my publication to some fake-open-source journal

I am used to use sa-learn with Spamassassin or rspamc with rspamd to use existing mail for ham education,  but ther is no rspamc. The spam/learn tab in rspamd is ridiculous - should I manually paste in hundreds of ham messages?

What is the best method to instruct a mailu installation to use an existing clean mailbox as ham-fodder?

**Comment by ofthesun9** [comment]
Hello,
You can move (using your mail client, or the webmail)  messages to the Junk Folder, rpsmad will learn them as spam messages.

If you move a mail *from* the Junk folder back to any folder (except the Trash folder), Mailu will learn them as ham. Not straightforward, but maybe that would work ?

A more straightforward way would be to modify the existing behaviour as defined in [dovecot](https://github.com/Mailu/Mailu/blob/master/core/dovecot/conf/dovecot.conf)

**Comment by dmenne** [comment]
Sounds scary, but would it work? Will it be "unlearned" from spam after moving it back?

**Comment by dmenne** [comment]
I did it and got a strange message (this is neural, so not directly relevant)

<b00205>; lua; neural.lua:487: cannot learn ANN tRFANN9D954503A5235C34260: too many ham samples: 162

**Comment by dmenne** [comment]
>>classify: skip classification as ham class has not enough learns: 144, 200 required

This value was unchanged by the move in/out

**Comment by ofthesun9** [comment]
> Sounds scary, but would it work? Will it be "unlearned" from spam after moving it back?

I did look into the code, and we are maybe missing a "fuzzy_del" action when we are moving a from ham to spam and vice versa.
I will submit a PR for this.

**Comment by dmenne** [comment]
Thank for looking into it. Please post your PR # so I can follow up

**Comment by ofthesun9** [comment]
Yes I will do.
To come back to you question "How to teach Bayes ham and spam":

- to learn a spam: put it in the Junk folder
- to learn a ham message: you could create a mailbox "Ham", and create the following file in /mailu/overrides/dovecot.conf
```
plugin {
  # Learn ham
  imapsieve_mailbox3_name = Ham
  imapsieve_mailbox3_from = *
  imapsieve_mailbox3_causes = COPY
  imapsieve_mailbox3_before = file:/conf/report-ham.sieve
}
```
Any new message that will be put in this folder will be learnt as ham (for both bayes and fuzzy)
In order to learn from an already existing mailbox, if moving back and forth the messages is not suitable, you might run rspamc from within the dovecot container:
```
rspamc -h antispam:11334 -P mailu -f 13 fuzzy_add /mail/user\@example.com/.Ham_Learn/cur/  `
```
This should learn every file located in the Ham_Learn mailbox from user@example.com

**Comment by dmenne** [comment]
Thanks. I know about the rspamc method, but I tried to run it from the rspamd container. Maybe put this info somewhere in the docs?

**Comment by HorayNarea** [comment]
In the meantime you can also learn spam/ham in the webinterface of rspamd under yourmaildomain.tld/admin/antispam/#scan (which only works if you are logged in as an administrator)

**Comment by dmenne** [comment]
As I wrote in the original posting:  "The spam/learn tab in rspamd is ridiculous - should I manually paste in hundreds of ham messages?"
