### ISSUE TITLE
High CPU Load on Host on process named auth and started dy dovecot

### ISSUE THREAD

**Issue by wollo** [Mailu/Mailu#144]
I made a strange observation and do not know if it is an issue and if it is related to the image or not. With top on the docker host I see always one or even more processes called 'auth', with constant high cpu load (around 50%) It is a core i7 machine so it can go up to 800% cpu load. So no point to worry at the moment for me. With top inside the container I see only some processes called dovecot/auth but the have only several % cpu load. Which is understandable, as clients are connecting.
When I close the dovecot container the auth process on the host disappears, and comes back again with 50% CPU load, a few seconds after I have started the Dovecot container again.
Anyone has made the same observations. Any explanation, solutions, suggestions?

**Comment by kaiyou** [comment]
This is probably related to your Dovecot container generating its DH parameters. It should only happen during the first start of the container however.

Does the load decrease at one point?

**Comment by wollo** [comment]
No it persists, or the load even increases.

even after weeks...


Am 10.01.17 um 19:27 schrieb kaiyou:

**Comment by kaiyou** [comment]
Ok. I cannot reproduce the behaviour, either on the latest or stable version. Could you try and check these:
- setup and run another instance of Mailu with no data (separate folder, separate project name, bind to another IP address if you do not want to interfere with the legitimate instance), see if you get the same behaviour
- maybe try with the latest version as well
- check the logs and maybe network traffic on port 143, looking for someone bruteforcing authentication, same with the Webmail
- check ``iotpop`` maybe for some unusual IO

**Comment by wollo** [comment]
Ok, I found the issue. The reason was a badly configured server always trying to send mail. I did not find it before, as I was looking in the dovecot logs, but it was locked in the postfix smtp logs.

Sorry for bothering you!
