### ISSUE TITLE
max_quota_bytes for domain not working?

### ISSUE THREAD

**Issue by okossuth** [Mailu/Mailu#1442]
Hello

It seems that the max_quota_bytes per domain is not working?
I created a domain with max_quota_bytes set to 20MB. Then i proceeded to create two email accounts related to this domain, with quotas set to 15MB and 25MB.
Quotas for email accounts work fine, but what is the purpose of max_quota_bytes at the domain level?
I'm using Mailu 1.7
Thanks!

**Comment by okossuth** [comment]
Just yo update it seems the max_quota_bytes its only enforced when creating the domain and email accounts through the web interface. But if i try to use mailu's command line the limit will not be enforced.

**Comment by Nebukadneza** [comment]
Hi There,

The `Mailu`-Project is currently in a bit of a bind! We are short on man-power, and we need to judge if it is possible for us to put in some work on this issue.

To help with that, we are currently trying to find out which issues are actively keeping users from using `Mailu`, which issues have someone who want to work on them — and which issues may be less important. These a less important ones could be discarded for the time being, until the project is in a more stable and regular state once again.

In order for us to better assess this, it would be helpful if you could put a **reaction on this post** (use the :smiley: icon to the top-right).
- 👍️ if you **need this** to be able to use Mailu. Ideally, you’d also be able to test this on your installation, and provide feedback …
- 🎉 if you find it a **nice bonus**, but no deal-breaker
- 🚀 if you want to **work on it yourself**!
We want to keep this **voting open for 2 weeks** from now, so please help out!

**Comment by Diman0** [comment]
> Just yo update it seems the max_quota_bytes its only enforced when creating the domain and email accounts through the web interface. But if i try to use mailu's command line the limit will not be enforced.

Do you mean that after creating the domains and settings max_quota_bytes via CLI, could you see in the web interface the values were not set?

**Comment by Diman0** [comment]
The quota is indeed only enforced via the Administration page.
