### ISSUE TITLE
Postgres postmaster.pid permission issue

### ISSUE THREAD

**Issue by josephhernandezphd** [Mailu/Mailu#1443]
I am getting the following error when restarting my Mailu instance.  I pulled the lasted version using docker-compose pull.  

```database_1   | pg_ctl: could not open PID file "/data/postmaster.pid": Permission denied
database_1   | pg_ctl: could not open PID file "/data/postmaster.pid": Permission denied
database_1   | Traceback (most recent call last):
database_1   |   File "/start.py", line 59, in <module>
database_1   |     setup()
database_1   |   File "/start.py", line 12, in setup
database_1   |     conn =  psycopg2.connect(user='postgres')
database_1   |   File "/usr/lib/python3.7/site-packages/psycopg2/__init__.py", line 126, in connect
database_1   |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
database_1   | psycopg2.OperationalError: could not connect to server: No such file or directory
database_1   |  Is the server running locally and accepting
database_1   |  connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
```

Is this related to persistent file permissions?  I am running this as root in ubuntu 18

**Comment by Nebukadneza** [comment]
Hi There,

The `Mailu`-Project is currently in a bit of a bind! We are short on man-power, and we need to judge if it is possible for us to put in some work on this issue.

To help with that, we are currently trying to find out which issues are actively keeping users from using `Mailu`, which issues have someone who want to work on them — and which issues may be less important. These a less important ones could be discarded for the time being, until the project is in a more stable and regular state once again.

In order for us to better assess this, it would be helpful if you could put a **reaction on this post** (use the :smiley: icon to the top-right).
- 👍️ if you **need this** to be able to use Mailu. Ideally, you’d also be able to test this on your installation, and provide feedback …
- 🎉 if you find it a **nice bonus**, but no deal-breaker
- 🚀 if you want to **work on it yourself**!
We want to keep this **voting open for 2 weeks** from now, so please help out!
