### ISSUE TITLE
managesieve auth fails

### ISSUE THREAD

**Issue by aksdb** [Mailu/Mailu#1450]
I just setup a new installation of mailu 1.7. Unfortunately, I cannot edit filters. Roundcube throws an error and the `imap` container logs show:

```
managesieve-login: Info: Aborted login (auth failed, 1 attempts in 2 secs) ...
```

Since IMAP login succeeded, the credentials seem to be correct.

**Comment by packet23** [comment]
You can enable authentication debug logging in `overrides/dovecot.conf` by adding `auth_debug = yes`. I had a similar error and had to disable IPv6.

**Comment by muhlemmer** [comment]
@aksdb are you using IPv6?

**Comment by aksdb** [comment]
Damn, I didn't consider that to be related. But now that you mention it it's apparently the same problem as #1336. After trying out master instead of 1.7 it seems to work. So apparently the problem is "fixed in the future". (or maybe could be backported?)

**Comment by Nebukadneza** [comment]
Hi There,

The `Mailu`-Project is currently in a bit of a bind! We are short on man-power, and we need to judge if it is possible for us to put in some work on this issue.

To help with that, we are currently trying to find out which issues are actively keeping users from using `Mailu`, which issues have someone who want to work on them — and which issues may be less important. These a less important ones could be discarded for the time being, until the project is in a more stable and regular state once again.

In order for us to better assess this, it would be helpful if you could put a **reaction on this post** (use the :smiley: icon to the top-right).
- 👍️ if you **need this** to be able to use Mailu. Ideally, you’d also be able to test this on your installation, and provide feedback …
- 🎉 if you find it a **nice bonus**, but no deal-breaker
- 🚀 if you want to **work on it yourself**!
We want to keep this **voting open for 2 weeks** from now, so please help out!
