### ISSUE TITLE
Cannot change profile settings in roundcube (error 600)

### ISSUE THREAD

**Issue by veshus** [Mailu/Mailu#1454]
Help, please, I'm trying to change the default subscription in Roundcube, but get an Error 600.

When in `webmail/?_task=settings&_action=identities` I click on my current identity - got `
SERVICE CURRENTLY NOT AVAILABLE!
Error No. [600]
`
Logs doesn't contain any errors.

**Comment by ghostwheel42** [comment]
My install logs this error:
`PHP Error: Enigma plugin: GPG binary not found. If you are sure the GPG binary is installed, please specify the location of the GPG binary using the 'binary' driver option. in /var/www/html/plugins/enigma/lib/enigma_engine.php on line 91 (GET /?_task=settings&_action=edit-identity&_iid=2&_framed=1)`
I think it will be fixed by #1338
Alex

**Comment by Nebukadneza** [comment]
Hi There,

The `Mailu`-Project is currently in a bit of a bind! We are short on man-power, and we need to judge if it is possible for us to put in some work on this issue.

To help with that, we are currently trying to find out which issues are actively keeping users from using `Mailu`, which issues have someone who want to work on them — and which issues may be less important. These a less important ones could be discarded for the time being, until the project is in a more stable and regular state once again.

In order for us to better assess this, it would be helpful if you could put a **reaction on this post** (use the :smiley: icon to the top-right).
- 👍️ if you **need this** to be able to use Mailu. Ideally, you’d also be able to test this on your installation, and provide feedback …
- 🎉 if you find it a **nice bonus**, but no deal-breaker
- 🚀 if you want to **work on it yourself**!
We want to keep this **voting open for 2 weeks** from now, so please help out!

**Comment by Nebukadneza** [comment]
Like @ghostwheel42 noted, this may be fixed by now-merged #1338. Thus, I’m closing this.

If the issue persists, please feel free to re-open.
