### ISSUE TITLE
How to add dovecot plugin 

### ISSUE THREAD

**Issue by sergeykolzhanov** [Mailu/Mailu#146]
Hi,
I would like to append dovecot_deleted_to_trash plugin to my installation since I have OE and Outlook clients. Can I make it without modifying containers? with using overrides f.e. ?

**Comment by kaiyou** [comment]
Unfortunately, there is currently no way to do this in a simple way.

The best I would recommend is forking our Docker image for Dovecot and install the plugin, the simply replace that specific image in your ``docker-compose.yml``.

**Comment by hadifarnoud** [comment]
and maybe send a PR @sergeykolzhanov. I find that plugin useful too
