### ISSUE TITLE
"Relay access denied" after adding a new domain

### ISSUE THREAD

**Issue by AndreKoepke** [Mailu/Mailu#1460]
Hello,

my mailu-instance is healthy since a few months. Iam very happy with mailu, thank you for the nice software.  
I need a second domain (*.online is a bit to long for the most mail-address-validations ...) so I bought a new one, obtain certificates for it ... and got stuck in a problem.

According to the docs, I changed my configMap to this:    

```
    # Main mail domain
    # It is the old (main) domain
    DOMAIN: "akop.online"

    # Hostnames for this server, separated with comas
    # akop.top is the new domain
    HOSTNAMES: "akop.online,akop.top"
```

And configured a new mail-domain in the admin-panel. I only want one mailbox, so I created a catch-all alias for the new domain and targeting it to my mailbox on the old domain.

But now I have a big problem: If I send an email (from external) to my old domain "test@akop.online", then mailu returns `Relay access denied `.  
When I send a message to the new domain "test@akop.top", then it works perfectly.

What can I do?

**Comment by AndreKoepke** [comment]
It is really funny: This error occurs, when I try to send an email via Googlemail.  
But many other E-Mail-Providers can send me mails without any problem.

**Comment by ofthesun9** [comment]
Hello,
Could you share logs from the SMTP container for both cases (Googlemail and another "working" provider) ?

**Comment by AndreKoepke** [comment]
Yes, there are 3 events

### Correct blocked
```
Apr 30 09:41:35 akop postfix/smtpd[590]: NOQUEUE: reject: RCPT from unknown[85.93.7.247]: 554 5.7.1 <mboconnect2019@hotmail.com>: Relay access denied; from=<contact2421909577@cwu.edu> to=<mboconnect2019@hotmail.com> proto=ESMTP helo=<cwu.edu>
Apr 30 09:41:35 akop postfix/smtpd[590]: disconnect from unknown[85.93.7.247] ehlo=2 xclient=0/1 mail=1 rcpt=0/1 quit=1 commands=4/6
```

### Correct received (from gmail, to new domain) 
```
Apr 30 15:59:14 akop postfix/smtpd[615]: connect from 172-17-0-15.front.mailu-mailserver.svc.cluster.local[172.17.0.15]
Apr 30 15:59:15 akop postfix/smtpd[615]: 9233D5E0092: client=mail-lf1-f47.google.com[209.85.167.47]
Apr 30 15:59:15 akop postfix/cleanup[620]: 9233D5E0092: message-id=<CAFS4dCgjsko0J3n=PT=YGJVgo9__atSKPnwOAqMnjMr-wuM3Tg@mail.gmail.com>
Apr 30 15:59:17 akop postfix/qmgr[126]: 9233D5E0092: from=<SRS0=DBuR=6O=googlemail.com=****@akop.online>, size=2536, nrcpt=1 (queue active)
Apr 30 15:59:18 akop postfix/smtpd[615]: disconnect from mail-lf1-f47.google.com[209.85.167.47] ehlo=2 xclient=0/1 mail=1 rcpt=1 bdat=1 quit=1 commands=6/7
Apr 30 15:59:18 akop postfix/lmtp[621]: 9233D5E0092: to=<*****@akop.online>, orig_to=<test@akop.top>, relay=10.110.141.224[10.110.141.224]:2525, delay=3.3, delays=2.8/0.12/0.07/0.3, dsn=2.0.0, status=sent (250 2.0.0 <****@akop.online> eXtKCdb1ql6gIAAA0dfFiA Saved)
Apr 30 15:59:18 akop postfix/qmgr[126]: 9233D5E0092: removed
```


### Incorrect received (from gmail to old domain)
There are no log-lines. Mh, I will check my dns-config. Maybe is there a problem with DKIM or SPF.  
Google only says: "554 5.7.1 <test@akop.online>: Relay access denied", thats all ...

**Comment by AndreKoepke** [comment]
TLS configuration is fine (via STARTTLS), DNS-Config seems fine. 
![test](https://media.giphy.com/media/xL7PDV9frcudO/giphy.gif)

**Comment by ofthesun9** [comment]
I see that akop.online is having a AAAA record in addition to a A record (akop.top is only having a A record). I did a quick check using the A record and the AAAA record, and it seems to me that these are different hosts... My guess is that the AAAA is not correct ;-)

**Comment by AndreKoepke** [comment]
@ofthesun9 totally true. I don't have IPV6 configured yet, so the AAAA is a relict. Thank you very much.
