### ISSUE TITLE
Can't connect w external client but Webmail works Fine

### ISSUE THREAD

**Issue by odoo-mastercore** [Mailu/Mailu#1461]
Hi there, 

I use **jwilder/nginx-proxy:latest** and **jrcs/letsencrypt-nginx-proxy-companion:latest** on same network

here is docker-compose.yml

**===================== docker-compose.yml ===============================**

version: '2.2'

services:

  **# External dependencies**
  **redis:**
    image: redis:alpine
    restart: always
    volumes:
      - "/mailu/redis:/data"
    networks:
      - production
    
  **# Core services**

  **front:**
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}nginx:${MAILU_VERSION:-1.7}
    restart: always
    env_file: mailu.env
    **environment:**
      - VIRTUAL_HOST=mail.mydomain.com
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=mail.mydomain.com
      - LETSENCRYPT_MAIL=mymail
    logging:
      driver: json-file
    **ports:**
      - "PUBLIC_IP_V4:25:25"
      - "PUBLIC_IP_V4:465:465"
      - "PUBLIC_IP_V4:587:587"
      - "PUBLIC_IP_V4:110:110"
      - "PUBLIC_IP_V4:995:995"
      - "PUBLIC_IP_V4:143:143"
      - "PUBLIC_IP_V4:993:993"
    networks:
      - production
    volumes:
      - "/etc/nginx/certs:/certs"
      - "/mailu/overrides/nginx:/overrides"

  **admin:**
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}admin:${MAILU_VERSION:-1.7}
    restart: always
    env_file: mailu.env
    volumes:
      - "/mailu/data:/data"
      - "/mailu/dkim:/dkim"
    depends_on:
      - redis
    networks:
      - production

  **imap:**
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}dovecot:${MAILU_VERSION:-1.7}
    restart: always
    env_file: mailu.env
    volumes:
      - "/mailu/mail:/mail"
      - "/mailu/overrides:/overrides"
    depends_on:
      - front
    networks:
      - production

  **smtp:**
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}postfix:${MAILU_VERSION:-1.7}
    restart: always
    env_file: mailu.env
    volumes:
      - "/mailu/overrides:/overrides"
    depends_on:
      - front
    networks:
      - production

  **antispam:**
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}rspamd:${MAILU_VERSION:-1.7}
    restart: always
    env_file: mailu.env
    volumes:
      - "/mailu/filter:/var/lib/rspamd"
      - "/mailu/dkim:/dkim"
      - "/mailu/overrides/rspamd:/etc/rspamd/override.d"
    depends_on:
      - front
    networks:
      - production

  **webdav:**
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}radicale:${MAILU_VERSION:-1.7}
    restart: always
    env_file: mailu.env
    volumes:
      - "/mailu/dav:/data"
    networks:
      - production

  **fetchmail:**
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}fetchmail:${MAILU_VERSION:-1.7}
    restart: always
    env_file: mailu.env
    networks:
      - production

 **webmail:**
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}roundcube:${MAILU_VERSION:-1.7}
    restart: always
    env_file: mailu.env
    volumes:
      - "/mailu/webmail:/data"
    depends_on:
      - imap
    networks:
      - production

**networks:**
  production:
    external:
      name: PRODUCTION

==================================
Here mailu.env

**==================== mailu.env =========================**

SECRET_KEY=XXXXXXXXXXXXX

SUBNET=172.31.0.0/22

DOMAIN=mydomain.com

HOSTNAMES=mail.mydomain.com

POSTMASTER=admin

TLS_FLAVOR=mail

AUTH_RATELIMIT=10/minute;1000/hour 

DISABLE_STATISTICS=False

ADMIN=true

WEBMAIL=roundcube

WEBDAV=radicale

MESSAGE_SIZE_LIMIT=50000000

RELAYNETS=

RELAYHOST=

FETCHMAIL_DELAY=600

RECIPIENT_DELIMITER=+

DMARC_RUA=admin
DMARC_RUF=admin

COMPRESSION=
COMPRESSION_LEVEL=

WEBROOT_REDIRECT=/admin

WEB_ADMIN=/admin

WEB_WEBMAIL=/webmail

SITENAME=mydomain.com Mail

WEBSITE=https://mail.mydomain.com

COMPOSE_PROJECT_NAME=mailu

PASSWORD_SCHEME=BLF-CRYPT

REAL_IP_HEADER=

REAL_IP_FROM=

REJECT_UNLISTED_RECIPIENT=

LOG_LEVEL=WARNING

DB_FLAVOR=sqlite

===========================================================

**here is docker network inspect PRODUCTION**

    {
        "Name": "PRODUCTION",
        "Id": "_______________",
        "Created": "2020-04-24T19:55:34.986359302-03:00",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.31.0.0/22",
                    "Gateway": "172.31.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": true,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        .
        .
        .
        .
        .

==============================================

I can't connect to external client...

But from Webmail i can send and receive mails. 

**VERY THANKS FOR HELP**

**Comment by odoo-mastercore** [comment]
Hi again. 
Inside Network (from another host inside network)

# nmap 172.31.0.12 -Pn
Starting Nmap 7.70 ( https://nmap.org ) at 2020-04-25 17:03 UTC
Nmap scan report for **mailu_front_1.PRODUCTION** (172.31.0.12)
Host is up (0.000021s latency).
Not shown: 997 closed ports
PORT      STATE SERVICE
25/tcp    open  smtp
80/tcp    open  http
10025/tcp open  unknown

# nmap mail.mydomain.com
Starting Nmap 7.70 ( https://nmap.org ) at 2020-04-25 17:03 UTC
Nmap scan report for mail.mydomain.com (PUBLIC_IP)
Host is up (0.000030s latency).
Not shown: 990 closed ports
PORT    STATE SERVICE
22/tcp  open  ssh
25/tcp  open  smtp
80/tcp  open  http
110/tcp open  pop3
143/tcp open  imap
443/tcp open  https
465/tcp open  smtps
587/tcp open  submission
993/tcp open  imaps
995/tcp open  pop3s


==============
**Outside network (other point of world)** 

╰─$ nmap mail.mydomain.com
Starting Nmap 7.70 ( https://nmap.org ) at 2020-04-25 14:04 -03
Nmap scan report for mail.mydomain.com (PUBLIC_IP)
Host is up (0.26s latency).
Not shown: 996 closed ports
PORT    STATE SERVICE
22/tcp  open  ssh
25/tcp  open  smtp
80/tcp  open  http
443/tcp open  https

**Comment by ofthesun9** [comment]
Hello,
Please have a look in the documentation : [Finish setting up TLS](https://mailu.io/1.7/compose/setup.html#finish-setting-up-tls)
You will also need to share the certs generated by jrcs/letsencrypt-nginx-proxy-companion with your front service

**Comment by odoo-mastercore** [comment]
I can solve it 

It was a broken link of SSL cert's.
