### ISSUE TITLE
Authentication rate limit affect to webmail.

### ISSUE THREAD

**Issue by calmohallag** [Mailu/Mailu#1462]
I set up Mailu over https 4433 port. Then I access locally by apache proxy.

When user use webmail, authentication rate limit make user get error on normal usage.

HTTP/1.1", host: "domain.com:4433", referrer: "https://domain.com/webmail/?_task=mail&_mbox=INBOX"
front_1      | 2020/04/25 18:14:56 [info] 12#12: *205 client 192.168.150.10:35120 connected to 0.0.0.0:10143
front_1      | 2020/04/25 18:14:56 [info] 12#12: *205 client login failed: "Authentication rate limit from one source exceeded" while in http auth state, client: 192.168.150.10, server: 0.0.0.0:10143, login: "mi@domain.com"
front_1      | 127.0.0.1 - - [25/Apr/2020:18:14:56 +0000] "GET /auth/email HTTP/1.0" 200 0 "-" "-"

192.168.150/24 is docker network
Mailu 1.7

**Comment by ChrisBarriere** [comment]
Same problem for me with webmail behind Traefik V2:

Log from mailu_front: client login failed: "Authentication rate limit from one source exceeded" while in http auth state, client: 192.168.203.11, server: 0.0.0.0:10143, login:me@XXXX.XX

**Comment by ChrisBarriere** [comment]
Currently the ratelimiting happens for all authentications (then  the webmail creates a new imap session on each click, so it easily exhauses the rate limit).

I read_ the PR https://github.com/Mailu/Mailu/pull/1278.  With this PR, only failed auths will increment the counter.

We have to wait for the new version (1.8). The solution for the moment is to modify the value of AUTH_RATELIMIT in teh env file
