### ISSUE TITLE
When changing POSTMASTER in setup.mailu.io, DMARC_RUA and DMARC_RUF are not updated

### ISSUE THREAD

**Issue by JayBeavers** [Mailu/Mailu#1463]
For example, if in the web ui for generating mailu.env I change the POSTMASTER from 'admin' to 'jay', I get:

POSTMASTER=jay
DMARC_RUA=admin
DMARC_RUF=admin

I expected to get:

POSTMASTER=jay
DMARC_RUA=jay
DMARC_RUF=jay

**Comment by ofthesun9** [comment]
Thanks for the feedback, I will submit a PR to fix this.
