### ISSUE TITLE
internal TLS connections between  Mailu containers

### ISSUE THREAD

**Issue by tafkam** [Mailu/Mailu#1466]
I would like to know if there any plans to introduce TLS connections between all Mailu containers. As far as I can figure out how the Mailu components are working together, the TLS termination for mails ends at the frontend nginx loadbalancer. 

Correct me please if I have missed something in the core component configurations, but external mail traffic or authentication seem to be proxied without encryption from the frontend nginx to the admin container, and is then sent to postfix/dovecot in plain text. This is not desirable at all on a kubernetes cluster in a public network. In that regard the security feature claim about "enforced TLS" is a bit misleading.

I have tried to use istio for mTLS encryption with Mailu, but then postfix and dovecot break since the source of all mail traffic is 127.0.0.1 (coming from the local envoy proxy sidecar). 
Postfix is a open relay then with POD_ADDRESS_RANGE configuration set to 127.0.0.1. (sadly istio doesn't seem to support ip masquerading of incoming traffic any time soon.. but that is another github issue ;-))

I'm trying to figure out how to get TLS encryption working for all Mailu components by changing the frontend nginx config to https upstreams, using nginx sidecars for TLS termination on the http based containers, and adding TLS ports to postfix/dovecot override configs. TLS for redis seems a bit painful, but could be mitigated with a redis sidecar for the components which need it.
But I'm pretty sure I will fail on the admin container and it's python components to get this working properly. I guess smtps or imaps won't work out of the box in the admin container by just switching ports.

Do you have any advice on this or plans for full network encryption in mailu?

**Comment by muhlemmer** [comment]
> Correct me please if I have missed something in the core component configurations, but external mail traffic or authentication seem to be proxied without encryption from the frontend nginx to the admin container, and is then sent to postfix/dovecot in plain text. This is not desirable at all on a kubernetes cluster in a public network. In that regard the security feature claim about "enforced TLS" is a bit misleading.

Nginx is termination for authentication and TLS. This is our security model. If TLS does not work, Nginx blocks all incoming connections. The connection between nginx and the other containers has to be a 100% trusted network! Even if you do manage to make it TLS secured, anybody that has access to the network will be able to send unauthenticated mail. (Open relay).

1. Mailu was originally developed for `docker-compose` and the internal network runs completely on the host. Hence, considered secure.
2. Docker swarm is another (experimental) deployment target. It allows for IPSec encrypted networks between hosts. If setup correctly, this is also secure.
3. Perhaps on a multi-node K8S cluster, some kind of secure network is to be configured. (Sorry, not a K83 guy myself). I would recommend trying IPSec, like swarm. 

In both cases 2 and 3 it is more cluster administrators job to keep the internal network secure I guess. Hope this gave you some pointers. There are a few people using K8S and if you a are lucky they might pitch in. Or feel free to join our matrix chat ;) (link on website).

**Comment by tafkam** [comment]
To clarify on the k8s networking part, the access from external networks to the internal k8s network is secured, so external connections have to go through the frontend loadbalancer. But if the frontend runs on one server1, the admin container runs on server2 and postfix runs on server3 all traffic between those servers is basically unencrypted in the mailu setup and open to eavesdropping. This is an issue for clusters on public clouds (or basically anywhere, where you don't own the network infrastructure).
My point is, because http and unencrypted ports are hardcoded into the components, there is no way to properly secure this traffic from a administrators' point of view, since code changes have to be done at least in the admin container, as I pointed out. (There might be other service mesh solutions beside istio which might work though, but meh.)

**Comment by unixfox** [comment]
Meanwhile, you may deploy Mailu in an encrypted network like Wormhole offers thanks to Wireguard: https://github.com/gravitational/wormhole

**Comment by micw** [comment]
> But if the frontend runs on one server1, the admin container runs on server2 and postfix runs on server3 all traffic between those servers is basically unencrypted in the mailu setup and open to eavesdropping. This is an issue for clusters on public clouds (or basically anywhere, where you don't own the network infrastructure).

I strongly disagree that this is an application layer issue. Public cloud providers provide network isolation (like AWS VPC). If you don't trust in that, you can switch to a CNI that supports inter-node encryption (like wormhole mentioned by @unixfox). (Personally I think if you don't trust in cloud provider's network isolation, you should also not trust in vendor's disc encryption where the cloud provider manages your keys and switch the cloud provider).

> Postfix is a open relay then with POD_ADDRESS_RANGE configuration set to 127.0.0.1

No, it is not. It's only an open relay if you shape the traffic in a way that it seems to come from 127.0.0.1 (e.g. by allowing the local proxy to be accessed from everywhere).

> Do you have any advice on this or plans for full network encryption in mailu?

I see this way out of Mailu's development scope. Nevertheless, I'd be open to PRs around this.

**Comment by Nebukadneza** [comment]
Hi There,

The `Mailu`-Project is currently in a bit of a bind! We are short on man-power, and we need to judge if it is possible for us to put in some work on this issue.

To help with that, we are currently trying to find out which issues are actively keeping users from using `Mailu`, which issues have someone who want to work on them — and which issues may be less important. These a less important ones could be discarded for the time being, until the project is in a more stable and regular state once again.

In order for us to better assess this, it would be helpful if you could put a **reaction on this post** (use the :smiley: icon to the top-right).
- 👍️ if you **need this** to be able to use Mailu. Ideally, you’d also be able to test this on your installation, and provide feedback …
- 🎉 if you find it a **nice bonus**, but no deal-breaker
- 🚀 if you want to **work on it yourself**!
We want to keep this **voting open for 2 weeks** from now, so please help out!

**Comment by benyanke** [comment]
not stale, this is important security work

**Comment by Diman0** [comment]
Hi There,

we see this issue had only little attention 😟. As much as it pains us: In order to get the current issues a bit more manageable for us, we decided to close it. 👋👋

We hope that no one feels offended by doing so. Should the issue get really pressing in the future, please feel free to re-open it.

Thank you for your patience and understanding, 🙇
- Your Mailu Team

**Comment by thienohs** [comment]
> I would like to know if there any plans to introduce TLS connections between all Mailu containers. As far as I can figure out how the Mailu components are working together, the TLS termination for mails ends at the frontend nginx loadbalancer.
> 
> Correct me please if I have missed something in the core component configurations, but external mail traffic or authentication seem to be proxied without encryption from the frontend nginx to the admin container, and is then sent to postfix/dovecot in plain text. This is not desirable at all on a kubernetes cluster in a public network. In that regard the security feature claim about "enforced TLS" is a bit misleading.
> 
> I have tried to use istio for mTLS encryption with Mailu, but then postfix and dovecot break since the source of all mail traffic is 127.0.0.1 (coming from the local envoy proxy sidecar).
> Postfix is a open relay then with POD_ADDRESS_RANGE configuration set to 127.0.0.1. (sadly istio doesn't seem to support ip masquerading of incoming traffic any time soon.. but that is another github issue ;-))
> 
> I'm trying to figure out how to get TLS encryption working for all Mailu components by changing the frontend nginx config to https upstreams, using nginx sidecars for TLS termination on the http based containers, and adding TLS ports to postfix/dovecot override configs. TLS for redis seems a bit painful, but could be mitigated with a redis sidecar for the components which need it.
> But I'm pretty sure I will fail on the admin container and it's python components to get this working properly. I guess smtps or imaps won't work out of the box in the admin container by just switching ports.
> 
> Do you have any advice on this or plans for full network encryption in mailu?

Hi @tafkam , was you able to setup mailu to work with istio ? I have changed the SUBNET configuration to 127.0.0.0/8, 127.0.0.0/16(along with even disabling istio mTLS tunnelling using PeerAuthentication), however, dovecot and postfix still not connecting with the front API (They are working fine without istio injected sidecar - envoy proxy).

For example, i'm getting timeout when login from Webmail:
![image](https://user-images.githubusercontent.com/4403470/120929648-001b6200-c714-11eb-8692-51f2a74aa412.png)

Due to issue with imap:
IMAP Error: Login failed for <email> against front.mailu-mailserver.svc.cluster.local from 127.0.0.6(X-Real-IP: 127.0.0.6,X-Forwarded-For: 188.166.232.168, 127.0.0.6). Empty startup greeting (front.mailu-mailserver.svc.cluster.local:10143) in /var/www/html/program/lib/Roundcube/rcube_imap.php on line 200 (POST /?_task=login&_action=login)
