### ISSUE TITLE
SSL Certs

### ISSUE THREAD

**Issue by adi90x** [Mailu/Mailu#147]
Hello, 
Is there a way to use a different SSL certs per domain name  ? 
Basically, I have 2 virtual domain setup in Mailu, however I can use SMTP with SSL on one of them because my certs are single host (using Let's Encrypt).
Would it be possible to use a kind of regex in postfix something like domainname.cert and domainname.key that would point to the best match cert in the certs folder ? 

regards,

**Comment by adi90x** [comment]
Ok , I reply to myself , seems impossible because Postfix don't know which host is requested ^^
Will probably try to do a multi domain cert ...
Not sure if Let's encrypt support has been added to Mailu but I may tried to work something if anyone is interested ?

**Comment by kaiyou** [comment]
I don't think that Postfix supports SNI unfortunately. And it probably never will.
There is some letsencrypt support available through the ``CERTBOT`` configuration value, but it requires that you first setup a junk certificate (self signed for instance) first.

Regarding TLS for the SMTP and IMAP with multiple names, I would recommend that you have a single generic name instead. For instance, the TeDomum association runs Mailu for many domains, but all users connect to ``mail.tedomum.net``, same for the MX.

**Comment by adi90x** [comment]
Perfectly working with a SAN certificate from let's encrypt ! Problem solved ! Closing the issue !
