### ISSUE TITLE
Rerun Lets Encrypt

### ISSUE THREAD

**Issue by ShazerHD** [Mailu/Mailu#1474]
Hello,

When I was setting up Mailu, I forgot to open port 80 on my router and so lets encrypt failed.
Is there a way to rerun it?

**Comment by ofthesun9** [comment]
Hello,
Mailu will retry/check every hour.
If you want to rerun without waiting, you can recreate the stack:
```
docker-compose down
docker-compose up -d 
```
We have also an [faq](https://mailu.io/master/faq.html#letsencrypt-issues) entry for further let's encrypt troubleshooting, if needed.

**Comment by HorayNarea** [comment]
just restarting the front container via
```
docker-compose restart front
```
should also be enough to retrigger lets encrypt

**Comment by simokarpin** [comment]
Just adding here - looking into https://github.com/Mailu/Mailu/blob/master/core/nginx/letsencrypt.py 
Is there a reason why it spawns on port 8008 but never exposed outside of docker?

**Comment by HorayNarea** [comment]
The `.well-known` directory is reverse-proxied:
https://github.com/Mailu/Mailu/blob/master/core/nginx/conf/nginx.conf#L84

**Comment by ofthesun9** [comment]
@ShazerHD , I assume we can close this now. If you still have some issues, feel free to reopen it.
