### ISSUE TITLE
1.7: postgresql crash

### ISSUE THREAD

**Issue by chint95** [Mailu/Mailu#1479]
After #1469 the postgresql container crashes on my ipv4 only system with:

CONTEXT:  line 85 of configuration file "/data/pg_hba.conf"
FATAL:  could not load pg_hba.conf

Setting SUBNET6 env seems to resolve the problem.

**Comment by ToBoNaToR3** [comment]
I got the same error message on a ipv4 only server. Thank you so much for the tip with the SUBNET6 setting. This saved me a lot of time!
SUBNET6=::1/32 in the mailu.env fixed postgres for me.

**Comment by muhlemmer** [comment]
My sincere apologies. For now, I will revert the merge of #1469. We need to implement a conditional for this variable.

**Comment by Nebukadneza** [comment]
Hi There,

The `Mailu`-Project is currently in a bit of a bind! We are short on man-power, and we need to judge if it is possible for us to put in some work on this issue.

To help with that, we are currently trying to find out which issues are actively keeping users from using `Mailu`, which issues have someone who want to work on them — and which issues may be less important. These a less important ones could be discarded for the time being, until the project is in a more stable and regular state once again.

In order for us to better assess this, it would be helpful if you could put a **reaction on this post** (use the :smiley: icon to the top-right).
- 👍️ if you **need this** to be able to use Mailu. Ideally, you’d also be able to test this on your installation, and provide feedback …
- 🎉 if you find it a **nice bonus**, but no deal-breaker
- 🚀 if you want to **work on it yourself**!
We want to keep this **voting open for 2 weeks** from now, so please help out!

**Comment by Diman0** [comment]
Hi There,

we see this issue had only little attention 😟. As much as it pains us: In order to get the current issues a bit more manageable for us, we decided to close it. 👋👋

We hope that no one feels offended by doing so. Should the issue get really pressing in the future, please feel free to re-open it.

Thank you for your patience and understanding, 🙇
- Your Mailu Team
