### ISSUE TITLE
postfix throttling afer a hard shutdown

### ISSUE THREAD

**Issue by ofthesun9** [Mailu/Mailu#1483]
After a hard shutdown, I noticed that postfix would not restart because of master.pid is found in /queue/pid/master.pid
We should check and remove this file during container start up (start.py)

**Comment by ofthesun9** [comment]
It is quiet hard to reproduce though !
Most likely an issue related to my nfs share set-up.
Closing now.

**Comment by micw** [comment]
I reopen this due to https://github.com/Mailu/helm-charts/issues/54. It seems to affect others as well.

**Comment by Nebukadneza** [comment]
Hi There,

The `Mailu`-Project is currently in a bit of a bind! We are short on man-power, and we need to judge if it is possible for us to put in some work on this issue.

To help with that, we are currently trying to find out which issues are actively keeping users from using `Mailu`, which issues have someone who want to work on them — and which issues may be less important. These a less important ones could be discarded for the time being, until the project is in a more stable and regular state once again.

In order for us to better assess this, it would be helpful if you could put a **reaction on this post** (use the :smiley: icon to the top-right).
- 👍️ if you **need this** to be able to use Mailu. Ideally, you’d also be able to test this on your installation, and provide feedback …
- 🎉 if you find it a **nice bonus**, but no deal-breaker
- 🚀 if you want to **work on it yourself**!
We want to keep this **voting open for 2 weeks** from now, so please help out!
