### ISSUE TITLE
no webdav manifest

### ISSUE THREAD

**Issue by RavenB** [Mailu/Mailu#150]
Hi,

wile trying to start mailu with webdav configured in env i get the following error

Pulling webdav (mailu/radicale:stable)...
Trying to pull repository docker.io/mailu/radicale ...
ERROR: manifest unknown: manifest unknown

**Comment by kaiyou** [comment]
You should not enable Webdav on ``stable``, sorry if that wasn't documented. It is currently only available in ``latest`` for testing.
