### ISSUE TITLE
Keep Emails setting

### ISSUE THREAD

**Issue by okossuth** [Mailu/Mailu#1505]
Hello

In fetched accounts, can anybody explain me what is the Keep emails setting for?
At first i thought that it would prevent deletion of emails on the server but that seems
to not be the case. 
Thanks

**Comment by kaiyou** [comment]
Your understanding is correct though, it is meant to keep emails from being deleted on the remote server.

It might not work properly using pop3 since many servers delete emails anyway when pulled using pop3.

**Comment by okossuth** [comment]
Cool thanks!
