### ISSUE TITLE
mailu 1.7/master authentication failures

### ISSUE THREAD

**Issue by diresi** [Mailu/Mailu#1509]
I'm running mailu via docker-compose and tried both 1.7 and master with similar results.
Mailu is running behind an external non-dockerized nginx as reverse proxy, so maybe that's an issue.

Anyway, what I see is this:
- log in to webmail works most of the time, also when returning after some time I'm automatically logged in
- if not, it helps to force logins using private mode or by wiping related history from my browser
- webmail then seems to work normally
- after approx 1 minute operations start to fail: refreshing the message list, changing folders, loading messages, ...
- but then again, suddenly new-mail notifications pop up (without reloading or logging in again) so it's not all broken

I tried changing $SUBNET as suggested in #1156, re-creating containers and also removing/recreating the docker network, all without success. 

The logs seem pretty noisy to me, I guess that bots are checking me out, so I can see a bunch of failed/aborted logins in the `imap` container (without username).

I'd be happy to post some logs but I don't know what exactly to look for...

EDIT:
I also used to run wireguard on the same machine, but since wireguard and docker don't go together well I removed wireguard again.

**Comment by diresi** [comment]
Having written this issue report, suddenly webmail works again. I did _not_ reload the page.
Switching between folders works again, loading messages also ...

Is this some sort of temporal anomaly that's known or expected?

**Comment by tborychowski** [comment]
I tried Mailu for the first time today and I'm having the exactly same issues

**Comment by doy** [comment]
i'm also seeing this, but even setting `AUTH_RATELIMIT=1000/minute;10000/hour` doesn't keep these errors from happening for me.

**Comment by diresi** [comment]
thanks @tborychowski for the hint 'bout AUTH_RATELIMIT. I increased it as well, although I cannot find any "exceeded" logs anymore, but it's the best I bet for now.

also, I didn't experience any oddities since that first report, so maybe it's just fixed now.
thus I'm going to close the issue, the whole thing is probably too vague anyway.
