### ISSUE TITLE
Review of SSL ciphers

### ISSUE THREAD

**Issue by adi90x** [Mailu/Mailu#151]
Hello, 

There should be a review of all SSL ciphers available , as for the moment mailu scores F on [CryptCheck](https://tls.imirhil.fr/)

MD5-ANONYMOUS-DES3-RC4 should be disable I think.

**Comment by hoellen** [comment]
I think this ciphers would be good:

`ssl_cipher_list = ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES256-SHA:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:!DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA:!CAMELLIA128:!CAMELLIA256`

What do you think? Stronger?

I think we should also change: `ssl_prefer_server_ciphers = yes`

greets
hoellen

**Comment by kaiyou** [comment]
This is indeed worrying, especially given issue #45 that supposedly took care of the matter. I am investigating this urgently.

**Comment by kaiyou** [comment]
Indeed, the Postfix TLS configuration was only applied for mandatory encryption (on Submission port for instance) but not on opportunistic encryption. I just changed that on master and will be testing for a couple days.

**Comment by kaiyou** [comment]
CryptCheck score just bumped to B. There is still room for improvement but most issues are addresses. Maybe TLS1.0 could be disabled, as well as DH enforced with a 2048bits key.

**Comment by adi90x** [comment]
Look way better !
