### ISSUE TITLE
Issue letsencrypt fails during secondary validation: no valid ip address found

### ISSUE THREAD

**Issue by soermejo** [Mailu/Mailu#1510]
I have a vps with a NAT. The ip where is running the vps is a local IP (10.x.x.x) so it can't be reached by remote. I do have a public ip with NAT 1:1 to the local vps ip address. I provided this ip address to "IPv4 listen address" here https://setup.mailu.io/1.7/submit_flavor. But i'm getting this error https://nekobin.com/bosudupivu  when i run the generated configuration for the first time. 

Is there some way i can solve this issue?

By the way, I'm using scaleway as vps provider.

**Comment by soermejo** [comment]
After 12 hours now https://mail.namoso.tk/admin seems magically working fine but https://mail.namoso.tk/webmail not working "NOT FOUND"

**Comment by muhlemmer** [comment]
The IP address should be the interface address of the **local** server. This is where Docker will try to bind the `front` service. This should match with the info from:

````
$ ip address
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 96:00:00:18:22:ff brd ff:ff:ff:ff:ff:ff
    inet 116.203.53.123/32 brd 116.203.53.123 scope global dynamic eth0
       valid_lft 58296sec preferred_lft 58296sec
    inet6 2a01:dead:beef::1/64 scope global 
       valid_lft forever preferred_lft forever
    inet6 fe80::9400:ff:fe18:22ff/64 scope link 
       valid_lft forever preferred_lft forever
````

In this case the adapter I'm using is `eth0`. The applicable IP addresses are `116.203.53.123` and `2a01:dead:beef::1` in case of IPv6

`HOSTNAMES` are the **public** addresses, usually sub-domains where the server is reachable. When you have a NAT, your DNS records should point to the public address of the NAT. Ports should be forwarded to the local IP address of the server.

**Comment by Nebukadneza** [comment]
Hi There,

The `Mailu`-Project is currently in a bit of a bind! We are short on man-power, and we need to judge if it is possible for us to put in some work on this issue.

To help with that, we are currently trying to find out which issues are actively keeping users from using `Mailu`, which issues have someone who want to work on them — and which issues may be less important. These a less important ones could be discarded for the time being, until the project is in a more stable and regular state once again.

In order for us to better assess this, it would be helpful if you could put a **reaction on this post** (use the :smiley: icon to the top-right).
- 👍️ if you **need this** to be able to use Mailu. Ideally, you’d also be able to test this on your installation, and provide feedback …
- 🎉 if you find it a **nice bonus**, but no deal-breaker
- 🚀 if you want to **work on it yourself**!
We want to keep this **voting open for 2 weeks** from now, so please help out!

**Comment by Diman0** [comment]
Hi There,

we see this issue had only little attention 😟. As much as it pains us: In order to get the current issues a bit more manageable for us, we decided to close it. 👋👋

We hope that no one feels offended by doing so. Should the issue get really pressing in the future, please feel free to re-open it.

Thank you for your patience and understanding, 🙇
- Your Mailu Team
