### ISSUE TITLE
webdav service : Radicale 3.0 is released. -f option is not longer supported.

### ISSUE THREAD

**Issue by ofthesun9** [Mailu/Mailu#1512]
[Release notes for 3.0](https://github.com/Kozea/Radicale/blob/3.0.x/NEWS.md#300)
Travis builds are currently failing:
```
Printing logs for: webdav_webdav_1_e0f619906f75
usage: radicale [OPTIONS]
radicale: error: unrecognized arguments: -f
```
I will propose a PR to stick to radicale 2.1.12, until we have time to investigate what other changes might be needed to use radicale 3.0

**Comment by psukys** [comment]
So far, seems that foreground is the default functionality, as 3.0 is delegating daemon duties to service managers. Tho, by the look of incoming issues in Radicale, it probably makes sense to not move to 3.0 just yet. Maybe this ticket could track relevant changes for Radicale 3.0?

**Comment by ofthesun9** [comment]
Yes, this PR should remain open until we investigate the changes needed to go switch to radicale 3.0.
Fot the time being, master is built with Radicale 2.1.12. There is also a backport for Mailu 1.7, but not merged yet.
I could push a PR to get a build against Radicale 3.0, but I can't run functional test for the time being..
@psukys , would you have time to do some functional tests on Radicale 3.0 ?

**Comment by psukys** [comment]
can do, tho likely weekend/next week

**Comment by ofthesun9** [comment]
@psukys Thanks !
the build with radicale 3.0 is available through: mailutest/radicale:pr-1526

**Comment by ofthesun9** [comment]
Radicale 3.0.3 released 3 days ago
bors try to rebuild the test image mailutest/radicale:pr-1526
