### ISSUE TITLE
[admin] edit alias, user or domain fails

### ISSUE THREAD

**Issue by hoellen** [Mailu/Mailu#152]
Hello, 

if you want to edit an existing alias, user or domain in admin panel, you can't save the new data because you get the error message 'This field is required.' 

greets
hoellen

**Comment by kaiyou** [comment]
I cannot reproduce this, would you please provide some steps? Also, what browser are you using, and is Javascript enabled?

**Comment by trueserve** [comment]
I can reproduce this.

* PaleMoon 27.0.3
* Docker version 1.12.6, build 78d1802, Gentoo LXD container
* Running Mailu:latest, I do not know how to pull a specific version, let me know if you need it

Steps to reproduce:
1. Edit an account of some type, where the account name on the edit screen is an uneditable field
(such as _/admin/user/edit/acct@domain.com_ or _/admin/domain/edit/domain.com_)
2. Save changes by clicking Save Settings or the erroneous "Create" button
3. The uneditable name field is now empty, highlighted, and has the error "This field is required."

Expected result:
1. Changes are saved.
----
![fail_message](https://cloud.githubusercontent.com/assets/888856/22240421/fcfbbc10-e1cf-11e6-9720-de326a61c5a7.png)

**Comment by hoellen** [comment]
The image shows exactly what i mean. I use Firefox 50.1.0 with uMatrix (like NoScript) but scripts are enabled.
Server: Mailu:stable with Docker 1.13.0

**Comment by kaiyou** [comment]
Okay, I managed to reproduce that behaviour on Chromium as well but I cannot isolate why yet. Working on it right now, thank you for reporting!

**Comment by kaiyou** [comment]
I isolated the behaviour to that commit : https://github.com/kvesteri/wtforms-components/commit/5083591825aeb7681b7819603ed0cf7ea6f6a3f9

Because the field is disabled, the input is not sent when the form is validated, thus affecting validation.

**Comment by kaiyou** [comment]
I just pushed a fix to master, disabling validation for these specific fields when they are disabled. This should not cause any security issue because disabling the field also disables the ``populate_obj`` from the field.

**Comment by kaiyou** [comment]
I also reported the change in behavior to the developers of WTForms Components.

**Comment by hoellen** [comment]
I tested users, aliases and domains and it worked. Thanks.

**Comment by kaiyou** [comment]
I just pushed to ``stable`` after some testing.
