### ISSUE TITLE
Build webmails on php:fpm-alpine

### ISSUE THREAD

**Issue by bolet** [Mailu/Mailu#1521]
Mailu's webmails are both built on debian/apache/php.

AFAIK all other mailu components are based on alpine, and we already have an nginx frontend.

IMHO it would make sense to rebase webmails on php:fpm-alpine and use the same nginx frontend for the static parts of the webmails.

If we want independent webmail containers (which is also nice), we should at least build the images with alpine/nginx/php-fpm built-in.

**Comment by Nebukadneza** [comment]
Hi There,

The `Mailu`-Project is currently in a bit of a bind! We are short on man-power, and we need to judge if it is possible for us to put in some work on this issue.

To help with that, we are currently trying to find out which issues are actively keeping users from using `Mailu`, which issues have someone who want to work on them — and which issues may be less important. These a less important ones could be discarded for the time being, until the project is in a more stable and regular state once again.

In order for us to better assess this, it would be helpful if you could put a **reaction on this post** (use the :smiley: icon to the top-right).
- 👍️ if you **need this** to be able to use Mailu. Ideally, you’d also be able to test this on your installation, and provide feedback …
- 🎉 if you find it a **nice bonus**, but no deal-breaker
- 🚀 if you want to **work on it yourself**!
We want to keep this **voting open for 2 weeks** from now, so please help out!

**Comment by lub** [comment]
Using fpm and serving the static files via the existing would require sharing the files between both containers either via volumes (and subsequently some upgrade logic) or by putting all webmail files also in the nginx image.

I think your second proposal (completely independent containers) makes more sense, which is probably why it's currently built that way.

For using alpine we'd need to switch the base image, as docker.io/php doesn't provide tags with both alpine base and an integrated web server as far as I can see.

I don't really see a benefit in switching to alpine just for the sake of it, considering we'd need different base images and thus would have to switch away from the official Docker image for php.

**Comment by Diman0** [comment]
Hi There,

we see this issue had only little attention 😟. As much as it pains us: In order to get the current issues a bit more manageable for us, we decided to close it. 👋👋

We hope that no one feels offended by doing so. Should the issue get really pressing in the future, please feel free to re-open it.

Thank you for your patience and understanding, 🙇
- Your Mailu Team

**Comment by nextgens** [comment]
I'd like to re-open this.

Here the image of the webmail is over 600MiB, fresh start with no user it's 70MiB of RAM... we can do better.

**Comment by nextgens** [comment]
One good reason to switch is to limit the number of technologies (and configuration syntaxes) one has to be familiar with. If front is nginx, whatever is behind should either have very little configuration (FPM) or be the same (another nginx instance)

**Comment by Diman0** [comment]
There are a couple of possibilities:
- Use php:fpm-alpine and use the same nginx frontend (front image) for the static parts of the webmails.
- Use php:fpm-alpine and also use this image for serving static files

For roundcube we could chose to base our image on the official roundcube php-fpm-alpine image. 
https://github.com/roundcube/roundcubemail-docker
It is already has the functionality to set via env variable what plugins you want to run. A much requested feature for mailu roundcube. 

For rainloop I could not find any official image. But there is a  dockerfile on the rainloop repo we could use as a basis.
https://github.com/RainLoop/rainloop-webmail/tree/master/.docker/php
