### ISSUE TITLE
Collect issues and solutions for propper preserving of client ips

### ISSUE THREAD

**Issue by micw** [Mailu/Mailu#1523]
Mailu works only if the original client IP is known to the services. That means is must be known by mailu-front (behind it, this behaviour is ensured by mailu itself).
For HTTP/s this can easily be achieved by trusting proxy headers. For mail protocols it's way more difficult.

The default case is: ipv4, exposing the mail ports of the "front" container directly (e.g. by using a "port" mapping on docker or by using "hostPort" on kubernetes.

Prone to issues are: ipv6, various cloud providers, reverse proxies. In the result, deployments often end in open relays.

This issue is to collect different situations and solutions for that problem so that we can see how we can address it.

**Comment by micw** [comment]
One possible solution for some cloud providers (Digital Ocean, maybe others?) is described in https://github.com/Mailu/Mailu/issues/1370#issuecomment-612439037

**Comment by ofthesun9** [comment]
on a swarm, I preserve original ip (ipv4) address by using mode: host in the ports definition for the front container:
```
    ports:
      - target: 110
        published: 110
        mode: host
```
As my host is having ipv6 as well, front is also listening on ipv6. I don't think it possible to prevent this.
When an ipv6 machine connects to my server, front see an address translated by the docker_gwbridge network:
> mailu_front.1.z15yyj0xy5ji@coreos-01    | 2020/05/27 14:12:16 [info] 13#13: *36 client 172.19.0.1:59580 connected to 0.0.0.0:25

As a consequence it is very important to check that RELAYNETS defined in mailu.env is **not** encompassing docker_gwbridge (172.19.0.1/24 in my case)

**Comment by Nebukadneza** [comment]
Hi There,

The `Mailu`-Project is currently in a bit of a bind! We are short on man-power, and we need to judge if it is possible for us to put in some work on this issue.

To help with that, we are currently trying to find out which issues are actively keeping users from using `Mailu`, which issues have someone who want to work on them — and which issues may be less important. These a less important ones could be discarded for the time being, until the project is in a more stable and regular state once again.

In order for us to better assess this, it would be helpful if you could put a **reaction on this post** (use the :smiley: icon to the top-right).
- 👍️ if you **need this** to be able to use Mailu. Ideally, you’d also be able to test this on your installation, and provide feedback …
- 🎉 if you find it a **nice bonus**, but no deal-breaker
- 🚀 if you want to **work on it yourself**!
We want to keep this **voting open for 2 weeks** from now, so please help out!

**Comment by Diman0** [comment]
Hi There,

we see this issue had only little attention 😟. As much as it pains us: In order to get the current issues a bit more manageable for us, we decided to close it. 👋👋

We hope that no one feels offended by doing so. Should the issue get really pressing in the future, please feel free to re-open it.

Thank you for your patience and understanding, 🙇
- Your Mailu Team
