### ISSUE TITLE
https://setup.mailu.io/1.7/submit error 500

### ISSUE THREAD

**Issue by kklepper** [Mailu/Mailu#1527]
Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Comment by grimsi** [comment]
Same for https://setup.mailu.io/master/submit so I think their setup server is currently overloaded

**Comment by schniggie** [comment]
Still broken ...

**Comment by Artheriom** [comment]
Yup, broken

**Comment by LuczynskiDar** [comment]
It's still not working, unable to generate docker compose file.

**Comment by Artheriom** [comment]
Still in 500... Is there a workaround (eg. a way to mount a personnal setup website) ? :/

**Comment by muhlemmer** [comment]
Hi guys, sorry for inconvenience. The server disk was full. It is cleaned up now. I'll keep this issue open as a reminder to put an automatic cleanup script.

**Comment by Artheriom** [comment]
Hi !

Works like a charm now, thanks for the fix (and for your amazing work on this project) :D

**Comment by OscarPaz** [comment]
Doesn't work for me now...
Full disk?

**Comment by Nebukadneza** [comment]
See referenced issues, setup unfortunately currently isn’t as stable as it should. Currently working though, so … closing.
