### ISSUE TITLE
clarify and rework reverse proxy documentation

### ISSUE THREAD

**Issue by m121212** [Mailu/Mailu#1528]
Hi all,

the doc here is very vague: https://github.com/Mailu/Mailu/blob/master/docs/reverse.rst
Could you please detail all the steps with a customary NGINX+SSL reverse proxy server (e.g. fresh-install or Docker-Letsencrypt https://github.com/linuxserver/docker-letsencrypt).

Thank you.

Reference here has limitation: Manually copy generated certificates to Mailu
https://github.com/Mailu/Mailu/issues/1459

**Comment by m121212** [comment]
Hi all,
I have a suggestion.
Since mailu has de facto a proxy server (front), you shall move the inclue overrides/*.conf directly in the http section, instead of placing it in the server section. In this way, you will give tremendously higher flexibility in the integration of custom web servers.

**Comment by Nebukadneza** [comment]
Hi There,

The `Mailu`-Project is currently in a bit of a bind! We are short on man-power, and we need to judge if it is possible for us to put in some work on this issue.

To help with that, we are currently trying to find out which issues are actively keeping users from using `Mailu`, which issues have someone who want to work on them — and which issues may be less important. These a less important ones could be discarded for the time being, until the project is in a more stable and regular state once again.

In order for us to better assess this, it would be helpful if you could put a **reaction on this post** (use the :smiley: icon to the top-right).
- 👍️ if you **need this** to be able to use Mailu. Ideally, you’d also be able to test this on your installation, and provide feedback …
- 🎉 if you find it a **nice bonus**, but no deal-breaker
- 🚀 if you want to **work on it yourself**!
We want to keep this **voting open for 2 weeks** from now, so please help out!

**Comment by lub** [comment]
> Could you please detail all the steps with a customary NGINX+SSL reverse proxy server (e.g. fresh-install or Docker-Letsencrypt https://github.com/linuxserver/docker-letsencrypt).

I don't think I understand what exactly you are looking for.

We are providing a completely configured nginx including certificate issuance via Let's Encrypt. When you don't want to use this setup feel free to use your own reverse proxy, but we can't explain how to configure every single proxy out there. Especially as the question seems about generic nginx configuration advise instead of Mailu specific requirements.


But I agree we should rework that document. For example "You can simply disable Mailu reverse proxy by removing the front section from the docker-compose.yml" is not really as simple as it sounds.

**Comment by 3x3cut0r** [comment]
To clarify the reverse proxy documentation ... is it only to access the webfrontend and adminbackend?
What is necessary to do on the reverse proxy / host to recieve mails? which ports need to be forworded and where?
that is unclear to me.

**Comment by SuicideCat** [comment]
Hi everyone! 
Plese can you tell me how to configure this parameter?
REAL_IP_FROM=x.x.x.x,y.y.y.y.y
#x.x.x.x,y.y.y.y.y is the static IP address your reverse proxy uses for connecting to Mailu.

I can`t understand which ip i should use(

**Comment by mmospanenko** [comment]
any ideas how to use external Nginx? https://mailu.io/master/reverse.html#have-mailu-web-frontend-listen-locally doesn't work with compose generated file, need more examples how to work with Docker networks, what ports expose and how, where to manage certs, etc - simple working example will be great

**Comment by geminigeek** [comment]
> Hi everyone! Plese can you tell me how to configure this parameter? REAL_IP_FROM=x.x.x.x,y.y.y.y.y #x.x.x.x,y.y.y.y.y is the static IP address your reverse proxy uses for connecting to Mailu.
> 
> I can`t understand which ip i should use(

hi,

looking for same answer, did you figure it out ?

**Comment by nazar-pc** [comment]
For `REAL_IP_FROM` you'll likely want to use the same as `SUBNET` (because request from the outside will come from gateway Docker creates that'll be in the same subnet). For instance `192.168.203.0/24`.

**Comment by Dr-Ari-Gami** [comment]
I am unable to get the reverse proxy functional. I end up with a 502 Bad Gateway error. I changed the listening ports to 8080 and 8443 in docker-compose.yml. Below is my nginx configuration, modified by lets encrypt, with my domain replaced with `domain.com`

```
server {
    server_name mail.domain.com;

    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_pass https://localhost:8443;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/mail.domain.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/mail.domain.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
    if ($host = mail.domain.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    listen 80;
    server_name mail.gami.app;
    return 404; # managed by Certbot
}
```

Did anyone figure out how to configure nginx as an external reverse proxy?

**Comment by Dr-Ari-Gami** [comment]
I figured it out. I had change the TLS type to mail-letsencrypt

**Comment by Diman0** [comment]
The documentations has been updated on master.
