### ISSUE TITLE
Problem with xapian/pigeonhole/ABI when building on arm

### ISSUE THREAD

**Issue by leolivier** [Mailu/Mailu#1533]
[replaces issue #1531 ]
Hi
I'm building myself the mailu images for raspberry pi (directly on the Pi itself).
I built it last weekend after having pulled the master branch and it recreated the dovecot image from scratch .
No I have the following issue with the xapian plugin in the logs and I canoot connect with imap:
```
imap_1      | Jun 06 18:00:02 imap-login: Info: Login: user=<me@mydomain.tld>, method=PLAIN, rip=192.168.203.2, lip=192.168.203.6, mpid=816, session=<EQ+UJW6nNrjAqMsC>
imap_1      | Jun 06 18:00:02 imap(me@mydomain.tld): Error: Couldn't load required plugin /usr/lib/dovecot/lib21_fts_xapian_plugin.so: Module is for different ABI version 2.3.ABIv10(2.3.10.1) (we have 2.3.ABIv7(2.3.7.2))
```
I found the same kind of issue here: https://github.com/openwrt/packages/issues/5062 linked to pigeonhole usage (which is also installed in the dovecot image) but didn't find the way to apply it to mailu yet.

**Comment by leolivier** [comment]
Weird, I just rebuilt the dovecot image locally to be able to provide logs for this issue and now it works ! 

Looks like the alpine package for dovecot has been updated since my previous build...
The log trace above complained that the xapian package was "_for different ABI version 2.3.ABIv10(2.3.10.1)_" and the dovecot package installed in the trace below is indeed version 2.3.10.1.
Anyway, if I faced it last week, could happen again in the future so we might need to ensure that versions are in sync... I'm not sure the problem is specific to raspberrypi.

Build trace:
```
pi@raspberrypi /hdd/dev/docker/Mailu $ docker-compose -f tests/build.yml  --env-file /docker/mailu/.env build imap
Building imap
Step 1/17 : ARG DISTRO=alpine:3.10
Step 2/17 : FROM $DISTRO as builder
 ---> 97fdd8310375
Step 3/17 : WORKDIR /tmp
 ---> Using cache
 ---> d7a075eed667
Step 4/17 : RUN apk add git build-base automake autoconf libtool dovecot-dev xapian-core-dev icu-dev
 ---> Using cache
 ---> 250b1c21b3b9
Step 5/17 : RUN git clone https://github.com/grosjo/fts-xapian.git   && cd fts-xapian   && git checkout 1.2.7   && autoreconf -vi   && PANDOC=false ./configure --with-dovecot=/usr/lib/dovecot   && make   && make install
 ---> Using cache
 ---> 52d050288b48
Step 6/17 : FROM $DISTRO
 ---> 97fdd8310375
Step 7/17 : RUN apk add --no-cache     python3 py3-pip git bash py3-multidict py3-yarl   && pip3 install --upgrade pip
 ---> Using cache
 ---> 8c8db2f343de
Step 8/17 : RUN pip3 install socrate==0.2.0
 ---> Using cache
 ---> 410b0134eb24
Step 9/17 : RUN pip3 install "podop>0.2.5"
 ---> Using cache
 ---> d146dd9e5bf6
Step 10/17 : RUN apk add --no-cache   dovecot dovecot-lmtpd dovecot-pop3d dovecot-submissiond dovecot-pigeonhole-plugin rspamd-client xapian-core   && mkdir /var/lib/dovecot
 ---> Running in 30f4964b7316
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/main/armv7/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/community/armv7/APKINDEX.tar.gz
(1/23) Installing openssl (1.1.1g-r0)
(2/23) Installing libcap (2.27-r0)
(3/23) Installing libsodium (1.0.18-r0)
(4/23) Installing dovecot (2.3.10.1-r0)
Executing dovecot-2.3.10.1-r0.pre-install
Executing dovecot-2.3.10.1-r0.post-install
Generating a RSA private key
.......................+++++
....+++++
writing new private key to '/etc/ssl/dovecot/server.key'
-----

subject=OU = IMAP server, CN = imap.example.com, emailAddress = postmaster@example.com
SHA1 Fingerprint=E2:42:2D:92:3A:B4:8A:46:11:C8:3C:7D:77:9D:B7:73:95:F9:0D:0E
(5/23) Installing dovecot-lmtpd (2.3.10.1-r0)
(6/23) Installing dovecot-pigeonhole-plugin (2.3.10.1-r0)
(7/23) Installing dovecot-pop3d (2.3.10.1-r0)
(8/23) Installing dovecot-submissiond (2.3.10.1-r0)
(9/23) Installing libevent (2.1.10-r0)
(10/23) Installing libintl (0.19.8.1-r4)
(11/23) Installing libuuid (2.33.2-r0)
(12/23) Installing libblkid (2.33.2-r0)
(13/23) Installing libmount (2.33.2-r0)
(14/23) Installing pcre (8.43-r0)
(15/23) Installing glib (2.60.4-r0)
(16/23) Installing libstdc++ (8.3.0-r0)
(17/23) Installing icu-libs (64.2-r1)
(18/23) Installing luajit (2.1.0_beta3-r4)
(19/23) Installing libmagic (5.37-r1)
(20/23) Installing rspamd (1.9.4-r0)
Executing rspamd-1.9.4-r0.pre-install
(21/23) Installing rspamd-client (1.9.4-r0)
(22/23) Installing libxapian (1.4.11-r0)
(23/23) Installing xapian-core (1.4.11-r0)
Executing busybox-1.30.1-r3.trigger
OK: 130 MiB in 56 packages
Removing intermediate container 30f4964b7316
 ---> e49b59bea1d5
Step 11/17 : COPY --from=builder /usr/lib/dovecot/lib21_fts_xapian_plugin.* /usr/lib/dovecot/
 ---> 32140261b6a6
Step 12/17 : COPY conf /conf
 ---> 826104ca7cb2
Step 13/17 : COPY start.py /start.py
 ---> 8f9d56877fac
Step 14/17 : EXPOSE 110/tcp 143/tcp 993/tcp 4190/tcp 2525/tcp
 ---> Running in aacd0544ff74
Removing intermediate container aacd0544ff74
 ---> cf599569eae5
Step 15/17 : VOLUME ["/mail"]
 ---> Running in 2072f2f2fddd
Removing intermediate container 2072f2f2fddd
 ---> 3c9f7c5fc02a
Step 16/17 : CMD /start.py
 ---> Running in b2821dcaed00
Removing intermediate container b2821dcaed00
 ---> 12c659c7a855
Step 17/17 : HEALTHCHECK --start-period=350s CMD echo QUIT|nc localhost 110|grep "Dovecot ready."
 ---> Running in d45232df34bf
Removing intermediate container d45232df34bf
 ---> 67973d5d57a7
Successfully built 67973d5d57a7
Successfully tagged leolivier/mailu_dovecot:rpi-armv7

```

**Comment by Nebukadneza** [comment]
Hi There,

The `Mailu`-Project is currently in a bit of a bind! We are short on man-power, and we need to judge if it is possible for us to put in some work on this issue.

To help with that, we are currently trying to find out which issues are actively keeping users from using `Mailu`, which issues have someone who want to work on them — and which issues may be less important. These a less important ones could be discarded for the time being, until the project is in a more stable and regular state once again.

In order for us to better assess this, it would be helpful if you could put a **reaction on this post** (use the :smiley: icon to the top-right).
- 👍️ if you **need this** to be able to use Mailu. Ideally, you’d also be able to test this on your installation, and provide feedback …
- 🎉 if you find it a **nice bonus**, but no deal-breaker
- 🚀 if you want to **work on it yourself**!
We want to keep this **voting open for 2 weeks** from now, so please help out!

**Comment by leolivier** [comment]
Hi @Nebukadneza
Actually, this is now working.
Probably not that urgent, only a nice to have for guys who are building their own images on exotic platforms...

**Comment by Diman0** [comment]
Using QEMU it is also possible to build on a normal x86_64 computer and push the images to your RPI.
This is already documented on master. You might not have seen this yet for this reason:
https://mailu.io/master/rpi_build.html

I don't understand why you had the initial error. Maybe it was a bug that got fixed in the newer version that you got when retrying building the image a week later?

**Comment by leolivier** [comment]
The issue reappeared this week, I get this message in my dovecot logs:
`Oct 17 09:06:52 lmtp(2271): Fatal: Couldn't load required plugin /usr/lib/dovecot/lib21_fts_xapian_plugin.so: Module is for different ABI version 2.3.ABIv11(2.3.11.3) (we have 2.3.ABIv10(2.3.10.1))
`

The version has changed since the original issue but it seems that packages are not synced properly on alpine...

**Comment by leolivier** [comment]
I finally had to rebuild the dovecot image with alpine:3.11 instead of 3.12 (although it worked previously with 3.12) and it's working again...

**Comment by leolivier** [comment]
I removed the 3.12 alpine image to be sure not using cached images and rebuilt the dovecot image and it works!
So my guess (but I didn't find any evidence yet) is that when you rebuild the image from intermediate cached images, some packages are updated but not all of them, leading to inconsistencies in the image...

**Comment by leolivier** [comment]
Having no time to look further i this issue, I'm trying to bypass it by forcing  the --no-cache & --force-rm options when building dovecot. As the issue appears very randomly, I can't tell if it's working or not. 
I'll tell if the problem happens again using this fix.
