### ISSUE TITLE
Setting up a local Mailu and a remote Mailu as a relayhost

### ISSUE THREAD

**Issue by adamcavendish** [Mailu/Mailu#1534]
Hi, because of SMTP authentication requirements, usually a user cannot use a dynamic IP address to send out emails which therefore relayhost might be needed for that.
I've been trying to setup a local Mailu with full features and a remote Mailu as a relayhost. Ideally, it should only include postfix only on the remote server that accept the same smtp authentications as the local one. Is there anyone that has some clues about how to do it?

**Comment by ofthesun9** [comment]
Mailu is a complete stack, you won't be able to deploy a remote Mailu with only postfix.
However you can set up your "local mailu" to use external relayhost providers (whose IP will have a good reputation). See #958 and #387
