### ISSUE TITLE
Error starting resolver /dev/stdout: Permission denied

### ISSUE THREAD

**Issue by jwaes** [Mailu/Mailu#1536]
I have problem starting the unbound resolver.

```
[1591714689] unbound.conf[1:0] info: service stopped (unbound 1.9.1).
[1591714689] unbound.conf[1:0] info: server stats for thread 0: 882 queries, 0 answers from cache, 882 recursions, 0 prefetch, 0 rejected by ip ratelimiting
[1591714689] unbound.conf[1:0] info: server stats for thread 0: requestlist max 27 avg 17.9694 exceeded 0 jostled 0
[1591714689] unbound.conf[1:0] info: average recursion processing time 83.452849 sec
[1591714689] unbound.conf[1:0] info: histogram of recursion processing times
[1591714689] unbound.conf[1:0] info: [25%]=29.3813 median[50%]=62.7606 [75%]=154.587
[1591714689] unbound.conf[1:0] info: lower(secs) upper(secs) recursions
[1591714689] unbound.conf[1:0] info:    0.131072    0.262144 1
[1591714689] unbound.conf[1:0] info:    0.262144    0.524288 2
[1591714689] unbound.conf[1:0] info:    0.524288    1.000000 1
[1591714689] unbound.conf[1:0] info:    1.000000    2.000000 2
[1591714689] unbound.conf[1:0] info:    2.000000    4.000000 2
[1591714689] unbound.conf[1:0] info:    4.000000    8.000000 8
[1591714689] unbound.conf[1:0] info:    8.000000   16.000000 27
[1591714689] unbound.conf[1:0] info:   16.000000   32.000000 139
[1591714689] unbound.conf[1:0] info:   32.000000   64.000000 142
[1591714689] unbound.conf[1:0] info:   64.000000  128.000000 112
[1591714689] unbound.conf[1:0] info:  128.000000  256.000000 201
[1591715050] unbound.conf[1:0] error: Could not open logfile /dev/stdout: Permission denied
[1591715050] unbound.conf[1:0] notice: init module 0: validator
[1591715050] unbound.conf[1:0] notice: init module 1: iterator
[1591715050] unbound.conf[1:0] info: start of service (unbound 1.9.1).
```

I start using
`sudo docker-compose up`

Anyone else has this problem ?

I found a post with a hint to a solution, is this applicable here ?

https://serverfault.com/questions/599103/make-a-docker-application-write-to-stdout

**Comment by ofthesun9** [comment]
Hello,

You can ignore this error message. The resolver image is working ok ;-)
If you find a way to "fix" it, we will welcome a PR ;-)

**Comment by jwaes** [comment]
Hmm so this error is not related ?? it stays on status 'starting'

```
antivirus_1  | Wed Jun 10 09:31:22 2020 -> ^dn_expand failed
antivirus_1  | Wed Jun 10 09:31:22 2020 -> ^Invalid DNS reply. Falling back to HTTP mode.
antivirus_1  | Wed Jun 10 09:31:27 2020 -> ^Can't get information about database.clamav.net: Try again
antivirus_1  | Wed Jun 10 09:31:27 2020 -> ^Can't download main.cvd from database.clamav.net
antivirus_1  | Wed Jun 10 09:31:27 2020 -> Trying again in 5 secs...
antivirus_1  | Wed Jun 10 09:31:37 2020 -> ^dn_expand failed
antivirus_1  | Wed Jun 10 09:31:37 2020 -> ^Invalid DNS reply. Falling back to HTTP mode.
antivirus_1  | Wed Jun 10 09:31:42 2020 -> ^Can't get information about database.clamav.net: Try again
antivirus_1  | Wed Jun 10 09:31:42 2020 -> ^Can't download main.cvd from database.clamav.net
antivirus_1  | Wed Jun 10 09:31:42 2020 -> Trying again in 5 secs...
antivirus_1  | Wed Jun 10 09:31:52 2020 -> ^dn_expand failed
antivirus_1  | Wed Jun 10 09:31:52 2020 -> ^Invalid DNS reply. Falling back to HTTP mode.
antivirus_1  | Wed Jun 10 09:31:57 2020 -> !Can't get information about database.clamav.net: Try again
antivirus_1  | Wed Jun 10 09:31:57 2020 -> !Can't download main.cvd from database.clamav.net
antivirus_1  | Wed Jun 10 09:31:57 2020 -> Giving up on database.clamav.net...
antivirus_1  | Wed Jun 10 09:31:57 2020 -> Update failed. Your network may be down or none of the mirrors listed in /etc/clamav/freshclam.conf is working. Check https://www.clamav.net/documents/official-mirror-faq for possible reasons.
antivirus_1  | WARNING: Ignoring deprecated option DetectBrokenExecutables at /etc/clamav/clamd.conf:30
antivirus_1  | LibClamAV Error: cli_loaddbdir(): No supported database files found in /data
antivirus_1  | Wed Jun 10 09:31:57 2020 -> !Can't open file or directory
```

The strange thing is that when i open a console in this antivirus_1 the dns is not set.
```
bash-5.0# cat /etc/resolv.conf 
nameserver 127.0.0.11
options ndots:0
```

While in the docker-compose i have it defined:

```
  antivirus:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}clamav:${MAILU_VERSION:-1.7}
    restart: always
    env_file: mailu.env
    volumes:
      - "/mailu/filter:/data"
    depends_on:
      - resolver
    dns:
      - 192.168.203.254
```

**Comment by ofthesun9** [comment]
I am pretty sure your unbound service is Ok.
Did you try to restart the antivirus service ?

**Comment by Nebukadneza** [comment]
Hi There,

The `Mailu`-Project is currently in a bit of a bind! We are short on man-power, and we need to judge if it is possible for us to put in some work on this issue.

To help with that, we are currently trying to find out which issues are actively keeping users from using `Mailu`, which issues have someone who want to work on them — and which issues may be less important. These a less important ones could be discarded for the time being, until the project is in a more stable and regular state once again.

In order for us to better assess this, it would be helpful if you could put a **reaction on this post** (use the :smiley: icon to the top-right).
- 👍️ if you **need this** to be able to use Mailu. Ideally, you’d also be able to test this on your installation, and provide feedback …
- 🎉 if you find it a **nice bonus**, but no deal-breaker
- 🚀 if you want to **work on it yourself**!
We want to keep this **voting open for 2 weeks** from now, so please help out!

**Comment by toastboy70** [comment]
I found this because I wanted to add "log-queries: true" and found I couldn't see the log entries.

I've submitted a pull request to fix this: https://github.com/Mailu/Mailu/pull/1623

**Comment by psrcek** [comment]
Is there any hope of this working??? my mail server is currently dead because of this bug

**Comment by pirate** [comment]
I'm hitting this bug in v2.0, both smtp (postfix) and resolver are failing to start because `/dev/stdout` is not writable. Made me lose ~6 days of email :/

**Comment by nextgens** [comment]
@pirate you are not making any sense. This specific bug was fixed and the current [config file](https://github.com/Mailu/Mailu/blob/master/optional/unbound/unbound.conf) does not contain ``logfile: /dev/stdout`` anymore.

What you are encountering is likely a different bug... but since you do not provide us with any detail we will never know.

Here ``/dev/stdout`` is writable; find out why yours is not and then open a ticket.

**Comment by pirate** [comment]
I already opened a separate issue for my problem @nextgens: https://github.com/Mailu/Mailu/issues/3271

I was just commenting here to bump this thread in case @jwaes ever figured out the underlying reason why `/dev/stdout` randomly became unwritable.
