### ISSUE TITLE
Open Relay / 502 Bad Gateway

### ISSUE THREAD

**Issue by TyphoonSB** [Mailu/Mailu#1539]
Hi,

I will try to describe my problem .....

Basics:
Server running with CentOS 8, public IPv4, public IPv6, Docker version 19.03.11, build 42e35e61f3

I have installed a MailU setup using the config tool on https://setup.mailu.io/1.7/

fine so far....

After starting the containers .... I got a 502 Bad Gateway error on the Admin and Webmail IF.

I found out that when I activate masquerading (_firewall-cmd --zone=public --add-masquerade --permanent_) it works. Admin, Webmail, etc. are working, also sending and recieving Mails is working fine.
But now it looks like that all Mails are comming from the internal Docker IP range, and the Server works as an "Open Relay".

Has anybody an idea to solv that problem?

Thanks

**Comment by ofthesun9** [comment]
Hello,
I would recommend to you start disabling ipv6 (in your front section, comment out all ipv6 stuff in the port section)
Are you using any other reverse proxy on your server ? or only the one provided by mailu ?

**Comment by Nebukadneza** [comment]
Hi There,

The `Mailu`-Project is currently in a bit of a bind! We are short on man-power, and we need to judge if it is possible for us to put in some work on this issue.

To help with that, we are currently trying to find out which issues are actively keeping users from using `Mailu`, which issues have someone who want to work on them — and which issues may be less important. These a less important ones could be discarded for the time being, until the project is in a more stable and regular state once again.

In order for us to better assess this, it would be helpful if you could put a **reaction on this post** (use the :smiley: icon to the top-right).
- 👍️ if you **need this** to be able to use Mailu. Ideally, you’d also be able to test this on your installation, and provide feedback …
- 🎉 if you find it a **nice bonus**, but no deal-breaker
- 🚀 if you want to **work on it yourself**!
We want to keep this **voting open for 2 weeks** from now, so please help out!

**Comment by Xat59** [comment]
@TyphoonSB do you still have this issue ? I had this problem some weeks ago on Fedora 32.

Since I personally switched from docker-ce to moby-engine, my issue disappeared .
Hope it'll help 👍
