### ISSUE TITLE
Forwarding via admin entry

### ISSUE THREAD

**Issue by wollo** [Mailu/Mailu#154]
I get this error in the logs, when a user adds an forwarding adress into the admin page
smtp_1       | postfix/lmtp[44]: 1E2949A: to=<xxxt@my_domain.de>, relay=imap[192.168.144.6]:2525, delay=0.34, delays=0.26/0.01/0.01/0.06, dsn=4.2.0, status=deferred (host imap[192.168.144.6] said: 451 4.2.0 <xxx@my_domain.de> Execution of Sieve filters was aborted due to temporary failure (in reply to end of DATA command))

Any idea, how to debug/overcome this.
Itried different forwarding adresses, but the error persists

**Comment by kaiyou** [comment]
Sorry for the delay. Could you have a look at ``imap`` logs at the time of the error, there must be some issue with our Sieve filter.

**Comment by wollo** [comment]
Seems to be fixed in latest
Thank you
