### ISSUE TITLE
DSN missing

### ISSUE THREAD

**Issue by Al2Klimov** [Mailu/Mailu#1545]
While sending a test email to myself via Thunderbird I requested a DSN.

I instantly got the mail into my inbox, but no DSN.

**Comment by ofthesun9** [comment]
Hello,
I did a check on master and thunderbird 68.8 and it is working. I find this in smtp logs:

> mailu_smtp.1.exzm4rpqlh9y@rpi4-01    | Jun 23 18:39:58 mail postfix/bounce[1011]: CE10A250DD: sender delivery status notification: 438B4250F1

Can you share your smtp logs ?

**Comment by Al2Klimov** [comment]
```
Jun 23 18:48:56 smtp postfix/smtpd[1123]: connect from mailu-front.docker-services_mailu[192.168.234.67]
Jun 23 18:48:56 smtp postfix/smtpd[1123]: 5EC6EBC52C: client=unknown[46.128.138.177], sasl_method=XCLIENT, sasl_username=aklimov@al2klimov.de
Jun 23 18:48:56 smtp postfix/cleanup[1126]: 5EC6EBC52C: replace: header Received: from Alexanders-MacBook-Pro.local (unknown [46.128.138.177])??by smtp.al2klimov.de (Postfix) with ESMTPA id 5EC6EBC52C??for <grandmaster@al2klimov.de>; Tue, 23 Jun 2020 18:48:56 +0000 (UTC) from unknown[46.128.138.177]; from=<grandmaster@al2klimov.de> to=<grandmaster@al2klimov.de> proto=ESMTP helo=<Alexanders-MacBook-Pro.local>: Received: from authenticated-user (PRIMARY_HOSTNAME [PUBLIC_IP])??by smtp.al2klimov.de (Postfix) with ESMTPA id 5EC6EBC52C??for <grandmaster@al2klimov.de>; Tue, 23 Jun 2020 18:48:56 +0000 (UTC)
Jun 23 18:48:56 smtp postfix/cleanup[1126]: 5EC6EBC52C: message-id=<d1c40b0d-ccc6-6f04-d107-fd53dc0764f8@al2klimov.de>
Jun 23 18:48:56 smtp postfix/qmgr[175]: 5EC6EBC52C: from=<grandmaster@al2klimov.de>, size=599, nrcpt=1 (queue active)
Jun 23 18:48:56 smtp postfix/smtpd[1123]: disconnect from unknown[46.128.138.177] ehlo=2 xclient=0/1 mail=1 rcpt=1 data=1 quit=1 commands=6/7
Jun 23 18:48:56 smtp postfix/lmtp[1127]: 5EC6EBC52C: to=<aklimov@al2klimov.de>, orig_to=<grandmaster@al2klimov.de>, relay=192.168.234.69[192.168.234.69]:2525, delay=0.55, delays=0.3/0.05/0.02/0.18, dsn=2.0.0, status=sent (250 2.0.0 <aklimov@al2klimov.de> 41TgIphO8l5NBAAAA4uONA Saved)
Jun 23 18:48:56 smtp postfix/qmgr[175]: 5EC6EBC52C: removed
```

**Comment by ofthesun9** [comment]
Thanks, It seems that it is not working when the recipient is an alias.

**Comment by Al2Klimov** [comment]
Just sent a DSN test directly to `aklimov@al2klimov.de`. Doesn't work either.

**Comment by ofthesun9** [comment]
I tried again on my setup, and DSN is working, even when the recipient is an alias.
I tried also on test.mailu.io, using roundcube, and this is ok also.
I don't have a clue what could be the issue, unfortunately...

**Comment by Al2Klimov** [comment]
And when you send it to yourself w/ an alias in both From: and To:?

**Comment by Al2Klimov** [comment]
... like me?

**Comment by Nebukadneza** [comment]
Hi There,

The `Mailu`-Project is currently in a bit of a bind! We are short on man-power, and we need to judge if it is possible for us to put in some work on this issue.

To help with that, we are currently trying to find out which issues are actively keeping users from using `Mailu`, which issues have someone who want to work on them — and which issues may be less important. These a less important ones could be discarded for the time being, until the project is in a more stable and regular state once again.

In order for us to better assess this, it would be helpful if you could put a **reaction on this post** (use the :smiley: icon to the top-right).
- 👍️ if you **need this** to be able to use Mailu. Ideally, you’d also be able to test this on your installation, and provide feedback …
- 🎉 if you find it a **nice bonus**, but no deal-breaker
- 🚀 if you want to **work on it yourself**!
We want to keep this **voting open for 2 weeks** from now, so please help out!

**Comment by Al2Klimov** [comment]
> * you’d also be able to test this on your installation, and provide feedback

Yes, I would!

**Comment by Al2Klimov** [comment]
C'mon. I've even agreed to test fixes in my production and you're going to close this?

**Comment by Diman0** [comment]
Using thunderbird It works when you do not send the email to yourself. When you use an alias it is still treated as if you send it to yourself. In the header of the email I can also see the DSN header. Do you also see the DSN header in the received email?
I think it is a feature of thunderbird it doesn't ask you to send a DSN to yourself.

**Comment by Al2Klimov** [comment]
Tried to send across mail servers with Roundcube.

> Do you also see the DSN header in the received email?

Nope.

**Comment by Al2Klimov** [comment]
C'mon. I've already told you:

> C'mon. I've even agreed to test fixes in my production and you're going to close this?

**Comment by Al2Klimov** [comment]
C'mon. I've already told you:

> C'mon. I've even agreed to test fixes in my production and you're going to close this?

**Comment by Diman0** [comment]
We have switched the mail proxy from nginx to dovecot proxy.
I cannot  replicate the issue anymore. When sending from a Mailu server to another mailu server it works now. This also applies when the recipient email address is an alias.
