### ISSUE TITLE
Benchmark for mailu server

### ISSUE THREAD

**Issue by Kushang-egnaroinc** [Mailu/Mailu#1547]
Thanks for giving such a beautiful product.
Mailu has very good documentation but I could not find its benchmark figures mentioned.
I would like to know the mailu server benchmark in terms of,
Number of the user-user account,
Number of parallel mails processing capacity,
The number of mail client access in parallel.
I would like to know its benchmark for different machines like 2 core, 4 core, 8 core with different RAM.
If any data related to this exist, please let us know.

**Comment by Nebukadneza** [comment]
Hi There,

The `Mailu`-Project is currently in a bit of a bind! We are short on man-power, and we need to judge if it is possible for us to put in some work on this issue.

To help with that, we are currently trying to find out which issues are actively keeping users from using `Mailu`, which issues have someone who want to work on them — and which issues may be less important. These a less important ones could be discarded for the time being, until the project is in a more stable and regular state once again.

In order for us to better assess this, it would be helpful if you could put a **reaction on this post** (use the :smiley: icon to the top-right).
- 👍️ if you **need this** to be able to use Mailu. Ideally, you’d also be able to test this on your installation, and provide feedback …
- 🎉 if you find it a **nice bonus**, but no deal-breaker
- 🚀 if you want to **work on it yourself**!
We want to keep this **voting open for 2 weeks** from now, so please help out!

**Comment by Diman0** [comment]
Hello @Kushang-egnaroinc  we have no such benchmark data available. It is unlikely that we have such data available in the future. Unless someone decides to benchmark mailu by himself and send a PR to add this to the documentation.
