### ISSUE TITLE
POP3 USER Invalid Command

### ISSUE THREAD

**Issue by willkruss** [Mailu/Mailu#1550]
Hi All,

Is there an issue with POP3 auth on port 110 without using TLS?

When using TLS on port 995 logins work fine. However, when using port 110 without SSL the normal 'USER xxxx' fails with
-ERR invalid command

Unfortunately we need to enable unencrypted auth for POP3 on port 110 for a specific purpose.

Any pointer as to how to enable this (assuming it's been disabled for security reasons)?

Thanks,
Will

**Comment by ofthesun9** [comment]
Hello,
We wouldn't recommend this for security reason ;-)
I think you will need to provide your own modified [nginx.conf](https://github.com/Mailu/Mailu/blob/master/core/nginx/conf/nginx.conf) (to be mounted on  /conf/nginx.conf on front service) and modify the starttls section [here](https://github.com/Mailu/Mailu/blob/master/core/nginx/conf/nginx.conf#L245-L247).
I don't know if it will be enough though....

**Comment by willkruss** [comment]
Thanks, we did exactly that to get around it. I agree, we recommended the client not to do this, but they were stuck with some legacy application that doesn't support TLS for a project at this time.

**Comment by Nebukadneza** [comment]
Hi There,

The `Mailu`-Project is currently in a bit of a bind! We are short on man-power, and we need to judge if it is possible for us to put in some work on this issue.

To help with that, we are currently trying to find out which issues are actively keeping users from using `Mailu`, which issues have someone who want to work on them — and which issues may be less important. These a less important ones could be discarded for the time being, until the project is in a more stable and regular state once again.

In order for us to better assess this, it would be helpful if you could put a **reaction on this post** (use the :smiley: icon to the top-right).
- 👍️ if you **need this** to be able to use Mailu. Ideally, you’d also be able to test this on your installation, and provide feedback …
- 🎉 if you find it a **nice bonus**, but no deal-breaker
- 🚀 if you want to **work on it yourself**!
We want to keep this **voting open for 2 weeks** from now, so please help out!

**Comment by Diman0** [comment]
Hi There,

we see this issue had only little attention 😟. As much as it pains us: In order to get the current issues a bit more manageable for us, we decided to close it. 👋👋

We hope that no one feels offended by doing so. Should the issue get really pressing in the future, please feel free to re-open it.

Thank you for your patience and understanding, 🙇
- Your Mailu Team
