### ISSUE TITLE
Is it possible to change the name of the Junk folder?

### ISSUE THREAD

**Issue by unikitty37** [Mailu/Mailu#1552]
In https://github.com/Mailu/Mailu/pull/1470, it states that Mailu will learn messages as spam if they are moved to the `Junk` folder, and learn them as ham if they are moved out of it.

However, I do not call the folder `Junk` — I call it `@Spam`, as I don't like having a system folder appearing in the middle of the folder list. Is there a way to tell Mailu to use this folder instead?

**Comment by ofthesun9** [comment]
Hello,
Unfortunately, Mailu is not supporting  to define the name of the "Junk" mailbox:
"Junk" is hardcoded in (at least)
https://github.com/Mailu/Mailu/blob/master/core/admin/mailu/internal/templates/default.sieve
https://github.com/Mailu/Mailu/blob/master/core/dovecot/conf/dovecot.conf

**Comment by unikitty37** [comment]
Thanks — looks like turning off the spam filter in the user configuration allows me to use my own rule based on the header, at least. (And, as a bonus, I've now learned how to do numeric comparisons in sieve 👍 )

The `dovecot.conf` appears to be what keeps recreating the folder no matter how many times I delete it. Putting a changed version in the overrides folder should fix that, yes?

**Comment by unikitty37** [comment]
Rats — the override doesn't *replace* `dovecot.conf` — it merely gets included at the end, so the bogus folder still gets created.

Looks like those are the only places the folder names are hardcoded, though. Just working on a PR now to allow them to be configured.

**Comment by Nebukadneza** [comment]
(*Edit: I know we discussed a lot in the PR already, but as the complexity vs. use is still a bit debatable, I’d like to copypaste our call-for-vote also in this issue …)

Hi There,

The `Mailu`-Project is currently in a bit of a bind! We are short on man-power, and we need to judge if it is possible for us to put in some work on this issue.

To help with that, we are currently trying to find out which issues are actively keeping users from using `Mailu`, which issues have someone who want to work on them — and which issues may be less important. These a less important ones could be discarded for the time being, until the project is in a more stable and regular state once again.

In order for us to better assess this, it would be helpful if you could put a **reaction on this post** (use the :smiley: icon to the top-right).
- 👍️ if you **need this** to be able to use Mailu. Ideally, you’d also be able to test this on your installation, and provide feedback …
- 🎉 if you find it a **nice bonus**, but no deal-breaker
- 🚀 if you want to **work on it yourself**!
We want to keep this **voting open for 2 weeks** from now, so please help out!

**Comment by unikitty37** [comment]
I understand the reasons for putting the vote in here, but I'm not sure about the comment re the complexity side of things — the code doesn't seem particularly complex, and the end-user can continue using Mailu as normal without doing anything unless they actually want to change the defaults. If anything, the workarounds suggested in the PR are more complex for the end user, and don't work as well.

Getting bors to actually confirm the code's OK seems to be the most complex part 😁

**Comment by unikitty37** [comment]
Still trying to get the tests to actually *run*, but bors is the blocker here, and I can’t trigger new runs myself 😞

**Comment by nextgens** [comment]
IMHO the right fix here is to use https://wiki.dovecot.org/Plugins/MailboxAlias and an override. If you wanted to submit a PR documenting how to set it up that would be great

**Comment by unikitty37** [comment]
> This doesn't magically solve the problem of showing clients e.g. multiple Sent mailboxes, but it can be used to make sure that all of the different variants will have the same mails in them.

Unless hiding the `Junk` folder is covered by the override you speak of (in which case, could you give a few more details, please, because I don't understand what you mean there) then this isn't really a fix.

The object isn't just to have the spam go to `@Spam`, it's to _not_ have the `Junk` folder cluttering up the alphabetically-sorted list of real folders. I can already set the default spam folder to be `@Spam` — but `Junk` still gets created, and gets re-created if I delete it manually. The object of #1555 was to allow the `@Spam` folder to be used _without_ creating a superfluous `Junk` folder.

**Comment by unikitty37** [comment]
*Please* could somebody come up with a workaround for this — or allow the *user* to choose what the Junk folder should be called, rather than the Mailu developers?

Mailu has now decided to start ignoring my rule to put items marked as spam in the correct `@Spam` folder and is now filing them in its own unwanted Junk folder again. This is breaking all my smart mailboxes. I do *not* want to have the folder called Junk, because it appears in the middle of an alphabetical list of folders — that's why I use a name starting with `@`.

I submitted a PR (#1555) ages ago which would have respected user choices, but it never went anywhere (and I never could get the CI to finish building it…)

@nextgens You mentioned using MailboxAlias and an override — could you please expand on how to actually do this, because I can't see how to get overrides to prevent Mailu from creating this wretched folder in the first place?

**Comment by nextgens** [comment]
> _Please_ could somebody come up with a workaround for this — or allow the _user_ to choose what the Junk folder should be called, rather than the Mailu developers?
> 

The RFC says what the folder SHOULD be called and we are following the RFC.
https://datatracker.ietf.org/doc/html/rfc9051#section-7.3.1

> Mailu has now decided to start ignoring my rule to put items marked as spam in the correct `@Spam` folder and is now filing them in its own unwanted Junk folder again.

I am not aware of any recent change to the dovecot configuration on Mailu's side... what exactly are you referring to?
https://github.com/Mailu/Mailu/commits/master/core/dovecot/conf/dovecot.conf

[...]

> @nextgens You mentioned using MailboxAlias and an override — could you please expand on how to actually do this, because I can't see how to get overrides to prevent Mailu from creating this wretched folder in the first place?

The idea is to:
1) Let Mailu create the Junk folder
2) alias it using MailboxAlias, as described in https://doc.dovecot.org/settings/plugin/mailbox-alias-plugin/
3) create a different namespace where `@Spam` would be subscribed to... but `Junk` wouldn't

**Comment by unikitty37** [comment]
Thanks — I think the problem with Mailu changing the spam processing rules is actually down configuration on my end. If a message has `X-Spam-Status: yes` in the headers, it's moved to `@Spam` by an explicit filter I set, but if it doesn't but still trips the spam filter set in the account config, Mailu moves it to the default spam folder, which is Junk.

I had a disk failure on the disk containing the VM I was running mailu in, and the account config was one bit that wasn't backed up properly; I'd forgotten I'd disabled the built-in spam filter previously.

As to the folder name itself, I can't actually find anything in the RFC that states the name SHOULD be the same as the flag — just a couple of examples where that's the case — though I'm sure you've spent more time reading it than I have :)

Even so, SHOULD != MUST, so I still think allowing users to choose would be best.

I'm not sure how namespaces interact with either of the clients I'm using, as their docs don't really mention them, so I found another way to change the default:

I added this script as /mailu/imap_startup.sh:

```sh
#!/usr/bin/env bash

# BusyBox default sed lacks extended regexp support
apk update
apk add sed

/bin/sed -i -Ee '/for mailbox in.*"Junk"/s/(, )?"Junk"//' /conf/dovecot.conf
/bin/sed -i -e '/for mailbox in/i \\n  mailbox @Spam {\n    auto = subscribe\n    special_use = \\Junk\n  }' /conf/dovecot.conf
/bin/sed -i -Ee 's/(imapsieve_mailbox.*) = Junk/\1 = @Spam/' /conf/dovecot.conf
/bin/sed -i -e 's/ Junk/ @Spam/' /etc/dovecot/conf.d/15-mailboxes.conf /etc/dovecot/dovecot.conf

/start.py
```

then changed the `imap` container in docker-compose.yml, adding the extra mountpoint and changing the default startup command:

```yaml
  imap:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}dovecot:${MAILU_VERSION:-1.9}
    restart: always
    env_file: mailu.env
    volumes:
      - "/mailu/mail:/mail"
      - "/mailu/overrides/dovecot:/overrides:ro"
      - "/mailu/imap_startup.sh:/imap_startup.sh:ro"
    depends_on:
      - front
      - resolver
    dns:
      - 192.168.203.254
    command: ["/bin/sh", "-c", "/imap_startup.sh"]
```

and the `@Spam` folder is now auto-created and used for spam, the `Junk` folder is not created at all, and there's no need to reconfigure clients (which means I can put the entire thing into my Ansible playbook and not have to worry if I ever need to recreate the setup).

Thanks for your help — I'll mark this as closed (though if the dovecot image could include GNU sed rather than the standard busybox one, it would save a bit of time on each container restart. Not sure if that would add bloat to the image, though :)

**Comment by unikitty37** [comment]
…actually, that still doesn't work, as the `Junk` folder still gets created at some point, and messages put into it, even though others get caught by the Sieve rule and put correctly into `@Spam`.

Is this something I can resolve by turning the spam filter off in the settings? I'm guessing that's what's doing it, as there doesn't seem to be anything else that could — but it's rather difficult to test without getting myself on a load of spam lists :)
