### ISSUE TITLE
Cannot connect to Rspamd webui

### ISSUE THREAD

**Issue by richardbeumer** [Mailu/Mailu#1554]
Hello,

I set up Mailu on a self hosted kubernetes cluster using your documentation. Everything is working ok except for the Rspamd Webui. When I hit the Anti-spam button from the admin panel I get a new tab pointing to /admin/antispam but after that I get a password popup.

I'm using nginx as ingress and my security-ingress.yaml looks like this:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mailu-antispam-ingress
  namespace: mailu-mailserver
  annotations:
    #kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/auth-url: http://admin.mailu-mailserver.svc.cluster.local/internal/auth/admin
    nginx.ingress.kubernetes.io/auth-snippet: |
      proxy_set_header X-Real-IP "";
      proxy_set_header X-Forwarded-For "";
  labels:
    app: mailu
    role: mail
    tier: frontend
```

my security log is showing:

```
2020-06-26 19:20:58 #8(controller) <55e8c1>; csession; rspamd_controller_check_password: absent password has been specified
```

my admin log is showing:

```
192.168.3.14 - - [26/Jun/2020:19:20:58 +0000] "GET /internal/auth/admin HTTP/1.1" 200 0 "https://mail.rchrd.be/admin/antispam/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36"
```

I don't know what I configured wrong or isn't working right. Please help?!

**Comment by Nebukadneza** [comment]
Hi There,

The `Mailu`-Project is currently in a bit of a bind! We are short on man-power, and we need to judge if it is possible for us to put in some work on this issue.

To help with that, we are currently trying to find out which issues are actively keeping users from using `Mailu`, which issues have someone who want to work on them — and which issues may be less important. These a less important ones could be discarded for the time being, until the project is in a more stable and regular state once again.

In order for us to better assess this, it would be helpful if you could put a **reaction on this post** (use the :smiley: icon to the top-right).
- 👍️ if you **need this** to be able to use Mailu. Ideally, you’d also be able to test this on your installation, and provide feedback …
- 🎉 if you find it a **nice bonus**, but no deal-breaker
- 🚀 if you want to **work on it yourself**!
We want to keep this **voting open for 2 weeks** from now, so please help out!

**Comment by liquidat** [comment]
@richardbeumer Can you please check the value of `/etc/rspamd/local.d/worker-controller.inc`? Check if the entry for `secure_ip` does include the IP address of your ingress controller.

**Comment by richardbeumer** [comment]
@liquidat my ingress is in a different subnet. After adding this subnet to my Configmap (POD_ADDRESS_RANGE:) and restarted some pods I can access the UI.

Problem solved.
