### ISSUE TITLE
Mailu-front is stuck in CrashLoopBackOff

### ISSUE THREAD

**Issue by RikiReal** [Mailu/Mailu#1556]
Hello!

I am trying to deploy Mailu using the helm charts. However, I have come to a dead end. The mail-front pod is stuck in a crash loop with the following error message:

```
$ kubectl logs mailu-front-7989f9468b-ctxdt
nginx: [emerg] cannot load certificate "/certs/cert.pem": PEM_read_bio_X509_AUX() failed (SSL: error:0909006C:PEM routines:get_name:no start line:Expecting: TRUSTED CERTIFICATE)
```
When I check cert-manager with `kubectl describe certificate` and `kubectl describe certificaterequest`, the only event is `Created new CertificateRequest resource "mailu-certificates-3877016192"`.

I know the cert-manager works. Before I tried deploying Mailu I issued a certificate with letsencrypt as my ACME. It reported "certificated issued successfully". 

Any help is much appreciated. 

### System

- Cloud provider: bare-metal VPS (contabo)
- OS: Centos 8
- host (uname -a): Linux masternode 4.18.0-147.8.1.el8_1.x86_64 #1 SMP Thu Apr 9 13:49:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- kubernetes: 1.18
- mailu helm install: 1.8
- runtime: cri-o 1.18.1
- cert-manager: v0.15.1

**Comment by RikiReal** [comment]
Because I am using a bare-metal cluster I cannot use the helm files to deploy mailu as they are not configured for my environment. The proper way is to use the original manifest files and configure them to suit my needs. 

I'm closing this now.

**Comment by caesarcxiv** [comment]
same issue using helm chart
