### ISSUE TITLE
Make smtp_tls_policy_maps easily configurable

### ISSUE THREAD

**Issue by Snakesms** [Mailu/Mailu#1558]
Hi Team,

It will be great to have following options configurable from mailu.env as they are required in many cases
when SMTP RELAY from an ISP is in use:
smtp_tls_security_level
smtp_tls_wrappermode
(PR is following)

**Comment by Nebukadneza** [comment]
Hi There,

The `Mailu`-Project is currently in a bit of a bind! We are short on man-power, and we need to judge if it is possible for us to put in some work on this issue.

To help with that, we are currently trying to find out which issues are actively keeping users from using `Mailu`, which issues have someone who want to work on them — and which issues may be less important. These a less important ones could be discarded for the time being, until the project is in a more stable and regular state once again.

In order for us to better assess this, it would be helpful if you could put a **reaction on this post** (use the :smiley: icon to the top-right).
- 👍️ if you **need this** to be able to use Mailu. Ideally, you’d also be able to test this on your installation, and provide feedback …
- 🎉 if you find it a **nice bonus**, but no deal-breaker
- 🚀 if you want to **work on it yourself**!
We want to keep this **voting open for 2 weeks** from now, so please help out!

**Comment by Snakesms** [comment]
It's already done and PR is pending to be approved and merged

**Comment by Snakesms** [comment]
What recent activity is expected here? PR just pending to be reviewed and hopefully merged

**Comment by Snakesms** [comment]
> Hi There,
> 
> The `Mailu`-Project is currently in a bit of a bind! We are short on man-power, and we need to judge if it is possible for us to put in some work on this issue.
> 
> To help with that, we are currently trying to find out which issues are actively keeping users from using `Mailu`, which issues have someone who want to work on them — and which issues may be less important. These a less important ones could be discarded for the time being, until the project is in a more stable and regular state once again.
> 
> In order for us to better assess this, it would be helpful if you could put a **reaction on this post** (use the 😃 icon to the top-right).
> 
> * 👍️ if you **need this** to be able to use Mailu. Ideally, you’d also be able to test this on your installation, and provide feedback …
> * 🎉 if you find it a **nice bonus**, but no deal-breaker
> * 🚀 if you want to **work on it yourself**!
>   We want to keep this **voting open for 2 weeks** from now, so please help out!

Hi,
I appreciate your business with the project a lot, at the same time my PR with few lines of changes is "only" 1 year old.
Could you kindly review it and either merge or just cancel?
It is sitting and waiting for something really unknown to happen

Regards Sergiy

**Comment by nextgens** [comment]
We've discussed this on #mailu-dev recently ... and can't see a usecase for smtp_tls_wrappermode.

You can already specify a port in the relay host field... and force SMTPS that way (fqdn-of-smtpd.example.com:465)

That being said, it would be great if settings could be specified for specific destinations (GAFAs are unlikely to get their TLS setup wrong so we could force a secure connection there). Having a configurable (or easily overridable) smtp_tls_policy_maps would make sense and could cover relays.

**Comment by nextgens** [comment]
@Snakesms can you confirm whether #1902 above would solve your usecase?

**Comment by Snakesms** [comment]
Thanks for coming back on this.
1) I'm not sure how specifying the port "fqdn-of-smtpd.example.com:465" should help me with 
"SMTP_TLS_WRAPPERMODE=yes" option for Postfix required to let my (or actually Internet provider's) relay to work

According to the doc:

smtp_tls_wrappermode (default: no)
Request that the Postfix SMTP client connects using the legacy SMTPS protocol instead of using the STARTTLS command.

This mode requires "smtp_tls_security_level = encrypt" or stronger.

Example: deliver all remote mail via a provider's server "mail.example.com".

/etc/postfix/main.cf:
    # Client-side SMTPS requires "encrypt" or stronger.
    smtp_tls_security_level = encrypt
    smtp_tls_wrappermode = yes
    # The [] suppress MX lookups.
    relayhost = [mail.example.com]:465

2) "That being said, it would be great if settings could be specified for specific destinations" -
agree, it would be great to have a polciy_maps easily configurable and potentially "wrappermode" can be configured through the map according to this line in the doc:
"The lookup result is a security level, **followed by an optional list of whitespace and/or comma separated name=value attributes that override related main.cf settings.** ..."

however, it needs to be tested

**Comment by nextgens** [comment]
1) smtp_tls_wrappermode is only required if your relayhost expects SMTPS on a port that isn't 465 ... on the example you give, removing that line will work just fine (as port 465 is specified/used).
2) yes indeed, it needs to be tested; Can you test #1902 ? (deploy the patch and create a tls_policy.map file in overrides/postfix/ ?)

Looking at your usecase, to me it looks like all you need is the following configuration variable:
RELAYHOST=[mail.example.com]:465

If you intend on making it more secure, you can add:
OUTBOUND_TLS_LEVEL=encrypt

This should work on the current version of mailu and doesn't require anything specific.

**Comment by Grennith** [comment]
Digging in some real old issues here... 
```
2023-04-16T10:38:33.576392+02:00 mailu-postfix-79cf49674c-rwhvr postfix/smtp[520]: SMTPS wrappermode (TCP port 465) requires setting "smtp_tls_wrappermode = yes", and "smtp_tls_security_level = encrypt" (or stronger)
2023-04-16T10:38:33.616860+02:00 mailu-postfix-79cf49674c-rwhvr postfix/smtp[520]: warning: DNSSEC validation may be unavailable
2023-04-16T10:38:33.616898+02:00 mailu-postfix-79cf49674c-rwhvr postfix/smtp[520]: warning: reason: dnssec_probe 'ns:.' received a response that is not DNSSEC validated
```

Hence using port 465 may very well require configuration of smtp_tls_wrappermode which is currently not possible.
To use port 587 (STARTTLS) requires additional parameters as well...

**Comment by nextgens** [comment]
@Grennith If you need help with setting it up, user support is at https://riot.im/app/#/room/#mailu:tedomum.net
