### ISSUE TITLE
setup.mailu.io is down frequently

### ISSUE THREAD

**Issue by Nebukadneza** [Mailu/Mailu#1563]
Hi all,

unfortunately setup.mailu.io is down again. @muhlemmer currently has access to fix is, but seems quite busy.

Until he can help out, I put up a emergency replacement at:
https://mailu-setup.kanojo.de/
While it can only offer 1.7 at the moment, please use it until we can get the main setup-utility up and running again.

Sorry for the inconvenience caused.

**Comment by OscarPaz** [comment]
Thanks @Nebukadneza!
Did read about this only just after posting on #1527.

**Comment by Nebukadneza** [comment]
Sorry i didn’t place a link inside there … and thanks for referencing them!

**Comment by mikelopez654** [comment]
@Nebukadneza I was looking for a way to "give back" to the mailu team.  If you guys need a server to host an extra copy of the setup, please just let me know! I self-host all my sites, so 1 more wouldn't be a big deal.....no charge of course :) Thank you for everything all of you do

**Comment by Nebukadneza** [comment]
Official setup instance is up again, so closing this.


> If you guys need a server to host an extra copy of the setup, please just let me know!

Thanks for the offer. I think the problem is more a organizational one, than a technical. We just need to find time to either give the whole team access to the current hosting, or move it somewhere where doing so would be easy. Thanks nevertheless~

**Comment by Nebukadneza** [comment]
Currently, it’s broken again, and the team could not find time to make the setup server accessible to team-members. So, I’m reopening this, with my replacement started up again …

**Comment by muhlemmer** [comment]
Hey! Sorry for the inconvenience. All systems are back up again.

So, after solving the last issue (on that server) of ClamaAV filling all the disk space, now the Docker deamon filled up everything under `/var/docker`. Probably has to do with the automatic update script running. Although strangely enough, `docker system prune` did not cleanup anything until I stopped all containers.

So at the moment there are two things pending from my side,

1. Provide access to the server to more members of the team.
2. Check the updater script if it can do some house keeping on the way.

**Comment by Nebukadneza** [comment]
Hi @muhlemmer, and thanks for the continued maintenance of these systems!

If 1. would be possible, that’d mean that more people could collaborate on fixing 2. — which would probably lead to lessen the load on your end, as well as make it more likely to find and fix all of these issues for good ^_^.

I understand that the environment this runs on is co-used by some of your other projects/services/…, is that correct?

If that’s the case, and the main issue blocking us at this point, how about we reach out and try to find someone as a sponsor for the project? I guess for only setup and demo, a rather small machine would be sufficient. I could imagine to write mails to a couple of cloud-hosting/server-hosting companies (maybe DigitalOcean, Hetzner, …) and … well … daringly ask if it’s possible?

As for more technical solutions under the above assumption, I can only come up with ugly solutions myself:
1. A restartable-from-the-inside DinD to contain the various setup/demo containers, along with a host user that has a shell forced into the container
2. (depending on your setup), A true VM do to the same.

While 1. makes me want to take a shower from proposing something so dirty, 2. may or may not be possible depending on your architecture.

Sorry for having written such a long rambling again. Please let me know what you think ^_^.
Best,
-Dario

**Comment by Kernald** [comment]
Ping on that - it's down today as well. The main form works, but submitting triggers an internal server error. The replacement linked in https://github.com/Mailu/Mailu/issues/1563#issue-652532107 is also down (404).

**Comment by HosseyNJF** [comment]
I'm experiencing the same issue.

**Comment by Diman0** [comment]
In the past year multiple changes have been applied to make demo site and setup site more robust. I'm closing this issue.
If new issues occurs, then we can create a new issue.
