### ISSUE TITLE
Ability to override babel selected language

### ISSUE THREAD

**Issue by lugdunum-1964** [Mailu/Mailu#1567]
I'm not sure if the option already exists, if so, I can't find it in the documentation.

Please add an option for a user to select the interface language. Babel apparently selects the language based on the browser suggestions. So I'm now getting the dutch language for the mail admin interface. However I've never used Dutch for anything technical since English is the universal language for anythin technical, so I don't know what half of the translations even mean. 
An option to override babel would be welcome.

--
Regards,
Lyon

**Comment by Nebukadneza** [comment]
Hi There,

The `Mailu`-Project is currently in a bit of a bind! We are short on man-power, and we need to judge if it is possible for us to put in some work on this issue.

To help with that, we are currently trying to find out which issues are actively keeping users from using `Mailu`, which issues have someone who want to work on them — and which issues may be less important. These a less important ones could be discarded for the time being, until the project is in a more stable and regular state once again.

In order for us to better assess this, it would be helpful if you could put a **reaction on this post** (use the :smiley: icon to the top-right).
- 👍️ if you **need this** to be able to use Mailu. Ideally, you’d also be able to test this on your installation, and provide feedback …
- 🎉 if you find it a **nice bonus**, but no deal-breaker
- 🚀 if you want to **work on it yourself**!
We want to keep this **voting open for 2 weeks** from now, so please help out!

**Comment by DjVinnii** [comment]
I am currently working on an updated version of the admin interface by using AdminLTE 3 (https://github.com/Mailu/Mailu/issues/1764). This morning I concluded there is no option to manually select a language, however this would be a nice addition. I will have a look if there is a neat way to implement this functionallity.
