### ISSUE TITLE
Project Management, Maintenance and Future

### ISSUE THREAD

**Issue by Nebukadneza** [Mailu/Mailu#1569]
Hello Dear Users, Contributors and Developers,

in the recent weeks to months, unfortunately, Mailu came to quite a halt. This is, to my knowledge, most likely due to a combination of increased workload of IT people due to COVID- but also personal and day-job matters.

Please take everything I write here as a Request-For-Discussion …

However, no matter the reason, currently the project fails at a couple of points:
(please don’t take this as an insult, I’m guilty myself of not helping enough, and I just want to attempt to list the pain-points)
* User communication and support: Issues remain unanswered, and the Matrix channel is only irregularly tended
* Contribution management: There’s a lot of nice contributors out there — currently we are not able to triage, support and include the open Pull-Requests
* Releases: 1.8 is overdue, and completion-wise at the doorstep, however we currently fail at going the last steps
* Infrastructure: Ranging from ever-failing builds and weird BORS behavior to the recent few failures of setup, these things are slowing us down, making us waste work and time perform tasks that do not bring us forward
* Github Management: We do have some Labels, Projects and Milestones — however, the Labels are still a bit verbose and chaotic to me and the Projects are kind of deserted. This makes it hard to efficiently find and sort Issues and PRs. I personally feel that simplicity would be bliss here …
* Testing: Our test-framework is coarse at best, and fails in a flaky manner. This frustrates contributors and maintainers alike — however, cleanly testing a system that’s main task is integrating complex service is no easy feat, and needs a lot of time-resources thrown onto.
* Project Future/Vision: To me, and I hope to many users :-), Mailu is in a state that’s incredibly useful. However, with the current amount of time the team is able to invest, it’s hard to envision how the project could move forward beyond keeping its currently-useful state.

I must admit that I am myself a bit at a loss of what to do. With the amount of PRs and Issues open, the task of triaging all (most?) of them seems tremendous.

In fact, this is one of the key-points that I would like to discuss: Looking at the list above, it’s obvious we can’t manage all of these tasks. So: do we want to take a conscious decision to keep architectural change and feature additions to a minimum? Does that give us more air to breath to keep the project running, and push small, incremental, but worthy changes out?
Another thing I could think of is being much more radical in filtering what’s coming in (Issues / PRs). This is a part of constant management overhead that does take a toll. However, reducing that almost certainly means being »rude« to users and contributors … and I’m not sure that’s who we want to be?
If not that, what is your opinion on what points we can and should focus on? As said, I’m at a bit of a loss myself.

As a slight side-note: Regarding the immediate goal of finishing the upcoming 1.8 release, what would be our next steps? In my head, currently it’d be (in descending order of execution):
* Triage currently open PRs to the 1.8 milestone and care to get them merged
* Triage currently open Issues and add to the 1.8 milestone those which need immediate care
* Once most is integrated, try to get as many savvy people to manually test. I fear this stone-age-like step is required since our testing-framework is still lacking
* Once manual testing is somewhat satisfactory, maybe a few of the maintainers would care to dogfood? I’d certainly like to!
* Release? :tada: 

The problem is kind of how to get started, and in our distributed team with little time-resources on every individual, especially the triaging and testing seems daunting.

So … uh … I guess this was a bit of a confused writeup in epic length. Sorry for that.
I just really really want Mailu to stick around … and if possible, let’s discuss how we can proactively move forward!

A big thanks to everyone who’s using and contributing to Mailu!
Best Regards
-Dario

**Comment by jheinitz** [comment]
Moin Dario,

actually I do not have anything to contribute to Mailu, but I'm using it
now for some time and I don't want to miss it. So all I can add at this
point is to thank all of you for your great work on this project. Keep it
up!

Thanks and best regards

Jens

Am Mo., 13. Juli 2020 um 21:52 Uhr schrieb Dario Ernst <
notifications@github.com>:

**Comment by sholl** [comment]
Hi Dario,

since I am quite new to Mailu from a users perspective I would love to throw my hat in to support this project to get new momentum (and at least) for getting Version 1.8 out of the door.

Best regards

    Stephan

**Comment by conorboyd** [comment]
I've only recently come across Mailu, but it seems to have exactly what I
was looking for, and I'd love to see the project continue.

Thanks to all who have contributed in the past, and continue to do so.

Cheers,

Conor

**Comment by ofthesun9** [comment]
Hello @Nebukadneza 
Thanks for your message ! I mostly agree with you.
To regain some momentum on 1.8 release, I would propose an (arbitrary) date for a pre-release (to allow testing from the community), and a release date. It would give a clear deadline for the merging activities,  and maybe will bring some back some focus on it ?
Pre release on 1st september ?
Release on 1st october ?

**Comment by Nebukadneza** [comment]
Thanks everyone, and thanks @ofthesun9 

I think that is a very reasonable plan for action. It will give us some time — but not too much — to consolidate, give us a clear goal with a specific deadline, and we can plan on what’s to be included and what’s not given the time-frame and estimates of the time we can each muster up.

On the milestone, we can set a due-date — if okay with you, I’d go ahead and set it to 1st of october.

The one other thing I’d like to do in preparation, is weed out the issue/PR labels. As stated above, the current flood of labels confuses me to a level where i find it hard judging what’s most important and whats not — and makes triaging harder. And, by extension, triaging is something I’d like to do soon.

Last but not least, what do you guys think about a collaborative triaging session, in some free video-conferencing tool? We could use a free/selfhosted date-planning tool, to find a spot where enough people are free, and use a conferencing tool like jitsi or bigbluebutton to collaboratively go through open issues and PRs, and discuss/judge what’s most important and/or realistic to include. Would that help us accelerate a bit again?

Thanks everyone~,
-Dario

**Comment by Diman0** [comment]
Hello @Nebukadneza 

I really like this project. I'm currently working on a PR to add documentation for how the spam filtering works. 
Although I do not have a lot of experience with the software components yet I'd also to like help out. I don't mind joining a triage session. Triaging is probably easier if you can brainstorm with multiple people.

After triage everything that is to be included should have the label 1.8. After this a project could be created with all items with this label so we can keep track of all the work that must be done. Without this there is no overview on what has to be done.

**Comment by IchikawaYukko** [comment]
Hello @Nebukadneza
Mailu is very great project! I really like this too.
So, I'm using it as my domain's mail server from Ver 1.5.
I remember my 1st PR was marged into this project. I was very glad that time.
I wish Mailu have many more successful.
Thanks all who keep growing this.

Good luck.

**Comment by Nebukadneza** [comment]
Cross-linking one outcome of this:
#1582

**Comment by liquidat** [comment]
@Nebukadneza Thanks for this honest write up. Happy to help with project organization, labeling, and also documentation PRs (like the Spam documentation one going on right now).

In terms of project development, I would have two suggestions:
First, there should be releases every few months. It helps to show that the project is alive, it is more attractive to other contributors when their stuff is released rather quickly, and it eases the pain of updating if updates are frequently enough.
Second, I would recommend to switch to a fixed release cycle. If there is a release every 6 months contributors can better plan when their contributions might be accepted and merged. And again it forces the team itself to release often enough.

Adding @dhoppe for awareness.

**Comment by Nebukadneza** [comment]
Thank you for the offer to help, and suggestions!

Indeed, getting into a mode of having more regular but likely much smaller releases was one outcome of our discussions on matrix recently. I feel that’s one of the main goals we should focus on, and shape our scope such as that it can be accomplished, however small that may be — depending on the current possible time-investment.

On the practical side, we wanted to first get the long-overdue 1.8 out first, then go for a rather quick, very-small successor, and I believe that the right point in time for discussing whether the schedule can be regular, and if so, what it should be, would be after that.

As for your suggestion to help, that’s of course a warmly welcome one. Since you mentioned documentation, @Diman0 is currently continuing documentation work, and rather active in the Matrix channel. How about you drop by there …?

**Comment by pesimon** [comment]
Hi @Nebukadneza 

Thanks for your initiative to keep the project alive. I started using Mailu when it still was called freepost.io ;) 
I'm happy to help with testing, setting up automated testing or work on support for running on kubernetes with ingress etc. 
Of course all if time permits.

**Comment by Diman0** [comment]
For everyone's information. We are making some progress now. We are meeting regularly and have a 1.8 release candidate in our sights now. Hopefully we can start testing in October. This means we might be able to release 1.8 in November/December. 

For anyone who wants to get involved, feel free to join our matrix channel: https://matrix.to/#/#mailu:tedomum.net
To keep up to date for any meetings we had and for new meetings see topic #1582

**Comment by Diman0** [comment]
I think we can close this issue for now. More people have joined the project. We are meeting regularly now (see #1582 ). Hopefully we will have a new release at the end of this year. We have quite a lot of pull requests merged (see https://github.com/Mailu/Mailu/tree/master/towncrier/newsfragments ).

Once this becomes an issue again, we can continue in a new issue.
