### ISSUE TITLE
Enable Rspamd WebUI, or override configuration

### ISSUE THREAD

**Issue by kmoens** [Mailu/Mailu#157]
I would like to tune the rspamd further, with custom rulesets.
For this I would like to either have an option to configure them via a mapped folder, or alternatively by the admin ui of rspamd.

If not possible hyet, I'm willing to investigate the necessary changes and submit a pull request for it.

**Comment by kaiyou** [comment]
In the spirit of current Mailu developments, I would rather have a mounted volumes with additional rulesets, just like custom Dovecot configuration. It should be pretty straightforward to implement.

**Comment by kmoens** [comment]
Looks to me for a good approach too.
Could you point me to some docs about the Dovecot part? Then I'll investigate to do this for rspamd too and submit a pull request afterwards.

**Comment by kaiyou** [comment]
For statistics display, we may be able to display the Rspamd web UI using a proxy option with subrequest authenticaiton in Nginx.

**Comment by dzervas** [comment]
We could implement JWT or oAuth 2 in the admin panel and authenticate for the rspamd panel against that

**Comment by kaiyou** [comment]
oAuth would indeed be fine but I would rather have something generic enough for every application. Unless we implement oAuth in the nginx frontend as well, but I barely see the point since all components can do backend requests.

**Comment by kaiyou** [comment]
You can now override the configuration through `/mailu/overrides/rspamd`.
