### ISSUE TITLE
Postfix Internal server error after reboot

### ISSUE THREAD

**Issue by Megaland90** [Mailu/Mailu#1571]
Hello, after restarting the postfix server it returns the error code 451, 4.3.2 Internal server error . 
Do you have any solution?

**Comment by Diman0** [comment]
Have you tried to look up the real error in the output of the postfix container?
First replicate the error and then run
`docker logs --tail 1000 mailu_smtp_1 | less`

If nothing is listed, then you could temporarily increase logging of the smpt daemon
1). Connect to the container:
docker exec -it mailu_smtp_1 /bin/bash
2). Temporaliy set logging to verbose for smtp, open /etc/postfix/master.cf
vi /etc/postfix/master.cf
3). Change the line
`smtp      unix  -       -       n       -       -       smtp`
for
`smtp      unix  -       -       n       -       -       smtp -v`
4). Reload the postfix config, execute
postfix reload
5). exit the container using "exit" (without quotes).
6). Replicate the issue again and check the logs
docker logs --tail 1000 mailu_smtp_1 | less

**Comment by Nebukadneza** [comment]
Hi There,

The `Mailu`-Project is currently in a bit of a bind! We are short on man-power, and we need to judge if it is possible for us to put in some work on this issue.

To help with that, we are currently trying to find out which issues are actively keeping users from using `Mailu`, which issues have someone who want to work on them — and which issues may be less important. These a less important ones could be discarded for the time being, until the project is in a more stable and regular state once again.

In order for us to better assess this, it would be helpful if you could put a **reaction on this post** (use the :smiley: icon to the top-right).
- 👍️ if you **need this** to be able to use Mailu. Ideally, you’d also be able to test this on your installation, and provide feedback …
- 🎉 if you find it a **nice bonus**, but no deal-breaker
- 🚀 if you want to **work on it yourself**!
We want to keep this **voting open for 2 weeks** from now, so please help out!
