### ISSUE TITLE
How to change postfix configuration "main.cf"

### ISSUE THREAD

**Issue by blainvillem** [Mailu/Mailu#1572]
Hello,

When i change postfix configuration "main.cf" and restart the container, he reload the default configuration and remove my changes.

I've test to use the folder "overrides" with the file named "postfix.cf" but my new configuration is not being used.

**Comment by Diman0** [comment]
That is strange. On startup, the settings in postfix.cf should be added to main.cf via postconf

See lines 37-39 of [https://github.com/Mailu/Mailu/blob/1.7/core/postfix/start.py](https://github.com/Mailu/Mailu/blob/1.7/core/postfix/start.py)
```
if os.path.exists("/overrides/postfix.cf"):
    for line in open("/overrides/postfix.cf").read().strip().split("\n"):
        os.system('postconf -e "{}"'.format(line))
```

Maybe you could create a small python script with this code and try running it on the postfix container? 
Can you see any errors being logged in the output of the container?

**Comment by blainvillem** [comment]
Thanks for the information, I found the corresponding lines in the start.py file:

https://i.ibb.co/TmPrWqh/overrides.png

Maybe my problem is the modification I'm making to the hand.cf .

I try to add the possibility for the recipients to make an "unsubscribe":

https://i.ibb.co/bz1nzcy/list-unsub-header.png

https://i.ibb.co/X4g0jFR/postfix.png

**Comment by blainvillem** [comment]
I have another question, is it possible to save a new mail/postfix Docker image after changing some configuration files?

When I create my new image, I have the impression that it is not connected with the rest of the containers and it is impossible for me to send mails.
And it is also impossible for me to delete the old mailu/postfix image because the new image depends on the old one. "Depends child image".


Translated with www.DeepL.com/Translator (free version)

**Comment by Diman0** [comment]
Have you changed your docker-compose.yaml file to use the local image you've created?

**Comment by blainvillem** [comment]
What should be changed in the docker-composite file?



When I commit, I name the new image with the name of the old "mailu/postfix:1.7".



At that time, the old image loses its "1.7" tag.  But it is impossible to delete it with docker rmi because it is dependent on childs image.

**Comment by Nebukadneza** [comment]
Hi There,

The `Mailu`-Project is currently in a bit of a bind! We are short on man-power, and we need to judge if it is possible for us to put in some work on this issue.

To help with that, we are currently trying to find out which issues are actively keeping users from using `Mailu`, which issues have someone who want to work on them — and which issues may be less important. These a less important ones could be discarded for the time being, until the project is in a more stable and regular state once again.

In order for us to better assess this, it would be helpful if you could put a **reaction on this post** (use the :smiley: icon to the top-right).
- 👍️ if you **need this** to be able to use Mailu. Ideally, you’d also be able to test this on your installation, and provide feedback …
- 🎉 if you find it a **nice bonus**, but no deal-breaker
- 🚀 if you want to **work on it yourself**!
We want to keep this **voting open for 2 weeks** from now, so please help out!

**Comment by Diman0** [comment]
Normally I would use a different tag and image name when creating the image and also use this in your docker-compose.yml file to make it more explicit.
Another approach is to connect to the postfix container
```
cd /mailu
docker-compose exec smtp /bin/bash
```
After that you can create a python file with vi
```
if os.path.exists("/overrides/postfix.cf"):
    for line in open("/overrides/postfix.cf").read().strip().split("\n"):
        os.system('postconf -e "{}"'.format(line))
```

Can you share your /overrides/postfix.cf file?
and then run it to check the output.
