### ISSUE TITLE
Use of "deploy_to_pi.sh"

### ISSUE THREAD

**Issue by lupoalberto12** [Mailu/Mailu#1579]
Hi.
It isn't a issue but the lack of documentation.

What parameter does the script "(test/)deploy_to_pi.sh" need to start?
I meat at "compose_options=$1" .

Thanks.
Regards.

**Comment by Nebukadneza** [comment]
Hi There,

The `Mailu`-Project is currently in a bit of a bind! We are short on man-power, and we need to judge if it is possible for us to put in some work on this issue.

To help with that, we are currently trying to find out which issues are actively keeping users from using `Mailu`, which issues have someone who want to work on them — and which issues may be less important. These a less important ones could be discarded for the time being, until the project is in a more stable and regular state once again.

In order for us to better assess this, it would be helpful if you could put a **reaction on this post** (use the :smiley: icon to the top-right).
- 👍️ if you **need this** to be able to use Mailu. Ideally, you’d also be able to test this on your installation, and provide feedback …
- 🎉 if you find it a **nice bonus**, but no deal-breaker
- 🚀 if you want to **work on it yourself**!
We want to keep this **voting open for 2 weeks** from now, so please help out!

**Comment by lupoalberto12** [comment]
> Hi There,
> 
> The `Mailu`-Project is currently in a bit of a bind! We are short on man-power, and we need to judge if it is possible for us to put in some work on this issue.
> 
> To help with that, we are currently trying to find out which issues are actively keeping users from using `Mailu`, which issues have someone who want to work on them — and which issues may be less important. These a less important ones could be discarded for the time being, until the project is in a more stable and regular state once again.
> 
> In order for us to better assess this, it would be helpful if you could put a **reaction on this post** (use the 😃 icon to the top-right).
> 
> * 👍️ if you **need this** to be able to use Mailu. Ideally, you’d also be able to test this on your installation, and provide feedback …
> * 🎉 if you find it a **nice bonus**, but no deal-breaker
> * 🚀 if you want to **work on it yourself**!
>   We want to keep this **voting open for 2 weeks** from now, so please help out!

Hi Nebukadneza,
thank you for the response.

I export the image with the docker command and then import in my Pi.

Have a nice day.

**Comment by lub** [comment]
@lupoalberto12 I think `compose_options=$1` is just there in case you want to supply additional options to docker-compose.

By default it's apparently not neccessary https://github.com/Mailu/Mailu/raw/0417c791ffa24558102890d45a552ff29ef0f5cf/docs/rpi_build.rst

**Comment by nextgens** [comment]
deploy_to_pi.sh doesn't exist in master anymore. We now have arm64 images.
