### ISSUE TITLE
postfix.cf is not read (again)

### ISSUE THREAD

**Issue by tremlin** [Mailu/Mailu#1580]
The issue described in #941 is present again in master branch as the fix #945 was removed from the code (https://github.com/Mailu/Mailu/commit/bd69b7a4915cb1841adf700003018b07f7a260ad#diff-a3dd17dd36aa26b6fcf013616ab2b0c0). I think that adding an uncommented blank line is likely to break again.
Can we use `keep_trailing_newline` as suggested in the original issue or change the code in `start.py` in another way that enforces a new line at the end?

**Comment by Nebukadneza** [comment]
Hi There,

The `Mailu`-Project is currently in a bit of a bind! We are short on man-power, and we need to judge if it is possible for us to put in some work on this issue.

To help with that, we are currently trying to find out which issues are actively keeping users from using `Mailu`, which issues have someone who want to work on them — and which issues may be less important. These a less important ones could be discarded for the time being, until the project is in a more stable and regular state once again.

In order for us to better assess this, it would be helpful if you could put a **reaction on this post** (use the :smiley: icon to the top-right).
- 👍️ if you **need this** to be able to use Mailu. Ideally, you’d also be able to test this on your installation, and provide feedback …
- 🎉 if you find it a **nice bonus**, but no deal-breaker
- 🚀 if you want to **work on it yourself**!
We want to keep this **voting open for 2 weeks** from now, so please help out!

**Comment by tremlin** [comment]
I can provide a MR but I would like to have some input which solution is preferred.

**Comment by Nebukadneza** [comment]
Thanks, @tremlin !

In my opinion (other feedback warmly welcome!), making `Jinja` append the newline is more stable and more safe. Many developers (me among them :sweat_smile:) have an urge to remove trailing newlines or whitespaces everywhere. Sometimes editors do it without asking. So at least without a comment or note, the newline is bound to vanish again.

Without having tried it, I’d say parametrizeing Jinja is the better option, and not much more change or complexity.
