### ISSUE TITLE
Mail relaying (Relayed domain) does't work when no Remote Host is configured.

### ISSUE THREAD

**Issue by Diman0** [Mailu/Mailu#1588]
Description: 
When in the Web Administration Interface in Relayed domain, a domain is added without a Remote Host, emails for this domain fail to be relayed. When no Remote Host is configured, Mailu is supposed to relay the email message directly to the relayed domain.

In case it is relevant I use the docker-compose deployment.

Replication steps:
1). Deploy a standard Mailu installation (no special configuration required). 
2). In the Web Administration interface, on Relayed domains page add a new relayed domain with
Relayed domain name: test.mailu.io
Remote Host:  (blank, keep it empty).
3). Configure your email client SMTP settings to use your Mailu server on port 25 without any authentication.
4). Send an email to admin@test.mailu.io. If you receive the message, server is busy try again. Then Rspamd has greylisted you. Try sending the email again in 10 to 15 minutes. It should be accepted now.
5). Check the postfix logs (docker logs --tail 100 mailu_smtp_1 )

Aug 13 22:47:32 mail postfix/smtpd[270]: A1C493E2CE1: client=<redacted>.nl[xx.xxx.xx.xxx]
Aug 13 22:47:32 mail postfix/cleanup[315]: A1C493E2CE1: message-id=<71874e8e-c30d-e0a3-4d70-de4542b47664@yahoo.com>
Aug 13 22:47:33 mail postfix/qmgr[177]: A1C493E2CE1: from=<redacted@yahoo.com>, size=2765, nrcpt=1 (queue active)
Aug 13 22:47:33 mail postfix/smtpd[270]: disconnect from <redacted>.nl[xx.xxx.xx.xxx] ehlo=2 xclient=0/1 mail=1 rcpt=1 data=1 quit=1 commands=6/7
**Aug 13 22:47:33 mail postfix/smtp[316]: fatal: valid hostname or network address required in server description: []
Aug 13 22:47:34 mail postfix/qmgr[177]: warning: private/smtp socket: malformed response**
Aug 13 22:47:34 mail postfix/qmgr[177]: warning: transport smtp failure -- see a previous warning/fatal/panic logfile record for the problem description
Aug 13 22:47:34 mail postfix/master[175]: warning: process /usr/libexec/postfix/smtp pid 316 exit status 1
Aug 13 22:47:34 mail postfix/master[175]: warning: /usr/libexec/postfix/smtp: bad command startup -- throttling
Aug 13 22:47:34 mail postfix/error[318]: A1C493E2CE1: to=<admin@test.mailu.io>, relay=none, delay=1.6, delays=0.59/1/0/0.01, dsn=4.3.0, status=deferred (unknown mail transport error)

Workaround:
A workaround is to enter the hostname or IP address of the SMTP server of the relayed domain name as Remote Host. No MX lookup is performed for a hostname entered as Remote Host. For a public domain, you could use the mxtoolbox to lookup the SMTP server. E.g. in my example for test.mailu.io https://mxtoolbox.com/SuperTool.aspx?action=mx%3atest.mailu.io&run=toolpage .

Entering 78.47.92.244 or test.mailu.io as Remote Host will work as a workaround for the above example.

**Comment by Nebukadneza** [comment]
Hi There,

The `Mailu`-Project is currently in a bit of a bind! We are short on man-power, and we need to judge if it is possible for us to put in some work on this issue.

To help with that, we are currently trying to find out which issues are actively keeping users from using `Mailu`, which issues have someone who want to work on them — and which issues may be less important. These a less important ones could be discarded for the time being, until the project is in a more stable and regular state once again.

In order for us to better assess this, it would be helpful if you could put a **reaction on this post** (use the :smiley: icon to the top-right).
- 👍️ if you **need this** to be able to use Mailu. Ideally, you’d also be able to test this on your installation, and provide feedback …
- 🎉 if you find it a **nice bonus**, but no deal-breaker
- 🚀 if you want to **work on it yourself**!
We want to keep this **voting open for 2 weeks** from now, so please help out!

**Comment by sdotb** [comment]
I have two installatioin of mailu server accordingly with documentation. Apparently when I add a relayed domain an I press the Save Button nothing seems to work, Just not able to add relayed domains
