### ISSUE TITLE
Mailu with kubernetes branch master not let login on webmail because a problem with IPAM login.

### ISSUE THREAD

**Issue by aleleba** [Mailu/Mailu#1593]
When I try to login in webmail in Kubernetes with a valid user, webmail not let me in.

**Comment by aleleba** [comment]
I will paste the log error of mailu/roundcube:master pod:
[24-Aug-2020 15:54:34 +0000]: <6cb032a1> IMAP Error: Login failed for admin@p-lao.tk against front.mailu-mailserver.svc.cluster.local from 10.244.0.221(X-Real-IP: 10.244.0.26,X-Forwarded-For: 104.131.45.103, 10.244.0.26). AUTHENTICATE PLAIN: Authentication failed. in /var/www/html/program/lib/Roundcube/rcube_imap.php on line 200 (POST /?_task=login&_action=login)
10.244.0.221 - - [24/Aug/2020:15:54:31 +0000] "POST /?_task=login HTTP/1.1" 401 3064 "https://mail.p-lao.tk/webmail/" "Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Mobile Safari/537.36"

**Comment by liquidat** [comment]
> Login failed for admin@p-lao.tk 

@aleleba In my understanding IMAP logins only work with mail users you created. Admin is a user web frontend user that does not necessarily exist as a mail user.
Can you create a normal mail user and try to login with that?

**Comment by liquidat** [comment]
@aleleba Also, did you check the documentation about [possible database problems with imap login problems and kubernetes](https://mailu.io/1.7/kubernetes/mailu/index.html#imap-login-fix)?
