### ISSUE TITLE
tons of SSL errors in antispam log

### ISSUE THREAD

**Issue by pgeorgi** [Mailu/Mailu#160]
looks like
"map; http_map_error: connection with http server terminated incorrectly: ssl connect error: error:00000001:lib(0):func(0):reason(1)"

Running "apk add ca-certificates" inside mailu_antispam_1 fixes this for me (until the container is rebuilt the next time)

**Comment by kaiyou** [comment]
Thank you for reporting, rookie mistake on my side, fixing right now!
