### ISSUE TITLE
Changing password command not working

### ISSUE THREAD

**Issue by ManicPumpkin** [Mailu/Mailu#1602]
Hello,

I'm trying to reset the password for a specific user via the specified command in the documentation "docker-compose exec admin flask mailu password myuser example.net 'password123'", but the response the terminal shows me is, that such command "mailu" does not exists. 

The normal commands for creating a user via the manage.py script working normally. The problem I have here is, that there is no command for changing the user password.

Best wishes,
Manic.

**Comment by Diman0** [comment]
Are you using version 1.7?
Are you executing this command from the folder where the mailu stack is deployed?

`docker-compose exec admin flask mailu password myuser mydomain.com 'password123'`
This command still works fine for me.
