### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by cgott82** [Mailu/Mailu#1605]
A known problem occurs ==>

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Comment by NikitaDimitriev** [comment]
Has same responce from https://setup.mailu.io/1.7

**Comment by Nebukadneza** [comment]
Sorry, I took a while to re-post the replacement server issue, until we figure out the hosting access situation and all

duplicate #1563

Please head over there to find a working setup instance ^_^
