### ISSUE TITLE
setup.mailu.io returns: 500 internal sever error

### ISSUE THREAD

**Issue by ddtlabs** [Mailu/Mailu#1608]
Since a few days, I got an internal server error, when I try to get an docker-compose.yml. I have tried firefox and safari on Mac OS.
If you need more detailed infos, please let me know.

**Comment by liquidat** [comment]
Thanks for reporting, this was already noticed: See #1563 for an updated state and also an emergency service which can provide you a docker-compose.yml

Would you mind closing this in favor of #1563? We try to bundle everything there.

**Comment by ddtlabs** [comment]
Sorry for the circumstances, I did not found this issue.

**Comment by liquidat** [comment]
@ddtlabs No worries, glad that we could help that easily :)
Thanks for taking the time to follow up on this and closing the issue.

**Comment by cadmi** [comment]
again :)
