### ISSUE TITLE
Mail sending failure notification

### ISSUE THREAD

**Issue by Al2Klimov** [Mailu/Mailu#1614]
In the Postfix log I see the following error message:

```
Sep 06 15:51:08 smtp postfix/smtp[8260]: 2755E408D6: host mx03.t-online.de[194.25.134.73] refused to talk to me: 554 IP=192.0.2.1 - A problem occurred. (Ask your postmaster for help or to contact tosa@rx.t-online.de to clarify.) (BL)
```

But neither the postmaster, nor the sender got notified via eMail.

**Comment by Diman0** [comment]
Are you using version 1.7?
Did you make any changes to the postfix configuration?
The default configuration of Postfix sends bounce emails to the sender.

The next time you should post all relevant logs. 
1). docker logs mailu_smpt_1 > temp
2). grep 2755E408D6
This provides you with all relevant log messages. See example below

Sep 07 13:35:40 mail postfix/cleanup[26537]: 81EE0980F16: message-id=<00b7479e-5c0c-985f-1076-e6b833f9d66d@example.com>
Sep 07 13:35:40 mail postfix/qmgr[119]: 81EE0980F16: from=<user@example.com>, size=615, nrcpt=1 (queue active)
Sep 07 13:35:41 mail postfix/lmtp[26538]: 81EE0980F16: to=<doesnotexist@example.com>, relay=172.19.0.7[172.19.0.7]:2525, delay=0.72, delays=0.54/0.09/0.05/0.04, dsn=5.1.1, status=bounced (host 172.19.0.7[172.19.0.7] said: 550 5.1.1 <doesnotexist@example.com> User doesn't exist: doesnotexist@example.com (in reply to RCPT TO command))
**Sep 07 13:35:41 mail postfix/bounce[26539]: 81EE0980F16: sender non-delivery notification: 0FA90980F19**
Sep 07 13:35:41 mail postfix/qmgr[119]: 81EE0980F16: removed

The bolded line is postfix sending the bounce email. Do you also see this? 
You can also use grep to get these lines. For my example

3). grep 0FA90980F19 log_file
Sep 07 13:35:41 mail postfix/cleanup[26540]: 0FA90980F19: message-id=<20200907133541.0FA90980F19@mail.example.com>
Sep 07 13:35:41 mail postfix/bounce[26539]: 81EE0980F16: sender non-delivery notification: 0FA90980F19
Sep 07 13:35:41 mail postfix/qmgr[119]: 0FA90980F19: from=<>, size=4162, nrcpt=1 (queue active)
Sep 07 13:35:41 mail postfix/lmtp[26538]: 0FA90980F19: to=<user@example.com>, relay=172.19.0.7[172.19.0.7]:2525, delay=0.44, delays=0.04/0.07/0/0.33, dsn=2.0.0, status=sent (250 2.0.0 <user@example> 8AfRCS03Vl+aGAAAgYfiHQ Saved)
Sep 07 13:35:41 mail postfix/qmgr[119]: 0FA90980F19: removed

Can you still find these log patterns in your logs? Or do you see an postfix error when it sends the bounce email?

**Comment by lub** [comment]
@Al2Klimov Are you sure the email wasn't queued and it finally got delivered or deleted from the queue? I got the bounce for the same t-online.de error 5 days after I've initially sent the email that got blocked.

**Comment by Al2Klimov** [comment]
No, I'm not. At least one eMail finally was delivered. But this answer of yours opens another three questions:

* How long shall I wait?
* Why doesn't it send the bounce immediately?
* Do you know a definitively non-deliverable recipient address for provoking a bounce (for making sure it happens)?

**Comment by lub** [comment]
It's just the default postfix behaviour as far as I can see:

http://www.postfix.org/postconf.5.html#smtp_skip_5xx_greeting
> smtp_skip_5xx_greeting (default: yes)

http://www.postfix.org/postconf.5.html#maximal_queue_lifetime
> maximal_queue_lifetime (default: 5d)


> Do you know a definitively non-deliverable recipient address for provoking a bounce (for making sure it happens)?
foo@bar.invalid bounces directly for me

**Comment by Al2Klimov** [comment]
OK, to be honest, there _are_ sending failure notifications:

```
This is the mail system at host smtp.al2klimov.de.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

(...)

<foo@bar.invalid>: Name service error for name=bar.invalid type=AAAA: Malformed
    or unexpected name server reply
```
