### ISSUE TITLE
Spurious "Authentication failed" on Rainloop since last pull

### ISSUE THREAD

**Issue by colinleroy** [Mailu/Mailu#1620]
Hi,
My docker-compose mailu 1.7 stack is automatically pull'ed and restarted every night. Since your latest push, I get spurious "Authentication Failed" when using Rainloop. 
It can happen when trying to change the displayed folder, or when clicking on an email to display it.
Insisting (by trying again) solves the issue, so it may look like a timeout issue, maybe a communication problem between containers.
Problem is I don't know how to debug this ; logs are quite uninformative.

Can you help me with this ?
Thanks in advance,
Colin

**Comment by colinleroy** [comment]
Oh, I figured it out (thanks to Roundcube showing the details of the authentication error, contrary to Rainloop) : "Authentication rate limit from one source exceeded"
I incremented AUTH_RATELIMIT in mailu.env and it works much better.

**Comment by alightgoesout** [comment]
Thanks, I had the same issue and fixed it using your solution.
Maybe it should be an entry in the FAQ? The error in rainloop makes it very difficult to pin down what the actual problem is.
