### ISSUE TITLE
can't login as admin and can't change admin password with cli 

### ISSUE THREAD

**Issue by andruccho** [Mailu/Mailu#1622]
i was using mailu 1.7 for a while, and suddenly i detected that i can't login as admin anymore. My password was enough strong and i don't think that my instance was hacked. 

I tried to change admin's password with 
`docker-compose exec admin flask mailu password myuser example.net 'password123'`
but no success, i've got an 
`sqlite3.IntegrityError: UNIQUE constraint failed: user.email`
for admin user. Changing other users passwords is working properly.

**Comment by Diman0** [comment]
Does it work when you set it via the [mailu.env file](https://mailu.io/1.7/configuration.html#admin-account-automatic-creation)?
>INITIAL_ADMIN_ACCOUNT = myuser
>INITIAL_ADMIN_DOMAIN = example.net
>INITIAL_ADMIN_PW = password123
>INITIAL_ADMIN_MODE = update

You must restart the admin container after changing the mailu.env file to pick up the new settings.

**Comment by andruccho** [comment]
No, it doesn't.
I've looked inside `main.db` and seems that it's really corrupted. Not only admin can't login, some another users also. 
Maybe there was hard reboot on mailu VM, i don't remember. I have only few users so i'd better setup mailu again from fresh install.

But how to prevent such problems again..? Is there a way to use mysql instead of sqlite?

**Comment by Diman0** [comment]
Can't you restore the main.db file from your backup?

Yes you can use a different database back-end. This is all documented on the documentation site:
Instructions for databases: https://mailu.io/1.7/database.html
In your mailu.env file you must change the DB settings in the bottom of the file
>DB_FLAVOR=mysql
>DB_USER=myuser
>DB_PW=mypassword
>DB_HOST=dburl
>DB_NAME=dbname
You can run the setup again (setup.mailu.io) to generate the new mailu.env file for you.

If you are self-hosting I'd also double check the integrity of the storage.
