### ISSUE TITLE
LibClamAV Warning: The virus database is older than 7 days!

### ISSUE THREAD

**Issue by jigsmshah** [Mailu/Mailu#1625]
I am trying to use the mailu/clamav docker image and when I run the container, it gives the  message that 'The virus database is older than 7 days'.

Is the any config chance that need to be done manually?

Any help will be appreciated.

Regards 

Sun Sep 20 23:45:02 2020 -> ClamAV update process started at Sun Sep 20 23:45:02 2020
Sun Sep 20 23:45:02 2020 -> daily database available for update (local version: 25927, remote version: 25933)
LibClamAV Warning: **************************************************
LibClamAV Warning: ***  The virus database is older than 7 days!  ***
LibClamAV Warning: ***   Please update it as soon as possible.    ***
LibClamAV Warning: **************************************************

**Comment by lub** [comment]
Normally it should update the database around 6 times per day:
https://github.com/Mailu/Mailu/blob/master/optional/clamav/start.py#L17

Did you try running the container for some time and see if it fixes itself?
Otherweise manually running `freshclam` in the antivirus container could maybe reveal some more information.

**Comment by jigsmshah** [comment]
Thanks for the reply lub..

When I started the container, it gave the same message.

I kept it running for 4 hours and after that ran feshclam and it is give an error saying freshclam is being used by another process.

Screen shots attached for your reference.

Do I need to make any changes in any of the .conf files?

Please do advise.

![image](https://user-images.githubusercontent.com/1083757/93831749-2dcd8300-fc39-11ea-911f-726354fdc5a2.png)

![image](https://user-images.githubusercontent.com/1083757/93831770-3c1b9f00-fc39-11ea-87b8-4438071d9e49.png)

**Comment by lub** [comment]
According to your screenshot you are not even using the Mailu image ...

Mailu:
https://hub.docker.com/r/mailu/clamav

What you use:
https://hub.docker.com/r/mkodockx/docker-clamav

Please either raise an issue in their repository about their image or try our image.

**Comment by jigsmshah** [comment]
Sincere apologies for the confusion.
I have started using the mailu/clamav and I am seeing that there is a file size limit for scanning.
I have a requirement to scan files that are 250 MB in size.
Is there a way to modify the size file limit in the container?
Thanks for all your help!!!

**Comment by lub** [comment]
I've opened #1646 regarding the file size and #1632 to in-cooperate freshclam (the updater) logs on stdout, so it's more obvious what's happening regarding database updates.

@jigsmshah I guess this issue can be closed then?

**Comment by jigsmshah** [comment]
Yes, please.

Thanks for all the help!!!
