### ISSUE TITLE
MASTER.CF

### ISSUE THREAD

**Issue by blainvillem** [Mailu/Mailu#1628]
Hello,

We would like to know how to change the content of the configuration file "master.cf" for postfix.

The main.cf file is changed by creating a file called postfix.cf in the folder named "overrides".

But what about master.cf?

Thanks in advance.

**Comment by lub** [comment]
Overrides for master.cf should be possible via overrides/postfix.master as far as I can see

**Comment by blainvillem** [comment]
After doing the test, I can confirm that adding a postfix.master file in the overrides folder does not change the master.cf file in the postfix container.
Of course, I did a docker-compose after making the changes.

**Comment by blainvillem** [comment]
Thanks for your help, we have found the real cause of the problem as well as its solution.

Our problem was that the line written in postfix.master was not good, we noticed it with the command: "postconf -Me "the command".

However this command worked very well directly written to the file.

So we edited the configuration file generated by default in start.py. This file can be found in each container, in the /conf/ folder.

**Comment by Diman0** [comment]
I will add the backlog label to this issue. This should be enhanced in the documentation. It does not mention that overrides for master.cf should be done via overrides/postfix.master.

If anyone would like to create a PR for this it is appreciated.
