### ISSUE TITLE
Stalebot is going crazy

### ISSUE THREAD

**Issue by sbias** [Mailu/Mailu#1641]
Looks like the stale bot is currently targeting every Issue here. Since the Team announced that it is short of time there will not be a lot of activity there. I'd like to recommend to disable stalebot for this project to not close any unresolved issues that might be out of sight than.

**Comment by lub** [comment]
Hi,

see https://github.com/Mailu/Mailu/issues/1642 for some explanation on this. We plan to review the currently stale issues before they'll get closed.

**Comment by briantopping** [comment]
There's also a longer commentary in #1451. 

Stalebot is for bugs that have been accidentally fixed, not good feature ideas that people want to share. If there is no shared "notepad of ideas", there is nowhere for new contributors to start thinking about what might be accepted. Without `/lifecycle frozen`, stalebot is just going to make the entire project stale. Careful what you wish for!

Stalebot should be removed or fixed/replaced so features can be frozen.
