### ISSUE TITLE
make ClamAV respect MESSAGE_SIZE_LIMIT

### ISSUE THREAD

**Issue by lub** [Mailu/Mailu#1646]
Currently ClamAV has hardcoded file size limits:
https://github.com/Mailu/Mailu/blob/master/optional/clamav/conf/clamd.conf#L44-L45

I think we should adjust these limits to also use MESSAGE_SIZE_LIMIT, as otherwise you have the confusing situation that big emails are allowed, but big attachments are getting blocked.

**Comment by jigsmshah** [comment]
lub,

any updates on this issue?

**Comment by Diman0** [comment]
After discussing this in the previous triage meeting, we determined this is not a bug.
The size limits are already sane limits that cover all normal circumstances.

Allowing huge emails is something that must be done with care.
The same applies to changing the configuration of clamvav. Changing the settings to a higher setting makes you vulnerable for zip bombs (emails with smaller attachments with huge files. E.g. a small zip archive with a 8GB iso file).

It should not be too easy to change the clamav settings. People who know what they do, can simply create an host mount for directly changing the clamd config file. That is a small change to the docker-compose.yml file.
