### ISSUE TITLE
Docker Swarm support?

### ISSUE THREAD

**Issue by kristiandrucker** [Mailu/Mailu#165]
Hi, please may you support docker swarm deployment?

**Comment by kaiyou** [comment]
I don't think that we need anything specific for deploying on Docker Swarm, do we? Only problem for now will be the storage part, which requires that most of the containers are on the same host or share an underlying storage layer.

**Comment by kristiandrucker** [comment]
You can use it's integrated storage driver and when a user would like to access that storage, they will simply need to create a docker container and attach it to the volume.

**Comment by kaiyou** [comment]
Okay, would we need to add anything to the current project to support Docker Swarm?

**Comment by kristiandrucker** [comment]
@kaiyou Could you rewrite docker compose to v3, so It can be deployed via docker stack.

**Comment by kaiyou** [comment]
I do not think it need rewriting, simply updating the version, I will run some tests.

**Comment by kristiandrucker** [comment]
@kaiyou Ok

**Comment by kaiyou** [comment]
I confirm that you can simply change the Compose version number to ``3`` and get it up. You will need the latest Docker version though, which is why I won't be adding this to the repository until a couple more weeks/months.

**Comment by kristiandrucker** [comment]
I will try it on my system

**Comment by curry684** [comment]
I would heartily recommend against doing this without further infrastructure like Ceph or Gluster in place, or at the very least NFS for database and mailboxes. Keep in mind that a host going down means the affected containers will be rescheduled on other hosts, and that effectively will mean your system will still be up then with empty configuration, or empty mailboxes.
