### ISSUE TITLE
Is there any API documentaion available?

### ISSUE THREAD

**Issue by nahidhasan94** [Mailu/Mailu#1650]
i am looking for Mailu API documentaion. Can you referance any.

**Comment by zeromsi** [comment]
I'm also looking for that! Can anyone suggest any reference or any doc.

**Comment by lub** [comment]
Are you looking for the internal API that postfix/dovecot/nginx use or an external? Because the latter doesn't exist (see #445)

Besides REST APIs there is https://mailu.io/master/cli.html and eventually #1604
