### ISSUE TITLE
"Received:" line filtered inside attachment

### ISSUE THREAD

**Issue by vbence** [Mailu/Mailu#1660]
### Environment
 - [x] docker-compose
 - [ ] kubernetes
 - [ ] docker swarm

### Versions
1.7

## Description
The feature mentioned here: https://github.com/Mailu/Mailu/issues/466 and here https://github.com/Mailu/Mailu/issues/191 is affecting ATTACHMENTS if they are sent as plaintext (7-bit). This prevents using services like SpamCop which consume the original message's headers.

## Replication Steps
Forward yourself any previously received email as attachment and check its source upon retrieval. The original message's `Received:` lines will be replaces.

## Expected behaviour
The pattern replacing's scope should be the HEADER of the mail message. It should stop on the first empty line.

**Comment by lub** [comment]
Hi @vbence,

are you able to create a PR for this? Maybe it also makes sense to have a look at #1448 for some notes on general imporvements of the 'Received:' overwrite.

**Comment by vbence** [comment]
Hi @lub let me take a look...

**Comment by vbence** [comment]
Thanks for the pointers, it looks like this erroneous behavior is from postfix, the configuration specified in `outclean_header_filter.cf` will be also applied inside the message (opposed to only the headers).

Besides the behavior added by #1448 I would add a third option to disable this line altogather.
