### ISSUE TITLE
Support more password schemes from passlib

### ISSUE THREAD

**Issue by Diman0** [Mailu/Mailu#1662]
## Before you open your issue
- [x] Check if no issue or pull-request for this already exists.
- [x] Check [documentation](https://mailu.io/master/) and [FAQ](https://mailu.io/master/faq.html). (Tip, use the search function on the documentation page)
- [x] You understand `Mailu` is made by volunteers in their **free time** — be conscise, civil and accept that delays can occur.
- [x] The title of the issue should be short and simple. It should contain specific terms related to the actual issue. Be specific while writing the title.

### Description
Mailu uses the passlib python library for handling password hashes. The password hashes that can be used must be passed to the constructor of passlib. These are currently the [supported hashes](https://github.com/Mailu/Mailu/blob/90984c4d2bd8b0f82559f26d9837a7454626438a/core/admin/mailu/models.py#L365).

```
    scheme_dict = {'PBKDF2': "pbkdf2_sha512",
                   'BLF-CRYPT': "bcrypt",
                   'SHA512-CRYPT': "sha512_crypt",
                   'SHA256-CRYPT': "sha256_crypt",
                   'MD5-CRYPT': "md5_crypt",
                   'CRYPT': "des_crypt"}
```

In the mailu chat someone asked for support SSHA512 (salted ssh512).  It would be nice if we could support more hashing algorithms. This enables users to export/import users from other systems that use these hash algorithms.

#### What must happen for implementing this enhancement request?
1. modify requirements.txt to use a newer version of passlib to have support for newer hashes. Version 1.7.1 of passlib is currently used. Version 1.7.3 also has support for salted sha512.
2. modify models.py with additional hash algorithms. eg.
```
    scheme_dict = {'PBKDF2': "pbkdf2_sha512",
                   'BLF-CRYPT': "bcrypt",
                   'SHA512-CRYPT': "sha512_crypt",
                   'SHA256-CRYPT': "sha256_crypt",
                   'MD5-CRYPT': "md5_crypt",
                   'CRYPT': "des_crypt",
                   'SSHA256': "ldap_salted_sha256"
                   'SSHA512': "ldap_salted_sha512"  }
```

The proper solution is probably to make it possible to configure the scheme_dict via the Mailu.env file. This way you can still add support for other hashes via the mailu.env file.

**Comment by nextgens** [comment]
I've added a comment on https://github.com/Mailu/Mailu/issues/1194#issuecomment-761564557 regarding introducing new DoS vectors.

It may be worth documenting when new hash schemes are added.

**Comment by nextgens** [comment]
@Diman0  Please review #1753 ; it allows for all hash types supported by passlib to be used

**Comment by Diman0** [comment]
I'm closing this PR. It is not required anymore with the changes from nextgens PR1753..
