### ISSUE TITLE
TLS / SSL termination in service (container) apart from Nginx redirections logic

### ISSUE THREAD

**Issue by tiangolo** [Mailu/Mailu#167]
# What

I would like to set up the TLS / SSL termination in a service / container apart from the current Nginx that handles the redirections and `proxy_pass` to the other components of the system.

For this I would keep the redirects logic in the current Nginx container, but I would create an additional Nginx container with the TLS / SSL part and the redirection of HTTP to HTTPS.

This would allow setting up a different TLS / SSL termination system by replacing only that part but keeping the rest of the Nginx logic.

# Why

As HTTPS needs to handle the certificates and establish the connection before giving the hostname requested, having a multi host (multi domain, "virtual hosts") set-up would not be possible with the current configuration, as the Nginx container has to handle the TLS connections, so it has to listen on the public 443 port.

If there was an additional container doing just the TLS / SSL termination, it would be easier to replace only that component by a custom system. 

# Example

For example, using Rancher, it would be possible to configure a load balancer that handles all the HTTPS connections and the certificates and does TLS / SSL termination for Mailu and for (possibly) other services running on the same host.

Also, it could integrate directly with the Let's Encrypt Rancher stack.

# Proposal

Is this something that you would like / accept?

I can make a PR with the changes if that is something that could be "desirable" or acceptable for the project.

**Comment by kaiyou** [comment]
I don't know much about Rancher, but I have been looking for some time at possible solutions to solve that TLS nightmare. Of course, having a single TLS termination is one option that I would be glad someone could work on.

One problem however is terminating STARTTLS for IMAP and SMTP, which sounds quite difficult and would probably cause issues when it comes to only accepting authentication from encrypted connections for instance. One could argue that STARTTLS is terrible and Mailu should drop any support, but I am not ready to get down that road yet.

**Comment by kaiyou** [comment]
I just had a look at rancher. If you can integrate this without dropping support to bare Docker, that would be fine, but as it requires some advanced setup in the first place, I would prefer to avoid making it the default option.

**Comment by tiangolo** [comment]
So, what I would like to do is only separating the Nginx (`http`) service. I would let IMAP and SMTP continue as they are. I would only separate the HTTP internal redirection (from `/` to `/webmail`, `proxy_pass` from `/webmail` to the Roundcube service and `proxy_pass` from `/admin` to the Mailu admin service) and the HTTPS part (only the HTTPS handling, the first section of the Nginx config).

Right now, the `http` service (Nginx) does HTTP redirection AND TLS termination for HTTPS. But TLS for IMAP and SMTP is handled by those services directly. 

I don't know a good way to do TLS termination for email protocols, I think maybe there is a plug-in for Nginx or HAProxy, but I wouldn't touch that. I would only touch the HTTPS part.

---

BTW, IMHO, you shoudn't drop STARTTLS if you have it working. Email is one of those systems with some big backward compatibility requirements / issues.

---

I actually don't plan on "adding support" for Rancher directly, but rather just separate the `http` (Nginx) components in 2 concerns (HTTPS and redirects). That way, for someone deploying to Rancher (or anything else) can replace the HTTPS part alone.

This would also help someone that wants to fine tune the HTTPS termination (enable and disable ciphers, etc) without risking the internal redirects functionality.

**Comment by kaiyou** [comment]
Ok, then there is already a `FRONT` environment variable to decide which front image has to run. You could basically build a separate front image without HTTPS or the HTTPS redirection. I am not sure this is the cleanest way but it is definitely the most straightforward.

Also, as I plan on working hard on the full dynamic configuration in the next couple of weeks, probably this won't be an issue anymore by mid-year.

**Comment by tiangolo** [comment]
Cool! 

I was thinking on creating a separate service that would just handle the HTTPS and redirect to the current Nginx (and the current Nginx wouldn't have the HTTPS logic any more). So, in a "normal" scenario there would be the Nginx `FRONTEND` service and an additional Nginx service for HTTPS (that could be enabled with a `HTTPS` env var) just "`proxy_pass`ing" everything to the original `FRONTEND` Nginx but doing the HTTPS TLS termination.

In the custom scenario, there would be a `FRONTEND` env var set to `nginx` but the `HTTPS` env var would be set to `none`.

The possible advantage in separating that service in two services instead of having just another `FRONTEND` with almost all the same code would be to "keep it [DRY](https://en.wikipedia.org/wiki/Don't_repeat_yourself)".

But if it makes more sense for you, I can just make a copy of the current `nginx` and remove the HTTPS part, making it an alternative `FRONTEND`. The only caveat I see is that there would be a need to update both Nginx configs when updating something to keep both versions in sync.

---

What would you prefer? Alternative `FRONTEND` or additional `HTTPS`?

**Comment by kaiyou** [comment]
In the near future, I believe I would prefer an alternative `FRONTEND`, to avoid shipping a new `docker-compose.yml` with even more confusing options. Adding complexity at this point has become a burden in the projet and I would like to address the dynamic configuration before we start adding new optional services.

**Comment by tiangolo** [comment]
Perfect, I will do it that way (it's actually easier too).
