### ISSUE TITLE
Postfix logs 

### ISSUE THREAD

**Issue by thadjbullet** [Mailu/Mailu#1674]
Hi. I just checks the postfix pod logs and found some confusing stuff.
![image](https://user-images.githubusercontent.com/17276356/97816652-b4996500-1ca7-11eb-90cc-eff9847af642.png)
I never sends this emails. 
Is this mean that mailu sends emails from my instance?

**Comment by lub** [comment]
Did you try to grep for 11EB02C252D or what messages are you exactly talking about? The log is incomplete.

Also please try to post the text directly instead of screenshots, as it's easier to work with. You can put it in a code block by enclosing it inside three back ticks:

\```
long
spammy
log
messages
\```

**Comment by thadjbullet** [comment]
I talking about different email addresses in log like
```2020-11-02T13:52:02.681188429Z Nov 02 13:52:02 mail postfix/smtp[236167]: ECE922C5AD5: to=<betinahlamb@cs.com>, relay=mx-aol.mail.gm0.yahoodns.net[67.195.204.75]:25, delay=50544, delays=13259/37282/1.9/0.11, dsn=4.7.0, status=deferred (host mx-aol.mail.gm0.yahoodns.net[67.195.204.75] said: 421 4.7.0 [TSS04] Messages from 135.181.73.105 temporarily deferred due to user complaints - 4.16.55.1; see https://postmaster.verizonmedia.com/error-codes (in reply to MAIL FROM command))```
Complete log in attachment
[postfix.log](https://github.com/Mailu/Mailu/files/5475483/postfix.log)

**Comment by lub** [comment]
From the log and a short test by myself you currently have an open relay. This means your setup accepts emails to any recipient and subsequently acts as a relay and sends out these spam emails.

The most sensible approach is probably shutting down your postfix, checking you configuration for common pitfalls (e.g. check your SUBNET and RELAYNETS env vars, whether you have enabled ipv6 #1578, maybe you have some flawed NAT in your network, ...) and emptying your queue directory.

After starting postfix again you can use something like https://mxtoolbox.com/diagnostic.aspx to verify you don't have an open relay anymore.

For reference your mail server on mail.zona.media currently accepts this:

```
mail from:asef@invalid
250 2.0.0 OK
rcpt to:bsef@invalid
250 2.1.5 Ok
```

It currently doesn't perform any check whether the domain is valid, if the message is spam or if the email is even deliverable on your local system. A default Mailu setup normally shouldn't behave like this.

**Comment by thadjbullet** [comment]
I see, thx
