### ISSUE TITLE
clarify database documentation

### ISSUE THREAD

**Issue by lub** [Mailu/Mailu#1675]
https://mailu.io/master/database.html

We should change the following points:
* 'Mailu Postgresql' is deprecated and shouldn't be used anymore
* describe how you can actually migrate your data (either by reconfigure & reimport all settings or via sql dump?)
* document the DB_* env vars

**Comment by lub** [comment]
The setup utility already uses the env vars, they are just not mentioned in the documentation as far as I can see:

```
DB_FLAVOR=postgresql
DB_USER=dbuser
DB_PW=dbpwd
DB_HOST=dburl
DB_NAME=dbname
```

**Comment by bmiller59** [comment]
@lub   Hi! Thanks for this great project.

I need to migrate my mail server and I would like to set it up to use an external postgres instance to future proof it. Would it be possible to sketch out the right migration method here, to be more fully elaborated in the docs later? 

I was shocked to see how little data was in my daily pg_dumpall of my postgres database. ;) It is not clear where data for various services is stored and how to save it to a daily backup (e.g. for transfer to a safe offsite location), and then how to to restore it if needed.

Also, if I do migrate should I start my new server using 1.8-rc, or 1.7?

Thanks for any pointers in the short term.

**Comment by ghostwheel42** [comment]
@bmiller59 #1604 will add a good way to dump & restore the configuration.

**Comment by bmiller59** [comment]
@ghostwheel42 Thanks for that! From my quick review, this PR is about the config of mailu entered in the mailu admin interface, correct? 

Do you know how I can also migrate roundcube and other services configuration/data (e.g. filters and other settings) so that a new instance will be an exact mirror of an existing instance, for example if it needs to be restored or migrated? Thank you.

**Comment by ghostwheel42** [comment]
@bmiller59 Yes, #1604 is only about the mailu configuration and not data.
Mailu stores all it's configuration and data in the storage path you specified in the setup wizard.
When using the docker-compose setup for example, you would copy docker-compose.yml, mailu.env and the storage path to clone or backup the instance.
Alex

**Comment by bmiller59** [comment]
@ghostwheel42 Thank you for clarifying. So, then when it comes to migration to a new server, it seems important to separate the migration step from the upgrade step. For example:

To migrate to new machine:
1. Copy the copy docker-compose.yml, mailu.env and the storage path to the new machine
2. Make sure `MAILU_VERSION` is the same (1.7) and same mailu folder is selected and do `docker-compose up -d`
3. Confirm everything is working and migrate DNS setting

To upgrade (later):
Follow the steps that this ticket will describe. :)

Does that seem right?

**Comment by ghostwheel42** [comment]
@bmiller59 I think separating an upgrade from a migration is always a good idea. :) Backups are also a good idea.
The three steps to migrate look good to me - take care to set the right permissions when migrating the storage (for example: use rsync with --numeric-ids)
Upgrading is just a `docker-compose pull` as described here: https://mailu.io/1.8/maintain.html#upgrading-the-mail-server
Alex

**Comment by bmiller59** [comment]
@ghostwheel42  I'm glad upgrading is so simple! I was concerned there were some data migration steps needed. It seems the only extra step is to switch to an external postgres database before it is removed from the project entirely in some future version.

**Comment by Diman0** [comment]
> https://mailu.io/master/database.html
> 
> We should change the following points:
> 
>     * 'Mailu Postgresql' is deprecated and shouldn't be used anymore
> 
>     * describe how you can actually migrate your data (either by reconfigure & reimport all settings or via sql dump?)
> 
>     * document the DB_* env vars

Point 1 and 3 are addressed by PR #1831.
Point 2 is addressed by PR #1604. With this PR you can completely export/import your configuration via the new import/export commands.  

I will close this issue once those 2 PRs are merged.

**Comment by Diman0** [comment]
Scratch that. I though we had documentation on how simple moving data or creating a backup is. As stated by others it is sufficient to create a copy of your data folder. You could use rsync for this. 

This should indeed be documented and it currently is not. The things from the opening post will be documented once those PRs are merged. I think we need one more PR to add documentation on how to create a backup and how to restore it.

I think a section in the FAQ for how to backup or migrate mailu is sufficient. What do you think?

**Comment by parisni** [comment]
`duplicity` is a great solution for backup, equivalent to rsync, but with async encryption and compatible with object storage. I can write a documentation and with example scripts. Just let me know

**Comment by Diman0** [comment]
I think the most logical location would be the maintain.rst file (https://mailu.io/master/maintain.html). Creating a backup is a maintenance task.
In here we could first describe what is required to make a backup in general and how to restore a backup. After that we could provide two examples. One with rsync, and one with duplicity.

Another option is that we create a new FAQ entry with the info:
- how to create a backup in general and how to restore it
- how to backup with rsync
- how to backup with duplicity

**Comment by parisni** [comment]
On Wed Jun 30, 2021 at 11:55 AM CEST, Dimitri Huisman wrote:
> the most logical location would be the maintain.rst file
> Another option is that we create a new FAQ entry with the info:

I would'nt use the FAQ for informations that feat well in dedicated places and guess having a clear hierarchy as maintain.rst is better.

**Comment by parisni** [comment]
What about providing a dedicated docker image focused on dumps ? Also we could migrate the postgres dump together with emails. My guess is dump need tons of configuration and this might be easier to setup it on the host with some guidance
Nicolas paris
