### ISSUE TITLE
Can we have the exact ports/environment vars/volume mounts and certificate mounts details of each container.

### ISSUE THREAD

**Issue by vipinjn24** [Mailu/Mailu#1678]
Hi,

i have been trying to deploy mailu on bare metal kubernetes with metallb and traefik.
But it seems if i try to deploy the containers individually by separating their storage and environmen, then it will not start its services.
for e.g. if i try to run spamd by creating an individual container then it will not start.
however when i use config map provided and the storage mapping provided as in the original files and just updating the values then it will start its operations.

so now if i try to deploy the whole stack the admin will not run.

Now i want to deploy this stack witout front (nginx) and webmail (i want to deploy it separately) container and use traefik as proxy for port 80 and 443 for admin interface and metallb for smtp and imap and pop ports.

I also saw that dovecot and postfix are not provided with the certificates to listen on secure ports, so how would we put them up.

Regards,
Vipin

**Comment by lub** [comment]
> Now i want to deploy this stack witout front

front is designed as central exposed component and thus exposes all required ports, all certificates and is handling the authentication. Mailu doesn't work without front.

> for e.g. if i try to run spamd by creating an individual container then it will not start.
> so now if i try to deploy the whole stack the admin will not run.
Do you have any error messages or log files?

**Comment by vipinjn24** [comment]
@lub Please see this documentation part.
[https://mailu.io/1.7/reverse.html#disable-completely-mailu-reverse-proxy](Disable reverse proxy)
