### ISSUE TITLE
I can receive mail, but can't send it.

### ISSUE THREAD

**Issue by schristy189** [Mailu/Mailu#1682]
Mailu version 1.7

Hi, I'm trying to host email on my personal website. I've set up Mailu with docker-compose and can access the admin panel and webmail and receive mail from gmail, but I can't send it. I don't get any errors from the UI or in `docker-compose logs`, the mail just fails to show up at it's destination.

I *can* send mail between users on the domain, for instance from admin@example.com -> user@example.com.

I am aware that this is probably a DNS issue, so here are the DNS records that I've entered (with the specifics changed).

```
Type          Host             Value
A Record      @                12.34.56.78
CNAME Record  mail             example.com.
TXT Record    @                v=spf1 mx a:mail.example.com -all
TXT Record    _dmarc           v=DMARC1; p=reject; rua=mailto:admin@example.com; ruf=mailto:admin@example.com; adkim=s; aspf=s
TXT Record    dkim._domainkey  v=DKIM1; k=rsa; p=7vBWvdT8F8OZqo2xLET8egan0fGtWWR0ZJqABPK2IRIwIe9VLwwBkYqaNjTzOXiHBNsgAx6iEdGwlubAXCtcf177B+AAlSng5XgFMVBSudhl1uqyK4ZOVoQHJtvqLWS/620SNY99rD3DTlyccv8xxC/MSldb6blpFAD3eWtrQj4zW6MOoWIEF4gOZMi8nAO6PGxdJsvezDXVpsLUBBpH0zha
MX Record     @                mail.example.com.
```

I would appreciate any help, insight, or troubleshooting steps I can take to fix this. I'm loving Mailu so far in spite of this issue!

**Comment by ofthesun9** [comment]
Your internet provider might filter your outgoing connection to port 25.
Can you share the logs of the smtp service (docker-compose logs -f smtp) when you try to send an email ?

**Comment by schristy189** [comment]
Thanks for the information, it turned out that the VPS I was using (AWS) was blocking port 25. After a few days of support tickets it looks like they will not remove this restriction. Do you know of any way around this, for instance can I use a different port or maybe port forward to an IP that doesn't have smtp restrictions? If not, I'll probably just switch to a different VPS and hopefully have some luck with them.

**Comment by Diman0** [comment]
The short answer is no. Port 25 is the port for sending email. This port must be opened in AWS to send email. If you own another email server that listens on a different port than port 25, then you could use this email server as a smart host. See setting relayhost in the [configuration reference](https://mailu.io/1.8/configuration.html#mail-settings).
