### ISSUE TITLE
update roundcube and carddav plugin

### ISSUE THREAD

**Issue by lub** [Mailu/Mailu#1692]
roundcube mailu master: 1.4.6
roundcube current: 1.4.9

carddav mailu master: 3.0.3
carddav current: 4.0.2

Both can be configured in `webmails/roundcube/Dockerfile`, but I don't use roundcube so I can't easily test it.

**Comment by sholl** [comment]
I am willing to create a PR since I use this combination heavily.

**Comment by sholl** [comment]
Since ths issue has a security-label, is there any chance to get a backport to 1.7?

**Comment by betaxab** [comment]
@sholl you should create a clean branch!

**Comment by nextgens** [comment]
This was done in #1844
