### ISSUE TITLE
Configurator and test server are failing.

### ISSUE THREAD

**Issue by MakerMatrix** [Mailu/Mailu#1701]
I'd like to use the configure tool to make a docker compose file.

It's not working - the server returns an error when you submit.  Same thing happens when you try adding a user to the test server.

**Comment by Setsuneh** [comment]
I confirm, error 500 on setup.mailu.io. Is it possible to know when it will be fixed ?

**Comment by ilovelinux** [comment]
I don't see any reason to use a webpage to create a docker config. I think that a script would be better.

**Comment by mlow** [comment]
I'm guessing this is due to their redis server being down, because I just ran `docker run -it --rm -p 8080:80  mailu/setup:1.7` and got the 500 error when submitting the form:

```redis.exceptions.ConnectionError: Error -2 connecting to redis:6379. Name does not resolve.```


After spinning up a redis container: `docker run --name redis -d redis`
And then linking it to the setup container:  `docker run --link redis -it --rm -p 8080:80 mail/setup:1.7`

Then it worked :)

**Comment by MakerMatrix** [comment]
> I don't see any reason to use a webpage to create a docker config. I think that a script would be better.

Maybe you don't recognize that the documentation points you to that tool as a means to bootstrap a docker_config.yml which can be customized later.  Anyway, I thought they would like to know their service is down.

**Comment by lub** [comment]
I suspect it's because the disk is full, because of dangling images. There is an open PR to fix this (https://github.com/Mailu/infra/pull/9). I've notified some people with SSH access, but they are recently rather busy. Sorry for the inconvenience.

**Comment by lub** [comment]
The problem was fixed yesterday. Can someone that was affected confirm?

**Comment by RDiSa** [comment]
Yes, today I used it... Thanks.

Il giorno gio 3 dic 2020 alle ore 15:45 lub <notifications@github.com> ha
scritto:
