### ISSUE TITLE
Update roundcube to v1.4.x latest for Mailu v1.7

### ISSUE THREAD

**Issue by codeagencybe** [Mailu/Mailu#1703]
To be able to help you best, we need some more information.
### Environment
 - [x] docker-compose
 
### Versions
1.7

## Description
Can Mailu v1.7 also run with latest roundcube v1.4.x that is included with Mailu 1.8? 

## Expected behaviour
update roundcube seperate from Mailu

**Comment by sholl** [comment]
yes, you can selectively run the webmail-roundcube-image from master or v.1.8 while the rest of mailu runs on v1.7. I do that on ly production as well.
