### ISSUE TITLE
[HELP] Looking for advice getting setup using network switch

### ISSUE THREAD

**Issue by davidjohnbell** [Mailu/Mailu#1704]
### Environment
docker-compose

## Question
Hello, I'm looking for some help getting Mailu setup at my personal office. I have a public business IP address and have configured my router as such. From my router I have a network switch and then a server machine running Ubuntu server. When using your `setup.mailu.io` tool I entered in my public IPv4 address but I suspect this is wrong because I get a `cannot bind to <my-static-business-ip>:995` error. Should I be using my 192 address and port forward? Thankyou for any advice and the good work you've done.

**Comment by mlow** [comment]
Yes, port forwarding would be required in this scenario.

**Comment by davidjohnbell** [comment]
Thanks, if I can bug you a little more I have another question otherwise I'm happy to close this issue/question. I have a domain & wildcard SSL that I've purchased using NameCheap. I can choose the `cert` option and put my certificates in the `certs` folder or does the system require `letsencrypt` certs?

**Comment by mlow** [comment]
Yes (although I have not done so myself); the key should be named `key.pem` and the certificate should be named `cert.pem`, as documented here: https://mailu.io/1.7/compose/setup.html#tls-flavor

**Comment by davidjohnbell** [comment]
Thankyou @mlow, I appreciate your time.

**Comment by davidjohnbell** [comment]
@mlow - Do you mind if I ask you another question? How would I go about running other services alongside Mailu, either on the host machine or in a docker container? In particular, Mailu uses ports 80 and 443 for admin and webmail but I want to run an API alongside Mailu. From what I gather I would need to set up a `nginx` reverse proxy to my services, including Mailu, but the `docker-compose.yml` describes an `nginx` container already. What should I do?

**Comment by ofthesun9** [comment]
You can have a look at https://mailu.io/master/reverse.html#have-mailu-web-frontend-listen-locally 
Once mailu is no longer using ports 80 and 443, you can **add** another reverse proxy. (Keep the mailu nginx service, this is the frontend of all internal services (imap, pop,  smtp , web))
