### ISSUE TITLE
Every mail is tagged by RSPAMD as RCVD_NO_TLS_LAST

### ISSUE THREAD

**Issue by inconis** [Mailu/Mailu#1705]
Thank you for opening an issue with Mailu. Please understand that issues are meant for bugs and enhancement-requests.
For **user-support questions**, reach out to us  on [matrix](https://matrix.to/#/#mailu:tedomum.net).

To be able to help you best, we need some more information.

## Before you open your issue
- [x] Check if no issue or pull-request for this already exists.
- [x] Check [documentation](https://mailu.io/master/) and [FAQ](https://mailu.io/master/faq.html). (Tip, use the search function on the documentation page)
- [x] You understand `Mailu` is made by volunteers in their **free time** — be conscise, civil and accept that delays can occur.
- [x] The title of the issue should be short and simple. It should contain specific terms related to the actual issue. Be specific while writing the title.

### Environment
 - [x] docker-compose
 - [ ] kubernetes
 - [ ] docker swarm

### Versions
My version is 1.7

## Description
Every mail received also from GMAIL is marked by RSPAMD as RCVD_NO_TLS_LAST.
Is normal because I think that mail from famous provider use TLS 

## Replication Steps
Simply send an email from gmail anch check RSPAMD history

## Expected behaviour
I expected to recieve an email with TLS in each step.

## Thanks
Thank you very much for this wonderful project that makes it possible for everyone to build a mail server

**Comment by nextgens** [comment]
The faulty code is at https://github.com/rspamd/rspamd/blob/0b88d35b45dcea804e47a9236a5e0244b9b70c4e/rules/misc.lua#L263 ... It should filter out LMTP
