### ISSUE TITLE
Intermittent "Authentication Failed"

### ISSUE THREAD

**Issue by naanlizard** [Mailu/Mailu#1707]
## Before you open your issue
- [ x] Check if no issue or pull-request for this already exists.
- [x ] Check [documentation](https://mailu.io/master/) and [FAQ](https://mailu.io/master/faq.html). (Tip, use the search function on the documentation page)
- [x ] You understand `Mailu` is made by volunteers in their **free time** — be conscise, civil and accept that delays can occur.
- [ x] The title of the issue should be short and simple. It should contain specific terms related to the actual issue. Be specific while writing the title.

### Environment
 - [x ] docker-compose
 - [ ] kubernetes
 - [ ] docker swarm

### Versions
To find your version, get the image name of a mailu container and read  the version from the tag (example for version 1.7).
```
1.7 on Ubuntu 20.04
```
## Description
Further explain the bug in a few words. It should be clear what the unexpected behaviour is.  Share it in an easy-to-understand language.

Occasionally via both SMTP and IMAP I am getting "Authentication failed" - obviously bad when I need to send a  bunch of emails and half of them get me an auth failed warning. 

## Replication Steps
Follow all the steps on the config generator, spin it up in docker

## Expected behaviour
No auth failures when I am logged in to webmail, on my android imap client (gmail), or sending via smtp

## Logs
Will add logs when I can sort through the spammers trying to connect filling the logs (shouldn't be at a level that causes trouble, nor am I running on bad hardware - brand new 16c CPU, tons of RAM, etc)

**Comment by TomasVojacek** [comment]
I have run to similar problem. My guess that it is related to login rate limiting.
But I did not find anything in logs.

**Comment by naanlizard** [comment]
We've moved away from using mailu since there's been no response at all on this

**Comment by nextgens** [comment]
#1910 went in 1.8 ... this is most likely solved
