### ISSUE TITLE
Logging with Fluentd and ELK stack

### ISSUE THREAD

**Issue by phoen1x** [Mailu/Mailu#171]
I like to propose to add [Fluentd](http://www.fluentd.org/) and a [ELK stack](https://www.elastic.co/webinars/introduction-elk-stack) for Logging. This seems to be related to the currently open issues #116. 

Regards,
Thomas

**Comment by kaiyou** [comment]
As stated already in a couple issues (https://github.com/Mailu/Mailu/issues/85 for instance), logging in a Docker environment is not the responsibility of applications but that of Docker.

If you wish to log to ELK or Graylog or Fluentd, you should use the appropriate log driver in your Docker configuration.

**Comment by muhlemmer** [comment]
This was opened in error, as it is already included in the FAQ.
