### ISSUE TITLE
Which command allows me to send an email?

### ISSUE THREAD

**Issue by Yazur-admin** [Mailu/Mailu#1715]
Hello,

I would like to send a mail from the host machine using a command such as "mail" with mailutils through a container.

For this I would like to do "Docker exec -it "Name of container" "the command".

Why do I want to do this?
I have installed two anti-rootkit packages on the host machine and would like to receive the daily result of the checks by mail.

Yours sincerely, Maxime.

**Comment by ghostwheel42** [comment]
Hi,

you should use SMTP to send mail from the host machine. Install a small mailer (ssmtp or msmtp) and configure it for smtp auth and point it to your mailu server’s submission port. 

Alex

**Comment by Yazur-admin** [comment]
> Hi,
> 
> you should use SMTP to send mail from the host machine. Install a small mailer (ssmtp or msmtp) and configure it for smtp auth and point it to your mailu server’s submission port.
> 
> Alex

Nice, SSMTP + mailutils = GOOD :+1:

**Comment by alexanderadam** [comment]
> Nice, SSMTP + mailutils = GOOD +1

So this issue can be closed then?
