### ISSUE TITLE
Docker update doesn't upgrade Postfix configuration, SMTP server fails

### ISSUE THREAD

**Issue by benbucksch** [Mailu/Mailu#1721]
### Environment
 - [x] docker-compose

### Versions
```
$> docker ps -a | grep mailu
mailu/postfix:master
```
Pulled 2021-01-06

## Replication Steps
1. Have a working mailu setup
2. Several months pass
3. Due to the Dovecot security bug, update the Docker images, using `docker-compose pull`
4. Restarted the services using `docker-compose up; docker-compose down; docker-compose up &`
5. Test the setup by logging in on the webfrontend, and confirming that I can log in and I see my emails, so I presume everything is peachy.

## Actual behavior

* I see existing mail. I can poll for new mail, and I do not get any errors, so all day long, I presumed everything is fine.
* I don't get new emails in my inbox. But maybe nobody wrote me. 
* I get reports from other users on the server who see error message `SMTPAuthenticationError: 451 4.3.2 Internal server error` when trying to send email.

## Expected behaviour
* Can send mail
* New mail arrives

## Logs
After looking at the `smtp` container log, the problem cause becomes clear:
```
# docker logs mailu_smtp_1 
postconf: fatal: -Me, -MX or -M# requires service_name/type
postconf: fatal: -Me, -MX or -M# requires service_name/type
Jan 06 10:53:49 mail postfix[107]: Postfix is running with backwards-compatible default settings
Jan 06 10:53:49 mail postfix[107]: See http://www.postfix.org/COMPATIBILITY_README.html for details
Jan 06 10:53:49 mail postfix[107]: To disable backwards compatibility use "postconf compatibility_level=2" and "postfix reload"
Jan 06 10:53:57 mail postfix[322]: Postfix is running with backwards-compatible default settings
Jan 06 10:53:57 mail postfix[322]: See http://www.postfix.org/COMPATIBILITY_README.html for details
Jan 06 10:53:57 mail postfix[322]: To disable backwards compatibility use "postconf compatibility_level=2" and "postfix reload"
Jan 06 10:53:57 mail postfix/postfix-script[364]: fatal: missing 'postlog' service in master.cf - run 'postfix upgrade-configuration'
Jan 06 10:53:58 mail postfix/postfix-script[365]: fatal: Postfix integrity check failed!
```

## Fix

Not surprisingly, `overrides/postfix/master.cf` exists. The update adds the following lines to the end:
```
proxywrite unix -       -       n       -       1       proxymap
#smtp      inet  n       -       n       -       1       postscreen
#smtpd     pass  -       -       n       -       -       smtpd
#dnsblog   unix  -       -       n       -       0       dnsblog
#tlsproxy  unix  -       -       n       -       0       tlsproxy
postlog   unix-dgram n  -       n       -       1       postlogd
```

I don't remember ever making any modifications to it. IIRC, it comes from mailu standard docker-compose repo. Probably, this file should not have been outside the docker image, but be part of it, and be updated together with the image.

## Importance

The primary reason why I want to use mailu and docker is that I do *not* want to take care of the configuration, nor about updates. I want to configure it once, and then I want it to work for 10 years. Updates obviously need to happen, for security reasons, spam filter updates etc., but that's why I use a container, so that the maintainer can take care of this and I can take care of other things.

If a docker image update (which I did purely for security reasons, because Dovecot has a security bug), and it breaks my configuration, then that defeats the entire purpose of mailu for me.

Most Linux distributions take care of this in some way, to update the configuration - simply because it's necessary, and admins cannot manually fix configs on every update. In docker, it should be even easier, because the configuration is separate, in the `.env` file and in other dedicated files.

Whatever the philosophy, a smooth, automatic upgrade is simply a necessity for every software package, be it Windows GUI apps or Linux servers or docker images.

**Comment by benbucksch** [comment]
2 fixes:
* Put files like `postfix/master.cf` inside the docker image, so that it gets updated together with the application, and the versions are consistent.
* Create a mechanism to update uswer configuration when necessary during updates.

**Comment by benbucksch** [comment]
ping

**Comment by lub** [comment]
> Not surprisingly, overrides/postfix/master.cf exists.

This should actually very surprising, because Mailu doesn't read that file as far as I can see and generally doesn't write into the overrides directory:
https://github.com/Mailu/Mailu/blob/1.7/core/postfix/start.py#L41-L43

Could you please share the volumes you have specified in your docker-compose.yml? The setup utility only generates a mount for /overrides as far as I can see, but it sounds like you have mounted /etc/postfix

It should look something like this:
```
  smtp:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}postfix:${MAILU_VERSION:-1.7}
    restart: always
    env_file: mailu.env
    volumes:
      - "/mailu/overrides:/overrides"
    depends_on:
      - front
```

> Put files like postfix/master.cf inside the docker image, so that it gets updated together with the application, and they are consistent.

The proper master.cf is in the image.
https://github.com/Mailu/Mailu/blob/1.7/core/postfix/Dockerfile#L16
https://github.com/Mailu/Mailu/blob/1.7/core/postfix/conf/master.cf

> Create a mechanism to update uswer configuration when necessary during updates.

How should this be possible? Mailu can't just guess what the user wants to override.

**Comment by benbucksch** [comment]
>>    Not surprisingly, overrides/postfix/master.cf exists.
> This should actually very surprising, because Mailu doesn't read that file as far as I can see and generally doesn't write into the overrides directory

hm, could I really have been that stupid to have created an override for `master.cf` and forgotten about it? Indeed, my docker-compose.yml contains:
```
  smtp:
    image: mailu/postfix:$VERSION
    ...
    volumes:
      - "$ROOT/overrides:/overrides"
      - "$ROOT/overrides/postfix/master.cf:/conf/master.cf"
```

Ah, I remember now. The `reject_authenticated_sender_login_mismatch` rule was rejecting my mail from the other SMTP server on that domain, and I had to override it.

I'm sorry to have bothered you with a misguided bug report, when the problem was really created by myself. Sorry that I wasted your time!

RESOLVED INVALID REPORTED WAS STUPID

**Comment by lub** [comment]
> RESOLVED INVALID REPORTED WAS STUPID

With a mail server you are running one of the - in my experience - most bothersome pieces of server software. You are definitively not stupid :)

**Comment by benbucksch** [comment]
Thanks for your kindness, and thanks for replying to the bug reports here. It's really nice to see that somebody cares about them. Thank you.
