### ISSUE TITLE
Dovecot/IMAP slow to get mail (how to debug?)

### ISSUE THREAD

**Issue by dominick-han** [Mailu/Mailu#1723]
Thank you for opening an issue with Mailu. Please understand that issues are meant for bugs and enhancement-requests.
For **user-support questions**, reach out to us  on [matrix](https://matrix.to/#/#mailu:tedomum.net).

To be able to help you best, we need some more information.

## Before you open your issue
- [X] Check if no issue or pull-request for this already exists.
- [X] Check [documentation](https://mailu.io/master/) and [FAQ](https://mailu.io/master/faq.html). (Tip, use the search function on the documentation page)
- [X] You understand `Mailu` is made by volunteers in their **free time** — be conscise, civil and accept that delays can occur.
- [X] The title of the issue should be short and simple. It should contain specific terms related to the actual issue. Be specific while writing the title.

### Environment
 - [ ] docker-compose
 - [X] kubernetes
 - [ ] docker swarm

## Description
Migrated from a VM that has postfix/dovecot/roundcube to Mailu, now reading my INBOX takes 1.5-2 seconds.

## Replication Steps
Installed Mailu on kubernetes on single host, tried using both hostPath directly and hostPath/local PVC.
~4000 emails in my INBOX, and ~10000 in total
Personal email, the entire server is just one account

## Expected behaviour
Performance to be similar to the same stack on VM (same machine)

## Logs
(Original) VM performance
![vm](https://user-images.githubusercontent.com/11525517/104081467-c0039200-51fc-11eb-815e-cba9708201cb.PNG)

After migration, Mailu performance
![mailu](https://user-images.githubusercontent.com/11525517/104081468-c09c2880-51fc-11eb-927f-e8bda1ee0f47.PNG)

Tried "file system" tuning from [Dovecot page](https://wiki.dovecot.org/PerformanceTuning), no significant improvment
2011 Mac mini quad-core i7, SSD
```
$ cat /proc/cpuinfo
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 42
model name      : Intel(R) Core(TM) i7-2635QM CPU @ 2.00GHz
stepping        : 7
microcode       : 0x2f
cpu MHz         : 811.881
cache size      : 6144 KB
physical id     : 0
siblings        : 8
core id         : 0
cpu cores       : 4
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx lahf_lm pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid xsaveopt dtherm ida arat pln pts md_clear flush_l1d
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit
bogomips        : 3991.30
clflush size    : 64
cache_alignment : 64
address sizes   : 36 bits physical, 48 bits virtual
power management:
```

**Comment by lub** [comment]
Hi. Did you happen to change the mailbox format during migration?

Are there any other differences? e.g. did you use clamav/rspamd before?

If you use sqlite - did you try something else and do you use the same kind of database for roundcube for both stacks?

Do you have the same performance hit when using IMAP directly?

Can you maybe also try to use a token insead of your normal password? There is currently ongoing work regarding the performance of password validations, but tokens should be faster to validate already right now.

**Comment by dominick-han** [comment]
@lub 
I have moved it onto a new machine, skylake-based CPU

Somehow this had made the IMAP response fast again (~500ms)

Closing the issue as I cannot replicate it anymore
