### ISSUE TITLE
k8s / Dovecot bails out if IPv6 is disabled on host system

### ISSUE THREAD

**Issue by HaleyACS** [Mailu/Mailu#1729]
Thank you for opening an issue with Mailu. Please understand that issues are meant for bugs and enhancement-requests.
For **user-support questions**, reach out to us  on [matrix](https://matrix.to/#/#mailu:tedomum.net).

To be able to help you best, we need some more information.

## Before you open your issue
- [ ] Check if no issue or pull-request for this already exists.
- [ ] Check [documentation](https://mailu.io/master/) and [FAQ](https://mailu.io/master/faq.html). (Tip, use the search function on the documentation page)
- [ ] You understand `Mailu` is made by volunteers in their **free time** — be conscise, civil and accept that delays can occur.
- [ ] The title of the issue should be short and simple. It should contain specific terms related to the actual issue. Be specific while writing the title.

### Environment
 - [ ] docker-compose
 - [X] kubernetes
 - [ ] docker swarm

### Versions
To find your version, get the image name of a mailu container and read  the version from the tag (example for version 1.7).
```
Kubernetes k3s Rancher + ingress-nginx: v1.20.0+k3s2
Helm version: v3.4.2
```

## Description
Further explain the bug in a few words. It should be clear what the unexpected behaviour is.  Share it in an easy-to-understand language.

mailu-dovecot goes into a crash-loop
```
mailu-dovecot-785bb4fbdc-m52qs    0/1     CrashLoopBackOff    12         40m
```

## Replication Steps
Steps for replicating your issue

Just execute the helm installer.

## Expected behaviour
Explain what results you expected - be as specific as possible. Just saying "it doesn’t work as expected" is not useful. It's also helpful to describe what you actually experienced.

Helm chart should be able to configure the "listen" interface. Currently `listen: * ::` is used, while one should be able to choose to use "listen: *" in the dovecot.conf file.

## Logs
Often it is very useful to include log fragments of the involved component. You can get the logs via `docker logs <container name> --tail 1000`. For example for the admin container:
`docker logs mailu_admin_1 --tail 1000`
or using docker-compose `docker-compose -f /mailu/docker-compose.yml logs --tail 1000 admin`
If you can find the relevant section, please share only the parts that seem relevant. If you have any logs, please enclose them in code tags, like so:
````markdown
```

Jan 14 09:49:15 master: Error: service(imap-login): listen(::, 143) failed: Address family not supported by protocol
Error: socket() failed: Address family not supported by protocol
Jan 14 09:49:15 master: Error: socket() failed: Invalid argument
Error: service(imap-login): listen(::, 993) failed: Address family not supported by protocol
Jan 14 09:49:15 master: Error: service(imap-login): listen(::, 993) failed: Address family not supported by protocol
Fatal: Failed to start listeners
Jan 14 09:49:15 master: Fatal: Failed to start listeners
```
````

**Comment by HaleyACS** [comment]
Just  a FYI - I can override the data by creating a configmap for mailu overrides/dovecot.conf and applying it, just adding "listen = *"
This however will just work with kubernetes and if you know how to add it.

My steps were: configure my-values in helm.
Execute helm with the my-values file and provide option "template" instead of "install", redirect into a file.
Extract all snippets and put them into its own yaml file.
Then manually modify the the yaml files tin include a config-map.

**Comment by dominick-han** [comment]
@HaleyACS
For me, front (nginx), imap (dovecot), AND webdav all fail because they can't listen on IPv6 addresses (::)
I disabled my ipv6 by adding `ipv6.disable=1` to my grub options
Did you have to fix them? I couldn't find out how to overwrite webdav...

**Comment by HaleyACS** [comment]
@dominick-han You can create a config-map in kubernetes to actually disable ipv6 like this:
```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cfgmap-mailu-dovecot
  namespace: mailu

data:

  overrides.conf: |
    listen = *
    mail_nfs_index = yes
    mail_nfs_storage = yes
    mail_fsync = always
    mmap_disable = yes
    mail_max_userip_connections=100
```
The "listen = *"  will limite dovecot to ipv4 only.

**Comment by dominick-han** [comment]
Turns out, disabling IPv6 in grub disables it in the linux kernel, which I guess is the same kernel that all pods use?
I disabled IPv6 in mailu/overrides/dovecot.conf @HaleyACS, but not sure about how to disable IPv6 on front/nginx and webdav (nginx.conf overwriting means I'll have to copy the existing nginx.conf and remove all IPv6 listen? Instead of an one-line change like this)
