### ISSUE TITLE
Database is large for

### ISSUE THREAD

**Issue by konorws** [Mailu/Mailu#1731]
Hello
I use Mailu for mail server for my. 
I have 38 email addresses and limit on 1 GB for size for it.

My folder with mail have size **659M**
and my file **data/psql_db** have size **21GB**

root@vps-27090:/srv/mail# du -hs * 
  220K	certs
  21G	data
  4.0K	dav
  12K	dkim
  4.0K	docker-compose.yml
  12K	dovecot
  452M	filter
  659M	mail
  4.0K	mailu.env
  12K	overrides
  2.3M	redis
 37M	roundcube
 1.5M	webmail

root@vps-27090:/srv/mail/data# du -hs *
 4.0K	instance
 27M	psql_backup
 21G	         psql_db

**Comment by lub** [comment]
Hi,

did you have a look what table does take so much space? There are some example queries for this on the postgresql wiki:
https://wiki.postgresql.org/wiki/Disk_Usage
