### ISSUE TITLE
Server mailu said: 451 4.7.1 Try again later

### ISSUE THREAD

**Issue by Yazur-admin** [Mailu/Mailu#1742]
Hello,

Problem encountered: 

Server mailu said: 451 4.7.1 Try again later

![image](https://user-images.githubusercontent.com/73103693/105337115-514e0d80-5bda-11eb-86c4-e251988316cf.png)

I've looked into this, the problem could be due to:

 - Bad TLS certificate
 - Greylist configured?

This problem causes a wait of about 10 minutes when a mail has this problem.

How to get this problem:

I have a WEB server under linux "Debian 10" which relays its mails to the mail server.
When I do the command:
"mail -a FROM:rtonrpoergerzgpor@test.fr wcv49381@eoopy.com -s "testrohrnotigoierzgiezrgp"", sometimes the error appears but not all the time. Some times it sends the mail without going through the wait ten minutes before sending it back. 

Would you have an idea of what could happen because I have the impression that it is the mail server that tells the WEB server to wait before sending the mail, for a reason that escapes me.

**Comment by lub** [comment]
In the Admin UI you can jump to the antispam logs, where you should see wether it was greylisted (I suspect it was).

**Comment by Yazur-admin** [comment]
> Dans l'interface utilisateur d'administration, vous pouvez accéder aux journaux antispam, où vous devriez voir s'il était en liste grise (je suppose que c'était le cas).

Yes that's right, I can see the soft mails rejected by the greylist.
I tried to increase the greylist score from 4 to 5.
I don't really understand this scoring system because an email with a score of 4.87 was graylisted but now it's not graylisted anymore.

So I don't understand.

I saw that you can whitelist domains but I would like to whitelist the servers that send mail.

Or disable the graylist, how can I do that?

**Comment by Yazur-admin** [comment]
@lub 
![image](https://user-images.githubusercontent.com/73103693/105481142-ef0f0e80-5ca6-11eb-813f-a052b718c4a8.png)

Why with such a score, the mail is soft-rejected?

**Comment by lub** [comment]
>  I don't really understand this scoring system because an email with a score of 4.87 was graylisted but now it's not graylisted anymore.

The greylisting is cached for 24h by default in redis. See https://rspamd.com/doc/modules/greylisting.html for more information on this.

> I saw that you can whitelist domains but I would like to whitelist the servers that send mail.
> Or disable the graylist, how can I do that?

Never done this myself, but you can create overrides for the rspamd config, which are mounted from `<Mailu storage path>/overrides/rspamd/`.
I've found some examples regarding disabling greylisting on https://groups.google.com/g/rspamd/c/yl3AOBv_QvM and regarding whitelist ip addresses on https://whitelist.maven-group.org/

**Comment by lub** [comment]
And in case you are wondering about the scoring itself; in the rspamd web UI you can click on an email and see a breakdown.
