### ISSUE TITLE
Create accounts

### ISSUE THREAD

**Issue by masa2146** [Mailu/Mailu#1749]
Hello, I want to create many accounts with API. Is it possible with mailu? If it's, how can I do?  And create new user page does not appear, I can't find it on administrator page.

**Comment by Diman0** [comment]
This is described in the documentation. For creating users via API see https://mailu.io/1.7/cli.html.
```
docker-compose exec admin flask mailu user myuser example.net 'password123'
```

For creating users via the web interface see https://mailu.io/master/webadministration.html#add-user
In the web administration interface you go to Mail domains -> Users -> Add User

**Comment by Diman0** [comment]
Closing this since the question is answered. For future user-support questions, reach out to us  on [matrix](https://matrix.to/#/#mailu:tedomum.net).
