### ISSUE TITLE
Creating network "mailu_default" with the default driver

### ISSUE THREAD

**Issue by gnh1201** [Mailu/Mailu#175]
I did try run, but showing this error:

> root# docker-compose run --rm admin python manage.py admin root [domain] [password]
> ERROR: 404 page not found
> Creating network "mailu_default" with the default driverCreating network "mailu_default" with the default driver

How can I do?

**Comment by kaiyou** [comment]
The warning about creating the network is perfectly normal because the Compose file does not specify any network. The issue here is seems to be with the way you are invoking the ``admin`` command. Does your password contain any special char that would require escaping maybe?

**Comment by outbackdingo** [comment]
im seeing the same issue and no clear explaination on how to resolv it, i dont even see where its trying to create a network in the docker compose file

**Comment by kaiyou** [comment]
This is *not* an issue. Docker Compose will create a default network per project and join the containers to that network. This is the default behavior and is perfectly fine for Mailu to run properly :)
