### ISSUE TITLE
Unable to access the demo server

### ISSUE THREAD

**Issue by tomaswarynyca** [Mailu/Mailu#1762]
Can you check the server configuration because I can not access with the credentials provided on the web?
https://mailu.io/master/demo.html#connecting-to-the-server

**Comment by matheusfillipe** [comment]
Same problem.

**Comment by Diman0** [comment]
I have the same problem. I will ask someone with access to have a look on the server. There should be a script that resets the password of the admin user once per day. Maybe there is an issue with this script.

**Comment by Diman0** [comment]
Access has been restored. It is possible to login again with the admin@test.mailu.io user.
