### ISSUE TITLE
Switch to AdminLTE 3

### ISSUE THREAD

**Issue by tomaswarynyca** [Mailu/Mailu#1764]
In order to obtain a more current view, version 3.0.5 should be integrated or the new candidate version 3.1 should be integrated.

**Comment by hamamo** [comment]
Having DataTables for long lists would be fantastic.

**Comment by DjVinnii** [comment]
I started working on this by forking the Mailu project and creating a branch: [AdminLTE 3](https://github.com/DjVinnii/Mailu/tree/AdminLTE-3). I really liked the idea of DataTables, so I implemented it. Feel free to provide feedback.
