### ISSUE TITLE
Where to place "external" letsencrypt certificates for domain?

### ISSUE THREAD

**Issue by L0g4n** [Mailu/Mailu#1770]
Where in the certs directory do I have to place my folder with already obtained certificates from letsencrypt if I want to use them and skip obtaining a new certificate?

**Comment by tophirsch** [comment]
For the 'front' service set:
```
    volumes:
      - path_to_your_cert_folder:/certs:ro

```

In mail.env set:
```
TLS_FLAVOR=cert
TLS_CERT_FILENAME=your_cert.crt
TLS_KEYPAIR_FILENAME=your_cert.key
```

**Comment by L0g4n** [comment]
Thanks!
