### ISSUE TITLE
Possible to offer a docker run example?

### ISSUE THREAD

**Issue by hiqsociety** [Mailu/Mailu#1775]
Possible to offer a docker run example?

**Comment by benyanke** [comment]
I'm not sure what that would accomplish or help, given there are almost a dozen containers in a typical deployment. Docker compose is far simpler for this type of usecase.

What's your end goal?

**Comment by Diman0** [comment]
For user support please reach out on the [matrix channel](https://matrix.to/#/#mailu:tedomum.net).
