### ISSUE TITLE
pg_wal folder is filling up disk space

### ISSUE THREAD

**Issue by MrSuttonmann** [Mailu/Mailu#1779]
### Environment
 - [x] docker-compose

### Versions
1.7

## Description
/data/psql_db/pg_wal folder is taking up too much disk space.

Currently, on my 50GB VM, the folder is 28GB in size:

![image](https://user-images.githubusercontent.com/7480500/109776041-16d48900-7bfa-11eb-8fb5-95a8afd7a26a.png)

## Replication Steps
Run Mailu for a couple of months, and watch the folder size increase.

## Expected behaviour
As mentioned in the docs, Mailu has:

- Automatic minutely wal archiving and weekly pg_basebackup;
- Automatic cleaning of wal archives and base backups; Two versions always remain available;

I would then therefore expect the folder size to be minimal.

## Logs
These lines repeatedly appear in the database logs:
```docker-compose logs -f admin database```

````markup
```
database_1   | 2021-01-18 04:38:56.200 UTC [36] LOG:  archive command failed with exit code 1
database_1   | 2021-01-18 04:38:56.200 UTC [36] DETAIL:  The failed archive command was: test ! -f /backup/wal_archive/0000000100000000000000D2 && gzip < pg_wal/0000000100000000000000D2 > /backup/wal_archive/0000000100000000000000D2
database_1   | 2021-01-18 04:38:57.200 UTC [36] LOG:  archive command failed with exit code 1

```
````

**Comment by lbm34** [comment]
Same for me. It seems the wal path as changed since the last update i've done the 2021/14/02. 
The backup script still works in /backup/wal_archive instead of /data/pg_wal and :
- /backup/wal_archive doen't have been update since the update
- /data/pg_wal/ contains new wal files.

I guess it's only a matter of basebackup.sh to be updated with the new wal path (and, maybe, do a manual cleaning of the old path).

**Comment by MrSuttonmann** [comment]
@lbm34 Thank you for the workaround, you've saved my server from going down!

**Comment by Diman0** [comment]
Thank you for reporting this. This workaround will be helpful for other users who use the mailu shipped postgres image. From Mailu 1.8, the postgres image is deprecrated. You can still use an external postgres back-end. The mailu postgres image will be removed in a mailu version after 1.8. Once this happens we will provide a mechanism for transferring the database contents to another back-end.
