### ISSUE TITLE
Let's Encrypt failing on latest .env version

### ISSUE THREAD

**Issue by SaiGonSeamus** [Mailu/Mailu#178]
Hi,

When we added our second server as a backup in our DMZ, Let's Encrypt failed. 

I've reviewed the logs but can't see anything.

S

**Comment by kaiyou** [comment]
Did it simply fail without an error? do you have any log of a request to ``.well-known``?

Also, did you create another server with the same hostname? if so how did you split the requests between both servers?

**Comment by SaiGonSeamus** [comment]
Nothing in the logs for `.well-known`

No, they are named mail, mail1 etc. This is mail1.

Plan to use HAProxy, at present only one server is operational.

**Comment by ofthesun9** [comment]
I tried few day ago to install through stable branch : letsencrypt was not working.
I  modified "stable" by "1.4" in my .env file, relaunched docker-compose, and now it is working.

**Comment by SaiGonSeamus** [comment]
Didn't work for me I'm afraid. 

No `.well-known` in the logs either.

**Comment by kaiyou** [comment]
Could you try and run ``certbot`` manually from inside the ``admin`` container and report any errors?

To run it inside the container:

```
docker-compose exec admin certbot [...]
```

**Comment by SaiGonSeamus** [comment]
On server mail.mydomain.com, for this I get

```
root@mail:/mailu# docker-compose exec admin certbot certonly -d mydomain.com -d mail.mydomain.com
rpc error: code = 2 desc = oci runtime error: exec failed: container_linux.go:247: starting container process caused "exec: \"certbot\": executable file not found in $PATH"
```

on server mail1.mydomain.com, it runs but fails

```
Obtaining a new certificate
Performing the following challenges:
tls-sni-01 challenge for mydomain.com
tls-sni-01 challenge for mail1.mydomain.com
Waiting for verification...
Cleaning up challenges
Failed authorization procedure. mail1.mydomain.com (tls-sni-01): urn:acme:error:unauthorized :: The client lacks sufficient authorization :: Incorrect validation certificate for TLS-SNI-01 challenge. Requested 690f6ff1325c3eb534f11bcef049e3db.17027ea9932437e09ae868f8669bd7a5.acme.invalid from 115.78.248.220:443. Received 1 certificate(s), first certificate had names "mail1.mydomain.com", mydomain.com (tls-sni-01): urn:acme:error:unauthorized :: The client lacks sufficient authorization :: Incorrect validation certificate for TLS-SNI-01 challenge. Requested 012f4d64488df7d563c885fd4e5dbd84.c7facfe1bed915e6fd7c10cb13214e9b.acme.invalid from 139.59.110.199:443. Received 1 certificate(s), first certificate had names "mail.mydomain.com, mydomain.com"

IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: mail1.mydomain.com
   Type:   unauthorized
   Detail: Incorrect validation certificate for TLS-SNI-01 challenge.
   Requested
   690f6ff1325c3eb534f11bcef049e3db.17027ea9932437e09ae868f8669bd7a5.acme.invalid
   from XXX.XXX.XXX.XXX:443. Received 1 certificate(s), first
   certificate had names "mail1.mydomain.com"

   Domain: mydomain.com
   Type:   unauthorized
   Detail: Incorrect validation certificate for TLS-SNI-01 challenge.
   Requested
   012f4d64488df7d563c885fd4e5dbd84.c7facfe1bed915e6fd7c10cb13214e9b.acme.invalid
   from XXX.XXX.XXX.XXX:443. Received 1 certificate(s), first
   certificate had names "mail.mydomain.com, mydomain.com"

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A record(s) for that domain
   contain(s) the right IP address.

```

I have tried this with the Nginx container shut down as well, same result. My DNS records are fine as far as I know.

**Comment by SaiGonSeamus** [comment]
I spun up a 3rd server and hit the same problem. Running Cerbot manually gives this.

`rpc error: code = 2 desc = oci runtime error: exec failed: container_linux.go:247: starting container process caused "exec: \"certbot\": executable file not found in $PATH"`

**Comment by reciproco** [comment]
The same here. Mailu stable version, running certbot manually gives this:

rpc error: code = 2 desc = oci runtime error: exec failed: container_linux.go:247: starting container process caused "exec: \"certbot\": executable file not found in $PATH"

**Comment by reciproco** [comment]
Change stable version to 1.4 and now is working

**Comment by kaiyou** [comment]
That last part is definitely the weirdest. Stable and 1.4 should point to the same image exactly. Did you pull the latest image in both cases?

**Comment by nils-wisiol** [comment]
I can confirm the difference in 1.4 and stable behavior. For me, LE was only working with 1.4.

**Comment by kaiyou** [comment]
I will upgrade `stable` to `1.4` in the next few days after certbot is upgraded in `1.4`.

**Comment by kaiyou** [comment]
Last certificate renewal went just fine on my side using both `stable` and `master`.
