### ISSUE TITLE
rspamd fatal signal after changing architecture from armv7 to armv8 (64-bit) - unable to receive email

### ISSUE THREAD

**Issue by fracture-point** [Mailu/Mailu#1780]
### Environment
 - [x] docker-compose
 - [ ] kubernetes
 - [ ] docker swarm

### Versions
1.8.  

## Description
I had this running successfully for a long time on ARMv7 using leolivier's docker images.  I changed the Raspbian kernel to ARMv8 (64-bit), and at the same time switched to zurajm's images (because they have ARMv8 images and leolivier does not). 
 Everything appears to work fine EXCEPT for rspamd. I noticed that all incoming mail was getting rejected with SMTP message `4.7.1 Service unavailable - try again later`.

Upon further investigation, I noticed that in the handling of the inbound message I was getting an rspamd error in the docker logs.  I opened the Mailu web interface for rspamd, and saw an access error with it's .rrd file, which led me to this https://rspamd.com/doc/faq.html#why-am-i-getting-errors-after-moving-rspamd-to-a-different-platform-cpu-type.

In an attempt to resolve the issue, I shut everything down, renamed the `filter` folder, and let rspamd recreate the folder on startup.  Rspamd did recreate the folder and populate it (minus some sqllite files), but I continued to get the same errors.  I also then tried renaming the (original) filter folder back, but only removed the .rrd file. When rspamd comes online it recreates the .rrd file, but now I get this unhelpful message in the docker logs:

```
rspamd_crash_sig_handler: caught fatal signal 7(Bus error), pid: 7, trace: 
rspamd_crash_sig_handler: please see Rspamd FAQ to learn how to dump core files and how to fill a bug report
```

## Replication Steps
Move and existing Mailu installation from ARMv7 architecture to ARMv8

## Expected behaviour
Everything should work normally

I'm beginning to wonder if the .rrd issue is unrelated because I have switched back to ARMv7 but continue to use the zurajm images.  Everything works - email is received without issue and without the rspamd fatal signal error - but I do still get the .rrd error as 
```
antispam_1    | 2021-03-07 19:38:16 #9(controller) rspamd_worker_init_controller: cannot load rrd from /var/lib/rspamd/rspamd.rrd: rrd head cookies error: bad rra or ds count
```

**Comment by Diman0** [comment]
It is not likely you get any assistance here. x86_64 is the main architecture for Mailu. 
Someone who was able to build for Arm shared his steps by contributing:
https://mailu.io/master/rpi_build.html 
https://github.com/Mailu/Mailu/blob/master/tests/build_arm.sh

You could try our [mailu matrix channel](https://matrix.to/#/#mailu:tedomum.net). Someone in this channel might also use ARMv8.

**Comment by ofthesun9** [comment]
I have PR #1421 to have arm64 images generated automatically by travis. I think the the rspamd issues are now solved with latest alpine images.
You might give it a try (arm64 images, from master branch)

**Comment by fracture-point** [comment]
Excellent, thank you both for the pointers! @ofthesun9 - I'll wait until your PR is merged and then try again using the official images.

**Comment by Robin-floss** [comment]
Is there a way to get the official rpsamd image for amd64 right now?
