### ISSUE TITLE
gunicorn not listening on IPv6

### ISSUE THREAD

**Issue by kahrpatrick** [Mailu/Mailu#1789]
### Environment
 - [x] docker-compose
 - [ ] kubernetes
 - [ ] docker swarm

### Versions
1.8

## Description
Currently the gunicorn server of the admin container is only listening on IPv4 . https://github.com/Mailu/Mailu/blob/9c57f2ac39f9acf9911369a5eea8d2890ffbd648/core/admin/start.py#L22
In a docker-compose setup that uses IPv6 enabled networks, HOST_ADMIN and ADMIN_ADDRESS are getting resolved to internal IPv4 and IPv6 addresses. This causes requests to `/internal/auth` to get rejected whenever the IPv6 is chosen by the nginx proxy. In practice this breaks for example the rspamd dashboard.

## Replication Steps
Enable IPv6.

## Expected behaviour
gunicorn should listen on IPv6. This could be achieved by adding `-b [::]:80`.

## Logs

````markdown
```
[error] 13#13: *630 connect() failed (111: Connection refused) while connecting to upstream, client: 10.10.0.11, server: , request: "GET /admin/antispam/js/app/symbols.js HTTP/1.1", subrequest: "/internal/auth/admin", upstream: "http://[fd00:451c:dbab:3a4b::8]:80/internal/auth/admin", host: "mail.example.com", referrer: "https://mail.example.com/"

```
```

**Comment by kahrpatrick** [comment]
A temporary solution is to override the main `nginx.conf` of the front container and set the `ipv6=off` option on the resolver `resolver {{ RESOLVER }} ipv6=off valid=30s;`. This will force nginx to use IPv4 for internal communication.

**Comment by nextgens** [comment]
This is a real bug
