### ISSUE TITLE
rspamd only listens on localhost:11333

### ISSUE THREAD

**Issue by pgeorgi** [Mailu/Mailu#179]
"localhost" makes it hard for rmilter to reach it.

**Comment by kaiyou** [comment]
I am running the latest build of ``rspamd`` and it seems to be listening on ``0.0.0.0``':

```
tcp        0      0 0.0.0.0:11333           0.0.0.0:*               LISTEN      8/rspamd: main proc
tcp        0      0 0.0.0.0:11334           0.0.0.0:*               LISTEN      8/rspamd: main proc
```

Do you have any more details on the issue? Does rmilter complains about not being able to reach the antispam?

**Comment by pgeorgi** [comment]
$ docker run --rm mailu/rspamd:stable grep -r 1133 /etc/rspamd
/etc/rspamd/worker-normal.conf:    bind_socket = "*:11333";
/etc/rspamd/worker-controller.conf:    bind_socket = "0.0.0.0:11334";

$ docker run --rm mailu/rspamd:latest grep -r 1133 /etc/rspamd
/etc/rspamd/worker-normal.conf:    bind_socket = "localhost:11333";
/etc/rspamd/worker-controller.conf:    bind_socket = "0.0.0.0:11334";

so "stable" should work but "latest" needs a change

**Comment by kaiyou** [comment]
Ok, that must be an issue with a new default in the Alpine package. We will have to provide a ``worker-normal.com`` file as well.
