### ISSUE TITLE
502 Bad Gateway on /admin in VM Promox

### ISSUE THREAD

**Issue by Grazulex** [Mailu/Mailu#1797]
Hello,

I have just install the last version (1.7) of Mailu on a Debian 10 VM (Proxmox). When a try to go on the /admin url, I have a 502 Bad Gateway nginx error :-(

### Environment
 - [X] docker-compose
 - [ ] kubernetes
 - [ ] docker swarm

### Versions
1.7

## Logs
front_1      | 94.110.26.172 - - [04/Apr/2021:21:07:57 +0000] "GET /admin HTTP/2.0" 301 162 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36"
front_1      | 2021/04/04 21:07:57 [error] 11#11: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 94.110.26.172, server: , request: "GET /admin/ui HTTP/2.0", upstream: "http://192.168.203.5:80/ui", host: "mail.xxx.be"

**Comment by paal85** [comment]
I had the same issue. Found out it was just wrong mysql credentials/host in .env config. ( in my case, I forgot to add the sql server to same docker network as mailu)
you can check if you get a specific error with this command:
`docker-compose exec admin flask mailu admin me example.net password`
command found from setup docs. here: [https://mailu.io/1.7/compose/setup.html#start-mailu](https://mailu.io/1.7/compose/setup.html#start-mailu)
