### ISSUE TITLE
[enhancement-requests] mta-sts support?

### ISSUE THREAD

**Issue by MSandro** [Mailu/Mailu#1798]
Thank you for opening an issue with Mailu. Please understand that issues are meant for bugs and enhancement-requests.
For **user-support questions**, reach out to us  on [matrix](https://matrix.to/#/#mailu:tedomum.net).

![image](https://user-images.githubusercontent.com/10937159/113522401-8a263d80-95a0-11eb-8f57-e709cb7fd508.png)
my mail server gets blocked by Outlook. so it would be great to have an mta-sts option to prove the e-mail server.
I'm not a professional on the subject. With Mailu I managed to install an email server for the first time.

**Comment by ronivay** [comment]
+1 for MTA-STS support, but just saying lack of it is not the reason why outlook.com is rejecting your messages.

**Comment by robjloranger** [comment]
I naively feel like this shouldn't be too hard. So world like to work on it.

**Comment by nextgens** [comment]
@robjloranger have you managed to make progress on this? Do you need any help?

The "receive" side is not too hard... the "send" side is trickier

**Comment by robjloranger** [comment]
I have not yet had a chance, I just wrote mine by hand for the time being.

So if your interested please feel free.

What do you mean by send and receive side?

**Comment by nextgens** [comment]
I mean publishing the policy isn't hard... using policies published by others is harder.

**Comment by robjloranger** [comment]
Ah yes, very much so. And then sending reports

**Comment by nextgens** [comment]
Here's my overrides/nginx/mta-sts.conf; You also need to add mta-sts.example.com to HOSTNAMES to ensure that you get a valid certificate for it

```nginx
       location @mta-sts {
return 200 "version: STSv1
mode: testing
max_age: 86400
mx: mx.example.com\r\n";
      }

      location ^~ /.well-known/mta-sts.txt {
        try_files $uri @mta-sts;
      }
```
