### ISSUE TITLE
Authentication failures

### ISSUE THREAD

**Issue by lugdunum-1964** [Mailu/Mailu#1801]
Thank you for opening an issue with Mailu. Please understand that issues are meant for bugs and enhancement-requests.
For **user-support questions**, reach out to us  on [matrix](https://matrix.to/#/#mailu:tedomum.net).

To be able to help you best, we need some more information.

## Before you open your issue
- [x ] Check if no issue or pull-request for this already exists.
- [x] Check [documentation](https://mailu.io/master/) and [FAQ](https://mailu.io/master/faq.html). (Tip, use the search function on the documentation page)
- [x] You understand `Mailu` is made by volunteers in their **free time** — be conscise, civil and accept that delays can occur.
- [x] The title of the issue should be short and simple. It should contain specific terms related to the actual issue. Be specific while writing the title.

### Environment
 - [x] docker-compose

[docker-compose.yml.txt](https://github.com/Mailu/Mailu/files/6335354/docker-compose.yml.txt)

 - [ ] kubernetes
 - [ ] docker swarm

### Versions
v 1.7

## Description
I was running v1.7 before, but during a routine system upgrade I ran 

   $ docker-compose pull; docker-compose up -d -build 

on the mailu container. It did pull data from hub.docker.com and restarted fine. However, since then I'm unable to login with any of the accounts. Not with the existing ones, nor with a new one created for the purpose of testing.

I tested using open_ssl s_client -crlf -connect mailserver:imaps and also :ssmtp

The results are in this error file
[errors.txt](https://github.com/Mailu/Mailu/files/6335408/errors.txt)

## Replication Steps
Not sure how you can replicate this.

## Expected behaviour
I expect to be able to log in

## Logs
See: 
[errors.txt](https://github.com/Mailu/Mailu/files/6335419/errors.txt)

## Question
Is there a way to debug the authentication from the front end server and/or admin server?

**Comment by ofthesun9** [comment]
Hi,
You may try: 
docker-compose down
docker-compose up -d

Sometimes the IPs of the services are changed during an upgrade and I get used to recreate the full stack when I upgrade....

**Comment by lugdunum-1964** [comment]
Thanks ofthesun9. I tried that without luck

**Comment by phpwutz** [comment]
Hi,
I'm having the exact same issue with a fresh install via kubernetes/helm chart. Cannot login via imap or pop3.

Dovecot log:
`Apr 28 16:11:08 imap-login: Info: Disconnected (auth failed, 1 attempts in 2 secs): user=<user@myserver.com>, method=PLAIN, rip=10.1.186.197, lip=10.1.186.195, session=<j1REoArBQIUKAbrF>`

Front container log:
`2021/04/28 16:11:08 [info] 11#11: *886 upstream sent invalid response: "NO [AUTHENTICATIONFAILED] Authentication failed." while reading response from upstream, client: ****, server: 0.0.0.0:993, login: "user@myserver.com", upstream: 10.152.183.47:143`

Admin Container Log:
`[28/Apr/2021:16:11:06 +0000] "GET /internal/dovecot/passdb/user@myserver.com HTTP/1.1" 200 63 "-" "Python/3.8 aiohttp/3.7.4.post0"`

I'm glad to help debugging, just let me know what info is required

**Comment by phpwutz** [comment]
Uuuh just to update y'all, maybe someone can profit from this:
The culprit was the "subnet" value in the helmchart. ( in docker its the SUBNET env variable)
your containers need to be inside the configured subnet in order to authenticate stuff.
The default value in the helmchart did not match my kubernetes pod range, therefore it didnt work
