### ISSUE TITLE
Issue with optional clamav, can't build it

### ISSUE THREAD

**Issue by Tom284** [Mailu/Mailu#1809]
I pulled the repository but then when I tried to launch the Docker image (which I made from the pulled Dockerfile) it wouldn't work. I would get this message:

/bin/sh: /start.py: not found

So I had to change the Dockerfile into:

```
ARG DISTRO=alpine:3.12
FROM $DISTRO
# python3 shared with most images
RUN apk add --no-cache \
  python3 py3-pip bash \
  && pip3 install --upgrade pip
RUN apk add --no-cache clamav rsyslog wget clamav-libunrar

COPY conf /etc/clamav
COPY start.py /start.py
COPY health.sh /health.sh

EXPOSE 3310/tcp
VOLUME ["/data"]

CMD ["python3", "/start.py"]

HEALTHCHECK --start-period=350s CMD /health.sh
```
After that is done I keep getting:
```
ERROR: Incorrect argument format for option LogSyslog

ERROR: Can't open/parse the config file /etc/clamav/freshclam.conf

ERROR: Incorrect argument format for option LogSyslog

ERROR: Can't open/parse the config file /etc/clamav/freshclam.conf

ERROR: Incorrect argument format for option LogTime

ERROR: Can't open/parse the config file /etc/clamav/clamd.conf
```
with the argument being pretty much random each time.

I also get these errors when I make the clamd and freshclam configs pretty much empty:

ERROR: Update failed for database: daily

ERROR: Database update process failed: Connection failed

ERROR: Update failed.

ERROR: Incorrect argument format for option TCPSocket

ERROR: Can't open/parse the config file /etc/clamav/clamd.conf

**Comment by Diman0** [comment]
How did you try to build the image?
After cloning the repo you can build the image using:
```
docker-compose -f Mailu/tests/build.yml build antivirus
```
The folder Mailu is the cloned Mailu repo.

Are you using the latest version of docker and docker-compose?
