### ISSUE TITLE
warning: TLS library problem: error:14094418

### ISSUE THREAD

**Issue by SaiGonSeamus** [Mailu/Mailu#181]
Hi all,

When sending from our php based CRM with Mailu, they fail with this error.

`warning: TLS library problem: error:14094418:SSL routines:SSL3_READ_BYTES:tlsv1 alert unknown ca:s3_pkt.c:1153:SSL alert number 48:`

Has anyone else seen this?

Regards

S

**Comment by pgeorgi** [comment]
"alert unknown ca" looks like an SSL configuration issue where your CRM's PHP doesn't know the CA of your mail server

**Comment by askz** [comment]
if it's deb based distro check your ca-cert* package

**Comment by SaiGonSeamus** [comment]
I need to check the main.cf and master.cf for postfix to try to resolve this. Is there anything in this docker deployment that overwrites them or moves them?

**Comment by SaiGonSeamus** [comment]
The error seems to be a combination of the let's encrypt on Mailu not deploying correctly and PHP 5.6 being strict. 

```
openssl s_client -starttls smtp -crlf -connect mail.mydomain.com:587
CONNECTED(00000003)
depth=0 CN = mydomain.com
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 CN = mydomain.com
verify error:num=27:certificate not trusted
verify return:1
depth=0 CN = mydomain.com
verify error:num=21:unable to verify the first certificate
verify return:1
```

`Verify return code: 21 (unable to verify the first certificate)`

**Comment by SaiGonSeamus** [comment]
This issue is resolvable by including `smtpd_tls_CAfile`in a postfix override file.
