### ISSUE TITLE
ERROR: no such image: mailu/nginx:: invalid reference format

### ISSUE THREAD

**Issue by dhiraj-r** [Mailu/Mailu#1811]
I got this during fresh installation on Debian 9.

`root@vmi544711:/mailu# docker-compose -p mailu up -d`
`Creating network "mailu_default" with driver "bridge"`
`Pulling redis (redis:alpine)...`
`alpine: Pulling from library/redis`
`540db60ca938: Pull complete`
`29712d301e8c: Pull complete`
`8173c12df40f: Pull complete`
`a77b7ddf4978: Pull complete`
`3f34a000c6b3: Pull complete`
`275dfaedaf41: Pull complete`
`Digest: sha256:f8f0e809a4281714c33edf86f6da6cc2d4058c8549e44d8c83303c28b3123072`
`Status: Downloaded newer image for redis:alpine`
`ERROR: no such image: mailu/nginx:: invalid reference format`
`root@vmi544711:/mailu#`

My docker --version
Docker version 19.03.15, build 99e3ed8919

My docker-compose --version
docker-compose version 1.29.1, build c34c88b2

Mailu version : 1.7

Thank you.

**Comment by wuzhongyi1105** [comment]
`export MAILU_VERSION=1.7` then `docker-compose -p mailu up -d`

**Comment by dhiraj-r** [comment]
Thanks. It's working now.
