### ISSUE TITLE
Mailu setup file generator URL not working

### ISSUE THREAD

**Issue by dhiraj-r** [Mailu/Mailu#1814]
Mailu setup file generator URL (https://setup.mailu.io/) returned 404 error. Perhaps it's been moved to a new URL.

**Comment by okedialf** [comment]
Been trying to access it too... get 404 error as well

**Comment by neskhodovskiy** [comment]
Same thing. Since the online utility seems to be the only way to proceed with setup (even a template docker-compose file is nowhere to be found), taking it down will immediately block new installations of mailu. Suggestion: embed the utility into the project itself, so users can `git clone` and run it locally on their systems, or make it a separate container usable via `docker run`. This way the project will be decoupled from your server. Minus one responsibility!

**Comment by neskhodovskiy** [comment]
I'm sorry I was too quick to say that template files are missing. Found them at https://github.com/Mailu/Mailu/blob/master/setup/flavors/compose/docker-compose.yml. Will try to proceed with them manually meanwhile.

**Comment by neskhodovskiy** [comment]
Until the online URL is fixed, you can just clone this repo, `cd` into the `setup` folder and run `docker-compose up`. When the containers are ready, navigate to http://127.0.0.1:8001 to access the setup utility. 

Worth adding to the docs! ))

**Comment by Diman0** [comment]
It should be available again.  This was the actual error for the 1.7 setup image:
```
stable_1       |   File "/app/server.py", line 58, in build_app
stable_1       |     prefix_bp = flask.Blueprint(version, __name__)
stable_1       |   File "/usr/local/lib/python3.9/site-packages/flask/blueprints.py", line 195, in __init__
stable_1       |     raise ValueError("'name' may not contain a dot '.' character.")
stable_1       | ValueError: 'name' may not contain a dot '.' character.
stable_1       | Traceback (most recent call last):
```
The flask project released a breaking update last week where the usage of blueprint names was changed. Blueprint names may not contain a dot anymore. This caused our 1.7 setup image fail to start.
https://flask.palletsprojects.com/en/2.0.x/changes/
```
Show an error when a blueprint name contains a dot. The . has special meaning, it is used to separate (nested) blueprint names and the endpoint name. #4041
```
