### ISSUE TITLE
Can relay domains support relaying directly to a LMTP port?

### ISSUE THREAD

**Issue by decentral1se** [Mailu/Mailu#1815]
## Before you open your issue
- [x] Check if no issue or pull-request for this already exists.
- [x] Check [documentation](https://mailu.io/master/) and [FAQ](https://mailu.io/master/faq.html). (Tip, use the search function on the documentation page)
- [x] You understand `Mailu` is made by volunteers in their **free time** — be conscise, civil and accept that delays can occur.
- [x] The title of the issue should be short and simple. It should contain specific terms related to the actual issue. Be specific while writing the title.

### Environment
 - [ ] docker-compose
 - [ ] kubernetes
 - [x] docker swarm

### Versions

We're using the `master` docker tag.

## Description

When using relay domains in the web interface, the implementation assumes the use of SMTP. However, I am trying to relay directly using another protocol, namely, LMTP (the receiver is a mailman3 instance). 

When I see the remote host of my relay domain to `<host>:8024`, I see `refused to talk to me: 500 Error: command "HELO" not recognized)`. The Mailu postfix relay configuration assumes another postfix on the receiving end.

In my postfix configuration, I see it is possible to support a map such as `lmtp:/<ip>:<port>` and then postfix understands not to start with a `EHLO` command and pass the mail using LMTP (as far as I understand).

So, would it be possible to support LMTP relaying using relay domains?

## Replication Steps

- Setup any relay domain
- Specify a receiving port of 8024
- Setup a receiver on port 8024 expecting LMTP-based requests

## Expected behaviour

Relay domains can support LMTP.

## Logs

```
mail_example_com_smtp.1.zh0tmwq3qnjn@autonomic-swarm    | May 23 09:21:25 mail postfix/smtp[378]: 63D4536B052: to=<doesitwork@lists.example.com>, relay=lists_example_com_core[10.0.44.41]:8024, delay=1.4, delays=1.3/0.08/0.01/0, dsn=5.0.0, status=bounced (host lists_example_com_core[10.0.52.41] refused to talk to me: 500 Error: command "HELO" not recognized)
```

**Comment by Diman0** [comment]
No. Relay domains is meant for relaying emails to other SMTP servers (e.g. postfix). Relaying via the LMTP protocol is not one of the intended use cases.

I will mark this as an enhancement request.
