### ISSUE TITLE
[Enhancement] List of previously used addresses/aliases to block accidental reuse and privacy implications

### ISSUE THREAD

**Issue by elandorr** [Mailu/Mailu#1820]
I did search for existing issues first. Not quite sure how this feature would be worded so I may have missed a discussion.

I propose a simple feature, definitely easily overrideable if need be and with a toggle to turn it off, that permanently keeps track of used addresses so you cannot accidentally reuse a previously used one and leak data.

Address reuse is a problem for obvious reasons:
- intermingling different identities
- therefore leaking private information 

Storing the addresses can be done privacy friendly: simply store exclusively the address itself, no metadata.

On a side note: Deleting accounts does not delete the actual folders. I am doing this manually so far, but it'd be nice if *delete* actually meant *delete*.

As usual I have to praise how well Mailu works in general. I realized I've been using it for years now, and apart from some inconveniences like this or #1700 #1328 there hasn't been an issue, and it's more lightweight than the competitors. I wish you all the best!

**Comment by Diman0** [comment]
If I understand you correctly, deleting an user in the web administration GUI does not delete the mail folders of the user.
When you create a new user with the same user name (same email address), then this user sees the mail box of the deleted user.  For me this sounds as a bug./

The enhancement request is clear for me. This should be configurable via the GUI or via mailu.env.

**Comment by elandorr** [comment]
Yes, it does not delete the folders/data.

I did not check if you would see the content of the previous user, that'd be quite a grave bug indeed. I simply meant reusing addresses means that addresses could in the future receive data meant for the previous user. That's why pretty much every mailprovider blocks it.

I suggest:
- having an option to keep a list of all addresses that ever existed
- when creating a new inbox that matches, showing a warning, but having an option to override this as domain administrator if need be (deleting and recreating postmaster@ should be easy for instance)

**Comment by elandorr** [comment]
Mailu still does not remove deleted user data, or block/warn of address reusage for the record. You have to keep your own list and delete the folder in `/mail`.
