### ISSUE TITLE
Error starting userland proxy: listen tcp4 xx.xx.xxx.xxx:995: bind: cannot assign requested address

### ISSUE THREAD

**Issue by AnnyBon** [Mailu/Mailu#1825]
### Environment
 - [ ] docker-compose

### Versions
docker-compose version 1.29.2
mailu 1.7 
Ubuntu Server 18.04.5 LTS
AWS Instance & Azure VM

## Description
Gets the following error when trying to run 'docker-compose -p mailu up -d'.
`ERROR: for 81adede781ce_mailu_front_1  Cannot start service front: driver failed programming external connectivity on endpoint mailu_front_1 (247001136ed87ca3906de479130e7285835e61fdd2e42a022598bd375daf2f78): Error starting userland proxy: listen tcp4 xx.xx.xxx.xxx:995: bind: cannot assign requested address`

I'm new and trying to figure out what is wrong. Followed almost all the similar issues. But could not solve it.

**Comment by MiguelNdeCarvalho** [comment]
Hey,

Check if you have one service running with that port.

Thanks,
MiguelNdeCarvalho

**Comment by AnnyBon** [comment]
> Hey,
> 
> Check if you have one service running with that port.
> 
> Thanks,
> MiguelNdeCarvalho

No. The port is not in use. None of the services are using that port. I even reinstalled the entire OS and tried. Also, first I was trying that on AWS instances, and moved to Microsoft Azure thinkin that it's an issue with AWS. But the issue was same...

**Comment by MiguelNdeCarvalho** [comment]
Hey,

Is that `xx.xx.xxx.xxx` your machine IP or part of the subnet asked on the setup.mailu.io?

Thanks,
MiguelNdeCarvalho

**Comment by AnnyBon** [comment]
> Hey,
> 
> Is that `xx.xx.xxx.xxx` your machine IP or part of the subnet asked on the setup.mailu.io?
> 
> Thanks,
> MiguelNdeCarvalho

It's the public IP of the server. Subnet asked on the mailu setup is different.

**Comment by Diman0** [comment]
Does it work if you try to bind/listen on all interfaces? 
e.g.
    ports:
      - 443:443
or      
    ports:
      - 0.0.0.0:443:443

**Comment by prettyCoders** [comment]
does this bug resolved?

**Comment by AnnyBon** [comment]
> Does it work if you try to bind/listen on all interfaces?
> e.g.
> ports:
> - 443:443
> or
> ports:
> - 0.0.0.0:443:443

It's like 0.0.0.0:443:443
That was the default configurations of Mailu.
