### ISSUE TITLE
https://travis-ci.org/ ceased. We need to switch to a new CI/CD pipeline

### ISSUE THREAD

**Issue by Diman0** [Mailu/Mailu#1828]
1: Main topic: find new CI/CD provider ASAP
==

[Travis has ceased](https://travis-ci.org/). This means that from yesterday no new builds are created anymore!
From now on it is **not** possible to automatically test and merge pull requests. We must quickly decide to what new CI/CD system we switch.

When deciding for a new CI/CD pipeline we have the following topics to address
- Free or paid? 
- Deployment type
  - Cloud based only
  - Self-hosted only
  - Mixed
- Background of the company. How much do we trust the company not to pull the plug like with Travis. 
- Maybe other metrics, feel free to provide these.

Possible candidates. These are 2 candidates we discussed yesterday. Feel free to bring up other candidates.
- github actions (mixed). 
  - Free
  - Mixed deployment. You can make use of free cloud instances and you can self-host instances.
  - Github is owned by Microsoft. Do we trust them to not pull the plug or make it paid in the future?
- drone.io
  - Free
  - Mixed deployment. Offers cloud instances via partners and you can self-host instances.
  - Owned by [harness](https://harness.io/company/) who committed to keep it free.
  - recommended by decentral1se

2: Future topics for CI/CD
==
[Last project meeting](https://github.com/Mailu/Mailu/issues/1582) someone mentioned these topics. I think these should be discussed and tackled once we have switched to a new CI/CD provider. Possibly we could already do this when switching, but I think it takes time to make a proper decision.

2.1: Testing, can this be reduced? Solve long build times.
=====
Currently a build takes takes ~30 minutes on travis. The main reason is that there are many tests.  We need to thoroughly check if we really want to perform all the tests that are done currently.   For this we must document what component/functionality each test tests. After that we can make an informed decision if and what can be changed. Of course it is vital that all components are still tested.

Personally I think we should first check how long a build takes on the new CI/CD pipeline and then decide if this is too long. For me 20-30 minutes is already acceptable. What max build time acceptable for you?

**Comment by luilegeant** [comment]
Hello,
Here are my thoughts:
# 1. CI/CD to consider:
- GitLab has 400 CI/CD minutes per month on free accounts (*but* requires a credit card to validate)
- Could we consider having a pipeline self hosted (what if one of us has a lying computer) ?
  - This brings security/trust/quality (etc) consideration into the mix,
  - It could be an option for pre-merge builds (or help people better prepare their PR on their side before running the main one).
  - Once it has been merged into master, I would fallback to "trusted" pipelines.
What are your thoughts on this ?

Regarding the choice: I'm opinionated towards the mixed/dynamic solution: I personally self host (understand at home) most of my needs. I would propose a mixed solution depending on the availability of the services (we could choose multiple pipeline providers if we are allowed).

# 2. Future topics
## 2.1: Testing times
I would add the following questions to be answered/evaluated to this topic:
- How could the builds be factorized to reduce/parallelize building time.
- Could the build be specific to what bit has been changed and cascading the build requirement to impacted modules (dependency graph)

**Comment by decentral1se** [comment]
Nice one. Opened up https://github.com/Mailu/Mailu/issues/1830 to tackle the additional topic.

The CI setup in https://github.com/Mailu/Mailu/blob/master/.travis.yml#L30-L39 does not look that majorly complicated thankfully. This shouldn't be too difficult to convert into another format for a different system. As mentioned above yes, we're making a lot of use of Drone at Autonomic and hosting our own instance at https://drone.autonomic.zone. It is not a very powerful machine and I don't think we could open it up for this project just yet (unless @3-w-c has other ideas). 

But the approach is worth considering: using some decent and affordable VPS provider (e.g. Hetzner) and wiring up your Drone instance and your Drone Docker runner and integrating it with Github authentication. We have shared configurations for our Drone/runner setups in https://github.com/Coop-Cloud/drone and https://github.com/Coop-Cloud/drone-docker-runner. The question is though, where does the money come from? That is an organisational issue to figure out which we might want to right now. Then again, moving to a "free X minutes a month" might save us now but bring us right back to this question again. So, is anyone also thinking about Open Collective / Libera pay / `$my_favourite_shared_money_service` to support CI/CD costs? We could try to map out an estimate. Just throwing out ideas.

Self-hosting would be fun but I've seen it go very wrong on projects that have struggle with keeping volunteers around. If the person who has the machine dissapears, you cannot access your CI infrastructure. Having a cloud provider with a team model and shared access works better in this case imho.

**Comment by nextgens** [comment]
My vote goes to moving to github actions.

- It has free minutes
- It's the better known solution (will likely be easier to integrate with other tools), including github that we do use
- I've already used it

**Comment by decentral1se** [comment]
Oh! https://crowdfunding.lfx.linuxfoundation.org/projects/mailu

![image](https://user-images.githubusercontent.com/1991377/122435322-32d91c00-cf98-11eb-8801-a838d00b1b6f.png)

**Comment by luilegeant** [comment]
Regarding solving the CI/CD issue: I would focus on getting back on track even on a limited way.

Regarding funding, I would push that to another issue since it's a wider recurring issue and as decentral1se mentioned, some (even guestimate) projections would be something to work on ass well as affectations. It would also give the project a serious baseline to start looking into various funding solutions (not just individual/company sponsorship) but institutional like the Foundations, EU or respective countries.

**Comment by Diman0** [comment]
I think I also prefer switching to github actions. As nextgens already mentioned it has free minutes that reset every month. 
- it is backed by github/microsoft. So a large product team that maintains it.
- it has good quality documentation (and tons of documentation).
- it offers also the possibility for self-hosted runners in case we want to use this as well in the future.
- github actions can also be used to automate other things in the project. E.g. a workflow can be started when someone creates an issue or pull request. 

Anyone else feel free to give your opinion.

**Comment by parisni** [comment]
This paragraph is probably offtopic. I have the feeling moving to github action makes mailu more dependant to github. Just to mention there also exist alternative such sourcehut, and AFAIK there is some money on the project in case the later would become a paid solution. We could also create a mirror on github and benefit from a more FOSS environment, with git-mail workflow which is something pleasant for a mailing project such mailu.  

More realistic, github actions looks the most logic/serious move today I have to admit.

> * it (github action) offers also the possibility for self-hosted runners in case we want to use this as well in the future.

in case all the free shots will be  spent, as self-hosters we might add some of our servers to let the CI  happens, that's a good point IMO.

**Comment by Diman0** [comment]
Ok. Let's go for github actions. Most of the people who have responded have agreed this is the fastest solution for now. In the future we can always discuss using a different CI/CD.

I will look into creating the workflow.yml file and what changes are required to make the switch. 
So far I have only identified one potential issue. The login/password for the mail docker hub account. It is owned by @muhlemmer or @kaiyou . If one of you sees this message, I request him to add the docker login/password as secrets to the project.
1). Open the mailu project (https://github.com/Mailu/Mailu)
2). Go to settings -> secrets
3). Add 
- Docker_Login with the  login for the mailu docker repo
- Docker_Password with the password for the mailu docker repo

I already use secrets.Docker_Login and secrets_Docker_Password. If you decide to use a different name, that is not a problem. But of course you must inform us what the new name is of the secret so we can use it in the workflow yml.

**Comment by Diman0** [comment]
A short update. We got in contact with @kaiyou . He is the owner of the mailutest/mailu docker repository. This weekend he will probably have time to enter the required secrets for the new CI/CD workflow (the login/password for a new docker user who has access to the docker repositories).

I have finished an initial workflow. It takes about 17 to 27 minutes, depending on how many images are touched. The workflow caches all docker build layers. In the general use case where only 1 image is touched by a PR, the total time will be hopefully around ~20 minutes. The previous Travis CI/CD workflow took about 30 minutes.

After the required secrets are added, I will push the new ci/cd workflow. After that we can look into improving it. I already confirmed it works correctly with BORS. 

Hopefully we have a working CI/CD pipeline next week.

Once we start improving the workflow, we must remember that the most important factor is total billable time.
https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions
We only have 2000 minutes per month. That time is billed per job and not per workflow. So a workflow with 10  parallel jobs which take 10 minutes each only takes 10 minutes total running time. However we will be billed 100 minutes. This is an important factor to take into account when we further improve the workflow.

**Comment by Diman0** [comment]
After reading the [manage billing page](https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions), I noticed I overlooked something very important. It only applies to **private** repo's. Public repo's have no spending limit. Sometimes it is difficult to properly read and understand what you are reading. So ignore the last paragraph of my previous message.

**Comment by decentral1se** [comment]
Thanks for your work @Diman0! This is all sounding great.
