### ISSUE TITLE
QUESTION: clamav disable

### ISSUE THREAD

**Issue by supersophie** [Mailu/Mailu#183]
Hi, 

How can I disable Clamav from the workflow?
Thanks, Sophie

**Comment by kaiyou** [comment]
There is no actual option to disable Clamav properly at the moment. I am not sure what is the ``rmilter`` behaviour if it cannot reach the antivirus. You could try and disable the ``antivirus`` container and check the behaviour.

**Comment by supersophie** [comment]
Better would be to comment out the hook in rmilter  that calls it. Now I know where this is I shall look
--

**Comment by kaiyou** [comment]
This will be possible once we merge #212.
