### ISSUE TITLE
Question:  setup guide - unable to connect on port 80 from public Internet

### ISSUE THREAD

**Issue by supersophie** [Mailu/Mailu#184]
Hi, 
I just installed via the set up guide, but I cannot see how one actually connections to the public IP.

I have the containers running and can be access from localhost, but not from anywhere else.
On Amazon EC2 ( where this is running ) I have all the ports opened to everywhere and this worked for poste.io ( which didn't work very well :) ) 

``` 
# lsof -P -i tcp | grep LIST|grep docker
docker-pr 5058     root    4u  IPv4  20023      0t0  TCP localhost:4190 (LISTEN)
docker-pr 5112     root    4u  IPv4  20055      0t0  TCP localhost:995 (LISTEN)
docker-pr 5141     root    4u  IPv4  20086      0t0  TCP localhost:993 (LISTEN)
docker-pr 5165     root    4u  IPv4  20133      0t0  TCP localhost:143 (LISTEN)
docker-pr 5193     root    4u  IPv4  20162      0t0  TCP localhost:110 (LISTEN)
docker-pr 5455     root    4u  IPv4  20814      0t0  TCP localhost:443 (LISTEN)
docker-pr 5479     root    4u  IPv4  20883      0t0  TCP localhost:80 (LISTEN)
docker-pr 5696     root    4u  IPv4  21366      0t0  TCP localhost:587 (LISTEN)
docker-pr 5742     root    4u  IPv4  21419      0t0  TCP localhost:465 (LISTEN)
docker-pr 5771     root    4u  IPv4  21466      0t0  TCP localhost:25 (LISTEN)
docker-pr 6760     root    4u  IPv4  23990      0t0  TCP localhost:8000 (LISTEN)
```

Obvisously, as expected, the http://public-IP/admin did not go anywhere.

I looked at the allowed networked in .env, but left this as default because I want all networks on the Internet to connect. 
```
# Networks granted relay permissions, make sure that you include your Docker
# internal network (default to 172.17.0.0/16)
RELAYNETS=172.16.0.0/12
```
Unsure why this is there anyway for an email server.

Any ideas on how I could get this working?

Thanks, Soph.

**Comment by ofthesun9** [comment]
My guess : 
in the .env file, you have to set-up "BIND_ADDRESS"

I want mailu to listen from everywhere, so I put : 
BIND_ADDRESS=0.0.0.0

**Comment by supersophie** [comment]
Thanks. I tried this and docker-compose failed:
# docker-compose up -d
ERROR: In file './docker-compose.yml' service 'version' doesn't have any configuration options. All top level keys in your docker-compose.yml must map to a dictionary of configuration options.

My .env file
# grep -v ^# .env|grep -v ^$
ROOT=/mailu
VERSION=stable
SECRET_KEY=cHANGEmEcHANGEmEE
BIND_ADDRESS=0.0.0.0
DOMAIN=muddle.xyz
HOSTNAME=mail.muddle.xyz
POSTMASTER=admin
COMPOSE_PROJECT_NAME=mailu
FRONTEND=nginx
WEBMAIL=rainloop
EXPOSE_ADMIN=yes
ENABLE_CERTBOT=True
WEBDAV=none
MESSAGE_SIZE_LIMIT=10000000
RELAYHOST=
FETCHMAIL_DELAY=30
NGINX_SSL_DHPARAM_BITS=2048

**Comment by kaiyou** [comment]
Removing variable names should have the same effect as having an empty value, which is fine in the case of ``RELAYNETS`` indeed.

Given your error, I suspect that you are running a pretty old version of Docker Compose, which does not know how to parse version 2 of the Docker Compose syntax. Could you try and update Compose?

**Comment by ricardodemauro** [comment]
Probably your docker engine is old too. Try update both.

**Comment by curry684** [comment]
Run the following commands to update Docker Compose to current 1.12:
```
curl -L https://github.com/docker/compose/releases/download/1.12.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose
```

**Comment by ChadDa3mon** [comment]
Running into this same problem myself, found this by doing a google search. I've tried adding BIND_Address=0.0.0.0 to my .env file, but it made no difference. I can connect to 443 from localhost, but not other computers on that subnet. 

```
$ grep BIND mailu.env
BIND_ADDRESS=0.0.0.0
```
