### ISSUE TITLE
Radicale password check fails (length limited?)

### ISSUE THREAD

**Issue by parisni** [Mailu/Mailu#1861]
So far, the webdav radicale is protected with basic auth (apparently htaccess or similar).
If user password > 8 then it fails to connect. 
we should remove this limitation to let use stong passwords

**Comment by nextgens** [comment]
As far as I know, it's handled in 
https://github.com/Mailu/Mailu/blob/66ea28b50adce1c589fd6b2dc1b34356d4c64930/core/admin/mailu/internal/views/auth.py#L60 and there is no length limit.

Which version have you tested with? What's in master? Is there anything logged in the admin container?

**Comment by ghostwheel42** [comment]
I think we should update the basic_authentication method. The handling of the base64 encoded data IMHO is a little bit sloppy. 

@parisni  do you have a colon in the password? I think the split in line 66 will fail if there is any (", 1" missing).

**Comment by nextgens** [comment]
@ghostwheel42 good catch! it's even rsplit(b":",1) that you want

**Comment by nextgens** [comment]
@ghostwheel42 good catch! Yeah, I've checked the RFC and the username can't have a colon... maybe we should enforce that elsewhere too.

**Comment by ghostwheel42** [comment]
@nextgens 
> maybe we should enforce that elsewhere too.

There user name is a E-Mail address. The domain part is "checked" in the model: AFAIK idna encode does not encode a colon. 
I don't see a check for the local part, but this is part of my config-import/export/schema/api work in progress: I'll add validators to the model.

**Comment by nextgens** [comment]
@parisni Can you confirm that this is what is happening here? or are we chasing more than one bug? :stuck_out_tongue:

**Comment by nextgens** [comment]
> @nextgens
> 
> > maybe we should enforce that elsewhere too.
> 
> There user name is a E-Mail address. The domain part is "checked" in the model: AFAIK idna encode does not encode a colon.
> I don't see a check for the local part, but this is part of my config-import/export/schema/api work in progress: I'll add validators to the model.

Thinking about it further, I think that it's tricky to handle right... If we want the fix to be backported, we want to ensure we don't break existing setups (that may already use colons in emails), ... IMHO we should just keep it simple and accept that it's broken if such characters were to be used in the email.

I've submitted #1862, doing just the bare minimum... that can be safely backported
