### ISSUE TITLE
How to edit Postfix main.cf

### ISSUE THREAD

**Issue by SaiGonSeamus** [Mailu/Mailu#189]
Hi,
I need to edit main.cf of Postfix to add `smtpd_tls_CAfile` but I'm not sure how to with the containers. 

Anyone know how best to add this override?

**Comment by hoellen** [comment]
You can create a file in "$ROOT/overrides/postfix.cf" and override the config values.

**Comment by SaiGonSeamus** [comment]
Hi,
I created a postfix.cf with the contents of main.cf including my new additional line.

`smtpd_tls_CAfile =/certs/fullchain.pem`

and got

```
smtp_1       | postconf: fatal: missing attribute name: ""
smtp_1       | postconf: fatal: -e, -X, or -# accepts no comment input
```
Which might be similar to this.

https://github.com/tomav/docker-mailserver/issues/560

**Comment by hoellen** [comment]
You dont' have to put the complete content of the main.cf in /overrides/postfix.cf. 
Only include your values you want to override. 

My postfix.cf only include this lines: 
```
smtpd_tls_cert_file=/certs/fullchain.pem
smtpd_tls_key_file=/certs/privkey.pem
```

greets
hoellen

**Comment by SaiGonSeamus** [comment]
That worked. Thank you.

**Comment by muhlemmer** [comment]
@kaiyou. I'm this method is obsolete, since all connection handling is done by `front`? (Checking in context of the FAQ) #564

**Comment by hoellen** [comment]
@muhlemmer yes after the update where `front` handles all connections I removed the override.

**Comment by kaiyou** [comment]
It is indeed obsolete. We could however think of a similar method using nginx
