### ISSUE TITLE
Is possible to customize the admin UI?

### ISSUE THREAD

**Issue by codeinforest** [Mailu/Mailu#1905]
My company logo has primary color is RED. So I wanna change the color, does it possible and how to do that?
* I'm not familiar with python so please help me!

**Comment by ghostwheel42** [comment]
Hi @codeinforest 
Sorry. as of now only the blue "Admin LTE" skin is included. There are some other options but not easily selectable right now.
We are switching to AdminLTE 3 for the 1.9 version. I'll take a look if we can include more color options.

**Comment by ghostwheel42** [comment]
Hi @codeinforest - with version 1.9 it will be possible to change the logo and its background color in the upper left corner. There's no release date yet.
