### ISSUE TITLE
Strange header rewrite

### ISSUE THREAD

**Issue by senilio** [Mailu/Mailu#191]
Running v1.4, I've noticed that outgoing email gets its Received header rewritten with PRIMARY_HOSTNAME [PUBLIC_IP], literally.

Sending an email to gmail, here's the headers on the receiver side.

Received: from authenticated-user (PRIMARY_HOSTNAME [PUBLIC_IP]) by domain.com (Postfix) with ESMTPSA id 87AD9648 for <recipient@gmail.com>; Thu,
  6 Apr 2017 12:56:52 +0000 (UTC)

Here's the replace taking place in the postfix logs:

smtp_1       | postfix/cleanup[61]: 0EADA648: replace: header Received: from [172.17.7.226] (unknown [81.146.13.44])??by domain.com (Postfix) with ESMTPSA id 0EADA648??for <recipient@gmail.com>; Thu,  6 Apr 2017 12:34:23 +0000 (UTC) from unknown[81.146.13.44]; from=<sender@domain.com> to=<recipient@gmail.com> proto=ESMTP helo=<[172.17.7.226]>: Received: from authenticated-user (PRIMARY_HOSTNAME [PUBLIC_IP])??by domain.com (Postfix) with ESMTPSA id 0EADA648??for <recipient@gmail.com>; Thu,  6 Apr 2017 12:34:23 +0000 (UTC)

I'd expect PRIMARY_HOSTNAME [PUBLIC_IP] to be a real hostname and IP.

Thanks!

**Comment by kaiyou** [comment]
That is actually the intended behavior, in order to keep the full ``Received`` chain while helping authenticated users stay anonymous when sending emails through SMTP or Submission.

You can change this behaviour and build your own version of the ``smtp`` container by editing ``outclean_header_filter``.

**Comment by senilio** [comment]
Thanks for clarifying this!
