### ISSUE TITLE
sqlite3.IntegrityError: UNIQUE constraint failed: user.email 

### ISSUE THREAD

**Issue by siddheshkirve** [Mailu/Mailu#1921]
Thank you for opening an issue with Mailu. Please understand that issues are meant for bugs and enhancement-requests.
For **user-support questions**, reach out to us  on [matrix](https://matrix.to/#/#mailu:tedomum.net).

To be able to help you best, we need some more information.

## Before you open your issue
- [ ] Check if no issue or pull-request for this already exists.
- [ ] Check [documentation](https://mailu.io/master/) and [FAQ](https://mailu.io/master/faq.html). (Tip, use the search function on the documentation page)
- [ ] You understand `Mailu` is made by volunteers in their **free time** — be conscise, civil and accept that delays can occur.
- [ ] The title of the issue should be short and simple. It should contain specific terms related to the actual issue. Be specific while writing the title.

### Environment
 - [x] docker-compose
 - [ ] kubernetes
 - [ ] docker swarm

### Versions
To find your version, get the image name of a mailu container and read  the version from the tag (example for version 1.7).
```
$> docker ps -a | grep mailu
140b09d4b09c    mailu/roundcube:1.7    "docker-php-entrypoi…"    2 weeks ago    Up 2 days (healthy)    80/tcp
$> grep MAILU_VERSION docker-compose.yml mailu.env
```

## Description
Further explain the bug in a few words. It should be clear what the unexpected behaviour is.  Share it in an easy-to-understand language.

## Replication Steps
Steps for replicating your issue

## Expected behaviour
Explain what results you expected - be as specific as possible. Just saying "it doesn’t work as expected" is not useful. It's also helpful to describe what you actually experienced.

## Logs
Often it is very useful to include log fragments of the involved component. You can get the logs via `docker logs <container name> --tail 1000`. For example for the admin container:
`docker logs mailu_admin_1 --tail 1000`
or using docker-compose `docker-compose -f /mailu/docker-compose.yml logs --tail 1000 admin`
If you can find the relevant section, please share only the parts that seem relevant. If you have any logs, please enclose them in code tags, like so:
````markdown
```
Your logs here!
```
````

**Comment by DarekLin** [comment]
Hi
I have the same issue.
It is the fresh installation  mailu 1.8 base on docker-compose on Ubuntu 20.04.3 LTS.
I followed instruction an after made command  docker-compose -p mailu exec admin flask mailu admin admin aaa.cc PASSWORD I received error:
`Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1243, in _execute_context
    self.dialect.do_execute(
  File "/usr/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: user.email

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.9/site-packages/flask/cli.py", line 894, in main
    cli.main(args=args, prog_name=name)
  File "/usr/lib/python3.9/site-packages/flask/cli.py", line 557, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.9/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/flask/cli.py", line 412, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/app/mailu/manage.py", line 76, in admin
    db.session.commit()
  File "/usr/lib/python3.9/site-packages/sqlalchemy/orm/scoping.py", line 162, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1026, in commit
    self.transaction.commit()
  File "/usr/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 493, in commit
    self._prepare_impl()
  File "/usr/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 472, in _prepare_impl
    self.session.flush()
  File "/usr/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2451, in flush
    self._flush(objects)
  File "/usr/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2589, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 129, in reraise
    raise value
  File "/usr/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2549, in _flush
    flush_context.execute()
  File "/usr/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/usr/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 586, in execute
    persistence.save_obj(
  File "/usr/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 239, in save_obj
    _emit_insert_statements(
  File "/usr/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 1119, in _emit_insert_statements
    result = cached_connections[connection].execute(
  File "/usr/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/usr/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1101, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1247, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/usr/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 383, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 128, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1243, in _execute_context
    self.dialect.do_execute(
  File "/usr/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: user.email
[SQL: INSERT INTO user (created_at, updated_at, comment, localpart, password, quota_bytes, quota_bytes_used, global_admin, enabled, enable_imap, enable_pop, forward_enabled, forward_destination, forward_keep, reply_enabled, reply_subject, reply_body, reply_startdate, reply_enddate, displayed_name, spam_enabled, spam_threshold, domain_name, email) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ('2021-09-09', None, None, 'admin', '{PBKDF2}$pbkdf2-sha512$25000$WOs9p7QWQqh1LgUAYAyBUA$5yxzKztCGb5HfqgD7.mnA491QHHktm8dhnc.ObRe0y2fvFeCQoJ8xdDYP9t1GyML8iRLANTaMuEghcxR1vXzNQ', 1000000000, 0, 1, 1, 1, 1, 0, '', 1, 0, None, None, '1900-01-01', '2999-12-31', '', 1, 80, 'aaa.cc', 'admin@aaa.cc')]
(Background on this error at: http://sqlalche.me/e/gkpj)
`
`~/mailu$ docker ps -a | grep mailu
c0a247e72c39   mailu/roundcube:1.8   "docker-php-entrypoi…"   32 minutes ago   Up 32 minutes (healthy)     80/tcp                                                                                                                                                                                                                                                                                                                                                                                                                              mailu_webmail_1
712410577f44   mailu/postfix:1.8     "/bin/sh -c /start.py"   32 minutes ago   Up 32 minutes (healthy)     25/tcp, 10025/tcp                                                                                                                                                                                                                                                                                                                                                                                                                   mailu_smtp_1
d9ae466cc1a9   mailu/dovecot:1.8     "/bin/sh -c /start.py"   32 minutes ago   Up 32 minutes (healthy)     110/tcp, 143/tcp, 993/tcp, 2525/tcp, 4190/tcp                                                                                                                                                                                                                                                                                                                                                                                       mailu_imap_1
f74fa78dfc0f   mailu/rspamd:1.8      "/bin/sh -c /start.py"   32 minutes ago   Up 32 minutes (healthy)     11332/tcp, 11334-11335/tcp                                                                                                                                                                                                                                                                                                                                                                                                          mailu_antispam_1
951bf182cbb0   mailu/admin:1.8       "/bin/sh -c /start.py"   35 minutes ago   Up 35 minutes (healthy)     80/tcp                                                                                                                                                                                                                                                                                                                                                                                                                              mailu_admin_1
22508d2b5375   mailu/clamav:1.8      "/bin/sh -c /start.py"   35 minutes ago   Up 35 minutes (healthy)     3310/tcp                                                                                                                                                                                                                                                                                                                                                                                                                            mailu_antivirus_1
de0f90afafef   mailu/unbound:1.8     "/bin/sh -c /start.py"   35 minutes ago   Up 35 minutes (healthy)     53/tcp, 53/udp                                                                                                                                                                                                                                                                                                                                                                                                                      mailu_resolver_1
0407ab053d64   redis:alpine          "docker-entrypoint.s…"   35 minutes ago   Up 35 minutes               6379/tcp                                                                                                                                                                                                                                                                                                                                                                                                                            mailu_redis_1
31012cb542a3   mailu/nginx:1.8       "/bin/sh -c /start.py"   35 minutes ago   Up 32 minutes (unhealthy)   xx.xx.xx.xx:25->25/tcp, ::1:25->25/tcp, xx.xx.xx.xx:80->80/tcp, ::1:80->80/tcp, xx.xx.xx.xx:110->110/tcp, ::1:110->110/tcp, xx.xx.xx.xx:143->143/tcp, ::1:143->143/tcp, xx.xx.xx.xx:443->443/tcp, ::1:443->443/tcp, xx.xx.xx.xx:465->465/tcp, ::1:465->465/tcp, xx.xx.xx.xx:587->587/tcp, ::1:587->587/tcp, xx.xx.xx.xx:993->993/tcp, ::1:993->993/tcp, 10025/tcp, xx.xx.xx.xx:995->995/tcp, ::1:995->995/tcp, 10143/tcp   mailu_front_1
`

`grep MAILU_VERSION docker-compose.yml mailu.env
docker-compose.yml:    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}nginx:${MAILU_VERSION:-1.8}
docker-compose.yml:    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}unbound:${MAILU_VERSION:-1.8}
docker-compose.yml:    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}admin:${MAILU_VERSION:-1.8}
docker-compose.yml:    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}dovecot:${MAILU_VERSION:-1.8}
docker-compose.yml:    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}postfix:${MAILU_VERSION:-1.8}
docker-compose.yml:    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}rspamd:${MAILU_VERSION:-1.8}
docker-compose.yml:    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}clamav:${MAILU_VERSION:-1.8}
docker-compose.yml:    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}roundcube:${MAILU_VERSION:-1.8}
`

**Comment by ghostwheel42** [comment]
Hi @DarekLin - this traceback is shown when the admin user you try to create is already present in the database, so it's probably not really a fresh install. I admit an error message would be better and I'll change this.

To replace the user run:
`docker-compose -p mailu exec admin flask mailu admin --mode update admin aaa.cc PASSWORD`

To see what's in the database run:
`docker-compose -p mailu exec admin flask mailu config-export`

Alex

**Comment by DarekLin** [comment]
Thanks Alex,
now is little bit better:
`docker-compose -p mailu exec admin flask mailu admin --mode update admin aaa.cc PASSWORD
updated admin password
`
But in the next step I can't call the /admin page.  I received  404 page not found.
The /webmail login page is working.

Also I can't connect to database:
`
mail:~/mailu$ docker-compose -p mailu exec admin flask mailu config-export
Usage: flask mailu [OPTIONS] COMMAND [ARGS]...
Try "flask mailu --help" for help.

Error: No such command "config-export".`

The help command returned only this options:
`Commands:
  admin          Create an admin user 'mode' can be: - 'create' (default)...
  advertise      Advertise this server against statistic services.
  alias          Create an alias
  alias-delete   delete alias
  config-update  sync configuration with data from YAML-formatted stdin
  domain         Create a domain
  password       Change the password of an user
  setlimits      Set domain limits
  setmanager     Make a user manager of a domain
  user           Create a user
  user-delete    delete user
  user-import    Import a user along with password hash.
`

I Installed mailu based on https://setup.mailu.io/1.8/  and of course I have switched on admin checkbox.

What is wrong?

**Comment by ghostwheel42** [comment]
Hi.
It's good that the `flask mailu admin` call is working as expected now - this shows it was not a clean install you were working on.
Sorry for mentioning the `flask mailu config-export` - this command is not in 1.8 (will be in the next version).
Alex
