### ISSUE TITLE
Cannot login: IMAP dies

### ISSUE THREAD

**Issue by elandorr** [Mailu/Mailu#1927]
## Before you open your issue
- [x] Check if no issue or pull-request for this already exists.
- [x] Check [documentation](https://mailu.io/master/) and [FAQ](https://mailu.io/master/faq.html). (Tip, use the search function on the documentation page)
- [x] You understand `Mailu` is made by volunteers in their **free time** — be conscise, civil and accept that delays can occur.
- [x] The title of the issue should be short and simple. It should contain specific terms related to the actual issue. Be specific while writing the title.

### Environment
 - [x] docker-compose
 - [ ] kubernetes
 - [ ] docker swarm

### Versions
1.7 ordinary standard setup

## Description
Login is broken hard after a recent update, please advise urgently as everything is dead right now!

## Replication Steps
try to login

## Expected behaviour
login....

## Logs

When a login is attempted this occurs: 

```
mailu-imap  | Aug 13 11:52:16 imap(emailaddress)<144><randomid/randomid>: Fatal: master: service(imap): child 144 killed with signal 11 (core not dumped - https://dovecot.org/bugreport.html#coredumps - set /proc/sys/fs/suid_dumpable to 2)

```

**Comment by elandorr** [comment]
If anyone reads this, this is an incredible problem right now and I regret not having made a backup first to downgrade. Literally this is quite life threatening if not fixed. It seems not only login is broken, but the entire stack, mails aren't even saved on disk even though they showed up in rspamd (before the 10 reboots..).

How does one downgrade the stack with the way the images are used? All one can select is '1.7' with the latest iteration obviously being broken.

**Comment by elandorr** [comment]
It seems not only login is broken, but the entire stack, mails aren't even saved on disk even though they showed up in rspamd (before the 10 reboots wiped the history..).

How does one downgrade the stack with the way the images are used? All one can select is '1.7' with the latest iteration obviously being broken. I massively regret not having backuped the entire thing first.

**Comment by nextgens** [comment]
Please file one issue per problem you think you have identified and stick to the report template.

It's very difficult to help you and work out what the problems are from the above... let alone what version of the software you are actually using.

If dovecot is segfaulting, we need a core file to investigate. Have you ruled out hardware problems on your end (multiple unrelated problems that you're the only one to experience)?

**Comment by elandorr** [comment]
> stick to the report template.

I did.

> let alone what version of the software you are actually using.

It says right there in my template-compliant initial post:

> Versions
> 1.7 ordinary standard setup

> If dovecot is segfaulting, we need a core file to investigate. 

If you tell me how to get it, I will provide it given it does not contain private information.

> Have you ruled out hardware problems on your end (multiple unrelated problems that you're the only one to experience)?

Yes, the hardware is fine. And if you read the post, you know that it works after updating to 1.8.  And that a specific update you recently pushed to 1.7 caused this.

If you don't put in any effort in even reading my absolutely template-compliant report then you don't motivate people to continue any further.

The way you use docker images means there is only one version to choose from, i.e., 1.7, or now, 1.8. Which I clearly stated in the initial post.
According to your documentation one is supposed to regularly update to the latest image using an ordinary docker pull - which does not provide any more detailed version numbering than 1.7 + the date of the pull. Which... you can see from the date of this post.



> Please file one issue per problem you think you have identified

Could you possibly be any more condescending?
