### ISSUE TITLE
Metrics for removing/demoting contributors

### ISSUE THREAD

**Issue by Diman0** [Mailu/Mailu#1932]
As discussed in the last meeting (#1582), I think we have to check who should still have access to the project based on some metrics.

Currently we have the following roles
- Project owner. A god who has full control over the mailu repository. Has access to project settings and can make any changes he wants. The project owner can also push directly to protected branches (e.g. master and the 1.x branches) Current project owners are:
  - Diman0
  - kaiyou
  - micw 
  - Nebukadneza
- SSH access to infra machine. Contributors can apply for SSH access to the infra machine which hosts the setup site, demo site and documentation site. For more info see [this link](https://github.com/Mailu/infra).
  - [People with access](https://github.com/Mailu/infra/tree/master/ssh)
  - Access is only required for making the new release available. .Env variables are used to configure version information.
  - People with SSH access have SUDO permissions on the server.
- Trusted reviewer and contributor. Trusted contributors require only a single review to have their PR merged.
  - https://github.com/Mailu/Mailu/blob/966b9cb91858f33d9800b75cbdf43e9056bf4e0a/.mergify.yml#L30
- Contributors - They are member of the contributors group. Regular contributors have the ability to review and merge PRs. They can also close issues and pull requests and modify the metadata for these (e.g. add milestone, tag etc). 
  - We have 15 people in this team. I will not list everything since some people have set their affiliation to private. See https://github.com/orgs/Mailu/people for more info

- outside collaborators - An outside collaborator is a person who isn't explicitly a member of your organization, but who has Read, Write, or Admin permissions to one or more repositories in your organization.
  -  We have 1 person who is a collaborator for the helm-chart repo project. 
- non contributors. Outside persons who can create issues and submit PRs. They can review a PR, but this review will not be used mergify. Only reviews from contributors apply for the mergify rules to trigger a bors r+ (build, test and merge).

## project owners
Ideally we make sure we always have at least 2 project owners. . I'd say that if a project owner provides a contribution at least once per year, we will not take action. If you are inactive for a year, then you are demoted to a contributor. If this means, we have less than 2 project owners, we ask someone from the contribution team to become a project owner. Under normal circumstances the special powers of a project owner are never required. 

## SSH Access
Any contributor can apply for this. For this reason I think people should only be removed when they are removed as contributor.

## trusted author
I'm not sure what metric to use here. Of course we will remove people who have often contributed bad code (or are malicious), or are removed as contributor. 
Recently added people have not provided any contributions yet. Should we remove these persons and potentially add them after a couple of PRs?
Being removed only means you need 2 reviews, but still can provide reviews on PRs. My gut feeling is to remove everyone from the trusted authors who did not recently contribute to the project. Let's say for the last year. 

## contributors
For contributors I'd say we use the same 1 year metric? 
If you have not been active for 1+ year, then you are removed. Active means you have created or commented on an issue or pull request. Or do we want to keep people indefinitely? We have issues with getting reviews on time. However if someone did not review for a year, why would this person start reviewing after 1 year and 1 day?
Do we want to have a minimum amount of people? E.g. If we agree on 5, then we will not remove people if this results in less than 5 contributors. Even if this contributor has been inactive/away for 1+ year.

Should we exempt muhlemmer and kaiyou from this rule? Kaiyou is the original mailu project founder. I think he is also the owner of the mailu domain name. He was fine with being removed from the project since this is normal for an opensource project. If I remember correctly, muhlemmer is the person who provides the VPS for the [infra project](https://github.com/Mailu/infra). The machine which runs the demo server and setup utility.

Please share your thoughts on what metrics to use for project owners, trusted authors, contributors and SSH access

**Comment by nextgens** [comment]
My take on it:
- ssh access: this shouldn't be granted easily; I'd restrict it to trusted authors that request it
- trusted authors: I think that this should only be granted to repeat contributors (after a contributor has submitted several PRs that got merged). I do think that this status should be revoked after a period of innactivity
- contributors: I'm not sure this should ever be revoked (what's the rationale here?); I think that the documentation should make it clear how you "get" that status (by reviewing/commenting on PRs before having the status)

**Comment by Diman0** [comment]
> Yes, maybe we could keep the current list of contributors. The rationale was that it reflects who is currently still involved in the project. Why have someone one this list if he is not going to contribute anymore?
> 
>     * project owner. Remove people who are inactive for 1+ year. We keep a minimum of 2.
> 
>     * ssh access. Restricted to trusted authors ( I think this is already the case).  Remove anyone who has been inactive for 1+ year. someone can still be given access back if he comes back after a 1+ year.
> 
>     * Trusted authors. For now remove everyone who has not contributed yet to the project. We will have to discuss if we want to retract this after some time. And if we do, after how much time.
> 
>     * Contributors. Let's keep everyone for now.
> 
> 
> Nobody comments on this subject. It is difficult to make a consensus like this.

I have applied all action steps I mentioned. For now this is fine. Let's revisit this end next year again.
