### ISSUE TITLE
Is there any way to give high priority to some emails?

### ISSUE THREAD

**Issue by ghorbani-mohammad** [Mailu/Mailu#1933]
Hi, in our website we use Mailu for sending two types of emails. We want to give more priority to Type A mails than Type B mails. 
How I can achieve this? Thanks.

**Comment by ghostwheel42** [comment]
Hi. What do you want to prioritize?
You can use a email header to make your email client highlight the email in your inbox:

X-Priority: 1 (Highest)
X-MSMail-Priority: High
Importance: High
