### ISSUE TITLE
Some repeat DNS lookups are introducing TOCTOU problems

### ISSUE THREAD

**Issue by nextgens** [Mailu/Mailu#1938]
As discussed in the regular project meeting, I'm opening an issue for it: this will have to be addressed before we can consider merging #1716

Time Of Check Time of Use (or race conditions) are a serious problem: we want operations to be atomic (either succeed or fail but not have undetermined state).

#1716 is proposing to change the behaviour from "lookup once at container start-up" to "lookup each time we need it"

The codebase should be audited to ensure that should a lookup fail somewhere it won't lead to any operation being "half-completed".

One obvious occurrence of such problem is the sieve scripts:
- https://github.com/Mailu/Mailu/blob/master/core/dovecot/conf/ham.script
- https://github.com/Mailu/Mailu/blob/master/core/dovecot/conf/spam.script
where any failure in DNS resolution may lead to inconsistent state (that won't necessarily raise an error!).

**Comment by lub** [comment]
How are race conditions special with regards to DNS lookups? Resolving some name during startup doesn't guarantee availability at the time of a request.

I think it's reasonable to assume the docker (or kubernets) internal DNS to be available on a healthy system and thus just accept is as dependency.

**Comment by nextgens** [comment]
We've talked about it during the dev meeting: it's fine and we'll do dynamic resolution.
