### ISSUE TITLE
Mailu configuration server not accessible via IPv6

### ISSUE THREAD

**Issue by aahlborg** [Mailu/Mailu#1942]
### Environment
Mailu setup server, https://setup.mailu.io/1.8/

### Versions
Currently deployed server.

## Description
Downloading the generated files via IPv6 doesn't work. The download times out after two minutes and wget reverts to IPv4.

    root@localhost:~# wget https://setup.mailu.io/1.8/file/94e9b53e-f43f-4837-bc4c-e841c53cfa31/docker-compose.yml
    --2021-08-23 19:03:10--  https://setup.mailu.io/1.8/file/94e9b53e-f43f-4837-bc4c-e841c53cfa31/docker-compose.yml
    Resolving setup.mailu.io (setup.mailu.io)... 2a01:4f8:c2c:f707::1, 78.47.92.244
    Connecting to setup.mailu.io (setup.mailu.io)|2a01:4f8:c2c:f707::1|:443... failed: Connection timed out.
    Connecting to setup.mailu.io (setup.mailu.io)|78.47.92.244|:443... connected.
    HTTP request sent, awaiting response... 200 OK
    Length: 2316 (2.3K) [application/text]
    Saving to: ‘docker-compose.yml’
    
    docker-compose.yml.2  100%[=========================>]   2.26K  --.-KB/s    in 0s      
    
    2021-08-23 19:05:20 (54.0 MB/s) - ‘docker-compose.yml’ saved [2316/2316]

The server responds to ping on IPv6 so the problem is probably related to the web server configuration.

    root@localhost:~# ping setup.mailu.io
    PING setup.mailu.io(test.mailu.io (2a01:4f8:c2c:f707::1)) 56 data bytes
    64 bytes from test.mailu.io (2a01:4f8:c2c:f707::1): icmp_seq=1 ttl=56 time=4.19 ms

## Replication Steps

* Generate a configuration using the online wizzard.
* Run the wget command to download the files on a computer with IPv6 configured. I'm using a standard Linode Ubuntu server.

## Expected behaviour
Files can be downloaded from the server over IPv6.

## Logs
-

**Comment by Diman0** [comment]
This is the wrong location to report these kind of issues. Please report issues about the setup website in the infra project (https://github.com/Mailu/infra/issues).
