### ISSUE TITLE
Reply to a letter from a subaddress

### ISSUE THREAD

**Issue by hz61p1** [Mailu/Mailu#1948]
Now, if an email has been sent to a subaddress, for example, ```user+subadress@domain.tld``` and when you try to answer it, the address of the poisoner will be indicated ```user@domain.tld``` not ```user+subadress@domain.tld```. Is it possible to reply from the same address to which the letter was sent?

**Comment by ghostwheel42** [comment]
Hi. It is up to the user agent how to handle the subaddress part.
You should be able to configure multiple identities when using the optional webmail component of mailu. 
Alex
