### ISSUE TITLE
Links to specific areas of the admin panel do not work after login

### ISSUE THREAD

**Issue by jukey** [Mailu/Mailu#195]
All the sections in the control panel do have specific URLs like:

- `https://domain.tld/admin/user/forward` for *Auto-forward* or
- `https://domain.tld/admin/user/password` for *Update password*

These links are working fine in case the user is already authenticated. However in case the user is not already authenticated a login screen is shown and the URL is transformed into something like:

- `https://domain.tld/admin/login?next=%2Fadmin%2Fuser%2Fforward` for *Auto-forward*
- `https://domain.tld/admin/login?next=%2Fadmin%2Fuser%2Fpassword` for *Update password*

After logging in I always end up on the general setting page where I e.g. can adjust the spam threshold.

It seems there is a functionality to forward users to the right section of the control panel once they are logged in but it does not work.

**Comment by kaiyou** [comment]
Indeed, that ``next`` parameter is automatically generated by Flask-Login but never used anywhere in the code. There are probably some security issues at stake. Once we are sure it is fine, I see no reason why we should not redirect after a successful login.
