### ISSUE TITLE
How to use SMTP

### ISSUE THREAD

**Issue by zoom360** [Mailu/Mailu#1955]
Dear,
I send mail with PHPmailer using SMTP Mailu. But it's not work. Configuration based on "Client setup".

Mail protocol | SMTP( 465 (TLS) or 587 (STARTTLS))
Host: mail.domain.com
Email: client@domain.com
Password: email_password

**Comment by timm0e** [comment]
Does your setup work with other email clients?

**Comment by zoom360** [comment]
I only installed Mailu 1.8

**Comment by timm0e** [comment]
I'd suggest checking with another mail client first to check if the issue is on the PHPMailer side or if it's an issue with your Mailu installation.

If PHPMailer gives you any sort of error message, it would also be helpful if you posted it here

**Comment by zoom360** [comment]
I am using gmail SMTP for phpmailer and it works perfectly.

**Comment by danipiresk2k13** [comment]
I have same issue on my server.

**Comment by ghostwheel42** [comment]
Hi @danipiresk2k13 
I've tested this using the default php composer image (https://hub.docker.com/_/composer) and the PHPMailer example code:
https://github.com/PHPMailer/PHPMailer#a-simple-example
Everything is working as expected with a fresh Mailu 1.8 install.

As timm0e wrote: 
> If PHPMailer gives you any sort of error message, it would also be helpful if you posted it here

Setting `$mail->SMTPDebug = SMTP::DEBUG_SERVER`  seems to be a good start.

**Comment by zoom360** [comment]
> Hi @danipiresk2k13 I've tested this using the default php composer image (https://hub.docker.com/_/composer) and the PHPMailer example code: https://github.com/PHPMailer/PHPMailer#a-simple-example Everything is working as expected with a fresh Mailu 1.8 install.
> 
> As timm0e wrote:
> 
> > If PHPMailer gives you any sort of error message, it would also be helpful if you posted it here
> 
> Setting `$mail->SMTPDebug = SMTP::DEBUG_SERVER` seems to be a good start.

I reconfigured it and it worked fine
