### ISSUE TITLE
Set recipient_delimiter

### ISSUE THREAD

**Issue by Znafon** [Mailu/Mailu#196]
Hi,

on many mail systems, it is possible to send mail to mail+tag@domain.com to help categorize mails.
It's not available by default on mailu, I think it would be good to set `recipient_delimiter = +` in the postfix configuration and to let administrator disable this parameter or change the characther by using an environment variable.

Thanks,
Rémi

**Comment by pesimon** [comment]
this is somehow releated to #164

**Comment by Znafon** [comment]
Yes it is, it's the exact same idea with configuration.

Thanks
