### ISSUE TITLE
Postfix Stops Working in k8s

### ISSUE THREAD

**Issue by J-Ha** [Mailu/Mailu#1960]
### Environment
 - [ ] docker-compose
 - [x] kubernetes
 - [ ] docker swarm

### Versions
1.7 
1.8

## Description
mailu/postfix stops working, no changes where made.
Container is now in crashloop

```
Aug 28 11:45:57 mail postfix[60]: Postfix is running with backwards-compatible default settings
Aug 28 11:45:57 mail postfix[60]: See http://www.postfix.org/COMPATIBILITY_README.html for details
Aug 28 11:45:57 mail postfix[60]: To disable backwards compatibility use "postconf compatibility_level=2" and "postfix reload"
Aug 28 11:45:58 mail postfix/postfix-script[126]: starting the Postfix mail system
Aug 28 11:45:58 mail postfix/master[127]: fatal: remove public/pickup: Invalid argument
```

**Comment by nextgens** [comment]
Are you using helms chart? If so please report a bug on https://github.com/Mailu/helm-charts/
If not please see https://mailu.io/1.8/kubernetes/mailu/index.html

This sounds like a permission problem (ownership/UID of the data files)

**Comment by J-Ha** [comment]
yes im using the helmchart, was running since 7 moth without any problems.
stops working yesterday.

and it seems to be not an ownership problem, i already googled the issue and got results for permissions problems.
but the log message does not say, permission denied.

it says invalid argument.

**Comment by ulm0** [comment]
Hi @J-Ha have you any solution yet? i'm facing this issue with a fresh install via helm

**Comment by J-Ha** [comment]
nope, still the same, tried several things to get rid of it.
found this issue: https://github.com/Mailu/helm-charts/issues/54
tried to mount a not NFS volume to the Postfix container, still the same.

**Comment by HaleyACS** [comment]
I also had a similar behavior on my end due to my DNS not being correctly configured.
I have enabled DNSSEC on my domains, but the DS was not propagated for one domain yet.
This coredns from k3s (kubernetes lite) did invalidate all requests for my domain due to that, and start.py could not find the domain name/IP addresses to configure the IP's for postfix.
it was in the strace output somehow. Don't have the exact syntax.

To troubleshoot that I have done the following.
Edit the deployment for postfix with: kubectl edit deployment mailu-postfix -n mailu-mailserver
and modified the startup command like this:
```
--- postfix-deployment.yaml     2021-08-31 11:55:37.259773986 +0200
+++ postfix-deployment.yaml-manual      2021-08-31 11:53:39.159111358 +0200
@@ -22,7 +22,9 @@
       containers:
       - name: postfix
         image: mailu/postfix:1.8
-        #imagePullPolicy:  Always
+        command: ["/bin/sleep"]
+        args: ["86400"]
+        imagePullPolicy:  Always
         volumeMounts:
           - mountPath: /queue
             name: data
```
Then I went inside the pod with (replace with your own pod-id).
```
kubectl exec --stdin --tty mailu-postfix-849b68b8f8-s6jtt -n mailu-mailserver -- /bin/sh
```
Once inside the container, install "strace" and start it all using strace in front.
```
apk add strace
```

and start the postfix process with: 
```
strace /usr/bin/python3 /start.py
```
It should show you where it hangs. Eventually you can provide a log/details here!

**Comment by Lerentis** [comment]
I have the same problem. 
```
INFO:MAIN:MTA-STS daemon starting...
2021-09-06 18:21:38 INFO     MAIN: MTA-STS daemon starting...
INFO:MAIN:Starting eventloop...
INFO:MAIN:uvloop is not available. Falling back to built-in event loop.
2021-09-06 18:21:38 INFO     MAIN: Starting eventloop...
2021-09-06 18:21:38 INFO     MAIN: uvloop is not available. Falling back to built-in event loop.
INFO:MAIN:Eventloop started.
2021-09-06 18:21:38 INFO     MAIN: Eventloop started.
INFO:MAIN:Server started.
2021-09-06 18:21:38 INFO     MAIN: Server started.
INFO:MAIN:Proactive policy fetching is disabled.
2021-09-06 18:21:38 INFO     MAIN: Proactive policy fetching is disabled.
Sep 06 18:21:39 mail postfix[63]: Postfix is running with backwards-compatible default settings
Sep 06 18:21:39 mail postfix[63]: See http://www.postfix.org/COMPATIBILITY_README.html for details
Sep 06 18:21:39 mail postfix[63]: To disable backwards compatibility use "postconf compatibility_level=3.6" and "postfix reload"
Sep 06 18:21:40 mail postfix/postfix-script[358]: starting the Postfix mail system
Sep 06 18:21:40 mail postfix/master[359]: fatal: remove public/pickup: Invalid argument
```

already tried to have a look with strace, but there was not really that much information in there. anything i should look out for @HaleyACS ?
The log holds like this:
```
Sep 06 19:46:47 mail postfix/postfix-script[364]: starting the Postfix mail system
[{WIFEXITED(s) && WEXITSTATUS(s) == 1}], 0, NULL) = 298
rt_sigaction(SIGINT, {sa_handler=0x7f63c84e035f, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f63c8790c8b}, NULL, 8) = 0
rt_sigaction(SIGQUIT, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f63c8790c8b}, NULL, 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=298, si_uid=0, si_status=1, si_utime=0, si_stime=0} ---
madvise(0x7f63c8318000, 4096, MADV_FREE) = 0
madvise(0x7f63c824f000, 4096, MADV_FREE) = 0
madvise(0x7f63c8251000, 4096, MADV_FREE) = 0
madvise(0x7f63c8253000, 4096, MADV_FREE) = 0
munmap(0x7f63c824e000, 28672)           = 0
madvise(0x7f63c8248000, 4096, MADV_FREE) = 0
madvise(0x7f63c824a000, 4096, MADV_FREE) = 0
madvise(0x7f63c824c000, 4096, MADV_FREE) = 0
munmap(0x7f63c8247000, 28672)           = 0
madvise(0x7f63c8241000, 4096, MADV_FREE) = 0
madvise(0x7f63c8243000, 4096, MADV_FREE) = 0
madvise(0x7f63c8245000, 4096, MADV_FREE) = 0
munmap(0x7f63c8240000, 28672)           = 0
madvise(0x7f63c8236000, 4096, MADV_FREE) = 0
madvise(0x7f63c8238000, 4096, MADV_FREE) = 0
madvise(0x7f63c823a000, 4096, MADV_FREE) = 0
munmap(0x7f63c8235000, 28672)           = 0
madvise(0x7f63c822f000, 4096, MADV_FREE) = 0
madvise(0x7f63c8233000, 4096, MADV_FREE) = 0
madvise(0x7f63c822a000, 4096, MADV_FREE) = 0
madvise(0x7f63c822c000, 4096, MADV_FREE) = 0
madvise(0x7f63c8228000, 4096, MADV_FREE) = 0
munmap(0x7f63c8227000, 28672)           = 0
madvise(0x7f63c8219000, 4096, MADV_FREE) = 0
madvise(0x7f63c821b000, 4096, MADV_FREE) = 0
madvise(0x7f63c821d000, 4096, MADV_FREE) = 0
munmap(0x7f63c8218000, 28672)           = 0
madvise(0x7f63c8221000, 4096, MADV_FREE) = 0
madvise(0x7f63c8223000, 4096, MADV_FREE) = 0
munmap(0x7f63c823c000, 16384)           = 0
wait4(24, 0x7fff5333fb84, WNOHANG, NULL) = 0
wait4(25, 0x7fff5333fb84, WNOHANG, NULL) = 0
wait4(24, 0x7fff5333fb84, WNOHANG, NULL) = 0
wait4(25, 0x7fff5333fb84, WNOHANG, NULL) = 0
getpid()                                = 22
wait4(24, 
```

**Comment by nextgens** [comment]
@Lerentis please try adding -f to strace

**Comment by nextgens** [comment]
The best guess on #mailu-dev so far is that it is a DNS-related issue. Can you share a packet capture covering "port 53" while you attempt to start the container please?

**Comment by nextgens** [comment]
@J-Ha @ulm0 @Lerentis any news on this? Have you retried recently?

**Comment by Lerentis** [comment]
Hi @nextgens ,
sorry for the delay. i did a bit of troubleshooting with the information that i got from strace and checked the DNS traffic. there was indeed something on the DNS side that returned NXDOMAIN. i removed this DNS server and all pods are starting green now. thanks the the help y'all
