### ISSUE TITLE
Can Mail run on a AWS EC2 instance which already has my php site running 24/7?

### ISSUE THREAD

**Issue by inglesuniversal** [Mailu/Mailu#197]
Hello: I have a webste at AWS EC2 instance... and I have my Email service under WORKMAIL which is AWS Email Service... The thing is that with 7 tiny account I pay over 15 USD a month... Do you think that I can run and install your script? Can I run your script with my site which is currently hosted there? How do I go about setting up the MX files or any other files that Amazon created for me before? Can I host my Email from my second AWS EC2 instance without causing any server errors? thanks.

**Comment by kaiyou** [comment]
The question that remains is: where would you install Mailu? If you plan on installing it on EC2 and you host a decent amount of emails, you will probably end up paying more than 15USB/mth.

Regarding the server errors and MX, I am not an Amazon Workmail expert and cannot really how you could export your mailboxes, who manages your DNS and MX. Maybe someone could jump in with such information.

Anyway, what I would point out is: if you have the proper skills to manage a Mailu instance, you probably will figure out migrating your mailboxes and managing your MX. If you do not have the knowledge for managing your DNS zone or do standard sysadmin tasks, it would probably be a really interesting experience to setup the stack required for Mailu to run properly, but I wouldn't rely on it for any critical email accounts in the begging at least.
