### ISSUE TITLE
DEFER_ON_TLS_ERROR in mailu.env doesn't appear to be applied.

### ISSUE THREAD

**Issue by JCBird1012** [Mailu/Mailu#1973]
Thank you for opening an issue with Mailu. Please understand that issues are meant for bugs and enhancement-requests.
For **user-support questions**, reach out to us  on [matrix](https://matrix.to/#/#mailu:tedomum.net).

To be able to help you best, we need some more information.

## Before you open your issue
- [X] Check if no issue or pull-request for this already exists.
- [X] Check [documentation](https://mailu.io/master/) and [FAQ](https://mailu.io/master/faq.html). (Tip, use the search function on the documentation page)
- [X] You understand `Mailu` is made by volunteers in their **free time** — be conscise, civil and accept that delays can occur.
- [X] The title of the issue should be short and simple. It should contain specific terms related to the actual issue. Be specific while writing the title.

### Environment
 - [X] docker-compose
 - [ ] kubernetes
 - [ ] docker swarm

### Versions
master (d464187)

## Description
DEFER_ON_TLS_ERROR in mailu.env doesn't appear to be applied. I've set this environment variable to "false" and my emails still appear to be deferred according to the SMTP container. 
`(status=deferred (client TLS configuration problem))`

I've set this to "false" because MTA-STS isn't as widely deployed as one would hope, and I don't want my emails blackholed and deferred until my destination's policy is published (which may be never)... 

## Replication Steps
In mailu.env - set `DEFER_ON_TLS_ERROR=false`, reload containers, then try sending an email to a domain without an MTA-STS policy...

Then output logs for the SMTP container and note the message deferral.

## Expected behaviour
I expect the email to continue being sent despite the MTA-STS error.

## Logs
```
smtp_1       | Sep 09 13:42:08 mail postfix/cleanup[416]: 85B6147DDA: message-id=<074C120E-8E94-4753-8F7D-ECE60F3AEDB4@jcaicedo.com>
smtp_1       | Sep 09 13:42:09 mail postfix/qmgr[391]: 85B6147DDA: from=<jonathan@jcaicedo.com>, size=6074, nrcpt=1 (queue active)
smtp_1       | Sep 09 13:42:09 mail postfix/smtp[417]: warning: connect to /tmp/mta-sts.socket: No such file or directory
smtp_1       | Sep 09 13:42:09 mail postfix/smtp[417]: warning: table socketmap:unix:/tmp/mta-sts.socket:postfix lookup error: No such file or directory
smtp_1       | Sep 09 13:42:09 mail postfix/smtp[417]: warning: socketmap:unix:/tmp/mta-sts.socket:postfix lookup error for "ssl-tools.net"
smtp_1       | Sep 09 13:42:09 mail postfix/smtp[417]: warning: smtp_tls_policy_maps, next-hop destination "ssl-tools.net": policy table lookup error
smtp_1       | Sep 09 13:42:09 mail postfix/smtp[417]: warning: TLS policy lookup for ssl-tools.net/ssl-tools.net: client TLS configuration problem
smtp_1       | Sep 09 13:42:09 mail postfix/smtp[417]: warning: TLS policy lookup for ssl-tools.net/ssl-tools.net: client TLS configuration problem
smtp_1       | Sep 09 13:42:09 mail postfix/smtp[417]: 85B6147DDA: to=<check@ssl-tools.net>, relay=none, delay=1.1, delays=1/0.03/0.01/0, dsn=4.7.5, status=deferred (client TLS configuration problem)
```

**Comment by nextgens** [comment]
@JCBird1012 sorry about this, I've introduced that bug...

FYI this configuration option is only useful for domains that publish a misconfigured policy. A domain without policy (the majority as you've pointed out) should get delivered to as before, regardless of how the configuration is set.

**Comment by leolivier** [comment]
Hi,
I currently have the same issue as above (TLS error when sending to gmail !) with the same error about /tmp/mta-sts.socket:postfix file not existing
I tried DEFER_ON_TLS_ERROR=false in mailu.env but mails still get defered 
@nextgens I don't get your answer about misconfigured policy: is it my domain which would be misconfigured or gmail one (which I don't think is :)
Also, it worked well before, I didn't change the config but only moved to the new beta images for arm. So probably an issue here but I will retry older versions to make sure.

**Comment by nextgens** [comment]
> Hi, I currently have the same issue as above (TLS error when sending to gmail !) with the same error about /tmp/mta-sts.socket:postfix file not existing

That means that the mta-sts daemon doesn't run. It's started at https://github.com/Mailu/Mailu/blob/d931cbd528564e93451d0d6b70f358260285d29b/core/postfix/start.py#L39 ... find why this isn't running.

**Comment by leolivier** [comment]
Thanks @nextgens 
Well, actually, I have the following trace that explains why:
```
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/start.py", line 38, in start_mta_sts_daemon
    from postfix_mta_sts_resolver import daemon
  File "/usr/lib/python3.9/site-packages/postfix_mta_sts_resolver/daemon.py", line 13, in <module>
    from .proactive_fetcher import STSProactiveFetcher
  File "/usr/lib/python3.9/site-packages/postfix_mta_sts_resolver/proactive_fetcher.py", line 7, in <module>
    from postfix_mta_sts_resolver.resolver import STSResolver, STSFetchResult
  File "/usr/lib/python3.9/site-packages/postfix_mta_sts_resolver/resolver.py", line 6, in <module>
    import aiodns
  File "/usr/lib/python3.9/site-packages/aiodns/__init__.py", line 4, in <module>
    import pycares
  File "/usr/lib/python3.9/site-packages/pycares/__init__.py", line 2, in <module>
    from ._cares import ffi as _ffi, lib as _lib
ModuleNotFoundError: No module named 'pycares._cares'
2022-08-31T09:06:47.428593+00:00 f2e69a26925d postfix[57]: Postfix is running with backwards-compatible default settings
2022-08-31T09:06:47.428814+00:00 f2e69a26925d postfix[57]: See http://www.postfix.org/COMPATIBILITY_README.html for details
2022-08-31T09:06:47.428977+00:00 f2e69a26925d postfix[57]: To disable backwards compatibility use "postconf compatibility_level=3.6" and "postfix reload"
```
so linked to pycares and maybe the same issue I found in #2383 (last comments), I will check and tell @Diman0
