### ISSUE TITLE
demo: Wrong e-mail or password

### ISSUE THREAD

**Issue by AndreMarschalek** [Mailu/Mailu#1979]
no login possible with the demo credentials mentioned at https://mailu.io/1.8/demo.html

**Comment by ghostwheel42** [comment]
Confirmed.
We'll try to fix this ASAP.

**Comment by lub** [comment]
Login should be possible again. Can you test it again @AndreMarschalek ?

**Comment by AndreMarschalek** [comment]
confirm its working
