### ISSUE TITLE
Custom paths for the certificates

### ISSUE THREAD

**Issue by 2tefan** [Mailu/Mailu#1995]
### Environment
 - [x] docker-compose

### Version
`1.8`

## Description
It would be nice to have an environmental variable to set a location for the certificates instead of just putting them into `/certs`.

## Expected behaviour
To have two environmental variables for example `TLS_CERT_PATH` and `TLS_KEYPAIR_PATH`.

## Workaround
Even if the [tls.conf](https://github.com/Mailu/Mailu/blob/52361962885506ea479534a314f6429e8b95bc49/core/nginx/conf/tls.conf) is overwritten by the new path, the [config.py](https://github.com/Mailu/Mailu/blob/52361962885506ea479534a314f6429e8b95bc49/core/nginx/config.py) is checking for the certificate with the hardcoded `/certs`. And as there are no certificates it will just skip TLS :cry:.

My workaround is to (ab)use `TLS_CERT_FILENAME` and `TLS_KEYPAIR_FILENAME`, as I set them to `../new/custom/folder/xyz.pem`. This way it escapes the `/certs` directory, but I am not sure, that this is intended.

**Comment by ghostwheel42** [comment]
Hi @2tefan - there's no need to specify a different path for the volume _inside_ the container.
You can edit the docker-compose.yml and point the /certs mount wherever you want.
```
    volumes:
      - "/source/path/on/the/host:/certs"
```
So it's always /certs inside the container.
