### ISSUE TITLE
Redis port changing

### ISSUE THREAD

**Issue by 2andgi** [Mailu/Mailu#2001]
Ability to change redis port in some cases

**Comment by lub** [comment]
You can already overwrite it with `REDIS_ADDRESS=redis:<port>`

Is this not sufficient?

https://mailu.io/master/configuration.html#infrastructure-settings

**Comment by 2andgi** [comment]
Was trying 
HOST_REDIS=redis:<port>
REDIS_ADDRESS=redis:<port>

I assume, can't resolve correct host
webmail frontend started, but at login process generate error with connection to imap server

**Comment by 2andgi** [comment]
to get It worked, additionally needed to change  manually redis container with:
example:6378
`    command: --port 6378
    ports:
      - 6378:6379
    expose:
      - "6378"`

**Comment by leim** [comment]
what show i do if my redis has password
