### ISSUE TITLE
Docker compose upgrade from 1.x to 2.x can result in non-working Mailu

### ISSUE THREAD

**Issue by Infides** [Mailu/Mailu#2003]
### Versions
Mailu 1.8
Docker compose 2.0.1

## Description
With the recent upgrade of Docker Compose from version 1.x to 2.x many things changed and it seems that this is also the case for the parser of the environment file. If there a spaces in some of the settings, docker compose will not start and will complain with "key cannot contain a space". For me this was the case with "WELCOME_SUBJECT" and "WELCOME_BODY" in the mailu.env file. A simple and straight forward solution was to put the settings into quotes. As these values were directly taken from the configurator this could affect new users.
See also this issue here from docker compose: https://github.com/docker/compose/issues/8736

## Replication Steps
Install the latest docker compose (2.0.1) and make an environment file with a setting which contain spaces.

## Expected behaviour
"docker compose" should not complain about spaces in settings. Therefore all settings with spaces should be inside quotes.

**Comment by Diman0** [comment]
Looks like the issue in the [dotenv parser](https://github.com/docker/compose/issues/8763) is resolved. I'm closing this issue.
