### ISSUE TITLE
How do I change the language of the Admin UI?

### ISSUE THREAD

**Issue by iskycc** [Mailu/Mailu#2009]
I am a Mailu user using Docker-compose. 

How to change the language of the Admin UI?

 I don't see an option to switch languages.

 I need to display Chinese, but it's In English. 

Notice that this project has Chinese translation, how should I open it?

I didn't find any questions in the documentation either.

Thanks.

**Comment by ghostwheel42** [comment]
In version 1.8 there's no possibility to change the language in the user interface. You have to change your browser's language preferences (found somewhere in your browser's settings).
In version 1.9 (not released yet) there's a button in the upper right corner. See here: [https://test.mailu.io/admin/ui/](demo server)
Alex

**Comment by ghostwheel42** [comment]
I've checked 1.9 and yes, sometimes with some browser switching the language does nothing. That's a bug.
