### ISSUE TITLE
Certbot attempted to renew, failed, domain is throttled

### ISSUE THREAD

**Issue by trueserve** [Mailu/Mailu#202]
Today I started receiving notifications that my cert was expired. Looking into it, this is what I found.
1. It looks like renewals were attempted since Apr 19th every day. I can tell by a new file created every day in /certs/keys.
2. It looks like they may have succeeded, at least in part; attempting renewal manually, it seems my domain is throttled and I cannot get a cert now.
3. In /certs/archive/<domain>, there were 15 privkey.pem listed. Other than the live one (privkey1.pem), they were all 0 byte files.
4. Thinking this was a problem with a container or dependency, I pulled the latest Mailu version today. So I do not know what logs are available for me to look at now. (It would be nice if Mailu kept important task logs persistent and available through the web interface.)

So now I have a domain with an expired cert, I cannot renew it. I also had to restart the nginx container to have a working webinterface again.

Any idea what I should look at?

**Comment by trueserve** [comment]
Looks like I might be out of throttle. There's a lot of logged communication, and then this failure. Here is the relevant except from from /tmp/letsencrypt.log:

````
2017-05-05 02:00:08,262:DEBUG:certbot.storage:Writing new private key to /certs/archive/<domain>/privkey2.pem.
2017-05-05 02:00:08,264:DEBUG:certbot.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/certbot/main.py", line 755, in main
    return config.func(config, plugins)
  File "/usr/local/lib/python3.6/site-packages/certbot/main.py", line 682, in certonly
    lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
  File "/usr/local/lib/python3.6/site-packages/certbot/main.py", line 77, in _get_and_save_cert
    renewal.renew_cert(config, domains, le_client, lineage)
  File "/usr/local/lib/python3.6/site-packages/certbot/renewal.py", line 306, in renew_cert
    lineage.save_successor(prior_version, new_cert, new_key.pem, new_chain, config)
  File "/usr/local/lib/python3.6/site-packages/certbot/storage.py", line 1084, in save_successor
    f.write(new_privkey)
TypeError: write() argument must be str, not bytes
````

So my guess is a Python3 vs Python2 problem? A bug in certbot (wouldn't be the first)?

**Comment by ofthesun9** [comment]
I was hit by the same issue (thanks for posting and warning btw).
I think that the cerbot provided in the container is too old. I couldn't install a new one with "pip install certbot" so I tried something else :

$ docker-compose exec admin bash
within the admin container:
$ wget https://dl.eff.org/certbot-auto
$ chmod a+x ./certbot-auto
$ certbot-auto certonly -n --work-dir /tmp --logs-dir /tmp --config-dir /certs --standalone --agree-tos --preferred-challenges http --email xxxx@vmaltair.ddns.net -d vmaltair.ddns.net --http-01-port 8081

**Comment by ofthesun9** [comment]
After digging a little bit, I could figure that running the following shall do the trick:
$ pip install certbot --upgrade

**Comment by trueserve** [comment]
Confirming that the upgrade command updated certbot and resolved this issue. I don't know what is necessary for a permanent fix though.

**Comment by kaiyou** [comment]
The issue is related to an old version of certbot being installed and patched due to a bug at the time. Dependencies have upgraded as well and it is time to get back to the official certbot upstream.

**Comment by kaiyou** [comment]
This was just pushed as well as moving stable to `1.4`.
