### ISSUE TITLE
Manager can't designate someone as manager

### ISSUE THREAD

**Issue by fabiorauber** [Mailu/Mailu#203]
I don't know it it is the intended behaviour, but someone that has the Manager role cannot desginate another someone from the same domain as Manager. In my opinion, it would be beneficial to be able to delegate the authority of being a Manager, without needing to ask the Super Administrator to do that.

**Comment by kaiyou** [comment]
This was initially an intended behavior. Could anyone else provide feedback on the matter?

**Comment by curry684** [comment]
Makes sense from a shared security perspective. In hosting scenarios you will likely want to make customer domains fully self-managed, and if the customer wants to share those rights with a colleague, including the privilege of being able to demote the original manager, he should only do it if he fully trusts that colleague.

Alternatively you could also differentiate with a simple boolean flag between Owner (SuperAdmin or Owner assigned) and Manager (Owner assigned). Technically they would be the same, but Owners would be unmanageable by Managers. This would allow customer level delegation without risking hijacks, yet they could still appoint a highly trusted colleague as fellow Owner and for example an external IT guy as Manager.

**Comment by kaiyou** [comment]
Agreeing with @curry684. I believe a decent implementation would be to first change the behavior, then add the "owner" concept.
