### ISSUE TITLE
Upgrade Roundcube to 1.5

### ISSUE THREAD

**Issue by tgrelka** [Mailu/Mailu#2031]
## Before you open your issue
- [x] Check if no issue or pull-request for this already exists.
- [x] Check [documentation](https://mailu.io/master/) and [FAQ](https://mailu.io/master/faq.html). (Tip, use the search function on the documentation page)
- [x] You understand `Mailu` is made by volunteers in their **free time** — be conscise, civil and accept that delays can occur.
- [x] The title of the issue should be short and simple. It should contain specific terms related to the actual issue. Be specific while writing the title.

### Environment
 - [x] docker-compose
 - [x] kubernetes
 - [x] docker swarm

### Versions
Since this is not a bug report, I’m not sure if you need my current version.

## Description
Currently, Mailu still uses version 1.4 of the Roundcube webmail client, which has recently received an update. Highlights of the 1.5 release are summarized in this [blogpost from roundcube.net](https://roundcube.net/news/2021/10/18/roundcube-1.5.0-released), though (for me) the most interesting are:
- OAuth2 support
- Elastic now comes with a dark mode

From a quick glance at the Dockerfile, it didn’t seem like there are any huge requirements, but I’ll give it a try later and see what happens. I’d be happy to contribute this change if it works, but I don’t have a full picture of the behind the scenes of the mailu stack yet, so I may need help if I walk into any traps.

Thank you all for your work with mailu! It’s an awesome project and really makes hosting a mailserver extremly easy, at least on a small scale.

#### Changlog
[2021-11-01 08:41 +00]: add thank you note

**Comment by Diman0** [comment]
I did not know roundcube 1.5 was released. I see it was released only 2 weeks ago. We could have a look at including this with the next Mailu release. 
It should be a matter of updating the release tar.g.z url in the Dockerfile.
At the same time the carddav plugin should also be updated to the newest version:
https://github.com/mstilkerich/rcmcarddav/releases/download/v4.2.2/carddav-v4.2.2.tar.gz
