### ISSUE TITLE
nginx: [emerg] invalid number of arguments in "location" directive in /etc/nginx/nginx.conf:112

### ISSUE THREAD

**Issue by dashaub** [Mailu/Mailu#2040]
## Before you open your issue
- [X] Check if no issue or pull-request for this already exists.
- [X] Check [documentation](https://mailu.io/master/) and [FAQ](https://mailu.io/master/faq.html). (Tip, use the search function on the documentation page)
- [X] You understand `Mailu` is made by volunteers in their **free time** — be conscise, civil and accept that delays can occur.
- [X] The title of the issue should be short and simple. It should contain specific terms related to the actual issue. Be specific while writing the title.

### Environment
 - [X] docker-compose
 - [ ] kubernetes
 - [ ] docker swarm

### Versions
1.8

## Description
It appears nginx has an invalid config because [WEB_ADMIN](https://github.com/Mailu/Mailu/blob/1.8/core/nginx/conf/nginx.conf#L140-L159) is not being set, so in my `nginx.conf` I have
```
      location  {
        return 301 /ui;
      }

      location ~ /(ui|static) {
        rewrite ^/(.*) /$1 break;
        include /etc/nginx/proxy.conf;
        proxy_set_header X-Forwarded-Prefix ;
        proxy_pass http://$admin;
      }

      location /antispam {
        rewrite ^/antispam/(.*) /$1 break;
        auth_request /internal/auth/admin;
        proxy_set_header X-Real-IP "";
        proxy_set_header X-Forwarded-For "";
        proxy_pass http://$antispam;
      }
```

## Replication Steps
use https://setup.mailu.io for creating config
check the box for **Enable the admin UI (and path to the admin UI)**-- `ADMIN=true` appears in generated `mailu.env` but `WEB_ADMIN` is not set

``
docker-compose up -d
``
all containers launch, but `front` enters an unhealthy state. No web admin

## Expected behaviour
All containers running in healthy state, web admin accessible.

## Logs
`docker-compose logs front` gives
```
nginx: [emerg] invalid number of arguments in "location" directive in /etc/nginx/nginx.conf:112
```

**Comment by Diman0** [comment]
I cannot replicate this. When you tick the option "Enable the admin UI (and path to the admin UI)", the value "/admin" is automatically filled in on the setup.mailu.io page. 

As stated in the [configuration reference](https://mailu.io/1.8/configuration.html#web-settings), you need to use at least a leading slash '/' for the variable WEB_ADMIN (if ADMIN is set to true). You are not allowed to use an empty value.

**Comment by dashaub** [comment]
[here](https://setup.mailu.io/1.8/setup/d2b1fedd-3d9b-4bf1-9308-02081f777333) is an example.

> As stated in the configuration reference, you need to use at least a leading slash '/' for the variable WEB_ADMIN (if ADMIN is set to true). You are not allowed to use an empty value.

Is the setup page not supposed to populate `WEB_ADMIN` automatically if "Enable the admin UI (and path to the admin UI)" was marked? I thought  it would do that automatically. If not, is there a reason this can't have a default or at least a mandatory text field next to that box that must be filled in if the user sets it. Otherwise, the setup page generates a `mailu.env` file that doesn't work out of the box, and the user must edit the file by hand afterwards.

**Comment by dashaub** [comment]
Looking at this again, I see that a box like that _does_ appear exactly as expected if JS from ajax.googleapis.com is allowed. That explains it.

**Comment by spoulson** [comment]
I encountered this issue on a fresh server install.  What happened for me is that I was repeatedly generating new configurations from https://setup.mailu.io.  When I use the back button to make edits, the "Enable the admin UI" is checked, but the associated form field for admin path is hidden.  If I generate a configuration in this state, I will get `WEB_ADMIN=` with no value.

<img width="768" alt="image" src="https://user-images.githubusercontent.com/102494/187301487-965b70e5-7b2c-41f2-8dcd-b044e9d7a646.png">

**Workaround**
Uncheck and recheck the box to get the hidden input field back.  Then, generate configuration as usual.
