### ISSUE TITLE
Multiple SMTP Milter service erros with fresh docker deployment..

### ISSUE THREAD

**Issue by philliphodges** [Mailu/Mailu#2057]
Thank you for opening an issue with Mailu. Please understand that issues are meant for bugs and enhancement-requests.
For **user-support questions**, reach out to us  on [matrix](https://matrix.to/#/#mailu:tedomum.net).

To be able to help you best, we need some more information.

## Before you open your issue
- [x] Check if no issue or pull-request for this already exists.
- [x] Check [documentation](https://mailu.io/master/) and [FAQ](https://mailu.io/master/faq.html). (Tip, use the search function on the documentation page)
- [x] You understand `Mailu` is made by volunteers in their **free time** — be conscise, civil and accept that delays can occur.
- [x] The title of the issue should be short and simple. It should contain specific terms related to the actual issue. Be specific while writing the title.

### Environment
 - [x] docker-compose

### Versions
1.8

## Description
I have just deployed a fresh server (1.8) using docker compose. I used the wizzard on the mailu site to create compose and env files. All services appear to load and run, however, I am unable to send or receive mail. I am able to configure a client and can connect to an account. The frontend and webmail applications also work.

When trying to send an email via a client (Thunderbird) I get the following error:
````markdown
```
The mail server responded: 4.7.1 Service unavailable - try again later.

```
````
Looking at the docker logs (see below) it appears there is an issue with the Milter service being unavailable in the SMTP service.

## Replication Steps
Perform a fresh 1.8 deployment using a similar configuration as the one I'm using.

## Expected behaviour
I should be able to send an email. The smtp service should not be throwing the errors listed.

## Logs
````markdown
```
smtp_1       | Nov 17 13:36:09 mail postfix/smtpd[345]: disconnect from localhost[127.0.0.1] quit=1 commands=1
smtp_1       | Nov 17 13:36:40 mail postfix/smtpd[345]: connect from localhost[127.0.0.1]
smtp_1       | Nov 17 13:36:43 mail postfix/smtpd[345]: warning: connect to Milter service inet:192.168.203.8:11332: Host is unreachable
smtp_1       | Nov 17 13:36:43 mail postfix/smtpd[345]: NOQUEUE: milter-reject: CONNECT from localhost[127.0.0.1]: 451 4.7.1 Service unavailable - try again later; proto=SMTP
smtp_1       | Nov 17 13:36:43 mail postfix/smtpd[345]: disconnect from localhost[127.0.0.1] quit=1 commands=1
smtp_1       | Nov 17 13:37:13 mail postfix/smtpd[345]: connect from localhost[127.0.0.1]
smtp_1       | Nov 17 13:37:16 mail postfix/smtpd[345]: warning: connect to Milter service inet:192.168.203.8:11332: Host is unreachable
smtp_1       | Nov 17 13:37:16 mail postfix/smtpd[345]: NOQUEUE: milter-reject: CONNECT from localhost[127.0.0.1]: 451 4.7.1 Service unavailable - try again later; proto=SMTP
smtp_1       | Nov 17 13:37:16 mail postfix/smtpd[345]: disconnect from localhost[127.0.0.1] quit=1 commands=1
smtp_1       | Nov 17 13:37:46 mail postfix/smtpd[345]: connect from localhost[127.0.0.1]
smtp_1       | Nov 17 13:38:16 mail postfix/smtpd[345]: warning: connect to Milter service inet:192.168.203.8:11332: Operation timed out
smtp_1       | Nov 17 13:38:16 mail postfix/smtpd[345]: NOQUEUE: milter-reject: CONNECT from localhost[127.0.0.1]: 451 4.7.1 Service unavailable - try again later; proto=SMTP
smtp_1       | Nov 17 13:38:16 mail postfix/smtpd[345]: disconnect from localhost[127.0.0.1] quit=1 commands=1
smtp_1       | Nov 17 13:38:46 mail postfix/smtpd[345]: connect from localhost[127.0.0.1]
smtp_1       | Nov 17 13:38:49 mail postfix/smtpd[345]: warning: connect to Milter service inet:192.168.203.8:11332: Host is unreachable
smtp_1       | Nov 17 13:38:49 mail postfix/smtpd[345]: NOQUEUE: milter-reject: CONNECT from localhost[127.0.0.1]: 451 4.7.1 Service unavailable - try again later; proto=SMTP
smtp_1       | Nov 17 13:38:49 mail postfix/smtpd[345]: disconnect from localhost[127.0.0.1] quit=1 commands=1
smtp_1       | Nov 17 13:39:19 mail postfix/smtpd[345]: connect from localhost[127.0.0.1]
smtp_1       | Nov 17 13:39:21 mail postfix/smtpd[345]: warning: connect to Milter service inet:192.168.203.8:11332: Connection refused
smtp_1       | Nov 17 13:39:21 mail postfix/smtpd[345]: NOQUEUE: milter-reject: CONNECT from localhost[127.0.0.1]: 451 4.7.1 Service unavailable - try again later; proto=SMTP
smtp_1       | Nov 17 13:39:21 mail postfix/smtpd[345]: disconnect from localhost[127.0.0.1] quit=1 commands=1
smtp_1       | Nov 17 13:39:51 mail postfix/smtpd[345]: connect from localhost[127.0.0.1]
smtp_1       | Nov 17 13:40:10 mail postfix/smtpd[345]: warning: connect to Milter service inet:192.168.203.8:11332: Host is unreachable
smtp_1       | Nov 17 13:40:10 mail postfix/smtpd[345]: NOQUEUE: milter-reject: CONNECT from localhost[127.0.0.1]: 451 4.7.1 Service unavailable - try again later; proto=SMTP
smtp_1       | Nov 17 13:40:10 mail postfix/smtpd[345]: disconnect from localhost[127.0.0.1] quit=1 commands=1
smtp_1       | Nov 17 13:40:40 mail postfix/smtpd[345]: connect from localhost[127.0.0.1]
smtp_1       | Nov 17 13:40:43 mail postfix/smtpd[345]: warning: connect to Milter service inet:192.168.203.8:11332: Host is unreachable
smtp_1       | Nov 17 13:40:43 mail postfix/smtpd[345]: NOQUEUE: milter-reject: CONNECT from localhost[127.0.0.1]: 451 4.7.1 Service unavailable - try again later; proto=SMTP
smtp_1       | Nov 17 13:40:43 mail postfix/smtpd[345]: disconnect from localhost[127.0.0.1] quit=1 commands=1
smtp_1       | Nov 17 13:41:13 mail postfix/smtpd[345]: connect from localhost[127.0.0.1]
smtp_1       | Nov 17 13:41:16 mail postfix/smtpd[345]: warning: connect to Milter service inet:192.168.203.8:11332: Host is unreachable
smtp_1       | Nov 17 13:41:16 mail postfix/smtpd[345]: NOQUEUE: milter-reject: CONNECT from localhost[127.0.0.1]: 451 4.7.1 Service unavailable - try again later; proto=SMTP
smtp_1       | Nov 17 13:41:16 mail postfix/smtpd[345]: disconnect from localhost[127.0.0.1] quit=1 commands=1
smtp_1       | Nov 17 13:41:46 mail postfix/smtpd[345]: connect from localhost[127.0.0.1]
smtp_1       | Nov 17 13:41:49 mail postfix/smtpd[345]: warning: connect to Milter service inet:192.168.203.8:11332: Host is unreachable
smtp_1       | Nov 17 13:41:49 mail postfix/smtpd[345]: NOQUEUE: milter-reject: CONNECT from localhost[127.0.0.1]: 451 4.7.1 Service unavailable - try again later; proto=SMTP
smtp_1       | Nov 17 13:41:49 mail postfix/smtpd[345]: disconnect from localhost[127.0.0.1] quit=1 commands=1
smtp_1       | Nov 17 13:42:19 mail postfix/smtpd[345]: connect from localhost[127.0.0.1]
smtp_1       | Nov 17 13:42:22 mail postfix/smtpd[345]: warning: connect to Milter service inet:192.168.203.8:11332: Host is unreachable
smtp_1       | Nov 17 13:42:22 mail postfix/smtpd[345]: NOQUEUE: milter-reject: CONNECT from localhost[127.0.0.1]: 451 4.7.1 Service unavailable - try again later; proto=SMTP
smtp_1       | Nov 17 13:42:22 mail postfix/smtpd[345]: disconnect from localhost[127.0.0.1] quit=1 commands=1
smtp_1       | Nov 17 13:42:53 mail postfix/smtpd[345]: connect from localhost[127.0.0.1]
smtp_1       | Nov 17 13:42:56 mail postfix/smtpd[345]: warning: connect to Milter service inet:192.168.203.8:11332: Host is unreachable
smtp_1       | Nov 17 13:42:56 mail postfix/smtpd[345]: NOQUEUE: milter-reject: CONNECT from localhost[127.0.0.1]: 451 4.7.1 Service unavailable - try again later; proto=SMTP
smtp_1       | Nov 17 13:42:56 mail postfix/smtpd[345]: disconnect from localhost[127.0.0.1] quit=1 commands=1
smtp_1       | Nov 17 13:43:26 mail postfix/smtpd[345]: connect from localhost[127.0.0.1]
smtp_1       | Nov 17 13:43:29 mail postfix/smtpd[345]: warning: connect to Milter service inet:192.168.203.8:11332: Host is unreachable
smtp_1       | Nov 17 13:43:29 mail postfix/smtpd[345]: NOQUEUE: milter-reject: CONNECT from localhost[127.0.0.1]: 451 4.7.1 Service unavailable - try again later; proto=SMTP
smtp_1       | Nov 17 13:43:29 mail postfix/smtpd[345]: disconnect from localhost[127.0.0.1] quit=1 commands=1
smtp_1       | Nov 17 13:43:59 mail postfix/smtpd[345]: connect from localhost[127.0.0.1]
smtp_1       | Nov 17 13:44:29 mail postfix/smtpd[345]: warning: connect to Milter service inet:192.168.203.8:11332: Operation timed out
smtp_1       | Nov 17 13:44:29 mail postfix/smtpd[345]: NOQUEUE: milter-reject: CONNECT from localhost[127.0.0.1]: 451 4.7.1 Service unavailable - try again later; proto=SMTP
smtp_1       | Nov 17 13:44:29 mail postfix/smtpd[345]: disconnect from localhost[127.0.0.1] quit=1 commands=1

```
````

**Comment by philliphodges** [comment]
The following log was captured when trying to send a test email from the client (Thunderbird)...

....markup
...
front_1      | 2021/11/17 14:45:12 [info] 11#11: *58 client 192.168.20.132:46632 connected to 0.0.0.0:587
front_1      | 127.0.0.1 - - [17/Nov/2021:14:45:12 +0000] "GET /health HTTP/1.1" 301 162 "-" "curl/7.79.1"
front_1      | 127.0.0.1 - - [17/Nov/2021:14:45:12 +0000] "GET /health HTTP/2.0" 204 0 "-" "curl/7.79.1"
front_1      | 2021/11/17 14:45:12 [info] 11#11: *59 client 127.0.0.1 closed keepalive connection
front_1      | 127.0.0.1 - - [17/Nov/2021:14:45:12 +0000] "GET /auth/email HTTP/1.0" 200 0 "-" "-"
smtp_1       | Nov 17 14:45:12 mail postfix/smtpd[484]: connect from mail-server_front_1.mail-server_default[192.168.203.4]
smtp_1       | Nov 17 14:45:16 mail postfix/smtpd[345]: connect from localhost[127.0.0.1]
imap_1       | Nov 17 14:45:16 pop3-login: Info: Disconnected: Aborted login by logging out (no auth attempts in 0 secs): user=<>, rip=127.0.0.1, lip=127.0.0.1, secured, session=<IsEdF/3Q06J/AAAB>
webmail_1    | 127.0.0.1 - - [17/Nov/2021:14:45:22 +0000] "GET / HTTP/1.1" 200 5677 "-" "curl/7.74.0"
smtp_1       | Nov 17 14:45:34 mail postfix/smtpd[345]: warning: connect to Milter service inet:192.168.203.7:11332: Host is unreachable
smtp_1       | Nov 17 14:45:34 mail postfix/smtpd[345]: NOQUEUE: milter-reject: CONNECT from localhost[127.0.0.1]: 451 4.7.1 Service unavailable - try again later; proto=SMTP
smtp_1       | Nov 17 14:45:34 mail postfix/smtpd[345]: disconnect from localhost[127.0.0.1] quit=1 commands=1
front_1      | 2021/11/17 14:45:35 [info] 11#11: *65 client 10.0.0.1:41844 connected to 0.0.0.0:143
smtp_1       | Nov 17 14:45:42 mail postfix/smtpd[484]: warning: connect to Milter service inet:192.168.203.7:11332: Operation timed out
smtp_1       | Nov 17 14:45:42 mail postfix/smtpd[484]: NOQUEUE: milter-reject: CONNECT from mail-server_front_1.mail-server_default[192.168.203.4]: 451 4.7.1 Service unavailable - try again later; proto=SMTP
smtp_1       | Nov 17 14:45:42 mail postfix/smtpd[484]: NOQUEUE: milter-reject: EHLO from mail-server_front_1.mail-server_default[192.168.203.4]: 451 4.7.1 Service unavailable - try again later; proto=SMTP helo=<mail.philliphodges.com>
front_1      | 127.0.0.1 - - [17/Nov/2021:14:45:43 +0000] "GET /health HTTP/1.1" 301 162 "-" "curl/7.79.1"
front_1      | 127.0.0.1 - - [17/Nov/2021:14:45:43 +0000] "GET /health HTTP/2.0" 204 0 "-" "curl/7.79.1"
front_1      | 2021/11/17 14:45:43 [info] 11#11: *66 client 127.0.0.1 closed keepalive connection
smtp_1       | Nov 17 14:45:46 mail postfix/smtpd[484]: warning: connect to Milter service inet:192.168.203.7:11332: Host is unreachable
smtp_1       | Nov 17 14:45:46 mail postfix/smtpd[484]: NOQUEUE: milter-reject: XCLIENT from optiplex390.thehodgesfamily.mylocal[192.168.20.132]: 451 4.7.1 Service unavailable - try again later; proto=SMTP sasl_username=<phillip@philliphodges.com>
smtp_1       | Nov 17 14:45:46 mail postfix/smtpd[484]: NOQUEUE: milter-reject: EHLO from optiplex390.thehodgesfamily.mylocal[192.168.20.132]: 451 4.7.1 Service unavailable - try again later; proto=SMTP helo=<[192.168.20.132]> sasl_username=<phillip@philliphodges.com>
front_1      | 2021/11/17 14:45:46 [info] 11#11: *58 client logged in, client: 192.168.20.132 using starttls, server: 0.0.0.0:587, login: "phillip@philliphodges.com", upstream: 192.168.203.6:10025
smtp_1       | Nov 17 14:45:46 mail postfix/smtpd[484]: NOQUEUE: milter-reject: MAIL from optiplex390.thehodgesfamily.mylocal[192.168.20.132]: 451 4.7.1 Service unavailable - try again later; from=<phillip@philliphodges.com> proto=ESMTP helo=<[192.168.20.132]> sasl_username=<phillip@philliphodges.com>
imap_1       | Nov 17 14:45:46 pop3-login: Info: Disconnected: Aborted login by logging out (no auth attempts in 0 secs): user=<>, rip=127.0.0.1, lip=127.0.0.1, secured, session=<tYfqGP3Q9YB/AAAB>
mail-server_antispam_1 exited with code 132
...
....

**Comment by philliphodges** [comment]
looks to be something similar to this: https://talk.plesk.com/threads/postfix-milter-reject-after-upgrade-to-onyx.344367/

**Comment by philliphodges** [comment]
the antispam container is constantly restarting.. 

`mailu/rspamd:1.8      "/bin/sh -c /start.py"   40 minutes ago   Restarting (132) 7 seconds ago   mail-server_antispam_1`

i am looking at the logs to try and see why..

**Comment by Diman0** [comment]
That exit code indeed indicates the software is missing a certain CPU flag.
Exit code 132  = 128 + 4
exit code 128 = Invalid argument to exit (an error resulted to an exit)
exit code 4 = Illegal Instruction (that could be your missing AVX flag).

I cannot find anything on the rspamd site that states you require a CPU with AVX support. I can only find a config module that can be used to check what CPU flags are supported by a CPU https://rspamd.com/doc/lua/rspamd_config.html#mfee9b.

Looking in the rspamd issues section I can see that rspamd detects with cpu flags can be used. This rspamd crash should never occur: https://github.com/rspamd/rspamd/issues/399#issuecomment-148317711

I advise to create an issue on the rspamd github project to get assistance with troubleshooting this error.
