### ISSUE TITLE
Use official clamav docker image for Mailu clamav image

### ISSUE THREAD

**Issue by oliv3r** [Mailu/Mailu#2059]
With https://github.com/Cisco-Talos/clamav having official docker support https://hub.docker.com/r/clamav/clamav it might be worth considering referring or preferring that container in the future?

**Comment by Diman0** [comment]
It might be worthwhile to have a deeper look at using their image. However a quick look already shows a couple of issues
- no TZData package (timezone settings)
- No proper healthcheck
But this can be addressed in our Dockerfile which will use the clamav docker image of course.

I see they also offer pinned versions. That means we can use it.

**Comment by oliv3r** [comment]
@diman0, Hi

as the original author of the docker container, can you point out the issues in more detail? I'm sure we can discuss and integrate the needed things.

No TZData package, that is of course trivial to add. I'm no clamav expert, but is it used by clamav if available? If so, we could and should of course include it.

No proper healthcheck is supprising, because afaik it was inpsired by the healthcheck in mailu :p (but this was in 2019 so it may have changed significantly). Getting a better healthcheck in is of course only better then a poor healthcheck. But how is the current healthcheck not proper in your eyes?

**Comment by Diman0** [comment]
I see the Dockerfile does contain a HEALTHCHECK, but it is in the wrong location.
(https://github.com/Cisco-Talos/clamav/blob/679883fdb6b123ac534d5e7c27c902e04cbfa711/Dockerfile#L14
If this is moved below the second FROM (line 90), then the docker image will have a working healthcheck.

**Comment by oliv3r** [comment]
@diman0, thank you for pointing out these oversights. I'm fairly certain it worked at some point :) Docker improvement or broken Dockerfile for a long time. Either or; they are addressed.
