### ISSUE TITLE
mailu auto forward to other mail

### ISSUE THREAD

**Issue by farsad2020** [Mailu/Mailu#2060]
Hi
i define alias for the mail on mailu server but it does not forward any email that resivecd
what i missed?!

**Comment by nextgens** [comment]
https://mailu.io/1.8/webadministration.html?highlight=forward#auto-forward

**Comment by Diman0** [comment]
As nextgens, already stated for forwarding received emails use email forwarding
https://mailu.io/1.8/webadministration.html?highlight=forward#auto-forward

[Email aliases](https://mailu.io/1.8/webadministration.html#aliases) have a different purpose.
