### ISSUE TITLE
Docker Compose setup fails - containers can't talk to each other/the internet

### ISSUE THREAD

**Issue by Poolitzer** [Mailu/Mailu#2061]
Thank you for opening an issue with Mailu. Please understand that issues are meant for bugs and enhancement-requests.
For **user-support questions**, reach out to us  on [matrix](https://matrix.to/#/#mailu:tedomum.net).

To be able to help you best, we need some more information.

## Before you open your issue
- [x] Check if no issue or pull-request for this already exists.
- [x] Check [documentation](https://mailu.io/master/) and [FAQ](https://mailu.io/master/faq.html). (Tip, use the search function on the documentation page)
- [x] You understand `Mailu` is made by volunteers in their **free time** — be conscise, civil and accept that delays can occur.
- [x] The title of the issue should be short and simple. It should contain specific terms related to the actual issue. Be specific while writing the title.

### Environment
 - [x] docker-compose
 - [ ] kubernetes
 - [ ] docker swarm

### Versions

The version is 1.8.

## Description
The admin web interface returns a 404 error. The `antispam `container fails to start because it can't connect to the `redis `container, which leads to `postfix `not being healthy because it can't connect to antispam

When one does a request to the admin interface, the forward to /ui works, after that, the following error appears:
`front_1     | 2021/11/21 18:09:19 [info] 11#11: *1 client closed connection while waiting for request, client: 192.168.203.1, server: 0.0.0.0:80`

I bashed into the antispam container and tried to ping the internet, which fails, as the redis connection does:
```
2 packets transmitted, 0 packets received, 100% packet loss
```

## Replication Steps
* Follow the tutorial of https://mailu.io/1.8/compose/requirements.html and https://mailu.io/1.8/compose/setup.html
* then do the reverse proxy steps of https://mailu.io/1.8/reverse.html#have-mailu-web-frontend-listen-locally

## Expected behaviour
Have a working mailu instance

## Logs
Example log
````markdown

antispam_1  | 2021-11-21 18:20:07 #8(fuzzy) <o78sb9>; lua; lua_redis.lua:1200: cannot upload script to 192.168.203.2:6379: timeout while connecting the server; registered from: /usr/share/rspamd/lualib/plugins/neural.lua:190

````

**Comment by Poolitzer** [comment]
Hi, I took the time to verify it didn't fix itself since I wrote the issue, it did not.

**Comment by Poolitzer** [comment]
Still there. Its alright if you guys can't help I will just give up then.

**Comment by ghostwheel42** [comment]
Did you regenerate your Dockerfile/env with the new 1.9 release yet?

**Comment by Poolitzer** [comment]
Hi, I did not. Just did and same error comes up:
`antispam_1  | 2022-01-10 10:57:20 #17(fuzzy) <a93eud>; lua; lua_redis.lua:1200: cannot upload script to 192.168.203.2:6379: timeout while connecting the server; registered from: /usr/share/rspamd/lualib/plugins/neural.lua:196`
