### ISSUE TITLE
DB_PORT environment setting is ignored

### ISSUE THREAD

**Issue by mojerro** [Mailu/Mailu#2073]
### Environment
 - [x] docker-compose
 - [ ] kubernetes
 - [ ] docker swarm

### Versions
mailu 1.8

## Description
As a reason that the default database port is not secure, and I hope to install mailu with other postgres port instead of 5432. But in the dockerfile and env file, I cannot find a place to change it , can someone help or this will be a new feature?

**Comment by Diman0** [comment]
In Mailu it is not possible to use a custom port. I will mark this as an enhancement request.

**Comment by mojerro** [comment]
I just found I can add `DB_PORT=xxxx` in `mailu.env` to assign a custom port, and it seems working!  This env is found in this [documentation](https://github.com/Mailu/Mailu/blob/20f00a36999efbe6b9d5c1d9279eec7d6c359eb6/docs/database.rst)

**Comment by Diman0** [comment]
Ah yes. You are correct https://mailu.io/master/configuration.html#database-settings
However I think it is not used. See:
https://github.com/Mailu/Mailu/blob/1675399047be7fe6813ceb7db418be9010124400/core/admin/mailu/configuration.py#L97

Can you double check if the setting works? I cannot find any reference to the DB_PORT env variable in the project.

**Comment by mojerro** [comment]
Well, sorry about what I said above, the real change is directly add port after the link. Such as:
`portgres.domain:1234`

**Comment by mojerro** [comment]
I did many changes and one of them get successful. I also get another mistake from the database which puzzled me ...

**Comment by Diman0** [comment]
Looking at the SQLAlchemy]

**Comment by Diman0** [comment]
Note: After changing the settings you must **recreate** the containers. Restarting is not sufficient.

**Comment by mojerro** [comment]
thanks a lot

> 

That's pretty clear, and my mailu server is now working well! thx!
