### ISSUE TITLE
[master] Webmail token check does not work if WEBMAIL_ADDRESS is set to a hostname

### ISSUE THREAD

**Issue by micw** [Mailu/Mailu#2079]
In master with the new token stuff, webmail is not working when WEBMAIL_ADDRESS is set to a hostname.

The issue is in https://github.com/Mailu/Mailu/blob/e3396b83ce0496231515cbefa88fca61f8355410/core/admin/mailu/internal/nginx.py#L35 where the hostname is compared to the IP adress.

See also https://github.com/Mailu/Mailu/blob/e52a3de1b04fa1f8968e0f596a04f2d17205ef9c/core/admin/mailu/configuration.py#L118

When HOST_WEBMAIL is set, it is statically resolved and it works (but with all drawbacks of statically resolved hosts, we don't want this anymore). When WEBMAIL_ADDRESS is set, it's used as it is and not resolved.

Possible solutions:
* check against $SUBNET
* set a special mark on temp tokens so that the check is not required
* set a special auth header on FRONT so that it's clear that the request comes from webmail (best solution IMO)

**Comment by Diman0** [comment]
- set a special auth header on FRONT so that it's clear that the request comes from webmail (best solution IMO)

That is the solution. We already have this information. That is the auth-port 10143. This port is only used for webmails. We can change the `ip==` part with `port = 10143` and it should work under all conditions again.

**Comment by nextgens** [comment]
> This port is only used for webmails

No, it's used for IMAP without SSL: that's not specific to the webmail.

A better check would be to ensure the IP isn't front's

**Comment by nextgens** [comment]
Disregard my last comment, I've missed #2081 and you're right.

**Comment by micw** [comment]
I'd recommend not to use the auth port but a dedicated header (like "auth-type = webmailtoken").
Reason: using the port works but is extremely intransparent. Changing the port would break things in a completely unexpected manner. I already saw one port-dependent rule and thought it has a code smell.

**Comment by micw** [comment]
I see. For 2., the "scope" could be added by the fact that webmail uses a special port that is internal reachable only. That port section in front could add an extra header (like it already does for the port). This could also be used to achieve 1. - if the header is set, we know that it's a webmail token.

We could even use the user's session id as token and link the expiration to the sso session. This would also solve #2080.

**Comment by nextgens** [comment]
I'm not sure I am following regarding the user's session-id: which one? The webmail's or admin's?

**Comment by micw** [comment]
To the one used in sso - I don't know exactly how it is implemented. But from a user's PoV, if he starts a webmail session, it should be valid as long as the SSO session. And as long as the user works in Webmail, the session should be kept alive.

**Comment by nextgens** [comment]
That's clearly not how it currently works

I'm guessing you won't like how it's implemented on the admin side either. Right now the session's lifetime isn't extended at each request: there is a hard-stop at 24h (see below) regardless of activity.

https://mailu.io/master/configuration.html#advanced-settings check SESSION_LIFETIME
