### ISSUE TITLE
Add mailpile webmail

### ISSUE THREAD

**Issue by jagu-sayan** [Mailu/Mailu#208]
Can be interesting to add [Maipile Webmail](https://www.mailpile.is/)

**Comment by kaiyou** [comment]
I did not realized that Mailpile was meant to be single-user, that will make things a lot more difficult I believe.

**Comment by gregf** [comment]
I have in there faq they'll add multiuser support after the 1.0 release.

**Comment by kaiyou** [comment]
Then let's wait for release ``1.0`` and see how they manage to implement multi-user support.

**Comment by muhlemmer** [comment]
Mailpile does not seem to move anywhere real quick. Does anybody still want this?

**Comment by kaiyou** [comment]
Mailpile has officially announced that they would not support multiple users and see their app as a desktop one. I am closing this issue since we cannot integrate it in Mailu.
