### ISSUE TITLE
[master] Temp tokens (Webmail) expires on midnight

### ISSUE THREAD

**Issue by micw** [Mailu/Mailu#2080]
A webmail temp token contains the current date in it's HMAC. So it will expire on midnight, giving varying token lifetime between 0s and 24h:
https://github.com/Mailu/Mailu/blob/dbbfa44461c3b8a537e9fe6b56f4690417d3c8a2/core/admin/mailu/models.py#L651

Better approach:
* on token creation, get the curent date and time
    * use date and time as part of HMAC
    * append date+time in plaintext to the token
* on validation, use date+time from token
    * use to validate hmac
    * use to validate if the token is expired or not

**Comment by Diman0** [comment]
That would be a nice enhancement. We could perhaps use the `SESSION_LIFETIME` setting to also determine how long a webmail session should live.

**Comment by nextgens** [comment]
I'm fairly sure that it works as intended: the token will eventually be wrong, it will trigger login_failed -> re-authentication with a fresh, new token. If the admin session is still valid (SESSION_LIFETIME hasn't expired), all of this should be mostly transparent (just a bunch of redirects).

Keep in mind that this token isn't exposed to the user at all; It could be completely static (or even non-existent if we decided to trust that we know the webmail's IP address) but we're rotating it it just in case it leaks.

**Comment by micw** [comment]
| Remove the extra redirects on the first request after midnight?

Failing to send mails around midnight (server time) with webmail when you start to write the mail before midnight and send it after midnight.

**Comment by nextgens** [comment]
The proposed fix won't solve that problem and will just make it less deterministic: the token will eventually expire even if that's not at midnight anymore

**Comment by micw** [comment]
Right. A session token that is renewed on access would be much better
