### ISSUE TITLE
Problem with mysql (MariaDB) Connect after upgrade 1.7 -> 1.8

### ISSUE THREAD

**Issue by wernieman** [Mailu/Mailu#2085]
### Environment
docker-compose 1.17.4
docker 20.10.12

### Versions
Work 1.7
Problem 1.8

## Description
I Upgrade vrom 1.7 (Work) to 1.8. Ich check my mailu.env and docker-compose.yml with a new generatet Versions and update my Version. in the mailu.env is the line:
DB_User=mailu

After Upgrade i get with "docker-compose logs -f"
webmail_1    | Initializing database
webmail_1    | ERROR: SQLSTATE[HY000] [1698] Access denied for user 'roundcube'@'172.28.6.10'
webmail_1    | ERROR: Failed to connect to database
webmail_1    |
mailu_webmail_1 exited with code 1

 Why it Use the User roundcube?? I Search in the whole Direktory, but there is no "roundcube" User in a Config (or other File). Can you help? I love this "Software"

In the Config:
DB_FLAVOR=mysql
DB_USER=mailu
DB_PW=VeryGoodPassword
DB_HOST=DB-Server-Name
DB_NAME=mailu

## Replication Steps
Good Question (Sorry). At my Installation I can Replicate the Problem by upgrade to 1.8 

## Expected behaviour
I Check my  config file for the User "roundcube", but there is no "roundcube". I change from 1.8 to 1.7 and it works. Back to 1.8 I get the same Problem, without a Change, to resolve it. Back to (aktual) 1.7 and it works with the same DB_XX Settings. With 1.8 it don´t work

## Logs

s.o. and as a replicate:

webmail_1    | Initializing database
webmail_1    | ERROR: SQLSTATE[HY000] [1698] Access denied for user 'roundcube'@'172.28.6.10'
webmail_1    | ERROR: Failed to connect to database
webmail_1    |
mailu_webmail_1 exited with code 1

***
Sorry abount my english, I hope, you understand me,

**Comment by wernieman** [comment]
The automatic mailu.env forget one Setting:
ROUNDCUBE_DB_FLAVOR=sqlite

Set it (and delete the original roundcube.db), then it works ....

**Comment by Diman0** [comment]
This will be fixed in Mailu 1.9. The PR #2069 with the required changes is waiting for review.
