### ISSUE TITLE
[Error: EACCES: permission denied, mkdir '/app/public/css']

### ISSUE THREAD

**Issue by jsballesterosm** [Mailu/Mailu#2088]
99% end closing watch compilation[webpack-cli] [Error: EACCES: permission denied, mkdir '/app/public/css'] {
hellodjango-webpack-1   |   errno: -13,
hellodjango-webpack-1   |   code: 'EACCES',
hellodjango-webpack-1   |   syscall: 'mkdir',
hellodjango-webpack-1   |   path: '/app/public/css'
hellodjango-webpack-1   | }
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by Diman0** [comment]
This appears not to be mailu related.
