### ISSUE TITLE
rmilter overrides disabled

### ISSUE THREAD

**Issue by Logan2211** [Mailu/Mailu#209]
2a3f62fc65f36d9edc6f56460e11066d5212515d disabled rmilter overrides with no explanation in the commit message. Is there a reason why these overrides are disabled? Can we fix it to get the overrides enabled again?

**Comment by LorbusChris** [comment]
I'm just passing by, but this may be important:
As of rspamd v1.6 rmilter has been obsoleted and will receive no further updates.
All of its functionality is said to be possible with rspamd modules.

See https://rspamd.com/rmilter/

**Comment by kaiyou** [comment]
@Logan2211 this is surely a mistake, I will check and re-enable overrides. Thank you @LorbusChris for reporting about the deprecation.
