### ISSUE TITLE
Fix INITIAL_ACCOUNT environment variable documentation master

### ISSUE THREAD

**Issue by Erriez** [Mailu/Mailu#2092]
## Before you open your issue
- [X] Check if no issue or pull-request for this already exists.
- [X] Check [documentation](https://mailu.io/master/) and [FAQ](https://mailu.io/master/faq.html). (Tip, use the search function on the documentation page)
- [X] You understand `Mailu` is made by volunteers in their **free time** — be conscise, civil and accept that delays can occur.
- [X] The title of the issue should be short and simple. It should contain specific terms related to the actual issue. Be specific while writing the title.

### Environment
 - [X] docker-compose

### Versions
To find your version, get the image name of a mailu container and read  the version from the tag (example for version 1.7).

```
master e7f7787 Wed Dec 15 2021
```

## Description

**Issue 1**: https://mailu.io/1.8/compose/setup.html?highlight=initial_account describes:

> You can have the system create it automatically: use the environment variables INITIAL_ACCOUNT* 

This environment variable does not exist and should be `INITIAL_ADMIN_ACCOUNT`.  
A suggestion is to refer to [Admin account - automatic creation](https://mailu.io/1.8/configuration.html#admin-account) only.

**Issue 2**: https://mailu.io/1.8/configuration.html#admin-account

```
INITIAL_ADMIN_ACCOUNT = ``root`` The first part of the e-mail address (ROOT@example.com)
INITIAL_ADMIN_DOMAIN = ``example.com`` the domain appendix. Most probably identical to the DOMAIN variable
INITIAL_ADMIN_PW = ``password`` the chosen password for the user
```

Proposal to remove spaces around the `=` and remove back-quotes.

## Replication Steps

Add the following lines to `mailu.env` and recreate `admin` container:

```bash
INITIAL_ADMIN_MODE=ifmissing
INITIAL_ADMIN_ACCOUNT=admin
INITIAL_ADMIN_DOMAIN=domain.nl
INITIAL_ADMIN_PW=mysecretpassword
```

Proposal is to document the 4 environment variables above in one example at a single place.

## Expected behaviour
Create admin account automatically by configuring environment variables after updating documentation. 

This is a nice and useful feature. Thanks!

**Comment by Diman0** [comment]
Issue1: 
It should indeed be `INITIAL_ADMIN_*` instead of `INITIAL_ACCOUNT*`. Removing this part and only referring to the configuration guide is a good idea New administrators must be encouraged to review the configuration reference.

Issue2: 
It would indeed be better if there are no spaces around the `=` and the ticks are removed. I suspect it was displayed differently in the past. The backticks should have displayed it like ``this``.
