### ISSUE TITLE
Cannot edit aliases anymore

### ISSUE THREAD

**Issue by cobrafast** [Mailu/Mailu#2093]
Thank you for opening an issue with Mailu. Please understand that issues are meant for bugs and enhancement-requests.
For **user-support questions**, reach out to us  on [matrix](https://matrix.to/#/#mailu:tedomum.net).

To be able to help you best, we need some more information.

## Before you open your issue
- [ ] Check if no issue or pull-request for this already exists.
- [ ] Check [documentation](https://mailu.io/master/) and [FAQ](https://mailu.io/master/faq.html). (Tip, use the search function on the documentation page)
- [X] You understand `Mailu` is made by volunteers in their **free time** — be conscise, civil and accept that delays can occur.
- [X] The title of the issue should be short and simple. It should contain specific terms related to the actual issue. Be specific while writing the title.

### Environment
 - [X] docker-compose
 - [ ] kubernetes
 - [ ] docker swarm

### Versions
master

## Description
The edit button for aliases is just gone. Editing aliases was useful for changing target addresses or the comment.

## Replication Steps
Load list of aliases and attempt to edit an existing one.

## Expected behaviour
Aliases can be edited.

## Logs
—

**Comment by cobrafast** [comment]
Upon closer inspection the anchor is still there but the icon seems to have disappeared making it zero-width and thus non-clickable.  
Looks to me like the `fa-pencil` class no longer exists.

**Comment by Diman0** [comment]
Thank you for reporting this. The class `fa-pencil` should be `fa-pencil-alt`.
As a workaround you can change the class `fa-pencil` to `fa-pencil-alt` via the developer tools in your internet browser.

**Comment by Diman0** [comment]
I did a quick search. It looks like these lines must be updated to use the new class `fa-pencil-alt`:
https://github.com/Mailu/Mailu/blob/c5966b29dbc15b99b4d688496734acc75bb31706/core/admin/mailu/ui/templates/alias/list.html#L31
https://github.com/Mailu/Mailu/blob/1675399047be7fe6813ceb7db418be9010124400/core/admin/mailu/ui/templates/relay/list.html#L29
https://github.com/Mailu/Mailu/blob/1675399047be7fe6813ceb7db418be9010124400/core/admin/mailu/ui/templates/fetch/list.html#L33

The other relevant lists were already updated to use fa-pencil-alt.
