### ISSUE TITLE
ValueError "hash could not be identified" when adding new alias

### ISSUE THREAD

**Issue by m0rtalis** [Mailu/Mailu#2104]
### Environment
 - [x] docker-compose
 - [ ] kubernetes
 - [ ] docker swarm

### Versions
1.8

## Description
I have deleted an old mailbox and then tried to add a new alias with the exact same address.
This froze my entire server! for about 60s (even affected other dockerised applications, could not connect via ssh) and then ran into a gateway timeout.
The alias was created afterwards so that's a plus :man_shrugging:

## Replication Steps
Could not replicate it with this, that's just what I did:

1. Create mailbox example@example.com
2. Send mails to and from mailbox
3. Delete mailbox
4. Create alias example@example.com to some other address

## Expected behaviour
New alias is created

## Logs
The following stacktrace was repeated at least 74 times. 
````markdown
```
admin_1       | [2021-12-23 07:17:47,872] ERROR in app: Exception on /internal/auth/email [GET]
admin_1       | Traceback (most recent call last):
admin_1       |   File "/usr/lib/python3.9/site-packages/flask/app.py", line 2292, in wsgi_app
admin_1       |     response = self.full_dispatch_request()
admin_1       |   File "/usr/lib/python3.9/site-packages/flask/app.py", line 1815, in full_dispatch_request
admin_1       |     rv = self.handle_user_exception(e)
admin_1       |   File "/usr/lib/python3.9/site-packages/flask/app.py", line 1718, in handle_user_exception
admin_1       |     reraise(exc_type, exc_value, tb)
admin_1       |   File "/usr/lib/python3.9/site-packages/flask/_compat.py", line 35, in reraise
admin_1       |     raise value
admin_1       |   File "/usr/lib/python3.9/site-packages/flask/app.py", line 1813, in full_dispatch_request
admin_1       |     rv = self.dispatch_request()
admin_1       |   File "/usr/lib/python3.9/site-packages/flask/app.py", line 1799, in dispatch_request
admin_1       |     return self.view_functions[rule.endpoint](**req.view_args)
admin_1       |   File "/app/mailu/internal/views/auth.py", line 24, in nginx_authentication
admin_1       |     headers = nginx.handle_authentication(flask.request.headers)
admin_1       |   File "/app/mailu/internal/nginx.py", line 63, in handle_authentication
admin_1       |     if not status and user.check_password(password):
admin_1       |   File "/app/mailu/models.py", line 384, in check_password
admin_1       |     result = context.verify(password, reference)
admin_1       |   File "/usr/lib/python3.9/site-packages/passlib/context.py", line 2338, in verify
admin_1       |     record = self._get_or_identify_record(hash, scheme, category)
admin_1       |   File "/usr/lib/python3.9/site-packages/passlib/context.py", line 2026, in _get_or_identify_record
admin_1       |     return self._identify_record(hash, category)
admin_1       |   File "/usr/lib/python3.9/site-packages/passlib/context.py", line 1131, in identify_record
admin_1       |     raise ValueError("hash could not be identified")
admin_1       | ValueError: hash could not be identified
admin_1       | [2021-12-23 07:21:37 +0000] [10] [CRITICAL] WORKER TIMEOUT (pid:56510)
admin_1       | [2021-12-23 07:26:10 +0000] [78116] [INFO] Booting worker with pid: 78116
```
````

**Comment by nextgens** [comment]
Do you have access to backups of the database? It would be interesting to see what format the unrecognised hash type was.

Assuming that you are using sqlite3:
```
sqlite3 data/main.db 'select * from user'
```

**Comment by m0rtalis** [comment]
Yes I will check as soon as I'm home. Do you want the hash from the user I am logged in with or the one I deleted?

**Comment by nextgens** [comment]
The one you've deleted.

How did you import the old hash?

**Comment by m0rtalis** [comment]
So I checked and the old hash was just empty.
But that alone does not explain it, bc. I had multiple user like that, that I deleted and the error did not reproduce. I guess it could have been some raise condition..
But then again the container froze when I added the alias, not when I deleted the user so idk.

I converted and imported the users manually directly into the database from an old mailsystem.

**Comment by nextgens** [comment]
>So I checked and the old hash was just empty.

Hmm, it wouldn't have thrown that exception if it was empty :)

>  How can I get a commit Id from the image, since as far as I know the tags are moving?

You can't in 1.8; We are about to release 1.9 and there the version information will be in /version in all containers.

**Comment by nextgens** [comment]
I have prepared a PR to mute the exception (see above) but I'm not convinced that it's any better. If you have manually imported the hashes and they don't work (regardless of why), it's probably best if you do get some form of indication that something is off. 

We could of course make it more descriptive (and tell you which user that relates to), and strip it from the DB (so that it doesn't get re-evaluated next time around)... but I personally don't like discarding data we can't parse... and spamming log messages instead of exceptions isn't really an improvement.

Maybe other maintainers think differently though.

**Comment by m0rtalis** [comment]
Yes I agree, the error should be reported to the user. Maybe catch the exception and rethrow it with the username in the message. I think that would help with the clarity. 

What I don't understand is why was the stacktrace repeated 74 times in a few seconds and if that can somehow be fixed.

**Comment by nextgens** [comment]
Presumably the exception was thrown each time a password check was attempted... It's common to have a lot of authentication attempts in a short timeframe... and to fix that we would need to discard the bogus data from the database (and that's what I am reluctant to do)

**Comment by m0rtalis** [comment]
Yes I agree with you that deleting data from the database is probably not a good idea.
So basically we could add the username to the exception so it's easier to understand and I will look into limiting the resources of that service via docker so hopefully in the future it does not affect other services on the server.
