### ISSUE TITLE
Roundcube Enigmail not working after upgrade to 1.9

### ISSUE THREAD

**Issue by robertvalik** [Mailu/Mailu#2117]
## Before you open your issue
- [x] Check if no issue or pull-request for this already exists.
- [x] Check [documentation](https://mailu.io/master/) and [FAQ](https://mailu.io/master/faq.html). (Tip, use the search function on the documentation page)
- [x] You understand `Mailu` is made by volunteers in their **free time** — be conscise, civil and accept that delays can occur.
- [x] The title of the issue should be short and simple. It should contain specific terms related to the actual issue. Be specific while writing the title.

### Environment
 - [x] docker-compose
 - [ ] kubernetes
 - [ ] docker swarm

### Versions
```
$> docker ps -a | grep mailu
b637bcc9ea26   mailu/roundcube:1.9                         "docker-php-entrypoi…"
$> grep MAILU_VERSION docker-compose.yml mailu.env
docker-compose.yml:    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}nginx:${MAILU_VERSION:-1.9}
docker-compose.yml:    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}admin:${MAILU_VERSION:-1.9}
docker-compose.yml:    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}dovecot:${MAILU_VERSION:-1.9}
docker-compose.yml:    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}postfix:${MAILU_VERSION:-1.9}
docker-compose.yml:    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}rspamd:${MAILU_VERSION:-1.9}
docker-compose.yml:    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}clamav:${MAILU_VERSION:-1.9}
docker-compose.yml:    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}fetchmail:${MAILU_VERSION:-1.9}
docker-compose.yml:    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}roundcube:${MAILU_VERSION:-1.9}
```

## Description
While opening a GPG encrypted mail I expected all to work correctly (as did in 1.8). Instead, I got "Decryption failed. Private key not found. Key ID: ...".

I tried to open Settings -> PGP keys to check if the key is there, but got "Unable to list keys! Internal error."

## Replication Steps
Open any GPG encrypted mail; open Settings -> PGP keys

## Expected behaviour
Ability to read GPG encrypted mail if the correct keys are present. Ability to list keys in Settings...

## Logs
````markdown
```
Dec 31, 2021 @ 11:47:11.067 mailu_webmail_1 192.168.203.4 - - [31/Dec/2021:11:47:11 +0100] "POST /?_task=settings&_action=plugin.enigmakeys HTTP/1.1" 200 807 "https://webmail.example.com/webmail/?_task=settings&_action=plugin.enigmakeys" "Mozilla/5.0 (X11; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/95.0"
Dec 31, 2021 @ 11:47:11.062 mailu_webmail_1 errors: <3sfklbkt> PHP Error: Enigma plugin: Unknown error getting keys. Please use the 'debug' option when creating the Crypt_GPG object, and file a bug report at http://pear.php.net/bugs/report.php?package=Crypt_GPG in /var/www/html/plugins/enigma/lib/enigma_engine.php on line 995 (POST /?_task=settings&_action=plugin.enigmakeys)
Dec 31, 2021 @ 11:47:10.881 mailu_webmail_1 192.168.203.4 - - [31/Dec/2021:11:47:10 +0100] "GET /?_task=settings&_action=plugin.enigmakeys HTTP/1.1" 200 4876 "https://webmail.example.com/webmail/?_task=settings" "Mozilla/5.0 (X11; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/95.0"
Dec 31, 2021 @ 11:47:09.193 mailu_webmail_1 192.168.203.4 - - [31/Dec/2021:11:47:09 +0100] "GET /?_task=settings HTTP/1.1" 200 3834 "https://webmail.example.com/webmail/?_task=mail&_mbox=05%20Banky" "Mozilla/5.0 (X11; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/95.0"
```
````

EDIT: Attaching "debug" logs from enigma:
[rc_enigma_settings_gpg_keys.log](https://github.com/Mailu/Mailu/files/7796111/rc_enigma_settings_gpg_keys.log) - enigma debug log from opening Settings -> PGP Keys
[rc_enigma_read_encrypted_mail.log](https://github.com/Mailu/Mailu/files/7796112/rc_enigma_read_encrypted_mail.log) - enigma debug log from opening encrypted mail

**Comment by Diman0** [comment]
It looks like this is the problematic part:
```
Dec 31, 2021 @ 12:50:54.325 mailu_webmail_1 enigma: <3sfklbkt> GPG: => about to read 65536 bytes from GPG error
Dec 31, 2021 @ 12:50:54.326 mailu_webmail_1 enigma: <3sfklbkt> GPG: ERROR: gpg: error running '/usr/bin/gpg-agent': probably not installed
Dec 31, 2021 @ 12:50:54.335 mailu_webmail_1 enigma: <3sfklbkt> GPG: ERROR: gpg: failed to start agent '/usr/bin/gpg-agent': Configuration error
```

When checking the difference between 1.8 and 1.9 I can see that gpg-agent is indeed missing. 
The Dockerfile of 1.8 and 1.9 both install the gpg package.

The main difference is php:7.4-apache and php:8.0-apache.

I bet the debian version used was updated in php:8.0-apache and the newer version of debian does not automatically install gpg-agent anymore when you install the gpg package.


As a workaround you can manually install the gpg-agent package in the roundcube container. Does it work after gpg-agent is installed and available?

**Comment by robertvalik** [comment]
After executing `apt-get update` and `apt-get install gpg-agent` in the webmail container, the Enigma works - I am able to decrypt e-mails and display keys. Thank you.

**Comment by Diman0** [comment]
thank you for the confirmation.

It is really odd that debian suddenly does not include this package by default anymore when installing gpg.
But it is any easy fix fortunately. We only have to update the dockerfile to explicitly install gpg-agent as well.
