### ISSUE TITLE
Suggestion: Only show "Fetched accounts" menu entry if fetchmail is enabled

### ISSUE THREAD

**Issue by BluemediaGER** [Mailu/Mailu#2127]
I think it would be neat if the sidebar entry `Fetched accounts` in the admin portal is only displayed when fetchmail is really enabled. When fetchmail is disabled, the tab may cause confusion for users, as it has no functionality in this case.

**Comment by Erriez** [comment]
I noticed the same. Good idea to disable or remove the `Fetched accounts` menu in admin when the container is not running or reachable, because the `fetchmail` container is optional to use.
