### ISSUE TITLE
Cannot send email after upgrade to 1.9 `non DNSSEC destination`

### ISSUE THREAD

**Issue by cupcakearmy** [Mailu/Mailu#2135]
## Before you open your issue
- [x] Check if no issue or pull-request for this already exists.
- [x] Check [documentation](https://mailu.io/master/) and [FAQ](https://mailu.io/master/faq.html). (Tip, use the search function on the documentation page)
- [x] You understand `Mailu` is made by volunteers in their **free time** — be conscise, civil and accept that delays can occur.
- [x] The title of the issue should be short and simple. It should contain specific terms related to the actual issue. Be specific while writing the title.

### Environment
 - [x] docker-compose
 - [ ] kubernetes
 - [ ] docker swarm

### Versions
1.9

## Description
Thanks for all the work! 1.9 seems like an amazing release overall ❤️ 

I upgraded to 1.9, generated the new docker-compose file with the tool.
Copied the relevant env variables over and started everything.
I can still receive mails, and send internal one (from and to my own domain)
I cannot send mails to external providers.

after restoring from backup everything works in 1.8

```
Final-Recipient: rfc822; ******
Original-Recipient: rfc822;******
Action: delayed
Status: 4.7.5
Diagnostic-Code: X-Postfix; non DNSSEC destination
Will-Retry-Until: Fri,  7 Jan 2022 18:38:34 +0000 (UTC)
Return-Path: <*****>
From: Cloud <*******>
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=nicco.io; s=dkim;
	t=1641148715;
	h=from:from:reply-to:subject:subject:date:date:message-id:message-id:
	 to:to:cc:mime-version:mime-version:content-type:content-type:
	 in-reply-to:in-reply-to:references:references;
	bh=Q0j3Ph9l8nLeBMIzdq6aOtNcsZOyiD8WuiQSGgc2oeY=;
	b=nF+9OZeRSSEDZ995inbj/6nDYgbTDMhPGc63Gab3FN1A984PxY7rDoHIhkO5nvh2wzNZG6
	5jIAmfCyYfHriJawNrtcKeUA4wBO5YgYPWag6CbGmWQ8sGSIty2fjIO0W4dWfWy+OjsksX
	sJ2TK8uft8Ax9F9QmQKMuZHBP3Myh/I=
Content-Type: multipart/mixed;
	boundary="Apple-Mail=_DD0DBE9A-59E8-455E-B4DD-1317DF1D24F9"
Mime-Version: 1.0
Subject: =*****
Date: Sun, 2 Jan 2022 19:38:33 +0100
References: <****>
<****>
<****>
<****>
To: ***
In-Reply-To: ****
Message-Id: ****
X-Spam-Level: *
X-Spamd-Bar: +
Authentication-Results: *****;
	auth=pass smtp.mailfrom=*****
```

**Comment by nextgens** [comment]
Is your local DNS resolver supporting DNSSEC? If not can you retry with unbound configured (it's an option in setup)?

Is it failing for all outgoing destinations or just one? If it's one, would you mind sharing the target FQDN?

**Comment by cupcakearmy** [comment]
How can I check? I can try unbound, don't have it in the config rn.
Yes, gmail delivery fails and some other providers too.
Thanks for the quick reply!

**Comment by archerne** [comment]
I am having the same issue:
```
2022-01-04T14:28:48.456222-06:00 cca953dfc6f8 postfix/smtp[428]: warning: TLS policy lookup for gmail.com/gmail-smtp-in.l.google.com: non DNSSEC destination
2022-01-04T14:28:48.456465-06:00 cca953dfc6f8 postfix/smtp[428]: warning: TLS policy lookup for gmail.com/gmail-smtp-in.l.google.com: non DNSSEC destination
2022-01-04T14:28:48.519750-06:00 cca953dfc6f8 postfix/smtp[428]: warning: TLS policy lookup for gmail.com/alt1.gmail-smtp-in.l.google.com: non DNSSEC destination
2022-01-04T14:28:48.519937-06:00 cca953dfc6f8 postfix/smtp[428]: warning: TLS policy lookup for gmail.com/alt1.gmail-smtp-in.l.google.com: non DNSSEC destination
2022-01-04T14:28:48.573257-06:00 cca953dfc6f8 postfix/smtp[428]: warning: TLS policy lookup for gmail.com/alt2.gmail-smtp-in.l.google.com: non DNSSEC destination
2022-01-04T14:28:48.587170-06:00 cca953dfc6f8 postfix/smtp[428]: B66B71C4140: to=<XXXX@gmail.com>, relay=none, delay=0.94, delays=0.24/0.07/0.63/0, dsn=4.7.5, status=deferred (non DNSSEC destination)
```

**Comment by archerne** [comment]
Setting `DEFER_ON_TLS_ERROR` in the env seems to have fixed this for now. Although it looks like it "magically" validated DNSSEC so maybe when I added that to the env file and redeployed it fixed something too?

**Comment by nextgens** [comment]
I suspect that this is down to not having access to a DNSSEC validating resolver.

To fix it you need to either:
- enable DNSSEC validation on your resolver
- enable unbound (so that Mailu uses its own resolver)
- switch to a different DNS resolver (keep in mind that public DNS resolvers such as 8.8.8.8 are usually unsuitable to use with Mailu as they are rate limited on RBLs)

**Comment by nextgens** [comment]
@cupcakearmy would you mind retrying 1.9 with unbound enabled please?

**Comment by cupcakearmy** [comment]
I added 

```
resolver:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}unbound:${MAILU_VERSION:-1.9}
    env_file: .env
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 192.168.203.254
```

To my compose file and the depends_on in the smtp and antivirus but no luck. I checked the generated config but there seems nothing to be configured there? Am I doing something wront?

**Comment by nextgens** [comment]
You should have the following for all containers except unbound:
```
    depends_on:
      - resolver
    dns:
      - <ip of unbound>
```

**Comment by cupcakearmy** [comment]
Adding `dns` entries to each container seems to fix the issue, thanks!

**Comment by leolivier** [comment]
Hi
I have this issue for only one address: team@pcloud.email
I checked the address at https://hunter.io/verify/team@pcloud.email  and it's ok 
All other email addresses are working and I'm able to send an email to this address from eg Gmail...
Maybe I should open a new issue for that?

**Comment by nextgens** [comment]
@leolivier It looks like it's behaving as intended. That destination is just broken.

```
$host -t TLSA _25._tcp.pcloud.email.
Host _25._tcp.pcloud.email not found: 2(SERVFAIL)
$ docker-compose exec smtp /bin/bash
bash-5.1# postmap -q pcloud.email socketmap:unix:/tmp/podop.socket:dane
dane-only
```

SERVFAIL is what we would get if the DNSSEC records were invalid... so mailu acts like it should and defers the email (unless you've set DEFER_ON_TLS_ERROR to False).

If you're only experiencing issues with that destination you can fix it by doing the following:
```
cat >> overrides/postfix/tls_policy <<EOT
pcloud.email may
EOT
```
and recreating your smtp container.

**Comment by leolivier** [comment]
Thank you @nextgens, sorry to have bothered with that. I had figured out the destination was behaving badly and removed my comment but you took it into account...
And thanks for the trick, I'll test it!

**Comment by nextgens** [comment]
Have you reattempted a delivery with ``postqueue -f`` since recreating the container ?

**Comment by baskinsy** [comment]
It was a new attempt after recreating the container. All previous attempts had failed and removed from queue but I tried that also without success.

**Comment by nextgens** [comment]
I guess there are several factors at play here.

```
$nc -C mailn.eett.gr. 25
554 Transaction failed
```

5XX is a permanent error code

**Comment by baskinsy** [comment]
Got it, thank you very much. Any ideas on how to disable (if possible) STARTTLS for this domain only? Will report to them in any case.

**Comment by baskinsy** [comment]
It seems there is not a ```tls_policy.lmdb``` but there are the following:

```
tls_policy.map
tls_policy.map.lmdb
```

First file seems empty although...

**Comment by nextgens** [comment]
Yeah well that's the same error I got earlier. Odds are it will eventually go through.
