### ISSUE TITLE
Weak Diffie-Hellman issue

### ISSUE THREAD

**Issue by ebrahim** [Mailu/Mailu#214]
It seems Mailu suffers from weak Diffie-Hellman security problem. More info: https://weakdh.org/

**Comment by kaiyou** [comment]
The Diffie Hellman generation and use is terrible indeed. I will try and centralize the generation in the admin process, then use the parameters in every related container.

**Comment by kaiyou** [comment]
As a complement to #250, I will try and extract the DH from the `traefik` container, for all others to use. If no automated certificate generation is enabled, the the DH parameters will be generated by the admin container.

**Comment by kaiyou** [comment]
This is fixed in 53c3153229da98afa94a3cbce4c78e19df05a369
