### ISSUE TITLE
Login is failing with older password hashes in Version 1.8

### ISSUE THREAD

**Issue by vanthome** [Mailu/Mailu#2148]
### Environment
 - [ ] docker-compose
 - [x ] kubernetes
 - [ ] docker swarm

### Versions
1.8, coming from 1.6(?)

## Description
I have a user DB that looks like this:

````
| aaaaaaaaaaaa@bbbbbbbb.bb          | $bcrypt-sha256$v=2,t=2b,r=12$Pyvf7pxxxxxxxxVNSQg.$F649N4If9x1556ec1zaO2T1SG4izH4.                                                        |
| cccccccccccc@ddddddddddd.dd       | {PBKDF2}$pbkdf2-sha512$25000$Ruh9z5mT0xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxHyYK7dzDfEc1SjoH/tG0BZwrRJG6IakAof4DcTMsaGBbAD5KE6rIm1R1S9Q |
````

Today I have upgraded to 1.8 from 1.6 (older helm charts did not use versioned images). After the upgrade, I could not log in with users having `bcrypt-sha256` PW hashes; `PBKDF2` hashes worked. I saw there were changes in the supported algos but this should still be supported. I have fixed this by downgrading only the admin service to `pr-1888` and it works again.

## Replication Steps
Have older password hashes around in the DB and then upgrade

## Expected behaviour
Log-in is still possible

## Logs

in the admin service:

```
ValueError: hash could not be identified
```

**Comment by nextgens** [comment]
Support for ```bcrypt-sha256``` was introduced in #1753 (that's 1.9+), previous versions had support for ```bcrypt```, introduced in #647

What I suspect happened is that you have upgraded to 1.9 or master... and tried to roll-back to 1.8; that's not supported and as you can see doesn't work. Options from there are either to restore a backup (that will have the older version of the hashes) or upgrade to 1.9 (helm is almost but not quite working yet, join https://riot.im/app/#/room/#mailu:tedomum.net for help if required)

By the way, mix-and-matching different versions of the various containers is also a bad idea (it *will* break SSO)

**Comment by nextgens** [comment]
This is kind of related to #2104 ... maybe we should improve upon the message being logged.

**Comment by nextgens** [comment]
@vanthome did you find a way out of it? can this be closed?

**Comment by vanthome** [comment]
I thin you are right here! I'm using a helm chart that uses `master` tag by default and only afterwards I have downgraded to 1.8 because that is the stable release. I will test it once i.9 is released. Should there be still this issue, I will reopen it.

**Comment by nextgens** [comment]
OK

My understanding is that https://github.com/Mailu/helm-charts/tree/feature/1.9-fixes is mostly working at this point... see if it helps.
