### ISSUE TITLE
Strengthening SSL/TLS security

### ISSUE THREAD

**Issue by ebrahim** [Mailu/Mailu#215]
Qualys SSL Labs Test says Mailu should fix this: https://blog.qualys.com/ssllabs/2017/03/13/caa-mandated-by-cabrowser-forum

**Comment by kaiyou** [comment]
Well, this is not for Mailu to fix. If you want to use CAA, you must first determine which CA is signing your certificate, then update your DNS records. Mailu simply cannot because it does not have access to your zone file.
