### ISSUE TITLE
Web admin does not allow adding of more than 59 alias (per domain)

### ISSUE THREAD

**Issue by airinformation** [Mailu/Mailu#2167]
Thank you for opening an issue with Mailu. Please understand that issues are meant for bugs and enhancement-requests.
For **user-support questions**, reach out to us  on [matrix](https://matrix.to/#/#mailu:tedomum.net).

To be able to help you best, we need some more information.

## Before you open your issue
- [ X ] Check if no issue or pull-request for this already exists.
- [ X ] Check [documentation](https://mailu.io/master/) and [FAQ](https://mailu.io/master/faq.html). (Tip, use the search function on the documentation page)
- [ X ] You understand `Mailu` is made by volunteers in their **free time** — be conscise, civil and accept that delays can occur.
- [ X ] The title of the issue should be short and simple. It should contain specific terms related to the actual issue. Be specific while writing the title.

### Environment
 - [ X ] docker-compose
 - [ ] kubernetes
 - [ ] docker swarm

### Versions
To find your version, get the image name of a mailu container and read  the version from the tag (example for version 1.7).
```
$> docker ps -a | grep mailu
e76d95f7db72   mailu/roundcube:1.9   "docker-php-entrypoi…"   2 days ago    Up 2 days (healthy)      80/tcp

$> grep MAILU_VERSION docker-compose.yml mailu.env
docker-compose.yml:    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}nginx:${MAILU_VERSION:-1.9}

## Description
In the Web Admin, you cannot add any new aliases on a domain if there are already 59. 
In the CLI, there is no limit and you can add more than 59 aliases.
Any aliases added in the CLI (>59) are visible in the Web Admin

## Replication Steps
Create 59 aliases, and then try adding the 60th one in the Web Admin

## Expected behaviour
Expect no limits to the number of allowed (new) aliases to be allowed in the Web Admin

## Logs
Often it is very useful to include log fragments of the involved component. You can get the logs via `docker logs <container name> --tail 1000`. For example for the admin container:

No errors relating to aliases reported by
`docker logs mailu_admin_1 --tail 1000`
`docker logs mailu_front_1 --tail 1000`

**Comment by Diman0** [comment]
I cannot replicate this. I can create more than 60 aliases in Web admin. There should be no artificial limit in the web administration interface. There must be something unique with your deployment.

What do you see when you try to add a 60th alias?
Can you perhaps see an error in the console of the developer tools of the internet browser?
What database backend do you use? If it is not SQLite, do you see any errors in the database server logs?

**Comment by airinformation** [comment]
I am using SQLite so that are no logs I don't think.
I don't see any errors reported on the server itself
The problem seems to be here
https://github.com/Mailu/Mailu/blob/ff4d3f4d375b020867a737fe5e44d3ae14e41705/core/admin/mailu/ui/views/aliases.py#L19
But I'm not sure what the maximum number of aliases is actually set to, and how to change it

**Comment by airinformation** [comment]
I have three domains on my setup; one with 60+ aliases where I cannot add any more through the webUI
and the other two domains with just a few aliases where the webUI will continue to allow me to add more aliases

Is there a way to change the domain.max_aliases setting? And to determine what it is?

**Comment by airinformation** [comment]
OMG - I've just found the Edit Domain setting where max_aliases is set/displayed.
By default it is set to 10
Changing it to 100 allowed me to add more aliases through the webUI
![domain-edit](https://user-images.githubusercontent.com/97469569/151378271-e0cb0394-0af5-4fed-8653-b290bb75b8ea.jpg)
