### ISSUE TITLE
Improvement: Store mail in the folder

### ISSUE THREAD

**Issue by Archie1978** [Mailu/Mailu#217]
I have seen that all emails are stored in a mail folder directly. This limits the number of mail to be processed.
/mailu/mail/toto@example.com

Generally in the system of a certain sizes, one makes the domains then the emails of the domain.
/mailu/mail/example.com/toto

When do you think ?

**Comment by kaiyou** [comment]
As long as you are not browsing the directory, all should be fine. Ext4 for instance is capable of storing 4 billion files per directory on a standard setup I believe. It would be nice however to help migrations/backups.

We'd have to think about migrating from one scheme to the other however.

**Comment by Archie1978** [comment]
I'm all in agreement. A folder under ext4 / btrfs / xfs / hdfs can contain milion of files. To access its files does not change anything even if there is not much file.

On the other hand, if I want to know if all email stores that are in a domain for a maintenance issue. 
You write :
 ls -la | grep '@toto.com$'

On 4 billion your order will last very long with 1000 emails the time is more long.

**Comment by kaiyou** [comment]
Indeed, it will take more time. But it should scale linearly and I do not think that Mailu instances will be hosting more than a couple thousands accounts in the next couple of months :)

**Comment by nalt** [comment]
It should be possible to do this via an overrides/dovecot.conf:
mail_location = maildir:/mail/%d/%n

**Comment by kaiyou** [comment]
Indeed, @nalt solution sounds like the best way to go for now. If huge Mailu instances become the norm, we can still make it a configurable option with a migration script, but nothing urgent I believe.
