### ISSUE TITLE
Port 25 is closed on Brasil

### ISSUE THREAD

**Issue by pedronet007** [Mailu/Mailu#2170]
## Description
Please, How can I change postfix to send and receive emails only on port 587 ?
Because on Brazil port 25 is closed for all ISP providers.

I tried this:
root@mail:/mailu/overrides/postfix# cat master.cf
submission inet n       -       n       -       -       smtpd

But is only open 587 port. on the mail_smtp container.

postfix still using 25 to send .
The mail system
<pedro.felix@outlook.com>: connect to
    outlook-com.olc.protection.outlook.com[104.47.66.33]:25: Operation timed
    out

BUT port 25 is blocked on Brazil.

Thanks

**Comment by ktechmidas** [comment]
Not possible, if you're sending emails from server->server it needs to be on 25. If you're sending emails between your client and the server (which will send it on on 25) that can be on 587

You need to use a relay that allows port 25

**Comment by pedronet007** [comment]
ok.  i´m trying make everything from scrath again..  mailu1.9
but I stiil receive this message when send emails..  from \webmail

"If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<meuemail@outlook.com>: non DNSSEC destination"

**Comment by pedronet007** [comment]
Ok, thanks. I discovered ,  the Oracle Cloud provider block´s 25 port.
I have opened case support to open port.
Its same on AWS,  we need request remove email sending limitations
