### ISSUE TITLE
DNS DKIM entry has random " " in it

### ISSUE THREAD

**Issue by archerne** [Mailu/Mailu#2176]
## Before you open your issue
- [ x] Check if no issue or pull-request for this already exists.
- [ x] Check [documentation](https://mailu.io/master/) and [FAQ](https://mailu.io/master/faq.html). (Tip, use the search function on the documentation page)
- [ x] You understand `Mailu` is made by volunteers in their **free time** — be conscise, civil and accept that delays can occur.
- [ x] The title of the issue should be short and simple. It should contain specific terms related to the actual issue. Be specific while writing the title.

### Environment
 - [ x] docker-compose
 - [ ] kubernetes
 - [ ] docker swarm

### Versions
```
1.9
```

## Description
Further explain the bug in a few words. It should be clear what the unexpected behaviour is.  Share it in an easy-to-understand language.
On the `admin/domain/details` page the DNS DKIM entry it shows the value like this:
```
dkim._domainkey.domain. 600 IN TXT "v=DKIM1; k=rsa; p=<part of the key>" "<the rest of the key>"
```
This can be seen on the demo portal:
![dkim](https://user-images.githubusercontent.com/561565/150401469-7590f82d-7314-4952-8009-eae1acce112a.PNG)

## Expected behaviour
It should be:
```
dkim._domainkey.domain. 600 IN TXT "v=DKIM1; k=rsa; p=<rsa of the key>"
```

**Comment by kumanoko24** [comment]
Just had this problem, most of the dns providers' interface will handle this part, so the displaying in Mailu-Admin should be just raw text without splitting.

**Comment by ghostwheel42** [comment]
> most of the dns providers' interface will handle this part

Some do, some do not - this is why we display both DKIM public key notations.
