### ISSUE TITLE
Improved: Add date into vacation

### ISSUE THREAD

**Issue by Archie1978** [Mailu/Mailu#218]
Hello,
   I have tested a vacation this morning and I realized that there are not a date.

It often happens that I am called in advance to put a date from 10/07/2017 to 22/07/2017 ;).

Therefore, it would require a start date and an end date in vacation.

**Comment by kaiyou** [comment]
Yes, thank you for creating a ticket, this a a required feature that I have been willing to add for some time.

**Comment by Archie1978** [comment]
thanks you kaiyou, I goto update

**Comment by kaiyou** [comment]
Make sure that you first properly migrate to branch ``1.5``, as ``.env`` and the Compose file have changed.. a lot :)
