### ISSUE TITLE
Sending from aliases does work when using Roundcube  but not with Thunderbird

### ISSUE THREAD

**Issue by random36** [Mailu/Mailu#2181]
Thank you for opening an issue with Mailu. Please understand that issues are meant for bugs and enhancement-requests.
For **user-support questions**, reach out to us  on [matrix](https://matrix.to/#/#mailu:tedomum.net).

To be able to help you best, we need some more information.

## Before you open your issue
- [ x ] Check if no issue or pull-request for this already exists.
- [ x ] Check [documentation](https://mailu.io/master/) and [FAQ](https://mailu.io/master/faq.html). (Tip, use the search function on the documentation page)
- [ x ] You understand `Mailu` is made by volunteers in their **free time** — be conscise, civil and accept that delays can occur.
- [ x ] The title of the issue should be short and simple. It should contain specific terms related to the actual issue. Be specific while writing the title.

### Environment
 - [ x ] docker-compose
 - [ ] kubernetes
 - [ ] docker swarm

## Description
Seding e-mails from aliases that are created for a user works when I send from Roundcube, but when i try to send from thunderbird i get the error message "Error: Sender address rejected: User unknown in virtual mailbox table.". Aliases are set as identities for the user in both MUAs. Receiving mails on those aliases also works without issue.

## Replication Steps
Issue happened on freshly setup server only modifications i made where:
*  setting um mta-sts policy as described here: https://mailu.io/1.9/faq.html#how-do-i-setup-a-mta-sts-policy

*  modifying the tls.conf of nginx to prioritise 256 bit ciphers over 128 bit ciphers.

## Expected behaviour
Being able to send from aliases independently of chosen MUA.

## Logs
```
mailu-smtp-1       | 2022-01-22T00:03:57.692341+00:00 395e385bbdcd postfix/smtpd[37428]: NOQUEUE: reject: RCPT from host-redacted[ip redacted]: 550 5.1.0 <e-mail redacted>: Sender address rejected: User unknown in virtual mailbox table; from=<e-mail redacted> to=<e-mail redacted> proto=ESMTP helo=<[ip redacted]>
```

**Comment by Diman0** [comment]
This error indicates the alias was not created in the Mailu Admin interface.
If the alias was created, then it is important to login with the correct user.
e.g.  If alias@example.com is created as alias for example@example.com, then you must login the smtp server with user example@example.com. 
You cannot login the smtp server using a different Mailu user.

**Comment by random36** [comment]
The aliases i tested this with, were all created within the Mailu Admin interface and are visible there.I even queried the aliases table in the database manually (`sqlite3 main.db "SELECT * FROM alias;"`)  to confirm that the aliases are there, which they are. The user used to login is also the same user (same username and password) in both MUAs and is an actual user and not an alias.

**Comment by random36** [comment]
Update: Issue resolved. Reason: Typo
