### ISSUE TITLE
max attachement size with rainloop is 1mb

### ISSUE THREAD

**Issue by audioscavenger** [Mailu/Mailu#2186]
### Environment
 - [x] docker-compose
 - [ ] kubernetes
 - [ ] docker swarm

### Versions
1.9

## Description
cannot attach anything larger then 1,048,300 bytes to any email from rainloop

## Replication Steps
attach anything larger then 1,048,300 bytes to any email from rainloop and it will fails with http 413

## Expected behaviour
i can attach any file as large as the MESSAGE_SIZE_LIMIT as defined in (mailu.env - 33%)

## Logs
browser log only: for the xhr POST
````markdown
```
413 Request Entity Too Large
```
````

**Comment by marioja** [comment]
Good day please see the comment in this pool request: https://github.com/Mailu/Mailu/pull/2149#issuecomment-1021784532

This explains that something needs to be changed also in the webmail container
