### ISSUE TITLE
SPF_HELO_NONE - SPF: HELO does not publish an SPF Record

### ISSUE THREAD

**Issue by audioscavenger** [Mailu/Mailu#2188]
### Environment
 - [x] docker-compose
 - [ ] kubernetes
 - [ ] docker swarm

### Versions
1.9

## Description
testing emails sent from rainloop with https://www.mail-tester.com/ returns some warnings from Spamassasin lowering your acceptability score. one easy one to fix is ` -0.001		SPF_HELO_NONE		SPF: HELO does not publish an SPF Record`

## Replication Steps
send an email through the dmarc/dkim validator tool https://www.mail-tester.com/

## Expected behaviour
`SPF_HELO_PASS		SPF: HELO matches SPF record`

## Logs
no logs, it's an smtp issue in /etc/postfix/main.cf

**Comment by Diman0** [comment]
This works as intended. Mailu uses the first domain from HOSTNAMES for HELO/EHLO.
This error indicates you did not publish a SPF record for your EHLO/HELO.
This is not mandatory. See https://datatracker.ietf.org/doc/html/rfc7208#section-2.3
It is only recommended. Possibly the Mailu web interface could be enhanced to also show the SPF record for the EHLO/HELO name.

For more information see http://www.open-spf.org/action_browse_id_FAQ/Common_mistakes_revision_26/#helo
