### ISSUE TITLE
XCLIENT not blocked - Received header changed

### ISSUE THREAD

**Issue by marinkobabic** [Mailu/Mailu#2198]
```
Jan 30 12:24:44 mail postfix/smtpd[2696344]: C79C22F81890: client=unknown[14.139.58.66], sasl_method=XCLIENT, sasl_username=info@mydomain.com
INFO:root:Connect 
Jan 30 12:24:47 mail postfix/cleanup[2696347]: C79C22F81890: replace: header Received: from 14.139.58.66 (unknown [14.139.58.66])??by mail.mydomain.com (Postfix) with ESMTPA id C79C22F81890??for <blabla@t-online.de>; Sun, 30 Jan 2022 12:24:43 +0000 (UTC) from unknown[14.139.58.66]; from=<info@mydomain.com> to=<blabla@t-online.de> proto=ESMTP helo=<14.139.58.66>: Received: from authenticated-user (mail.mydomain.com [161.97.xxx.xx])??by mail.mydomain.com (Postfix) with ESMTPA id C79C22F81890??for <blabla@t-online.de>; Sun, 30 Jan 2022 12:24:43 +0000 (UTC)
Jan 30 12:24:47 mail postfix/cleanup[2696347]: C79C22F81890: message-id=<>
Jan 30 12:24:49 mail postfix/smtpd[2696164]: connect from localhost[127.0.0.1]
Jan 30 12:24:49 mail postfix/smtpd[2696164]: disconnect from localhost[127.0.0.1] quit=1 commands=1
Jan 30 12:24:49 mail postfix/qmgr[366]: C79C22F81890: from=<info@mydomain.com>, size=48309, nrcpt=1 (queue active)
```
I have set the SUBNET and have done tests and I can confirm that the server is not an open relay. This is fine so far. SUBNET values is configured to subnet: 192.168.27.0/24. I would expect that only mailu front can use the protocol XCLIENT, but according to this log another ip is using XCLIENT as well. It seems like this hacker is replacing the Received header so that the mail is getting accepted and sent out. What does this mean "Received: from authenticated-user", does the hacker have the credentials or does this mean that the sender ip has been accepted?

Any help is appreciated.

**Comment by nextgens** [comment]
This doesn't look abnormal.

Can you confirm that the range you have picked for SUBNET is not your LAN's?

Can you paste the output of the following command please?
```docker-compose exec smtp postconf smtpd_authorized_xclient_hosts```

Do you have the matching logs from the front container?

To me it looks like 14.139.58.66 is in possession of the credentials for info@mydomain.com. Does info@mydomain.com exist?

**Comment by nextgens** [comment]
I've tested it locally and can't reproduce; Assuming that this is still ongoing, can you please provide a packet capture?

**Comment by marinkobabic** [comment]
Sorry for the delay. The whole solution is running on Kubernetes by using HostPort which is actually the only way to prevent an open relay. Here the applied values

```yaml
database:
  postgresql:
    database: mailu
    host: postgres.database.svc.cluster.local
    password: xypassword
    roundcubeDatabase: roundcube
    roundcubePassword: roundxxllskks
    roundcubeUser: myusser
    user: mailu
  roundcubeType: postgresql
  type: postgresql
domain: mydomain.com
front:
  externalService:
    enabled: false
    externalTrafficPolicy: Local
    type: LoadBalancer
  hostPort:
    enabled: true
hostnames:
- mail.mydomain.com
ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: nginx
initialAccount:
  domain: mydomain.com
  password: sxxkkslsllsls!
  username: admin
logLevel: INFO
mail:
  authRatelimit: 100/minute;3600/hour
  messageSizeLimitInMegabytes: 200
persistence:
  size: 100Gi
secretKey: skskksks-
subnet: 192.168.27.0/24
```
I have disabled roundcube just to check if the mails are coming from the UI, but this is not the case. The reason why XCLIENT works is that the sending of mails is happening by using the front container. If I disable front container, then there are no spam mails, which is clear, no ports are exposed to internet when front is not running.

Here the requested output
```
smtpd_authorized_xclient_hosts = 192.168.27.0/24
```

I wanted to provide here the log of the front, but waiting for the spam client to connect. Will keep you updated.

**Comment by nextgens** [comment]
The above shows that there is a limit on where we accept xclient from. In Mailu it's expected for front to use xclient when talking to postfix.

There is nothing abnormal in the logs you have pasted above; My guess is that the credentials are known by a 3rd party; Are you sure that a password has actually been set for that user?

The configuration you have pasted above looks outdated. Which version of mailu are you running? Current stable (1.9) doesn't expect authRatelimit as specified.

**Comment by nextgens** [comment]
> I wanted to provide here the log of the front, but waiting for the spam client to connect. Will keep you updated.

Can't you pull the logs corresponding to the timestamps of what you have pasted above?

**Comment by marinkobabic** [comment]
The problem is solved. Many thanks @nextgens for your time, really appreciated. Here what happened:

We have on the same server wordpress solution running. It seems like the log4shell issue was used in order to get into that server, so they got the credentials for one specific email address. This email address was used to send spam. After changing the password of this specific e-mail account and updating the wordpress to the newest version, I can see several requests in the log 

```
161.97.140.40 - - [02/Feb/2022:10:30:59 +0000] "GET /health HTTP/1.1" 204 0 "-" "kube-probe/1.20"
2022/02/02 10:31:02 [info] 12#12: *10465 client 106.75.54.33:46779 connected to 0.0.0.0:465
161.97.140.40 - - [02/Feb/2022:10:31:03 +0000] "GET /health HTTP/1.1" 204 0 "-" "kube-probe/1.20"
2022/02/02 10:31:07 [error] 12#12: *10465 106.75.54.33 could not be resolved (3: Host not found) while in resolving client address, client: 106.75.54.33, server: 0.0.0.0:465
2022/02/02 10:31:08 [info] 12#12: *10465 client login failed: "Authentication credentials invalid" while in http auth state, client: 106.75.54.33, server: 0.0.0.0:465, login: "info@mydomain.com"
```

Once more many thanks for your time.
