### ISSUE TITLE
Setting TLS_FLAVOR=notls does not prevent front from redirecting to https

### ISSUE THREAD

**Issue by audioscavenger** [Mailu/Mailu#2204]
## Before you open your issue
- [x] Check if no issue or pull-request for this already exists.
- [x] Check [documentation](https://mailu.io/master/) and [FAQ](https://mailu.io/master/faq.html). (Tip, use the search function on the documentation page)
- [x] You understand `Mailu` is made by volunteers in their **free time** — be conscise, civil and accept that delays can occur.
- [x] The title of the issue should be short and simple. It should contain specific terms related to the actual issue. Be specific while writing the title.

### Environment
 - [x] docker-compose
 - [ ] kubernetes
 - [ ] docker swarm

### Versions
1.9

## Description
setting TLS_FLAVOR=notls seems to not works as front nginx keeps redirecting to https and also gives http 403

## Replication Steps
set TLS_FLAVOR=notls in mailu.env

## Expected behaviour
external proxy handling certificates correctly redirect to mailu http and mailu logic correctly works without certificates

## Logs
n/a

**Comment by Diman0** [comment]
notls is only meant for specific test scenario's. It is not meant for production usage. 
You want to use TLS_FLAVOR=mail as documented here (https://mailu.io/1.9/compose/setup.html#tls-certificates).
You still have to setup certs for mailu. The certs are required for SMTPS and starttls. See https://mailu.io/1.9/compose/setup.html#finish-setting-up-tls.
