### ISSUE TITLE
Provide a "slow" transport for Postfix

### ISSUE THREAD

**Issue by FabriceLapeyrere** [Mailu/Mailu#2213]
### Environment
 - [x] docker-compose
 - [ ] kubernetes
 - [ ] docker swarm

### Versions
1.9

## Description
Orange, a mainstream french ISP, and a few others, have a rate limit : without a slow transport, I get deferred messages with this : "Too many connections, slow down." It is a known issue https://blog.network-studio.fr/2011/06/30/too-many-connections-slow-down/

I managed to get it done with the overrides/ files :

overrides/postfix.cf :

```
transport_maps = socketmap:unix:/tmp/podop.socket:transport lmdb:/etc/postfix/transport.map

slow_destination_concurrency_limit = 1
slow_destination_recipient_limit = 20
slow_destination_rate_delay = 5s
slow_destination_concurrency_failed_cohort_limit=10

```
overrides/postfix.master :

```
slow/unix= slow unix - - n - 5 smtp -o syslog_name=postfix-slow
```

overrides/transport.map :

```
wanadoo.com slow:
wanadoo.fr slow:
orange.com slow:
orange.fr slow:
laposte.net slow:
free.fr slow:
hotmail.fr slow:
outlook.fr slow:
yahoo.fr slow:
```
I did not have time to fully test it, but it seems to work. Configuration values may need a fine tuning...

It would be nice to have such "slow" transport built in in Mailu, with an override possibility to edit the domain list.

**Comment by nextgens** [comment]
@FabriceLapeyrere would you mind giving #2255 a try please?

You should be able to pull the images directly from dockerhub once they are built (``docker pull mailuci/postfix:pr-2255``)
