### ISSUE TITLE
fail2ban proposal - use ipset rather than plain iptables

### ISSUE THREAD

**Issue by tkaefer** [Mailu/Mailu#2214]
Thank you for opening an issue with Mailu. Please understand that issues are meant for bugs and enhancement-requests.
For **user-support questions**, reach out to us  on [matrix](https://matrix.to/#/#mailu:tedomum.net).

To be able to help you best, we need some more information.

## Before you open your issue
- [x] Check if no issue or pull-request for this already exists.
- [x] Check [documentation](https://mailu.io/master/) and [FAQ](https://mailu.io/master/faq.html). (Tip, use the search function on the documentation page)
- [x] You understand `Mailu` is made by volunteers in their **free time** — be conscise, civil and accept that delays can occur.
- [x] The title of the issue should be short and simple. It should contain specific terms related to the actual issue. Be specific while writing the title.

### Environment
 - [x] docker-compose
 - [ ] kubernetes
 - [ ] docker swarm

## Description
ipset is a nice addon for iptables, if you filter a lot of IPs with the same rule - as it is for blocking with fail2ban.

So the change (using the example from the faqs) would be something like:
```
[Definition]

actionstart = actionstart = ipset --create f2b-bad-auth iphash
              iptables -I DOCKER-USER -p tcp -m multiport --dports 1:1024 -m set --match-set f2b-bad-auth src -j DROP

actionstop = iptables -D DOCKER-USER -p tcp -m multiport --dports 1:1024 -m set --match-set f2b-bad-auth src -j DROP
             ipset --destroy f2b-bad-auth


actionban = ipset --test f2b-bad-auth <ip> ||  ipset --add f2b-bad-auth <ip>

actionunban = ipset --test f2b-bad-auth <ip> && ipset --del f2b-bad-auth <ip>
```

In the end you just have one iptable rule. Specially when dealing with bigger attacks, this come in handy, since having a lot of iptable rules might have a big impact on the network performance. I do have like 1000+ entries in the ipset, with no big load to be handled. This was very different when I had them as individual iptable rules in an own chain.

Do you think this is worth to have a PR to add this to the FAQs?

**Comment by gldickens3** [comment]
Several years ago I merged ipset with fail2ban similar to the way that this is described and it works great, especially if you are  interested in permanent bans and it works so much more efficiently than iptables.
