### ISSUE TITLE
missing translation for string "Start of vacation" in admin 1.9.12 Auto-reply form

### ISSUE THREAD

**Issue by level420** [Mailu/Mailu#2217]
## Before I've opened the issue
- [x] Checked if no issue or pull-request for this already exists.
- [x] Checked [documentation](https://mailu.io/master/) and [FAQ](https://mailu.io/master/faq.html). (Tip, use the search function on the documentation page)
- [x] I've understood `Mailu` is made by volunteers in their **free time** — be conscise, civil and accept that delays can occur.
- [x] The title of the issue is short and simple but precise. It contains specific terms related to the actual issue. I was specific while writing the title.

### Environment
 - [x] docker-compose
 - [ ] kubernetes
 - [ ] docker swarm

### Versions
1.9.12. fresh docker-compose pull minutes before writing this issue.

## Description
In `/admin` there is a missing translation for the string "Start of vacation" in the "Auto-reply" dialog. At least for DE and ES the translation is missing.

## Replication Steps
Login into `/admin`, go to "Auto-reply" and change the language via the languages selector in the top right corner to "Deutsch".  See the string remains untranslated "Start of vacation".

## Expected behaviour
The string should be translated for DE as "Beginn der Abwesenheit".

**Comment by DjVinnii** [comment]
I just opened a PR for the missing Dutch translation as well as the German translation for `Start of vacation` as provided by you. Could you maybe have a look at other missing German translations so they can be added in the same PR?
