### ISSUE TITLE
Specify Postfix client address (smtp_bind_address)

### ISSUE THREAD

**Issue by colinleroy** [Mailu/Mailu#2219]
Hello,

I'm running mailu version 1.7 from docker-compose. It works really fine, except for one detail. I would want to force Postfix to use a specific address (the service VIP) for sending email, but it uses the default one (the physical IP).
I have tried to add an overrides/postfix.cf file containing

smtp_bind_address=212.83.157.151

But this is not possible as postfix runs in a container, and the logs show:

postfix/smtp[137]: warning: smtp_connect_addr: bind 212.83.157.151: Address not available

This impacts deliverability.

There is a way to bind docker containers to listen on specific IPs, but I cannot find a way to have them establish outgoing connections using a specific IP.
Can you help?

Many thanks in advance,
Colin

**Comment by nextgens** [comment]
This isn't something that can be addressed within Mailu. The host should be configured to pick the right outbound IP for the traffic originating from docker (or the mailu containers in docker).

http://linux-ip.net/html/routing-selection.html
man iptables-extensions
