### ISSUE TITLE
Setting upDKIM/SPF & DMARC Entries using CLI

### ISSUE THREAD

**Issue by anthonybe98** [Mailu/Mailu#2224]
Hey Everyone, I'm trying to setup DKIM/SPF & DMARC Entries using the CLI because my emails are getting rejected. I tried looking at the documentation but all I could find is a sentence saying use CLI or admin panel along with the steps for the admin panel. I disabled the admin panel in my Mailu.env so I can't do it that way.
Thank you!

**Comment by ghostwheel42** [comment]
If you want to configure dkim via cli you can do this using the configuration import feature: https://mailu.io/1.9/cli.html#config-import

To see what is possible you can export the current configuration using the --full option. 

You can create a new key by adding dkim_key: -generate- to a domain.
When exporting the configuration using the --dns option afterwards you can see what needs to be configured in dns.
