### ISSUE TITLE
nginx.conf manual override not working as in docs

### ISSUE THREAD

**Issue by yogitea** [Mailu/Mailu#2232]
### Environment
 - [x ] docker-compose
 - [ ] kubernetes
 - [ ] docker swarm

Mailu 1.9

## Description

In Override Mailu configuration https://mailu.io/master/reverse.html#override-mailu-configuration it is mentioned that in case someone wants to change the nginx config, they should just do a volume override like this.
`  volumes:
    - "$ROOT/certs:/certs"
    - "$ROOT/nginx.conf:/etc/nginx/nginx.conf"
`

I tried this, but seems like the actual 
core/nginx/config.py

is always run at container startup and will override it again.

## Replication Steps
Mount nginx.conf in docker compose
 - "$ROOT/nginx.conf:/etc/nginx/nginx.conf"
and then edit the file. Restart the container.

## Expected behaviour
Expected from logs would be the possibility to keep the local changes.

## Workaround
I am now building my own docker container and modify the file before, but that is much more cumbersome than the volume override.

Thanks for the great work.

**Comment by Diman0** [comment]
I think that part is outdated. You can put your *.conf override files in $root/overrides/nginx/ as documented here https://mailu.io/master/faq.html#how-can-i-override-settings.

It will be included here in the nginx.conf file
https://github.com/Mailu/Mailu/blob/b73963aae5177770c64c8e04be7c11b00317f0a5/core/nginx/conf/nginx.conf#L135

The reverse proxy documentation must be corrected.

**Comment by yogitea** [comment]
@Diman0 Thanks for reviewing the bug. Unfortunately the overrides do not work in my case, because I wanted to change more fundamental things in the nginx.conf. (adding another server directive) While my use-case for that has gone away, the documentation is still wrong in the way that this way of mounting does not work.
