### ISSUE TITLE
/static/ clashes with /static/ of Mailman - can /static/ be changed?

### ISSUE THREAD

**Issue by yogitea** [Mailu/Mailu#2233]
### Environment
 - [X ] docker-compose
 - [ ] kubernetes
 - [ ] docker swarm

### Versions
1.9

## Description
I am trying to combine Mailu and Mailman as described here:
https://patrick.georgi.family/2019/01/12/combining-mailman-3-with-mailu/

The solution there was done on 1.5 and since then some things probably have changed.
One specific annoyance is that both Mailu and Mailman use /static/ to serve static images, and therefore one or the other is not working correctly.
I did not find any easy way to change the Mailu Flask App to use something else than /static/

Is there maybe a workaround that I missed?

## Expected behaviour
Don't know if it would make sense to have a config item for the static files dir, so it can be changed easily.

Thanks for the great work!

**Comment by nextgens** [comment]
The short answer is no.

Sharing the same FQDN for the mailing list AND "other" emails is probably not a great idea either deliverability-wise... I suggest you configure mailman to use "lists.example.org" instead; that will solve the problem (you will be able to add an override to front to serve all mailman related stuff from its own FQDN).

**Comment by yogitea** [comment]
Thanks @nextgens Actually I think I found most places where static could be changed in the code, but then I cannot build admin container because of the sass bug. But you are right probably best to change the Front Container. Will try it the other way.
