### ISSUE TITLE
[Docs] Missing environment variable 'HOST_FRONT'

### ISSUE THREAD

**Issue by peterpramb** [Mailu/Mailu#2237]
## Version
`1.9`

## Description
The `imap` container (Dovecot) references an environment variable `HOST_FRONT` (or `FRONT_ADDRESS`) to get the `front` container (Nginx) for mail submission.

Please add it to the environment list in the [documentation](https://mailu.io/1.9/configuration.html#infrastructure-settings).

**Comment by ghostwheel42** [comment]
We will rework the name resolution at startup and all '*_ADDRESS' and 'HOST_*' variables for the next major release.

**Comment by nextgens** [comment]
HOST is now gone in master
