### ISSUE TITLE
Donations

### ISSUE THREAD

**Issue by L0g4n** [Mailu/Mailu#2238]
Hey everybody,

do you guys have already published information about a way to make donations to this project?

I'd like to support this project to help keeping it alive.

**Comment by elandorr** [comment]
If possible please avoid the tyrannical abusers like gofundme et al. and just give us a bank account number. It's cheaper, and if in the same region (NA/EU), often **free**. Even liberapay etc. are just useless middlemen.
It can also be used via wise.com, which is by far the cheapest option if you're on the other side of the world. Extremely much cheaper than the tyrants' sites anyway. Win-win.

If we can all contribute a little bit to support the Mailu team in fixing all the open issues and keep it going that'd be great. Just a little bit from everyone could amount to a lot. It's the only open source project of this particular kind and provides what many need. Nothing else is exactly like it (standalone dockerized, relatively light), not even the commercial ones.

**Comment by Diman0** [comment]
In the hopefully near future it will be possible to donate to the project via https://crowdfunding.lfx.linuxfoundation.org/projects/mailu
At the moment I'm trying to get ownership of  this funding project. The previous owner of this funding project has been inactive for a long time and is unreachable. So it is not possible to access the donated funds. I already started the process to be made owner. It is now simply a matter of waiting. When I joined the Mailu project, the previous owner was already inactive and unreachable. 

I hope this process is finished within a couple of weeks. After that the fund link will be reactivated. Until then, I advise not to donate via that link.

**Comment by Diman0** [comment]
Good news. Ownership was transferred to me. I re-enabled the donation link. 
The link for the donation page is https://crowdfunding.lfx.linuxfoundation.org/projects/mailu.
This link is also viewable from the main github page https://github.com/Mailu/Mailu. Search for 'sponsor this project'.

I will close this issue now.
