### ISSUE TITLE
Setting user storage quotas more finely

### ISSUE THREAD

**Issue by elandorr** [Mailu/Mailu#2242]
Currently you can only set it from 1..50GiB. I'd like/need to set it to less than that.

You can create new users via the cli and specify bytes as per https://mailu.io/1.9/cli.html#user , but I don't see an option to update existing users.

The 'thumbsup' isn't me congratulating myself, I was instructed to use it as a sign of interest.

**Comment by elandorr** [comment]
Is there any risk in directly updating the `./data/main.db`? Would also make it easier to change all users to the new limit.
`update user where email='foo@bar.com' set 'quota_bytes'=100000;`
I tried on my own account and it seems to work, but I'd rather ask than cause unforeseen consequences if it wasn't intended to be edited like that.

**Comment by elandorr** [comment]
Bump. I'd appreciate a short reply regarding my temporary solution (editing the DB directly). If this works I'm fine for now.

**Comment by ghostwheel42** [comment]
@elandorr You should use the command line client rather than editing the db directly. 
Flask mailu config-import enables you to do what you want.

**Comment by elandorr** [comment]
@ghostwheel42 You mean export, then import and overwrite?

**Comment by ghostwheel42** [comment]
@elandorr yes, the "-u" enables the update mode and your snippet shows how it can be used.
the old 'config-update' will be marked as deprecated in the near future.
Maybe there is a more flexible approach for the slider in the admin ui? I don't have an idea right now.

**Comment by elandorr** [comment]
> and your snippet shows how it can be used.

Do I need any permissions to put this on the docs? I'd document the details I find out/ask for so others can find it too and you save some time.

> Maybe there is a more flexible approach for the slider in the admin ui?

Personally we don't need any design, an HTML4 table with input box is fine for me. Just needed to set it lower than the GB increments. An overview of used space would also be very helpful, per domain, and total.

The storage used shown per mailbox doesn't seem to include all the metadata and especially not the xepian stuff (also see #2268). This needs to be taken into account by the admin when planning. An extra field/hardlimit might be useful if that is even possible.

I noticed the undocumented `setlimits` option: I used it on a domain with only 1 mailbox, which is now set to the given limit. Is this intended to be used by the admin to set limits for users who self-manage their domains? There is no domain-limit in the UI after all. 
Or does this simply set the same limit for all mailboxes?

**Comment by ghostwheel42** [comment]
The `config-import` action is already documented quite lengthy here: https://mailu.io/master/cli.html#config-import

Slider: are you willing to make a PR adding a editable text-field to the slider?
Storage: The data displayed is the quota/used quota reported by dovecot. It does not include metadata.
setlimits: I didn't know this action either. It sets the values you can edit here: https://mailu.tld/admin/domain/edit/domain.tld

**Comment by elandorr** [comment]
Few people browsing the docs looking to change user quotas will think of this workaround, so the snippet is worth it I think. The 'update' flag makes it much less painful than you'd expect (no full ex/import necessary).

I wouldn't consider myself competent enough to mess with a public comms project, but I guess adding a text field should be fairly consequence-free and I can look at how you do it in the other settings. On the weekend maybe!
Seems this comes from: https://github.com/Mailu/Mailu/blob/4c5c6c3b5fd2d6165bdfa460d48a302be766fdc7/core/admin/mailu/ui/templates/user/create.html#L23
I don't know flask, but I can look into it a little. 

If dovecot doesn't report it I wonder how organizations handle this. You cannot say 1 user = 500MB then. The xepian thing is huge too. What does one calculate with, double? I have no idea how bloated it can get. 
On top of that mailu does not delete cleanly. If you remove a user there's always something left behind, but that was reported years ago. Since we aren't that big yet I just do it by hand.

The setlimits doesn't really explain what it does. It seems to be what the domain manager can allow, but it's not a limit for the whole domain. If we allow a user 1GB in total we'd have to limit him to 1 mailbox to ensure the 1GB, instead of letting him choose several boxes how he needs it.

Have a nice evening til then
