### ISSUE TITLE
relayhost conf issue after upgrade to 1.9

### ISSUE THREAD

**Issue by jericho63** [Mailu/Mailu#2245]
hello

I have update my mailu environnement from 1.8 to 1.9.
I'm hosted at home and i use the stmp of my isp for relay email.

since i have update, my relay smtp  conf has stop worked.

i have tried many test and it don't want work.

here my last conf
RELAYHOST=[[smtp.orange.fr]:587
[RELAYUSER=user@orange.fr
RELAYPASSWORD=password
OUTBOUND_TLS_LEVEL=may
DEFER_ON_TLS_ERROR=False

and smtp_tls_wrappermode = yes in postfix override.

and in the log i have this :
 warning: smtp_tls_wrappermode requires "smtp_tls_security_level = encrypt" (or stronger)

without override conf i have : 
warning: SASL authentication failure: No worthy mechs found

thank for your help, i'm really stuck

**Comment by nextgens** [comment]
try with the following instead:

```
RELAYHOST=[[smtp.orange.fr]:465
[RELAYUSER=user@orange.fr
RELAYPASSWORD=password
```
and smtp_tls_wrappermode = yes in postfix override.

You don't need any of the other options.

**Comment by nextgens** [comment]
Try adding ```OUTBOUND_TLS_LEVEL=encrypt```

**Comment by jericho63** [comment]
many thanks , that work at last!

Could you expain me why  it was need to change the port of the smtp host?
I have not undestand the difference between both

thank again

**Comment by nextgens** [comment]
port 465 is implicit TLS... whereas 587 is explicit

It looks like orange doesn't support explicit TLS (see below, there is no STARTTLS offered); odds are your email traffic was going unencrypted until you have upgraded and recent hardening in Mailu now prevents credentials from being sent in clear text.

```
$nc -C smtp.orange.fr 587
220 opmta1mto17nd1 smtp.orange.fr ESMTP server ready
EHLO example.com
250-opmta1mto17nd1 hello [92.94.109.159], pleased to meet you
250-HELP
250-AUTH LOGIN PLAIN
250-SIZE 46000000
250-ENHANCEDSTATUSCODES
250-8BITMIME
250 OK
QUIT
221 2.0.0 opmta1mto17nd1 smtp.orange.fr closing connection
```

**Comment by jericho63** [comment]
Thank for your explanation.
 So all is for the best.
 Thank you again for your help
