### ISSUE TITLE
nginx docker image tagged as stable is out of date

### ISSUE THREAD

**Issue by jdrowell** [Mailu/Mailu#225]
reference: https://hub.docker.com/r/mailu/nginx/tags/

All of the mailu/*:stable images are from 7 weeks ago, but the mailu/nginx:stable image is from 6 months ago. I had problems with certbot (pull request will follow) and the version of nginx.conf in that image doesn't even have the port 8081 redirect for ACME validation, although the maily/admin:stable image has certbot functionality (and even mentions that the port is hardcoded in the nginx image).
 
Installing all images tagged as 1.4 (setting that version in '.env') worked fine.

**Comment by curry684** [comment]
You're right, it would appear the build failed, see https://hub.docker.com/r/mailu/nginx/builds/bca23frv63fcbkwqknpfvwy/. Looking into it.

**Comment by curry684** [comment]
@kaiyou can you look into this?

The tagged builds all failed with:
```
Step 2/6 : RUN apk add --no-cache nginx-lua openssl

 ---> Running in f2b3c58f1673

fetch http://dl-cdn.alpinelinux.org/alpine/v3.5/main/x86_64/APKINDEX.tar.gz

fetch http://dl-cdn.alpinelinux.org/alpine/v3.5/community/x86_64/APKINDEX.tar.gz

ERROR: unsatisfiable constraints:

  nginx-lua (virtual):
    provided by: nginx-mod-http-lua
    required by: world[nginx-lua]

Removing intermediate container f2b3c58f1673

The command '/bin/sh -c apk add --no-cache nginx-lua openssl' returned a non-zero code: 1
```
You did apparently fix it later on as `latest` is building fine since then, but `stable` and `1.4` were left broken. Need your powers to fix that I'm afraid  😉

**Comment by kaiyou** [comment]
Oh, yes it seems that 4e212e3d fixed this but was never merged in master.

**Comment by kaiyou** [comment]
I just cherry picked the commit, will wait for the build to complete.
