### ISSUE TITLE
sieve rules does not run correctly if 'Move message to' a folder with Chinese characters

### ISSUE THREAD

**Issue by qiongzhu** [Mailu/Mailu#2258]
Thank you for opening an issue with Mailu. Please understand that issues are meant for bugs and enhancement-requests.
For **user-support questions**, reach out to us  on [matrix](https://matrix.to/#/#mailu:tedomum.net).

To be able to help you best, we need some more information.

## Before you open your issue
- [x] Check if no issue or pull-request for this already exists.
- [x] Check [documentation](https://mailu.io/master/) and [FAQ](https://mailu.io/master/faq.html). (Tip, use the search function on the documentation page)
- [x] You understand `Mailu` is made by volunteers in their **free time** — be conscise, civil and accept that delays can occur.
- [x] The title of the issue should be short and simple. It should contain specific terms related to the actual issue. Be specific while writing the title.

### Environment
 - [x] docker-compose
 - [ ] kubernetes
 - [ ] docker swarm

### Versions
1.9

## Description
Messages could not be moved to a folder with Chinese character name. Please check following Replication Steps as below.

## Replication Steps
1. login into roundcube webmail
2. goto `Settings` --> `Folders` --> `Create`, and create 2 folders with name `Test` & `测试`
3. open a shell & goto the maildir for this user, check the folder exists as follows:
```
[root@imail someone@home.lan]# ls -ld './.&bUuL1Q-' './.Test'
drwx------ 5 mail mail 4096 Feb 25 20:42 './.&bUuL1Q-'
drwx------ 5 mail mail 4096 Feb 25 21:02  ./.Test
```
4. goto `Settings` --> `Filters` --> `Create`, and create 2 rules to move incoming message to above 2 folders. the file `sieve/roundcube.sieve` found in the user maildir may be something like:
```
# rule:[send to self1]
if allof (header :contains "subject" "self1", header :contains "from" "someone@home.lan", header :contains "to" "someone@home.lan")
{
        fileinto "Test";
        stop;
}
# rule:[send to self2]
if allof (header :contains "subject" "self2", header :contains "from" "someone@home.lan", header :contains "to" "someone@home.lan")
{
        fileinto "&bUuL1Q-";
        stop;
}
```
5. for above rule, send 2 emails to self, with key words `self1` & `self2` as subject field for each mail message
6. check the result, the mail `self1` will be sorted to folder `Test`, but the other `self2` will be kept in Inbox, with `.dovecot.sieve.log` complains as follows:
```
sieve: info: started log at Feb 25 21:01:31.
error: msgid=<f81bf9c5baa1ce5c3b4b701f93605eb0@home.lan>: fileinto action: failed to store into mailbox '&bUuL1Q-': Mailbox doesn't exist: &bUuL1Q-.
```

## Expected behaviour
Sieve rules run correctly for any valid folder name, sort messages to corresponding folders.

## Logs
Please check above `Replication Steps`

**Comment by nazar-pc** [comment]
I have an identical issue, but with cyrillic characters

**Comment by nazar-pc** [comment]
The issue is not Roundcube (at lest I think so), it is Dovecot configuration.
When following override is used to force it to store directories on disk in UTF-8, everything suddenly "Just works":
```
mail_location = maildir:/mail/%u:UTF-8
```


Maybe consider defaulting new installations to UTF-8? I think for existing users it will be a breaking change because directories will need to be renamed back into normal format (as far as mail client is concerned).

**Comment by nazar-pc** [comment]
Above solution is partial (optional?).

The actual solution is to edit `/var/www/html/plugins/managesieve/lib/Roundcube/rcube_sieve_engine.php` file and replace this line:
```php
        $mbox_encoding     = $this->rc->config->get('managesieve_mbox_encoding', 'UTF7-IMAP');
```
With this:
```php
        $mbox_encoding     = $this->rc->config->get('managesieve_mbox_encoding', 'UTF8');
```

I do not understand why, but neither override nor editing `/config.inc.php` had no effect on `managesieve` plugin, not sure why.

I think if those two patches are included into Mailu it'll start working for people out of the box. I can send a PR if you'd like.

**Comment by ghostwheel42** [comment]
> I do not understand why, but neither override nor editing `/config.inc.php` had no effect on `managesieve` plugin, not sure why.

Did you restart the webmail container after creating the overrid file?
Di you use `<?php ... ?>` and named the file ending in `.inc`?

I've created `overrides/roundcube/sieve-utf8.inc` and it seems to work.

**Comment by nazar-pc** [comment]
Yes, I created file `overrides/roundcube/managesieve.inc.php` with following contents:
```php
<?php
$config['managesieve_mbox_encoding'] = 'UTF8';
```

I did restart container, though it is unnecessary due to the fact that it is PHP and will reload things on every page load.

Documentation says `*.inc.php` files should be created, not `*.inc`.

**Comment by nazar-pc** [comment]
Tried `overrides/roundcube/sieve.inc`, doesn't work either (doesn't have any effect). As I said, I even tried to edit main config in the container, it doesn't apply for whatever inexplicable reason, might be the root cause (though other options apply, right? Doesn't make any sense to me).

**Comment by nazar-pc** [comment]
To reproduce try to create email folder called `Пошта` and get Roundcube GUI to store it intact in `.sieve` file.

**Comment by ghostwheel42** [comment]
> I did restart container, though it is unnecessary due to the fact that it is PHP and will reload things on every page load.

The configuration is currently generated by a python script - so you need the restart to add new includes.
But we probably could change this and put the logic inside the config.php

> Documentation says `*.inc.php` files should be created, not `*.inc`.

Yes, both extensions are okay.

**Comment by nazar-pc** [comment]
`*.inc.php` file didn't work for me, but `*.inc` file finally did.

**Comment by ghostwheel42** [comment]
@Diman0 no, I just tested the include logic.
But as far as I remember roundcube plugins have their respective configuration in their plugin folders and not in the main config. So you would need to create `/var/www/roundcube/plugins/managesieve/config.inc.php`

see: https://docs.kolab.org/administrator-guide/roundcube-settings-reference.html#roundcube-settings-reference-guide

**Comment by ghostwheel42** [comment]
> `*.inc.php` file didn't work for me, but `*.inc` file finally did (after restart)

Ah, good. Then there seems to be a bug when including the overrides.
And my last message is not correct, too, as apparently the main `config.inc` can also be used.

**Comment by nazar-pc** [comment]
I see no reason why it wouldn't work in default config, other managesieve settings are already there.
Two overrides is not that bad for a workaround, but at least now it should be clear how to resolve this.
Thanks for all the hints!
