### ISSUE TITLE
Question:  Is login possible via port 25

### ISSUE THREAD

**Issue by lknite** [Mailu/Mailu#2261]
If only port 25 is open to the world, is it possible for a brute force password attack to occur?

I'm seeing messages but someone told me the errors can't be trusted, that there is no actual way to log in via port 25.  But if this were true why would the error message indicate different?

```
2022/03/02 06:04:22 [info] 13#13: *89499 client 31.210.20.189:60509 connected to 0.0.0.0:25
2022/03/02 06:04:22 [error] 13#13: *89499 31.210.20.189 could not be resolved (3: Host not found) while in resolving client address, client: 31.210.20.189, server: 0.0.0.0:25
127.0.0.1 - - [02/Mar/2022:06:04:23 +0000] "GET /auth/email HTTP/1.0" 200 0 "-" "-"
2022/03/02 06:04:23 [info] 13#13: *89499 client login failed: "Authentication credentials invalid" while in http auth state, client: 31.210.20.189, server: 0.0.0.0:25, login: "database"
```

**Comment by madstk1** [comment]
I'm experiencing similar logs. However, there's no new messages in the admin container since startup. None of the other containers show anything relavant, either.

**Comment by nextgens** [comment]
I will need a packet capture and the exact version of what you are running (``cat /version``) to debug this... You can generate one using ``tcpdump -w /tmp/25.pcap -n -s 0 tcp port 25``

From what I can see:
1) no AUTH method is advertised on port 25 (so no RFC compliant client should attempt to AUTH)
2) we reject any "valid" attempt
Of course there are a zillion of corner cases (like if the attacker does STARTTLS) so that's why a packet capture would help.

PLAIN using a valid credentials:
```
$nc -C test.mailu.io 25
220 test.mailu.io ESMTP ready
EHLO client.example.com
250-test.mailu.io
250-PIPELINING
250-SIZE
250-2000000
250-ETRN
250-ENHANCEDSTATUSCODES
250-8BITMIME
250-DSN
250 STARTTLS
AUTH PLAIN
334 
AGFkbWluQHRlc3QubWFpbHUuaW8AbGV0bWVpbg==
502 5.5.1 AUTH not supported
QUIT

$nc -C test.mailu.io 25
220 test.mailu.io ESMTP ready
EHLO client.example.com
250-test.mailu.io
250-PIPELINING
250-SIZE
250-2000000
250-ETRN
250-ENHANCEDSTATUSCODES
250-8BITMIME
250-DSN
250 STARTTLS
AUTH PLAIN AGFkbWluQHRlc3QubWFpbHUuaW8AbGV0bWVpbg==
502 5.5.1 AUTH not supported
QUIT
```

LOGIN using valid credentials:
```
$nc -C test.mailu.io 25
220 test.mailu.io ESMTP ready
EHLO client.example.com
250-test.mailu.io
250-PIPELINING
250-SIZE
250-2000000
250-ETRN
250-ENHANCEDSTATUSCODES
250-8BITMIME
250-DSN
250 STARTTLS
AUTH LOGIN
334 VXNlcm5hbWU6
YWRtaW5AdGVzdC5tYWlsdS5pbwo=
334 UGFzc3dvcmQ6
bGV0bWVpbgo=
502 5.5.1 AUTH not supported
QUIT
```

**Comment by nextgens** [comment]
Looking further into my logs, I have also experienced cases with "Authentication credentials invalid" instead of "AUTH not supported".

The admin logs are explicit about why though: 
```WARNING in nginx: Invalid user 'xxx': (builtins.ValueError) invalid email address (no "@")```

if you don't see these messages it may be something else.
