### ISSUE TITLE
Mail are not replicating/coming after AWS to Azure Migration in Thunderbird email client

### ISSUE THREAD

**Issue by xcubated** [Mailu/Mailu#2264]
Thank you for opening an issue with Mailu. Please understand that issues are meant for bugs and enhancement-requests.
For **user-support questions**, reach out to us  on [matrix](https://matrix.to/#/#mailu:tedomum.net).

To be able to help you best, we need some more information.

## Before you open your issue
- [ ] Check if no issue or pull-request for this already exists.
- [ ] Check [documentation](https://mailu.io/master/) and [FAQ](https://mailu.io/master/faq.html). (Tip, use the search function on the documentation page)
- [ ] You understand `Mailu` is made by volunteers in their **free time** — be conscise, civil and accept that delays can occur.
- [ ] The title of the issue should be short and simple. It should contain specific terms related to the actual issue. Be specific while writing the title.

### Environment
 - [ ] docker-compose
 - [ ] kubernetes
 - [ ] docker swarm

### Versions
To find your version, get the image name of a mailu container and read  the version from the tag (example for version 1.7).
```
$> docker ps -a | grep mailu
140b09d4b09c    mailu/roundcube:1.7    "docker-php-entrypoi…"    2 weeks ago    Up 2 days (healthy)    80/tcp
$> grep MAILU_VERSION docker-compose.yml mailu.env
```

## Description
Further explain the bug in a few words. It should be clear what the unexpected behaviour is.  Share it in an easy-to-understand language.

## Replication Steps
Steps for replicating your issue

## Expected behaviour
Explain what results you expected - be as specific as possible. Just saying "it doesn’t work as expected" is not useful. It's also helpful to describe what you actually experienced.

## Logs
Often it is very useful to include log fragments of the involved component. You can get the logs via `docker logs <container name> --tail 1000`. For example for the admin container:
`docker logs mailu_admin_1 --tail 1000`
or using docker-compose `docker-compose -f /mailu/docker-compose.yml logs --tail 1000 admin`
If you can find the relevant section, please share only the parts that seem relevant. If you have any logs, please enclose them in code tags, like so:
````markdown
```
Your logs here!
```
````

**Comment by xcubated** [comment]
Hello Team,

Good day !

As requested, please find the details for our issue.

We've currently our mails (I.e, xcubated.in) hosted in AWS cloud platform using "Maillu" with 20-35 mailboxes and we're currently using "Thunderbird" mail client for mailboxes.
Now we're planning to move this mail server from AWS to Azure Cloud Platform on urgent basis.
After the migration from AWS to Azure, new mails are not replicating to "Thunderbird" mail client and we had already troubleshoot (including the SMTP Port opened in Inbound and Outbound security groups, etc., ) with Azure support team also and they had informed us, it is your internal "mailu" server issue. Hence we're requested to help this issue.

Do we need any configuration settings in "Mailu" or any changes in Azure ?

Kindly help and support

Kind regards
Sunish,
IT Infra
Xcubated Business Solutions Pvt. Ltd.
www.xcubated.com

**Comment by xcubated** [comment]
Hello Team,

Awaiting your support

**Comment by ghostwheel42** [comment]
Hi, by "are not replicated" do you mean "you can't fetch emails"?
Which Ports did you open for ouside access?

Btw: you did not fill out the issue template: https://github.com/Mailu/Mailu/blob/master/ISSUE_TEMPLATE.md

Please understand that issues are meant for bugs and enhancement-requests.
For **user-support questions**, reach out to us  on [matrix](https://matrix.to/#/#mailu:tedomum.net).

**Comment by xcubated** [comment]
Hello Team,

As i mentioned, after the migration, new mails are not replicating (can't fetch new emails)  to Thunderbird mail client.
Hope you have understand the issue now.

Please help.

Regards
Sunish.

**Comment by xcubated** [comment]
Hello Team,

Adding - 
Which Ports did you open for ouside access? = We've opened SMTP 22 for both inbound and outbound

Regards
Sunish.

**Comment by ghostwheel42** [comment]
Hi Sunish,

port 22 if for ssh, not smtp. You need to open the ports listed in the documentation:
https://mailu.io/1.9/compose/requirements.html?highlight=143#install-the-distribution

When using IMAP only theese will be: 25, 80, 143, 443, 465, 587, 993
