### ISSUE TITLE
How long is the rspamd history, can you change it, and can you clear it?

### ISSUE THREAD

**Issue by elandorr** [Mailu/Mailu#2266]
See title, any version

**Comment by Diman0** [comment]
We haven't configured anything, but the redis location. See
https://github.com/Mailu/Mailu/blob/master/core/rspamd/conf/history_redis.conf

[The rspamd documentation](https://rspamd.com/doc/modules/history_redis.html) shows that you can only configure a row limit. 
The default is 200 rows. That should be the value used by Mailu. To use a different values you can add a custom config file to the overrides folder.

**Comment by elandorr** [comment]
Thank you Diman. So:
- 200 rows default for detailed info.
- Statistics show at most for one year in the graph, yet it's unclear how long it's actually stored. (I assume forever.)

The history file in the `filter` directory is empty. yet there are plenty of cache files.

Thanks to https://mailu.io/1.9/antispam.html I found `rspamc` is available in the dovecot container, but there's not much info in the upstream docs. Closest I found is https://rspamd.com/doc/workers/controller.html but no idea where one would use e.g. `/graph`.

`rspamc --commands` shows `stat_reset` which seems like it'd do the trick (Haven't tried yet, might backup first.).
`rspamc -h antispam:11334 -P mailu stat` works.

Can you simply stop mailu, delete the filter folder, and restart? I suppose since you called it 'filter' this would delete all training too?

Here (https://github.com/rspamd/rspamd/issues/3203) someone suggests connecting to redis manually and flushing all. Can this be recommended for a clean reset?

I'm trying to learn how to keep storage under control long-term, since there don't seem to be any limits anywhere. With users scaling up we need to know where and how data is stored after all.
