### ISSUE TITLE
even with full text search disabled in the .env, xapian indexes are generated

### ISSUE THREAD

**Issue by elandorr** [Mailu/Mailu#2268]
v1.9

Leading to quite substantial waste of storage. I suspect these indexes aren't used for anything other than FTS?

**Comment by Diman0** [comment]
What setting did you enter in mailu.env?
It must be set to off, false or 0.

Can you see any references to fts in /etc/dovecot/dovecot.conf?

**Comment by elandorr** [comment]
> What setting did you enter in mailu.env?

I could've sworn this was always opt-in, not opt-out. Turns out it's the opposite.. Set it to off now, thank you.

Will mailu eventually delete the now unused data, or should I manually remove all xapian folders?

**Comment by Diman0** [comment]
You should manually remove the folders/files. The only thing it does is add/remove the relevant settings to the dovecot config.

**Comment by elandorr** [comment]
I checked the fts-xapian docs to no avail. It only generates the `xapian-indexes` folder, correct?
`find . -type d -name 'xapian-indexes' -exec rm -rf {} \;` So that should cover disabling FTS.
PSA `doveadm index -A '*'` did nothing.

Do you know if dovecot has a timeout for searches? Without xapian I'd like there to be a clear limit, so users with big inboxes can't inadvertently DoS the server.

Thanks for helping!
