### ISSUE TITLE
How to add custom language?

### ISSUE THREAD

**Issue by AliKhadivi** [Mailu/Mailu#2270]
Hi
How to add custom language?
I want to add Persian language

**Comment by Diman0** [comment]
You would first create the message.pot file using pybabel. See https://mailu.io/1.9/contributors/memo.html#update-translations for instructions for creating the language file.
After that you can update the translation file. One of the best tools for this is poedit (https://poedit.net/).
When you are happy you can create a pull request from your forked repository for submitting your work.

**Comment by AliKhadivi** [comment]
Thanks
