### ISSUE TITLE
editing POSTMASTER post install is not effective

### ISSUE THREAD

**Issue by elandorr** [Mailu/Mailu#2273]
v1.9
Wanted to set it to a more standard conform 'postmaster', changed the .env, docker-compose down, up.
It didn't change it in the domain DNS record view. (I suppose it's only relevant for the DMARC?)

**Comment by ghostwheel42** [comment]
POSTMASTER= is used for administrative emails (bounces, cron mails, ...)
To change the displayed DMARC records you need to set DMARC_RUA= and DMARC_RUF=

**Comment by ghostwheel42** [comment]
You are correct: postmaster is for humans.
As you grepped it is used as sender when sending emails via the web-if, as address for the automatic lets encrypt and as sender for bounces when sent by dovecot. So maybe the last one could/should be MAILER-DAEMON@...
As for the Labels: I don't know, but the issue template states "ask questions on matrix", so it isn't really necessary for the user to pre-label an issue.

**Comment by elandorr** [comment]
> So maybe the last one could/should be MAILER-DAEMON@

Mailu does use MAILER-DAEMON - that's why I'm surprised. The dovecot docs directly say bounces use postmaster, yet even with the seemingly innocuous config mail uses, it's MAILER-DAEMON. I guess the dovecot docs are wrong then. I'll close the issue since the original title doesn't match anymore, and when one of us has too much free time we can bug dovecot about it :) too minimal to bother maybe.

> "ask questions on matrix",

Personally, I'm not signing up with the 9000th cloudflare-telemetry-lets-spread-your-data-on-every-server (genius solution) thing just to ask a question. IRC works fine for a quick chat and typically is login-free and log-free. Anyway this was meant as a bug report and turned out to be a misunderstanding of variables.
