### ISSUE TITLE
Certbot certs generation with SANs?

### ISSUE THREAD

**Issue by dosimeter** [Mailu/Mailu#228]
I have a mail server with multiple CNAMEs.
How to specify they properly in a config (".env"?) file to allow cert generation with SANs?

**Comment by kaiyou** [comment]
Currently, this is not supported at all. Mailu is supposed to be accessed through a single domain. Maybe we could include a list of CNAMEs that would populate the certbot command though.

**Comment by kaiyou** [comment]
See #250 for long term plans regarding Certbot.

**Comment by kaiyou** [comment]
This could allow for multiple domains as well, so I will keep this issue open and mark it for `1.5` as well.

**Comment by kaiyou** [comment]
This will be related to #272 and could actually be implemented then if we succeed.

**Comment by kaiyou** [comment]
This is now supported in the `refactor-nginx` branch and works nicely for the Web interface.

**Comment by kaiyou** [comment]
This is now supported in `master` !
