### ISSUE TITLE
Stable image seems to be broken

### ISSUE THREAD

**Issue by Thrakath** [Mailu/Mailu#229]
Hi,
The stable image seems to be broken. Change to latest will fix the issues.

1) Building no https image leads to error: 

_Pulling http (mailu/nginx-no-https:stable)...
ERROR: manifest for mailu/nginx-no-https:stable not found_

2) Webinterfaces not reachable -> proxy seems not to work correctly

_192.168.2.51 - - [10/Aug/2017:19:17:53 +0000] "GET /webmail HTTP/1.1" 404 162 "-" "Mozilla/5.0 (Wind                                                                           ows NT 6.1; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0"
2017/08/10 19:17:53 [error] 8#8: *2 open() "/var/lib/nginx/html/webmail" failed (2: No such file or                                                                            directory), client: 192.168.2.51, server: , request: "GET /webmail HTTP/1.1", host: "jeremie.fritz.b                                                                           ox"_
 
best regards

Thrakath

**Comment by kaiyou** [comment]
That was a misconfiguration of the builder, thank you for reporting!
