### ISSUE TITLE
I can't connect with POP3 server

### ISSUE THREAD

**Issue by adnankhanakib** [Mailu/Mailu#2292]
I have tested SMTP working fine but can't connect with POP3
https://www.wormly.com/test-pop3-mail-server/host/mail.chirkutt.xyz/ssl/0/port/110/id/dCCXQI0u

**Comment by nextgens** [comment]
The server announces ``STLS`` ... you can't authenticate over an insecure link if SSL is enabled

**Comment by nextgens** [comment]
Use an SSL-enabled client, connect to port 995 instead.

```openssl s_client -connect mail.chirkutt.xyz:995```

**Comment by adnankhanakib** [comment]
But I can't test it online also can't connect through php

> AuthenticationFailedException: invalid command

**Comment by nextgens** [comment]
> But I can't test it online also can't connect through php
> 
> `$mail = imap_open('{mail.chirkutt.xyz:110/pop3}', 'chirkuttadmin@chirkutt.xyz', 'mypassword');`
> 
> Error ->
> 
> > TLS/SSL failure for mail.chirkutt.xyz: SSL not supported on this machine - upgrade your system software

Try with:
 `$mail = imap_open('{mail.chirkutt.xyz:110/pop3/tls}', 'chirkuttadmin@chirkutt.xyz', 'mypassword');`
or better:
 `$mail = imap_open('{mail.chirkutt.xyz:995/pop3/ssl}', 'chirkuttadmin@chirkutt.xyz', 'mypassword');`
instead

**Comment by nextgens** [comment]
Hmm, reading your error message: you need a version of PHP that can do SSL to connect to an SSL-enabled deployment of Mailu.

Install/enable the openssl module for instance:
https://www.php.net/manual/en/openssl.installation.php

**Comment by nextgens** [comment]
Using the same website, you can see that it works as expected when you enable SSL:
https://www.wormly.com/test-pop3-mail-server/host/mail.chirkutt.xyz/ssl/1/id/SnUMF9Wt
