### ISSUE TITLE
webmail login 302 FOUND

### ISSUE THREAD

**Issue by xuhuanzy** [Mailu/Mailu#2298]
Thank you for opening an issue with Mailu. Please understand that issues are meant for bugs and enhancement-requests.
For **user-support questions**, reach out to us  on [matrix](https://matrix.to/#/#mailu:tedomum.net).

To be able to help you best, we need some more information.

## Before you open your issue
- [ ] Check if no issue or pull-request for this already exists.
- [ ] Check [documentation](https://mailu.io/master/) and [FAQ](https://mailu.io/master/faq.html). (Tip, use the search function on the documentation page)
- [ ] You understand `Mailu` is made by volunteers in their **free time** — be conscise, civil and accept that delays can occur.
- [ ] The title of the issue should be short and simple. It should contain specific terms related to the actual issue. Be specific while writing the title.

### Environment
 - [ ] docker-compose
 - [ ] kubernetes
 - [ ] docker swarm

### Versions
1.9

## Description
webmail login is redirected, unable to enter webmail and admin interface.
Entering the wrong password will prompt that the password is incorrect, but entering the correct password will refresh the page.
Changing the language option is also invalid, still return to the original page

## Expected behaviour
Explain what results you expected - be as specific as possible. Just saying "it doesn’t work as expected" is not useful. It's also helpful to describe what you actually experienced.

## Logs
I set the log level to debug, then checked the logs of all containers, and found no errors,

**Comment by daald** [comment]
Same here. cannot login to webmail but imap with thunderbird works. I upgraded from mailu 1.7

**Comment by daald** [comment]
I think this is a bug

**Comment by anon767** [comment]
Facing the same issue here

**Comment by qndydyhm** [comment]
same here

**Comment by daald** [comment]
I just tested this again. Still 1.9.
I discovered that my bookmarked links were http links and if I changed to https the login worked without problems. So the core problem seem to be that that http doesn't work properly OR that http should redirect to htttps but doesn't.
