### ISSUE TITLE
Alternative to Certbot

### ISSUE THREAD

**Issue by SaiGonSeamus** [Mailu/Mailu#230]
We are stopping using Let's encrypt in all of our servers. It has proved to unreliable to run in production. 

Is anyone running mailu with other cert authorities and if so, who do they recommend?

What is the process for installation?

**Comment by kaiyou** [comment]
See #250 for long term plans regarding Certbot.

**Comment by kaiyou** [comment]
A first implementation is available in the branch `feature-traefik`, I am inviting you to comment on #250 and am closing this as a somehow duplicate.
