### ISSUE TITLE
Mailu container won't start due to problem with getting ssl 

### ISSUE THREAD

**Issue by kaaaq** [Mailu/Mailu#2301]
Hi,
I've upgraded Mailu from 1.8 to  VERSION=1.9 but there is a problem with TLS (please read [this issue](https://github.com/Mailu/Mailu/issues/2169) first)
I have the certificate on my server but due to the mentioned-above problem, letsencrypt has been blocked my domain name
now when the mailu container wants to come up it faces with domain-blocked error and all configs will write incorrect due to following jinja template that placed in "conf/nginx.conf":
 ```
      {% if KUBERNETES_INGRESS != 'true' and **TLS_ERROR** and not (TLS_FLAVOR in [ 'mail-letsencrypt', 'mail' ]) %}
      {% if TLS_FLAVOR in ['letsencrypt','mail-letsencrypt'] %}
      ssl_certificate /certs/letsencrypt/live/mailu/fullchain.pem;
      ssl_certificate /certs/letsencrypt/live/mailu-ecdsa/fullchain.pem;
```
So correct config wouldn't write in "/etc/nginx/nginx.conf"
even changing the name of fullchain.pem to nginx-chain.pem worked for me 
I think at first when the container wants to run, should check the path for the existence of the certificate after that tries to get a new one

### Environment
 - [x] docker-compose
 - [ ] kubernetes
 - [ ] docker swarm

### Versions
VERSION=1.9

# Mailu Config:
TLS_FLAVOR=letsencrypt
VERSION=1.9

## Expected behavior
When the container wants to run, at first it should check the path for the existence of the certificate, if there isn't any cert it should try to get a new one

**Comment by nextgens** [comment]
I suspect that something is terribly off in your letsencrypt configuration files and suggest you attempt the following:

```
docker-compose down
mv certs/letsencrypt certs/letsencrypt.bak
docker-compose up -d
```

Provided that you are not blocked by letsencrypt at the point you attempt it, it should work.

**Comment by Alexylva** [comment]
Had the same problem, solved by opening port 8008

**Comment by nextgens** [comment]
It does but over the loopback interface (on the same container); you shouldn't need to expose the port

**Comment by nextgens** [comment]
@kaaaq can you test and report back please?

**Comment by kaaaq** [comment]
> @kaaaq can you test and report back please?

Sorry for being late in response @nextgens,
Unfortunately, I couldn't test cause my domain is blocked already,
But I read the flow of making the config file from the Jinja template, I think it will fix if you add what I said above.
