### ISSUE TITLE
SMTP queue is full with spam emails

### ISSUE THREAD

**Issue by wajdijurry** [Mailu/Mailu#2304]
I observed the SMTP queue and found a lot of spam emails sent on behalf of my domain.

![wireshark-packets](https://user-images.githubusercontent.com/25797257/161105880-861049a8-e5c6-4822-aff3-3db0a8e96b7e.png)

All these addressed are not registered in my local mail server.

I am using ports (25, 465, 587) for SMTP, (110, 993) for IMAP, (143, 995) for POP3. 

I am also signing each outgoing email with DKIM using a private key, with a valid SSL certificate for the mail domain.

Why the SMTP queue is filled with spam mails and how to prevent this?

**Comment by nextgens** [comment]
Can you share extracts of the logs of the front and smtp containers please?

**Comment by wajdijurry** [comment]
Unfortunately, I don't have. I switched containers down after being spoofed and no logs for now. 

What I want is to prevent sending mail from un-registered accounts, that is, only registered / authenticated accounts can send mails.

How to do that?

**Comment by nextgens** [comment]
That's the default configuration except for localhost... unless you have configured RELAYNETS

Are you sure that no account has been compromised? Unfortunately it's not something we can help with if there are no logs.

**Comment by wajdijurry** [comment]
I am sure that no accounts have been compromised. All mails are sent from randomly generated email accounts.

Regarding relaynets, I defined those records in webmail admin:

![image](https://user-images.githubusercontent.com/25797257/161244943-12e5ddb6-96ca-4ddf-a109-da7cb774fdd1.png)


Is there something should be changed here?

**Comment by nextgens** [comment]
RELAYNETS is defined in mailu.env (see https://mailu.io/1.9/configuration.html#mail-settings)

The settings configured in the screenshot you have provided do not make sense to me... and don't unless you send emails to @worldwide or @worldwide1 ; Do you?

**Comment by wajdijurry** [comment]
> RELAYNETS is defined in mailu.env (see https://mailu.io/1.9/configuration.html#mail-settings)
> 
> The settings configured in the screenshot you have provided do not make sense to me... and don't unless you send emails to @Worldwide or @worldwide1 ; Do you?

`RELAYNETS` is not set in my case. 

The purpose of the mail server is to send & receive mails to and from other mail providers, like Gmail, Yahoo, ...etc.

**Comment by nextgens** [comment]
Please reopen the issue and provide logs if you experience this again.

**Comment by wajdijurry** [comment]
> Please reopen the issue and provide logs if you experience this again.

Sure! Thank you @nextgens .
