### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by skironDotNet** [Mailu/Mailu#2306]
Sorry, didn't know where to ask.
Is there a way to hookup to incoming mail to fire an event, some trigger? This is not specific to mailu, just smtp in general, but since you are experts... I would like to send myself a notification when the email comes in. Is there any way to capture that and invoke anything, bash script or make HTTP request?

Thank you

**Comment by ghostwheel42** [comment]
You can do this via SIEVE or using a SERVICE in portfix for example.

Sieve: https://doc.dovecot.org/configuration_manual/sieve/plugins/extprograms/ 

Via Postfix I think you can do it like this:
1. add "service" to master.cf:
  `SERVICE   unix  -       n       n       -       -       pipe  flags=Fq    user=<USERNAME>    argv=</path/to/script>`
2. add mapping and catch-all to transport-map:
  `<localpart@domain.tld> SERVICE:`

**Comment by skironDotNet** [comment]
Thank you @ghostwheel42 I'll look into it
