### ISSUE TITLE
Slow imap login

### ISSUE THREAD

**Issue by trnila** [Mailu/Mailu#231]
I'm having issue with slower roundcube because of slow imap authentization.
Roundcube requests takes up from 600 ms to 2 seconds.
The issue is reproducible on clean installation with STABLE/LATEST version on multiple systems.

From inside imap container:
```
$ time doveadm auth test root@example.net password
passdb: root@example.net auth succeeded                                                                                                                       
extra fields:                                                                                                                                                 
  user=root@example.net
real    0m0.543s                                                                                                                                              
user    0m0.011s                                                                                                                                              
sys     0m0.000s
```

When enabled dovecot verbose output, there is delay between these two log messages:
```
auth-worker(50): Debug: sql(root@example.net): query: SELECT password FROM user WHERE user.email = 'root@example.net'
auth: Debug: client passdb out: OK       1       user=root@example.net
```
When I manually run this sql command in sqlite from inside that container, it is executed without delay.
When I straced all processes, there seems to be no syscall invoked in that delay.
I am not able to figure out, where the delay comes from. Do you have any suggestion?

**Comment by kaiyou** [comment]
I do not encounter the same problem though. Could you strace when running the `doveadm auth` and see if a blocking syscall is taking all your time?

**Comment by trnila** [comment]
The slowness is caused by SHA512-CRYPT, can we make it configurable with https://github.com/Mailu/Mailu/pull/246 ?

**Comment by kaiyou** [comment]
Making it configurable with a sane default is perfectly fine, but the slowness remains weird. On what kind of hardware are you running it?

**Comment by kaiyou** [comment]
Ok, that makes sense. Let me know if the pull request we merged helps significantly.

**Comment by trnila** [comment]
Yes it helped significantly, thank you.

We could make additional algorithm options (like default number of rounds) configurable via `CryptContext.from_path()` with mounted file to container instead of adding additional environment variables.
Are you interested if I prepare a pull request for this feature?

**Comment by kaiyou** [comment]
Offering a couple options is already fine IMO. Especially when it comes to crypto, to many options can only lead to so many mistakes. That's the main reason why cipher lists are not configurable at the moment, so I would prefer we limit options for password encyption just as well.
