### ISSUE TITLE
Auth Ratelimit not working with login error "AUTH not supported"

### ISSUE THREAD

**Issue by benvei** [Mailu/Mailu#2311]
Hi!

Got mailu 1.9.25 running with docker-compose and it's working great.
My instance is facing some brute force traffic which is unsuccessful and the login fails with error "AUTH not supported" (see log below).
The brute force tries about 3 times / minute from the same IP Address.
My AUTH_RATELIMIT_IP is set to 60/hour, we are well above 60/hour but mailu is not blocking the IP Adress.

I double checked my configuration and monitored this for a few month now, seems to be a Bug or am I missing something here?
Sadly the latest fix regarding Ratelimit for IMAP/POP/SMTP doesn't change anything here.

Thanks!

````
2022/04/05 15:46:01 [info] 81#81: *73 client login failed: "AUTH not supported" while in http auth state, client: 5.34.205.67, server: 0.0.0.0:25, login: "sday"
2022/04/05 15:46:02 [info] 81#81: *80 client 5.34.205.67:35276 connected to 0.0.0.0:25
2022/04/05 15:46:02 [error] 81#81: *80 5.34.205.67 could not be resolved (3: Host not found) while in resolving client address, client: 5.34.205.67, server: 0.0.0.0:25
2022/04/05 15:46:18 [info] 81#81: *80 client login failed: "AUTH not supported" while in http auth state, client: 5.34.205.67, server: 0.0.0.0:25, login: "iweb"
2022/04/05 15:46:22 [info] 81#81: *85 client 5.34.205.67:1622 connected to 0.0.0.0:25
2022/04/05 15:46:22 [error] 81#81: *85 5.34.205.67 could not be resolved (3: Host not found) while in resolving client address, client: 5.34.205.67, server: 0.0.0.0:25
2022/04/05 15:46:43 [info] 81#81: *86 client 5.34.205.67:32368 connected to 0.0.0.0:25
2022/04/05 15:46:43 [error] 81#81: *86 5.34.205.67 could not be resolved (3: Host not found) while in resolving client address, client: 5.34.205.67, server: 0.0.0.0:25
2022/04/05 15:46:44 [info] 81#81: *85 client login failed: "AUTH not supported" while in http auth state, client: 5.34.205.67, server: 0.0.0.0:25, login: "minute"
````

**Comment by nextgens** [comment]
I am not sure what you are expecting Mailu to do here...

- AUTH is not advertised on port 25: no legitimate client should ever attempt to use it
- the message is clear: Authentication will **never** succeed on that port
- rate limiting is triggered: IPs that ignore the hint will not be able to authenticate (even on other ports!) if they hit the limit; See https://github.com/Mailu/Mailu/blob/ecf929969a3da3723fca34ac3d5aff4c73ab04c1/core/admin/mailu/internal/views/auth.py#L20

**Comment by benvei** [comment]
I would expect Mailu to drop traffic comming from this IP as soon as it hits the ratelimit of 60/hour.
In my case the brute force is "only" doing 3 tries / minute, so only 180/hour which is not that much. But what happens if the number increases?
It looks like mailu is also trying to resolve the IP every time it tries. This puts unnecessary load on the system, especially when we are talking about a higher number of tries.
Also it make the logs quite messy. So tl;dr: I would expect the rate limiting just dropping this IP and not doing anything with this IP as soon as it has been ratelimited.

**Comment by nextgens** [comment]
> I would expect Mailu to drop traffic comming from this IP as soon as it hits the ratelimit of 60/hour.

Dropping traffic isn't spec-compliant... it's port 25 we are talking about here: dropping traffic may have side effects that result in loosing emails

> In my case the brute force is "only" doing 3 tries / minute, so only 180/hour which is not that much. But what happens if the number increases?

The same thing: Mailu politely answers that it won't do authentication on port 25... and will reject any attempt to authenticate from that IP/subnet for as long as the host remains rate-limited.

> It looks like mailu is also trying to resolve the IP every time it tries. This puts unnecessary load on the system, especially when we are talking about a higher number of tries.

DNS records are usually cached; this shouldn't cause any trouble

> Also it make the logs quite messy. So tl;dr: I would expect the rate limiting just dropping this IP and not doing anything with this IP as soon as it has been ratelimited.

I think that there is a misunderstanding of what the feature is: it's an **authentication** rate-limit that has been implemented... if you are after something else we could talk about it, but as a new feature.

**Comment by benvei** [comment]
Thanks for the clarification.
Seems like this is a misunderstanding on my side. I thought connections on 25 also get handled as authentication, which is not the case. You are also right that DNS gets cached and shouldn't cause trouble. So apart from log messages this should not be an issue in any way.

Thanks for your effort and your great work!
