### ISSUE TITLE
Clamd was NOT notified

### ISSUE THREAD

**Issue by nike7o0** [Mailu/Mailu#2319]
Thank you for opening an issue with Mailu. Please understand that issues are meant for bugs and enhancement-requests.
For **user-support questions**, reach out to us  on [matrix](https://matrix.to/#/#mailu:tedomum.net).

To be able to help you best, we need some more information.

## Before you open your issue
- [x] Check if no issue or pull-request for this already exists.
- [x] Check [documentation](https://mailu.io/master/) and [FAQ](https://mailu.io/master/faq.html). (Tip, use the search function on the documentation page)
- [x] You understand `Mailu` is made by volunteers in their **free time** — be conscise, civil and accept that delays can occur.
- [x] The title of the issue should be short and simple. It should contain specific terms related to the actual issue. Be specific while writing the title.

### Environment
 - [x] docker-compose
 - [ ] kubernetes
 - [ ] docker swarm

### Versions
MASTER

$> docker ps -a | grep mailu
451023b7710b   mailu/roundcube:master   "docker-php-entrypoi…"   2 hours ago   Up 2 hours (healthy)       80/tcp   
         
$> grep MAILU_VERSION docker-compose.yml mailu.env
docker-compose.yml:    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}clamav:${MAILU_VERSION:-master}

## Description
There is a problem with Clamav container.
WARNING: Clamd was NOT notified: Can't connect to clamd through /tmp/clamd.sock: No such file or directory

## Replication Steps
Update to master

## Logs
antivirus_1  | Tue Apr 12 12:01:55 2022 -> WARNING: Clamd was NOT notified: Can't connect to clamd through /tmp/clamd.sock: No such file or directory

**Comment by ghostwheel42** [comment]
The explanation: freshclam is started only once at container startup before starting clamd.
So this is okay, as there's no clamd running yet.
