### ISSUE TITLE
Clamav failed to scan, maximum retransmits exceed

### ISSUE THREAD

**Issue by baskinsy** [Mailu/Mailu#2321]
### Environment
 - [ ] docker-compose

### Versions

1.9.25

## Description

Antivirus scanning not working at all

## Replication Steps

Sending attachments to mail accounts on the server and checking the antispam service logs. Clamav service is up and running no errors appear on its logs.

## Expected behaviour

Antivirus scanning of attachments should work. I remember it was still working with 1.9.24 if I'm not wrong, or at least with 1.9.23 which was the first version I installed and then upgraded.

## Logs

````markdown
```
antispam_1   | 2022-04-15 14:57:24 #7(rspamd_proxy) <79c0bd>; lua; clamav.lua:119: clamav: failed to scan, maximum retransmits exceed
antispam_1   | 2022-04-15 14:57:24 #7(rspamd_proxy) <79c0bd>; lua; common.lua:110: clamav: result - FAILED with error: "failed to scan and retransmits exceed - score: 0"
antispam_1   | 2022-04-15 15:38:26 #7(rspamd_proxy) <0ec412>; lua; clamav.lua:119: clamav: failed to scan, maximum retransmits exceed
antispam_1   | 2022-04-15 15:38:26 #7(rspamd_proxy) <0ec412>; lua; common.lua:110: clamav: result - FAILED with error: "failed to scan and retransmits exceed - score: 0"
```
````

**Comment by baskinsy** [comment]
A restart of the antispam service fixed the scanning problem, but i would like to know if there is anything I can check so it will not happen again. In case the problem re-appears, I will re-open the issue.

**Comment by baskinsy** [comment]
I am reopening the issues because the problem appears again. Restarting the antispam service fix it temporally. I will try to upgrade the VM to 8GB memory in case 4GB are not enough, but haven't see any service to fail due to memory exhaustion. 

Those are the latest errors from the admin interface

```
4/18/2022, 1:18:47 PM | rspamd_proxy | 7 | lua | 48dbf3 | clamav: failed to scan, maximum retransmits exceed
4/18/2022, 1:18:47 PM | rspamd_proxy | 7 | lua | 48dbf3 | clamav: failed to scan, maximum retransmits exceed
4/18/2022, 1:18:47 PM | rspamd_proxy | 7 | lua | 48dbf3 | clamav: failed to scan, maximum retransmits exceed
4/18/2022, 1:18:47 PM | rspamd_proxy | 7 | lua | 48dbf3 | clamav: failed to scan, maximum retransmits exceed
```

**Comment by pagaille** [comment]
Same problem here. Strangely enough it doesn't happens on another similarly configured machine with less ressources.
Still investigating, will report any findings.

**Comment by pagaille** [comment]
Fixed. Clamav was struggling to scan the email which was > 20MB. I extended the delay in `/etc/rspamd/local.d/antivirus.conf`

**Comment by baskinsy** [comment]
> Fixed. Clamav was struggling to scan the email which was > 20MB. I extended the delay in `/etc/rspamd/local.d/antivirus.conf`

Is there any way to do it in docker-compose or env file or we have to do it in the container (it will be overwritten with redeploy).

**Comment by pagaille** [comment]
Generally with docker you can use the -v (volume) option to map a file or even a folder on the host (and therefore persistent) to another one into the container. It takes precedence. See the doc for more info. 

>
