### ISSUE TITLE
Suggested DNS TLSA entry for LetsEncrypt is expired and incomplete

### ISSUE THREAD

**Issue by henniaufmrenni** [Mailu/Mailu#2326]
## Before you open your issue
- [x] Check if no issue or pull-request for this already exists.
- [x] Check [documentation](https://mailu.io/master/) and [FAQ](https://mailu.io/master/faq.html). (Tip, use the search function on the documentation page)
- [x] You understand `Mailu` is made by volunteers in their **free time** — be conscise, civil and accept that delays can occur.
- [x] The title of the issue should be short and simple. It should contain specific terms related to the actual issue. Be specific while writing the title.

### Environment
 - [x] docker-compose
 
### Versions
1.9.26

## Description
In the admin panel, Mailu suggests adding the [retired  Let's Encrypt ISRG Root X1](https://letsencrypt.org/certificates/#intermediate-certificates) as an TLSA entry, leading to DANE issues and thus [undeliverable mail](https://dnssec-stats.ant.isi.edu/~viktor/x3hosts.html).

The currently active certificates are R3, R4, E1, E2.

**Comment by nextgens** [comment]
We have talked about it at length on #2138, including with the author of the website you link to.

Please provide proof of what you are saying.

```
openssl s_client -connect test.mailu.io:25 -starttls smtp -dane_tlsa_domain test.mailu.io -dane_tlsa_rrdata "2 1 1 0b9fa5a59eed715c26c1020c711b4f6ec42d58b0015e14337a39dad301c5afc3" -tls1_2 -showcerts
```
says ```
Verification: OK
Verified peername: test.mailu.io
DANE TLSA 2 1 1 ...015e14337a39dad301c5afc3 matched TA certificate at depth 2
```
