### ISSUE TITLE
MESSAGE_RATELIMIT throws error ValueError: couldn't parse rate limit string 'xxx'

### ISSUE THREAD

**Issue by TerrapinSoftware** [Mailu/Mailu#2329]
### Environment
 - [x] docker-compose
 - [ ] kubernetes
 - [ ] docker swarm

### Versions
admin: 1.9.26

## Description
I tried to set MESSAGE_RATELIMIT=2000 in mailu.env, but the admin module keeps issuing the error `ValueError: couldn't parse rate limit string 'xxx'`. Maybe I am wrong? I am trying to disable rate limiting.

## Expected behaviour
Rate limit increased.

### Attempted fix

Add to `overrides/postfix/postfix.cf`:

    smtpd_client_message_rate_limit = 2000

**Comment by nextgens** [comment]
It expects a value over a time interval, as documented on https://mailu.io/1.9/configuration.html

Try ```MESSAGE_RATELIMIT=2000/minute``` or something

**Comment by TerrapinSoftware** [comment]
Hi Florent,

thank you so muchfor the explanation! Maybe you’d want to add a few examples to the documentation - it was not clear to me that a “double value” was expected.

Regards, Michael
