### ISSUE TITLE
"Plus mails" / sub-addressing should work out of the box

### ISSUE THREAD

**Issue by sunsided** [Mailu/Mailu#233]
Apparently "plus mails" ([RFC 5233](https://tools.ietf.org/html/rfc5233) / [Wiki](https://en.wikipedia.org/wiki/Email_address#Subaddressing)) do not work out of the box. Here, mails sent to `foo+something@domain.tld` would be automatically delivered to `foo@domain.tld`.

I see how I can set this up using wildcard aliases, but adding this to every address is extremely time consuming (especially since I make heavy use of aliases already).

**Comment by pesimon** [comment]
No need for wildcard... see #196

**Comment by sunsided** [comment]
Yes, but that would require configuration change and I'm not currently sure how to do this in a sane way.
My proposal is to have that a s a default.

**Comment by kaiyou** [comment]
We could use the `recipient_delimiter = +` setting in Postfix. I do not have enough time to test and see if there is any side effect with the way we handle aliases. If anyone could give it a try and report, I am considering adding the option to `master`

**Comment by kaiyou** [comment]
Could you test with `postfix:feature-recipient-delimiter` ?
