### ISSUE TITLE
Postfix stucks at startup

### ISSUE THREAD

**Issue by PepitoMexico** [Mailu/Mailu#2333]
### Environment
 - [ ] docker-compose
 - [ X] kubernetes
 - [ ] docker swarm

### Versions
Mailu 1.8 version.

## Description
Mailu is supposed to start, however when the pod is starting postfix hangs on starting.

## Replication Steps
Using mailu/postfix:1.8 image on a k3s instance

## Expected behaviour
The postfix server is supposed to start.

## Logs
May 03 12:36:09 mail postfix[50]: Postfix is running with backwards-compatible default settings
May 03 12:36:09 mail postfix[50]: See http://www.postfix.org/COMPATIBILITY_README.html for details
May 03 12:36:09 mail postfix[50]: To disable backwards compatibility use "postconf compatibility_level=3.6" and "postfix reload"
May 03 12:36:10 mail postfix[297]: Postfix is running with backwards-compatible default settings
May 03 12:36:10 mail postfix[297]: See http://www.postfix.org/COMPATIBILITY_README.html for details
May 03 12:36:10 mail postfix[297]: To disable backwards compatibility use "postconf compatibility_level=3.6" and "postfix reload"
May 03 12:36:11 mail postfix/postfix-script[363]: starting the Postfix mail system

**Comment by nextgens** [comment]
Mailu 1.8 is not supported anymore; Please retry with the current version and if you are still encountering problems, report them on https://github.com/Mailu/helm-charts/
