### ISSUE TITLE
Admin interface no sign-in button

### ISSUE THREAD

**Issue by TemporalAgent7** [Mailu/Mailu#2334]
Thank you for opening an issue with Mailu. Please understand that issues are meant for bugs and enhancement-requests.
For **user-support questions**, reach out to us  on [matrix](https://matrix.to/#/#mailu:tedomum.net).

To be able to help you best, we need some more information.

## Before you open your issue
- [x] Check if no issue or pull-request for this already exists.
- [x] Check [documentation](https://mailu.io/master/) and [FAQ](https://mailu.io/master/faq.html). (Tip, use the search function on the documentation page)
- [x] You understand `Mailu` is made by volunteers in their **free time** — be conscise, civil and accept that delays can occur.
- [x] The title of the issue should be short and simple. It should contain specific terms related to the actual issue. Be specific while writing the title.

### Environment
 - [x] docker-compose
 - [ ] kubernetes
 - [ ] docker swarm

### Versions
1.9

## Description
Just did a fresh installation of mailu on a brand new Debian 11 VM. Trying to finish the setup process by logging into the admin interface, but there is no "sign in" button, and pressing Enter doesn't do anything (nothing shows up in the browser console either). Tried with both Firefox and Chrome.

![0](https://user-images.githubusercontent.com/48541170/167057228-820e608a-54da-441f-94f7-1501f751db49.png)

## Replication Steps
Open the admin interface in a browser

## Expected behavior
I wanted to log into the admin interface to finish the setup (https://mailu.io/master/dns.html#dkim-spf-dmarc-entries).

**Comment by ghostwheel42** [comment]
Did you enable `ADMIN` or `WEBMAIL` in your `mailu.env` file?
```
ADMIN=true
WEBMAIL=roundcube
```
If ADMIN and WEBMAIL are disabled you can use the cli to configure mailu using the config-import and config-export actions.

**Comment by TemporalAgent7** [comment]
I wasn't able to figure out the issue, so just removed all mailu dockers and the local configuration and retried following the instructions again. I can see the "Signin" button now.

Still, I recommend displaying some kind of error message for this situation instead of hiding both sign-in buttons with no user messaging.
