### ISSUE TITLE
Unhealthy containers help

### ISSUE THREAD

**Issue by himuura** [Mailu/Mailu#2339]
## Before you open your issue
- [x ] Check if no issue or pull-request for this already exists.
- [x ] Check [documentation](https://mailu.io/master/) and [FAQ](https://mailu.io/master/faq.html). (Tip, use the search function on the documentation page)
- [x ] You understand `Mailu` is made by volunteers in their **free time** — be conscise, civil and accept that delays can occur.
- [x ] The title of the issue should be short and simple. It should contain specific terms related to the actual issue. Be specific while writing the title.

### Environment
 - [x ] docker-compose
 - [ ] kubernetes
 - [ ] docker swarm

### Versions
To find your version, get the image name of a mailu container and read  the version from the tag (example for version 1.7).
```
$> docker ps -a | grep mailu --> v1.9

$> grep MAILU_VERSION docker-compose.yml mailu.env
docker-compose.yml:    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}nginx:${MAILU_VERSION:-1.9}
docker-compose.yml:    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}unbound:${MAILU_VERSION:-1.9}
docker-compose.yml:    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}admin:${MAILU_VERSION:-1.9}
docker-compose.yml:    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}dovecot:${MAILU_VERSION:-1.9}
docker-compose.yml:    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}postfix:${MAILU_VERSION:-1.9}
docker-compose.yml:    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}rspamd:${MAILU_VERSION:-1.9}
docker-compose.yml:    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}clamav:${MAILU_VERSION:-1.9}
docker-compose.yml:    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}radicale:${MAILU_VERSION:-1.9}
docker-compose.yml:    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}fetchmail:${MAILU_VERSION:-1.9}
docker-compose.yml:    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}roundcube:${MAILU_VERSION:-1.9}


## Description
Further explain the bug in a few words. It should be clear what the unexpected behaviour is.  Share it in an easy-to-understand language.
3 unhealthy containers (admin, front, resolver), a couple of errors, no admin interface. I'm deploying on local network to test it.

Admin: 
CRITICAL:root:Your DNS resolver at 127.0.0.11 is not working (The DNS operation timed out after 11.601568460464478 seconds). Please see https://mailu.io/master/faq.html#the-admin-container-won-t-start-and-its-log-says-critical-your-dns-resolver-isn-t-doing-dnssec-validation

Front: 
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='acme-v02.api.letsencrypt.org', port=443): Max retries exceeded with url: /directory (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2d5f754dc0>: Failed to establish a new connection: [Errno -3] Try again'))
An unexpected error occurred:
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='acme-v02.api.letsencrypt.org', port=443): Max retries exceeded with url: /directory (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb05eac4a00>: Failed to establish a new connection: [Errno -3] Try again'))
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.
Saving debug log to /var/log/letsencrypt/letsencrypt.log

Resolver:
 <<>> DiG 9.16.27 <<>> @127.0.0.1 ; (1 server found) ;; global options: +cmd ;; connection timed out; no servers could be reached

## Replication Steps
Steps for replicating your issue
Fresh install of mailu.

## Expected behaviour
Explain what results you expected - be as specific as possible. Just saying "it doesn’t work as expected" is not useful. It's also helpful to describe what you actually experienced.
Don't actually know, i'm a first timer on this project.

## Logs
Often it is very useful to include log fragments of the involved component. You can get the logs via `docker logs <container name> --tail 1000`. For example for the admin container:
`docker logs mailu_admin_1 --tail 1000`
or using docker-compose `docker-compose -f /mailu/docker-compose.yml logs --tail 1000 admin`
If you can find the relevant section, please share only the parts that seem relevant. If you have any logs, please enclose them in code tags, like so:
````markdown
```
Just noticed the section..the logs are above.
Admin: 
CRITICAL:root:Your DNS resolver at 127.0.0.11 is not working (The DNS operation timed out after 11.601568460464478 seconds). Please see https://mailu.io/master/faq.html#the-admin-container-won-t-start-and-its-log-says-critical-your-dns-resolver-isn-t-doing-dnssec-validation

Front: 
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='acme-v02.api.letsencrypt.org', port=443): Max retries exceeded with url: /directory (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2d5f754dc0>: Failed to establish a new connection: [Errno -3] Try again'))
An unexpected error occurred:
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='acme-v02.api.letsencrypt.org', port=443): Max retries exceeded with url: /directory (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb05eac4a00>: Failed to establish a new connection: [Errno -3] Try again'))
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.
Saving debug log to /var/log/letsencrypt/letsencrypt.log

Resolver:
 <<>> DiG 9.16.27 <<>> @127.0.0.1 ; (1 server found) ;; global options: +cmd ;; connection timed out; no servers could be reached
(not much in the logs though)
[1652096158] unbound.conf[1:0] notice: init module 0: validator
[1652096158] unbound.conf[1:0] notice: init module 1: iterator
[1652096158] unbound.conf[1:0] info: start of service (unbound 1.13.2).

```
````
Any help would be greatly appreciated! Thanks in advance!
I know it's probably on my side (deploying on local network is always troublesome) i just wanted to spin the containers and check the interface and usability. It might be some sort of connection issue (being blocked by the corporate firewall) but if anyone has any idea of which of these containers in failing and cascading to the other i would be thankfull!

**Comment by nextgens** [comment]
The admin container refuses to start as the DNS resolution doesn't work. You can override the DNS settings of the admin container in your docker-compose.yml file if required

**Comment by himuura** [comment]
> The admin container refuses to start as the DNS resolution doesn't work. You can override the DNS settings of the admin container in your docker-compose.yml file if required

Yeah i figured as well. LOTS OF REQUESTS being blocked by the firewall...after allowing the server to connect to the requests it made, almost everything worked! Haven't managed to figure the letsencrypt part as it fails to create an account...dunno why though. For now, im testing the web interface on the local network, will test the full fledged configuration in the upcoming days.
Thank you for you reply!

**Comment by nextgens** [comment]
letsencrypt won't work unless you 1) use a valid domain 2) set the DNS records like they should be 3) allow access to port 80/443 from outside

**Comment by himuura** [comment]
Any chance on a quick step guide to do this using no-ip? I've created the domain and added the MX record but i might be missing something. If you don't have the time, no worries mate! I'll keep breaking stone until it's working =)

**Comment by entrymon** [comment]
Any help fixing this issue when you setup using helm chart as we don't have docker compose files when dealing with helm chart.
