### ISSUE TITLE
Can I prevent to use the local domain query?

### ISSUE THREAD

**Issue by PascalKu** [Mailu/Mailu#2340]
Hi there,

Right now, mails which are send to the same system are delivered directly - also if it's not the expected DNS-Configuration. Is it possible to remove this local query? So that the mail is send over DNS-Queried Mailserver?

Thanks!

**Comment by nextgens** [comment]
If you don't declare the domain as a mailu Domain this is what will happen. Have you tried removing it?

**Comment by PascalKu** [comment]
Is there any documentation about this? I mean how can I do this?

**Comment by nextgens** [comment]
https://mailu.io/1.9/webadministration.html
