### ISSUE TITLE
Remove AES128-GCM-SHA256 from nginx cipher list

### ISSUE THREAD

**Issue by ben221199** [Mailu/Mailu#2341]
### Environment
 - [x] docker-compose
 - [x] kubernetes
 - [x] docker swarm

### Versions
1.9

## Description
The cipher AES128-GCM-SHA256 is outdated.

## Replication Steps
NA

**Comment by nextgens** [comment]
Says who?

We follow https://ssl-config.mozilla.org/ except for port 25 where we want maximum compatibility (as any cryptography beats no cryptography and lost emails).

**Comment by ben221199** [comment]
https://internet.nl/mail/test.mailu.io/721304/
