### ISSUE TITLE
Support for resolving alias through an external API

### ISSUE THREAD

**Issue by f00wl** [Mailu/Mailu#2343]
_This is a feature request._

## Actual behavior

Aliases are resolved locally

## Expected behavior

Have the possibility to use, per domain, an external API for alias resolution

- It's interesting for people who use SSO/centralized accounts management to be able to manage user alias within it rather than inside mailu. 
- As passwordless authentication/SSO for apps is a good practice, this is also true for every users metadata, like email. To improve users privacy and reduce data leak risks (app side) it is possible to give randomized aliases to the app who use mailu instance to send emails to users. As it, only the account manager has the real email address. An alias delegation API setting per domain in mailu make this possible automatically, with the right account manager, for all user, all apps connected. A little schema, better than a big blaba:

```text
+-------------------------------------------------------+       +-----------------------------+
| Account manager/SSO  account.foo.bar                  |       | app.foo.bar                 |
| +---------------------------------------------------+ |       |                             |
| |User: foo          +-----------------------------+ | |       | +-------------------------+ |
| |Email: foo@foo.bar |App: app.foo.bar             | | |       | |User: oof                | |
| |        ^          |Email: xxxx@users.foo.bar+-------------> | |Email: xxx@users.foo.bar | |
| |        |          |Profile: oof                 | | |       | |        +                | |
| |        |          +-----------------------------+ | |       | +-------------------------+ |
| +---------------------------------------------------+ |       +-----------------------------+
+-------------------------------------------------------+                  |
           |                                                  +------------+
           |                                                  |
           |             +-----------------------------------------------+
           |             | Mailu Server                       |          |
           |             | --------------------------------------------- |
           |             | | Domain: users.foo.bar            v        | |
           +-------------+ | API: account.foo.bar/api/profile/{}/email | |
                         | +-------------------------------------------+ |
                         +-----------------------------------------------+
```
## About

I didn't invent anything  , [this article (in french sorry)](https://write.tedomum.net/tedomum/hiboo-re-inventons-la-roue-de-lauthentification#m%C3%A9tadonn%C3%A9es-des-utilisateurs) does. It explain this very well and has been realized with the account manager/SSO [Hiboo](https://forge.tedomum.net/acides/hiboo/hiboo). Mainly developed by @kaiyou also.

In fact all of this run in multiple production environments pretty well since years but never been reup-streamed in Mailu, I think other people could be interested, and it's boring to maintain the patch, so I take some time to submit a PR.

**Comment by Diman0** [comment]
This feature request does not align with the main goals of the project. For this reason we will not implement this. 
It is too much of a niche feature which adds yet more maintenance overhead.
It also does not align with goal that mailu is insular. 

The config-import/config-export cli functionality can be used to add new aliases to mailu. In the future we will also have a restful api available.
