### ISSUE TITLE
can't open admin web

### ISSUE THREAD

**Issue by j848623143** [Mailu/Mailu#2358]
Hi all, i am new to Mailu and i cannot figure out what is wrong with my new install.
![image](https://user-images.githubusercontent.com/54465474/170432363-304ceb30-402b-46f5-b3df-6758a4fbdd08.png)

**Comment by nextgens** [comment]
Your front container is not staying up for some reason; Please provide the output of:
``docker exec -ti emails_front_1 cat /etc/ninx/nginx.conf``

Do you have any override in overrides/nginx/ ?
