### ISSUE TITLE
Admin: Base URL is hard-coded

### ISSUE THREAD

**Issue by nalt** [Mailu/Mailu#236]
The admin interface is hardcoded to the base URL /admin and generates links accordingly. In many setups, the admin interface must made available under a different URL. Therefore, the base URL should be configurable, or, if possible, only relative links should be used.

**Comment by kaiyou** [comment]
I agree, but my knowledge of Flask was limited at the time and I did not find any better option. I will have another look and see if this is possible. If not, I really plan on moving to a REST API and a JS app, which will solve the issue.

**Comment by nalt** [comment]
I think a quick workaround would be to use an env variable "WEBROOT" instead of the hard-coded /admin. If the variable is not set, the webroot would default to /admin.

**Comment by kaiyou** [comment]
A proper workaround as I found out is to use `X-Forwarded-Prefix`, that is passed by `traefik` to the destination container. Thus, the admin container could simply serve its interface at `/` and we could use proper blueprints for features instead of a desperate `/admin` blueprint.

Also, we would need to implement this in all webmails, which could be more of an issue.

However, it would make our containers a lot more reusable.

**Comment by nalt** [comment]
Webmail does not have this problem; it works well behind a reverse proxy even under a different URL. I can post my config if it helps.

**Comment by kaiyou** [comment]
It would help indeed :)

**Comment by kaiyou** [comment]
This is now implemented in #262, all the prefixes can be set in `docker-compose.yml` directly with no further change.

**Comment by trueserve** [comment]
This works, but the default paths have a trailing slash, meaning that visiting /admin won't work, but /admin/ will for example.

Removing the trailing slash will allow for both conditions to work.

**Comment by kaiyou** [comment]
Thank you for the advice, will commit this :)

**Comment by kaiyou** [comment]
Removing the trailing slash does not seem to match properly with traefik prefix stripping rules, could you share your working configuration?

**Comment by trueserve** [comment]
I only changed the following lines in docker-compose.yml:

`      - traefik.admin.frontend.rule=Host:$HOSTNAME;PathPrefix:/admin`
and
`      - traefik.frontend.rule=Host:$HOSTNAME;PathPrefix:/webmail`

I tested on a fresh browser without my domain cached, and going to http://mail.mydomain.com/admin properly redirected me to https://mail.mydomain.com/admin/login?next=%2Fadmin%2F

**Comment by kaiyou** [comment]
Following #272, we will probably have to rollback on this and find another way to configure the admin path.

**Comment by kaiyou** [comment]
This is now implemented as part of the nginx configuration.
