### ISSUE TITLE
V1.9 Fails to start, if in isolated env. (no Internet) 

### ISSUE THREAD

**Issue by ARGO1960** [Mailu/Mailu#2365]
Thank you for opening an issue with Mailu. Please understand that issues are meant for bugs and enhancement-requests.
For **user-support questions**, reach out to us  on [matrix](https://matrix.to/#/#mailu:tedomum.net).

To be able to help you best, we need some more information.

## Before you open your issue
- [ ] Check if no issue or pull-request for this already exists.
- [ ] Check [documentation](https://mailu.io/master/) and [FAQ](https://mailu.io/master/faq.html). (Tip, use the search function on the documentation page)
- [ ] You understand `Mailu` is made by volunteers in their **free time** — be conscise, civil and accept that delays can occur.
- [ ] The title of the issue should be short and simple. It should contain specific terms related to the actual issue. Be specific while writing the title.

### Environment
 - [X] docker-compose
 - [ ] kubernetes
 - [ ] docker swarm

### Versions
1.9
## Description
Using version 1.7 in a lab environment using compose I can get it working.
When Using V1.9 I see the nice msg:
mailu-admin-1     | CRITICAL:root:Your DNS resolver at 127.0.0.11 is not working (The DNS operation timed out after 11.60525631904602 seconds). Please see https://mailu.io/master/faq.html#the-admin-container-won-t-start-and-its-log-says-critical-your-dns-resolver-isn-t-doing-dnssec-validation 

Now I have setup the unbound resolver container and that seems to try to connect to:
58	0.801798	10.10.10.50	192.203.230.10	DNS	70	Standard query 0x07ad NS <Root> OPT
59	0.801837	10.10.10.1	10.10.10.50	ICMP	98	Destination unreachable (Host unreachable)
61	1.177625	10.10.10.50	192.203.230.10	DNS	70	Standard query 0x6f56 NS <Root> OPT
62	1.177672	10.10.10.1	10.10.10.50	ICMP	98	Destination unreachable (Host unreachable)
63	1.555801	10.10.10.50	192.112.36.4	DNS	70	Standard query 0x0efd NS <Root> OPT
64	1.555852	10.10.10.1	10.10.10.50	ICMP	98	Destination unreachable (Host unreachable)
65	1.932561	10.10.10.50	192.112.36.4	DNS	70	Standard query 0xc475 NS <Root> OPT
66	1.932611	10.10.10.1	10.10.10.50	ICMP	98	Destination unreachable (Host unreachable)
67	2.310334	10.10.10.50	192.203.230.10	DNS	70	Standard query 0x5978 NS <Root> OPT

When I allow the internet connection, and restart it works (meaning the web interfaces come up and I can login).
But assume you want to use this in a complete isolated environment without internet access you can't get it to run.
Also the error msg complains about  DNS resolver at 127.0.0.11 but its using 192.168.203.254 so is that wrong?

## Replication Steps
Shutdown containers 
disconnect Internet access.
start containers / Docker-compose up

## Expected behavior
It should start even if it can't get those DNS hosts, I think is not even a DNSSEC error at al but just DNS error.
in my isolated world there are ROOT level resolver and SLD but its not the internet.

Logs:
mailu-antispam-1  | 2022-05-30 17:16:23 #1(main) <4dego7>; map; rspamd_try_load_re_map_cache: loaded hypersan cache from /var/lib/rspamd//3034a0483753f4fd9b1d586eda8b5b7eb0f8352dbdb2fbccd5114fcdecb80cfe.hsmc (5.97KiB length) for static
mailu-antispam-1  | 2022-05-30 17:16:23 #1(main) <4dego7>; map; rspamd_re_map_finalize: hyperscan read 2 cached regular expressions from static
mailu-antispam-1  | 2022-05-30 17:16:23 #1(main) <4dego7>; map; rspamd_regexp_list_fin: read regexp list of 2 elements
mailu-antispam-1  | 2022-05-30 17:16:23 #1(main) <ks7cha>; map; read_map_file: /etc/rspamd/local.d/greylist-whitelist-domains.inc: map file is not found; it will be read automatically if created
mailu-antispam-1  | 2022-05-30 17:16:23 #1(main) <ks7cha>; map; read_map_file: /etc/rspamd/local.d/maps.d/greylist-whitelist-domains.inc: map file is not found; it will be read automatically if created
mailu-antispam-1  | 2022-05-30 17:16:23 #1(main) <4dego7>; map; read_map_static: static: read map data, 10 bytes
mailu-antispam-1  | 2022-05-30 17:16:23 #1(main) <4dego7>; map; rspamd_radix_fin: read radix trie of 1 elements: ents=1 dup=0 tbm=0 lc=3 mem=1k free=0 waste=0
mailu-antispam-1  | 2022-05-30 17:16:23 #1(main) <759e28>; main; main: rspamd 3.2 is starting, build id: release
mailu-antispam-1  | 2022-05-30 17:16:23 #1(main) <759e28>; main; main: cpu features: avx2, avx, sse2, sse3, ssse3, sse4.1, sse4.2, rdrand
mailu-antispam-1  | 2022-05-30 17:16:23 #1(main) <759e28>; main; main: cryptobox configuration: curve25519(libsodium), chacha20(avx2), poly1305(libsodium), siphash(libsodium), blake2(libsodium), base64(avx2)
mailu-antispam-1  | 2022-05-30 17:16:23 #1(main) <759e28>; main; main: libottery prf: AES-128
mailu-antispam-1  | 2022-05-30 17:16:23 #1(main) <759e28>; main; main: pid file is not specified, skipping writing it
mailu-antispam-1  | 2022-05-30 17:16:23 #1(main) <759e28>; main; main: event loop initialised with backend: epoll
mailu-antispam-1  | 2022-05-30 17:16:23 #1(main) <759e28>; main; rspamd_fork_worker: prepare to fork process rspamd_proxy (0); listen on: *
mailu-antispam-1  | 2022-05-30 17:16:23 #1(main) <759e28>; main; spawn_workers: worker of type normal(localhost:11333) is disabled in the config, skip spawning
mailu-antispam-1  | 2022-05-30 17:16:23 #1(main) <759e28>; main; rspamd_fork_worker: prepare to fork process fuzzy (0); listen on: *
mailu-antispam-1  | 2022-05-30 17:16:23 #7(rspamd_proxy) <759e28>; main; rspamd_worker_set_limits: use system max file descriptors limit: 1024KiB cur and 1024KiB max
mailu-antispam-1  | 2022-05-30 17:16:23 #7(rspamd_proxy) <759e28>; main; rspamd_worker_set_limits: use system max core size limit: -1B cur and -1B max
mailu-antispam-1  | 2022-05-30 17:16:23 #7(rspamd_proxy) <759e28>; main; rspamd_handle_child_fork: starting rspamd_proxy process 7 (0); listen on: *:11332
mailu-antispam-1  | 2022-05-30 17:16:23 #7(rspamd_proxy) <ngh66s>; cfg; rspamd_dns_resolv_conf_on_server: parsed nameserver 127.0.0.11 from resolv.conf
mailu-antispam-1  | 2022-05-30 17:16:23 #7(rspamd_proxy) <ngh66s>; cfg; rspamd_dns_read_hosts_file: processed host file /etc/hosts; 9 records added
mailu-antispam-1  | 2022-05-30 17:16:23 #1(main) <759e28>; main; rspamd_fork_worker: prepare to fork process controller (0); listen on: *
mailu-antispam-1  | 2022-05-30 17:16:23 #1(main) <759e28>; main; rspamd_fork_worker: prepare to fork process hs_helper (0), no bind socket
mailu-antispam-1  | 2022-05-30 17:16:23 #7(rspamd_proxy) <ngh66s>; cfg; rspamd_stat_init: added backend redis for symbol BAYES_SPAM
mailu-antispam-1  | 2022-05-30 17:16:23 #7(rspamd_proxy) <ngh66s>; cfg; rspamd_stat_init: added backend redis for symbol BAYES_HAM
mailu-antispam-1  | 2022-05-30 17:16:23 #1(main) <759e28>; main; main: listening for control commands on /run/rspamd/rspamd.sock
mailu-antispam-1  | 2022-05-30 17:16:23 #10(hs_helper) <759e28>; main; rspamd_worker_set_limits: use system max file descriptors limit: 1024KiB cur and 1024KiB max
mailu-antispam-1  | 2022-05-30 17:16:23 #10(hs_helper) <759e28>; main; rspamd_worker_set_limits: use system max core size limit: -1B cur and -1B max
mailu-antispam-1  | 2022-05-30 17:16:23 #10(hs_helper) <759e28>; main; rspamd_handle_child_fork: starting hs_helper process 10 (0); no listen
mailu-antispam-1  | 2022-05-30 17:16:23 #7(rspamd_proxy) <ngh66s>; lua; lua_redis.lua:1207: uploaded redis script to 192.168.203.2:6379 with id 4, sha: e7a1e089124abbfb1f68ecf1d1da3ac41d4f86a3
mailu-antispam-1  | 2022-05-30 17:16:23 #7(rspamd_proxy) <ngh66s>; lua; lua_redis.lua:1207: uploaded redis script to 192.168.203.2:6379 with id 1, sha: b2b5aaa894dc3056e6ac294e44adbd0a1ca702b6
mailu-antispam-1  | 2022-05-30 17:16:23 #7(rspamd_proxy) <ngh66s>; lua; lua_redis.lua:1207: uploaded redis script to 192.168.203.2:6379 with id 2, sha: a43800941e2820ed8d764d50dfd9c142beddde68
mailu-antispam-1  | 2022-05-30 17:16:23 #7(rspamd_proxy) <ngh66s>; lua; lua_redis.lua:1207: uploaded redis script to 192.168.203.2:6379 with id 3, sha: 3b7b7539e4555fa579ead520dcc3a85d8a25ceab
mailu-antispam-1  | 2022-05-30 17:16:23 #7(rspamd_proxy) <ngh66s>; lua; lua_redis.lua:1207: uploaded redis script to 192.168.203.2:6379 with id 5, sha: 3356099ff58c7e8893283c259278305d0d813a84
mailu-antispam-1  | 2022-05-30 17:16:23 #7(rspamd_proxy) <ngh66s>; lua; lua_redis.lua:1207: uploaded redis script to 192.168.203.2:6379 with id 6, sha: da3a534c5a16cf973cfab2ba50c1fb8461a87093
mailu-antispam-1  | 2022-05-30 17:16:23 #8(fuzzy) <759e28>; main; rspamd_worker_set_limits: use system max file descriptors limit: 1024KiB cur and 1024KiB max
mailu-antispam-1  | 2022-05-30 17:16:23 #8(fuzzy) <759e28>; main; rspamd_worker_set_limits: use system max core size limit: -1B cur and -1B max
mailu-antispam-1  | 2022-05-30 17:16:23 #8(fuzzy) <759e28>; main; rspamd_handle_child_fork: starting fuzzy process 8 (0); listen on: *:11335
mailu-antispam-1  | 2022-05-30 17:16:23 #9(controller) <759e28>; main; rspamd_worker_set_limits: use system max file descriptors limit: 1024KiB cur and 1024KiB max
mailu-antispam-1  | 2022-05-30 17:16:23 #9(controller) <759e28>; main; rspamd_worker_set_limits: use system max core size limit: -1B cur and -1B max
mailu-antispam-1  | 2022-05-30 17:16:23 #8(fuzzy) <ngh66s>; cfg; rspamd_dns_resolv_conf_on_server: parsed nameserver 127.0.0.11 from resolv.conf
mailu-antispam-1  | 2022-05-30 17:16:23 #9(controller) <759e28>; main; rspamd_handle_child_fork: starting controller process 9 (0); listen on: *:11334
mailu-antispam-1  | 2022-05-30 17:16:23 #8(fuzzy) <ngh66s>; cfg; rspamd_dns_read_hosts_file: processed host file /etc/hosts; 9 records added
mailu-antispam-1  | 2022-05-30 17:16:23 #9(controller) <ngh66s>; controller; rspamd_controller_password_sane: your normal password is not encrypted, we strongly recommend to replace it with the encrypted one
mailu-antispam-1  | 2022-05-30 17:16:23 #9(controller) <ngh66s>; controller; rspamd_controller_password_sane: enable password is not set, so you should filter controller availability by using of firewall or `secure_ip` option
mailu-antispam-1  | 2022-05-30 17:16:23 #9(controller) <ngh66s>; cfg; rspamd_dns_resolv_conf_on_server: parsed nameserver 127.0.0.11 from resolv.conf
mailu-antispam-1  | 2022-05-30 17:16:23 #8(fuzzy) <f81e1d>; radix; radix_insert_compressed: fuzzy update: cannot insert 00007F807CE541C0, key: [::ffff:127.0.0.1]/128, duplicate value
mailu-antispam-1  | 2022-05-30 17:16:23 #8(fuzzy) <ngh66s>; cfg; rspamd_dns_resolv_conf_on_server: parsed nameserver 127.0.0.11 from resolv.conf
mailu-antispam-1  | 2022-05-30 17:16:23 #9(controller) <ngh66s>; cfg; rspamd_dns_read_hosts_file: processed host file /etc/hosts; 9 records added
mailu-antispam-1  | 2022-05-30 17:16:23 #8(fuzzy) <ngh66s>; cfg; rspamd_dns_read_hosts_file: processed host file /etc/hosts; 9 records added
mailu-antispam-1  | 2022-05-30 17:16:23 #8(fuzzy) fuzzy_peer_rep: got peer fd reply from the main process
mailu-antispam-1  | 2022-05-30 17:16:23 #8(fuzzy) fuzzy_peer_rep: start listening on [::]:11335
mailu-antispam-1  | 2022-05-30 17:16:23 #8(fuzzy) fuzzy_peer_rep: start listening on 0.0.0.0:11335
mailu-antispam-1  | 2022-05-30 17:16:23 #8(fuzzy) <ngh66s>; lua; lua_redis.lua:1207: uploaded redis script to 192.168.203.2:6379 with id 5, sha: 3356099ff58c7e8893283c259278305d0d813a84
mailu-antispam-1  | 2022-05-30 17:16:23 #8(fuzzy) <ngh66s>; lua; lua_redis.lua:1207: uploaded redis script to 192.168.203.2:6379 with id 4, sha: e7a1e089124abbfb1f68ecf1d1da3ac41d4f86a3
mailu-antispam-1  | 2022-05-30 17:16:23 #8(fuzzy) <ngh66s>; lua; lua_redis.lua:1207: uploaded redis script to 192.168.203.2:6379 with id 2, sha: a43800941e2820ed8d764d50dfd9c142beddde68
mailu-antispam-1  | 2022-05-30 17:16:23 #8(fuzzy) <ngh66s>; lua; lua_redis.lua:1207: uploaded redis script to 192.168.203.2:6379 with id 6, sha: da3a534c5a16cf973cfab2ba50c1fb8461a87093
mailu-antispam-1  | 2022-05-30 17:16:23 #8(fuzzy) <ngh66s>; lua; lua_redis.lua:1207: uploaded redis script to 192.168.203.2:6379 with id 1, sha: b2b5aaa894dc3056e6ac294e44adbd0a1ca702b6
mailu-antispam-1  | 2022-05-30 17:16:23 #8(fuzzy) <ngh66s>; lua; lua_redis.lua:1207: uploaded redis script to 192.168.203.2:6379 with id 3, sha: 3b7b7539e4555fa579ead520dcc3a85d8a25ceab
mailu-antispam-1  | 2022-05-30 17:16:23 #9(controller) <ngh66s>; cfg; rspamd_stat_init: added backend redis for symbol BAYES_SPAM
mailu-antispam-1  | 2022-05-30 17:16:23 #9(controller) <ngh66s>; cfg; rspamd_stat_init: added backend redis for symbol BAYES_HAM
mailu-antispam-1  | 2022-05-30 17:16:23 #9(controller) <tp57x4>; rrd; rspamd_rrd_open: rrd file opened: /var/lib/rspamd/rspamd.rrd
mailu-antispam-1  | 2022-05-30 17:16:23 #9(controller) <ngh66s>; lua; lua_redis.lua:1207: uploaded redis script to 192.168.203.2:6379 with id 5, sha: 3356099ff58c7e8893283c259278305d0d813a84
mailu-antispam-1  | 2022-05-30 17:16:23 #9(controller) <ngh66s>; lua; lua_redis.lua:1207: uploaded redis script to 192.168.203.2:6379 with id 4, sha: e7a1e089124abbfb1f68ecf1d1da3ac41d4f86a3
mailu-antispam-1  | 2022-05-30 17:16:23 #9(controller) <ngh66s>; lua; lua_redis.lua:1207: uploaded redis script to 192.168.203.2:6379 with id 3, sha: 3b7b7539e4555fa579ead520dcc3a85d8a25ceab
mailu-antispam-1  | 2022-05-30 17:16:23 #9(controller) <ngh66s>; lua; lua_redis.lua:1207: uploaded redis script to 192.168.203.2:6379 with id 2, sha: a43800941e2820ed8d764d50dfd9c142beddde68
mailu-antispam-1  | 2022-05-30 17:16:23 #9(controller) <ngh66s>; lua; lua_redis.lua:1207: uploaded redis script to 192.168.203.2:6379 with id 1, sha: b2b5aaa894dc3056e6ac294e44adbd0a1ca702b6
mailu-antispam-1  | 2022-05-30 17:16:23 #9(controller) <ngh66s>; lua; lua_redis.lua:1207: uploaded redis script to 192.168.203.2:6379 with id 6, sha: da3a534c5a16cf973cfab2ba50c1fb8461a87093
mailu-antispam-1  | 2022-05-30 17:16:28 #10(hs_helper) rspamd_rs_compile_cb: compiled 0 regular expressions to the hyperscan tree, postpone loaded notification for 1 seconds to avoid races
mailu-antispam-1  | 2022-05-30 17:16:28 #9(controller) <o33omj>; map; rspamd_map_dns_callback: cannot resolve maps.rspamd.com: query timed out
mailu-antispam-1  | 2022-05-30 17:16:28 #9(controller) <qbq3yk>; map; rspamd_map_dns_callback: cannot resolve maps.rspamd.com: query timed out
mailu-antispam-1  | 2022-05-30 17:16:28 #9(controller) <dyatkr>; map; rspamd_map_dns_callback: cannot resolve maps.rspamd.com: query timed out
mailu-antispam-1  | 2022-05-30 17:16:28 #9(controller) <fdp86m>; map; rspamd_map_dns_callback: cannot resolve maps.rspamd.com: query timed out
mailu-antispam-1  | 2022-05-30 17:16:28 #9(controller) <7n3qic>; map; rspamd_map_dns_callback: cannot resolve maps.rspamd.com: query timed out
mailu-admin-1     | CRITICAL:root:Your DNS resolver at 127.0.0.11 is not working (The DNS operation timed out after 11.60525631904602 seconds). Please see https://mailu.io/master/faq.html#the-admin-container-won-t-start-and-its-log-says-critical-your-dns-resolver-isn-t-doing-dnssec-validation

**Comment by nextgens** [comment]
IMHO That's a feature and not a bug.

Mailu now checks that DNS resolution works and bails out early if it doesn't. There is a zillion things that do rely on internet connectivity (clamav updates, RBL checks in rspamd, reverse DNS lookups in postfix, ...).

What's the usecase for running Mailu (or any mailserver) without internet connectivity?

**Comment by aprilmaccydee** [comment]
If you need this, or to override the DNSSEC check, you can take start.py from the admin container, comment out this line:
https://github.com/Mailu/Mailu/blob/master/core/admin/start.py#L47
and mount it as /start.py inside the container (make sure to chmod +x it).

**Comment by ARGO1960** [comment]
> IMHO That's a feature and not a bug.
> 
> Mailu now checks that DNS resolution works and bails out early if it doesn't. There is a zillion things that do rely on internet connectivity (clamav updates, RBL checks in rspamd, reverse DNS lookups in postfix, ...).
> 
> What's the usecase for running Mailu (or any mailserver) without internet connectivity?

Depends how you look at it.
Mailu 1.7 did not have it.

Maybe there are networks not connected to the internet spanning the whole world and people there want an easy way to exchange msg by using mailu in docker containers.  as I understand there is only one world in your view. ;-) no offend meaning.

**Comment by ARGO1960** [comment]
> If you need this, or to override the DNSSEC check, you can take start.py from the admin container, comment out this line: https://github.com/Mailu/Mailu/blob/master/core/admin/start.py#L47 and mount it as /start.py inside the container (make sure to chmod +x it).

Thanks when I have time i'll look at it. as yes maybe i'll do that and try to reconfigure the whole stuff to our dns setup 
as i like the dnssec setup but our roots are different.
Thank you for the hint thats what i'm looking for.
