### ISSUE TITLE
Rspamd triggers "DHFILTER_HOSTNAME_UNKNOWN" since v1.9.29 (May 19th update)

### ISSUE THREAD

**Issue by ch4ox** [Mailu/Mailu#2368]
Thank you for opening an issue with Mailu. Please understand that issues are meant for bugs and enhancement-requests.
For **user-support questions**, reach out to us  on [matrix](https://matrix.to/#/#mailu:tedomum.net).

To be able to help you best, we need some more information.

## Before you open your issue
- [x] Check if no issue or pull-request for this already exists.
- [x] Check [documentation](https://mailu.io/master/) and [FAQ](https://mailu.io/master/faq.html). (Tip, use the search function on the documentation page)
- [x] You understand `Mailu` is made by volunteers in their **free time** — be conscise, civil and accept that delays can occur.
- [x] The title of the issue should be short and simple. It should contain specific terms related to the actual issue. Be specific while writing the title.

### Environment
 - [x] docker-compose
 - [ ] kubernetes
 - [ ] docker swarm

### Versions
1.9

## Description
Today while checking "Antispam" I discovered that almost all mails are flagged with "HFILTER_HOSTNAME_UNKNOWN (2.5)" which increases the spam score by 2.5. This behavior happens since v1.9.29 update on May 19th 2022.

When looking at the mail headers involved, the problem seems to be the PTR lookup. The last "Received:" entry always misses the foreign mail server's hostname ("unknown" is shown):

````markdown
Received: from mail.congstar.de (unknown [83.125.118.152]) by myserver.com (Postfix) with ESMTP id 273FC5E9B1 for <me@myserver.com>; Mon, 23 May 2022 20:21:38 +0200 (CEST)
Received: from mail-pj1-f51.google.com (unknown [209.85.216.51]) by myserver.com (Postfix) with ESMTP id 3069A5F76A for <me@myserver.com>; Wed, 1 Jun 2022 01:46:44 +0200 (CEST)
````

## Replication Steps
- Install Mailu with latest update (v1.9.29)
- unbound DNS was configured in setup
- everything else is on default config

## Expected behaviour
"DHFILTER_HOSTNAME_UNKNOWN" should only be triggered if PTR is incorrect.

## Logs
Postfix log also shows "unknown":

````markdown
2022-06-01T01:46:44.107931+02:00 1c3dde3db55b postfix/smtpd[170371]: connect from mailu_front_1.ch4osnet[172.18.0.30]
2022-06-01T01:46:44.199185+02:00 1c3dde3db55b postfix/smtpd[170371]: 3069A5F76A: client=unknown[209.85.216.51]
2022-06-01T01:46:44.409957+02:00 1c3dde3db55b postfix/cleanup[170535]: 3069A5F76A: message-id=<1881315720.185842752.1654040799980@email.apple.com>
2022-06-01T01:46:47.663596+02:00 1c3dde3db55b postfix/qmgr[362]: 3069A5F76A: from=<SRS0=pugr=WH=gmail.com=me@myserver.com>, size=38821, nrcpt=2 (queue active)
2022-06-01T01:46:47.766008+02:00 1c3dde3db55b postfix/lmtp[170536]: 3069A5F76A: to=<me@myserver.com>, relay=172.18.0.33[172.18.0.33]:2525, delay=3.6, delays=3.5/0.04/0.01/0.05, dsn=2.0.0, status=sent (250 2.0.0 <me@myserver.com> nAe9KueolmJk2gIAPBrCBg Saved)
````

**Comment by ch4ox** [comment]
Is this related to [this](https://github.com/Mailu/Mailu/issues/2260#issuecomment-1143443351)? My setup uses IPv4 only though.

**Comment by Diman0** [comment]
It is caused by PR #2348 
A solution is to add back the resolver line to the config. Although this will lead to warning messages in the nginx log again.
