### ISSUE TITLE
500 server error when navigating to url

### ISSUE THREAD

**Issue by kale1d0code** [Mailu/Mailu#2380]
Thank you for opening an issue with Mailu. Please understand that issues are meant for bugs and enhancement-requests.
For **user-support questions**, reach out to us  on [matrix](https://matrix.to/#/#mailu:tedomum.net).

To be able to help you best, we need some more information.

## Before you open your issue
- [x] Check if no issue or pull-request for this already exists.
- [x] Check [documentation](https://mailu.io/master/) and [FAQ](https://mailu.io/master/faq.html). (Tip, use the search function on the documentation page)
- [x] You understand `Mailu` is made by volunteers in their **free time** — be conscise, civil and accept that delays can occur.
- [x] The title of the issue should be short and simple. It should contain specific terms related to the actual issue. Be specific while writing the title.

### Environment
docker-compose + traefik reverse proxy
env file not compatible with setup (portainer docker admin panel) environment variables moved to docker-compose file

### Versions
1.9

## Description
traefik responds with 500 status code when navigating to url for web interface,
nginx container mentions a connection on port 25 from traefik container ip address and imap container mentions an aborted pop-3 login

## Replication Steps
1 start up stack.
2 navigate to url set in traefik router rule

## Expected behaviour
server responds with setup screen or welcome screen

## Logs
FRONT
```
2022/06/24 19:18:10 [info] 11#11: *18 client sent too many invalid commands while in auth state, client: <TRAEFIK_IP>, server: 0.0.0.0:25
2022/06/24 19:20:48 [info] 11#11: *24 client <TRAEFIK_IP>:41220 connected to 0.0.0.0:25
```
IMAP
```
Jun 24 19:27:41 pop3-login: Info: Disconnected: Aborted login by logging out (no auth attempts in 0 secs): user=<>, rip=127.0.0.1, lip=127.0.0.1, secured, session=<EmLCuTXiBpR/AAAB>
```

**Comment by witten** [comment]
In case anyone else runs across this one: The problem is that Traefik is sending HTTP traffic to the first port published by the Mailu front container—which is 25. But you don't want HTTP traffic going to port 25; you want it going to 80. So the solution is to add an extra label to the front container instructing Traefik to use the right port! Example:

```
labels:
    ...
    "traefik.http.services.front.loadbalancer.server.port=80"
```

In my case, the full set of labels is:

```
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.front-websecure.rule=Host(`mail.example.org`)"
      - "traefik.http.routers.front-websecure.entrypoints=websecure"
      - "traefik.http.routers.front-websecure.tls.certResolver=letsencrypt"
      - "traefik.http.services.front.loadbalancer.server.port=80"
```
