### ISSUE TITLE
Proposal for simplifying CI file

### ISSUE THREAD

**Issue by leolivier** [Mailu/Mailu#2383]
Hi
Looking at the CI file, I'm a bit puzzled of all these repetitions for building all the environment.
Why not using the much more easy way of jobs output as described here: https://www.macstadium.com/blog/sharing-variables-between-jobs-in-github-actions
This would save hundreds of lines in the CI file, make it much more maintainable and understandable.
If you're interested in that, I can try to do a PR...

**Comment by Diman0** [comment]
Using that functionality, it would indeed be possible to use a single job to derive all variable values, and then use a single step in each job to assign the variable values using needs to the environment variables of the runner. This makes the CI.yml indeed much easier to read.

But because it is the CI, it must be tested very well. Without seeing all scenarios working in a forked repo, I'm not sure if a PR would be accepted. The CI influence automatic build and deployment of images on docker and github releases. For this reason we don't make often changes to it. 

The next time the CI must be adapted, we will have a look at this.

**Comment by leolivier** [comment]
@Diman0 all right. another thing that could be addressed when looking at the CI file is to replace the "explicit" docker commands (docker login, docker-compose, docker save, ...) by  github [docker-build-push actions](https://github.com/docker/build-push-action), [docker-login actions](https://github.com/docker/login-action), [bake actions](https://github.com/docker/bake-action) ...
This would:
* simplify very much the cache mechanism (and maybe enhance its performance) 
* prepare for using buildx and thus open the possibility to multiarch (you can start with only amd64 platform)

I fully understand this is quite a big change in the build process but worth having a look as arm64 becomes unavoidable (and armv7 resists :))

**Comment by Diman0** [comment]
For this release I was planning on looking into use buildx and switching to buildx. I haven't used it before. This would also be a great moment to simplify and improve the CI.yml file. Especially with that "sharing variables between jobs". That will make the yml file much easier to read. After that we could look into what is required to get arm working.

**Comment by leolivier** [comment]
We've experienced buildx on Mailu with @Erriez and I can help if needed

**Comment by leolivier** [comment]
New progress on the topic:
- replaced all tests by one generic test instanciated by ci matrix
- clean ghcr job written but needs to be triggered properly
- cleaned setup job

All tests passed! https://github.com/leolivier/Mailu/actions/runs/2728178415 
CI job at https://github.com/leolivier/Mailu/blob/ci-multiarch/.github/workflows/CI-multiarch.yml 

Still to do 
- no way currently to use the cache for tests, so still using ghcr.io as registry for tests
- replace deploy.sh script by simple github action
- solve the issue with expected pre existing resolver image
- build multiarch

**Comment by Diman0** [comment]
That looks promising. I will use this in my simplification for the automatic build. Using a single test job with a matrix for all targets is really handy to get rid of most of the configuration lines in the ci.yml.

**Comment by Diman0** [comment]
Again thank you for your assistance. Your examples were really helpful.  I have taken over most of the things. The complete workflow takes about ~12/13 minutes instead of the 20+ minutes it was before.  That is a great improvement.

I'm not going to use the ghcr.io docker registry. It is too unclear for me how the images must be removed. It also introduces more complexity because we will have mutliple CI workflow runs pushing to the same registry (runs for push on master, push on x.y branch and push on try branch).

Besides it means that all images are send twice during the build job which takes twice the time
- images are pushed to ghcr.io
- build cache is pushed to github cache

Now only the latter happens (use build cache). In subsequent steps (tests and deploy) all images are rebuild from github cache. This takes only about a minute. 

This is the latest workflow. It has one test too much. This is already resolved in .yml file. There should only be one filters test with waiting time 3 minutes.
https://github.com/Diman0/Mailu_Fork/actions/runs/2752134371
https://github.com/Diman0/Mailu_Fork/blob/master/.github/workflows/CI.yml

All  that is left to do for me is testing. I did not test the release flow yet (push on branch x.y, e.g. 1.10). I will probably have some findings. I always overlook some things. There are just too many variables in play.

**Comment by leolivier** [comment]
Very glad it helped, @Diman0 !
 I'll have a look at your ci file version next weekend and restart from it to see how I can add the multiarch things 
I'll keep you posted in this thread

**Comment by Diman0** [comment]
Sounds good. However I think it might be better to focus on a workflow file that builds for arm only. If building for arm really takes 1.5 hours on github actions, then it is not feasible to combine this (create multiarch image). The build for the arm images should go through the same tests. Maybe a workflow file that creates the same images but with -arm appended to the tag. E.g.
- mailu/admin:latest-arm
- mailu/admin:master-arm
- mailu/admin:1.9-arm
- mailu/admin:1.9.22-arm

So the steps for calculating MAILU_VERSION and PINNED_MAILU_VERSION can append -arm.

I think in the beginning we will create a workflow file that builds for arm whenever something is pushed on
- master
- branch x.y (e.g. 1.9)

That way the main workflow (CI.yml) can be completed without issues. If something is merged, then the workflow is kicked off for building the the arm images. The workflow for the arm image can be almost the same. The main difference will be the target platform for buildx and that -arm must be appended to the calculated tags. So x hours after something is merged on branch master/x.y (1.9), the arm images should be available as well.

**Comment by leolivier** [comment]
Fully agree @Diman0

**Comment by leolivier** [comment]
Hi @Diman0 
I totally missed the set *.cache-from=type=gha,scope=build-xxx in the test and deploy jobs which actually is the right way to use the cached version and get rid of ghcr.io I was looking for 👍 
There probably might be a way to avoid the repetition of cache names by reusing the matrix built in the target job just as for builds.
Something like
```
   set *.cache-from=type=gha,scope=build-${{ fromJson(needs.targets.outputs.matrix) }}
```

Also, looking at your CI file (link above) I'm wondering why you still use in different jobs the step:
```
      - name: setup builder instance
        run: docker buildx create --use
```
although you have the buildx
```
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
```
which in my opinion already does that...
At least, I didn't need that in my CI tests.

Anyway, the CI file is way more elegant and simple now... Great!

Coming back on what you said above: if we have different tags for arm and non arm versions, we won't totally achieve the multiarch goal. Obviously, the main goal to have arm images will be achieved but not in one single image...
On specific occasions (push to master or branch x.y) and once we are sure amd version is tested ok, we could on the fly build the full multiarch image (amd+armv7+arm64) and tag it with the "usual" tag (w/o arm), what do you think?
It would only be triggering the same CI file with a different set of platforms, I don't know if this is possible to express that...

**Comment by leolivier** [comment]
Also, I think the 'time' management in the test is not finished, you set it in the matrix but don't use it afterward (or did I miss something?)

**Comment by Diman0** [comment]
> Also, I think the 'time' management in the test is not finished, you set it in the matrix but don't use it afterward (or did I miss something?)

Correct. I will correct this. It (Matrix.Time) should be used instead of 3 on line 
https://github.com/Diman0/Mailu_Fork/blob/c1a113382bd9140708f937b9887eaa0fd40a9237/.github/workflows/CI.yml#L233

I will also look into adding the possibility for using parameters/arguments (for when you manually trigger the build). It would nice if you could state what docker-org to use and what architecture when triggering the workflow manually.


>  Also, looking at your CI file (link above) I'm wondering why you still use in different jobs the step:

By default `docker buildx bake` uses docker as build engine. When docker is used it is **not** supported to use multiple cache.to and/or cache.from as we use. When looking online, I saw that an easy workaround is to start a new docker buildx instance using `docker buildx create --use` before the bake command. Possibly this is also possible with a certain parameter for the setup buildx action or the bake-and-push action, but I'm not familiar with these actions.

>  if we have different tags for arm and non arm versions, we won't totally achieve the multiarch goal. Obviously, the main goal to have arm images will be achieved but not in one single image...
On specific occasions (push to master or branch x.y) and once we are sure amd version is tested ok, we could on the fly build the full multiarch image (amd+armv7+arm64) and tag it with the "usual" tag (w/o arm), what do you think?

The problem with this, is that this will still fail if there is an arm-specific issue. Even though the PR was approved, all tests in the context of the PR (the original bors try and bors r+ (test and merge)) went fine. The images are not pushed to docker. the result is that we have no new images at all due an arm-related issue. If we would follow this path, then we should build and test for both amd+arm7+arm64 in the PR.

To my understanding you can only have 1 image with a specific tag in a docker repo. You cannot have a single arch image and a multiarch image both with the same tag (e.g. admin:1.9). First building and pushing for the single arch (amd) and then also try  to build and push the multiarch image for the same tag is not an option. This would introduce a time window where the multiarch image is not available, and people using arm have no images available. Even worse is if the arm build would fail in this scenario. This is also not an option.

Those are the possible scenarios I could think of when thinking about building multi-arch images. Correct if I'm wrong.

That is why I suggested using a separate arm tag. If the build for arm fails, then the previous arm image is still available. If the build for arm fails, then this has no influence on the main x64 images.

**Comment by leolivier** [comment]
>  It (Matrix.Time) should be used instead of 3

Yeah, it was what I supposed :)

> When docker is used it is not supported to use multiple cache.to and/or cache.from as we use.

Weird as the cache was working for me even w/o this `docker buildx create --use` step. Maybe it worked only inside the job but not for subsequent ones (as I didn't rebuild in the test job)...

For multiarch, I'm afraid you're right on all the points you mentioned. I'll try to find another solution but meanwhile having 2 different tags for arm and non-arm is the only solution I see, agreed...

**Comment by leolivier** [comment]
Actually, the real point is " this will still fail if there is an arm-specific issue" and my experience shows that we have to make slight tweaks in the build for arm specific issues, specifically, I need to install special packages like this for podop:
```
--- ../Mailu_Fork/core/dovecot/Dockerfile
+++ core/dovecot/Dockerfile
@@ -15,7 +15,9 @@
 RUN pip3 install socrate==0.2.0

 # Shared layer between dovecot and postfix
-RUN pip3 install "podop>0.2.5"
+RUN apk add --no-cache --virtual .build-deps gcc musl-dev python3-dev \
+  && pip3 install "podop>0.2.5" \
+  && apk del .build-deps

 # Image specific layers under this line
 RUN apk add --no-cache \
--- ../Mailu_Fork/core/postfix/Dockerfile
+++ core/postfix/Dockerfile
@@ -16,7 +16,9 @@
 RUN pip3 install socrate==0.2.0

 # Shared layer between dovecot and postfix
-RUN pip3 install "podop>0.2.5"
+RUN apk add --no-cache --virtual .build-deps gcc musl-dev python3-dev \
+  && pip3 install "podop>0.2.5" \
+  && apk del .build-deps
```
I tested this with amd64 builds and it's working so useless to create specific Dockerfile versions for ARM versions in my opinion...

**Comment by leolivier** [comment]
Back to the docker buildx create, I confirm the setup-buildx-action already does it:
![image](https://user-images.githubusercontent.com/4014752/182037634-743f9b44-d639-4245-b079-5e66c760a6f5.png)
so you can safely remove it from your steps...

**Comment by leolivier** [comment]
For reusing workflows: https://docs.github.com/en/actions/using-workflows/reusing-workflows 
The existing CI.yml file should be changed into a reusable workflow with the rights params (ie ARM='' or '-arm' and PLATFORMS=linux/amd64 or linux/armv7,linux/arm64 depending on what we build) and the computed MAILU_VERSION and PINNED_MAILU_VERSION are appended with ${{ env.ARM }} and linux/amd64 is replaced by $ {{ env.PLATFORMS }}
Then we create 2 caller workflows, one for non-arm and one for arm which calls this workflow with the right params and the right triggers...

**Comment by Diman0** [comment]
> Back to the docker buildx create, I confirm the setup-buildx-action already does it:

It shows the problem. It uses the docker driver. The docker driver does not support multiple cache-from/cache-to arguments. If this setup-buildx-action action allows to set the driver to a different driver, then we can indeed remove the addition `docker buildx create --set` step. I will check the action documentation. I cannot imagine that we cannot set a different driver via this action.

> For reusing workflows: https://docs.github.com/en/actions/using-workflows/reusing-workflows
.......

I agree. Having one reusable workflow is the preferred way. I will implement this.

**Comment by leolivier** [comment]
I had a look at the latest version of the CI files, wow, looks really great!
Everything solved, I think, except maybe the specific arm issues in Dockerfiles listed above (did you manage to build arm versions w/o that?).
Also, if the arm images are now built in standard, you should remove the build_arm.sh script and all the things related to that (qemu, arch related things, ...) in Dockerfiles that are not needed anymore. You can look at my version of these files to see the cleaning done.

Anyway, good job!

**Comment by leolivier** [comment]
Actually, looking twice, you still didn't change 3 by matrix.time and the docker buildx create step has not been removed 😇

**Comment by Diman0** [comment]
I did make these changes. I removed it by mistake. It was probably undone when I made changes to switch to a reusable workflow.

I have renamed the files. Latest files are here::
https://github.com/Diman0/Mailu_Fork/tree/master/.github/workflows
Latest shared workflow:
https://github.com/Diman0/Mailu_Fork/blob/master/.github/workflows/build_test_deploy.yml

I made the necessary changes for building arm:
https://github.com/Diman0/Mailu_Fork/actions/runs/2780574905
Currently the workflow is running. All images that do not require compilation finished. Admin/Dovecot/Postfix are still building. I hope the workflow will finish successfully.

**Comment by Diman0** [comment]
It finished successfully!
https://github.com/Diman0/Mailu_Fork/actions/runs/2781548578
https://hub.docker.com/layers/263974124/diman/postfix/master-arm/images/sha256-4f8089f8ab100c7a3e41a2ddde4156c841e712c936b181c81d4ac99a409ea290?context=repo

My repo has images with architecture arm64 and armv7. Last finishing touch is that I must update build.hcl to exclude commit-hash-arm as tag. 

Can you test on your ARM hardware with docker org diman and tag master-arm (e.g. diman/admin:master-arm)?
I'd like to know if the images start at all and if basic functionality works (like logging in admin or sending/receiving email).

**Comment by leolivier** [comment]
I didn't have time to test today, sorry, I'll try tomorrow morning

**Comment by leolivier** [comment]
I finally found some time to test tonight and .... drum roll... **it's working !!!**
I tested the following things:
- send an email
- receive an email
- connect to admin
- rainloop
All other containers I'm using (rspamd, clamav, fetchmail & resolver) are started and healthy but not tested specifically...

**Comment by Diman0** [comment]
As expected. If it can be built, you would not expect the software not being able to run. But since there are not automatic tests it had to be verified. 

Thank you for the verification. Now I can include arm builds as well in my PR for switching to buildx.

**Comment by leolivier** [comment]
Well, actually, I have experienced several troubles with built pieces of mailu in the past: images which didn't start or didn't work properly eg when I tried to use prebuilt python packages for Arm from pypi.org instead of recompiling them from scratch (building time reduced from 1hr to 20mns)...
Anyway, it works for what I tried, so let's go!

**Comment by leolivier** [comment]
Hi Diman0,
sad news, I upgraded to the latest master-arm "official beta" version and there is an issue in admin, actually the same I encountered with my own version after version 1.9.25. I don't understand why it didn't appear in previous tests. In the admin logs, I see the traces below and it doesn't start...
```
Error: While importing 'mailu', an ImportError was raised.
Usage: flask [OPTIONS] COMMAND [ARGS]...
Try 'flask --help' for help.
Error: No such command 'mailu'.
Usage: flask db upgrade [OPTIONS] [REVISION]
Try 'flask db upgrade --help' for help.
Error: While importing 'mailu', an ImportError was raised.
Error: While importing 'mailu', an ImportError was raised.
Usage: flask [OPTIONS] COMMAND [ARGS]...
Try 'flask --help' for help.
Error: No such command 'mailu'.
Traceback (most recent call last):
  File "/usr/bin/gunicorn", line 8, in <module>
    sys.exit(run())
  File "/usr/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 67, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/usr/lib/python3.9/site-packages/gunicorn/app/base.py", line 231, in run
    super().run()
  File "/usr/lib/python3.9/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/usr/lib/python3.9/site-packages/gunicorn/arbiter.py", line 58, in __init__
    self.setup(app)
  File "/usr/lib/python3.9/site-packages/gunicorn/arbiter.py", line 118, in setup
    self.app.wsgi()
  File "/usr/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/app/mailu/__init__.py", line 7, in <module>
    from mailu import utils, debug, models, manage, configuration
  File "/app/mailu/models.py", line 30, in <module>
    from mailu import dkim, utils
  File "/app/mailu/dkim.py", line 5, in <module>
    from OpenSSL import crypto
  File "/usr/lib/python3.9/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/lib/python3.9/site-packages/OpenSSL/crypto.py", line 14, in <module>
    from cryptography import utils, x509
  File "/usr/lib/python3.9/site-packages/cryptography/x509/__init__.py", line 6, in <module>
    from cryptography.x509 import certificate_transparency
  File "/usr/lib/python3.9/site-packages/cryptography/x509/certificate_transparency.py", line 10, in <module>
    from cryptography.hazmat.bindings._rust import x509 as rust_x509
ImportError: Error loading shared library ld-linux-armhf.so.3: No such file or directory (needed by /usr/lib/python3.9/site-packages/cryptography/hazmat/bindings/_rust.abi3.so)
```

So, the issue is that ld-linux-armhf.so is not provided by alpine if I get it well... 
As I said I have this issue since 1.9.26 with my own build and I previously investigated on that. I tried forcing install of this lib in the image (manually) but then I had other issues and I had to give up...

**Comment by leolivier** [comment]
I switched back to your 1.11-arm image and it's working, I tried your master-arm image and it does not work. Strange...

**Comment by leolivier** [comment]
I think I found the issue: I don't know how but you ended using part of my own Dockerfile for your build in master-arm.
I can see in the image that you used the command 
```
RUN |1 VERSION=1673d78fb0358f2fc3309a92312d9db18db6f27f-arm /bin/sh -c set -eu  && apk add --no-cache libressl curl postgresql-libs mariadb-connector-c  && pip install --no-cache-dir --extra-index-url=https://www.piwheels.org/simple -r requirements.txt --only-binary=:all: --no-binary=Flask-bootstrap,PyYAML,SQLAlchemy  || ( apk add --no-cache --virtual build-dep libressl-dev libffi-dev python3-dev build-base postgresql-dev mariadb-connector-c-dev cargo  && pip install --upgrade pip  && pip install -r requirements.txt  && apk del --no-cache build-dep ) # buildkit
```
which is using piweels.org for avoiding to build the python wheels. This is something i tied to use to gain a lot of time during the build, but this does not work. The pywheels package are working **only** on raspbian, not on alpine...

This is typically the kind of things I told you above on things that build but don't run at the end...


This use of pywheels does not appear in the 1.11-arm version...
