### ISSUE TITLE
Feature Request: Add xapian compact script, options, documentation

### ISSUE THREAD

**Issue by macdabby** [Mailu/Mailu#2390]
### Environment
 - [X] docker-compose
 - [ ] kubernetes
 - [ ] docker swarm

### Versions
1.9

## Description
Feature Request

Xapian (full text search) databases can grow to be huge, in my case some mail accounts which have 10gb of mail have xabian databases of 5gb. Xapian has a program called xapian-compact that will make them smaller, some of my databases were reduced by 50% after running this. it would be great to have a command that we could run that would filter through all the mail accounts and compact the xapian databases. i was able to do this running inside of docker but it's just a complex one liner and doesn't do all the mail accounts, only one at a time. A full compact script could be configured to run automatically via cron or manually.

```
for file in ./* ; do xapian-compact $file "${file}-new" && chown -R mail:mail "${file}-new" && mv $file "${file}-old" && mv "${file}-new" $file && rm -rf "${file}-old"; done
```

Also, xapain doesn't appear to be documented much, although there should be options to disable indexing of certain binary files like email attachments, and possibly even filter by type. for example, maybe scanning PDFs is good but scanning JPGs and MOVs is not. I think this depends mostly on the imap server configuration and how it sends data to xapian.

Example compacting rations (first column is new old size, second column is new size)
![image](https://user-images.githubusercontent.com/176957/180447091-454240cf-b770-4da4-9241-115d3e93f9d6.png)

**Comment by codingoverdrive** [comment]
Completely agree that an automatic compaction script should be included in the distribution. 

I have the situation where a user's emails disk usage is not that large but the xapian indexes are HUGE. See this real=life example:

`
$ du -m --max-depth=1 /mailu/mail/someuser\@domain.com/
14	/mailu/mail/someuser@domain.com/.Drafts
924	/mailu/mail/someuser@domain.com/.Trash
392	/mailu/mail/someuser@domain.com/cur
1	/mailu/mail/someuser@domain.com/tmp
1	/mailu/mail/someuser@domain.com/.Emailed Contacts
294	/mailu/mail/someuser@domain.com/.Sent
3243	/mailu/mail/someuser@domain.com/xapian-indexes
1	/mailu/mail/someuser@domain.com/.Archives.2012
3	/mailu/mail/someuser@domain.com/.Junk
1	/mailu/mail/someuser@domain.com/.Archives.2010
1	/mailu/mail/someuser@domain.com/.Archives
1	/mailu/mail/someuser@domain.com/.Archives.2013
1	/mailu/mail/someuser@domain.com/.Contacts
407	/mailu/mail/someuser@domain.com/.Spambox
1	/mailu/mail/someuser@domain.com/new
1	/mailu/mail/someuser@domain.com/.Chats
2	/mailu/mail/someuser@domain.com/.Archives.2018
5278	/mailu/mail/someuser@domain.com/
`

**Comment by codingoverdrive** [comment]
There's an alternate way of compacting the xapian indexes

On the IMAP container execute the following two commands (per mailbox)

```
# this wipes out the index files
doveadm fts rescan -u john.doe@domain.com

# and this rebuilds them for the INBOX
doveadm index -u John.doe@domain.com -q INBOX
```

You can get a back shell on the IMAP container using the following command:

`docker-compose exec imap bash`

(notice how you use the service name and not the container name with docker-compose`

Now I just need to find a way of generating all the email addresses on my server and running those two command for each user

**Comment by macdabby** [comment]
Thanks for that! I attempted to run this on an account with 9gb of mail. immediately after running, the index dropped to 3.6gb, but within another day, the index was back to 11gb, which is about where it started. 

Also according to this you can just use -A to do all users: https://wiki.dovecot.org/Tools/Doveadm/FTS

**Comment by codingoverdrive** [comment]
I tried the `doveadm fts rescan -A` command to compact all mailbox indexes but  it didn't seem to work for me which is why I ran it on some of the worst mailboxes

It's worrying that the indexes grew back to their original size on you within a day again.

I think this issue qualifies as a bug and hopefully we can get some kind of fix baked in

**Comment by ghostwheel42** [comment]
podop does not support iteration over all accounts (-A) yet. 
But I think I'll implement it soon.

**Comment by fahrenheit9** [comment]
Thanks, I had an issue with an email account which has arround 500M of mails but 362G of xapian index ... taking all my disk space.

Executing the 2 commands provided by [codingoverdrive](https://github.com/codingoverdrive) reduced the index to 28K. 

I hope it won't repeat in the futur.

**Comment by nextgens** [comment]
Running the current master, I can confirm that ``doveadm fts rescan -A`` nukes all the indexes and ``doveadm index -Aq '*'`` rebuilds them.

I have played with xapian-compact and found that it's not much better than re-starting from scratch; YMMV

**Comment by nike7o0** [comment]
This is my config in dovecot override, i am no indexing attachments. Still not sure if this is the best option.

plugin {
  quota = count:User quota
  quota_vsizes = yes
  quota_clone_dict = proxy:/tmp/podop.socket:quota

  fts = xapian
  fts_xapian = partial=2 full=30 verbose=0 lowmemory=512MB attachments=0
  fts_autoindex = yes
  fts_enforced = yes
  fts_autoindex_exclude = \Trash
  fts_autoindex_exclude2 = \Junk
  fts_autoindex_max_recent_msgs = 999


}

**Comment by nextgens** [comment]
I've done some work on this in #2972 

Can you give it a test please?

Be careful, this is with master (and not stable): do backups or better yet try on a non-production environment
```
export MAILU_VERSION='pr-2972'
docker compose up -d
```
