### ISSUE TITLE
Docker container crashes if IPv6 is disabled at the system level.

### ISSUE THREAD

**Issue by sosed213** [Mailu/Mailu#2392]
If listen [::] is found somewhere in the configs, but IPv6 is disabled at the host system level and in the docker, then the process crashes, and, accordingly, the docker container also crashes.

This can be manually climbed into each container, corrected, but it is not very convenient.

docker exec mailu_front_1 sed -i '/listen \[/d' /conf/nginx.conf
docker exec mailu_front_1 sed -i '/listen \[/d' /etc/nginx/nginx.conf
docker exec mailu_front_1 sed -i '/listen \[/d' /etc/nginx/http.d/default.conf
docker restart mailu_front_1

docker restart mailu_webdav_1 && docker exec -it mailu_webdav_1 sed -i 's/hosts =.*\[::\].*/hosts = 0.0.0.0:5232/g' /radicale.conf && docker restart mailu_webdav_1

Can you add a container launch option to remove listen [::] from configs?

**Comment by nextgens** [comment]
We were talking about it on #2272 ... other users are lobbying for the exact opposite on #1789

**Comment by ghostwheel42** [comment]
@sosed213 Hi. I'd like to test if my pr fixes this, but I'm unable to recreate the error. 
Weißt do you mean by "IPv6 is disabled at the host system level". 
How was it disabled?

**Comment by sosed213** [comment]
Hi!


#Add to /etc/sysctl.conf

# IPv6 disabled
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1

# update
sudo sysctl -p

**Comment by ghostwheel42** [comment]
@sosed213 Thanks, I already did this but this doesn't stop the current docker version to have ipv6 enabled inside the containers.
```
$ sysctl -a | grep disable_ipv6
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.eth0.disable_ipv6 = 0
net.ipv6.conf.lo.disable_ipv6 = 0
```
Binding to `[::]:port` therefore works inside the container and we wouldn't need to change the way Mailu binds the ports.
I've added the changes you suggested to #2630 nevertheless just to be sure.
