### ISSUE TITLE
Alternative domain of unicode domain results in "Bad adress syntax"

### ISSUE THREAD

**Issue by KingOfDog** [Mailu/Mailu#2393]
### Environment
 - [x] docker-compose
 - ~~[ ] kubernetes~~
 - ~~[ ] docker swarm~~

### Versions
Version 1.9

## Description
My setup includes a domain that has Unicode characters (i.e. German umlauts), e.g. `exämple.com`. There is an alternative domain that provides a 'fallback' so users can also send emails to `example.com`. The domain has an account `mail@exämple.com` which is able to receive emails as expected. When sending an email to `mail@example.com`, the sender receives an error message provided with the Postfix error message:

```
<mail@ex??mple.com> (expanded from <mail@example.com>): bad address syntax
```

I suspect the cause might be that when looking up the alternative domain, the unicode version is provided to Postfix instead of the IDNA code (`xn--exmple-cua.com`).

It should be noted that my setup doesn't have a top-level domain with an umlaut but instead a subdomain with an umlaut (e.g. `ümlaut.example.com`). I didn't have a way to test it using a domain that contains any unicode characters itself.

## Replication Steps
1. Create a new mail domain containing an umlaut (e.g. `exämple.com`)
2. Add an account to this domain
3. Create an alternative for this domain that doesn't contain any umlaut (e.g. `example.com`)
4. Send an email to the account using the alternative domain

## Expected behaviour
The email sent to the alternative domain should be received without any error and should appear in the account's inbox (which has a primary domain with an umlaut).

## Logs

Postfix logs:

````markdown
smtp_1       | INFO:root:Connect
smtp_1       | DEBUG:root:Received bytearray(b'sendermap sender@email.com')
smtp_1       | DEBUG:root:Request sendermap/sender@email.com
smtp_1       | DEBUG:root:Table get sender@email.com
smtp_1       | DEBUG:root:Replying b'NOTFOUND '
smtp_1       | DEBUG:root:Received bytearray(b'recipientmap recipient@no-umlaut-alternative.example.com')
smtp_1       | DEBUG:root:Request recipientmap/recipient@no-umlaut-alternative.example.com
smtp_1       | DEBUG:root:Table get recipient@no-umlaut-alternative.example.com
smtp_1       | DEBUG:root:Replying b'NOTFOUND '
smtp_1       | DEBUG:root:Received bytearray(b'alias recipient@no-umlaut-alternative.example.com')
smtp_1       | DEBUG:root:Request alias/recipient@no-umlaut-alternative.example.com
smtp_1       | DEBUG:root:Table get recipient@no-umlaut-alternative.example.com
smtp_1       | DEBUG:root:Table get recipient@no-umlaut-alternative.example.com is recipient@umläut.example.com
smtp_1       | DEBUG:root:Replying b'OK recipient@uml\xc3\xa4ut.example.com'
smtp_1       | DEBUG:root:Received bytearray(b'alias recipient@uml\xc3\xa4ut.example.com')
smtp_1       | DEBUG:root:Request alias/recipient@umläut.example.com
smtp_1       | DEBUG:root:Table get recipient@umläut.example.com
smtp_1       | DEBUG:root:Table get recipient@umläut.example.com is recipient@umläut.example.com
smtp_1       | DEBUG:root:Replying b'OK recipient@uml\xc3\xa4ut.example.com'
smtp_1       | 2022-07-26T16:25:19.988453+00:00 dc2c0dc34192 postfix/cleanup[3824]: E3B23192FB03: message-id=<####@example.com>
smtp_1       | 2022-07-26T16:25:20.081615+00:00 dc2c0dc34192 postfix/qmgr[339]: E3B23192FB03: from=<sender@email.com>, size=281, nrcpt=1 (queue active)
smtp_1       | 2022-07-26T16:25:20.083187+00:00 dc2c0dc34192 postfix/smtpd[3821]: disconnect from mailu_webmail_1.mailu_default[192.168.203.7] ehlo=2 xclient=0/1 mail=1 rcpt=1 data=1 quit=1 commands=6/7
smtp_1       | 2022-07-26T16:25:20.103349+00:00 dc2c0dc34192 postfix/error[3825]: E3B23192FB03: to=<recipient@uml??ut.example.com>, orig_to=<recipient@no-umlaut-alternative.example.com>, relay=none, delay=0.36, delays=0.34/0.01/0/0.01, dsn=5.1.3, status=bounced (bad address syntax)
````

Error message provided by Postfix:

```
This is the mail system at host mail.example.com.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to postmaster.

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<recipient@uml??ut.example.com> (expanded from
    <[recipient@no-umlaut-alternative.example.com](mailto:recipient@no-umlaut-alternative.example.com)>): bad address syntax
Reporting-MTA: dns; mail.example.com
X-Postfix-Queue-ID: E3B23192FB03
X-Postfix-Sender: rfc822; [sender@email.com](mailto:sender@email.com)
Arrival-Date: Tue, 26 Jul 2022 16:25:19 +0000 (UTC)

Final-Recipient: rfc822; recipient@uml??ut.example.com
Original-Recipient: rfc822;[recipient@umlaut.example.com](mailto:recipient@umlaut.example.com)
Action: failed
Status: 5.1.3
Diagnostic-Code: X-Postfix; bad address syntax
```

**Comment by Diman0** [comment]
This should work. IDNA encoding should already be used internally. Apparently there is an edge case.

Do you also receive this error if you send an email to the domain with the umlaut?
If you remove the alternative and send the email to the domain with the umlaut, do you still receive an error?

**Comment by ghostwheel42** [comment]
This can be fixed in https://github.com/Mailu/Mailu/blob/e50f6c58c0f81f639295033463584dab92f16808/core/admin/mailu/internal/views/postfix.py#L32
The return value needs to be encoded as @KingOfDog suggested.
I can prepare a PR, but I want to check the use of resolve_destination first, as it seems to return None, an address or a list of addresses - which would lead to nasty errors when joining with "," as the postfix_alias_map function does. 
https://github.com/Mailu/Mailu/blob/e50f6c58c0f81f639295033463584dab92f16808/core/admin/mailu/models.py#L436

**Comment by Diman0** [comment]
That would be great. I've assigned it to you so it is clear you will work on this whenever you have time. This basically blocks people from using domains with a special character and alternative with normal notation.
