### ISSUE TITLE
setup.mailu.io: add server validation for configuration?

### ISSUE THREAD

**Issue by tarwirdur** [Mailu/Mailu#2396]
## Description
I'm using umatrix that block scripts from third-party domains.
So when I open https://setup.mailu.io, jquery from third party CDN was blocked, but web page looks good and I did not notice anything suspicious.

But without JQuery there is no input for WEB_ADMIN variable. And in result mailu.env is incorrect. Example: https://setup.mailu.io/master/file/048a14d0-9220-4468-8ac6-2b9bf524ff18/mailu.env
```
ADMIN=true
...
WEB_ADMIN=
```
So backend could generate unhealthy configuration without any notice.

**Comment by CryptosWORLD** [comment]
maybe is related 
https://github.com/Mailu/Mailu/issues/2710
