### ISSUE TITLE
Resolve build/push issue of CI workflow

### ISSUE THREAD

**Issue by Diman0** [Mailu/Mailu#2398]
The CI workflow failed to push all the images when the snappymail PR was merged. Not all images for tag master are updated. At least the snappymail image and setup image are not uploaded.
See https://github.com/Mailu/Mailu/runs/7564825204?check_suite_focus=true#step:12:49

```
Login Succeeded
Pushing front (***/nginx:master)...
The push refers to repository [docker.io/***/nginx]
master: digest: sha256:e6f3798de698272b7a14074cc0388c2a19d8f29824964f03fe60a1e15989a00b size: 2201
...
Pushing snappymail (***/snappymail:master)...
The push refers to repository [docker.io/***/snappymail]
denied: requested access to the resource is denied
```

Maybe the mailuci docker account only has permissions to update images, but not upload new images?

**Comment by Diman0** [comment]
I'm working on this, and I'm making progress.

**Comment by kaiyou** [comment]
For future reference, I just transferred ownership of the Docker hub `mailu` organization to @Diman0.

**Comment by Diman0** [comment]
I got ownership of the docker mailu organization. 
I think I was able to fix the issues. The latest master images are all built and pushed to the mailu docker repo now.
