### ISSUE TITLE
Add customisation for dmarc values

### ISSUE THREAD

**Issue by Xumeiquer** [Mailu/Mailu#240]
It would be really nice to add custom values for rua field in dmarc entry as well as it would be really interesting to add ruf field.

**Comment by kaiyou** [comment]
Well, the DMARC entry is only an indication and we currently have no automatic mechanism for handling reports, so I guess that should be up to the admin of every server.

**Comment by kaiyou** [comment]
I just tested your pull request, and this is actually nice, for domains that are not managed by the admin itself. Thank you for contributing.

**Comment by Xumeiquer** [comment]
Yeah, this can be used with aliasses, for example.

**Comment by kaiyou** [comment]
I am okay with merging this if you improve the template bit as suggested to avoid unnecessary complexity when maintaining.

**Comment by kaiyou** [comment]
This was just merge into `master`, thank you so much!
