### ISSUE TITLE
Per-user Activity Logs in Admin UI

### ISSUE THREAD

**Issue by H-MAli** [Mailu/Mailu#2400]
As a system administrator, it's not rare to be asked whether a specific email has been sent, delivered, received, etc.

It would be a great addition to have if we can have a section in Admin UI's Users List section (/admin/user/list/DOMAIN) listing each user's sending and receiving activity.

What I believe would be useful to have for each mail entry:

- Email title
- Senders and recipients
- Final status (delivered, deferred, rejected, etc.)
- Spam rating
- And some more info as the ones found in Antispam/History section

**Comment by Diman0** [comment]
If you have the need to have this information logged. You can enable postfix logging. See this link for more info https://mailu.io/1.9/configuration.html#mail-log-settings. Postfix also logs the rspamd result (for sending and receiving email).
