### ISSUE TITLE
Feature Request  - Issue #1319 Should be Selectable Key Length not Forced 2048 for DKIM

### ISSUE THREAD

**Issue by jamesarbrown** [Mailu/Mailu#2401]
Issue #1319 changed the key length to 2048, but our ISP said they could not insert such a long key even using a split method as they use update scripts and the script is the issue. not the DNS

It would be great if the /admin page can have 
Button - Delete Existing Private Key (as re-generate keys does not appear to regenerate the /dkim/domain.tld.dkim.key), I had to go into the Kubernetes pod and delete.
Selection of key length, maybe even just two key lengths 1024 or 2048 which then is pulled in the dkim.py script

**Comment by nextgens** [comment]
IMHO the solution for this is #2050 (moving away from RSA)
