### ISSUE TITLE
Can't launch rspamd and send mails

### ISSUE THREAD

**Issue by ImAARIX** [Mailu/Mailu#2411]
### Environment
 - [x] docker-compose
 - [ ] kubernetes
 - [ ] docker swarm

### Versions
Mailu version 1.9

## Description
When I launch the stack with docker-compose, everything is starting normally, but the mailu antispam keep crashing.

## Replication Steps
Just launching the stack

## Logs
The only report that I have is a comment on docker logs :
````markdown
```
antispam_1    | 2022-08-07 00:41:18 #1(main) <bbba0c>; main; main: rspamd 3.2 is loading configuration, build id: release
mail_antispam_1 exited with code 132
```
````
![WindowsTerminal_gm56QF9OKn](https://user-images.githubusercontent.com/34407239/183270339-b5f5c9f1-965a-4d99-8d09-f2b080498159.png)

Is there anything that I can do to start this container (or to tell postfix to not use the antispam)?

**Comment by arnaudluti** [comment]
Same issue here - latest mailu stack

**Comment by Anaerin** [comment]
Same error here. Exit Code 132 is "Terminated, illegal instruction". Several people have reported getting that error on Raspberry Pis or when AVX instructions are called on a non-AVX system. I know my system doesn't have AVX, as it's a Core2Duo.

**Comment by routmoute** [comment]
same, in core 2 duo e8400. no one know fix or workaround ?
thank you.

**Comment by nextgens** [comment]
That's a processor from 2008!

Use an older version of Mailu :/

**Comment by routmoute** [comment]
okok, thank you
