### ISSUE TITLE
SASL login name rejected: You are sending too many emails too fast.

### ISSUE THREAD

**Issue by liusijun** [Mailu/Mailu#2416]
Send mail through STMP. If you send too many messages, an error will be returned.
SASL login name rejected: You are sending too many emails too fast.
Can this restriction be lifted? Thank you very much.

**Comment by nextgens** [comment]
See ```MESSAGE_RATELIMIT``` and ```MESSAGE_RATELIMIT_EXEMPTION``` on https://mailu.io/master/configuration.html#mail-settings

**Comment by matarrsil** [comment]
I’m having same issues
