### ISSUE TITLE
Default docker-compose.yml mounts /var/run/docker.sock

### ISSUE THREAD

**Issue by svengo** [Mailu/Mailu#242]
I am new to Mailu and started with the first setup today. 

The default [docker-compose.yml](https://raw.githubusercontent.com/Mailu/Mailu/master/docker-compose.yml.dist) binds `/var/run/docker.sock` as volume for the admin service. Why is the mount needed? I'm running docker with [user namespaces](https://docs.docker.com/engine/security/userns-remap/) and don't want to run mailu as privileged container unless needed.

**Comment by Xumeiquer** [comment]
You can check the other container status on the admin panel, nothing else.

**Comment by svengo** [comment]
Thanks for the information!
