### ISSUE TITLE
Comparing Mailu to Roundcube

### ISSUE THREAD

**Issue by master3395** [Mailu/Mailu#2431]
Hello everyone.

This Mailu looks almost 100% identical to RoundCube.
What makes this better/worse than roundcube?

**Comment by Igortorrente** [comment]
Mailu is a mail solution. It includes SMTP server (postfix), IMAP/POP3 server (dovecot), spam filter (rspamd), the admin web and cli interface (Mailu-admin) and a (optionaly) web mail (Roundcube or snappymail).
So Mailu uses Roundcube as a web mail.
