### ISSUE TITLE
using piwheels.org python wheels in arm images fails at runtime

### ISSUE THREAD

**Issue by leolivier** [Mailu/Mailu#2439]
Specifically for @Diman0 

As described in https://github.com/Mailu/Mailu/issues/2383#issuecomment-1230552614 and in https://github.com/Mailu/Mailu/issues/1973#issuecomment-1232678585 the master-arm versions of postfix and admin (and maybe others?) images are using the wheels from piwheels.org in an attempt to drastically cut the build time for arm.
Unfortunately, this does not work at runtime as said in https://github.com/piwheels/packages/issues/312 (piwheels does support only Rasbian, not alpine)
The previous versions (namely diman/xxx:1.11-arm) are working well.

see eg in postfix Dockerfile:
`/bin/sh -c pip install --no-cache-dir --extra-index-url=https://www.piwheels.org/simple --only-binary=:all: postfix-mta-sts-resolver==1.0.1 || (apk add --no-cache --virtual .build-deps gcc musl-dev python3-dev py3-wheel libffi-dev   && pip3 install postfix-mta-sts-resolver==1.0.1   && apk del .build-deps )`

or in admin Dockerfile:
`/bin/sh -c set -eu  && apk add --no-cache libressl curl postgresql-libs mariadb-connector-c  && pip install --no-cache-dir --extra-index-url=https://www.piwheels.org/simple -r requirements.txt --only-binary=:all: --no-binary=Flask-bootstrap,PyYAML,SQLAlchemy  || ( apk add --no-cache --virtual build-dep libressl-dev libffi-dev python3-dev build-base postgresql-dev mariadb-connector-c-dev cargo  && pip install --upgrade pip  && pip install -r requirements.txt  && apk del --no-cache build-dep )` 

The result is that admin cannot start at all (see https://github.com/Mailu/Mailu/issues/2383#issuecomment-1230495806), and postfix starts but not the mta-sts daemon (see https://github.com/Mailu/Mailu/issues/1973#issuecomment-1232670764)

This also means that we definitely need to have:
1. some automated tests before publishing arm images. I understand github does not provide arm environments for testing but if needed, I think we can use local raspberry pies (eg with https://github.com/nektos/act or https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners) 
2. "fixed" tags allowing to come back to previous versions (only master-arm is currently published and replaced by new versions, so no fallback possible to a previous version)

**Comment by nextgens** [comment]
I've proposed on #mailu-dev that we run/precompile on a separate repository. It could be either just the python wheels or a docker image... that we would publish... and that this repository would use; the idea being that we hardly ever change the dependencies (anyway we could have two branches, one that pin versions and what that doesn't) and they could be updated asynchronously (maybe using a daily cronjob) to the main build process.

On tags, the idea is that once it's out of beta (and tagged as releases) rollbacks will be possible; until then it's something no one should use except those that want to make it work. We don't want people to run different flavours of master; if you elect to go for bleeding edge, that's what you get.

**Comment by Diman0** [comment]
For now we will undo the move to the usage of wheels. At a later moment we can investigate how we want to precompile all wheels.

**Comment by nextgens** [comment]
I wouldn't remove everything, just remove the parameter with the URL to piwheels... so that we're only building them for ARM and the x86_64 build remains fast.

**Comment by leolivier** [comment]
@nextgens I understand this is still beta. And I fully agree to try to cut the build time, I tried the piwheels trick myself and told @Diman0 it didn't work in the builx discussion a month ago (maybe not clearly enough though)
I also fully agree to build the wheels in a specific repo.
Nevertheless, what I don't get is how you want to manage the arm tests? Even in beta stage, I don't think we should have not tested versions with a master something tag.
That's why I proposed to try automating tests with local rasps. I didn't check yet if this can work on raspbian for Github but I already did that with Gitlab runners

**Comment by leolivier** [comment]
> I wouldn't remove everything, just remove the parameter with the URL to piwheels... so that we're only building them for ARM and the x86_64 build remains fast.
The standard build files worked so until the wheels are built in another repo, why not just rollback to that?

**Comment by nextgens** [comment]
> > I wouldn't remove everything, just remove the parameter with the URL to piwheels... so that we're only building them for ARM and the x86_64 build remains fast.
> 
> The standard build files worked so until the wheels are built in another repo, why not just rollback to that?

Because it would make the x86_64 build slower; the previous build files were not using the wheels properly AFAIC.

Check what I have proposed in #2440 out; if that works I suggest we go with that.

**Comment by Diman0** [comment]
`|| ( apk add --no-cache --virtual build-dep libressl-dev libffi-dev python3-dev build-base postgresql-dev mariadb-connector-c-dev cargo`
Does that part mean, only execute this if the previous part fails? Then I understand it and I will approve it

**Comment by Diman0** [comment]
Yes it does. It is the OR operator in bash. It is only executed if the left part fails

**Comment by leolivier** [comment]
I confirm #2440 (latest master-arm images) is working on my RPi (tested admin + send / receive an email)
