### ISSUE TITLE
FR: Remember login session in web interface (i.e. don't logout automatically after x minutes)

### ISSUE THREAD

**Issue by woj-tek** [Mailu/Mailu#2447]
## Before you open your issue
- [x] Check if no issue or pull-request for this already exists.
- [x] Check [documentation](https://mailu.io/master/) and [FAQ](https://mailu.io/master/faq.html). (Tip, use the search function on the documentation page)
- [x] You understand `Mailu` is made by volunteers in their **free time** — be conscise, civil and accept that delays can occur.
- [x] The title of the issue should be short and simple. It should contain specific terms related to the actual issue. Be specific while writing the title.

### Environment
 - [ ] docker-compose
 - [x] kubernetes
 - [ ] docker swarm

(though I think it's not dependend on any particular environment)

### Versions
(managed by fluxcd)
```
mailu-prod-mailu                      	0.3.3   	False    	True 	pulled 'mailu' chart with version '0.3.3'
```

Images (output of, `kubectl -n mailu-prod get pods -o jsonpath="{.items[*].spec.containers[*].image}"`, based on https://kubernetes.io/docs/tasks/access-application-cluster/list-all-running-container-images/... seems wrong though):
```
mailu/admin:1.9.26
mailu/clamav:1.9.26
mailu/dovecot:1.9.26
mailu/nginx:1.9.26
mailu/nginx:1.9.26
mailu/nginx:1.9.26
mailu/postfix:1.9.26
redis:5-alpine
mailu/roundcube:1.9.26
mailu/rspamd:1.9.26
```
As hashes (`kubectl get pods -o jsonpath="{.items[*].status.containerStatuses[*].imageID}" | tr -s '[[:space:]]' '\n' | sort | uniq -c`0:
```
      1 docker.io/library/redis@sha256:1c465cac273d3e0a63ca9896cb78eb75bad9c80e9a0b3ea0b5a0c6d1f12c3232
      1 docker.io/mailu/admin@sha256:321e84b2361a65d02aa0c47ddf63b7f048ee701f0b75a0069cda7e1757c84f96
      1 docker.io/mailu/clamav@sha256:d7a5a568fa858cd57a2c5305e172d40a8a32567216042d1a2be95332133490f2
      1 docker.io/mailu/dovecot@sha256:afe7dced133bd8152862bde2db29ff4eb60c67f25b3c9261df26e6af856acdd3
      3 docker.io/mailu/nginx@sha256:3972e5c7c1e893a8e94474204e52e98b84f5ed4bfd93b6561c11798be4585b7e
      1 docker.io/mailu/postfix@sha256:0ecf0e4a58323cb060993a96e709b950e56385be59b8d434983a04d555f692f3
      1 docker.io/mailu/roundcube@sha256:19e7fb5b960b55201fd7520077779a9a4ee71da32ca205f2117f4178deb0c971
      1 docker.io/mailu/rspamd@sha256:ed73261cb709cfcc718403202c3b588bbcf226179a880cb00440c017dfdf93c0
```

## Description
Currently, web ui (admin, webmail) automatically logs-out user after a couple of minutes of inactivity. It would be great if there were an option "Remember me on this computer" so each time I open webmail I would be automatically authenticated.

I search issues/PR for "remember session", "remember login", "sticky session" and so forth but I couldn't find anythig related (there were threads/topics about reworking [2FA] authentication but I think this one is somewhat different).

**Comment by nextgens** [comment]
Please start by reading the documentation. The two settings you are looking for are ``SESSION_TIMEOUT`` and ``PERMANENT_SESSION_LIFETIME``
https://mailu.io/1.9/configuration.html?highlight=session#advanced-settings

**Comment by woj-tek** [comment]
My bad, missed that when searching documentation (using search instead of checking sections).

Though, in case of k8s/helm chart it seems taht those options are not exposed (looking at https://github.com/Mailu/helm-charts/blob/eccf0342c81609c9b770205eb12c02683396f93a/mailu/templates/admin.yaml#L59-L173)? Would PR with additional env variables (`SESSION_TIMEOUT` and `PERMANENT_SESSION_LIFETIME`) be ok?

**Comment by nextgens** [comment]
I'm sorry but it's in the helm charts that this needs to be fixed.

There is already a ticket open for it: https://github.com/Mailu/helm-charts/issues/152 ... please send a PR to implement that instead :)

**Comment by woj-tek** [comment]
Yes yes, I'm aware that it has to be done in helm-charts (see the link above pointing to admin.yaml with list of variables that misses those env variables mentioned in the documentation. Thanks for pointing me to the PR :-)
