### ISSUE TITLE
Please add TLS config option for port 25

### ISSUE THREAD

**Issue by TerrapinSoftware** [Mailu/Mailu#2449]
We have to use securitymetrics.com for PCI compliance validation. These people complain about TLSv1 and TLSv1.1 being enabled for the STARTTLS command on port 25.

Can you, please, add an environment variable for the offered TLS versions in the front container for the server on port 25 so TLSv1 and TLSv1.1 can be turned off?

Right now, I help myself with a command in the YAML file:

```
front:
    ...
    command: ["/bin/sh", "-c", "
        /bin/sed -i 's/TLSv1 TLSv1.1 //' /conf/nginx.conf;
        /start.py
    "]
```

**Comment by TerrapinSoftware** [comment]
I cannot agree more. Specifially, https://www.immuniweb.com/ssl/ also checks for PCI compliance, and they do not have any problem with TLS 1.0/1.1. Out of curiosity, I have contacted them and asked for an explanation. I will be happy to post it here FYI.

The PR fixes that issue just fine, including warning text. Nice!

**Comment by TerrapinSoftware** [comment]
And here is the response from SecurityMetrics:

"To answer your question when it comes to PCI compliance, the entire network is in scope which is why the scanner checks for all ports. The use of old or misconfigured mail servers should not be put in place when it comes to PCI compliance, It is stated on the PCI Guideline that up to date protocols must be enabled with SSL Certificates in this current case it;s TLS 1.2 and TLS 1.3."

IMHO this is ridiculous; I post it here for reference purposes - it seems that others have the same problem.

**Comment by nextgens** [comment]
@TerrapinSoftware Please ask them why they do not flag that plaintext email delivery is possible.

Surely if TLS1.0 isn't good enough, plaintext shouldn't be either? ;)
