### ISSUE TITLE
not allowing POP3/IMAP leads to infinite loop in webmail

### ISSUE THREAD

**Issue by elandorr** [Mailu/Mailu#2451]
v1.9.32

I noticed a small bug. If both are disabled, webmail is stuck in an infinite loop. I guess nobody ever tried it before since both are checked by default.

Not very consequential, but I figured you might want to know. Not sure about the use case either. I unchecked them because there was no need for this particular account and found it that way.

Cheers

**Comment by ghostwheel42** [comment]
Thanks. Logs show this (over and over again):
```
mailu-front-1  | * - - [14/Sep/2022:13:46:43 +0000] "GET /webmail/sso.php HTTP/2.0" 302 0 "https://domain.fqdn/sso/login" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:104.0) Gecko/20100101 Firefox/104.0"
mailu-front-1  | 2022/09/14 13:46:43 [info] 10#10: *1372 client 192.168.203.10:38486 connected to 0.0.0.0:10143
mailu-front-1  | 2022/09/14 13:46:43 [info] 10#10: *1372 client login failed: "Authentication credentials invalid" while in http auth state, client: 192.168.203.10, server: 0.0.0.0:10143, login: "disabled@example.com"
```
