### ISSUE TITLE
CRITICAL:root:Your DNS resolver at 127.0.0.11 is not working (The DNS operation timed out after 11.603842496871948 seconds)

### ISSUE THREAD

**Issue by CreatorSimon** [Mailu/Mailu#2454]
My Setup: Im currently using a VPS as an Gateway for all public hosted services. Wireguard is installed on that VPS to safely connect trough a tunnel to my Mailu host. When I route the traffic trought that tunnel (all or just the mailu containers) I got the DNS timeout issue. I searched for multiple solutions about wireguard dns issues but I didn't find a working one. I'm currently helpless because I dont know why I'm having this issue. Here are some logs of the containers:

LOGS:
antivirus_1  | Fri Sep 23 08:51:45 2022 -> Trying to retrieve CVD header from https://database.clamav.net/daily.cvd
antivirus_1  | Fri Sep 23 08:51:45 2022 -> ERROR: remote_cvdhead: Download failed (5) Fri Sep 23 08:51:45 2022 -> ERROR:  Message: Couldn't resolve proxy name
antivirus_1  | Fri Sep 23 08:51:45 2022 -> WARNING: Failed to get daily database version information from server: https://database.clamav.net
antivirus_1  | Fri Sep 23 08:51:45 2022 -> ERROR: check_for_new_database_version: Failed to find daily database using server https://database.clamav.net.
antivirus_1  | Fri Sep 23 08:51:45 2022 -> Giving up on https://database.clamav.net...
antivirus_1  | Fri Sep 23 08:51:45 2022 -> ERROR: Update failed for database: daily
antivirus_1  | Fri Sep 23 08:51:45 2022 -> ERROR: Database update process failed: HTTP GET failed
antivirus_1  | Fri Sep 23 08:51:45 2022 -> ERROR: Update failed.

admin_1      | CRITICAL:root:Your DNS resolver at 127.0.0.11 is not working (The DNS operation timed out after 11.603049755096436 seconds). Please see https://mailu.io/master/faq.html#the-admin-container-won-t-start-and-its-log-says-critical-your-dns-resolver-isn-t-doing-dnssec-validation

fetchmail_1  | Traceback (most recent call last):
fetchmail_1  |   File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
fetchmail_1  |     httplib_response = self._make_request(
fetchmail_1  |   File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 394, in _make_request
fetchmail_1  |     conn.request(method, url, **httplib_request_kw)
fetchmail_1  |   File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 234, in request
fetchmail_1  |     super(HTTPConnection, self).request(method, url, body=body, headers=headers)
fetchmail_1  |   File "/usr/lib/python3.9/http/client.py", line 1253, in request
fetchmail_1  |     self._send_request(method, url, body, headers, encode_chunked)
fetchmail_1  |   File "/usr/lib/python3.9/http/client.py", line 1299, in _send_request
fetchmail_1  |     self.endheaders(body, encode_chunked=encode_chunked)
fetchmail_1  |   File "/usr/lib/python3.9/http/client.py", line 1248, in endheaders
fetchmail_1  |     self._send_output(message_body, encode_chunked=encode_chunked)
fetchmail_1  |   File "/usr/lib/python3.9/http/client.py", line 1008, in _send_output
fetchmail_1  |     self.send(msg)
fetchmail_1  |   File "/usr/lib/python3.9/http/client.py", line 948, in send
fetchmail_1  |     self.connect()
fetchmail_1  |   File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 200, in connect
fetchmail_1  |     conn = self._new_conn()
fetchmail_1  |   File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 181, in _new_conn
fetchmail_1  |     raise NewConnectionError(
fetchmail_1  | urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fe9b1edd6d0>: Failed to establish a new connection: [Errno -3] Try again

front_1      | Traceback (most recent call last):
front_1      |   File "/usr/lib/python3.9/site-packages/tenacity/__init__.py", line 407, in __call__
front_1      |     result = fn(*args, **kwargs)
front_1      |   File "/usr/lib/python3.9/site-packages/socrate/system.py", line 12, in resolve_hostname
front_1      |     return socket.gethostbyname(hostname)
front_1      | socket.gaierror: [Errno -2] Name does not resolve
front_1      |
front_1      | The above exception was the direct cause of the following exception:
front_1      |
front_1      | Traceback (most recent call last):
front_1      |   File "/config.py", line 17, in <module>
front_1      |     args["ADMIN_ADDRESS"] = system.get_host_address_from_environment("ADMIN", "admin")
front_1      |   File "/usr/lib/python3.9/site-packages/socrate/system.py", line 32, in get_host_address_from_environment
front_1      |     return resolve_address(environ.get("HOST_{}".format(name), default))
front_1      |   File "/usr/lib/python3.9/site-packages/socrate/system.py", line 20, in resolve_address
front_1      |     ip_address = resolve_hostname(hostname)
front_1      |   File "/usr/lib/python3.9/site-packages/tenacity/__init__.py", line 324, in wrapped_f
front_1      |     return self(f, *args, **kw)
front_1      |   File "/usr/lib/python3.9/site-packages/tenacity/__init__.py", line 404, in __call__
front_1      |     do = self.iter(retry_state=retry_state)
front_1      |   File "/usr/lib/python3.9/site-packages/tenacity/__init__.py", line 361, in iter
front_1      |     raise retry_exc from fut.exception()
front_1      | tenacity.RetryError: RetryError[<Future at 0x7f28ed5eb9d0 state=finished raised gaierror>]

**Comment by nextgens** [comment]
Those logs all suggest that your Mailu deployment doesn't have internet connectivity. Currently you can't run Mailu without it.
