### ISSUE TITLE
Grant permissions for non-root user in mailu deployment for rsync.

### ISSUE THREAD

**Issue by adamward-git** [Mailu/Mailu#2459]
Thank you for opening an issue with Mailu. Please understand that issues are meant for bugs and enhancement-requests.
For **user-support questions**, reach out to us  on [matrix](https://matrix.to/#/#mailu:tedomum.net).

To be able to help you best, we need some more information.

## Before you open your issue
- [x] Check if no issue or pull-request for this already exists.
- [x] Check [documentation](https://mailu.io/master/) and [FAQ](https://mailu.io/master/faq.html). (Tip, use the search function on the documentation page)
- [x] You understand `Mailu` is made by volunteers in their **free time** — be conscise, civil and accept that delays can occur.
- [x] The title of the issue should be short and simple. It should contain specific terms related to the actual issue. Be specific while writing the title.

### Environment
 - [x] docker-compose
 - [ ] kubernetes
 - [ ] docker swarm

### Versions
To find your version, get the image name of a mailu container and read  the version from the tag (example for version 1.7).
1.9

## Description
As described in https://mailu.io/1.9/maintain.html#migrating-an-instance I am attempting to get a clone of the mailu deployment.
Running rsync in dry run returns Permission denied (13)

## Replication Steps
Use rsync with a non-root user to connect to the server as the source (anonymised):

** Launching RSYNC command (simulation mode):
rsync -r -n -t -v --progress -s non-root-user@servername:/mailu/ /some-local-directory/

## Expected behaviour
rsync synchronises the files to the destination. 

## Logs
(anonymised)
rsync: [sender] opendir "/mailu_prod/certs/letsencrypt/accounts" failed: Permission denied (13)
rsync: [sender] opendir "/mailu_prod/certs/letsencrypt/archive" failed: Permission denied (13)
rsync: [sender] opendir "/mailu_prod/certs/letsencrypt/keys" failed: Permission denied (13)
rsync: [sender] opendir "/mailu_prod/certs/letsencrypt/live" failed: Permission denied (13)
rsync: [sender] opendir "/mailu_prod/mail/xxxx@xxxxxx" failed: Permission denied (13)
rsync: [sender] opendir "/mailu_prod/mailqueue/active" failed: Permission denied (13)
rsync: [sender] opendir "/mailu_prod/mailqueue/bounce" failed: Permission denied (13)
rsync: [sender] opendir "/mailu_prod/mailqueue/corrupt" failed: Permission denied (13)
rsync: [sender] opendir "/mailu_prod/mailqueue/defer" failed: Permission denied (13)
rsync: [sender] opendir "/mailu_prod/mailqueue/deferred" failed: Permission denied (13)
rsync: [sender] opendir "/mailu_prod/mailqueue/flush" failed: Permission denied (13)
./
rsync: [sender] opendir "/mailu_prod/mailqueue/hold" failed: Permission denied (13)
docker-compose.yml
rsync: [sender] opendir "/mailu_prod/mailqueue/incoming" failed: Permission denied (13)
docker-compose.yml.old
rsync: [sender] opendir "/mailu_prod/mailqueue/maildrop" failed: Permission denied (13)
mailu.env
rsync: [sender] opendir "/mailu_prod/mailqueue/private" failed: Permission denied (13)

**Comment by ghostwheel42** [comment]
Hi.

Some of the files mailu creates are owned by root and therefore you need to run rsync add root.

You could also copy the files by creating and extracting a tar archive (as root).

Or you may be able to enable sudo without password on the remote machine and use the switch --rsync-path="sudo rsync" when syncing. 

Alex

**Comment by adamward-git** [comment]
Thanks, I was able to do this as suggested.
I created a specific user for the purpose (I guess you could call it a service account), granted sudo access for the rsync command and established the following command line to run it:

rsync -r -t -v --progress -s --exclude=filter --rsync-path='sudo rsync' user@domain:/mailu/ /local/storage/area

I am excluding the filter area because the data set can get large and and my understanding is that it is generated by clamav independently of the email storage - i.e. it can be safely regenerated.   Is this the case ?

**Comment by nextgens** [comment]
yes
