### ISSUE TITLE
how to add a List-Unsubscribe?

### ISSUE THREAD

**Issue by kathylincn** [Mailu/Mailu#2461]
I want people to be able to unsubscribe when emails are sent, but where do I add the ability to unsubscribe?

**Comment by ghostwheel42** [comment]
Thank you for opening an issue with Mailu. Please understand that issues are meant for bugs and enhancement-requests.
For **user-support questions**, reach out to us  on [matrix](https://matrix.to/#/#mailu:tedomum.net).

List-unsubscibe is done via an email header set by your mail-client or mailing-list software.
