### ISSUE TITLE
add aspell-en,de

### ISSUE THREAD

**Issue by MiKuBB** [Mailu/Mailu#2466]
please add aspell-en & aspell-de packages into roundcube docker image, because spell checker is not working

Mailu version 1.9. environment docker.

PHP Warning:  pspell_new(): PSPELL couldn't open the dictionary. reason: No word lists can be found for the language &quot;en&quot;. in /var/www/html/program/lib/Roundcube/spellchecker/pspell.php on line 76, referer: https://my-domain/webmail/?_task=mail&_action=compose&_id=225630545633d558dc2f1d

Thank you.

**Comment by dominch** [comment]
More language should be suported than en and de
