### ISSUE TITLE
can we  receive the email that doesn't exist?

### ISSUE THREAD

**Issue by viponedream** [Mailu/Mailu#2470]
how can we do that?
all users those dont exist send to admin@my.com
then we don't need to create  every user.

**Comment by ghostwheel42** [comment]
Thank you for opening an issue with Mailu. Please understand that issues are meant for bugs and enhancement-requests.
For **user-support questions**, reach out to us  on [matrix](https://matrix.to/#/#mailu:tedomum.net).
