### ISSUE TITLE
nginx.conf

### ISSUE THREAD

**Issue by MrKira34** [Mailu/Mailu#2477]
Error in nginx.conf file on line 158. Unspecified location
```
       location  {
         include /etc/nginx/proxy.conf;
         proxy_pass http://$admin;
         expires $expires;
       }
```
What location do you need to specify?

**Comment by MrKira34** [comment]
`nginx: [emerg] invalid number of arguments in "location" directive in /etc/nginx/nginx.conf:128`

**Comment by MrKira34** [comment]
```
       location  {
         include /etc/nginx/proxy.conf;
         proxy_pass http://$admin;
         expires $expires;
       }
```

**Comment by DjVinnii** [comment]
I think you are missing `WEB_ADMIN` in your configuration. This should be something like `/admin`. See the [Configuration Reference](https://mailu.io/1.9/configuration.html#web-settings) for more information about the different configuration variables.
