### ISSUE TITLE
unable to send email  and connection time out part SMTP

### ISSUE THREAD

**Issue by yusoffnike01** [Mailu/Mailu#2484]
![Screenshot 2022-10-22 001901](https://user-images.githubusercontent.com/59350157/197242576-edce6c06-90a0-488b-8681-ebc26c48560a.png)

**Comment by nextgens** [comment]
This is the same as #2473 #2478 #2457 and others...

Something is preventing connectivity to other SMTP servers (tcp port 25), usually the culprit is the ISP filtering traffic to prevent spam.

**Comment by yusoffnike01** [comment]
@nextgens, I already unblock my port 25 but still cannot send the email

**Comment by nextgens** [comment]
Try the following command from the command prompt: what do you see?

```
nc -C gmail-smtp-in.l.google.com 25
```

**Comment by yusoffnike01** [comment]
when I use this command line, not display nothing

![Screenshot 2022-10-22 200233](https://user-images.githubusercontent.com/59350157/197337978-b4defb8b-4701-4a57-9060-aee30df29aec.png)

**Comment by yusoffnike01** [comment]
when I check my port, already open 


![Screenshot 2022-10-22 200355](https://user-images.githubusercontent.com/59350157/197338050-4575e25e-16b3-4d6a-95cf-4b57d3ef3670.png)

**Comment by nextgens** [comment]
So as explained above, it **does not work** and isn't something Mailu can help you with; only your ISP can.

What is being blocked is your ability to establish outbound connections.

Your second screenshot relates to inbound connections.

**Comment by yusoffnike01** [comment]
any reference to solve this issue part ISP?

**Comment by nextgens** [comment]
Just tell them that you would like to operate an email server and that you need them to stop blocking traffic to port 25
