### ISSUE TITLE
1.8 Compose file generation utility

### ISSUE THREAD

**Issue by khashashin** [Mailu/Mailu#2492]
## Before you open your issue
- [x] Check if no issue or pull-request for this already exists.
- [x] Check [documentation](https://mailu.io/master/) and [FAQ](https://mailu.io/master/faq.html). (Tip, use the search function on the documentation page)
- [x] You understand `Mailu` is made by volunteers in their **free time** — be concise, civil and accept that delays can occur.
- [x] The title of the issue should be short and simple. It should contain specific terms related to the actual issue. Be specific while writing the title.

### Environment
 - [x] docker-compose
 - [ ] kubernetes
 - [ ] docker swarm

### Versions

1.7

## Description

Unable to generate compose file using [mailu setup utility](https://setup.mailu.io/1.9/)

![image](https://user-images.githubusercontent.com/17837758/197980435-2d9aaf86-8bbf-4b3c-bbf7-0778b3d272a8.png)

## Expected behaviour

Choosing 1.8 version

**Comment by nextgens** [comment]
The current stable (and supported) version of Mailu is 1.9

If you need to run 1.8, you can spawn your own setup instance using https://github.com/Mailu/Mailu/tree/1.8/setup
