### ISSUE TITLE
Error response from daemon: driver failed programming external connectivity on endpoint mailu-front-1 (307b4a12e8b09613103f140314fd269530434b69d33d843d013fbe91b1064004): Error starting userland proxy: listen tcp4 *.*.*.*:995: bind: cannot assign requested address

### ISSUE THREAD

**Issue by abhay2510kr** [Mailu/Mailu#2521]
Error response from daemon: driver failed programming external connectivity on endpoint mailu-front-1 (307b4a12e8b09613103f140314fd269530434b69d33d843d013fbe91b1064004): Error starting userland proxy: listen tcp4 *.*.*.*:995: bind: cannot assign requested address

**Comment by kikbi** [comment]
I encountered this problem too. Did you solve it? Or have you made any progress on this issue?

**Comment by kikbi** [comment]
> I encountered this problem too. Did you solve it? Or have you made any progress on this issue?

And I am pretty sure that there is no applications listened 955 port

**Comment by ghostwheel42** [comment]
This is almost certain a docker and not a mailu problem.
If there's nothing listening already on the port (995) - maybe docker got stuck. Try restarting docker, pruning containers, etc.

First hit is stackoverflow: https://www.google.com/search?q=Error+response+from+daemon%3A+driver+failed+programming+external+connectivity+on+endpoint

**Comment by aszurnasirpal** [comment]
> 

I'm affected by this problem as well. Has anyone had any luck? I tried with StackOverflow steps with no results so far. And there is no other application on port 995

**Comment by MauroMP1** [comment]
Hello, I ran into this problem at first and I found that it is because when configuring the public ip, I was configuring an ip that does not exist in the network cards of the VM, I use one in AWS and the public ip address does not carry over to the card directly, this is where I get lost, no matter what IP I configure, of the IPs that the VM has, it does not work correctly with nginex

**Comment by carlos00027** [comment]
+1

**Comment by ghostwheel42** [comment]
You should disable the userland proxy feature when using Mailu.

Create a file named /etc/docker/daemon.json if it does not exist, and add the "userland-proxy": false setting. The daemon.json file should be valid JSON; if this is the only configuration in that file, it should look like;

```
{
    "userland-proxy": false
}
```

After saving the file, restart the daemon using (if your host uses systemd);

```
sudo systemctl restart docker
```

**Comment by peter891014** [comment]
> > You should disable the userland proxy feature when using Mailu.
> > Create a file named /etc/docker/daemon.json if it does not exist, and add the "userland-proxy": false setting. The daemon.json file should be valid JSON; if this is the only configuration in that file, it should look like;
> > ```
> > {
> >     "userland-proxy": false
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > After saving the file, restart the daemon using (if your host uses systemd);
> > ```
> > sudo systemctl restart docker
> > ```
> 
> I'm having the same issue and disabled the userland proxy but no lucky. Can you please help me in fixing this issue?
> 
> <img alt="Screenshot 2023-05-03 at 9 09 14 PM" width="1436" src="https://user-images.githubusercontent.com/51378608/235966918-7bcc38e0-5cd9-4080-a7d7-8297e1cef47d.png">

my  erro not equal this title , my error is :Error response from daemon: driver failed programming external connectivity on endpoint nacos (d5f9463745d5e1c6407f4037c7587920d87e4a46e6968a47e8f58a3fd6c6be0d): Error starting userland proxy:
Error: failed to start containers: nacos
,when i  start any container  ,open this error,  in your way, i fix it ,  thank you , the error happen beacuse i drop docker  before, but  not clearly, with Hackers have infiltrated my system, installed some Ubuntu containers to mine cryptocurrency

**Comment by Tim-Masuda** [comment]
+1
