### ISSUE TITLE
database - general connection string support (feature request)

### ISSUE THREAD

**Issue by ZsBT** [Mailu/Mailu#2533]
Most languages support _DB URL_ recently. Host, dbname, user, password do not cover the required connection parameters in all cases.
E.g., even `psycopg2.connect` can accept something like this:

`postgresql://user:password@eu-central-1.cockroachlabs.cloud:15757/roundcube?sslmode=verify-full&options=--cluster%3Ddeep-beast-666
`

We could give a new environment variable like this:

`DB_CONNSTRING=postgresql://xyz...`

**Comment by nextgens** [comment]
I am fairly sure that if you get rid of ``DB_FLAVOR`` and set ``SQLALCHEMY_DATABASE_URI`` instead it will do the right thing. Granted this should be documented somewhere.
