### ISSUE TITLE
Mailu on arm exits with code 132

### ISSUE THREAD

**Issue by Minion3665** [Mailu/Mailu#2541]
### Environment

- [x] docker-compose
- [ ] kubernetes
- [ ] docker swarm

### Version

- Version: `master`

## Description

Mailu fails to run on a raspberry pi 4

## Replication Steps

- Follow https://mailu.io/master/arm_images.html to create a docker compose configuration for mailu
- Put that configuration onto a raspberry pi 4
- Run `docker compose up`

## Observed behaviour

- Every mailu container (i.e. everything except redis) exits with code 132
![2022-11-18 21:54:58+00:00](https://user-images.githubusercontent.com/34243578/202809663-8b0b24db-9c64-4180-ae54-a0e1aca0df1e.png)

## Expected behaviour

- I expect the mailu containers to start and run mailu

## Extra notes

- This seems to have been introduced between 8a90f83bd039b2c24fc892ef03c93439caed1496 and 68bb8da2b7dbc8112366684168413546f9881f25 as reverting to the former and building manually works

## Logs

```
{16:49}/opt/mailu ➭ docker compose up                                                              (PI) 
[+] Running 11/11
 ⠿ Network mailu_default        Created                                                             0.1s
 ⠿ Container mailu-resolver-1   Created                                                             0.3s
 ⠿ Container mailu-webdav-1     Created                                                             3.1s
 ⠿ Container mailu-front-1      Created                                                             3.1s
 ⠿ Container mailu-fetchmail-1  Created                                                             3.1s
 ⠿ Container mailu-redis-1      Created                                                             3.1s
 ⠿ Container mailu-admin-1      Created                                                             0.3s
 ⠿ Container mailu-imap-1       Created                                                             0.3s
 ⠿ Container mailu-smtp-1       Created                                                             0.3s
 ⠿ Container mailu-antispam-1   Created                                                             0.3s
 ⠿ Container mailu-webmail-1    Created                                                             0.1s
Attaching to mailu-admin-1, mailu-antispam-1, mailu-fetchmail-1, mailu-front-1, mailu-imap-1, mailu-redis-1, mailu-resolver-1, mailu-smtp-1, mailu-webdav-1, mailu-webmail-1
mailu-redis-1      | 1:C 18 Nov 2022 21:49:33.978 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
mailu-redis-1      | 1:C 18 Nov 2022 21:49:33.978 # Redis version=7.0.5, bits=64, commit=00000000, modified=0, pid=1, just started
mailu-redis-1      | 1:C 18 Nov 2022 21:49:33.979 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
mailu-redis-1      | 1:M 18 Nov 2022 21:49:33.985 * monotonic clock: POSIX clock_gettime
mailu-redis-1      | 1:M 18 Nov 2022 21:49:33.988 * Running mode=standalone, port=6379.
mailu-redis-1      | 1:M 18 Nov 2022 21:49:33.989 # Server initialized
mailu-redis-1      | 1:M 18 Nov 2022 21:49:33.990 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
mailu-redis-1      | 1:M 18 Nov 2022 21:49:33.996 * Loading RDB produced by version 7.0.5
mailu-redis-1      | 1:M 18 Nov 2022 21:49:33.996 * RDB age 94 seconds
mailu-redis-1      | 1:M 18 Nov 2022 21:49:33.996 * RDB memory usage when created 1.11 Mb
mailu-redis-1      | 1:M 18 Nov 2022 21:49:34.001 * Done loading RDB, keys loaded: 2480, keys expired: 0.
mailu-redis-1      | 1:M 18 Nov 2022 21:49:34.001 * DB loaded from disk: 0.005 seconds
mailu-redis-1      | 1:M 18 Nov 2022 21:49:34.001 * Ready to accept connections
mailu-resolver-1 exited with code 0
mailu-fetchmail-1 exited with code 132
mailu-webdav-1 exited with code 132
mailu-resolver-1 exited with code 132
mailu-front-1 exited with code 132
mailu-admin-1 exited with code 132
mailu-smtp-1 exited with code 0
mailu-fetchmail-1 exited with code 0
mailu-imap-1 exited with code 132
mailu-antispam-1 exited with code 132
mailu-webdav-1 exited with code 132
mailu-resolver-1 exited with code 132
mailu-admin-1 exited with code 132
mailu-fetchmail-1 exited with code 132
mailu-smtp-1 exited with code 132
mailu-webmail-1 exited with code 132
mailu-front-1 exited with code 132
mailu-imap-1 exited with code 132
mailu-antispam-1 exited with code 132
mailu-resolver-1 exited with code 132
mailu-admin-1 exited with code 132
mailu-webdav-1 exited with code 132
mailu-webmail-1 exited with code 0
mailu-smtp-1 exited with code 132
mailu-fetchmail-1 exited with code 132
mailu-imap-1 exited with code 132
mailu-antispam-1 exited with code 132
mailu-front-1 exited with code 132
mailu-resolver-1 exited with code 132
mailu-admin-1 exited with code 132
mailu-webmail-1 exited with code 132
mailu-webdav-1 exited with code 132
mailu-smtp-1 exited with code 132
mailu-antispam-1 exited with code 132
mailu-fetchmail-1 exited with code 132
mailu-imap-1 exited with code 132
mailu-admin-1 exited with code 132
^CGracefully stopping... (press Ctrl+C again to force)
[+] Running 4/6
 ⠿ Container mailu-webmail-1    Stopped                                                             0.3s
 ⠿ Container mailu-fetchmail-1  Stopped                                                             0.1s
 ⠿ Container mailu-webdav-1     Stopped                                                             0.2s
 ⠹ Container mailu-admin-1      Stopping                                                            0.3s
 ⠹ Container mailu-smtp-1       Stopping                                                            0.3s
 ⠿ Container mailu-antispam-1   Stopped                                                             0.3s
 ⠋ Container mailu-imap-1       Stopping                                                            0.0s
```

**Comment by leolivier** [comment]
Hi, same issue here also with latest arm64 version.
I think the issue is in the resolver which exits for an unknown reason with code 0 and as other containers depend on it, they can't start.
And by the way, still no way to go back to the previous version, so my server is not working and I can't rollback to the working version :/

**Comment by leolivier** [comment]
Found at https://stackoverflow.com/questions/60930359/docker-containers-exit-code-132 and at https://github.com/RasaHQ/rasa/issues/4602 that in an amd64 context, it might be due to building with amd64-avx and not simply amd64.
On https://github.com/openresty/docker-openresty/issues/39, more or less the same but with sse4.2

 I don't know if the same kind of issue might happen in arm64 context and if something was changed in the build recently ?

**Comment by leolivier** [comment]
Likely to be linked to #2538 I'm afraid. It changes the C++ compilation flags for ARM build...

**Comment by nextgens** [comment]
It's most likely one of the compiler flags at https://github.com/Mailu/Mailu/blob/68bb8da2b7dbc8112366684168413546f9881f25/core/base/Dockerfile#L26 ... I'm investigating.

**Comment by nextgens** [comment]
This works on the aarch64 machine I have access to.

```
root@a2:~/dev/storage# docker ps 
CONTAINER ID   IMAGE                           COMMAND                  CREATED              STATUS                        PORTS                                                                                                                                                                                                                                NAMES
1a54d32de8da   mailu/postfix:master-arm        "/bin/sh -c /start.py"   About a minute ago   Up About a minute (healthy)   25/tcp, 10025/tcp                                                                                                                                                                                                                    storage-smtp-1
18430bca9627   mailu/admin:master-arm          "/bin/sh -c /start.py"   About a minute ago   Up About a minute (healthy)   80/tcp                                                                                                                                                                                                                               storage-admin-1
53f074c8614c   mailu/roundcube:master-arm      "/bin/sh -c /start.py"   About a minute ago   Up About a minute (healthy)   80/tcp                                                                                                                                                                                                                               storage-webmail-1
2d5b09459747   mailu/dovecot:master-arm        "/bin/sh -c /start.py"   About a minute ago   Up About a minute (healthy)   110/tcp, 143/tcp, 993/tcp, 2525/tcp, 4190/tcp                                                                                                                                                                                        storage-imap-1
6dcc523d4c15   mailu/rspamd:master-arm         "/bin/sh -c /start.py"   About a minute ago   Up About a minute (healthy)   11332/tcp, 11334-11335/tcp                                                                                                                                                                                                           storage-antispam-1
4ec576a01421   mailu/nginx:master-arm          "/bin/sh -c /start.py"   About a minute ago   Up About a minute (healthy)   0.0.0.0:25->25/tcp, 127.0.0.1:110->110/tcp, 0.0.0.0:80->80/tcp, 127.0.0.1:143->143/tcp, 127.0.0.1:465->465/tcp, 127.0.0.1:587->587/tcp, 127.0.0.1:993->993/tcp, 10025/tcp, 0.0.0.0:443->443/tcp, 127.0.0.1:995->995/tcp, 10143/tcp   storage-front-1
79f0c980563f   redis:alpine                    "docker-entrypoint.s…"   About a minute ago   Up About a minute             6379/tcp                                                                                                                                                                                                                             storage-redis-1
7c0b8f50aa11   mailu/unbound:master-arm        "/bin/sh -c /start.py"   About a minute ago   Up About a minute (healthy)   53/tcp, 53/udp                                                                                                                                                                                                                       storage-resolver-1
2f5722a4fdfe   moby/buildkit:buildx-stable-1   "buildkitd"              2 weeks ago          Up 2 weeks                                                                                                                                                                                                                                                         buildx_buildkit_competent_margulis0
root@a2:~/dev/storage# docker exec -ti storage-admin-1 /bin/sh -c 'uname -a; ps'
Linux 18430bca9627 5.15.0-1016-oracle #20-Ubuntu SMP Mon Aug 8 07:08:08 UTC 2022 aarch64 Linux
PID   USER     TIME  COMMAND
    1 root      0:00 python3 /start.py
    8 root      0:02 {gunicorn} /app/venv/bin/python3 /app/venv/bin/gunicorn --threads 4 -b :80 --access-logf
    9 root      0:00 {gunicorn} /app/venv/bin/python3 /app/venv/bin/gunicorn --threads 4 -b :80 --access-logf
   58 root      0:00 ps
root@a2:~/dev/storage# docker exec -ti storage-admin-1 /bin/bash -c 'apk add lsof;lsof |grep /usr/lib/libhardened_malloc.so'
OK: 70 MiB in 43 packages
python3    1              root  mem       REG      8,1          14542605 /usr/lib/libhardened_malloc.so (path dev=0,89)
gunicorn   8              root  mem       REG      8,1          14542605 /usr/lib/libhardened_malloc.so (path dev=0,89)
gunicorn   9              root  mem       REG      8,1          14542605 /usr/lib/libhardened_malloc.so (path dev=0,89)
gunicorn   9  10 gunicorn root  mem       REG      8,1          14542605 /usr/lib/libhardened_malloc.so (path dev=0,89)
gunicorn   9  11 gunicorn root  mem       REG      8,1          14542605 /usr/lib/libhardened_malloc.so (path dev=0,89)
gunicorn   9  12 gunicorn root  mem       REG      8,1          14542605 /usr/lib/libhardened_malloc.so (path dev=0,89)
gunicorn   9  13 gunicorn root  mem       REG      8,1          14542605 /usr/lib/libhardened_malloc.so (path dev=0,89)
bash     172              root  mem       REG      8,1          14542605 /usr/lib/libhardened_malloc.so (path dev=0,89)
lsof     179              root  mem       REG      8,1          14542605 /usr/lib/libhardened_malloc.so (path dev=0,89)
grep     180              root  mem       REG      8,1          14542605 /usr/lib/libhardened_malloc.so (path dev=0,89)
lsof     181              root  mem       REG      8,1          14542605 /usr/lib/libhardened_malloc.so (path dev=0,89)
```

**Comment by nextgens** [comment]
@leolivier @Minion3665 we have recently added two things: libhardened_malloc via LD_PRELOAD and a bunch of compiler hardening flags; if you could find what is causing the problems that'd be great

**Comment by leolivier** [comment]
@nextgens, how can we do that? 
What I can tell is that I update my images every week, and the images of last Friday (11/11) were working (I don't remember if they were updated at that time, so it's maybe older images actually, but I did a pull on 11/11).
If you provide some images with or without the flags, I can try them quickly and tell you if they are working or not.

**Comment by leolivier** [comment]
> This works on the aarch64 machine I have access to.

Is it a raspberry pi? I have switched recently my RPi 4 to arm64 version, but the images were working before I updated today...

**Comment by nextgens** [comment]
Just recompile the images with the proposed changes:
```
export MAILU_VERSION=local-arm
docker buildx bake --no-cache -f tests/build.hcl --set '*.platform=linux/arm64/v8'
docker-compose up -d
```

For speed sake, you may want to try only one of the failing images (don't forget MAILU_VERSION=local-arm)
```
docker buildx bake --no-cache -f tests/build.hcl --set '*.platform=linux/arm64/v8' resolver
```

**Comment by nextgens** [comment]
> > This works on the aarch64 machine I have access to.
> 
> Is it a raspberry pi? I have switched recently my RPi 4 to arm64 version, but the images were working before I updated today...

That's an ampere A1 instance on oracle's cloud.

**Comment by leolivier** [comment]
> export MAILU_VERSION=local-arm

But if I do that on the master branch, I will have the same result as the hub image, won't I? 
Anyway, I will try it but I don't get the idea...

**Comment by Minion3665** [comment]
> > docker buildx bake --no-cache -f tests/build.hcl --set '*.platform=linux/arm64/v8' resolver
> 
> But if I do that on the master branch, I will have the same result as the hub image, won't I? Anyway, I will try it but I don't get the idea...

I believe the idea is to do it after modifying the code (e.g. I checked-out a week-old commit and did it, my results are on docker hub under minion3665 and are working for me). Hopefully if we build enough we can pinpoint where the error is

**Comment by nextgens** [comment]
Somewhere in between line 21 and 25 on https://github.com/Mailu/Mailu/blob/68bb8da2b7dbc8112366684168413546f9881f25/core/base/Dockerfile#L26 is my guess.

**Comment by leolivier** [comment]
I confirm @Minion3665 images are working for me too.
I will use them until the bug is fixed. 
@Minion3665 are you trying to rebuild the different combinations of commits? If you do it, I won't as I would need to recreate my whole docker devt environment which I destroyed recently...

**Comment by nextgens** [comment]
@leolivier commenting line by line line 21 to 25 and finding what exactly is breaking things would be helpful.

**Comment by nextgens** [comment]
I've retried rebuilding everything for armv7 and that works too on this CPU:

```
root@a2:~/dev/storage# docker run --rm -it mailu/nginx:local-arm7 /bin/bash
WARNING: The requested image's platform (linux/arm/v7) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
bash-5.1# ldd /bin/hostname 
	/lib/ld-musl-armhf.so.1 (0xf7ef3000)
	libc.musl-armv7.so.1 => /lib/ld-musl-armhf.so.1 (0xf7ef3000)
```

**Comment by Minion3665** [comment]
> I confirm @Minion3665 images are working for me too. I will use them until the bug is fixed. @Minion3665 are you trying to rebuild the different combinations of commits? If you do it, I won't as I would need to recreate my whole docker devt environment which I destroyed recently...

I am not right now, however I may do soon (i.e. when I finish some other work I have to do) so depending on how quickly you want this fixed you can either try rebuilding or not.

**Comment by nextgens** [comment]
It would be good if we could identify a test-case that would break on the builder: there's no point in them running the test-suite if I can't make it crash there.

**Comment by leolivier** [comment]
> I am not right now, however I may do soon (i.e. when I finish some other work I have to do) so depending on how quickly you want this fixed you can either try rebuilding or not.
Actually, your current front image has an issue and does not start for me (I think it's linked to webmail) so I have no working version...

**Comment by leolivier** [comment]
> It would be good if we could identify a test-case that would break on the builder: there's no point in them running the test-suite if I can't make it crash there.

As I said, I destroyed my devt envt so I just tried a git clone on my RPi4 directly then export MAILU_VERSION and docker buildx bake on the Pi. I have this starnge 132 error which does seem to be linked to any cpp variable:
```
ERROR: failed to solve: process "/bin/sh -c set -euxo pipefail   ; apk add --no-cache py3-pip   ; python3 -m venv ${VIRTUAL_ENV}   ; ${VIRTUAL_ENV}/bin/pip install --no-cache-dir -r requirements-build.txt   ; apk del -r py3-pip   ; rm -f /tmp/*.pem" did not complete successfully: exit code: 132
```

**Comment by nextgens** [comment]
132 means 'illegal instruction'; it could be anything.

Remove line 21 to 25 in Mailu/core/base/Dockerfile and retry.

**Comment by leolivier** [comment]
I did that already but it keeps stopping on the above error...

**Comment by nextgens** [comment]
Including line 21 with LD_PRELOAD ? That could well be what makes pip crash.

**Comment by nextgens** [comment]
If that still doesn't work, try rebuilding without buildx:
```
cd core/base
docker build -t test/test .
```

**Comment by leolivier** [comment]
LD_PRELOAD didn't work. I tried docker build w/o buildx but it fails too because TARGETPLATFORM is not set :/
```
+ uname -m
+ machine=aarch64
/bin/sh: TARGETPLATFORM: parameter not set
The command '/bin/sh -c set -euxo pipefail   ; addgroup -Sg ${MAILU_GID} mailu   ; adduser -Sg ${MAILU_UID} -G mailu -h /app -g "mailu app" -s /bin/bash mailu   ; apk add --no-cache bash ca-certificates curl python3 tzdata   ; machine="$(uname -m)"   ; ! [[ "${TARGETPLATFORM}" != linux/arm/v7 && \( "${machine}" == x86_64 || "${machine}" == armv8* || "${machine}" == aarch64 \) ]]     || apk add --no-cache --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing hardened-malloc' returned a non-zero code: 2
```
I must confess that I worked on a lot of other things since I worked on this topic and I have forgotten **everything**, so I'm not efficient at all  :(

**Comment by nextgens** [comment]
try with --build-arg TARGETPLATFORM=linux/arm64/v8

**Comment by leolivier** [comment]
> try with --build-arg TARGETPLATFORM=linux/arm64/v8

I added that and I'm back to the same issue:
```
The command '/bin/sh -c set -euxo pipefail   ; apk add --no-cache py3-pip   ; python3 -m venv ${VIRTUAL_ENV}   ; ${VIRTUAL_ENV}/bin/pip install --no-cache-dir -r requirements-build.txt   ; apk del -r py3-pip   ; rm -f /tmp/*.pem' returned a non-zero code: 132
```

**Comment by nextgens** [comment]
This may be a different bug/problem. Looking at the diff in between the two commits mentioned in the issue:

```
git diff 8a90f83..68bb8da -- core/base/Dockerfile
diff --git a/core/base/Dockerfile b/core/base/Dockerfile
index d5be6a90..6f31e21c 100644
--- a/core/base/Dockerfile
+++ b/core/base/Dockerfile
@@ -8,11 +8,21 @@ ENV TZ=Etc/UTC LANG=C.UTF-8
 
 ARG MAILU_UID=1000
 ARG MAILU_GID=1000
+ARG TARGETPLATFORM
 
 RUN set -euxo pipefail \
   ; addgroup -Sg ${MAILU_GID} mailu \
   ; adduser -Sg ${MAILU_UID} -G mailu -h /app -g "mailu app" -s /bin/bash mailu \
-  ; apk add --no-cache bash ca-certificates curl python3 tzdata
+  ; apk add --no-cache bash ca-certificates curl python3 tzdata \
+  ; machine="$(uname -m)" \
+  ; ! [[ "${TARGETPLATFORM}" != linux/arm/v7 && \( "${machine}" == x86_64 || "${machine}" == armv8* || "${machine}" == aarch64 \) ]] \
+    || apk add --no-cache --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing hardened-malloc
+
+ENV LD_PRELOAD=/usr/lib/libhardened_malloc.so
+ENV CXXFLAGS="-g -O2 -fdebug-prefix-map=/app=. -fstack-protector-strong -Wformat -Werror=format-security -fstack-clash-protection -fexceptions"
+ENV CFLAGS="-g -O2 -fdebug-prefix-map=/app=. -fstack-protector-strong -Wformat -Werror=format-security -fstack-clash-protection -fexceptions"
+ENV CPPFLAGS="-Wdate-time -D_FORTIFY_SOURCE=2"
+ENV LDFLAGS="-Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now"
 
 WORKDIR /app
 
```

**Comment by leolivier** [comment]
I finally was able to restore my devt environment.
I removed all lines from 21 to 25 in the Dockerfile and rebuilt resolver and it works.
I will now 1rts rebuild everything with that context to have my whole server working (hopefully) then I will try to put back these lines one by one and keep you updated once there is an issue on resolver.

**Comment by leolivier** [comment]
Hi again, 1rst result:
Adding only the line `NV LD_PRELOAD=/usr/lib/libhardened_malloc.so` breaks the build itself:
```
ERROR: failed to solve: process "/bin/sh -c set -euxo pipefail   ; apk add --no-cache py3-pip   ; python3 -m venv ${VIRTUAL_ENV}   ; ${VIRTUAL_ENV}/bin/pip install --no-cache-dir -r requirements-build.txt   ; apk del -r py3-pip   ; rm -f /tmp/*.pem" did not complete successfully: exit code: 137
```
(Note the 137 code, not 132 - which means by the way RF KILL if this is an errno, not illegal instruction)

I will now try with other lines, w/o the hardened malloc

**Comment by leolivier** [comment]
I confirm that only removing the line on hardened malloc solves the issue! (tested only on resolver for now but I think it's enough)

**Comment by nextgens** [comment]
@leolivier please check whether LD_PRELOAD=/usr/lib/libhardened_malloc-light.so works

**Comment by nextgens** [comment]
@leolivier @Minion3665 the PR has been merged and new images should have been pushed; please confirm they work.

**Comment by leolivier** [comment]
> /usr/lib/libhardened_malloc-light.so

Same 137 error...

**Comment by leolivier** [comment]
> @leolivier @Minion3665 the PR has been merged and new images should have been pushed; please confirm they work.

Thanks for the new images!
Everything looks ok except snappymail which seems to be frozen at start. I will investigate a bit more on that one.

I know this is still beta but would it be possible to work on having specific tags on each new versions so we can rollback to the previous version when such an issue arises?

**Comment by Minion3665** [comment]
> @leolivier @Minion3665 the PR has been merged and new images should have been pushed; please confirm they work.

Thank you very much, everything is working perfectly on my end

> I know this is still beta but would it be possible to work on having specific tags on each new versions so we can rollback to the previous version when such an issue arises?

The problem is that each version is a commit, if it were done on existing pages I suspect this would lead to a *lot* of tags very quickly which'd be quite a bit of noise for anyone looking at tags on docker hub. If this were done perhaps a second org/similar would be an advantage

**Comment by nextgens** [comment]
> > @leolivier @Minion3665 the PR has been merged and new images should have been pushed; please confirm they work.
> 
> Thanks for the new images! Everything looks ok

Thank you for the feedback.

> except snappymail which seems to be frozen at start. I will investigate a bit more on that one.
> 

Massive work has been done on #2526 ; it may improve things. By default snappymail uses a file-based cache... and we switch to APCu.

> I know this is still beta but would it be possible to work on having specific tags on each new versions so we can rollback to the previous version when such an issue arises?
> 

We've talked about it in the past and the answer is no. When the ARM images will hit a stable release then that will be possible... but we don't want people running different shades of master. To solve your specific problem, I suggest you look into persisting the "running" images before attempting an update; what I usually do is stop the containers, rename them and then upgrade. If the upgrade work I then dispose of the stopped containers... and if they don't I just restart them.

**Comment by leolivier** [comment]
Thanks for the suggestion @nextgens, I will try that

**Comment by nextgens** [comment]
@leolivier
```
docker images --format "{{.Repository}}:{{.Tag}}"|grep :master|while read image; do docker tag "$image" "${image/:master/:working}"; done
```

**Comment by leolivier** [comment]
Thank you @nextgens

**Comment by leolivier** [comment]
@nextgens here it is:
```
pi@raspberrypi ~ $ cat /proc/cpuinfo
processor       : 0
BogoMIPS        : 108.00
Features        : fp asimd evtstrm crc32 cpuid
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

processor       : 1
BogoMIPS        : 108.00
Features        : fp asimd evtstrm crc32 cpuid
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

processor       : 2
BogoMIPS        : 108.00
Features        : fp asimd evtstrm crc32 cpuid
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

processor       : 3
BogoMIPS        : 108.00
Features        : fp asimd evtstrm crc32 cpuid
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

Hardware        : BCM2835
Revision        : c03112
Serial          : 10000000adfa00dd
Model           : Raspberry Pi 4 Model B Rev 1.2
```
