### ISSUE TITLE
S3 Bucket Integration for all mails storing

### ISSUE THREAD

**Issue by Wezboin** [Mailu/Mailu#2549]
How can I integrate s3 bucket for storing mails as we have multiple mail servers and want to sink all the mails to each other but not able to integrate can anyone provide a solution

**Comment by nextgens** [comment]
The "solution" you are looking for is called obox; It's sold there:

https://doc.dovecot.org/admin_manual/mailbox_formats/
https://www.open-xchange.com/products/ox-dovecot-pro/
