### ISSUE TITLE
Feature request - Credential Export

### ISSUE THREAD

**Issue by pappastech** [Mailu/Mailu#2572]
I'd like to request an additional action for user accounts. I would like the ability to export user credentials to a PDF that could be printed and given to users when new accounts are created. This is a feature that exists in other systems I've used and is very nice for getting users started.

Thanks,
Tom

**Comment by Diman0** [comment]
This is not possible. Passwords are stored as encrypted hashes. It is not possible to decrypt these.
When creating the account, you can jot down the username/password for the user.

Users can be created via automation using the mailu cli command `user`. https://mailu.io/1.9/cli.html#user
You could use a script to create users automatically and then also via script create a text file with the username/password.

**Comment by pappastech** [comment]
It is possible, the PDF with the credentials would just have to be created when the user account is created and then store the PDF. If that's outside the scope of what the project wants to do, I can understand that; but it's not impossible.

**Comment by ghostwheel42** [comment]
You could generate users and passwords in a batch process and create the PDFs yourself.
You can then create the users via the cli (flask mailu config-import) or (when it's released) via the REST API.
But honestly I think that printing passwords is not a good idea - there's currently no way to force the user to change it after the first login.

**Comment by pappastech** [comment]
Thanks for the consideration. Closing this request.
