### ISSUE TITLE
[Question] Before I install

### ISSUE THREAD

**Issue by MartinHotmann** [Mailu/Mailu#2578]
I have not installed this docker-based Mailserver yet, but would like to know something upfront, which is very important for me.

Does this (Mailu) have insecure SSL & TLS versions enabled by default? If so, is there a very easy way to disable them for all applications in this docker-compose stack?

Insecure versions are:

- SSLv2
- SSLv3
- TLSv1.0
- TLSv1.1

Thank you in advance!

**Comment by nextgens** [comment]
Yes it does but only on port 25.

The setting to change the behavior is called ``TLS_PERMISSIVE`` and currently only exists in master.

https://mailu.io/master/configuration.html#advanced-settings
https://github.com/Mailu/Mailu/pull/2450

As far as SMTP is concerned, the alternative to "weak encryption" is "no encryption"; think twice before enabling it.
