### ISSUE TITLE
I can only receive emails, but I can’t send any.

### ISSUE THREAD

**Issue by Jaydenha09** [Mailu/Mailu#2582]
### Environment

- [x] docker-compose
- [ ] kubernetes
- [ ] docker swarm

### Version

- Version: `master`

## Description

I can receive mail, but cannot send mail,I host server on my own computer at home, so it won’t be VPS problem. 

System send me this
 

>This is the mail system at host jayden.ml.
>
>####################################################################
># THIS IS A WARNING ONLY.  YOU DO NOT NEED TO RESEND YOUR MESSAGE. >#
>####################################################################
>
>Your message could not be delivered for more than 0 hour(s).
>It will be retried until it is 5 day(s) old.
>
>For further assistance, please send mail to postmaster.
>
>If you do so, please include this problem report. You can
>delete your own text from the attached returned message.
>
>                   The mail system
>
><[hajayden2009@gmail.com](mailto:hajayden2009@gmail.com)>: connect to
>    alt2.gmail-smtp-in.l.google.com[2607:f8b0:4023:1004::1a]:25: Address not
>    available
>Reporting-MTA: dns; jayden.ml
>X-Postfix-Queue-ID: D720C4A01F8
>X-Postfix-Sender: rfc822; [admin@jayden.ml](mailto:admin@jayden.ml)
>Arrival-Date: Mon, 12 Dec 2022 23:52:05 +0000 (UTC)
>
>Final-Recipient: rfc822; [hajayden2009@gmail.com](mailto:hajayden2009@gmail.com)
>Original-Recipient: rfc822;[hajayden2009@gmail.com](mailto:hajayden2009@gmail.com)
>Action: delayed
>Status: 4.4.1
>Diagnostic-Code: X-Postfix; connect to
>    alt2.gmail-smtp-in.l.google.com[2607:f8b0:4023:1004::1a]:25: Address not
>    available
>Will-Retry-Until: Sat, 17 Dec 2022 23:52:05 +0000 (UTC)
>Return-Path: <[admin@jayden.ml](mailto:admin@jayden.ml)>
>MIME-Version: 1.0
>DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=jayden.ml; s=dkim;
>    t=[1670889125](tel:1670889125);
>    h=from:from:reply-to:subject:subject:date:date:message-id:message-id:
>     to:to:cc:mime-version:mime-version:content-type:content-type:
>     content-transfer-encoding:content-transfer-encoding:
>     in-reply-to:in-reply-to:references:references;
>    bh=QXzVIBXPSNxvE7i6SS/9uwcLxQFJp7SzbfuS9SanpAk=;
>    b=PoTQOUqKpYocSQz8KZ8LJgpMe4wlTd8BI2cHR19mX6NPvee/>6g9KC7sw8Neg5rrFt1Oc6e
>    dGmA6rqOEvmuDVj5a9usyd9zrAoatHu7elmCv5XwHp7amSRzpR9WIJ2Oegn>F3hs5NgcVYV
>    Nsc88AqfR5W2VqAKZMM9ImC8qd+yHU3ZY5bXHU0EGgjRVx7PKQuzPUyqV>MB5HI0/BJ1lcu
>    5EhzgWCja9cA8WCS9kaOgWt0rFBScxdXCXFn85Axuy2p0elcNR1wKTkbA+T>BInWTuhzv5O
>    mvsf/>ZhyhRaIiNKjhqHH36vsaJnHvvHd+SKfVEXJMEedQ82J8cXjOJcn2N1+8A==
>Date: Mon, 12 Dec 2022 23:52:05 +0000
>From: [admin@jayden.ml](mailto:admin@jayden.ml)
>To: Jayden Ha <[hajayden2009@gmail.com](mailto:hajayden2009@gmail.com)>
>Subject: Re: [12345678990](tel:12345678990)
>In-Reply-To: <[CAA6_NUE-ncPufVEWxv9=P5->bfWCRtpVvH7F=Ss=74HD+ceQZzQ@mail.gmail.com](mailto:CAA6_NUE-ncPufVEWxv9=P5-bfWCRtpVvH7F=Ss=74HD+ceQZzQ@mail.gmail.com)>
>References: <[CAA6_NUE-ncPufVEWxv9=P5->bfWCRtpVvH7F=Ss=74HD+ceQZzQ@mail.gmail.com](mailto:CAA6_NUE-ncPufVEWxv9=P5-bfWCRtpVvH7F=Ss=74HD+ceQZzQ@mail.gmail.com)>
>Message-ID: <[97b85f914b006d9338c858cd02c110d3@jayden.ml](mailto:97b85f914b006d9338c858cd02c110d3@jayden.ml)>
>X-Sender: [admin@jayden.ml](mailto:admin@jayden.ml)
>Content-Type: text/plain; charset=UTF-8;
> format=flowed
>Content-Transfer-Encoding: 8bit
>Authentication-Results: jayden.ml;
>    auth=pass [smtp.mailfrom=admin@jayden.ml](mailto:smtp.mailfrom=admin@jayden.ml)
>X-Spamd-Bar: /

## Expected behaviour

I can’t receive mail in gmail.com

**Comment by Jaydenha09** [comment]
Will this be the network provider block port 25?But I had check port 25 is open.
![730BD7C6-886D-4FDB-9B47-160C20DEBFAF](https://user-images.githubusercontent.com/98650905/207503780-d57c6d4c-7aba-499f-ad00-1688d71032a8.jpeg)

**Comment by nextgens** [comment]
It's the egress to port 25 that is probably blocked. Try to connect to the test server: if you don't see the banner it's your ISP or your router that is blocking it.

```
$nc -C test.mailu.io. 25
220 test.mailu.io ESMTP ready
```

**Comment by carlos00027** [comment]
i have same problem
