### ISSUE TITLE
manually copying certs, not sure what to name the certs for the second domain, no documentation

### ISSUE THREAD

**Issue by SanjayDookhoo** [Mailu/Mailu#2584]
I am using TLS_FLAVOR=cert, and I am currently copying in the cert using the following script 

```console
#!/bin/sh
cp /etc/letsencrypt/live/domain.com/privkey.pem /mailu/certs/key.pem || exit 1
cp /etc/letsencrypt/live/domain.com/fullchain.pem /mailu/certs/cert.pem || exit 1
docker exec mailu_front_1 nginx -s reload
```

This example script was gotten from https://mailu.io/master/maintain.html#managing-of-external-let-s-encrypt-certificates

i would like to add another domain, lets say domain2.com. Based on the example script, I can't figure out what I should name the new cert that I copy into the folder for the docker volume related to domain2.com (key.pem and cert.pem was used in the example)

*Note: I am unable to use letsencrypt, therefore I am manually copying the cert, due to this https://support.cloudflare.com/hc/en-us/articles/214820528-Validating-a-Let-s-Encrypt-Certificate-on-a-Site-Already-Active-on-Cloudflare

**Comment by Diman0** [comment]
You can use only one cert. The cert must contain all public domains (A records) that point to your Mailu box.

**Comment by SanjayDookhoo** [comment]
thank you, after some searching i figured out how to do it manually! thank you

**Comment by hafidzaini** [comment]
any sample?
i dont know hot to set the cert manually too

**Comment by SanjayDookhoo** [comment]
i installed certbot on my server following only step 1 https://www.digitalocean.com/community/tutorials/how-to-use-certbot-standalone-mode-to-retrieve-let-s-encrypt-ssl-certificates-on-ubuntu-20-04

this is the bash script that i used for initially creating the cert for multiple domains 

```shell
DOMAINS=domain1.com,domain2.com,domain3.com
ALL_DOMAIN=""
for DOMAIN in ${DOMAINS//,/ }
do
	ALL_DOMAIN+="-d *.$DOMAIN -d $DOMAIN "
done
certbot certonly --manual --preferred-challenges dns $ALL_DOMAIN --agree-tos --manual-public-ip-logging-ok --preferred-challenges dns-01 --server https://acme-v02.api.letsencrypt.org/directory --register-unsafely-without-email --rsa-key-size 4096
```

the following  can then be used to renew the cert (can save this is a .sh file and create a cron job to run every x days)

```shell
#!/bin/sh
certbot renew 
cp /etc/letsencrypt/live/domain.com/privkey.pem /mailu/certs/key.pem || exit 1
cp /etc/letsencrypt/live/domain.com/fullchain.pem /mailu/certs/cert.pem || exit 1
docker exec mailu_front_1 nginx -s reload
```

Note: This is old documentation i saved before, I have not revisited it in a while, I hope this at least helps
