### ISSUE TITLE
Access webmail on subdomain (webmail.domain.tld) instead of default path (/webmail)

### ISSUE THREAD

**Issue by pboesch** [Mailu/Mailu#2585]
Hi, 

Im looking for a way to access webmail from a subdomain instead of default path.

```
DOMAIN=domain.tld
HOSTNAMES=mail.domain.tld

WEB_REDIRECT=/
WEB_WEBMAIL=/
```
But obviously Im getting a `HTTP/1.1 500 Internal Server Error`

Is it possible with mailu?

Thanks

**Comment by nextgens** [comment]
Not currently. The SSO requires cookies... it could only work if the webmail is a subdomain of the mailu FQDN. If you want this to happen, please explain clearly the usecase and open a feature request.
