### ISSUE TITLE
Can someone elaborate on the reasoning behind merging webmails into one container?

### ISSUE THREAD

**Issue by psych0d0g** [Mailu/Mailu#2586]
Upon deploying a new mailu instance on my new k8s using the refactor fork ( https://github.com/Mailu/helm-charts/pull/193 ) of the helm chart, i stumbled upon this commit: https://github.com/Mailu/Mailu/commit/dc9e2a3e70954d460963e25b43889d0e55508024

i dont want to offend anyone but wouldnt it make more sense, in a containerized world, to keep them split apart into seperate containers?
Maybe introduce a common webmail base-image that shares the common code, and extend from there to the two webmailer specific containers?

If there is a specific reason or limitation behind merging them I would love to understand more about it.

**Comment by nextgens** [comment]
- They were too similar to justify the overhead of maintaining both.
- Having both means slower CI, more tests to be done and ultimately more complexity
- There are plans to allow both webmails to run concurrently; It doesn't make much sense to have several instances of HTTPd/FPMs to make that happen, especially now that we aim to allow people to run Mailu on ARM/low-memory environments.
- We have long standing requests about adding "more" webmail options: see #518 for instance

What is the downside of merging them exactly? Having a merged image that's a few megabytes larger?
