### ISSUE TITLE
is:issue is:open how to send mail to @msn.com by mailu

### ISSUE THREAD

**Issue by killghost** [Mailu/Mailu#2595]
### Environment

- [ ] docker-compose
- [ ] kubernetes
- [ ] docker swarm

### Version

- Version: `master`

**Comment by killghost** [comment]
how to send mail to @msn.com by mailu

**Comment by Reinitialized** [comment]
Sounds like you have some DNS configuration issues. One of my favorite things about mailu is how easy it makes to set all of this up as it provides the DNS records you need. Here is an example of the path for getting to those automatically generated records: https://example.com/admin/domain/details/example.com

As for figuring out other issues, such as if your IP is blacklisted, check out these resources:
- https://mail-tester.com/ - Allows you to send emails to its service and it'll analyze whether you have configuration issues or not. More designed for mass sending emails, but still a great tool overall.
- https://intodns.com/ - Gives you a clean view of your DNS settings and whether things are properly configured. It does have one issue to be aware of regarding `MX name validity`. You can read about that specific issue here https://community.cloudflare.com/t/the-mx-records-that-do-not-seem-valid-hostname/427795/2

Hopes this helps with getting your mail server up and going!
