### ISSUE TITLE
The IP you're using to send mail is not     authorized to 550-5.7.1 send email directly to our servers.

### ISSUE THREAD

**Issue by liusijun** [Mailu/Mailu#2599]
I failed to send an email to gmail. Is there a solution to this problem?

host alt1.gmail-smtp-in.l.google.com[142.250.141.26]
    said: 550-5.7.1 [47.98.50.1] The IP you're using to send mail is not
    authorized to 550-5.7.1 send email directly to our servers. Please use the
    SMTP relay at your 550-5.7.1 service provider instead. Learn more at 550
    5.7.1  https://support.google.com/mail/?p=NotAuthorizedError
    j15-20020a056a00234f00b0057a8accf94dsi11536503pfj.261 - gsmtp (in reply to
    end of DATA command)

**Comment by Pinkbyte** [comment]
Out of curiosity: did you have properly configured SPF and DKIM for your domain?

**Comment by micw** [comment]
Definitively not an issue with mailu but with google and/or your IP setup. I have started to write a tutorial which also includes some paragraphs regarding this: https://github.com/micw/mailu-setup-bare-metal/blob/master/step_03_deploy_mailu.md#warm-up-and-white-list-your-mailserver
I never had an issue with google, so there is no section for it in the document. But configuring spf/dkim/dmark as suggested above might be a good start.
