### ISSUE TITLE
Remove unused split repositories

### ISSUE THREAD

**Issue by kaiyou** [Mailu/Mailu#260]
This is mostly a question to @curry684, it seems to me the split read-only repositoried are mostly unused. Should we get rid of them?

**Comment by curry684** [comment]
They're not harming anyone really are they? I'm just back from holiday, but I just ran the update script again as I do periodically, so they should be fully up to date again.

Keyword is "mostly" I think, as long as it provides value to someone out there repositories are still free on Github 😄

**Comment by kaiyou** [comment]
I guess you are right, I was afraid you were not around anymore to keep updating them. Thank you :)

**Comment by curry684** [comment]
I have an internal server migration coming up next few months, by that time I'll set up a permanently webhookable splitter frontend and let you know so we can fully automate them.

**Comment by curry684** [comment]
I archived the split repos today, it's not practical to keep them up to date with invasive changes in the main repository.
