### ISSUE TITLE
Error trying to generate a simple setup

### ISSUE THREAD

**Issue by Igcorreia** [Mailu/Mailu#2600]
I have tried everything in my power to try to generate a setup but I had no luck.
Ideally, I want to create a setup with the following subdomain, for example:
[continuent][number].[service].[domain].[extension]and it looks like this:
us01.emailserver.google.com

### Environment

- [X ] docker-compose

### Version

- Version: `master` -> 1.9.3

mailu/setup:1.9.43 "/bin/sh -c 'gunicor…"   9 minutes ago    Up 6 minutes 0.0.0.0:72912->80/tcp, :::72912->80/tcp       mailnu

## Description

Find the SETUP docker image, load it, I only have master as an option,
Visit the setup page and try to configure a domain using sqllite,
no matter what I test it always fails.

## Observed behaviour

https://user-images.githubusercontent.com/1076409/209596232-9f5d1529-d0cd-442e-8ebd-ee28be319a15.mp4

## Expected behaviour
I expected for a default configuration even if it is not perfect.

## Logs
`172.17.0.1 - - [27/Dec/2022:01:03:28 +0000] "POST /submit HTTP/1.0" 500 290 "https://us01.emailserve.google.com/submit_flavor" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.17.0.1 - - [27/Dec/2022:01:03:30 +0000] "GET / HTTP/1.0" 200 2491 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.17.0.1 - - [27/Dec/2022:01:03:33 +0000] "POST /submit_flavor HTTP/1.0" 200 13987 "https://us01.emailserve.google.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.17.0.1 - - [27/Dec/2022:01:03:41 +0000] "POST /submit_flavor HTTP/1.0" 200 17764 "https://us01.emailserve.google.com/submit_flavor" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.17.0.1 - - [27/Dec/2022:01:04:17 +0000] "POST /submit HTTP/1.0" 500 290 "https://us01.emailserve.google.com/submit_flavor" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.17.0.1 - - [27/Dec/2022:01:06:32 +0000] "GET / HTTP/1.0" 200 2491 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.17.0.1 - - [27/Dec/2022:01:06:35 +0000] "POST /submit_flavor HTTP/1.0" 200 17764 "https://us01.emailserve.google.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.17.0.1 - - [27/Dec/2022:01:06:56 +0000] "POST /submit HTTP/1.0" 500 290 "https://us01.emailserve.google.com/submit_flavor" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
172.17.0.1 - - [27/Dec/2022:01:07:03 +0000] "POST /submit HTTP/1.0" 500 290 "https://us01.emailserve.google.com/submit_flavor" "Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Mobile Safari/537.36"
172.17.0.1 - - [27/Dec/2022:01:14:23 +0000] "POST /submit_flavor HTTP/1.0" 200 17764 "https://us01.emailserve.google.com/" "Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Mobile Safari/537.36"
172.17.0.1 - - [27/Dec/2022:01:14:23 +0000] "GET /master/static/render.js HTTP/1.0" 200 0 "https://us01.emailserve.google.com/submit_flavor" "Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Mobile Safari/537.36"
172.17.0.1 - - [27/Dec/2022:01:14:28 +0000] "POST /submit_flavor HTTP/1.0" 200 17764 "https://us01.emailserve.google.com/submit_flavor" "Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Mobile Safari/537.36"
172.17.0.1 - - [27/Dec/2022:01:14:28 +0000] "GET /master/static/render.js HTTP/1.0" 200 0 "https://us01.emailserve.google.com/submit_flavor" "Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Mobile Safari/537.36"
172.17.0.1 - - [27/Dec/2022:01:14:56 +0000] "POST /submit HTTP/1.0" 500 290 "https://us01.emailserve.google.com/submit_flavor" "Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Mobile Safari/537.36"
[2022-12-27 01:03:22 +0000] [1] [INFO] Starting gunicorn 19.9.0
[2022-12-27 01:03:22 +0000] [1] [INFO] Listening at: http://0.0.0.0:80 (1)
[2022-12-27 01:03:22 +0000] [1] [INFO] Using worker: sync
/usr/lib/python3.9/os.py:1023: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  return io.open(fd, *args, **kwargs)
[2022-12-27 01:03:22 +0000] [7] [INFO] Booting worker with pid: 7
[2022-12-27 01:03:22 +0000] [8] [INFO] Booting worker with pid: 8
[2022-12-27 01:03:22 +0000] [9] [INFO] Booting worker with pid: 9
[2022-12-27 01:03:22 +0000] [10] [INFO] Booting worker with pid: 10
[2022-12-27 01:03:28,262] ERROR in app: Exception on /submit [POST]
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/redis/connection.py", line 492, in connect
    sock = self._connect()
  File "/usr/lib/python3.9/site-packages/redis/connection.py", line 519, in _connect
    for res in socket.getaddrinfo(self.host, self.port, self.socket_type,
  File "/usr/lib/python3.9/socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name does not resolve

`

**Comment by nextgens** [comment]
setup is the tool used to generate the default configurations. You do not need to run your own instance to use Mailu, you can use the one at https://setup.mailu.io to generate the said configuration ; This is all explained in the documentation.

If you really need to, the scripts on https://github.com/Mailu/infra are the ones used under the hood to run the public setup instance. In your particular case, from the stack trace, it looks like you have failed to tell setup where your redis container is.
