### ISSUE TITLE
Proposal: Segregate mailboxes per domain 

### ISSUE THREAD

**Issue by skironDotNet** [Mailu/Mailu#2610]
current structure is hard to manage having `/mailu/mail`:
userA@Adomain.com
userB@Adomain.com
userA@Bdomain.com
userB@Bdomain.com

I think it would better to group mailboxes per "mail domain":
```
/mailu/mail:
   Adomain.com:
      userA
      userB
   Bdomain.com:
      userA
      userB
```

I just migrated off VestaCP and must add @domain to every mailbox, easy via script, but still thinking per domain is nice way of organizing mailboxes

**Comment by sholl** [comment]
hi @skironDotNet ,

you could accomplish your need using a dovecot overwrite in `overwrites/dovecot/dovecot.conf` and insert the following:
```
mail_home = /mail/%d/%n
mail_location = maildir:~/Maildir
```
This results in the following directory-layout:
```
tld1.com
 |
  - user 1
  - user 2
  - user n
tld2.com
 |
  - user 1
  - user 2
  - user n
```

**Comment by ghostwheel42** [comment]
@skironDotNet you can think of the folder structure as raw data of a database you should not mess around with.
We'll need to add some management functions in the future (to remove a mailbox from disk for example) and changing the folder layout via overrides would break this functionality.

What exactly do you need to "manage" here? Listing users and domains can be done using the json/yaml config-export. This could also be used to determine the path of a mailbox "on disk".

You can use this to get the storage root from `docker-compose.yml`:
```
yq -o j x | jq -r '.services.imap.volumes[] | split(":") | select(.[1]=="/mail") | .[0]'
```
And this to get the user mailbox folders:
```
docker exec -i $(docker-compose ps -q admin) flask mailu config-export -j user.email | jq -r '.user[] | .email'
```
So this script would show used space for example:
```
root="$(yq -o j x | jq -r '.services.imap.volumes[] | split(":") | select(.[1]=="/mail") | .[0]')"
while read -r user; do
  du -s "${root}/${user}/"
done < <(
  docker exec -i $(docker-compose ps -q admin) flask mailu config-export -j user.email | jq -r '.user[] | .email'
)
```

**Comment by skironDotNet** [comment]
@nextgens maybe it's not hard to manage, but in theory if you had 20 domains, and you want to move one domain to another server, then it's as easy as `tar` domain folder and un tar on destination server, vs having mailboxes mixed up creates a need for "cherry picking" folder that belongs to a domain x.

Per @ghostwheel42 reply I'm willing to close the proposal, but final question 

What if there are 2+ domains hosted from one mailu instance (this is possible) and you have 2 users with same user name from diffrent domains? having a folder named with user name under `/mailu/mail` would cause a conflict, or am I missing something?

**Comment by nextgens** [comment]
@skironDotNet tar accepts filenames, you can do ``tar cf backup.tar /path/to/mailboxes/*@example.com``

I'll answer for ghost on the second one: We use the full email address: same username but different domains leads to different mailbox folders.
