### ISSUE TITLE
How do I use external redis with a password?

### ISSUE THREAD

**Issue by fruworg** [Mailu/Mailu#2616]
### Environment

- [x] docker-compose

### Version

- Version: `master`

## Description

Hi. I couldn't find a line in the documentation for specifying a password. In nextcloud, it is implemented like this:
REDIS_HOST=\<redis-ip\>
REDIS_HOST_PASSWORD=\<redis-pass\>

**Comment by nextgens** [comment]
Currently this is not an option. Mailu uses several redis databases on the same instance, if we were to support external instances we would have to provide a configuration mechanism too.

Overall a lot of complexity for little gain. If you do want this as a feature request, please spell out the usecase.
