### ISSUE TITLE
DNSSEC - Is the AD Flag in start.py (Admin) the right thing to do?

### ISSUE THREAD

**Issue by jamesarbrown** [Mailu/Mailu#2619]
**Based on this Article**
[https://mailu.io/master/faq.html#the-admin-container-won-t-start-and-its-log-says-critical-your-dns-resolver-isn-t-doing-dnssec-validation](https://mailu.io/master/faq.html#the-admin-container-won-t-start-and-its-log-says-critical-your-dns-resolver-isn-t-doing-dnssec-validation)

**Where the admin container runs this script**
[https://github.com/Mailu/Mailu/blob/master/core/admin/start.py](https://github.com/Mailu/Mailu/blob/master/core/admin/start.py)

**Case 1**
We have a window 2016 dns server, pretty much unremovable due to Active Directory being tied and we also need it to stop steering dns queries outside that are inside.
It does not return a AD flag when queried on example.org
As far as I know thats right... its not authorative.

**Case 2**
We then moved as a trial to our ISP DNS server 80.68.34.6
It does not return an AD flag when queried on example.org
As far as I know thats right... its not authorative.

Its no great abnormal situation to provide an ISP DNS server... so why is this programmed to block startup.....

So is there not a better way based around 
dig @xx.yy.xx.zz +dnssec example.org

Rather than
dig@ xx.yy.xx.zz +adflag......

**Comment by nextgens** [comment]
> Is the AD Flag in start.py (Admin) the right thing to do?

Yes. See https://www.rfc-editor.org/rfc/rfc6840.html#section-5.7 ; Unlike what you seem to believe, it has nothing to do with being authoritative. You are probably confusing ``AD`` with ``AA` which stands for "authoritative answer".

> Its no great abnormal situation to provide an ISP DNS server... so why is this programmed to block startup.....

Most are unsuitable for the operation of an email server (either because they serve lies in responses, are rate limited or do not perform DNSSEC validation), this is why we ship and recommend that people deploy unbound. You should stick to the recommended setup and use unbound.

Case 1 and 2 showcase that we are right: neither of the two resolvers you have configured behave like expected/they should. They most likely do not perform DNSSEC validation.

> dig @xx.yy.xx.zz +dnssec example.org vs dig@ xx.yy.xx.zz +adflag

Please read the RFC linked to above. Mailu does not validate DNSSEC records, it doesn't need them (so setting the ``DO`` flag is not what we need/want). We expect the upstream DNS resolver to do it for us (and check that it did).

**Comment by jamesarbrown** [comment]
Hi,

Ok thanks. I will have to think about this. 

All to do with traffic steering within the domain creates a need for a dns server or split brain approach. 

I appreciate they why.... But also a pity that mailu forces this. Pity the helm does not have ability to disable for testing, headaches etc

The problem for is is that MS DNS server without a great headache must be used for active directory. So that sits in the middle whether we use pihole, unbound, bind etc

And it is the ms server that is not giving the ad flag.... Though it does give a dnsssc key if we check

I have to go into kubedns, change to 1.1.1.1, get mailu up and then revert kubedns, so its bypasable, just a nightmare if the admin pod restarts.

James

**Comment by nextgens** [comment]
GRRRRR. So you are a helm-chart/k8s user? Why didn't you say so earlier?

@jamesarbrown  Which version of Mailu and which version of coredns are you using?

**Comment by jamesarbrown** [comment]
Mailu : 1.9.37
CoreDNS : 1.8.0

**Comment by nextgens** [comment]
Current stable version of Mailu is 1.9.45. It has a workaround for a bug fixed in coredns 1.9.4; see https://github.com/coredns/coredns/issues/5189

So yeah, Mailu is definitely right in pointing out that your DNS stack is broken beyond repair.

**Comment by nextgens** [comment]
For the avoidance of doubt, the solution is to upgrade to the current version of Mailu or your coredns. Their current stable is 1.10.0

``kubectl -n kube-system edit deployment coredns``

**Comment by jamesarbrown** [comment]
Really appreciate the support. Thankyou. I think its working after moving to 1.9.45 and coredns 1.10.0

For others coming here, this is a snippet out of start.py to run in a Python on a console to investigate (needs dnspython eg > pip install dnspython)
 
```
import dns.resolver
import dns.exception
import dns.flags
import dns.rdtypes
import dns.rdatatype
import dns.rdataclass
import time

# DNS stub configured to do DNSSEC enabled queries
resolver = dns.resolver.Resolver()
resolver.use_edns(0, dns.flags.DO, 1232)
resolver.flags = dns.flags.AD | dns.flags.RD
nameservers = resolver.nameservers

#Override
nameservers[0] = '10.8.23.15'
#nameservers[0] = '80.68.34.6'

for ns in nameservers:
  resolver.nameservers=[ns]
  try:
    result = resolver.resolve('example.org', dns.rdatatype.A, dns.rdataclass.IN, lifetime=10)
  except Exception as e:
    print("Your DNS resolver is not working. Please see https://mailu.io/master/faq.html#the-admin-container-won-t-start-and-its-log-says-critical-your-dns-resolver-isn-t-doing-dnssec-validation");
  else:           
    print(result.response)
    if result.response.flags & dns.flags.AD:
      print("IT WORKS")
    else:
      print("Your DNS resolver isn't doing DNSSEC validation; Please see https://mailu.io/master/faq.html#the-admin-container-won-t-start-and-its-log-says-critical-your-dns-resolver-isn-t-doing-dnssec-validation

```

**Comment by cipianpascu** [comment]
with coredns:v1.10.1 and mailu/admin:2.0.10, for me, it still doesn't work.
I run dig from within the cluster and ChatGPT confirmed that dnssec works properly with coredns.

---------------------
dig @10.44.0.10 ciprianpascu.ro. A +dnssec +multiline

; <<>> DiG 9.18.10 <<>> @10.44.0.10 ciprianpascu.ro. A +dnssec +multiline
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 3626
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags: do; udp: 1232
; COOKIE: 46072a15b8905e40 (echoed)
;; QUESTION SECTION:
;ciprianpascu.ro.	IN A

;; ANSWER SECTION:
ciprianpascu.ro.	30 IN RRSIG A 13 2 3600 (
				20230814070820 20230715070820 60682 ciprianpascu.ro.
				1fRSn92pcVEnrh09nDqAEH0KqlIjzLsyHIo+E5fmUS6g
				sK4SXQv/U+b1Zo0dC5Rain30ZX1mjqa4dUMyRrXcEg== )
ciprianpascu.ro.	30 IN A	86.120.147.233

;; Query time: 128 msec
;; SERVER: 10.44.0.10#53(10.44.0.10) (UDP)
;; WHEN: Sat Jul 15 10:48:18 UTC 2023
;; MSG SIZE  rcvd: 213


---------------------------------------

WARNING:root:Disabling hardened-malloc on this CPU
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
updated admin password
CRITICAL:root:Your DNS resolver at 10.44.0.10 isn't doing DNSSEC validation; Please see https://mailu.io/master/faq.html#the-admin-container-won-t-start-and-its-log-says-critical-your-dns-resolver-isn-t-doing-dnssec-validation.
CRITICAL:root:Your DNS resolver at 10.44.0.10 isn't doing DNSSEC validation; Please see https://mailu.io/master/faq.html#the-admin-container-won-t-start-and-its-log-says-critical-your-dns-resolver-isn-t-doing-dnssec-validation.
CRITICAL:root:Your DNS resolver at 10.44.0.10 isn't doing DNSSEC validation; Please see https://mailu.io/master/faq.html#the-admin-container-won-t-start-and-its-log-says-critical-your-dns-resolver-isn-t-doing-dnssec-validation.

**Comment by nextgens** [comment]
@cipianpascu what have you configured upstream of coredns? Is it an instance of unbound like we recommend?

**Comment by cipianpascu** [comment]
> @cipianpascu what have you configured upstream of coredns? Is it an instance of unbound like we recommend?

Thanks for the heads-up Florent. Since it is not that easy to change the default coreDns instance, I just changed the configuration by amending the forward directive:

        forward . 8.8.8.8 8.8.4.4 {
           max_concurrent 1000
        }
Kind regards,
Ciprian
