### ISSUE TITLE
Feature Request: Mailing-Lists with sender-whitelist

### ISSUE THREAD

**Issue by MrSteelMiner** [Mailu/Mailu#2626]
Hello there,
First: Many thanks for this great project!

I run a small club and would like to create a mailing list to send an email to every member of the club. For this I use the "Alias" function. Unfortunately, this mailing list is then publicly addressable. I would like to limit this to selected sender addresses. 

Is this somehow possible with the existing feature set? Otherwise I have marked the ticket as a feature request.

**Comment by ghostwheel42** [comment]
Hi. I'd say this is out of scope for a Mailserver.
For lots of recipients a mailing list software should be used.
For a "small club" you can create a contact group in roundcube webmail and add all entries to BCC by holding shift when selecting the first & last contact in the group.
You Email-Client probably has a similar feature when using BCC.
Alex

**Comment by ghostwheel42** [comment]
@MrSteelMiner I think maybe you could do this by configuring "sieve" rules using the roundcube client (Settings - filters).
This would be my no means secure, though.
Just create a filter matching your sender address(es) and forward to the member addresses.

**Comment by ghostwheel42** [comment]
This would look like this:
<img width="846" alt="roundcube-filters" src="https://user-images.githubusercontent.com/8457866/216759510-f166c96b-afb2-4b30-b06d-70fec75d94cd.png">
