### ISSUE TITLE
add another web server to Mailu/Nginx configuration

### ISSUE THREAD

**Issue by alexsalex** [Mailu/Mailu#2635]
Thank you for greit Mail server.

Have only question... I have some other services on my host with web interface.

How can I change nginx.conf or add another "server" for Nginx???

I don't want to install another nginx container or something like this. Would like to use maul/nginx for it.

**Comment by ghostwheel42** [comment]
This is for issues with Maiu. Please ask questions in the Matrix channel:
https://mailu.io/1.9/faq.html#where-to-ask-questions
I think it's currently only possible to host another domain using [another proxy](https://mailu.io/1.9/reverse.html) in front.
But the [overrides feature](https://mailu.io/1.9/faq.html#how-can-i-override-settings) could be improved to do this

**Comment by alexsalex** [comment]
This is future request for mailu nginx container!
This is related to "front" container.

The point: I DONT WANT TO INSTALL 100500 nginx containers on one host! I would like to use front nginx container fow my ONLY ONE site on the same server where mailu installed.

Right now I use it like this:
1. Crate share from container to host: "-v /mailu/nginx:/etc/nginx"
2. Run container once to create the files
3. Make this share RO
4. Edit nginx.conf to add ONLY one line: "include /etc/nginx/conf.d/*.conf" in to HTTP section (NOT IN SERVER SECTION like the wrapper folder do)
5. Restart the container and enjoy

SO I WOULD LIKE TO DO NOT DO ALL THIS STAFF. Its not impact enything if Mailu team in the front container allow the "server" configs.


And small suggestion: DO NOT CLOSE THE TICKET UNTILL YOU KNOW THE ISSUE.
