### ISSUE TITLE
Traefik labels are ignored by Traefik

### ISSUE THREAD

**Issue by di-rect** [Mailu/Mailu#2642]
I'm trying to setup mailu behind Traefik which runs great for several of webservices and met certs are generated using the Traefik labels.

When I add the same type of labels tothe front(end) container of Mailu the labels are ignored and no certificate or routing is created. My debug setting in Traefik is not helping me further as well.

Has anyone an idea where to look for ?

Networking is setup all fine for it.

**Comment by ghostwheel42** [comment]
I think you should ask this question in the Traefik project or forum.
There's also a small section about Traefik in the Mailu documentation here:
https://mailu.io/1.9/reverse.html#traefik-as-reverse-proxy

**Comment by di-rect** [comment]
@ghostwheel42 Thanks, I have seen that but there is a lot of stuff missing there.

**Comment by ghostwheel42** [comment]
Okay, the this probably needs some improvement by someone using Traefik.
Maybe asking in the Matrix channel will get you some help:
https://mailu.io/master/faq.html#where-to-ask-questions
The Mailu issues are not a good place to ask questions about other tools like Traefik.

**Comment by di-rect** [comment]
@ghostwheel42 if you close such ticket this will never be solved in public. I'm trying to figure it out but it seems that "something" is missing within the labels and that's why the service is not registered within traefik. I cannot look into the nginx server enough to make sure what is going wrong.
