### ISSUE TITLE
DKIM public key incorrectly prsented in DSN DKIM entry in admin UI

### ISSUE THREAD

**Issue by nazar-pc** [Mailu/Mailu#2645]
### Environment

- [x] docker-compose
- [ ] kubernetes
- [ ] docker swarm

### Version

- Version: `1.9.46`

## Description
On `/admin/domain/details/example.com` "DNS DKIM entry" is formatted incorrectly with extra characters in the middle of the pubic key.

## Replication Steps
Fresh installation resulted in this after clicking "Regenerate keys" for the first time.

## Observed behaviour
I have following DKIM public key:
> MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAujBEEgGB3it/fYqKqW3oWH4JNYKXLrLExwiBnxbEZoJsOIJdteqyziFkTyTtrltJxzqVndouR87LyckG96dlTVvu9G57U0l0yAc6jP8UOVb36M8jrWx0cw9eGtJRo+Qsyx0fNMlwYOkb3HfHrcLeI+yop/L+CgGwpplvCoHBpEU2gz1jp6MeeyHWtSIx4rJopkEdniANsgAVJ0if1yQjO61sIT4MbVcwWnHw2WZTeb/VeKd3UY3UYG/bQ2FVmWrYrCbUx4O5imPbtuZ8VtJYw8HH0MXExlQknaCa1cSvZVpKN47R9KxBtm8s7KBD2bdEux+MxXMf1VA1ArEOXJBOjQIDAQAB

But DNS DKIM entry was this:
> dkim._domainkey.example.com. 600 IN TXT "v=DKIM1; k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAujBEEgGB3it/fYqKqW3oWH4JNYKXLrLExwiBnxbEZoJsOIJdteqyziFkTyTtrltJxzqVndouR87LyckG96dlTVvu9G57U0l0yAc6jP8UOVb36M8jrWx0cw9eGtJRo+Qsyx0fNMlwYOkb3HfHrcLeI+yop/L+CgGwpplvCoHBpEU2gz1jp6MeeyHWtSIx" "4rJopkEdniANsgAVJ0if1yQjO61sIT4MbVcwWnHw2WZTeb/VeKd3UY3UYG/bQ2FVmWrYrCbUx4O5imPbtuZ8VtJYw8HH0MXExlQknaCa1cSvZVpKN47R9KxBtm8s7KBD2bdEux+MxXMf1VA1ArEOXJBOjQIDAQAB"

Note `" "` in the middle of public key, like if it was converted into base64 using CLI tool with some wrapping and didn't expect such large public key.

## Expected behaviour
DNS DKIM entry should look like this instead:

> dkim._domainkey.example.com. 600 IN TXT "v=DKIM1; k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAujBEEgGB3it/fYqKqW3oWH4JNYKXLrLExwiBnxbEZoJsOIJdteqyziFkTyTtrltJxzqVndouR87LyckG96dlTVvu9G57U0l0yAc6jP8UOVb36M8jrWx0cw9eGtJRo+Qsyx0fNMlwYOkb3HfHrcLeI+yop/L+CgGwpplvCoHBpEU2gz1jp6MeeyHWtSIx4rJopkEdniANsgAVJ0if1yQjO61sIT4MbVcwWnHw2WZTeb/VeKd3UY3UYG/bQ2FVmWrYrCbUx4O5imPbtuZ8VtJYw8HH0MXExlQknaCa1cSvZVpKN47R9KxBtm8s7KBD2bdEux+MxXMf1VA1ArEOXJBOjQIDAQAB"

**Comment by ghostwheel42** [comment]
Duplicate #2618
