### ISSUE TITLE
Unable to view Mails in Webmail that contain images

### ISSUE THREAD

**Issue by Simon1511** [Mailu/Mailu#2647]
### Environment

- [x] docker-compose: v2.15.1
- [ ] kubernetes
- [ ] docker swarm

### Version

- Version: `master-arm`

## Description
Opening mails that contain images (NOT as attachment) will fail with following error:

![image](https://user-images.githubusercontent.com/46072379/216782216-646c7942-3c68-4ab6-8fbb-bdde177f6e2e.png)

However opening mails that are text-only or contain images as attachments works just fine.

## Replication Steps
Send yourself a Mail that contains an image, for example by directly inserting it in your Mail client using CTRL+V.

## Observed behaviour
Opening said mail in Webmail will fail with above message (see screenshot). Sending/Viewing mails with images as attachments however works just fine and shows a preview of that image.

## Expected behaviour
The Mail should be viewable, like in any Mail client.

## Logs
Attached as file because they were too long for Github.
[compose.log](https://github.com/Mailu/Mailu/files/10609336/compose.log)

**Comment by nextgens** [comment]
You need to re-run setup and update your docker-compose.yml

Your logs show that your webmail container uses ``/var/www/webmail/`` when ``/var/www/roundcube/`` is current. Odds are you are using the old ``roundcube`` image instead of the new ``webmail``.

Reopen if I am wrong.
