### ISSUE TITLE
can I change `SECRET_KEY` afterwards?

### ISSUE THREAD

**Issue by patzm** [Mailu/Mailu#2652]
### Environment

- [x] docker-compose
- [ ] kubernetes
- [ ] docker swarm

### Version

- Version: `v1.9.46`

## Description
Is it possible to change the `SECRET_KEY` _after_ a setup through `docker-compose` has been dispatched / created? Will changing it through the environment variable ([docs](https://mailu.io/master/configuration.html#common-configuration)) also update the stack's internal state?

**Comment by nextgens** [comment]
``SECRET_KEY`` can be changed if you bring the whole stack down and back up.

Changing the key has some side effects, like invalidating all sessions. All containers need to have the same ``SECRET_KEY``; if they don't things will break.

**Comment by patzm** [comment]
understood. Awesome thanks 🙇
