### ISSUE TITLE
Nginx container "corrupted" because apk is used to install 'nginx-mod-http-lua'

### ISSUE THREAD

**Issue by SunMar** [Mailu/Mailu#266]
Hi,

Not sure if this is really still relevant since I noticed in ```master``` just yesterday you removed Nginx and switched to Traefik, but while setting up Mailu from ```stable``` I noticed this in the Dockerfile for Nginx:

https://github.com/Mailu/Mailu/blob/b40f3f35cae56f1d2c1a0f61dccab47fbfb637bf/nginx/Dockerfile#L3

This actually presents a problem, as you are extending ```nginx:alpine``` it "corrupts" the container. The official Nginx container (as well as others like PHP) compile the software from source and do not use the package repository of the underlying system (in this case Alpine, but the same applies when Debian is used). The package manage (here ```apk```) has no knowledge of that compilation from source, so when you install a package through it like ```nginx-mod-http-lua``` it also pulls in ```nginx```, because that's a dependency and as far as ```apk``` knows it isn't installed. That ```nginx``` package then overwrites the Nginx version installed by the ```nginx:alpine``` container and with that "corrupts" the container. So in short you should not pull in modules or extensions from the package manager for software that's installed in the base container unless you know the base container also uses the package manager.

I was able to resolve this without using Lua by adding in ```start.sh``` the following:

```sh
echo -n > /etc/nginx/environment
echo "set \$webmail '$WEBMAIL';" >> /etc/nginx/environment
echo "set \$webdav '$WEBDAV';" >> /etc/nginx/environment
echo "set \$expose_admin '$EXPOSE_ADMIN';" >> /etc/nginx/environment
```

And then in ```/etc/nginx/nginx.conf``` in the ```server``` block I added ```include /etc/nginx/environment;```. This set the required variables without having to use to Lua (or Perl).

If you want I can create a pull request against the ```stable``` branch, but I guess that would depend on what your timetable is for bumping Traefik to ```stable```. If that is soon(ish) it might not be worth to fix this in ```stable```. The Nginx version in Alphine is 1.10 and the ```nginx:alpine``` container uses the latest 1.13, so there is a (small) risk of introducing new issues through this fix.

**Comment by kaiyou** [comment]
You are perfectly right. I will probably not fix this unless someone decides to maintain a long-term nginx container, but `traefik` is about to become the main reverse proxy for Mailu, as `nginx` was really cumbersome to maintain and integrate in more complex environments.
