### ISSUE TITLE
Missing cert or key file, disabling TLS

### ISSUE THREAD

**Issue by kutay-celebi** [Mailu/Mailu#2666]
### Environment

- [x] docker-compose
- [ ] kubernetes
- [ ] docker swarm

### Version

- Version: `1.9`

## Description
When Mailu is running behind the external reverse proxy, custom SSL certificates are not being recognized by Mailu.

## Observed behaviour
Even though I can see the related certificate files inside the 'front' container's docker volume, Mailu does not recognize certificates that are assigned within `docker-compose.yml` file. This error is logged by `core/nginx/config.py`.

Environment variables is set as below.
```
TLS_FLAVOR=mail
TLS_KEYPAIR_FILENAME=privkey.pem
TLS_CERT_FILENAME=cert.pem
```

Related service configuration on `docker-compose.yml` is as below. 

```yml
  front:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}nginx:${MAILU_VERSION:-1.9}
    restart: always
    env_file: mailu.env
   # ... other settings...
    volumes:
      - "/prod/xxx.domain/certs:/certs"
      - "/mailu/overrides/nginx:/overrides:ro"
      - "/mailu/letsencrypt-log:/var/log/letsencrypt/"
```

Then I saw the following logs on mailu-front: 'Missing cert or key file, disabling TLS'.

## Logs

```
Missing cert or key file, disabling TLS   <--------- Here.
2023/02/15 13:44:04 [notice] 1#1: using the "epoll" event method
2023/02/15 13:44:04 [notice] 1#1: nginx/1.20.2
2023/02/15 13:44:04 [notice] 1#1: OS: Linux 5.4.0-105-generic
2023/02/15 13:44:04 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2023/02/15 13:44:04 [notice] 1#1: start worker processes
2023/02/15 13:44:04 [notice] 1#1: start worker process 11
2023/02/15 13:44:04 [notice] 1#1: start worker process 12
2023/02/15 13:44:04 [notice] 1#1: start worker process 13
2023/02/15 13:44:04 [notice] 1#1: start worker process 14
```

**Comment by ghostwheel42** [comment]
Can you enter the front container and list the contents of the certs folder, please?
```
docker compose exec front ls -l /certs
```

**Comment by weltenseglr** [comment]
Encountered the same problem. Directory is populated and files are accessible:

`#> docker compose -p mailu exec front ls -l /certs
total 24
-rw-r--r--    1 root     root           692 Apr  6 10:33 README
-rw-r--r--    1 root     root          1927 Apr  6 10:33 cert.pem
-rw-r--r--    1 root     root          3749 Apr  6 10:33 chain.pem
-rw-r--r--    1 root     root          5676 Apr  6 10:33 fullchain.pem
-rw-------    1 root     root          1704 Apr  6 10:33 privkey.pem
#> docker compose -p mailu exec front cat /certs/cert.pem
-----BEGIN CERTIFICATE-----
MIIFYjCCBEqgAwIBAgISA0ZKopR7R4....
`

**Comment by weltenseglr** [comment]
Solved for me.
The error message `Missing cert or key file, disabling TLS` was misleading.

When mailu started before my proxy, the files were found AND could be opened, but  the proxy failed to start with a permission denied message.
I copied the certs from /etc/letsencrypt/live/[domain] to certs. Hence, these were symlinks. `cp -L  /etc/letsencrypt/live/[domain]/*  ./certs/` did the trick.

**Comment by Diman0** [comment]
I'm glad you were able to resolve your issue.
