### ISSUE TITLE
Admin and antivirus containers work with resolver's IP but not with resolver's DNS name

### ISSUE THREAD

**Issue by LeVraiRoiDHyrule** [Mailu/Mailu#2672]
Hi,

I am using `master` release and `docker-compose` flavor.
If I set the DNS settings for the admin and the ClamAV antivirus like this, it works:
```yaml
    dns:
      - ${MAILU_NETWORK_IP}.254
```
But like this, using the DNS name of the resolver, it doesn't work:
```yaml
    dns:
      - mailu-resolver
```

It leads to the following error:
```
CRITICAL:root:Your DNS resolver at 127.0.0.11 is not working (The resolution lifetime expired after 11.602 seconds: Server 127.0.0.11 UDP port 53 answered The DNS operation timed out.; Server 127.0.0.11 UDP port 53 answered The DNS operation timed out.; Server 127.0.0.11 UDP port 53 answered The DNS operation timed out.; Server 127.0.0.11 UDP port 53 answered The DNS operation timed out.; Server 127.0.0.11 UDP port 53 answered The DNS operation timed out.). Please see https://mailu.io/master/faq.html#the-admin-container-won-t-start-and-its-log-says-critical-your-dns-resolver-isn-t-doing-dnssec-validation
```
Those are the only 2 containers that have problems with the DNS name of the resolver. All other containers (imap, smtp...) works perfectly with the DNS name.

It isn't a big problem, I've just set the resolver's IP for both now.

EDIT : it causes problems with the SMTP container too, that is unable to find relayhosts if DNS name is set.

**Comment by nextgens** [comment]
This is a limitation of docker compose: you have to specify the IP address, see https://docs.docker.com/config/containers/container-networking/#dns-services

Not something Mailu can fix, nor something we set by default if you use setup.
