### ISSUE TITLE
Add API documentation?

### ISSUE THREAD

**Issue by jt0dd** [Mailu/Mailu#2673]
I see the API feature was marked completed recently, but I don't see any documentation on how it works? https://github.com/Mailu/Mailu/commit/bbf0ac5d477c866281ae07bcc13dfcffc637c14e

**Comment by ghostwheel42** [comment]
The documentation can be found here https://mailu.io/master/api.html, here https://mailu.io/master/configuration.html#advanced-settings and here https://test.mailu.io/api/v1/

**Comment by jt0dd** [comment]
@ghostwheel42 Ahh ok I was looking at 1.9 documentation.
