### ISSUE TITLE
is there a way to enable the showq socket

### ISSUE THREAD

**Issue by bunix42** [Mailu/Mailu#2679]
### Environment

- [x] docker-compose
- [ ] kubernetes
- [ ] docker swarm

### Version

- Version: `1.9`

## Description

I would like to collect some telemetry for my mailserver an wanted to use the [kumina/postfix-exporter](https://github.com/kumina/postfix_exporter) which relies on parsing the postfix logs on the one hand, and checking the showq socket for the queue status.

With my default setup of now showq socket is available, thus the exporter does not work. I am not deep enough in the postfix topic so maybe someone here on the team knows of a solution?

**Comment by ekrekeler** [comment]
I just ran into the same problem. Did you ever figure it out?
