### ISSUE TITLE
snappymail healthcheck fails

### ISSUE THREAD

**Issue by leolivier** [Mailu/Mailu#2684]
### Environment

- [x] docker-compose
- [ ] kubernetes
- [ ] docker swarm

### Version

- Version: `master-arm`

## Description
Snappymail healthcheck fails with the following message:
`OCI runtime exec failed: exec failed: unable to start container process: error starting setns process: fork/exec /proc/self/exe: no such file or directory: unknown`
I tried to execute the health check from the outside like this: `docker exec -it  mailu.webmail curl -f -L http://localhost/ping` 
but I got the same error, so I tried simpler: `docker exec -it  mailu.webmail  sh`, still the same error...

Nevertheless, snappymail is up and running! I can connect to it and look at my emails, mark them read, delete them, ...

## Logs
Log is totally empty!

**Comment by nextgens** [comment]
"unable to start container process" means that something is wrong with your host.

Running current master:
```
# docker exec -it mailu-webmail-1 sh
/app # ldd /bin/sh 
	/lib/ld-musl-aarch64.so.1 (0xffffb7a6d000)
	libc.musl-aarch64.so.1 => /lib/ld-musl-aarch64.so.1 (0xffffb7a6d000)
```

**Comment by leolivier** [comment]
Right @nextgens, although the container was up and running (I was able to see my emails), it had an issue.
I recreated it and it's now working again.
Sorry for bothering you with nothing
