### ISSUE TITLE
How can I use Amazon SES with Mailu, Please help

### ISSUE THREAD

**Issue by medram** [Mailu/Mailu#2689]
Hello everyone,

I would like to use Amazon SES for my outgoing email (all my emails or just particular ones),
Does anyone have any ideas?

Thanks in advance.

**Comment by nextgens** [comment]
You can use the ``RELAYHOST`` settings

See https://mailu.io/master/configuration.html#mail-settings

**Comment by medram** [comment]
Thank you, it's very appreciated :smile:
