### ISSUE TITLE
Traefik Letsencrypt on port 80

### ISSUE THREAD

**Issue by SunMar** [Mailu/Mailu#269]
Hi,

Is it possible to setup Traefik in such a way that it allows Letsencrypt on port 80? The reason is that I want to put the webmail and admin interfaces behind a firewall so they're not publicly exposed but still use Letsencrypt. The webmail and admin shouldn't be available over port 80. Ideally there wouldn't even be a service running on port 80 except for the moment the Letsencrypt/ACME challenge is done.

I don't mind giving a go at this myself but I'm not familiar with Traefik and don't really know where to start.

**Comment by kaiyou** [comment]
This would indeed be nice. I am preparing a couple of PR for `traefik`, so I might just as well have a look into this (I do not believe it is currently supported, as being kind of counter-intuitive!)

**Comment by SunMar** [comment]
An alternative solution if Traefik doesn't support doing Letsencrypt only on port 80 so it's possible to lock down port 443 would probably be create to a separate Docker container just for Letsencrypt which can generate (and renew) the certificates. Similar in the way it was previously done with Letsencrypt, though I guess that'd be more work to maintain. I do see various containers on Docker Hub that setup Letsencrypt in its own container including automatic renewal like https://hub.docker.com/r/blacklabelops/letsencrypt/.

It would be fine too to have Traefik just run without TLS on a custom port like 8080, then you can put your own proxy/loadbalancer in front of it with TLS termination, but there's still not really getting around Letsencrypt for the other services (IMAP/SMTP) if you want to automate the certificates.

**Comment by kaiyou** [comment]
This will be related to #272 and could actually be implemented then if we succeed.

**Comment by svengo** [comment]
I'm using https://github.com/jwilder/nginx-proxy and https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion to manage certificates without any problems. It would be easy for mailu to integrate these containers.

**Comment by kaiyou** [comment]
Nginx-proxy unfortunately does not offer a customizable enough template to be integrated out of the box. Regarding the letsencrypt companion, it works by mounting the Docker socket, which I would rather avoid as much as possible, because 1. security, of course 2. not everyone is using plain Docker for running Mailu.

**Comment by kaiyou** [comment]
This is not relevant anymore as nginx has been reintroduced instead of traefik.
