### ISSUE TITLE
CalDav in Roundcube not working with configured proxy

### ISSUE THREAD

**Issue by dasbenjo** [Mailu/Mailu#2693]
### Environment

- [x] docker-compose
- [ ] kubernetes
- [ ] docker swarm

### Version

- newest Version: `master`

## Replication Steps

- install newest version of mailu
- configure it to use proxy signin (I use authentik and nginx as an reverse proxy and use `mailu.domain.name` and `/webmail` for the roundcube location)
- try to add any caldav connection in roundcube (I tried internal and external ones)

## Observed behaviour

If I try to add Caldav calendars via the caldav plugin of Roundcube in Mailu. I get the red message, "an error occured"

## Expected behaviour

The calendar config should be added

## Logs

the logs show this error:

`2023/03/09 17:32:28 [error] 14#14: *19422 FastCGI sent in stderr: "PHP message: PHP Fatal error:  [snuffleupagus][0.0.0.0][disabled_function][drop] Aborted execution on call of the function 'ini_get', because its argument '$option' content (allow_url_fopen) matched a rule in /var/www/roundcube/vendor/guzzlehttp/guzzle/src/Utils.php on line 100" while reading response header from upstream, client: 192.168.XXX.XX1, server: , request: "POST /?_task=settings&_framed=1&_action=plugin.carddav.AccAdd HTTP/1.1", upstream: "fastcgi://unix:/var/run/php8-fpm.sock:", host: "192.168.XXX.XX2", referrer: "https://mailu.domain.name/webmail/?_task=settings&_framed=1&_action=plugin.carddav.AccDetails&accountid=new&_nav=hide"`

`192.168.XXX.XX1` is the reverse proxy with nginx
`192.168.XXX.XX2` is the mailu server with mailu docker containers

**Comment by nextgens** [comment]
@dasbenjo if you could test the PR and report back that would be great.

The CI tools will push ready-to-test images to https://hub.docker.com/r/mailuci/webmail/tags

**Comment by dasbenjo** [comment]
wow, this was quick, I'll try to test it at the weekend 💪😊

**Comment by dasbenjo** [comment]
@nextgens I tried now with the new image, but again I got the same error in the logs, when I try to add an external calendar

**Comment by nextgens** [comment]
Hmm, that's weird, it works here.

![image](https://user-images.githubusercontent.com/77500/224545463-1ca432e0-f753-4d7a-bdc9-bfa83f2d3cc0.png)

Can you do a ``docker compose exec webmail cat /version`` to ensure you are running the right image please?

**Comment by dasbenjo** [comment]
I've tested it with `pr-2660` and because it was pulished only minutes ago, also with `pr-2697`
everytime the same error, as I got in the beginning :(

**Comment by nextgens** [comment]
@dasbenjo the tag you need is ``pr-2694``

**Comment by dasbenjo** [comment]
oh I see, sorry, I'll try again

**Comment by dasbenjo** [comment]
yes, everything works, thank you very much for your effort! 🎉🎉🥳
