### ISSUE TITLE
snappymail master-arm tag disappeared?

### ISSUE THREAD

**Issue by leolivier** [Mailu/Mailu#2698]
Hi
I'm not sure of what is the status of snappymail in mailu to replace rainloop?
Anyway, I used to install/upgrade it with the tag 'master-arm' since months and this tag suddenly disappeared (last week as far as I can tell). 
Now, there is an arm-v7 version on 'latest' tag and that's all (no arm 64 version anymore).
So, I know this is not something really supported by mailu for now but it would be great to have a status on this
Thank you!

**Comment by nextgens** [comment]
You are using the wrong image; it's now called "webmail". Please re-run setup as there are other significant changes that have been made.
