### ISSUE TITLE
URL for traefik dashboard

### ISSUE THREAD

**Issue by SaiGonSeamus** [Mailu/Mailu#270]
It should be admin no?

All I see is the old admin dashboard, am I missing a trick here?

**Comment by kaiyou** [comment]
Mmmh, we are using `traefik` as a reverse proxy, it is definitely not intended to replace the admin dashboard. We could display the `traefik` dashboard, which show some statistics about web access, but it really merely is a Web reverse proxy, not an email management solution with a proper mail admin dashboard :)

**Comment by SaiGonSeamus** [comment]
OK, my mistake. I was under the impression that it was going to be used for a GUI for managing certs.

**Comment by kaiyou** [comment]
Nope, it was involved in improving the letsencrypt integration because it embeds an amazing letsencrypt implementation with automatic renewal and a way to simply export certificates, but that's mostly under the hood
