### ISSUE TITLE
Switch from docker hub to ghcr.io (github)

### ISSUE THREAD

**Issue by Diman0** [Mailu/Mailu#2704]
EDIT:
To switch to the images on ghcr.io.
1. Stop the containers `docker-compose down`
2. Create the file `.env` in the same folder as `docker-compose.yml` with the contents:
```
DOCKER_ORG=ghcr.io/mailu
```
3. Start the containers. `docker-compose up -d`
4. Check that the images from ghcr.io are used. `docker-compose ps`

old post:
https://blog.alexellis.io/docker-is-deleting-open-source-images/
https://news.ycombinator.com/item?id=35166317

Docker has decided to shutdown all 'Free Team organizations'. Mailu also makes use of this. So we have to move to a different registry for the production images. Ghcr.io (github) is already used for everything but the 1.9 images.

To use it, prefix the image path with ghcr.io. E.g.
Instead of `docker pull mailu/admin:master`
use: `docker pull ghcr.io/mailu/admin:master`
or for testing images: `docker pull ghcr.io/mailu/admin:pr-2703`

Tasks that must be done for switching:

- Modify the CI.yml (github action) to only use ghcri.io. So modify the step for copying images from ghcr.io to docker hub.
- Update setup (docker-compose.yml template) to use ghcri.io.
- Update instructions in the documentation to use ghcr.io. At least the section describing how to pull PR images must be modified.

After the switch has been made, we have to decide if we remove all images from docker. This should give a wake up call to people who never visit the website.

**Comment by nextgens** [comment]
I think we should pull the images from docker.

**Comment by nextgens** [comment]
```
$ docker pull ghcr.io/mailu/admin:1.9
1.9: Pulling from mailu/admin
cfab2db72209: Already exists 
63b4f274b36b: Downloading  23.27kB/2.316MB
25d22240b812: Downloading  326.8kB/31.77MB
18bd49581c3c: Download complete 
2a4310c28b59: Waiting 
28eb761abe90: Waiting 
f189367b7eb5: Waiting 
df72642e9ce1: Waiting 
242b3dbc5c07: Waiting 
953e528a7c8a: Waiting 
12c4e5c8b3f0: Waiting 
f94cfefb5974: Waiting 
192e50d4a3ee: Pulling fs layer 
```

**Comment by vahidalvandi** [comment]
very good idea
