### ISSUE TITLE
The admin panel is not loaded in roundcube

### ISSUE THREAD

**Issue by nike7o0** [Mailu/Mailu#2731]
## Environment & Version
1.9.50
### Environment

- [x] docker compose
- [ ] kubernetes
- [ ] docker swarm

### Version

- Version: `1.9.50`

## Description
The admin panel is not loaded in roundcube.

## Replication Steps
Use mailu/roundcube:1.9.50

## Observed behaviour
When you open roundcube, you can login only in the mail, but not in the admin interface.

**Comment by nextgens** [comment]
As far as I know roundcube doesn't have any admin panel. What are you referring to?

**Comment by nike7o0** [comment]
Cannot login to the admin UI, i am going to try the new docker-compose first.

**Comment by nike7o0** [comment]
It was my bad, please close the ticket.
