### ISSUE TITLE
Email management solution

### ISSUE THREAD

**Issue by SaiGonSeamus** [Mailu/Mailu#274]
We are using Mailu for a small consumer offering shortly.

Does anyone has any recommendations for what they use so that new customers can check email availability, add an account & change password?

**Comment by kaiyou** [comment]
You mean, register and/or buy an account? or pay monthly for the account?

**Comment by SaiGonSeamus** [comment]
No that is all handled by the membership website already.
Just checking if the account name they want is not already taken then entering the account name, a password twice and setting you their account.
Also to be able to change their password within rainloop would be nice.

**Comment by kaiyou** [comment]
If you only need to check the account availability and create it if available, I believe until we have a proper API that writing to the database would be just fine.

Regarding password change in the Webmails, I am fairly opposed to it, unless we find a proper way that does not require accessing the database directly, i.e. an API endpoint, or for now a link to the admin page.

**Comment by SaiGonSeamus** [comment]
I hadn't checked the admin panel as a non-admin user, that will do fine.
