### ISSUE TITLE
Retrieving messages via pop3 fails

### ISSUE THREAD

**Issue by AndreasKl** [Mailu/Mailu#2754]
I upgraded my Mailu installation from 1.8 to 2.0.2. After the upgrade pop3 stopped working.

### Environment

- [x] docker compose
- [ ] kubernetes
- [ ] docker swarm

### Version

- Version: `2.0.2`

## Description
When connecting via pop3 password authentication fails due to an unexpected error. The same issue occurs on the Mailu test environment:

```bash
openssl s_client -crlf -connect test.mailu.io:110 -starttls pop3

USER admin@test.mailu.io
+OK
CAPA
+OK Capability list follows
TOP
UIDL
RESP-CODES
PIPELINING
AUTH-RESP-CODE
USER
SASL PLAIN LOGIN
.
PASS letmein
-ERR Unknown command.
+OK
closed
```

## Observed behaviour

> -ERR Unknown command.

Is returned when a valid password is provided via pop3.

## Expected behaviour
pop3 responds with an +OK when a valid password is passed.

## Workaround

I guessed the breaking change was in the front (nginx) config, as the dovecot config looked not suspicious.

So I removed the following two lines:

https://github.com/Mailu/Mailu/blob/399345e796a4e16961f6e4f218bc0a0356a82286/core/nginx/conf/nginx.conf#L415

https://github.com/Mailu/Mailu/blob/399345e796a4e16961f6e4f218bc0a0356a82286/core/nginx/conf/nginx.conf#L463

and pop3 started to work again on my server.

```text
USER mail@######.net
+OK
CAPA
+OK Capability list follows
TOP
UIDL
RESP-CODES
PIPELINING
AUTH-RESP-CODE
USER
SASL PLAIN LOGIN
.
PASS ##################
+OK Logged in.
```

**Comment by nextgens** [comment]
Thank you for your report. It's actually the dovecot config that needs tweaking; nowadays we "talk" proxy protocol in between nginx and dovecot ... but that hasn't been configured for pop3.

**Comment by nextgens** [comment]
2.0.4 should be out momentarily, it will fix the problem
