### ISSUE TITLE
iOS client apps are not able to add accounts

### ISSUE THREAD

**Issue by kavolorn** [Mailu/Mailu#2755]
### Environment

- docker compose

### Version

- Versions: `1.9`, `2.0`

## Description

From iOS device mailing clients are not working. Tested old iPhone 7 and iPhone 13.

## Replication Steps

Mauilu setup is the following:

1. I'm running Mailu 1.9 behind Traefik proxy. 
2. There are multiple domains configured.
3. TCP routes are configured on 443, 25, 587, 110, 143, 465, 995, 993
4. TLS passthrough enabled on 443, 465, 995, 993
5. Proxy protocol 2 enabled on 25, 587, 110, 143, 465, 995, 993. Also added required Nginx proxy_protocol. Issue tested even without proxy protocol, so it is not the core of problem.

Let's encrypt enabled on the `front` proxy, working well.

## Observed behaviour

Trying to add account on iOS devices and not able to achieve it. On Harmony OS and OS X clients (many tested) everything works.

I tried to install root certificates from letsencrypt just in case. I did not make any difference.

I tried to see debug logs for Gmail and Yandex apps and I saw something related to stapling. Then I made the following experiment:

1. I added params `"--hsts", "--staple-ocsp", "--must-staple",` to certbot command from letsencrypt.py
2. I cleaned certificates and received new ones. I saw extra section "must straple" appeared in the certificate.
3. I tested iOS apps.

I got Yandex app working somehow with this modification! I don't know how, because stapling is not configured on imap/smtp. I assume "must staple" unblocked something.

But with Gmail still the same crap. I don't know which trick can help to go deeper into the problem. I see connection is coming to the `front` container but then it is rejected most probably from the app itself because of not know reason.

## Expected behaviour

I expect iOS client apps to be working.

## Logs

Everything seems working fine except for iOS clients. I can sent main, receive mail for all domains.

**Comment by nextgens** [comment]
nginx isn't able to staple things that aren't on port 443. By adding must-stapple to your certificate you most likely broke things.

Can you connect your clients onto https://test.mailu.io/ with ``admin@test.mailu.io`` and ``letmein`` ?

**Comment by kavolorn** [comment]
Yes, I see on the nginx config that staple not enabled on non-443 ports.

All my clients (mailspring, thunderbird, roundcupe, yandex on harmony os, native on harmony os and maybe few forget) are working with `must-staple` addition to certificate. Not as it was expected. Somehow additionally yandex client on iOS and native client on iOS started working with this extra bit in certificate as well.

But gmail is not working in any case. I think it is waiting for a valid OCSP response which is not coming for non 443 ports.

Is there any strategy to enable a valid OCSP response?

**Comment by nextgens** [comment]
Some clients are working because they ignore the said extension :)

Check with openssl as follow:
```
openssl s_client -crlf -connect $SERVER:$PORT -status -tls1_2
```

You will see that when it works you get:
```
OCSP response: 
======================================
OCSP Response Data:
    OCSP Response Status: successful (0x0)
...
```

For HTTP ports we use http://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_stapling ... and it just doesn't exist for the other modules (stream and mail), see http://nginx.org/en/docs/stream/ngx_stream_ssl_module.html for instance.

No, there isn't any way to do it using nginx... you could add a proxy in front that may be able to serve OSCP responses... or alternatively you could renew your cert without must_staple.

**Comment by kavolorn** [comment]
> Some clients are working because they ignore the said extension :)

I'm not sure if you clearly read, that I'm saying the opposite :) I got +2 clients app WORKING AFTER adding must stapling flag into certificate (without sending response of cource).

I was checking OCSP responses and it is working as configured and as you described. Successful for 443 and not present for other ports.


Question remains the same... How to work with Mailu on iOS? :(

**Comment by kavolorn** [comment]
I did the following exercise:

```
openssl s_client -crlf -connect imap.gmail.com:993 -status -tls1_2 
```

I also don't see there OCSP response. So probably Gmail app is blocked by something else.

**Comment by nextgens** [comment]
Again: you have found clients that do work despite must-staple being enabled. Those clients work because they do not implement/follow must-staple.

I am not sure of what you are trying to point out by showing that gmail is not using must-staple nor sending OSCP stapled responses. 

Your Mailu configuration is hosed because you have enabled must-staple. Just disable it and get new certificates.

**Comment by kavolorn** [comment]
You are not reading carefully what is written.

I added "must staple" only for experiment. **Because nothing was working.** And it helped for some clients and I wrote it as a full picture for the reader to understand my attempts for find the issue. I have no glue about mailing internals and providing as much information as possible.

iOS clients are not working without "must staple" flag. My initial question remains the same.

**Comment by nextgens** [comment]
I am sorry to have misunderstood your report that is all over the place. I'll let someone with more patience than me go through it.

It would help if you did clarify what version of Mailu you are running and provided logs.

haproxy/proxy protocol is not supported in 1.9.
1.9 is not the current stable version of Mailu.

**Comment by kavolorn** [comment]
No problem. Issue requires some time to align brains with it.

Good question about proxy protocol. I checked current version with implementation of proxy protocol. My implementation on top of 1.9 was the same. Let's also close this direction of thoughts as well. Because issue remains the same if I disable PROXY protocol.

Let me try to summarise my setup:

I have Traefik + Mailu 1.9 (latest docker images) with 3 domains in the configuration. Ports configured as described in the initial description. All domains have valid DNS records. I received correctly certificate from letsencrypt with SANS records for all 3 domains. Visually everything works except for iOS device clients.

1. When I try to add account in the native mailing app it is freezes.
2. When I try to add account in the yandex mail and in the google main they fail very fast.
3. I'm watching the log of `front` container and I see attempt of connection to 993. Much later I see timeout error for this attempt.

So, I see that traffik is reaching the desired mailu component. I think something wrong in the TLS negotiation.

My attempt to check certificate from ports shows correct certificate.

**Comment by kavolorn** [comment]
@nextgens I upgraded my version to latest one. I'm still seeing gmail app not able to connect to mailu. So, this ticket is valid and I will update version in the initial description.
