### ISSUE TITLE
Postfix master.cf override broken due to missing new line

### ISSUE THREAD

**Issue by Lex999** [Mailu/Mailu#2757]
### Environment

- [x] docker compose
- [ ] kubernetes
- [ ] docker swarm

### Version

- Version: `2.0`

## Description

When transferring the master.cf from /conf/ to /etc/postfix in the postfix startup script, the final new line character is stripped. The first line of the postfix.master override is appended to /etc/postfix/master.cf without this newline character as separator. Consequently, it does not take effect.

## Replication Steps
Add the following override in overrides/postfix/postfix.master.

```
showq/unix=showq unix n - n - - showq
```

## Observed behaviour
Last line of /etc/postfix/master.cf inside postfix container is:

```
postlog   unix-dgram n  -       n       -       1       postlogdshowq      unix  n       -       n       -       -       showq
```

## Expected behaviour
Last lines of /etc/postfix/master.cf inside postfix container should be:

```
postlog   unix-dgram n  -       n       -       1       postlogd
showq      unix  n       -       n       -       -       showq
```

## Solution Suggestion

Add another new line charachter to the end of the original master.cf (as it was in version 1.9) or avoid stripping the last new line character in the startup script.

**Comment by nextgens** [comment]
2.0.4 should be out momentarily, it will fix the problem
