### ISSUE TITLE
Autodiscover.xml insists on API_TOKEN

### ISSUE THREAD

**Issue by TerrapinSoftware** [Mailu/Mailu#2763]
### Environment

- [x ] docker compose
- [ ] kubernetes
- [ ] docker swarm

### Version

- Version: `2.0`

## Description

I am not sure if it is me or a real problem. The URL `/Autodiscover/Autodiscover.xml` complains about an unconfigured API-TOKEN. When configured, thre is a 405 Method Not Allowed error. To me, it seems that the URL wants to call the REST API, which is not enabled.

Mailu is behind an nginx reverse proxy. See config file attached.

## Replication Steps

Install Mailu without enabling the REST API, then load the URL above.

## Observed behaviour

See above. All other autodiscover options plus MTA-STS are working fine.

## Expected behaviour

The Autodiscover XML file should be returned.

## Logs

None.

## nginx Config

Nothing special.

```nginx
server {
  server_name mail.terrapinlogo.com ~^mta-sts.[a-z]+?\.com;
  access_log /var/log/nginx/mail.access.log;
  error_log /var/log/nginx/mail.error.log;

  add_header X-Content-Type-Options nosniff always;

  include snippets/ssl.conf;

  location / {
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_pass https://localhost:28443;
  }
}

server {
  server_name mail.terrapinlogo.com;
  access_log /var/log/nginx/mail.access.log;
  error_log /var/log/nginx/mail.error.log;
  
  listen 80;

  location / {
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_pass http://localhost:28080;
  }
}
```

**Comment by BluemediaGER** [comment]
Outlook actually makes a POST request to the XML endpoint if it knows the email address / UPN. So I think that this behavior is intentional. The corresponding route only handles POST requests:
https://github.com/Mailu/Mailu/blob/1b7de128c943ca68797b3be2b479e9e40631a52a/core/admin/mailu/internal/views/autoconfig.py#L54

**Comment by TerrapinSoftware** [comment]
Thank you for the info! I was just testing all autodiscover endpoints, not realizing the POST request requirement.
