### ISSUE TITLE
update mailu error

### ISSUE THREAD

**Issue by hungx1212** [Mailu/Mailu#2774]
V1.9 run: docker compose pull
Error response from daemon: pull access denied for mailu/admin, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Comment by prutseltje** [comment]
I'm having the same issue. It seems that the images are removed.

**Comment by elmanuel127** [comment]
Mailu has updated where the images are hosted. You will need to download a new mailu.env and docker-compose.yml or edit your files accordingly.

see: [https://github.com/Mailu/Mailu/releases](https://github.com/Mailu/Mailu/releases)

**Comment by nextgens** [comment]
https://github.com/Mailu/Mailu/issues/2704 has instructions on what to do
