### ISSUE TITLE
return-path domain is overwritten incorrectly for aliased emails

### ISSUE THREAD

**Issue by MurrayGroves** [Mailu/Mailu#2782]
### Environment

- [x] docker compose
- [ ] kubernetes
- [ ] docker swarm

### Version

- Version: `1.9`

## Description

When using an email alias to forward an email to another inbox the `return-path` header is overwritten with the wrong domain name. This results in it failing SPF.

## Replication Steps

- Add an alias. E.g. `%@mydomain.com` -> `catchall@mydomain.com`
- Receive an email to that alias. E.g. an email from `sender@theirdomain.net` to `receiver@mydomain.com`
- Check inbox for alias target. E.g. `catchall@mydomain.com`. I used Gmail which highlighted the SPF issue.
- `return-path` has been rewritten to `sender@mydomain.com`. This causes SPF to fail as obviously the IP no longer matches.

## Observed behaviour
Email from `sender@theirdomain.net` has `return-path` overwritten to `sender@mydomain.com`

## Expected behaviour
`return-path` should be preserved as `sender@theirdomain.net`

## Logs
[Email Source](https://pastebin.com/r9m6Hda3)
[mailu-smtp-1 logs](https://pastebin.com/m2BXuvhB)

**Comment by nextgens** [comment]
This is a feature and not a bug; it's called SRS: https://en.wikipedia.org/wiki/Sender_Rewriting_Scheme

The root cause of your problem is explained in that header:
```
Received-SPF: softfail (google.com: domain of transitioning srs0=/cb0=ak=thegrovesfamily.net=murray@murraygrov.es does not designate 212.227.126.135 as permitted sender) client-ip=212.227.126.135;
``

You need to change the SPF record of ``murraygrov.es`` to include 212.227.126.135.
```
murraygrov.es descriptive text "v=spf1 mx a:mail.murraygrov.es a:murraygrov.es include:_spf.google.com +a ~all"
```

Currently you have:
```
mail.murraygrov.es has address 212.132.245.139
```

**Comment by MurrayGroves** [comment]
@nextgens thank you for the quick response and information about SRS. That makes sense to me, but ` 212.227.126.135` is not the IP of my email server, it is the IP of the address that is sending to me. This would mean I would have to add every mail server that could send to me to my SPF record which seems incorrect. Do you have any further advice?

**Comment by nextgens** [comment]
Ah, sorry, I may have misunderstood the logs then.

My understanding is that you have received an email from ``thegrovesfamily.net`` on your Mailu instance which hosts ``murraygrov.es``. That email has then been "imported" into gmail with POP3. For some unknown reason gmail is re-evaluating SPF and finding that it has failed... I wouldn't worry about it.

**Comment by MurrayGroves** [comment]
Yeah that's what I was doing. Does seem to be a weird issue with only Gmail. Comes up as SPF passed on Mailu. Thanks for your help :)
