### ISSUE TITLE
Mailu lets you create but not login with a domain ending in .local

### ISSUE THREAD

**Issue by Luccio96** [Mailu/Mailu#2783]
### Environment

- [x] docker compose
- [ ] kubernetes
- [ ] docker swarm

### Version

- Version: `master`

## Description
I got error: "wrong e-mail or password" when I try the first login 
![immagine](https://user-images.githubusercontent.com/41821623/233114964-b2275988-09f7-4285-8228-a8c862fbd106.png)

## Replication Steps
I used the command `docker compose -p mailu exec admin flask mailu admin admin teamsolutions.local mypass`

## Observed behaviour
Also tried to add another account, delete current one without success.

**Comment by nextgens** [comment]
We use the default email validator from wtforms:
https://wtforms.readthedocs.io/en/2.3.x/_modules/wtforms/validators/#Email

Under the hood this is what is happening:
```
>>> import email_validator
>>> email_validator.validate_email('test@example.com',check_deliverability=False,allow_smtputf8=True,allow_empty_local=False)
<ValidatedEmail test@example.com>
email_validator.validate_email('admin@teamsolutions.local',check_deliverability=False,allow_smtputf8=True,allow_empty_local=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/a/env/lib/python3.7/site-packages/email_validator/validate_email.py", line 120, in validate_email
    domain_part_info = validate_email_domain_name(domain_part, test_environment=test_environment, globally_deliverable=globally_deliverable)
  File "/tmp/a/env/lib/python3.7/site-packages/email_validator/syntax.py", line 398, in validate_email_domain_name
    raise EmailSyntaxError("The part after the @-sign is a special-use or reserved name that cannot be used with email.")
email_validator.exceptions_types.EmailSyntaxError: The part after the @-sign is a special-use or reserved name that cannot be used with email.
```

It is true that ``.local`` should never be used for emails

**Comment by Luccio96** [comment]
I confirm that the domain is the problem, changed to `.loc` let me log in.
