### ISSUE TITLE
mailu front fails with KeyError: 'LD_PRELOAD'

### ISSUE THREAD

**Issue by pr0ton11** [Mailu/Mailu#2789]
### Environment

- [X] docker compose
- [ ] kubernetes
- [ ] docker swarm

### Version

- Version: `2.0`

## Description

Pulled the image today to create a new server. The nginx fails with the following error.

## Replication Steps

* docker-compose up -d
* docker shows unhealthy front container
* docker logs mailu_front_1

## Logs

```
# docker logs mailu_front_1
Traceback (most recent call last):
  File "/config.py", line 8, in <module>
    args = system.set_env()
  File "/app/venv/lib/python3.10/site-packages/socrate/system.py", line 80, in set_env
    del os.environ['LD_PRELOAD']
  File "/usr/lib/python3.10/os.py", line 696, in __delitem__
    raise KeyError(key) from None
KeyError: 'LD_PRELOAD'
```

**Comment by pr0ton11** [comment]
Seems like the env `"LD_PRELOAD=/usr/lib/libhardened_malloc.so" `is set when I run docker inspect

**Comment by nextgens** [comment]
Can't reproduce it here with 2.0.8.

Which specific version of Mailu are you running? ``cat /version`` from a container
What CPU are you running it from? ``cat /proc/cpuinfo``
Did you set LD_PRELOAD manually in mailu.env?

**Comment by RandomByte** [comment]
Same here with both `ghcr.io/mailu/nginx:2.0.7` and `ghcr.io/mailu/nginx:2.0.8`.

I reverted to `2.0.6` where the error does not occur.

**Comment by nextgens** [comment]
@RandomByte same questions.

The code is here: https://github.com/Mailu/Mailu/blob/master/core/base/libs/socrate/socrate/system.py#L80 and yes it's new. LD_PRELOAD is set https://github.com/Mailu/Mailu/blob/master/core/base/Dockerfile#L83 and should always be present: there should be no problem removing it.

**Comment by nextgens** [comment]
OK, found the problem; I'm working on a fix

**Comment by nextgens** [comment]
2.0.9 should be out soon
