### ISSUE TITLE
Doesn't working with a proxy

### ISSUE THREAD

**Issue by goldenivan** [Mailu/Mailu#279]
Hi everyone,

I'm using this to proxy all my rancher containers : https://github.com/adi90x/rancher-active-proxy

With this, I just have to specify an host with those variables : 

rap.host: example.com
rap.le_host: example.com

This is working for many other projects. With Mailu, there isn't working. There is my configuration : 

version: '2'
services:
  imap:
    image: mailu/dovecot:stable
    environment:
      BIND_ADDRESS: 127.0.0.1
      COMPOSE_PROJECT_NAME: mailu
      DEBUG: 'False'
      DOMAIN: example.com
      ENABLE_CERTBOT: 'False'
      EXPOSE_ADMIN: 'yes'
      FETCHMAIL_DELAY: '600'
      FETCHMAIL_KEEP: 'False'
      FRONTEND: none
      HOSTNAME: mailu.example.com
      MESSAGE_SIZE_LIMIT: '50000000'
      POSTMASTER: admin
      RELAYHOST: ''
      RELAYNETS: 10.0.0.0/8
      ROOT: /mailu
      SECRET_KEY: ********
      VERSION: stable
      WEBDAV: none
      WEBMAIL: roundcube
    volumes:
    - /mailu/data:/data
    - /mailu/mail:/mail
    - /mailu/certs:/certs
    - /mailu/overrides:/overrides
    labels:
      io.rancher.container.pull_image: always
  smtp:
    image: mailu/postfix:stable
    environment:
      BIND_ADDRESS: 127.0.0.1
      COMPOSE_PROJECT_NAME: mailu
      DEBUG: 'False'
      DOMAIN: example.com
      ENABLE_CERTBOT: 'False'
      EXPOSE_ADMIN: 'yes'
      FETCHMAIL_DELAY: '600'
      FETCHMAIL_KEEP: 'False'
      FRONTEND: none
      HOSTNAME: mailu.example.com
      MESSAGE_SIZE_LIMIT: '50000000'
      POSTMASTER: admin
      RELAYHOST: ''
      RELAYNETS: 10.0.0.0/8
      ROOT: /mailu
      SECRET_KEY: ********
      VERSION: stable
      WEBDAV: none
      WEBMAIL: roundcube
    volumes:
    - /mailu/data:/data
    - /mailu/certs:/certs
    - /mailu/overrides:/overrides
    labels:
      io.rancher.container.pull_image: always
  antivirus:
    image: mailu/clamav:stable
    environment:
      BIND_ADDRESS: 127.0.0.1
      COMPOSE_PROJECT_NAME: mailu
      DEBUG: 'False'
      DOMAIN: example.com
      ENABLE_CERTBOT: 'False'
      EXPOSE_ADMIN: 'yes'
      FETCHMAIL_DELAY: '600'
      FETCHMAIL_KEEP: 'False'
      FRONTEND: none
      HOSTNAME: mailu.example.com
      MESSAGE_SIZE_LIMIT: '50000000'
      POSTMASTER: admin
      RELAYHOST: ''
      RELAYNETS: 10.0.0.0/8
      ROOT: /mailu
      SECRET_KEY: ********
      VERSION: stable
      WEBDAV: none
      WEBMAIL: roundcube
    volumes:
    - /mailu/filter:/data
    labels:
      io.rancher.container.pull_image: always
  antispam:
    image: mailu/rspamd:stable
    environment:
      BIND_ADDRESS: 127.0.0.1
      COMPOSE_PROJECT_NAME: mailu
      DEBUG: 'False'
      DOMAIN: example.com
      ENABLE_CERTBOT: 'False'
      EXPOSE_ADMIN: 'yes'
      FETCHMAIL_DELAY: '600'
      FETCHMAIL_KEEP: 'False'
      FRONTEND: none
      HOSTNAME: mailu.example.com
      MESSAGE_SIZE_LIMIT: '50000000'
      POSTMASTER: admin
      RELAYHOST: ''
      RELAYNETS: 10.0.0.0/8
      ROOT: /mailu
      SECRET_KEY: ********
      VERSION: stable
      WEBDAV: none
      WEBMAIL: roundcube
    volumes:
    - /mailu/filter:/var/lib/rspamd
    labels:
      io.rancher.container.pull_image: always
  http:
    image: mailu/none:stable
    environment:
      BIND_ADDRESS: 127.0.0.1
      COMPOSE_PROJECT_NAME: mailu
      DEBUG: 'False'
      DOMAIN: example.com
      ENABLE_CERTBOT: 'False'
      EXPOSE_ADMIN: 'yes'
      FETCHMAIL_DELAY: '600'
      FETCHMAIL_KEEP: 'False'
      FRONTEND: none
      HOSTNAME: mailu.example.com
      LETSENCRYPT_EMAIL: maxrivolet@gmail.com
      LETSENCRYPT_HOST: mailu.example.com
      MESSAGE_SIZE_LIMIT: '50000000'
      POSTMASTER: admin
      RELAYHOST: ''
      RELAYNETS: 10.0.0.0/8
      ROOT: /mailu
      SECRET_KEY: ********
      VERSION: stable
      VIRTUAL_HOST: mailu.example.com
      VIRTUAL_PORT: '443'
      VIRTUAL_PROTO: https
      WEBDAV: none
      WEBMAIL: roundcube
    volumes:
    - /mailu/certs:/certs
    labels:
      io.rancher.container.pull_image: always
  admin:
    image: mailu/admin:stable
    environment:
      BIND_ADDRESS: 127.0.0.1
      COMPOSE_PROJECT_NAME: mailu
      DEBUG: 'False'
      DOMAIN: example.com
      ENABLE_CERTBOT: 'False'
      EXPOSE_ADMIN: 'yes'
      FETCHMAIL_DELAY: '600'
      FETCHMAIL_KEEP: 'False'
      FRONTEND: none
      HOSTNAME: mailu.example.com
      MESSAGE_SIZE_LIMIT: '50000000'
      POSTMASTER: admin
      RELAYHOST: ''
      RELAYNETS: 10.0.0.0/8
      ROOT: /mailu
      SECRET_KEY: ********
      VERSION: stable
      WEBDAV: none
      WEBMAIL: roundcube
    volumes:
    - /mailu/data:/data
    - /mailu/dkim:/dkim
    - /mailu/certs:/certs
    - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      rap.port: '80'
      rap.le_host: mailu.example.com
      io.rancher.container.pull_image: always
      rap.host: mailu.example.com
  webdav:
    image: mailu/none:stable
    environment:
      BIND_ADDRESS: 127.0.0.1
      COMPOSE_PROJECT_NAME: mailu
      DEBUG: 'False'
      DOMAIN: example.com
      ENABLE_CERTBOT: 'False'
      EXPOSE_ADMIN: 'yes'
      FETCHMAIL_DELAY: '600'
      FETCHMAIL_KEEP: 'False'
      FRONTEND: none
      HOSTNAME: mailu.example.com
      MESSAGE_SIZE_LIMIT: '50000000'
      POSTMASTER: admin
      RELAYHOST: ''
      RELAYNETS: 10.0.0.0/8
      ROOT: /mailu
      SECRET_KEY: ********
      VERSION: stable
      WEBDAV: none
      WEBMAIL: roundcube
    volumes:
    - /mailu/dav:/data
    labels:
      io.rancher.container.pull_image: always
  milter:
    image: mailu/rmilter:stable
    environment:
      BIND_ADDRESS: 127.0.0.1
      COMPOSE_PROJECT_NAME: mailu
      DEBUG: 'False'
      DOMAIN: example.com
      ENABLE_CERTBOT: 'False'
      EXPOSE_ADMIN: 'yes'
      FETCHMAIL_DELAY: '600'
      FETCHMAIL_KEEP: 'False'
      FRONTEND: none
      HOSTNAME: mailu.example.com
      MESSAGE_SIZE_LIMIT: '50000000'
      POSTMASTER: admin
      RELAYHOST: ''
      RELAYNETS: 10.0.0.0/8
      ROOT: /mailu
      SECRET_KEY: ********
      VERSION: stable
      WEBDAV: none
      WEBMAIL: roundcube
    volumes:
    - /mailu/filter:/data
    - /mailu/dkim:/dkim
    - /mailu/overrides:/overrides
    labels:
      io.rancher.container.pull_image: always
  fetchmail:
    image: mailu/fetchmail:stable
    environment:
      BIND_ADDRESS: 127.0.0.1
      COMPOSE_PROJECT_NAME: mailu
      DEBUG: 'False'
      DOMAIN: example.com
      ENABLE_CERTBOT: 'False'
      EXPOSE_ADMIN: 'yes'
      FETCHMAIL_DELAY: '600'
      FETCHMAIL_KEEP: 'False'
      FRONTEND: none
      HOSTNAME: mailu.example.com
      MESSAGE_SIZE_LIMIT: '50000000'
      POSTMASTER: admin
      RELAYHOST: ''
      RELAYNETS: 10.0.0.0/8
      ROOT: /mailu
      SECRET_KEY: ********
      VERSION: stable
      WEBDAV: none
      WEBMAIL: roundcube
    volumes:
    - /mailu/data:/data
    labels:
      io.rancher.container.pull_image: always
  webmail:
    image: mailu/roundcube:stable
    environment:
      BIND_ADDRESS: 127.0.0.1
      COMPOSE_PROJECT_NAME: mailu
      DEBUG: 'False'
      DOMAIN: example.com
      ENABLE_CERTBOT: 'False'
      EXPOSE_ADMIN: 'yes'
      FETCHMAIL_DELAY: '600'
      FETCHMAIL_KEEP: 'False'
      FRONTEND: none
      HOSTNAME: mailu.example.com
      MESSAGE_SIZE_LIMIT: '50000000'
      POSTMASTER: admin
      RELAYHOST: ''
      RELAYNETS: 10.0.0.0/8
      ROOT: /mailu
      SECRET_KEY: ********
      VERSION: stable
      WEBDAV: none
      WEBMAIL: roundcube
    volumes:
    - /mailu/webmail:/data
    labels:
      io.rancher.container.pull_image: always
  redis:
    image: redis:3
    environment:
      BIND_ADDRESS: 127.0.0.1
      COMPOSE_PROJECT_NAME: mailu
      DEBUG: 'False'
      DOMAIN: example.com
      ENABLE_CERTBOT: 'False'
      EXPOSE_ADMIN: 'yes'
      FETCHMAIL_DELAY: '600'
      FRONTEND: none
      HOSTNAME: mailu.example.com
      MESSAGE_SIZE_LIMIT: '50000000'
      POSTMASTER: admin
      RELAYHOST: ''
      RELAYNETS: 10.0.0.0/8
      ROOT: /mailu
      SECRET_KEY: ********
      VERSION: stable
      WEBDAV: none
      WEBMAIL: roundcube
    volumes:
    - /mailu/redis:/data
    labels:
      io.rancher.container.pull_image: always

The proxy see the connection request : 

0/9/2017 9:38:20 PMnginx.1     | mailu.example.com **.**.**.** - - [09/Oct/2017:19:38:20 +0000] "GET / HTTP/1.1" 503 213

Do you know what's going on ? Do I have to configure my Mailu in another way to fit with my proxy ?

**Comment by goldenivan** [comment]
Now I can access to my the admin part : mailu.example.com/admin

I've seen in the documentationthat then, I have to create the admin account : 

> docker-compose run --rm admin python manage.py admin root example.net password

How can I do that through Rancher ? Is it possible to use some variable to init the admin account and password ?

**Comment by curry684** [comment]
You can just SSH to the Rancher host running the admin container and use `docker exec` on the running admin container with the same parameters. Ie.:
```
docker exec my_admin_1 python manage.py admin root example.net password
```
I agree this should be .env controlled though, the manage scripts should not have to be used for a simple install.

**Comment by kaiyou** [comment]
I disagree with setting this in the `.env`, which should not contain values used for one-time actions, like creating the initial user. Maybe it could be created automatically with a random password provided in the logs?

**Comment by curry684** [comment]
I agree it's a poor solution for one time settings, but it seems to be the generally accepted one as the official MariaDB and MySQL containers do it like this, as do many others like Gitlab, Grafana and InfluxDB.

Docket implicitly doesn't think about stateful settings.
