### ISSUE TITLE
roundcube - spell check - only English available

### ISSUE THREAD

**Issue by Aaron-Ritter** [Mailu/Mailu#2798]
### Environment

- [x] docker compose
- [ ] kubernetes
- [ ] docker swarm

### Version
- Version: `2.0.10`

## Description
Since the 2.x release the German spell check is missing, in fact it looks like as if only English spell check is available. 

Based on my understanding it is using pspell and for this additional language files (dictionary) would have to be deployed, all thought I have not figured out how yet.

There are a lot of dictionaries available at http://ftp.gnu.org/gnu/aspell/dict/0index.html which I think should work with pspell.

## Replication Steps
I opened roundcube wrote an email and clicked on spell check but it only offered me English. My roundcube configuration was English and I thought maybe changing the UI language will change the spell check language too 
![image](https://user-images.githubusercontent.com/12079732/234831556-4c48df3b-8877-46db-b96f-434e9b993c54.png)
but despite changing it to German
![image](https://user-images.githubusercontent.com/12079732/234831212-002b6880-4427-403e-a229-9dfc29ca339f.png)
the spell check language is still English only

**Comment by nextgens** [comment]
The other dictionaries are installed: https://github.com/Mailu/Mailu/blob/master/webmails/Dockerfile#L19 ... as for why they are not used, no idea.

Try a different engine in roundcube's config maybe? If your comfortable with an online spellchecker:
```
$config['spellcheck_engine'] = 'googie';
$config['spellcheck_ignore_caps'] = true;
$config['spellcheck_ignore_nums'] = true;
$config['spellcheck_dictionary'] = true;
```

**Comment by nextgens** [comment]
Ahhh, found the problem, we need to define spellcheck_languages explicitly for it to work.

```
$config['spellcheck_languages'] = array('en'=>'English', 'de'=>'Deutsch');
```

**Comment by Aaron-Ritter** [comment]
Great! I was playing around with the config too but didn't got it to work 😅
So what would be the best way with this config, just add all available/installed languages?

When using something like googie as an engine, at least in the EU, there probably would need to be some sort of GDPR compliant use of it.

**Comment by nextgens** [comment]
I've added all the dictionaries that were available/packaged in alpine:
https://pkgs.alpinelinux.org/packages?name=aspell-%3F%3F&branch=v3.17&repo=&arch=&maintainer=

I agree that we could do better. Is that something you want to tackle?

**Comment by Aaron-Ritter** [comment]
ah ok, substantially fewer than on debian for example. I'll have a close look around it and see what better options would be. But as its only 5 languages for now its a good start at least adding all of them.

**Comment by nextgens** [comment]
@Aaron-Ritter don't hesitate to re-open & send a PR
