### ISSUE TITLE
Make it possible to disable Virus Scam for Outgoing Mails

### ISSUE THREAD

**Issue by vanthome** [Mailu/Mailu#280]
I'm getting this when I want to send mails with some attachments with ZIP files. I'm pretty sure there is no such virus but anyways, how can I disable this check? I tried to disable the spam filter but this does not help.

```
SMTP Error: [554] 5.7.1 Infected: PUA.Pdf.Trojan.EmbeddedJavaScript-1
```

**Comment by curry684** [comment]
It's better to disable that single signature if it's causing problems, ref. http://lists.clamav.net/pipermail/clamav-users/2016-March/002716.html

**Comment by vanthome** [comment]
Thx for the hint!
