### ISSUE TITLE
Improve auth-related logging

### ISSUE THREAD

**Issue by nextgens** [Mailu/Mailu#2803]
At the very least we should log:
- success/failure
- which service?
- which credentials were used if successful
- where from (including source port info)

arguably:
- a truncated hash of the failed creds
- where we are at rate-limiting wise

**Comment by Diman0** [comment]
This is a good idea. I think it is a good idea to log both success and failure. Success could be with log level info and failure with log level warning.

- which service?
  - all of them
- which credentials were used if successful
  - I agree
- where from (including source port info)
  - I agree


- a truncated hash of the failed creds
  -  I don't think a truncated hash of the password is relevant. What matters is that the login failed and the source ip/port
- where we are at rate-limiting wise
  - This is a nice to have. This will probably not be used in practice.

**Comment by nextgens** [comment]
> a truncated hash of the failed creds
> 
>     * I don't think a truncated hash of the password is relevant. What matters is that the login failed and the source ip/port

Well, the idea is to have an idea of which "version" of the password was used at the time. We could do it statefully by storing explicit version information or "date of last password change"... or we could just use some form of hash... it doesn't have to be of the password, it could be of the salt of the password.
