### ISSUE TITLE
User Signup support in Admin Panel [Feature Request]

### ISSUE THREAD

**Issue by whitef0x0** [Mailu/Mailu#281]
I was wondering whether there are any plans to integrate a signup form in the Admin panel so that users can create accounts for the mailserver by themselves, instead of relying on an administrator to create an account for them.

**Comment by kaiyou** [comment]
There is not at the moment, but it could be an interesting feature, either as an API for integration in a separate signup interface or a proper signup form.

A domain could have a flag set if it is open for signup. Also, we would need a proper CAPTCHA upon registration to avoid most obvious spam bots.

**Comment by whitef0x0** [comment]
@kaiyou to get around the spam bot issue, maybe implementing a invite link would be better (ala Slack)?

**Comment by kaiyou** [comment]
I am setting a goal for the end of the year. I would like to bring self registration of users, as well as self registration of domain owners.

**Comment by kaiyou** [comment]
Sorry I forgot about this issue, this was duplicated in #340 with more details
