### ISSUE TITLE
Assign IPv4 addresses domain specifically

### ISSUE THREAD

**Issue by a5a351e7** [Mailu/Mailu#2822]
### Environment

- [X] docker compose
- [ ] kubernetes
- [ ] docker swarm

### Version

- Version: `2.0`

## Description
If you have a host with two (or more) assigned IPv4 addresses, I couldn't find a way to assign one of these IPv4 addresses specifically to a configured domain in mailu. This behaviour is needed for sending emails (SMTP) from different ip adresses.
## Replication Steps
n/a

## Observed behaviour
n/a

## Expected behaviour
E.g.:
Domains: 
domain1.tld 
domain2.tld

IPv4:
123.456.789.001
123.456.789.002

domain1.tld should only use 123.456.789.001 for sending mails.
domain2.tld should only use 123.456.789.002 for sending mails.

## Logs
n/a

**Comment by nextgens** [comment]
What is the usecase for this?

**Comment by a5a351e7** [comment]
I got several domains running with different services. One of these domains is used to send newsletters and notifications, so in case the IP address is getting a bad reputation, I want to be sure, that the other domain is not affected by this using another IP address.
