### ISSUE TITLE
mailu.io website does not explain how to get or download Mailu

### ISSUE THREAD

**Issue by baldpenguin** [Mailu/Mailu#2825]
On the website ( https://mailu.io/2.0/setup.html ) there is no explanation on how to get or download Mailu.

I would suggest adding a paragraph on how to retreive the files ("git clone https://github.com/Mailu/Mailu.git"), and how to proceed from there.

**Comment by Eason-S-Lu** [comment]
https://setup.mailu.io/2.0/

**Comment by Eason-S-Lu** [comment]
> On the website ( https://mailu.io/2.0/setup.html ) there is no explanation on how to get or download Mailu.
> 
> I would suggest adding a paragraph on how to retreive the files ("git clone https://github.com/Mailu/Mailu.git"), and how to proceed from there.

try https://setup.mailu.io/2.0/

**Comment by Diman0** [comment]
https://mailu.io/2.0/compose/setup.html
On this page, you are referred to setup.mailu.io where you can generate the files for using Mailu.

Users are not meant to build from source. But the contributors documentation on mailu.io (https://mailu.io/2.0/contributors/environment.html) does explain how to build from source.
