### ISSUE TITLE
[enhancement requests]Cloudflare CDN DNS setup and auto save draft

### ISSUE THREAD

**Issue by Eason-S-Lu** [Mailu/Mailu#2828]
### Environment

- [✅ ] docker compose
- [ ] kubernetes
- [ ] docker swarm

### Version

- Version: `2.0`

## Description
Hope to have a version of the DNS that are more friendly to use with Cloudflare.
Currently the A record for "mail.example.com" can NOT be proxyed due to other record need to point to "mail.example.com" as their destination.If there is a way to point other records to the IP address of the server "mail.example.com" can be proxyed so it can enjoy the CDN service Cloudflare provide which will speed up resbounce time.

**Comment by Eason-S-Lu** [comment]
Also hope be able to autosave draft when exit the message compose page

**Comment by Eason-S-Lu** [comment]
One suggestion to allow cloudflare cdn is to set up 2 A address for example
The webmail can be mail.example.com
The mx can be mx.example.com
That way mail.example.com can be proxied.

**Comment by Diman0** [comment]
This should already be possible. 
Mailu accepts any connection, regardless the hostname used.

You can already use two different A records to point to your Mailu server.

**Comment by Eason-S-Lu** [comment]
Thanks
