### ISSUE TITLE
Make it possible to disable virus-scanning completely

### ISSUE THREAD

**Issue by HorayNarea** [Mailu/Mailu#283]
this would make Mailu more suitable for smaller setups because it would require way less RAM, also virus-scanning at the mailserver is not wanted in some scenarios (honeypots, etc.)

virus-scanning is probably not really needed¹, malware comes mostly from spam and that gets filtered anyway (correct me if i'm wrong)

¹ at least not that much that one would sacrifice 1-2 GB of RAM for it

**Comment by kaiyou** [comment]
This is already implemented as part of #212 and will be merged in the next release :)

**Comment by HorayNarea** [comment]
Whoops, didn't see that PR. Thanks for the clarification! :)
