### ISSUE TITLE
probleme d'envoie des mails avec la solution mailu

### ISSUE THREAD

**Issue by kuate-junior** [Mailu/Mailu#2832]
bonjour a tous je rencontre un probleme depuis ces dernier temps.
j'ai  eu a configurer mon serveur de mail avec la solution mailu grace a leur documentation. Je recois bien mes mail mais je n'arrive pas a envoyer de mail ors j'ai tous respecter la procedure et d'apres mxtoolbox toute mes configs dns sont bonne.
svp que faire?

**Comment by nextgens** [comment]
Bonjour, votre fournisseur d'accès filtre sans doute les connections sortantes vers le port SMTP. Contactez le pour lui dire que vous souhaitez utiliser un serveur de messagerie.
