### ISSUE TITLE
PHP Fatal error:  [snuffleupagus][0.0.0.0][readonly_exec][log] Error while accessing /overrides/config.php.inc

### ISSUE THREAD

**Issue by Igortorrente** [Mailu/Mailu#2836]
### Environment

- [x] docker compose
- [ ] kubernetes
- [ ] docker swarm

### Version

- Version: `2.0`

## Description

I can't add a override config to the roundcube webmail without having problems with snuffleupagus.

## Replication Steps

1. Add  `config.php.inc` to `/overrides/`
2. Restart the container

## Observed behaviour

When I mount the `/overrides/config.php.inc` as readonly I receive the error bellow
```
PHP Fatal error:  [snuffleupagus][0.0.0.0][readonly_exec][log] Error while accessing /overrides/config.php.inc: Read-only file system in /var/www/roundcube/config/config.inc.php on line 55
Fatal error: Please check the Roundcube error log and/or server error logs for more information.
```

And this other error when read/write:
```
PHP Fatal error:  [snuffleupagus][0.0.0.0][readonly_exec][drop] Attempted execution of a writable file (/overrides/config.php.inc) in /var/www/roundcube/config/config.inc.php on line 55
Fatal error: Please check the Roundcube error log and/or server error logs for more information.
```

Doesn't matter the content of the config file.

## Expected behaviour

The override file should work.

## Additional information

`config.php.inc` content:
``` php
<?php


```

Mount config:
``` json
{
    "Type": "bind",
    "Source": "/home/vagrant/containers_config/mailu/overrides/roundcube/config.php",
    "Destination": "/overrides/config.php.inc",
    "Mode": "",
    "RW": true,
    "Propagation": "rprivate"
}
```

File ownership and permission:
``` console
$ docker exec mailu ls -lha /overrides/
total 12K    
drwxr-xr-x    2 root     root        4.0K May 25 01:13 .
drwxr-xr-x   24 root     root        4.0K May 25 01:13 ..
-rw-------    1 mailu    mailu          7 May 25 00:31 config.php.inc
``

**Comment by nextgens** [comment]
What happens if you ``chown root:root config.php.inc ; chmod a+r config.php.inc`` ?

**Comment by Igortorrente** [comment]
Thank you! This solved my issue!
