### ISSUE TITLE
Template with Swarm support / environment variables documentation.

### ISSUE THREAD

**Issue by ghost** [Mailu/Mailu#284]
Currently Mailu Compose template uses env file directive. It is not supportet by Docker Swarm - 
https://github.com/moby/moby/issues/29133 .

It would be nice to have a template with Swarm support. One of the possible ways - to use "environment directive" and supply directives for each service like:
```
  admin:
    image: mailu/admin:1.4
    environment:
      - DOMAIN=foo
      - POSTMASTER=baz
      - SECRET_KEY=bar
      - DEBUG=False
    expose:
      - "8000:80"
--------- etc...
```

And there is no documentation currently on relations between Mailu services and env variables form the env file. So it is extremely hard to rewrite current template to use with k8s or Swarm.

**Comment by kaiyou** [comment]
Indeed, I could start mapping those if you are willing to write a Swarm or k8s template :)

**Comment by dosimeter** [comment]
Yes, I have one for Swarm and Mailu v1.4 (most likely with partially wrong env-var setup, but still working). Will try to add it on Nov 5-7.

**Comment by kaiyou** [comment]
If you write some documentation and i have not yet merged `refactor-repo` in master by then, feel free to pull request against that branch and add a specific compose file in `docs/compose` :)

**Comment by kaiyou** [comment]
Also, in `docs/configuration.md` in that branch, I added some documentation about the main configuration settings.

**Comment by dosimeter** [comment]
@kaiyou sorry for a delay. Here is my example config - https://github.com/Mailu/Mailu/pull/344 . (Has lot of copypasted env variables, would be nice to remove them ...)

**Comment by kaiyou** [comment]
I would say this is outdated
