### ISSUE TITLE
when the zone's DNS is on the same host, verification fails and errors show up

### ISSUE THREAD

**Issue by elandorr** [Mailu/Mailu#2842]
### Environment

- [x] docker compose
- [ ] kubernetes
- [ ] docker swarm

### Version

- Version: `2.0.14`

## Description

Adding new domains is laggy as the verification first has to time out on the DNS page. I reported this years ago but can't find it. 

![image](https://github.com/Mailu/Mailu/assets/56206745/50f2ed28-22f5-4489-9dd3-9b47032eddc0)

There are also a few ala 
`<hostname of the server> could not be resolved (2: Server failure) while in resolving client hostname`

To find out why, I tested it in all the mailu containers:

`docker exec -it mailu-webmail-1 getent hosts hostname` works
`docker exec -it mailu-resolver-1 getent hosts hostname` works
`docker exec -it mailu-smtp-1 getent hosts hostname` timeout
`docker exec -it mailu-redis-1 getent hosts hostname` timeout
`docker exec -it mailu-imap-1 getent hosts hostname` timeout
`docker exec -it mailu-front-1 getent hosts hostname` timeout
`docker exec -it mailu-antispam-1 getent hosts hostname` timeout
`docker exec -it mailu-admin-1 getent hosts hostname` timeout

Also noticed this guy in antispam:
`monitored; rspamd_monitored_propagate_error: servfail on resolving bl.blocklist.de, disable object`
Don't think that's related, though. Is that just a crappy blacklist? Seeing this one over and over.

## Replication Steps

I discovered the relation to having the DNS on the same server back then. So that's a starting point. In this case the DNS responsible for the hostname is in a docker container himself.

## Observed behaviour

Lookups fail

## Expected behaviour

Lookups don't fail

## Logs

see above

**Comment by elandorr** [comment]
Noticed the DNS set in the compose for the ones not working is to the resolver container. Now that's a bit odd, as the resolver container can resolve the hostname just fine.

**Comment by dieideeistgut** [comment]
hey @elandorr - think i'm running into this. what exactly did you change? thanks!
