### ISSUE TITLE
Client-Port HTTP header not expanded

### ISSUE THREAD

**Issue by nitroxis** [Mailu/Mailu#2848]
### Environment

- [x] docker compose
- [ ] kubernetes
- [ ] docker swarm

### Version

- Version: `master`

## Description
I'm currently trying to troubleshoot an issue in Mailu between nginx and postfix. I used `tcpdump` to dump some traffic and noticed that the HTTP headers sent by nginx to Mailu are not expanded correctly. This is most likely unrelated to my actual problem and I don't think it is currently causing any issues, but it might be worth fixing anyway. Here is the observed traffic between nginx and the email auth endpoint:

```
GET /internal/auth/email HTTP/1.0
Host: admin
Connection: close
Auth-Method: plain
Auth-User: [redacted]
Auth-Pass: [redacted]
Auth-Protocol: smtp
Auth-Login-Attempt: 1
Client-IP: [redacted]
Client-Host: [redacted]
Auth-SSL: on
Auth-SSL-Protocol: TLSv1.2
Auth-SSL-Cipher: ECDHE-RSA-AES256-GCM-SHA384
Auth-Port: 465
Client-Port: $remote_port

HTTP/1.0 200 OK
Server: gunicorn
Date: Mon, 05 Jun 2023 20:31:11 GMT
Connection: close
Content-Type: text/html; charset=utf-8
Auth-Status: OK
Auth-Server: 192.168.203.6
Auth-User: [redacted]
Auth-User-Exists: True
Auth-Port: 10025
Content-Length: 0


```
## Replication Steps
Log in to a Mailu instance via its nginx `front` container.

## Observed behaviour
The `Client-Port` request header is set to `$remote_port`.

## Expected behaviour
The `Client-Port` header should contain the actual port, not the variable name.

## Logs
See HTTP dump

**Comment by nextgens** [comment]
That's a known "feature" ... I don't think we can export the source port information using nginx's mail module; the PR linked above should make that problem go away
