### ISSUE TITLE
"_gateway" could not be resolved (3: Host not found)

### ISSUE THREAD

**Issue by papapumpnz** [Mailu/Mailu#2849]
### Environment

- [x] docker compose
- [ ] kubernetes
- [ ] docker swarm

### Version

- Version: `master`
MAILU_VERSION:-1.7}

## Description
Connections from docker containers on the same docker host fail "_gateway" could not be resolved (3: Host not found) while in resolving client hostname, client: 192.168.1.1, server: 0.0.0.0:587

## Replication Steps
1. Send mail from a docker container on the same docker host

## Observed behaviour
```
2023/06/06 01:55:08 [info] 12#12: *337 client logged in, client: 192.168.1.1 using starttls, server: 0.0.0.0:587, login: "noreply@contactnow.link", upstream: 192.168.203.9:10025
2023/06/06 01:55:08 [info] 12#12: *337 proxied session done, client: 192.168.1.1 using starttls, server: 0.0.0.0:587, login: "noreply@contactnow.link", upstream: 192.168.203.9:10025
2023/06/06 01:55:13 [info] 12#12: *345 client 192.168.1.1:44530 connected to 0.0.0.0:587
2023/06/06 01:55:13 [error] 12#12: *345 "_gateway" could not be resolved (3: Host not found) while in resolving client hostname, client: 192.168.1.1, server: 0.0.0.0:587
```

## Expected behaviour
Should be able to authenticate and send mail from containers on the same docker host. Works fine when sending from other docker hosts.

## Logs
```
2023/06/06 01:55:08 [info] 12#12: *337 client logged in, client: 192.168.1.1 using starttls, server: 0.0.0.0:587, login: "noreply@contactnow.link", upstream: 192.168.203.9:10025
2023/06/06 01:55:08 [info] 12#12: *337 proxied session done, client: 192.168.1.1 using starttls, server: 0.0.0.0:587, login: "noreply@contactnow.link", upstream: 192.168.203.9:10025
2023/06/06 01:55:13 [info] 12#12: *345 client 192.168.1.1:44530 connected to 0.0.0.0:587
2023/06/06 01:55:13 [error] 12#12: *345 "_gateway" could not be resolved (3: Host not found) while in resolving client hostname, client: 19

**Comment by PinchePelon** [comment]
Were you able to figure this out? Currently running in to the same issue, and am unable to relay mail from other docker containers on different networks.
