### ISSUE TITLE
Error accessing webmail with external nginx reverse proxy

### ISSUE THREAD

**Issue by magostinelli** [Mailu/Mailu#2850]
### Environment

- [ ] docker compose
- [ ] kubernetes
- [ ] docker swarm

### Version

2.0

## Description
Error 404 when accessing the mydomain.com/webmail.
After the login screen a redirect send you to o.mydomain.com/webmail/sso.php

Administration page, instead, work correctly.

## Replication Steps
Setup a nginix reverse proxy configuration as you can read on official documentation:
https://mailu.io/2.0/reverse.html#

## Observed behaviour
404 page not found 

## Expected behaviour
working roundcube webmail

**Comment by ghostwheel42** [comment]
Looks like the reverse proxy in front does not forward the request to mailu.
Without the config it is hard to say where the error lies.
Are you sure you are redirected to `o.mydomain.com` instead of `mydomain.com` - the domain name should not change when redirected.

**Comment by magostinelli** [comment]
It works If I use a dedicated domain, but if i use the rules specified in the offical doc ( location ~* ^/(admin|api|sso|static|webdav|webmail|(apple\.)?mobileconfig|(\.well\-known/autoconfig/)?mail/|Autodiscover/Autodiscover) {), it doesn't work

**Comment by ghostwheel42** [comment]
Using a dedicated domain is the best option.
I can take a look if you send your server block (at least all the location directives).
It should work like described in the docs.

**Comment by magostinelli** [comment]
This is my nginx conf:

  location ~* ^/(gest_email|webmail|api|sso|static|webdav|(apple\.)?mobileconfig|(\.well\-known/autoconfig/)?mail/|Autodiscover/Autodiscover) {
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_pass https://127.0.0.1:9443;
  }

I changed only the /admin url (and it works, only webmail doesn't work).

**Comment by jwr1** [comment]
I'm having a similar problem trying to get Mailu working with [Cosmos](https://github.com/azukaar/Cosmos-Server)'s reverse proxy. The login and admin page work, but the webmail (Roundcube) page has an infinite redirect to `/webmail/sso.php`.

**Comment by jwr1** [comment]
This is definitely still an issue. For my specific use case, I found a workaround that seems good enough, but the underlying issue is still there.
