### ISSUE TITLE
admin, resolver, and antispam unhealthy - NAT

### ISSUE THREAD

**Issue by ondrejnedoma** [Mailu/Mailu#2853]
## Environment & Version
Debian 11, Docker 24.0.2, Docker compose 2.18.1
### Environment

- [x] docker compose
- [ ] kubernetes
- [ ] docker swarm

### Version
tried both 2 and master

## Description

My server is behind a NAT, and no matter what listen IP I choose, the containers stay unhealthy. First I tried my public IP. That failed the worst, basically the container mailu-front-1 was stuck on creating for over 20 minutes, and when I checked with docker logs, it said that the mailu-admin-1 couldn't reach the DNS. Then I tried 0.0.0.0, <empty>, 127.0.0.1, and my router IP, all with the same success - the containers launch, but they are all unhealthy. docker logs does not give anything, and docker inspect states exit code 7 every 30 seconds on the admin container. I should note that I'm obviously port forwarding everything needed.
## Replication Steps

Try to run mailu behind a NAT, listen on pretty much any possible address, with no success.
## Observed behavior

3 unhealthy containers with no clear indication as to why
## Expected behavior

All containers being healthy, since I don't see any difference between the server being NATed with a port forward, and not being NATed.

**Comment by ghostwheel42** [comment]
Hi.
I'm sorry, but you need a public IP address to run your own mailserver.
When testing you should be able to run the mailu stack behind a nat gateway.
The logs will tell you what is missing (`docker compose logs admin`) - what is the exact error message?
