### ISSUE TITLE
mailu-front-1 cannot start

### ISSUE THREAD

**Issue by sendream** [Mailu/Mailu#2857]
### Environment

- [x] docker compose
- [ ] kubernetes
- [ ] docker swarm

### Version

- Version: `master`

## Logs

Today I will deploy mailu on Ubuntu, when I run "docker compose -p mailu up -d", I keep getting this status "Container mailu-front-1 Starting", what could be the reason.

**Comment by DatHardie** [comment]
Same Problem here

**Comment by izuku-franck1555** [comment]
Same problem. In my case, the error came from the fact that port 443 was being used by another service. Try checking yours !

**Comment by DatHardie** [comment]
For me it was also an already used port.

**Comment by Dr-Ari-Gami** [comment]
I have the same issue. I found no port conflicts. I can see the `start.py` script attempting to run in `htop`, however, the process immediately ends. Docker keeps trying to run it every 5 seconds.

I'm new to docker, is there a way I can see the error log from `start.py`?

**Comment by Dr-Ari-Gami** [comment]
I have the same issue. When running `journalctl -u docker` I found the following error message:
```
level=warning msg="Failed to allocate and map port 995-995: Error starting userland proxy: listen tcp4 XXX.XXX.XXX.XXX:995: bind: cannot assign requested address"
level=error msg="Handler for POST /v1.42/containers/YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY/start returned error: driver failed programming external connectivity on endpoint mailu-front-1 (ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ): Error starting userland proxy: listen tcp4 XXX.XXX.XXX.XXX:995: bind: cannot assign requested address"
```

I already checked the port 995, and it was not in use. While I know it isn't recommended, I'm using an Oracle Cloud free arm Ampere server, if that helps diagnose the issue. I'm not using this mail server for anything mission-critical, so it won't be the end of the world if Oracle decides that they would like to terminate my instance. I also already set Ingress and Egress rules for this port as well through Oracle Cloud's firewall configuration.

**Comment by ghostwheel42** [comment]
You should disable the userland proxy. It is vital for mailu to "see" the real client IP addresses.
Docker relays the requests using iptables when userland proxy is disabled.
You can disable the userland proxy like described here: https://mailu.io/master/faq.html#how-to-make-ipv6-work
