### ISSUE TITLE
Cannot delete mailbox from the admin UI

### ISSUE THREAD

**Issue by nike7o0** [Mailu/Mailu#2858]
### Environment

- [x] docker compose
- [ ] kubernetes
- [ ] docker swarm

### Version

- 2.0:latest

## Description
Cannot delete mailbox from the admin ui, no icon/button.

## Replication Steps
update to 2.0 latest and login in the admin panel

**Comment by ghostwheel42** [comment]
This is by design, as deleting can leave data behind (e-mails, webmail).
It needs to be done via cli: https://mailu.io/master/faq.html#delete-users
You can disable the user in the admin UI and delete via cli.

**Comment by Smartich0ke** [comment]
this doesnt seem to be working for me. I used the `user-delete` command in the mailu cli and the user is still listed in the admin interface.

**Comment by K3RM1T-CYBER** [comment]
> this doesnt seem to be working for me. I used the `user-delete` command in the mailu cli and the user is still listed in the admin interface.

I have exactly the same problem

**Comment by ghostwheel42** [comment]
Hi. User-delete is not supposed to remove a user anymore.
Please read the complete FAQ entry:
https://mailu.io/master/faq.html#how-to-delete-users

**Comment by Smartich0ke** [comment]
I understand the reasoning behind not having such feature as said in the faq but I also feel like fully deleting a user should be a basic requirement for any mail server or CRUD application. Anyone performing user operations from the CLI probably knows what they are doing but some safeguards could be put in place to fully ensure this, like a text-based yes/no confirmation prompt and/or some sort of `--force` flag perhaps?

**Comment by nike7o0** [comment]
The purge_user.sh script has a problem on line 4, it should be like this to work:

admin="$(docker compose ps admin --format=json | jq -r '.ID')"

in github it is

 admin="$(docker compose ps admin --format=json | jq -r '.[].ID')"
