### ISSUE TITLE
413 Request Entity Too Large. Max attachement size with roundcube is 1Mb.

### ISSUE THREAD

**Issue by LukaszJedynowicz** [Mailu/Mailu#2860]
### Environment

- [x] docker compose
- [ ] kubernetes
- [ ] docker swarm

### Version

- Version: `2.0`

## Description
Cannot attach anything larger then 1,048,300 bytes to any email from roundcube

## Replication Steps
Attach anything larger then 1,048,300 bytes to any email from roundcube and it will fails with http 413

## Expected behaviour

I can attach any file as large as the MESSAGE_SIZE_LIMIT as defined in (mailu.env - 33%)\
My mailu.env is set MESSAGE_SIZE_LIMIT=100000000 100Mb-33%=62Mb
## Logs

```
413 Request Entity Too Large
```

**Comment by ghostwheel42** [comment]
This works for me (tested with 2.0 right now). Do you have some other proxy in front of mailu?

**Comment by LukaszJedynowicz** [comment]
Thank you for your response. I have nginx proxy. I changed the settings and everything works as it should.
