### ISSUE TITLE
Password Complexity Requirements

### ISSUE THREAD

**Issue by fabiorauber** [Mailu/Mailu#287]
I've received feedback from a customer saying he could create an account with an extremely simple password, like "123", or even "1". I wonder if we could set password complexity requirements, at least concerning the password length. 

By the way, thanks for the excellent mail solution!

**Comment by kaiyou** [comment]
I believe we could at least set something for password length. That should be easy enough to implement I guess (global setting plus form constraint).

**Comment by witten** [comment]
Note that modern NIST guidelines suggest not including password complexity constraints. Summary: https://nakedsecurity.sophos.com/2016/08/18/nists-new-password-rules-what-you-need-to-know/

But minimum password size and checking against a common password blacklist are good.

**Comment by Nebukadneza** [comment]
Hi There,

The `Mailu`-Project is currently in a bit of a bind! We are short on man-power, and we need to judge if it is possible for us to put in some work on this issue.

To help with that, we are currently trying to find out which issues are actively keeping users from using `Mailu`, which issues have someone who want to work on them — and which issues may be less important. These a less important ones could be discarded for the time being, until the project is in a more stable and regular state once again.

In order for us to better assess this, it would be helpful if you could put a **reaction on this post** (use the :smiley: icon to the top-right).
- 👍️ if you **need this** to be able to use Mailu. Ideally, you’d also be able to test this on your installation, and provide feedback …
- 🎉 if you find it a **nice bonus**, but no deal-breaker
- 🚀 if you want to **work on it yourself**!
We want to keep this **voting open for 2 weeks** from now, so please help out!

**Comment by parisni** [comment]
just to mention https://github.com/dropbox/zxcvbn is a password strengh estimator based on entropy and has an implementation in python
