### ISSUE TITLE
The web client cannot log in, and the email client cannot receive emails

### ISSUE THREAD

**Issue by rebootder** [Mailu/Mailu#2872]
web login
http://192.168.1,120/sso/login
http return 302
I logged into my account via HTTP and returned 302, unable to log in, infinite loop, and the account password is correct

python
imaplib.IMAP4.abort: command: LOGIN => socket error: EOF

**Comment by ghostwheel42** [comment]
Hi. Please follow the setup guide: https://mailu.io/master/setup.html
TLS (https) is mandatory for mailu to function. You also need a public IP address to receive emails.
