### ISSUE TITLE
High rollback rate, is this normal behavior 

### ISSUE THREAD

**Issue by klauserber** [Mailu/Mailu#2875]
### Environment

- [ ] docker compose
- [x] kubernetes
- [ ] docker swarm

### Version

- Version: 2.0.10

## Description

I run Mailu for about 2 week and it runs very well.

My postgres monitoring (rolled out with the zalando operator) shows a high rollback rate, between 3 and 10%.

Is this the normal behavior or is it a bug? Many rollbacks are may be a problem. I just want to report it. 

## Replication Steps

Normal Mailu installation in Kubernetes. 

## Observed behaviour

<img width="1529" alt="Bildschirmfoto 2023-06-28 um 19 58 48" src="https://github.com/Mailu/Mailu/assets/9998995/76b57c36-92fe-47cc-9e66-83fe9f9cb5dd">

## Expected behaviour

A lower less constant rollback rate.

## Logs

There no logs messages that indicates rollbacks.

**Comment by ghostwheel42** [comment]
Mailu is using SQLAlchemy.
I think the cause could be this:

https://stackoverflow.com/questions/7559570/make-sqlalchemy-commit-instead-of-rollback-after-a-select-query?rq=1

Alex

**Comment by klauserber** [comment]
@ghostwheel42 sounds plausible

and it's probably not really a problem, right?

**Comment by ghostwheel42** [comment]
No. It's not a problem.

mailu could commit each transaction (even if there are only SELECTs) and the rollback rate would be lower. 

By default SQLite is used, so normally it goes unnoticed.

Alex
