### ISSUE TITLE
Force the user to change their password at next login

### ISSUE THREAD

**Issue by Marcus1Pierce** [Mailu/Mailu#2877]
### Environment

- [x] docker compose
- [ ] kubernetes
- [ ] docker `swarm`

### Version

- Version: `2.0`

## Description

Instead of directly changing the password by the admin, the admin can create a one-time password reset link for users who have forgotten their passwords, with the condition that the link is connected to the user's email.
## Expected behaviour

First, admin creates a password reset link by accessing the user's email edit menu, where the admin typically resets the password by directly entering a new one. Then, the admin clicks on the option to reset the selected user's email, and the system generates the one-time use link for the user. Subsequently, the admin provides the link to the user, and when the user opens the link, a page appears for them to change their password.

**Comment by nextgens** [comment]
How is that better than "the admin sets a new password and gives it to the user"? In both cases, if the data transmitted to the user is intercepted it's game-over.

Is the actual feature you need the ability for the admin to force a user to change his password at next login?

**Comment by Marcus1Pierce** [comment]
That's a valid point as well. Perhaps, if a user forgets their password and the admin resets it manually, having a feature to force the user to change their password at the next login would be better.

**Comment by ghostwheel42** [comment]
Yes, having the admin change the passowrd and forcing the user to change it would have the same result.
But I think having a fancy reset link would "look" better.
The reset message could be sent to another email address (maybe later even automatically if mailu would allow to specify one for recovary) or via messenger etc.
But yes. Adding a "force new password" flag would be a simple solution.

**Comment by nextgens** [comment]
IMHO you loose flexibility with a reset link: it will have to be longish and difficult to spell out... whereas a new temporary password can be much simpler

**Comment by Marcus1Pierce** [comment]
If using a reset link can reduce flexibility, perhaps using a verification code like Authentication tokens that generate 32 characters, but the difference is that it can only be used once and afterwards the user is forced to change their password. Users can generate their own one-time 32-character passwords and store them in a secure location. If at any time the user forgets their password, they can simply log in using the one-time 32-character password they saved. After logging in with the one-time password, the user will be forced to create a new password, and the one-time password will be regenerated once the user sets a new password. Resetting the password directly from the admin side is sufficient. But from my experience providing email services for several users, sometimes users prefer to use conventional email services like Gmail or Yahoo instead of requesting a password reset. Perhaps if there is an easy way to reset passwords, users can directly reset their own passwords instead of having to ask the admin to change their passwords.

**Comment by nextgens** [comment]
Well that could be implemented using a special type of token/app password that we would allow to login with. @ghostwheel42 do you want to add that to your upcoming PR? :p
