### ISSUE TITLE
Brute-forcing an account locks legitimate user out as only AUTH_RATELIMIT_USER applies, AUTH_RATELIMIT_IP does not

### ISSUE THREAD

**Issue by numo68** [Mailu/Mailu#2880]
### Environment

- [x] docker compose
- [ ] kubernetes
- [ ] docker swarm

### Version

- Version: `2.0`

## Description

Short description: Brute-forcing a single existing account does not count against `AUTH_RATELIMIT_IP`. This is as documented, the result is however blocking the affected *user* for possibly a long time.

Long description: My Mailu instance is configured with the defaults
```
AUTH_RATELIMIT_IP=5/hour
AUTH_RATELIMIT_USER=50/day
```
and an exemption for my trusted home address. Recently I was on vacation and found out I cannot get to my emails. The reason was an attack coming from a single IP trying to brute-force my user only. After 50 attempts the `AUTH_RATELIMIT_USER` was hit, blocking me for a day. `AUTH_RATELIMIT_EXEMPTION` did not help here, as I was 1) checking the mails quite infrequently (iOS low power mode and often no coverage), and 2) while traveling so my IP changed.

The documentation specifies the `AUTH_RATELIMIT_IP` as "the limit of authentication attempts that will be processed on distinct non-existing accounts for a specific IP subnet". There is probably some logic behind not counting *all* failed attempts against `AUTH_RATELIMIT_IP`, I would however prefer to (have the possibility to) have the IP-based limit hitting first, with the `AUTH_RATELIMIT_USER` only reacting if the attacker tries from too many IPs / too long.

## Replication Steps

- have one IP brute-forcing an existing account
- try to access that account from another IP after waiting for `AUTH_RATELIMIT_EXEMPTION`

## Observed behaviour

Being locked out of my e-mails.

## Expected behaviour

The attacker's IP(s) being locked out.

## Logs

```
front_1  | 2023/07/02 13:59:36 [info] 11#11: *488291 client login failed: "Authentication credentials invalid" while in http auth state, client: ROGUE.IP using starttls, server: 0.0.0.0:587, login: "xxxx"
...
front_1  | 2023/07/02 13:59:47 [info] 11#11: *488495 client login failed: "Authentication credentials invalid" while in http auth state, client: ROGUE.IP using starttls, server: 0.0.0.0:587, login: "xxxx"
front_1  | 2023/07/02 13:59:47 [info] 11#11: *488499 client login failed: "Temporary authentication failure (rate-limit)" while in http auth state, client: ROGUE.IP using starttls, server: 0.0.0.0:587, login: "xxxx"
...
front_1  | 2023/07/02 17:55:26 [info] 11#11: *496219 client login failed: "Temporary authentication failure (rate-limit)" while in http auth state, client: LEGITIMATE.IP, server: 0.0.0.0:993, login: "xxxx"
```

**Comment by nextgens** [comment]
Just to clarify: in your example it will count against both limits:
https://github.com/Mailu/Mailu/blob/890f847f6c721959cf24c749b95fee3a2f884a7a/core/admin/mailu/limiter.py#L79

The suggestion is to set a token on your iOS device.

**Comment by numo68** [comment]
> Just to clarify: in your example it will count against both limits:

The result is however the same - if the attacker continues, the legitimate user is locked out, even if the IP has already blocked the attempts. Is there any specific reason for this behavior?

> `AUTH_RATELIMIT_EXEMPTION` expects IP addresses or a list of CIDRs... not a time interval.

Ah, I meant `AUTH_RATELIMIT_EXEMPTION_LENGTH`, sorry for that.

> The suggestion is to set a token on your iOS device.

Thanks, I did that now. The information that the tokens are exempt from the rate limiting should be probably added to the configuration reference, I was not aware of that. Also, if the `AUTH_RATELIMIT_IP` is evaluated for all accounts, the phrase "distinct non-existing accounts" does not seem to reflect that.

Thanks for a great piece of software! Feel free to close the issue, the tokens solve that problem.

**Comment by nextgens** [comment]
> > Just to clarify: in your example it will count against both limits:
> 
> The result is however the same - if the attacker continues, the legitimate user is locked out, even if the IP has already blocked the attempts. Is there any specific reason for this behavior?

Yes, I can think of at least two reasons:
- one attacker may be using a botnet and bruteforcing the same account from different IP ranges. With the current code the attacker is limited to AUTH_RATELIMIT_USER attempts per period, regardless of how many IPs they control.
- "hitting" both limiters will refresh/extend the period for which the IP range will be blocked and the "wrong" password distinctively accounted for.

**Comment by nextgens** [comment]
Good point on the documentation, I'll tweak it on my next PR
