### ISSUE TITLE
`webdav` unavailable in generated `docker-compose.yml`

### ISSUE THREAD

**Issue by Flowneee** [Mailu/Mailu#2882]
### Environment

- [x] docker compose
- [ ] kubernetes
- [ ] docker swarm

### Version

- Version: `2.0`

## Description

Hi. I created `docker-compose.yml` via https://setup.mailu.io/2.0/ with `webdav` feature, but was unable to access it from outside, getting 502. Apparently this service is misconfigured in generated `docker-compose.yml` and missing dependency part, thus rendering service unavaliable for `front` service (hostname doesn't resolve). Adding

```yml
    depends_on:
      - front
```

to `webdav` service helped.

## Replication Steps

Generate config via setup utility, selecting `webdav` feature, then download docker-compose.yml. Here is example https://setup.mailu.io/2.0/file/99baacf5-8de5-4af2-9d08-0f039476cf70/docker-compose.yml

## Observed behaviour

Receiving 502 when trying to access webdav page at `webdav/.web/`.

## Expected behaviour

Everything works.

## Logs
```
$ docker-compose logs front webdav -fn1
mailu-webdav-1  | [2023-07-08 11:44:26 +0000] [1] [INFO] Radicale server ready
mailu-front-1   | 2023/07/10 19:52:19 [error] 12#12: *57927 webdav could not be resolved (3: Host not found) while sending to client, client: 192.168.203.1, server: , request: "GET /webdav/.web HTTP/1.0", host: "..."
```

**Comment by Flowneee** [comment]
Apparently suggested fix didn't work, it still sometimes breaks. I was unable to determine why (yet).

**Comment by nextgens** [comment]
@Flowneee the webmail container is now on its own network called "webmail". Front is also on that network and should be able to reach it

**Comment by Flowneee** [comment]
Problem is not with `webmail`, problem is with `webdav`, which is in it's own network `radicale`, and for some reason it cannot be resolved from `front`.
