### ISSUE TITLE
Connect Mailu WebDAV (Radicale) to Roundcube

### ISSUE THREAD

**Issue by alexsalex** [Mailu/Mailu#2883]
Always get a timeout and cant make it work. Did somebody connect it? If so could you help?

<img width="912" alt="Screenshot 2023-07-12 at 5 40 33 PM" src="https://github.com/Mailu/Mailu/assets/17325366/bdf99667-d010-48f4-8793-cdd2bf47660a">

**Comment by nextgens** [comment]
Check #589 out
