### ISSUE TITLE
Webmail Not Accessible

### ISSUE THREAD

**Issue by maregedze** [Mailu/Mailu#2886]
Everything else is working properly except the webmail.

Error:  **The page isn’t redirecting properly**.

This issue has just started, it used to work well.

**Comment by qy117121** [comment]
also encountered this problem

**Comment by ben221199** [comment]
Same. The mailserver also seems to respond with some internal server error (both SMTP and IMAP), so it isn't just the webmail.

The temporary solution that works at the moment:
```shell
cd /mailu
docker-compose down && docker-compose up -d
```

**Comment by ben221199** [comment]
I saw some line (not saved, sorry) that mentions Dovecot somehow being killed by signal 9 (SIGKILL). Can be my system consuming too much CPU, but I don't know. Also, the webmail image gives the following error when starting: `nginx: [emerg] host not found in set_real_ip_from "front" in /etc/nginx/http.d/webmail.conf:31`.

**Comment by ben221199** [comment]
Likely same problem as #2850 and #2890.

**Comment by geckolinux** [comment]
I'm also seeing this. It only happens after rebooting the server when it had been up for at least 24 hours roughly. After running `docker-compose down && docker-compose up -d` it starts working again and even survives another reboot of the server if it hasn't been up for too long.

I'm using the `TLS_FLAVOR=cert` method (certs are handled by another web app).

When this bug happens it also prevents connecting to Mailu over POP3.

The browser shows: "The page isn’t redirecting properly"

I'm also seeing `The certificate is empty` (not true) and `Fatal error: Dovecot is already running` in the logs.

**Comment by nextgens** [comment]
Please join https://app.element.io/#/room/#mailu:tedomum.net to get support. We can't help if you do not share details about your config.

> I'm also seeing The certificate is empty (not true) and Fatal error: Dovecot is already running in the logs.

That is harmless and unrelated

**Comment by phen0** [comment]
@mamiu could you please post your mailu.env file? I've got the same endless loop accessing webmail.

**Comment by geckolinux** [comment]
@phen0 You might first want to try upgrading Mailu. There was a recent fix for another more fundamental error that was also preventing access to webmail in some cases, specifically where webmail was inaccesible after a server reboot:
https://github.com/Mailu/Mailu/commit/d026f7023930fcf4eb47c58991eb9201a4a69682

**Comment by phen0** [comment]
@geckolinux my Mailu installation is working like a charm...only few little bugs I already raised an issue for.
I'm currently on version 2.0. To which version are you referring to?

**Comment by geckolinux** [comment]
The Mailu 2.0.22 release yesterday included a fix for Mailu installations that were running fine but sometimes randomly failed after rebooting the server.

**Comment by ben221199** [comment]
@geckolinux Is that the infinite redirect issue? If that is the case, I will update directly.

**Comment by geckolinux** [comment]
@ben221199 It could be a side effect of #2917, so I'd say it's worth upgrading.

**Comment by mamiu** [comment]
@phen0 Sure, here's my `mailu.env` file:

<details>
<summary>mailu.env</summary>
<p>

```conf
# Mailu main configuration file
#
# This file is autogenerated by the configuration management wizard for compose flavor.
# For a detailed list of configuration variables, see the documentation at
# https://mailu.io

###################################
# Common configuration variables
###################################

# Set to a randomly generated 16 bytes string
SECRET_KEY=2CRK4JTPB18LFGAX

# Subnet of the docker network. This should not conflict with any networks to which your system is connected. (Internal and external!)
SUBNET=192.168.203.0/24

# Main mail domain
DOMAIN=mydomain.com

# Hostnames for this server, separated with comas
HOSTNAMES=mail.mydomain.com,mail.anotherdomain.com

# Postmaster local part (will append the main mail domain)
POSTMASTER=admin

# Choose how secure connections will behave (value: letsencrypt, cert, notls, mail, mail-letsencrypt)
TLS_FLAVOR=letsencrypt

# Authentication rate limit per IP (per /24 on ipv4 and /48 on ipv6)
AUTH_RATELIMIT_IP=5/hour

# Authentication rate limit per user (regardless of the source-IP)
AUTH_RATELIMIT_USER=50/day

# Opt-out of statistics, replace with "True" to opt out
DISABLE_STATISTICS=False

###################################
# Optional features
###################################

# Expose the admin interface (value: true, false)
ADMIN=true

# Choose which webmail to run if any (values: roundcube, snappymail, none)
WEBMAIL=roundcube

# Expose the API interface (value: true, false)
API=false

# Dav server implementation (value: radicale, none)
WEBDAV=none

# Antivirus solution (value: clamav, none)
ANTIVIRUS=none

# Scan Macros solution (value: true, false)
SCAN_MACROS=true

###################################
# Mail settings
###################################

# Message size limit in bytes
# Default: accept messages up to 50MB
# Max attachment size will be 33% smaller
MESSAGE_SIZE_LIMIT=50000000

# Message rate limit (per user)
MESSAGE_RATELIMIT=100/day

# Networks granted relay permissions
# Use this with care, all hosts in this networks will be able to send mail without authentication!
RELAYNETS=

# Will relay all outgoing mails if configured
RELAYHOST=

# Enable fetchmail
FETCHMAIL_ENABLED=False

# Fetchmail delay
FETCHMAIL_DELAY=600

# Recipient delimiter, character used to delimiter localpart from custom address part
RECIPIENT_DELIMITER=+

# DMARC rua and ruf email
DMARC_RUA=admin
DMARC_RUF=admin

# Welcome email, enable and set a topic and body if you wish to send welcome
# emails to all users.
WELCOME=false
WELCOME_SUBJECT=Welcome to your new email account
WELCOME_BODY=Welcome to your new email account, if you can read this, then it is configured properly!

# Maildir Compression
# choose compression-method, default: none (value: gz, bz2, zstd)
COMPRESSION=
# change compression-level, default: 6 (value: 1-9)
COMPRESSION_LEVEL=

# IMAP full-text search is enabled by default. Set the following variable to off in order to disable the feature.
# FULL_TEXT_SEARCH=off

###################################
# Web settings
###################################

# Path to redirect / to
WEBROOT_REDIRECT=/webmail

# Path to the admin interface if enabled
WEB_ADMIN=/admin

# Path to the webmail if enabled
WEB_WEBMAIL=/webmail

# Path to the API interface if enabled
WEB_API=

# Website name
SITENAME=Mailu

# Linked Website URL
WEBSITE=https://mailu.io



###################################
# Advanced settings
###################################

# Docker-compose project name, this will prepended to containers names.
COMPOSE_PROJECT_NAME=mailu1

# Number of rounds used by the password hashing scheme
CREDENTIAL_ROUNDS=12

# Header to take the real ip from
REAL_IP_HEADER=

# IPs for nginx set_real_ip_from (CIDR list separated by commas)
REAL_IP_FROM=

# choose wether mailu bounces (no) or rejects (yes) mail when recipient is unknown (value: yes, no)
REJECT_UNLISTED_RECIPIENT=

# Log level threshold in start.py (value: CRITICAL, ERROR, WARNING, INFO, DEBUG, NOTSET)
LOG_LEVEL=WARNING

# Timezone for the Mailu containers. See this link for all possible values https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
TZ=Etc/UTC

# Default spam threshold used for new users
DEFAULT_SPAM_THRESHOLD=80

# API token required for authenticating to the RESTful API.
# This is a mandatory setting for using the RESTful API.
API_TOKEN=
```

</p>
</details>

But to me it sound like the issue @geckolinux described and said is fixed now.

**Comment by phen0** [comment]
Doesn't look that bad. And you don't make use of a reverse proxy? I.e. you're accessing mailu directly?
Maybe you could share a log excerpt too?

**Comment by mamiu** [comment]
Correct, I don't use a reverse proxy.

Sorry I can't share the logs with you anymore, since @ben221199's [temporary solution](https://github.com/Mailu/Mailu/issues/2886#issuecomment-1661209534) fixed it for me.

```bash
cd /mailu
docker compose down && docker compose up -d
```
