### ISSUE TITLE
Real_IP not shown in front server

### ISSUE THREAD

**Issue by phen0** [Mailu/Mailu#2888]
### Environment

- [x] docker compose
- [ ] kubernetes
- [ ] docker swarm

### Version

- Version: `2.0`

## Description

I've setup mailu with docker-compose and I'm using an nginx v1.17 with docker in host mode and really I've tried everything for days but no luck. Unfortunately I'm not able to get the real ip in mailu nginx server. Only getting the docker internal ip 192.168.203.1. I require the real IP if I want to block senders in postfix or something similar.

Moreover every single request is sent from docker IP 192.168.203.1 hence I'm reaching the rate-limit within minutes and can't login to the GUI.

## Replication Steps

The reverse proxy vhost configuration:
```
upstream mailu {
                        ## Can be connected with "nginx-web_default" network
                        # hc-web
                        server 10.x.x.x:443;
}
server {
        server_name mailu.example.com;
        include /etc/nginx/conf.d/http.include;
}
server {
        server_name mailu.example.com;
        ### SSL CERT SECTION
        #ssl_certificate /etc/nginx/certs/default.crt;
        #ssl_certificate_key /etc/nginx/certs/default.key;
        #ssl_dhparam /etc/nginx/certs/dhparam.pem;

        ssl_certificate /etc/nginx/certs/mail.example.com.crt;
        ssl_certificate_key /etc/nginx/certs/mail.example.com.key;
        ssl_trusted_certificate /etc/nginx/certs/mail.example.com.chain.pem;
        ssl_dhparam /etc/nginx/certs/mail.example.com.dhparam.pem;

        include /etc/nginx/conf.d/ssl.include;
        location / {
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_pass https://mailu;
                proxy_redirect https://10.x.x.x:443 https://$host;
        }
} 
``` 

mailu.env
```
SECRET_KEY=XXXXXXXXXX
SUBNET=192.168.203.0/24
DOMAIN=example.com
HOSTNAMES=mailu.example.com
POSTMASTER=admin
TLS_FLAVOR=letsencrypt
AUTH_RATELIMIT_IP=5/hour
AUTH_RATELIMIT_USER=50/day
DISABLE_STATISTICS=False
ADMIN=true
WEBMAIL=roundcube
API=false
WEBDAV=none
ANTIVIRUS=clamav
SCAN_MACROS=true
MESSAGE_SIZE_LIMIT=50000000
MESSAGE_RATELIMIT=200/day
RELAYNETS=
RELAYHOST=
FETCHMAIL_ENABLED=true
FETCHMAIL_DELAY=600
RECIPIENT_DELIMITER=+
DMARC_RUA=admin
DMARC_RUF=admin
WELCOME=false
WELCOME_SUBJECT=Welcome to your new email account
WELCOME_BODY=Welcome to your new email account, if you can read this, then it is configured properly!
COMPRESSION=
COMPRESSION_LEVEL=
WEBROOT_REDIRECT=/
WEB_ADMIN=/admin
WEB_WEBMAIL=/
WEB_API=
SITENAME=Mailu
WEBSITE=https://mailu.example.com
COMPOSE_PROJECT_NAME=mailu
CREDENTIAL_ROUNDS=12
REAL_IP_HEADER=X-Real-IP
REAL_IP_FROM=10.x.x.x     # REVERSE PROXY IP
REJECT_UNLISTED_RECIPIENT=
LOG_LEVEL=WARNING
TZ=Europe/Berlin
DEFAULT_SPAM_THRESHOLD=80
API_TOKEN=
``` 

docker-compose file is default. All ports of front server are bound to the public ip 10.x.x.x (80,443,25,465,587,110,995,143,993).
## Observed behaviour

I can access admin and webmail gui but the log entry is always showing (example log entry):
``` 
mailu-front-1  | 192.168.203.1 - - [24/Jul/2023:14:18:05 +0200] "GET /sso/login?url=/ HTTP/2.0" 200 2079 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.5.2 Safari/605.1.15"
``` 

## Expected behaviour

I've set the REAL_IP parameters but still I'm not seeing the public IP's (internal or external). E.g. 10.x.x.x for my internal network or public ones from the internet.

**Comment by nextgens** [comment]
Try disabling the userland proxy: https://mailu.io/master/faq.html#how-to-make-ipv6-work

If that doesn't work, can you confirm that your proxy sees and logs the right IP?

**Comment by phen0** [comment]
I had to set REAL_IP_FROM to 0.0.0.0/0, ::0 otherwise it didn't seem to work. Working now.

**Comment by nextgens** [comment]
There is no scenario where that makes sense. I encourage you to list the CIDRs where your proxy might be instead.

**Comment by phen0** [comment]
You're right....somehow it's working if I use the proxy. Connecting directly to mailu via curl shows only the docker ip.
