### ISSUE TITLE
Recommend making DNSSEC validation configurable as an option

### ISSUE THREAD

**Issue by magicJie** [Mailu/Mailu#2889]
Although DNSSEC can enhance security, not all DNS servers and domain servers support DNSSEC. Due to various reasons, my environment cannot support DNSSEC, which prevents me from using Mailu. Enforcing this validation is clearly sacrificing the flexibility of the software. Why not consider an optimization instead?

**Comment by ghostwheel42** [comment]
duplicate of #2854
