### ISSUE TITLE
remove footer on webmail login.

### ISSUE THREAD

**Issue by huseyn92** [Mailu/Mailu#2899]
### Environment

- [x] docker compose
- [ ] kubernetes
- [ ] docker swarm

### Version

- Version: `master`

**Comment by nextgens** [comment]
What do you mean? Can you at least post a screenshot or something?

**Comment by huseyn92** [comment]
![image](https://github.com/Mailu/Mailu/assets/50009358/d102de00-8c66-46d6-b3f8-2df5e9b82290)
How I can change this section ? and change  this logo
![image](https://github.com/Mailu/Mailu/assets/50009358/8763db92-2c26-437d-8a05-6e1f3d92019d)

**Comment by nextgens** [comment]
The template is in core/admin/mailu/ui/templates/base.html
