### ISSUE TITLE
Looking for someone to maintain the test server

### ISSUE THREAD

**Issue by kaiyou** [Mailu/Mailu#290]
Keeping up with the project is already difficult enough, thankfully contributors make that task a lot easier. I cannot however manage the test server properly as I do not have access to my computer every day.

If anyone is interested, kind enough and available enough to make sure that the test server runs properly on `master`, let's talk :)

**Comment by SaiGonSeamus** [comment]
Hey there, 
How do I join this chan?

**Comment by kaiyou** [comment]
The Matrix channel is linked from the README. You can join from any Matrix client on any Matrix server using this link: https://matrix.to/#/#mailu:tedomum.net (address is #mailu:tedomum.net)
