### ISSUE TITLE
Need help with self-signed certificate for stable and nginx

### ISSUE THREAD

**Issue by snesbittsea** [Mailu/Mailu#291]
All:

Can someone provide a step by step guide for getting the stable branch to work with a self-signed certificate? Current docs are incomplete and reference a version of mailu (1.5) that is not available yet.

What I've done so far is:
- Set FRONTEND=nginx
- Set EXPOSE_ADMIN to yes
- Comment out ENABLE_CERTBOT
- Created a key and cert and converted them to PEMS in the /mailu/certs directory
- Linked /certs to /mailu/certs

Results is:
```
http_1       | 2017/10/28 18:15:44 [emerg] 7#7: BIO_new_file("/certs/cert.pem") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/certs/cert.pem', 'r') error:2006D080:BIO routines:BIO_new_file:no such file)
http_1       | nginx: [emerg] BIO_new_file("/certs/cert.pem") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/certs/cert.pem', 'r') error:2006D080:BIO routines:BIO_new_file:no such file)
http_1       | 2017/10/28 18:24:33 [emerg] 7#7: PEM_read_bio_X509_AUX("/certs/cert.pem") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)
http_1       | nginx: [emerg] PEM_read_bio_X509_AUX("/certs/cert.pem") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: TRUSTED CERTIFICATE)

```
Thx in advance.

-steve

**Comment by kaiyou** [comment]
The `/certs` directory is actually mounted by Docker, do you still have the `$ROOT/certs:/certs` line in the `nginx` service description?

**Comment by snesbittsea** [comment]
Ok I tracked it down to a bad certificate ( a file size of 0 can't be good :-)

I will mention that mailu does expect certain names - cert.pem and key.pem

Thx for the help
