### ISSUE TITLE
Change default SMTP port

### ISSUE THREAD

**Issue by nesterov26** [Mailu/Mailu#2916]
Greetings,

Could you please provide guidance on how to modify the default port number?

Hetzner Cloud defaults to blocking port 25, and a request is necessary for access, typically granted to longstanding users. However, port 587 is permitted. I am unsure about the specific configuration that requires adjustment in this context.

**Comment by AvverbioPronome** [comment]
@nesterov26 mailu uses both already. And 465 too.

**Comment by ghostwheel42** [comment]
@nesterov26 you cannot change the port number other MTAs (mail servers) use to connect to your server.
You can also not change the port numbers your server uses to connect to other MTAs.

**Comment by tin607** [comment]
https://github.com/Mailu/Mailu/issues/3223#issue-2238888999
