### ISSUE TITLE
Authentication failure when client connects via ipv6

### ISSUE THREAD

**Issue by nitroxis** [Mailu/Mailu#2918]
### Environment

- [x] docker compose
- [ ] kubernetes
- [ ] docker swarm

### Version

- Version: `master`

## Description
When a client connects via ipv6 it seems to be unable to send mails due to a "Bad ADDR syntax" error. The syntax of the ipv6 IP appears to be correct however (unless it's meant to be in brackets?). I've not found anything related to this error anywhere, seems like it's not a very common issue.

## Replication Steps
Enable ipv6 support in Mailu and try to connect via ipv6 natively. I don't know if there are any special things in my setup.

## Observed behaviour
Client isn't able to send mail due to an error (see logs).

## Expected behaviour
It should work just the same as ipv4.

## Logs
```
mailu-front-1      | Aug 21 09:18:45 submission-login: Error: proxy(test@example.com,192.168.203.7:10025): Aborting due to remote server: XCLIENT failed: 501 5.5.4 Bad ADDR syntax: 2003:eb:XXXX: user=<test@example.com>, method=PLAIN, rip=2003:eb:XXXX, rport=36882, lip=fdee:eeee:eeee:eeee::4, lport=587, TLS
mailu-front-1      | Aug 21 09:18:45 submission-login: Info: Disconnected: Connection closed (internal failure, 1 successful auths): user=<test@example.com>, method=PLAIN, rip=2003:eb:XXXX, rport=36882, lip=fdee:eeee:eeee:eeee::4, lport=587, TLS
```

(ipv6 address redacted, it is correct in the real log)

**Comment by nextgens** [comment]
This is a known problem only affecting master. The fix is at https://github.com/dovecot/core/commit/88751f93d04816313f0fbcafe3a7fc018f5b9328 but it's not in any released version of dovecot

**Comment by dieideeistgut** [comment]
Temporary solution which helped me with this was @nextgens hint to disable AAAA-records until the dovecot fix gets released.

**Comment by nextgens** [comment]
I have left a comment on the commit and filed an issue on the alpine bug-tracker.

https://gitlab.alpinelinux.org/alpine/aports/-/issues/15340

**Comment by nextgens** [comment]
@nitroxis @dieideeistgut please retry with current master and report back if it hasn't fixed it
