### ISSUE TITLE
Non CSS mime types not allowed

### ISSUE THREAD

**Issue by phen0** [Mailu/Mailu#2922]
### Environment

- [x] docker compose
- [ ] kubernetes
- [ ] docker swarm

### Version

- Version: `2.0`

## Description

I'm using a MacBook M1 and in Safari it happens quite often that I get an error opening the Anti-spam menu. The page is displayed but the css is not being processed.

The error message I see in Dev Console is:
```non CSS MIME types are not allowed in strict mode```

Crawling the internet revealed that this issue occurs also for other projects on GitHub too.

## Replication Steps

Login to admin console with Safari. Open Antispam GUI. Open the admin area again. Do this a few times let's say 3-4 times going back and forth and the error will occur.
 
## Observed behaviour

Well a webpage without css looks lousy. And I see the error in dev console: 
```
[Error] Did not parse stylesheet at 'https://post.example.com/admin/antispam/css/prism.css' because non CSS MIME types are not allowed in strict mode.
```

**Comment by nextgens** [comment]
I think the new version of rspamd has fixed it in master.

Can you reproduce the problem with https://test.mailu.io/admin/antispam/css/prism.css ? Using credentials from https://mailu.io/master/demo.html#connecting-to-the-server
