### ISSUE TITLE
fetchmail does not fetch mails in 2.0

### ISSUE THREAD

**Issue by sholl** [Mailu/Mailu#2928]
### Environment

- [X] docker compose
- [ ] kubernetes
- [ ] docker swarm

### Version

- Version: 2.0, Container-"Id": "sha256:dd0a30f2ecb74491c49c8ab1b1d8d710eb55cc1e81d411acea9171ebd40ff314",

## Description

After updating from 1.9 to 2.0 fetchmails does not fetch mails from remote POP3s-Servers. The container-logs contain the following information with log-level WARNING. Log-level DEBUG does not print more useful information

```
mailu-20-fetchmail-1  | Option --folder is not supported with POP3
mailu-20-fetchmail-1  | Option --folder is not supported with POP3
mailu-20-fetchmail-1  | Option --folder is not supported with POP3
mailu-20-fetchmail-1  | Sleeping for 1000 seconds
mailu-20-fetchmail-1  | fetchmail: Query status=5 (SYNTAX)
mailu-20-fetchmail-1  |
mailu-20-fetchmail-1  |
mailu-20-fetchmail-1  | fetchmail: Query status=5 (SYNTAX)
```
I copied the mailu.db and fired up the new stack based on the newly created configs and docker-compose.yml-files.

## Replication Steps

migrated DB from 1.9 copied to the new folder and starting the stack.

## Observed behaviour

Any chance to get more detailed information from within the container?

## Expected behaviour

Fetching the remote mails and make them available in mailus mail-storage

**Comment by nextgens** [comment]
We can either find a way to enable MBOX (and assume the remote server supports it) or skip setting folders in the configuration file when we are configured to use pop3

https://sources.debian.org/src/fetchmail/6.3.26-3/pop3.c/#L978

**Comment by nextgens** [comment]
@sholl When the CI has finished on the attached PR, please try editing your docker-compose.yml and change the following:

```
fetchmail:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}fetchmail:pr2929
```

Then ``docker compose up -d`` and report if it fixes it please.

**Comment by sholl** [comment]
@nextgens will do. Is there a way I can see if the image is available AKA CI has finished? Currently the images is not available (yet).
```
$ docker inspect ghcr.io/mailu/fetchmail:pr2929
[]
Error: No such object: ghcr.io/mailu/fetchmail:pr2929
```

**Comment by nextgens** [comment]
Oh! my bad, there is a score; it's ``pr-2929``

https://github.com/Mailu/Mailu/pkgs/container/fetchmail/123333006?tag=pr-2929

**Comment by sholl** [comment]
thanks @nextgens , tested the above image. We got one step further, but still some errors:

```
mailu-20-fetchmail-1  | fetchmail: Connection errors for this poll:
mailu-20-fetchmail-1  | name 0: connection to front:2525 [192.168.210.3/2525] failed: Connection refused.
mailu-20-fetchmail-1  | fetchmail: LMTP connect to front/2525 failed
mailu-20-fetchmail-1  | fetchmail: SMTP transaction error while fetching from XXXX@XXXX and delivering to SMTP host front/2525
```

It seems the port is somehow doubled? should be front:25 instead of front:2525.

**Comment by nextgens** [comment]
Thank you for confirming that it works.

Things have moved on master... that's why it doesn't work. We will merge the fix and release a new build for 2.0 and that will work.

In the meantime, if you need it to work you need to export ``FRONT_ADDRESS=imap`` in the environment but exclusively for the fetchmail container.

Don't forget to revert your docker-compose.yml to what it was when you upgrade to the fixed 2.x build.

**Comment by nextgens** [comment]
@sholl 2.0.23 should solve the problem; please re-open if it doesn't

**Comment by sholl** [comment]
confirmed, works again. Thanks!
