### ISSUE TITLE
ERROR: manifest for mailu/traefik:stable not found

### ISSUE THREAD

**Issue by scottolipra** [Mailu/Mailu#293]
Following instructions at https://github.com/Mailu/Mailu/wiki/Setup-Guide , I chose to enable traefik in the .env file as reverse proxy. 

When I then issue docker-compose up -d, I get an error:
```
user@myhost:/opt/mailu$ docker-compose up -d
Creating network "mailu_default" with the default driver
Pulling http (mailu/traefik:stable)...
ERROR: manifest for mailu/traefik:stable not found
user@myhost:/opt/mailu$
```

I'm guessing there's a tag ":stable" missing in Docker Hub, on mailu/traefik.

**Comment by kaiyou** [comment]
For a pretty good reason, `traefik` is not stable yet, and will actually never be :)
I have to update that setup guide, as `traefik` was first envisioned for version `1.5` due next week, but has since been replace with a beefed-up version of nginx.

**Comment by scottolipra** [comment]
Understood. 

I changed the option to "none", and will check back.
Closing issue.
