### ISSUE TITLE
rspamd not saving scores possible owner/group issue

### ISSUE THREAD

**Issue by phen0** [Mailu/Mailu#2931]
### Environment

- [x] docker compose
- [ ] kubernetes
- [ ] docker swarm

### Version

- Version: `2.0`

## Description

Hi,

I noticed today that I can't change the scoring in rspamd (symbols menu). Moreover the blacklist.inc and whitelist.inc which has been created in overrides folder is read only in rspamd.
If I change o/g to rspamd it becomes editable both. white/blacklist as well as policies_group.conf

## Replication Steps

Try to change the black/whitelist via rspamd gui as well as try to change the scoring in symbols menu.

## Observed behaviour

Nothing changes. Values remain unchanged.

## Expected behaviour

Changes should be stored. What about persistence? Are the changes gone once I upgrade mailu version?

**Comment by phen0** [comment]
Should this ticket be closed and retested after an mailu update to the most recent version?

**Comment by ghostwheel42** [comment]
Don't worry. The changes you do to the files are persisted.

**Comment by ghostwheel42** [comment]
You wrote "If I change o/g to rspamd it becomes editable both."
Can you edit the files after changing permissions? Everything located in the storage/data folders will persist.

**Comment by phen0** [comment]
I've changed the owner/group of the blacklist.inc & whitelist.inc file to rspamd(101) in local overrides/rspamd folder but if I login to the container owner/group of these files are set to root.
