### ISSUE TITLE
POP3/IMAP is not accessable using external mail clients

### ISSUE THREAD

**Issue by LZNetwork-Main** [Mailu/Mailu#2933]
### Environment

- [X] docker compose
- [ ] kubernetes
- [ ] docker swarm

### Version

- Version: `2.0`

## Description
After following the guide, and trying with multiple clean installs of Debian, even trying different subdomains and domains, I am unable to connect using any external mail client (Gmail, Roundcube, Thunderbird), Thunderbird says that the connection has been actively refused. (I have not yet tried the internal Webmail) However, mail gets through without a problem - ingest and egress both.

## Replication Steps
Get a brand new installation of Mailu, and try to connect using external mail clients.

## Observed behaviour
The mail client connection gets refused without any additional logs.

## Expected behaviour
I am able to connect to the mail server using any POP3 or IMAP external mail client.

## Logs
This is a snippet of the whole server logs, I could not find anything related. 
https://pastebin.com/xvLxWMpU

**Comment by LZNetwork-Main** [comment]
Just wanted to add that the IPs in the log file are some random IPs trying to login or something, the IPs of my mail clients are not present.

**Comment by nextgens** [comment]
Here is the relevant part of the log:
```
mailu-front-1      | Error creating new order :: too many certificates (5) already issued for this exact set of domains in the last 168 hours: mx1.redacted.net, retry after 2023-09-02T04:47:29Z: see https://letsencrypt.org/docs/duplicate-certificate-limit/
mailu-front-1      | Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.
mailu-front-1      | Saving debug log to /var/log/letsencrypt/letsencrypt.log
```

**Comment by ghostwheel42** [comment]
The setup wizard creates a working config with opened ports. Unless there is another firewall in front of your setup, this is not expected. Please reach out to the paper in the mailu matrix channel to help debugging this. It's probably not related to the mailu stack.
