### ISSUE TITLE
Fix the log filter to make the "LMTP: The certificate is empty" error message disappear

### ISSUE THREAD

**Issue by ouafnico** [Mailu/Mailu#2939]
### Environment

Docker-compose installation

### Version

- Version: `2.0.23`

## Description

On logs, we can see a lot of LMTP errors 

```
mailu-imap[1019]: Sep 14 15:08:05 lmtp(225): Error: SSL context initialization failed, disabling SSL: Can't load SSL certificate (ssl_cert setting): The certificate is empty
```

## Replication Steps
Just receive an email, it will be shown every time.

## Observed behaviour
No problems actually, but the error appears for each received mail

It seems it's hardcoded in the models.py file, that the LMTP is contacted over imap container, on port 2525

```
    def sendmail(self, subject, body):
        """ send an email to the address """
        try:
            f_addr = f'{app.config["POSTMASTER"]}@{idna.encode(app.config["DOMAIN"]).decode("ascii")}'
            with smtplib.LMTP(host=app.config['IMAP_ADDRESS'], port=2525) as lmtp:
                to_address = f'{self.localpart}@{idna.encode(self.domain_name).decode("ascii")}'
                msg = text.MIMEText(body)
                msg['Subject'] = subject
                msg['From'] = f_addr
                msg['To'] = to_address
                lmtp.sendmail(f_addr, [to_address], msg.as_string())
            return True
        except smtplib.SMTPException:
            return False
```

But, on imap, no ssl_certs are declared, I guess because they are managed by the front container.

The question is :

- do we need to modify and route lmtp over front container ?
- or, do we need to modify some configuration to avoid the usage of ssl protocol for lmtp ?
- or, do we have to push certificates on imap container too?

Thanks,

**Comment by nextgens** [comment]
The error message ought to be filtered: https://github.com/Mailu/Mailu/blob/2.0/core/dovecot/start.py#L12
If it isn't we should fix the filtering...

We do not want TLS to be used locally for LMTP; Dovecot complains that it can't do it because we haven't configured a certificate and that is done on purpose.

Ideally we would tell explicitly dovecot that we do not want TLS for anything related to LMTP... Maybe we should add a section like the following:

```
protocol lmtp {
  ssl = no
}
```

**Comment by ouafnico** [comment]
Thanks for your feedback.
According to the doveconf, the ssl = no is already used

```
service lmtp {
  chroot = 
  client_limit = 1
  drop_priv_before_exec = no
  executable = lmtp
  extra_groups = $default_internal_group
  group = 
  idle_kill = 0
  inet_listener lmtp {
    address = 
    haproxy = no
    port = 2525
    reuse_port = no
    ssl = no
  }
  privileged_group = 
  process_limit = 0
  process_min_avail = 0
  protocol = lmtp
  service_count = 0
  type = 
  unix_listener lmtp {
    group = 
    mode = 0666
    user = 
  }
  user = 
  vsz_limit = 18446744073709551615 B
}
```

**Comment by nextgens** [comment]
Right, so filtering it like we are already attempting to do is probably our only option... and we should fix the filter.
