### ISSUE TITLE
resolver issues

### ISSUE THREAD

**Issue by alxlcr** [Mailu/Mailu#2940]
Hi there,
I have a special use case: I am building a completely disconnected (air-gapped) network; I have been using Mailu 1.9  since it came out with no issues and now I am trying to update my build to 2.0. My resolver does not start properly and the admin container complains about timeout while trying to resolve example.org. My DNS servers are fine, I can resolve my internal domains with no issues, but the test specifically goes to example.org... I understand that this is a very unique scenario, and I am looking at  possible solutions:
1. is there a way to disable this check in the build?
2. another option would be to add the example.org zone to the resolver, but not sure if there are any other checks down the road;
3. I could come up with other mitigating measures, but again, I think that a deeper understanding of the checks done would help; this could be an enhancement; 
4. of course, I can stick with 1.9 but I wouldn't call that sustainable

Any thoughts? I think this would be a useful enhancement if possible.

**Comment by nextgens** [comment]
DNSSEC sign example.org locally and it will work. I am fairly sure that there aren't any other checks. Simply adding the DNS record won't be enough, it needs to be DNSSEC signed (but can be signed using a different root of trust).

https://github.com/Mailu/Mailu/blob/master/core/admin/start.py#L43
