### ISSUE TITLE
Import issue

### ISSUE THREAD

**Issue by wezbowebservices** [Mailu/Mailu#2941]
### Environment

- [ ] docker compose
- [ ] kubernetes
- [ ] docker swarm

### Version

- Version: `master`

## Description

We have encountered a significant problem when attempting to import files larger than 50 MB into our system. Despite numerous attempts to configure the system settings to accommodate such imports, we consistently encounter errors. To address this issue and improve the user experience, I propose the implementation of a user import limit configuration feature within the admin panel.

## Expected behaviour

To overcome this challenge, I suggest the development of a new feature in the admin panel that allows us to configure user import limits. This feature would provide us with the following benefits:

Automation: The ability to set user import limits would automate the process, reducing the need for manual intervention and minimizing the chances of errors during data transfer.

Faster Data Transfer: With the import limit configuration, users can efficiently migrate their data to our platform without encountering size-related errors. This would make the migration process faster and more reliable.

Attracting More Users: By offering a seamless data migration experience, we can attract more users, including those who are looking to switch from other email service providers. This could lead to an increase in user base and revenue.

Competitive Advantage: Implementing this feature would give us a competitive edge in the market by providing a solution to a common problem faced by email service users.

**Comment by nextgens** [comment]
What do you mean by "import files" ? Can you produce matching log files?
