### ISSUE TITLE
Wiki setup guide unclear related to persistent directory

### ISSUE THREAD

**Issue by kaymccormick** [Mailu/Mailu#295]
The set-up guide at https://github.com/mailu/mailu/wiki/Setup-Guide is vague related to the instructions to create the "mailu" directory, at least for someone new to docker and running on the windows platform. I am trying to deploy mailu to a remote machine, but maybe I should run these commands on the host itself? This isn't clear to me, especially as it relates to working on a windows development machine.

**Comment by kaiyou** [comment]
Indeed, this must not be clear for someone new to Docker. There is plenty of documentation related to persistence on Docker and volumes on the Docker documentation itself.

Generally speaking, Mailu uses Docker volumes, and especially mounted Docker volumes, i.e. folders from the Docker host machine that are mapped inside containers. These folders must be created on the Docker host, which can be the client machine but not necessarily.

In your case, indeed, they must be created on the Docker server, not on your workstation accessing Docker remotely.
