### ISSUE TITLE
Bypassing anti-spoofing rejections

### ISSUE THREAD

**Issue by nestegg** [Mailu/Mailu#2954]
### Environment

- [X] docker compose
- [ ] kubernetes
- [ ] docker swarm

### Version

- Version: `2.0`

## Description

I recently finished upgrading from version 1.9 to 2.0 and discovered that the anti-spoofing behavior has become more aggressive.  I think in most cases this behavior is the correct behavior.  I have a situation where I have several hundred machines in a domain that send reports, alerts, etc using simple mailers that are not capable of dkim signing.  These messages all bounce now.  Is there a simple solutions for bypassing this behavior for specific domains?

**Comment by nextgens** [comment]
Yes but the better solution is to change the domain of those machines. All it takes is to update the DHCP.

Use a subdomain: ``internal.example.com``, ``corp.example.com`` ...

**Comment by nestegg** [comment]
Well DHCP isn't in play here and some are embedded devices, so it isn't that simple.  But I have considered it.  The machines already are generating mail with a domains of machinename.example.com and are being rejected.  Is there some other configuration I need to do?  I thought as long as example.com is handled by mailu it would be a problem?

**Comment by nextgens** [comment]
The easiest is to ensure one of the authentication methods passes (RELAYHOST, SPF, DKIM, ARC).

What about setting the appropriate SPF/TXT record (at least as seen from Mailu)?

What is the exact error message on the bounce? We have three different rules that may hit.

**Comment by nestegg** [comment]
```
 set pre-result to 'reject' (no score): 'Rejected (anti-spoofing: auth-failed)' from force_actions(0)
```

**Comment by nextgens** [comment]
Ok, thank you for confirming.

As I see it, the options are:
- Include those machines's IPs in ``RELAYNETS``: assuming you trust what they send, this is probably the easiest
- Tweak the TXT record of the domain to ensure their IPs are matched by SPF. If you do not want to do that globally you may be able to just change Mailu's view of that (by overriding what unbound returns for instance)
- Change the From domain those machines use.
- Override large portions of Mailu's config (for instance to disable anti-spoofing altogether)
