### ISSUE TITLE
mailu front crashed system is unresponsive

### ISSUE THREAD

**Issue by Spclaim** [Mailu/Mailu#2964]
### Environment

- [x] docker compose
- [ ] kubernetes
- [ ] docker swarm

### Version

- Version: `2.0`

## Description

Mailu server became unresponsive after 24h operating after upgrade to 2.0. Reboot was required since no ssh login possible. 

Front container apparently stopped working and produced no new logs until reboot.  Resolver container was unable to make new dns queries. 

## Replication Steps

Unable to replicate right now

## Observed behaviour

Exception in front container  and resolver container stops working.

## Expected behaviour

Just running. 

## Logs

docker logs front :

2023/10/04 15:38:22 [info] 11#11: *39948 proxied session done, client: xx.xxx.xxx.xxx server: 0.0.0.0:993, login: "xxxxx@xxxx.xxx", upstream: 192.168.203.7:143
Saving debug log to /var/log/letsencrypt/letsencrypt.log
An unexpected error occurred:
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='acme-v02.api.letsencrypt.org', port=443): Max retries exceeded with url: /directory (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f91ac3280>: Failed to establish a new connection: [Errno -3] Try again'))
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.
Saving debug log to /var/log/letsencrypt/letsencrypt.log
An unexpected error occurred:
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='acme-v02.api.letsencrypt.org', port=443): Max retries exceeded with url: /directory (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb643f280>: Failed to establish a new connection: [Errno -3] Try again'))
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.
Saving debug log to /var/log/letsencrypt/letsencrypt.log
An unexpected error occurred:
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='acme-v02.api.letsencrypt.org', port=443): Max retries exceeded with url: /directory (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb974f100>: Failed to establish a new connection: [Errno -3] Try again'))
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.
Saving debug log to /var/log/letsencrypt/letsencrypt.log
An unexpected error occurred:
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='acme-v02.api.letsencrypt.org', port=443): Max retries exceeded with url: /directory (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa48d3280>: Failed to establish a new connection: [Errno -3] Try again'))
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.
Saving debug log to /var/log/letsencrypt/letsencrypt.log
An unexpected error occurred:
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='acme-v02.api.letsencrypt.org', port=443): Max retries exceeded with url: /directory (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb66cf100>: Failed to establish a new connection: [Errno -3] Try again'))
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.
Saving debug log to /var/log/letsencrypt/letsencrypt.log
An unexpected error occurred:
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='acme-v02.api.letsencrypt.org', port=443): Max retries exceeded with url: /directory (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f840fae00>: Failed to establish a new connection: [Errno -3] Try again'))
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.
2023/10/07 13:17:37 [notice] 1#1: using the "epoll" event method

sudo journalctl showed this :

Okt 04 15:09:50 xxxxx mailu-antispam[2531041]: 2023-10-04 15:09:50 #153(controller) <5t8s4f>; map; http_map_error: error reading http://sa-update.surbl.org/rspamd/surbl-hashbl-map.inc(78.47.239.92:80)>
Okt 04 15:09:58 xxxxx mailu-antispam[2531041]: 2023-10-04 15:09:58 #151(rspamd_proxy) <nnw8jx>; map; rspamd_map_common_http_callback: need to reread cached map triggered by http://admin:8080/internal/>
Okt 04 15:09:58 xxxxx mailu-antispam[2531041]: 2023-10-04 15:09:58 #151(rspamd_proxy) <nnw8jx>; map; rspamd_map_read_cached: http://admin:8080/internal/rspamd/local_domains: read map data cached 33 by>
Okt 04 15:09:58 xxxxx mailu-antispam[2531041]: 2023-10-04 15:09:58 #151(rspamd_proxy) <nnw8jx>; map; rspamd_kv_list_fin: read hash of 3 elements from http://admin:8080/internal/rspamd/local_domains
Okt 04 15:10:12 xxxxx dockerd[2531041]: time="2023-10-04T15:10:12.083858044+02:00" level=error msg="[resolver] failed to query DNS server: 192.168.203.254:53, query: ;vR8LKWavPzMSp.fresh15.spameatingm>
Okt 04 15:10:13 xxxxx dockerd[2531041]: time="2023-10-04T15:10:13.087422419+02:00" level=error msg="[resolver] failed to query DNS server: 192.168.203.254:53, query: ;vR8LKWavPzMSp.fresh15.spameatingm>
Okt 04 15:10:14 xxxxx dockerd[2531041]: time="2023-10-04T15:10:14.091679474+02:00" level=error msg="[resolver] failed to query DNS server: 192.168.203.254:53, query: ;vR8LKWavPzMSp.fresh15.spameatingm>
Okt 04 15:10:15 xxxxx dockerd[2531041]: time="2023-10-04T15:10:15.095791659+02:00" level=error msg="[resolver] failed to query DNS server: 192.168.203.254:53, query: ;vR8LKWavPzMSp.fresh15.spameatingm>
Okt 04 15:10:18 xxxxx systemd[1]: run-docker-runtime\x2drunc-moby-2f870bc059b4f87a0a4aeb50e6b17c7bf4ddfc44788d2d848abe274036e64f6b-runc.ojCWau.mount: Succeeded.
Okt 04 15:10:18 xxxxx systemd[1]: run-docker-runtime\x2drunc-moby-8d5829c07c51482ea413efff685aad2b9cb61da9aa930016524ce497dff5e691-runc.a6O0IL.mount: Succeeded.
Okt 04 15:10:20 xxxxx systemd[1]: run-docker-runtime\x2drunc-moby-a8a8d49dedf8d9e9ba6e6541162bf60d2b694f1d1c9d7bcbc7f1c3ede22fdc5f-runc.vajps7.mount: Succeeded.
Okt 04 15:10:37 xxxxx kernel: [UFW BLOCK] IN=eth0 OUT= MAC=33:33:00:00:00:01:e0:28:6d:7e:b3:d5:86:dd SRC=fe80:0000:0000:0000:e228:6dff:fe7e:b3d5 DST=ff02:0000:0000:0000:0000:0000:0000:0001 LEN=60 TC=0>
Okt 04 15:10:37 xxxxx kernel: [UFW BLOCK] IN=eth0 OUT= MAC=33:33:00:00:00:01:e0:28:6d:7e:b3:d5:86:dd SRC=fe80:0000:0000:0000:e228:6dff:fe7e:b3d5 DST=ff02:0000:0000:0000:0000:0000:0000:0001 LEN=60 TC=0>
Okt 04 15:10:49 xxxxx systemd[1]: run-docker-runtime\x2drunc-moby-8d5829c07c51482ea413efff685aad2b9cb61da9aa930016524ce497dff5e691-runc.On6cmB.mount: Succeeded.
Okt 04 15:10:53 xxxxx mailu-antispam[2531041]: 2023-10-04 15:10:53 #153(controller) <nnw8jx>; map; rspamd_map_cache_cb: cached data is now expired (gen mismatch 129 != 130) for http://admin:8080/inter>
Okt 04 15:11:19 xxxxx systemd[1]: run-docker-runtime\x2drunc-moby-84d998a698c5c52855226bf4de518d64954a9e5559273fa7834a58dc2b6eb3d7-runc.FY9sD0.mount: Succeeded.
Okt 04 15:11:19 xxxxx systemd[1]: run-docker-runtime\x2drunc-moby-29455f4242ab5120a333e42658e880ec1baa26d7a5e0c9747b3fb6949206114e-runc.cRAdCG.mount: Succeeded.
Okt 04 15:11:53 xxxxx mailu-antispam[2531041]: 2023-10-04 15:11:53 #153(controller) <nnw8jx>; map; http_map_finish: need to reread map from http://admin:8080/internal/rspamd/local_domains
Okt 04 15:11:54 xxxxx systemd[1]: run-docker-runtime\x2drunc-moby-a8a8d49dedf8d9e9ba6e6541162bf60d2b694f1d1c9d7bcbc7f1c3ede22fdc5f-runc.bFm5rC.mount: Succeeded.
Okt 04 15:11:58 xxxxx mailu-antispam[2531041]: 2023-10-04 15:11:58 #153(controller) <nnw8jx>; map; http_map_finish: stored map data in a shared memory cache: /rhm.95fc8d9d6144e4eb700f
Okt 04 15:11:58 xxxxx mailu-antispam[2531041]: 2023-10-04 15:11:58 #153(controller) <nnw8jx>; map; http_map_finish: http://admin:8080/internal/rspamd/local_domains(192.168.203.4:8080): read map data 3>
Okt 04 15:11:58 xxxxx mailu-antispam[2531041]: 2023-10-04 15:11:58 #153(controller) <nnw8jx>; map; rspamd_map_save_http_cached_file: saved data from http://admin:8080/internal/rspamd/local_domains in >
Okt 04 15:11:58 xxxxx mailu-antispam[2531041]: 2023-10-04 15:11:58 #153(controller) <nnw8jx>; map; rspamd_kv_list_fin: read hash of 3 elements from http://admin:8080/internal/rspamd/local_domains
Okt 04 15:12:02 xxxxx mailu-antispam[2531041]: 2023-10-04 15:12:02 #151(rspamd_proxy) <nnw8jx>; map; rspamd_map_common_http_callback: need to reread cached map triggered by http://admin:8080/internal/>
Okt 04 15:12:02 xxxxx mailu-antispam[2531041]: 2023-10-04 15:12:02 #151(rspamd_proxy) <nnw8jx>; map; rspamd_map_read_cached: http://admin:8080/internal/rspamd/local_domains: read map data cached 33 by>
Okt 04 15:12:02 xxxxx mailu-antispam[2531041]: 2023-10-04 15:12:02 #151(rspamd_proxy) <nnw8jx>; map; rspamd_kv_list_fin: read hash of 3 elements from http://admin:8080/internal/rspamd/local_domains
Okt 04 15:12:19 xxxxx systemd[1]: run-docker-runtime\x2drunc-moby-11c6a33fcd80556dceacf2e282cf103b621bba8005686fed0b93053c344fff68-runc.gINB4G.mount: Succeeded.
Okt 04 15:12:19 xxxxx systemd[1]: run-docker-runtime\x2drunc-moby-29455f4242ab5120a333e42658e880ec1baa26d7a5e0c9747b3fb6949206114e-runc.KX4uqa.mount: Succeeded.
Okt 04 15:12:19 xxxxx systemd[1]: run-docker-runtime\x2drunc-moby-8d5829c07c51482ea413efff685aad2b9cb61da9aa930016524ce497dff5e691-runc.MwrqP5.mount: Succeeded.
Okt 04 15:12:42 xxxxx kernel: [UFW BLOCK] IN=eth0 OUT= MAC=33:33:00:00:00:01:e0:28:6d:7e:b3:d5:86:dd SRC=fe80:0000:0000:0000:e228:6dff:fe7e:b3d5 DST=ff02:0000:0000:0000:0000:0000:0000:0001 LEN=60 TC=0>
Okt 04 15:12:42 xxxxx kernel: [UFW BLOCK] IN=eth0 OUT= MAC=33:33:00:00:00:01:e0:28:6d:7e:b3:d5:86:dd SRC=fe80:0000:0000:0000:e228:6dff:fe7e:b3d5 DST=ff02:0000:0000:0000:0000:0000:0000:0001 LEN=60 TC=0>
Okt 04 15:13:19 xxxxx systemd[1]: run-docker-runtime\x2drunc-moby-c55567ee3e567f94f2661135ce738f94fe145cf1b5d206a2238c6c3eb1e2d747-runc.mDFBAs.mount: Succeeded.
Okt 04 15:13:20 xxxxx systemd[1]: run-docker-runtime\x2drunc-moby-8d5829c07c51482ea413efff685aad2b9cb61da9aa930016524ce497dff5e691-runc.aHy5hT.mount: Succeeded.
Okt 04 15:13:50 xxxxx systemd[1]: run-docker-runtime\x2drunc-moby-11c6a33fcd80556dceacf2e282cf103b621bba8005686fed0b93053c344fff68-runc.OLTfX4.mount: Succeeded.
Okt 04 15:14:08 xxxxx mailu-antispam[2531041]: 2023-10-04 15:14:08 #153(controller) <nnw8jx>; map; rspamd_map_cache_cb: cached data is now expired (gen mismatch 127 != 128) for http://admin:8080/inter>
Okt 04 15:14:47 xxxxx kernel: [UFW BLOCK] IN=eth0 OUT= MAC=33:33:00:00:00:01:e0:28:6d:7e:b3:d5:86:dd SRC=fe80:0000:0000:0000:e228:6dff:fe7e:b3d5 DST=ff02:0000:0000:0000:0000:0000:0000:0001 LEN=60 TC=0>
Okt 04 15:14:47 xxxxx kernel: [UFW BLOCK] IN=eth0 OUT= MAC=33:33:00:00:00:01:e0:28:6d:7e:b3:d5:86:dd SRC=fe80:0000:0000:0000:e228:6dff:fe7e:b3d5 DST=ff02:0000:0000:0000:0000:0000:0000:0001 LEN=60 TC=0>
Okt 04 15:14:50 xxxxx systemd[1]: run-docker-runtime\x2drunc-moby-c55567ee3e567f94f2661135ce738f94fe145cf1b5d206a2238c6c3eb1e2d747-runc.5ubIl5.mount: Succeeded.
Okt 04 15:15:19 xxxxx systemd[1]: run-docker-runtime\x2drunc-moby-2f870bc059b4f87a0a4aeb50e6b17c7bf4ddfc44788d2d848abe274036e64f6b-runc.igdQjE.mount: Succeeded.
Okt 04 15:15:20 xxxxx systemd[1]: run-docker-runtime\x2drunc-moby-11c6a33fcd80556dceacf2e282cf103b621bba8005686fed0b93053c344fff68-runc.15Ch1L.mount: Succeeded.
Okt 04 15:15:20 xxxxx systemd[1]: run-docker-runtime\x2drunc-moby-29455f4242ab5120a333e42658e880ec1baa26d7a5e0c9747b3fb6949206114e-runc.vSMFDt.mount: Succeeded.
Okt 04 15:15:20 xxxxx systemd[1]: run-docker-runtime\x2drunc-moby-8d5829c07c51482ea413efff685aad2b9cb61da9aa930016524ce497dff5e691-runc.hSLgyN.mount: Succeeded.
Okt 04 15:15:51 xxxxx systemd[1]: run-docker-runtime\x2drunc-moby-c55567ee3e567f94f2661135ce738f94fe145cf1b5d206a2238c6c3eb1e2d747-runc.NWPyVZ.mount: Succeeded.
Okt 04 15:16:03 xxxxx systemd[1]: run-docker-runtime\x2drunc-moby-a8a8d49dedf8d9e9ba6e6541162bf60d2b694f1d1c9d7bcbc7f1c3ede22fdc5f-runc.JbzTDd.mount: Succeeded.
Okt 04 15:16:21 xxxxx systemd[1]: run-docker-runtime\x2drunc-moby-84d998a698c5c52855226bf4de518d64954a9e5559273fa7834a58dc2b6eb3d7-runc.Rtgagy.mount: Succeeded.
Okt 04 15:16:21 xxxxx systemd[1]: run-docker-runtime\x2drunc-moby-8d5829c07c51482ea413efff685aad2b9cb61da9aa930016524ce497dff5e691-runc.T9pA05.mount: Succeeded.

**Comment by Diman0** [comment]
These logs indicate your machine had no internet access. The fact that you could not connect via SSH also indicates this. If this is a VM, you could try connecting to the console next time. If this is a rented VPS, then most VPS suppliers also provide a console.

Without a reproducible scenario there is not much to look into. Since the machine itself was not reachable I do not think it was something related to Mailu. Mailu runs within docker and is isolated from the host running docker. It should influence the host operating system.

**Comment by Spclaim** [comment]
The machine had internet access all the time as far as I can tell, I have other machines running from the same network and it didn't happen. 

I tried connecting to it via local network and it wasn't possible. All other machines are available just fine. 

Mailu prior to version 2.0 just ran fine over a year.

After last reboot it happened exactly 24 h later again. Apparently certbot /acme tries to revalidate every 24 hours ? 

It is a raspberry pi 4 8gb bare metal no vm in that linux with docker runs. 

Is there anything I can check additionally? I would love to help but unfortunately I have only little coding skills.


I extracted the letsencrypt logs:

`
2023-10-08 13:31:48,587:DEBUG:certbot._internal.main:certbot version: 1.32.0
2023-10-08 13:31:48,588:DEBUG:certbot._internal.main:Location of certbot entry point: /usr/bin/certbot
2023-10-08 13:31:48,588:DEBUG:certbot._internal.main:Arguments: ['-n', '--agree-tos', '-d', xxxxx.xxx.xxx', '--expand', '--allow-subset-of-names', '-m', 'xxxxxx@xxxx.xxx, '--standalone', '--cert-name', 'mailu', '--preferred-challenges', 'http', '--http-01-port', '8008', '--keep-until-expiring', '--allow-subset-of-names', '--renew-with-new-domains', '--config-dir', '/certs/letsencrypt', '--post-hook', '/config.py']
2023-10-08 13:31:48,589:DEBUG:certbot._internal.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)
2023-10-08 13:31:48,635:DEBUG:certbot._internal.log:Root logging level set at 30
2023-10-08 13:31:48,639:DEBUG:certbot._internal.plugins.selection:Requested authenticator standalone and installer None
2023-10-08 13:31:48,648:DEBUG:certbot._internal.plugins.selection:Single candidate plugin: * standalone
Description: Spin up a temporary webserver
Interfaces: Authenticator, Plugin
Entry point: standalone = certbot._internal.plugins.standalone:Authenticator
Initialized: <certbot._internal.plugins.standalone.Authenticator object at 0x7f86c8d390>
Prep: True
2023-10-08 13:31:48,649:DEBUG:certbot._internal.plugins.selection:Selected authenticator <certbot._internal.plugins.standalone.Authenticator object at 0x7f86c8d390> and installer None
2023-10-08 13:31:48,650:INFO:certbot._internal.plugins.selection:Plugins selected: Authenticator standalone, Installer None
2023-10-08 13:31:50,904:DEBUG:certbot._internal.main:Picked account: <Account(RegistrationResource(body=Registration(key=None, contact=(), agreement=None, status=None, terms_of_service_agreed=None, only_return_existing=None, external_account_binding=None), uri='https://acme-v02.api.letsencrypt.org/acme/acct/317201660', new_authzr_uri=None, terms_of_service=None), xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx, Meta(creation_dt=datetime.datetime(2021, 12, 11, 17, 31, 52, tzinfo=<UTC>), creation_host='xxxxxxxxxxxxxxxxxxxxxx', register_to_eff=None))>
2023-10-08 13:31:50,906:DEBUG:acme.client:Sending GET request to https://acme-v02.api.letsencrypt.org/directory.
2023-10-08 13:31:50,910:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): acme-v02.api.letsencrypt.org:443
2023-10-08 13:31:55,920:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3.10/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.10/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/usr/lib/python3.10/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f86c8f100>: Failed to establish a new connection: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='acme-v02.api.letsencrypt.org', port=443): Max retries exceeded with url: /directory (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f86c8f100>: Failed to establish a new connection: [Errno -3] Try again'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/certbot", line 33, in <module>
    sys.exit(load_entry_point('certbot==1.32.0', 'console_scripts', 'certbot')())
  File "/usr/lib/python3.10/site-packages/certbot/main.py", line 19, in main
    return internal_main.main(cli_args)
  File "/usr/lib/python3.10/site-packages/certbot/_internal/main.py", line 1744, in main
    return config.func(config, plugins)
  File "/usr/lib/python3.10/site-packages/certbot/_internal/main.py", line 1573, in certonly
    le_client = _init_le_client(config, auth, installer)
  File "/usr/lib/python3.10/site-packages/certbot/_internal/main.py", line 832, in _init_le_client
    return client.Client(config, acc, authenticator, installer, acme=acme)
  File "/usr/lib/python3.10/site-packages/certbot/_internal/client.py", line 311, in __init__
    acme = acme_from_config_key(config, self.account.key, self.account.regr)
  File "/usr/lib/python3.10/site-packages/certbot/_internal/client.py", line 76, in acme_from_config_key
    client = acme_client.BackwardsCompatibleClientV2(net, key, config.server)
  File "/usr/lib/python3.10/site-packages/acme/client.py", line 891, in __init__
    directory = messages.Directory.from_json(net.get(server).json())
  File "/usr/lib/python3.10/site-packages/acme/client.py", line 1256, in get
    self._send_request('GET', url, **kwargs), content_type=content_type)
  File "/usr/lib/python3.10/site-packages/acme/client.py", line 1194, in _send_request
    response = self.session.request(method, url, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.10/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='acme-v02.api.letsencrypt.org', port=443): Max retries exceeded with url: /directory (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f86c8f100>: Failed to establish a new connection: [Errno -3] Try again'))
2023-10-08 13:31:55,945:ERROR:certbot._internal.log:An unexpected error occurred:
2023-10-08 13:31:55,947:ERROR:certbot._internal.log:requests.exceptions.ConnectionError: HTTPSConnectionPool(host='acme-v02.api.letsencrypt.org', port=443): Max retries exceeded with url: /directory (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f86c8f100>: Failed to establish a new connection: [Errno -3] Try again'))`

**Comment by Diman0** [comment]
These logs state that the same issue occurred again. Certbot is unable to connect to 'acme-v02.api.letsencrypt.org'. This could mean many things:
- RPI had no internet access at that time.
- Something blocked the connection. That could be a firewall on the RPI or in your network or your ISP.
- RPI has no active network interface. Since you cannot SSH into the RPI this is the most logical option.

The fact that you cannot connect to the RPI during the incident, indicates something else is wrong on the RPI that also affects Mailu. As if the network interface is down on the RPI. Maybe you can get help on the RPI forum to troubleshoot this. I think the first step is to check the syslog. Something must be logged here when the RPI became unresponsive.

If you can SSH into the RPI when letsencrypt fails, and the same error occurs, then you can try accessing the url yourself using `curl https://acme-v02.api.letsencrypt.org`. This might provide more information. It makes sense to also try other URLs to confirm if any URL can be accessed at all.
If you notice that the RPI is unresponsive, instead of rebooting it you could attach a monitor and keyboard to it. This allows you to check the RPI when it is in the problematic state.
`ip addr`
with this command  you can check all network interfaces.
The interface with the IP address of the RPI should show the state UP
```
3: enp5s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether fc:34:97:a0:08:69 brd ff:ff:ff:ff:ff:ff
    inet 192.168.5.233/24 brd 192.168.2.255 scope global dynamic noprefixroute enp5s0
       valid_lft 83134sec preferred_lft 83134sec
    inet6 fe80::41f1:b38b:4775:314e/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
```
If you see `state DOWN` instead of `state UP` then the RPI has no active network connection.

**Comment by Spclaim** [comment]
thank you for your help. I attached monitor and keyboard and saw eth0 had no IP4 address assigned. 

After looking into journalctl -u dhcpcd i could see the message "route socked overflowed". Apparently docker  container are crashing the dhcpcd client due to too many requests. dhcpcd showed no further logs after that message and acquiring the ip lease. 


I am hopeful that this is the solution. But I'll have to wait 24 h .
