### ISSUE TITLE
Email service as a subscription service

### ISSUE THREAD

**Issue by vahidalvandi** [Mailu/Mailu#2965]
I want to offer the email service as a subscription service to my customers.
For example, one of my clients needs 5 accounts and each account needs a maximum of 1 gigabyte of space. Can Mailu provide me with this type of service?

**Comment by Diman0** [comment]
It is possible to set a maximum mailbox size for users.
I recommend to try out the [demo server](https://mailu.io/2.0/demo.html) and read the [documentation](https://mailu.io/2.0/webadministration.html#users).
