### ISSUE TITLE
"Too many attempts from your IP (rate-limit)" How to whitelist ip from host machine ?

### ISSUE THREAD

**Issue by hl037** [Mailu/Mailu#2968]
## Environment & Version

Docker-compose / linux / mailu 2.0

### Environment

- [x] docker compose
- [ ] kubernetes
- [ ] docker swarm

### Version

- Version: 2.0

## Description

I don't really know how, but I got my own IP banned from my own server (while I have never changed my password...). Since I can't connect to the admin, how can I unban the ip ?

This messages displays when I try to log in to the webadmin: "Too many attempts from your IP (rate-limit)"

**Comment by nextgens** [comment]
see https://github.com/Mailu/Mailu/issues/2856
