### ISSUE TITLE
Postfix start failed

### ISSUE THREAD

**Issue by LeeYanF** [Mailu/Mailu#2983]
Start postfix failed.Run postfix check get this error.
**find: /queue/public/outclean: Invalid argument**

**Comment by gegere** [comment]
The error message you're encountering suggests an issue with the `find` command in the Postfix mail server configuration. The error specifically mentions a problem with the `/queue/public/outclean` path, indicating that there may be an invalid argument in that context.

**Check Postfix Configuration:**
Ensure that your Postfix configuration is correct. You can use the following command to check the configuration:

`postfix check`

**Check Filesystem Permissions:**
Verify that the directories and files referenced in the Postfix configuration, especially `/queue/public/outclean`, have the correct permissions. The user running the Postfix process should have sufficient permissions to access and modify these files.

**Comment by ghostwheel42** [comment]
Please use the issue template. "Invalid argument" is probably some permission issue with the mapped volumes.
