### ISSUE TITLE
Alpine for base as well?

### ISSUE THREAD

**Issue by taoeffect** [Mailu/Mailu#299]
I saw this in the change log for 1.5:

> Global: most images moved to Alpine.

First, that's awesome, thank you so much for doing that! I've been looking all over the place for an email setup that uses Alpine images.

I'm wondering whether Mailu also works with alpine as the base operating system (as opposed to debian)? I notice that the [base server](https://github.com/Mailu/Mailu/wiki/Setup-a-base-server) docs primarily mention Debian. Has Mailu been tested using Alpine as the base? If so would it make sense to mention that in the docs too?

**Comment by kaiyou** [comment]
I have not tested with Alpine as the base server, but as long as you are able to run the proper version of Docker and Docker compose, and unless some SELinux or AppArmor configuration conflicts with Mailu access, I see no reason why it should not work.
