### ISSUE TITLE
Mailu & SIEM

### ISSUE THREAD

**Issue by SaiGonSeamus** [Mailu/Mailu#300]
We are currently looking at our options with regards to a new SIEM solution for our infrastructure. 

Has anyone got any advice on recommendations on a SIEM that works nicely with Mailu?

**Comment by kaiyou** [comment]
These are not proper SIEM on their own, but are a great start for bulding something consistent, so I have tested Mailu both with an ELK stack and Graylog, with pretty good success. I currently have email dashboards on Graylog, parsing mail domains, and using stateful parsing to match multiple logs with the same mail id when available.
