### ISSUE TITLE
Docs on stable branch not found

### ISSUE THREAD

**Issue by xtianus** [Mailu/Mailu#303]
The link in the docs
https://raw.githubusercontent.com/Mailu/Mailu/stable/docs/compose/docker-compose.yml.dist
results in a `404: Not Found`
I get the same error if I try to browse the stable branch on the github site.

**Comment by xtianus** [comment]
Further inspection reveals that the "docs" folder is missing on the stable branch.

**Comment by kaiyou** [comment]
You are right :) I'll change the documentation to match the branch currently displayed. Thank you for reporting!

**Comment by kaiyou** [comment]
Also, branching is rare enough that I am thinking about removing the `stable` tag: staying on a branch *is* indeed stable, and using the `stable` tag might not be so stable when a new branch is released.

**Comment by kaiyou** [comment]
Okay, so after some thinking and discussing with long time users, keeping a ``stable`` branch is indeed not quite useful for Mailu, so I will deprecate it starting with ``1.5``. Thus, I did update the documentation to provide a link depending on the version you are displaying.
