### ISSUE TITLE
docs/antispam.rst was not updated after a change of the including system

### ISSUE THREAD

**Issue by 0xErnie** [Mailu/Mailu#3036]
I had some trouble setting my very own deny- and allowlist for rspamd, using the documetation.
Found the reason after some digging: The documentation was not updated after a change:

https://github.com/Mailu/Mailu/commit/8861ce6edbd538eecc3c7c80570d66f52f9f9686

In https://github.com/mailu/mailu/blob/2.0/docs/antispam.rst#how-can-i-block-emails-from-a-domain
the line `map = "/etc/rspamd/override.d/blacklist.inc";`
has to be replaced by something like `map = "/overrides/blacklist.inc";` as mentioned in the change and the news article.

I may be submitting a pull request in the next days, fell free to fix this if I fail to do so.

**Comment by Diman0** [comment]
This has already been fixed on master: https://github.com/Mailu/Mailu/blob/master/docs/antispam.rst#how-can-i-block-emails-from-a-domain

To view the master version of documentation you can change the version from 2.0 to master in the version drop-down box in the bottom left on mailu.io. 
https://mailu.io/master/antispam.html#how-can-i-block-emails-from-a-domain

This was not backported to the 2.0 branch. Normally only critical/high severity bugs fixes are backported.
