### ISSUE TITLE
Reverse proxy documentation: PROXY_PROTOCOL setting is wrong

### ISSUE THREAD

**Issue by liquidat** [Mailu/Mailu#3052]
## Environment & Version

- `docker compose version`: v2.20.2
- Version: `2.0`

## Description

At least for me, Traefik v2 as a TCP reverse proxy to IMAP and SMTP only work when `PROXY_PROTOCOL` is set to `all`.
However, the [documentation](https://mailu.io/master/reverse.html) says `PROXY_PROTOCOL` has to be set to `all-but-http`.  But with that configuration, I am not able to make a successful connection.

## Replication Steps

1. Set up mailu with Traefik as reverse proxy according to the [documentation](https://mailu.io/master/reverse.html). In my case, certificates are provided via mailu certdumper
2. Ensure that TCP ports are also proxied, like port 993 is listened by Traefik, and imap is listening on 20993
3. Try to connect to imaps from the outside via `openssl s_client -crlf -connect firun.bayz.de:993`
4. Observe the error messages

## Observed behaviour

A connection is not possible, the SSL handshake fails.

## Expected behaviour

If I change the `PROXY_PROTOCOL` setting to `all`, the connection gets through.

## Logs

With `all-but-http` I get various errors:

client:
```
CONNECTED(00000003)
001E966D237F0000:error:0A000126:SSL routines:ssl3_read_n:unexpected eof while reading:ssl/record/rec_layer_s3.c:303:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 324 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
This TLS version forbids renegotiation.
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
---
```

Traefik:
```
traefik       | time="2023-11-14T00:40:54Z" level=debug msg="Handling TCP connection from 192.168.0.1:35256 to firun.bayz.de:20993"
traefik       | time="2023-11-14T00:40:54Z" level=debug msg="Dial with lookup to address firun.bayz.de:20993"
traefik       | time="2023-11-14T00:40:54Z" level=debug msg="Error while setting TCP connection deadline: set tcp 192.168.0.2:41770: use of closed network connection"
traefik       | time="2023-11-14T00:41:30Z" level=debug msg="Authentication failed" middlewareName=auth@file middlewareType=BasicAuth
```

front:
```
mailu-front-1  | 2023/11/14 00:40:54 [info] 13#13: *1 client 192.168.203.1:40236 connected to 0.0.0.0:993
mailu-front-1  | 2023/11/14 00:40:54 [info] 13#13: *1 SSL_do_handshake() failed (SSL: error:0A00010B:SSL routines::wrong version number) while SSL handshaking, client: 192.168.203.1, server: 0.0.0.0:993
```

IMAP/dovecot doesn't show any logs.

**Comment by nextgens** [comment]
You are following the instructions for master while running a different version of the software. Proxy protocol support has been improved in master.

**Comment by liquidat** [comment]
Ugh, you are right. Thanks for the clarification, I am sorry for the noise.
