### ISSUE TITLE
Emails reported as junk are always marked as read

### ISSUE THREAD

**Issue by Birkenstab** [Mailu/Mailu#3068]
## Environment & Version

- `k3s`
- Mailu Version: `2.0.28`

## Description
Emails moved to the junk folder are always marked as read, regardless of the "Enable marking spam mails as read" option in the admin panel. Even if I move an unread email in my email client to the junk folder it gets marked as read by Mailu.

## Replication Steps
* Disable the checkbox "Enable marking spam mails as read" in the admin panel
* Mark email as unread
* Move email to junk folder

## Observed behaviour
* Email is marked as read

## Expected behaviour
* Email should not be marked as read

## Possible solution
Remove the `setflag "\\seen";` in [report-spam.sieve](https://github.com/Mailu/Mailu/blob/master/core/dovecot/conf/report-spam.sieve#L4).
As far as I can tell if the "Enable marking spam mails as read" option is enabled, emails should still be marked as read by the [sieve script in admin](https://github.com/Mailu/Mailu/blob/master/core/admin/mailu/internal/templates/default.sieve#L25) when they get moved to the junk folder by the spam filter.

**Comment by Diman0** [comment]
https://github.com/Mailu/Mailu/blob/4b21beea25c17d0ee27548bab6abbad2857218ca/core/admin/mailu/internal/templates/default.sieve#L24
The toggle (enable/disable mark as read) is enabled here.

https://github.com/Mailu/Mailu/blob/4b21beea25c17d0ee27548bab6abbad2857218ca/core/dovecot/conf/report-spam.sieve#L4
This will mark any email moved to the Junk folder as read. Not sure if it is possible at all to make this conditional during runtime. I'm not familiar with sieve. Is it possible to poll admin from sieve to retrieve the current setting?

I think the solution is to modify spam.sieve to not always mark the email as read. I will test this.

**Comment by Diman0** [comment]
Yes. That resolves the bug. I will submit a PR
