### ISSUE TITLE
linux/amd64 docker images missing

### ISSUE THREAD

**Issue by Draxter** [Mailu/Mailu#3071]
**Issue**

The docker image builds in for example ghcr.io/mailu/radicale are missing the linux/amd64 architecture.

**Expected Behaviour**

One would expect the images to be present as they previously were, as linux/amd64 is one of the most popular architectures

**Logs**

`$ docker pull ghcr.io/mailu/radicale:latest`
```
latest: Pulling from mailu/radicale
no matching manifest for linux/amd64 in the manifest list entries
```

**Comment by nextgens** [comment]
We use the tags "master" and "2.0" ... are we referencing "latest" anywhere?

"master" has 3 archs: https://github.com/mailu/Mailu/pkgs/container/radicale/149084941?tag=master
