### ISSUE TITLE
Not running oletools soft rejects forever

### ISSUE THREAD

**Issue by nestegg** [Mailu/Mailu#3077]
## Environment & Version

- `docker compose version`
- Version: `2.0.34`

## Description

If you do not run oletools, messages with certain attachments soft reject.  I suspect issue #3056.  Shouldn't this take into account the value of SCAN_MACROS?

## Replication Steps

Generate a docker-compse setup with oletools disabled and use it.

## Observed behaviour

Messages with certain attachments are soft rejected.

## Expected behaviour

Messages should be accepted.

## Logs

```
mailu-antispam-1   | 2023-11-29 16:46:44 #161(rspamd_proxy) <1272b4>; proxy; rspamd_add_passthrough_result: <1476701da22e3$86133fe0$9239bfa0$@xxxxxx.com>: set pre-result to 'soft reject' (no score): 'Please retry later (anti-virus/oletools not ready)' from force_actions(0)
```

**Comment by nextgens** [comment]
Please provide the output of the following commands:
```
docker compose exec antispam head /etc/rspamd/local.d/external_services.conf
docker compose exec antispam head /etc/rspamd/local.d/ env |grep -E '(SCAN_MACROS|ANTIVIRUS)='
```

The rule you are hitting is defined in ``/etc/rspamd/local.d/force_actions.conf``... and it may be a clamav related problem.

**Comment by nestegg** [comment]
clamav is running.  I've dropped back to 2.0.32 as a work around.

```
antispam:/app# cat /etc/rspamd/local.d/external_services.conf
.include(try=true,priority=1,duplicate=merge) "/overrides/external_services.conf"

antispam:/app# env |grep -E '(SCAN_MACROS|ANTIVIRUS)='
ANTIVIRUS=clamav
SCAN_MACROS=false
```

**Comment by nextgens** [comment]
If this happens again, please provide the full logs so that we can see which rspamd rules have hit.
