### ISSUE TITLE
Managesieve broken and deprecated

### ISSUE THREAD

**Issue by kaiyou** [Mailu/Mailu#308]
Until version ``1.5``, a managesieve service was exposed by Mailu. This was removed for multiple reasons including:
- the protocol is cumbersome to proxify,
- there are almost no good client available anymore, except in webmails,
- we want to add a filtering interface to the admin UI, with more complete options.

In the process, we did not test enough the internal managesieve, with the webmails especially, and the authentication is currently broken.

**Comment by kaiyou** [comment]
The problem is: the authentication is now performed by ``nginx``, but it does not support managesieve. This is not a long term issue, but currently prevents from using the filtering interface in webmails.

After some thinking, I checked both Rainloop and Rouncube code, it seems that they enforce authentication before sieve can be accessed. My current reasoning would be: since the webmails enforce authentication before even try to access sieve, we could treat the webmail as the authentication endpoint for sieve.

Thus, we would disable authentication when the connection comes from the Webmail. Attack schemes include first attacking the webmail, then accessing sieve from there. But that would also mean getting all the emails of authenticated users, which is much (much) worse.

I am still trying to wrap my head around this, any input is welcome.

**Comment by mildred** [comment]
I'm trying to add again managesieve option to my setup. This is a requirement for me to use Mailu. If I understand well how nginx authentication works, nginx is asking the admin container for authentication and the admin interface answers with the host of the back end service.

But as far as I can see, dovecot still authenticates the incoming connections... Isn't it possible to have dovecot as frontend for managesieve ? It can do reverse proxy and authenticate against imap if needed...

**Comment by kaiyou** [comment]
Dovecot does not perform any authentication. Currently it trusts that authentication is done by the front container and basically rejects everything else.

So, to expose managesieve, you would need to proxy it through the front container, which I don't know how to perform, or you would need a separate authenticating container for managesieve. I guess you could create a separate Dovecot container with managesieve port exposed and the managesieve service enabled, and use local authentication against the sqlite database.

**Comment by nshaud** [comment]
As far as I understand, there is currently no way to manage Sieve filters in the Mailu admin panel, nor using external Sieve clients or in the internal webmails. I'd be satisfied with using Rainloop or Roundcube to manage the filters. Is there anything that we can expect in the near future on this matter ? Or is there any workaround for existing setups ?

**Comment by Diman0** [comment]
> As far as I understand, there is currently no way to manage Sieve filters in the Mailu admin panel, nor using external Sieve clients or in the internal webmails. I'd be satisfied with using Rainloop or Roundcube to manage the filters. Is there anything that we can expect in the near future on this matter ? Or is there any workaround for existing setups ?

You can edit sieve filters via the webmail (rainloop / roundcube). In the Mailu admin interface you can only set out of office and email forwarding.

**Comment by Diman0** [comment]
After discussing this issue during the last Mailu meeting. We decided to close PR#428.
- Our security model is that ALL communication goes via front. This PR circumvents this.
- TLS termination happens in the dovecot container. It must also check for SSL cert renewal. 
- Auth is not checked centrally like we have implemented for everything else.

The real option is waiting for that [nginx patch](https://trac.nginx.org/nginx/ticket/1697) for managesieve proxying to be merged. 
Once this is merged, we will revisit this topic. Anyone interested in this functionality, please ask via that [link](https://trac.nginx.org/nginx/ticket/1697) if the nginx team will merge it.

**Comment by Omrigan** [comment]
> The real option is waiting for that [nginx patch](https://forum.nginx.org/read.php?29,287586,292632#msg-292632) for managesieve proxying to be merged. You can also comment on the feature request on the [nginx site](https://trac.nginx.org/nginx/ticket/1697). Once this is merged, we will revisit this topic.
> 
> Anyone interested in this functionality, please ask via the links for the nginx team to implement it:
> 
>     * [nginx patch](https://forum.nginx.org/read.php?29,287586,292632#msg-292632)

Hi,

Email discussion with nginx guys mentions: 
 - "In the meantime we are using this for 18 months now, without issues" by Sander
 -  "I'd suggest to put the module somewhere on external repo for now, e.g. on github" by Maxim (I assume nginx dev)

So, since it takes that long for the patch to be merged, would it be possible to store the module out of nginx tree and use with mailu?
