### ISSUE TITLE
pop3 support

### ISSUE THREAD

**Issue by HorayNarea** [Mailu/Mailu#313]
nginx is not configured to handle pop3, but in docker-compose.yml the ports are proxied and dovecot is configured for pop3

is this a mistake or did you plan to not support pop3 anymore?

**Comment by kaiyou** [comment]
No, I would say that's a bad mistake. I will fix it by ``1.5.1`` :)

**Comment by curry684** [comment]
Had me stumped for half an hour debugging why the hell 110/995 were broken after upgrade to 1.5 hehe.

Shouldn't a "oops, broke half the system" issue like this make 1.5.1 a priority release and have other outstanding features move to 1.5.2 automatically?

**Comment by kaiyou** [comment]
It could have been indeed. Anyway, 1.5.1 was branched for testing and is building as we speak. I will merge it to 1.5 this week end.
