### ISSUE TITLE
Both Webmailers

### ISSUE THREAD

**Issue by HorayNarea** [Mailu/Mailu#314]
Is it possible to have both webmail-containers running at the same time?
Or would it be easier to just setup your own alternative Webmailers and connect them via smtp/imap?

**Comment by kaiyou** [comment]
It is not currently possible, and won't be until we setup something more flexible for managing containers. Currently the ``none`` container is a terrible hack that we still have to get around before allowing that kind of setup.

So indeed, setting both up would probably be simpler. Or you can fork the ``nginx`` container and tweak the configuration a bit.
