### ISSUE TITLE
Customize unbound configuration to enhance DNSSEC, DoT, unbound-control

### ISSUE THREAD

**Issue by cmonty14** [Mailu/Mailu#3149]
Hello,
I'm considering to migrate from Mail-in-a-Box to Mailu because it is a containerized deployment.
However I need to understand how to customize unbound configuration to enhance DNSSEC, DoT, unbound-control, etc.
This would result in an override of `/etc/unbound.conf` with
```
# The following line includes additional configuration files from the
# /etc/unbound/unbound.conf.d directory.
include-toplevel: "/etc/unbound/unbound.conf.d/*.conf"
```
There's a related issue [here](https://github.com/Mailu/Mailu/issues/2227).

Can you please advise how to proceed?
Or can you consider this as a feature request?

THX

**Comment by nextgens** [comment]
This is a dup of #2227
