### ISSUE TITLE
webmail (roundcube) wouldn't start when using override php file

### ISSUE THREAD

**Issue by darkclip** [Mailu/Mailu#3151]
## Environment & Version

- `docker compose version v2.24.2`
- Version: `2.0`

## Description
Put override file inside roundcube folder, when the file contains only necessary override configs.
for example `custom.inc.php`, mine was

```php
<?php
$config = array();
$config['max_message_size'] = '400M';
``` 
the webmail container wouldn't start and give out errors.

but if I copy the entire roundcube `config.inc.php` file content into that override file, the container seems working fine, but I didn't check thoroughly.
after some simple further tests, the minimal override config for the container to start is:

```php
<?php
$config = array();
$config['db_dsnw'] = 'sqlite:////data/roundcube.db';
$config['log_driver'] = 'stdout';
``` 
but it NOT working correctly with Mailu, the sso login page was gone, wouldn't able to login etc.

In fact this issue was reported before,   #2761 ,  and the reporter closed the issue without a solution.

## Replication Steps
put minimal override config php file inside `overrides/roundcube`, restart the container.

## Observed behaviour
webmail container wouldn't start, give out errors.

## Expected behaviour
container would run normally.

## Logs
```
webmail-1  | 2024/01/26 16:39:03 [error] 15#15: *2628 FastCGI sent in stderr: "PHP message: PHP Warning:  Array to string conversion in /var/www/roundcube/vendor/pear/crypt_gpg/Crypt/GPG/Engine.php on line 1669PHP message: PHP Warning:  Array to string conversion in /var/www/roundcube/vendor/pear/crypt_gpg/Crypt/GPG/Engine.php on line 1669PHP message: PHP Warning:  Array to string conversion in /var/www/roundcube/vendor/pear/crypt_gpg/Crypt/GPG/Engine.php on line 1669" while reading response header from upstream, client: X.X.X.X, server: , request: "GET /?_task=settings&_framed=1&_action=plugin.enigmakeys&_a=info&_id=2A8A5706B2A4B17B HTTP/1.1", upstream: "fastcgi://unix:/var/run/php8-fpm.sock:", host: "example.com", referrer: "https://example.com/webmail/?_task=settings&_action=plugin.enigmakeys"

webmail-1  | Initializing database
webmail-1  | PHP Fatal error:  [snuffleupagus][0.0.0.0][disabled_function][drop] Aborted execution on call of the function 'ini_set', because its argument '$option' content (error_log) matched a rule in /var/www/roundcube/program/lib/Roundcube/rcube_config.php on line 254
webmail-1  | Fatal error: Please check the Roundcube error log and/or server error logs for more information.
```

**Comment by DrDoug88** [comment]
I was trying to figure out how/where to edit the defaults and ran across this issue. Don't put `$config = array();` in your override, just put the setting you are trying to override. `$config = array();` allocates a new empty array, thus clearing out all of the preexisting settings.

Here's my custom,inc.php and it works fine:

```
<?php
$config['show_images'] = 3;
$config['timezone'] = 'America/Chicago';
?>
```

**Comment by darkclip** [comment]
@DrDoug88 Yes, you're right! the documentation on this part really is not so clear. closing this issue.
