### ISSUE TITLE
Feature Request: Use Configurable Domain Instead of Hardcoded 'example.org' in start.py

### ISSUE THREAD

**Issue by ShawkyZ** [Mailu/Mailu#3156]
## Issue Description
When initiating Mailu using Docker Compose in environments lacking internet access, the process fails. This issue is traced back to a specific line in [start.py](https://github.com/Mailu/Mailu/blob/master/core/admin/start.py#L53):

``
result = resolver.resolve('example.org', dns.rdatatype.A, dns.rdataclass.IN, lifetime=10)
``
This line attempts to resolve 'example.org', which is currently hardcoded.

## Suggested Enhancement
Instead of using the hardcoded 'example.org', the script could maybe use a the DOMAIN env variable mail.env file?

**Comment by nextgens** [comment]
Mailu is meant to help configure a useful, internet-connected mailserver; this is the tip of the iceberg.
