### ISSUE TITLE
Where to find the Dockerfile for the mailu/clamav image

### ISSUE THREAD

**Issue by arno4000** [Mailu/Mailu#3160]
Where can I find the Dockerfile for the mailu/clamav image https://github.com/Mailu/Mailu/pkgs/container/clamav

**Comment by nextgens** [comment]
On the 1.9 branch https://github.com/Mailu/Mailu/tree/1.9/optional/clamav. That image is not supported any-more, we use upstream's version now.

If you do use Mailu, re-run setup.
