### ISSUE TITLE
integration with google, google can't send mailu invites

### ISSUE THREAD

**Issue by migs35323** [Mailu/Mailu#3168]
### Version

- Version: `2.0.30`

## Description

this is a continuation of (i can't re-open it):
https://github.com/Mailu/Mailu/issues/2795

basically: 
Some workers created a google account using their work email addresses to use with google calendars and meets.
I'd like to enable mailu to allow google calendar emails

I see the email is being rejected in RSPAMD 

I am not sure if this is a matter of setting dns records or i can configure rspamd to allow google calendar emails

![rspamd](https://github.com/Mailu/Mailu/assets/92784574/ae67fb8a-bc60-4549-92f2-e2c7d1083d91)

**Comment by nextgens** [comment]
You need to configure google so that it passes DMARC.

Follow the instructions at https://support.google.com/a/answer/174124?hl=en to configure DKIM for your domain and it will fix it.
