### ISSUE TITLE
ISRG_X1 not included in fullchain.pem (--> DANE validation failed)

### ISSUE THREAD

**Issue by job-so** [Mailu/Mailu#3187]
Hi folks,
and thanks for this great software.
_Job-so._

## Environment & Version

- docker-compose
- Mailu Version: `2.0`

## Description

- Same issue as #2138
- As ISRG_X1 is not present in /certs/letsencrypt/live/mailu-ecdsa/fullchain.pem, DANE validation failed when TLSA DNS record is `2 1 1 0b9fa5a59eed715c26c1020c711b4f6ec42d58b0015e14337a39dad301c5afc3`

## Replication Steps

```
$ echo | openssl s_client -connect test.mailu.io:25 -starttls smtp -showcerts
CONNECTED(00000003)
depth=2 C = US, O = Internet Security Research Group, CN = ISRG Root X1
verify return:1
depth=1 C = US, O = Let's Encrypt, CN = R3
verify return:1
depth=0 CN = mailu.io
verify return:1
---
Certificate chain
 0 s:CN = mailu.io
   i:C = US, O = Let's Encrypt, CN = R3
   a:PKEY: rsaEncryption, 4096 (bit); sigalg: RSA-SHA256
   v:NotBefore: Feb 19 12:43:20 2024 GMT; NotAfter: May 19 12:43:19 2024 GMT
-----BEGIN CERTIFICATE-----
MIIF/DCCBOSgAwIBAgISA/rJ9CbQM3HoUjwXuZKxe47TMA0GCSqGSIb3DQEBCwUA
MDIxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQD
EwJSMzAeFw0yNDAyMTkxMjQzMjBaFw0yNDA1MTkxMjQzMTlaMBMxETAPBgNVBAMT
CG1haWx1LmlvMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA4XEW8iHD
8G3Uj6vB2j5/VgH3PVlAI4vy2a89HBoq48SvTWahxjLDrtQr2fx0eh2AeiZJ1umM
4ezVy1KuN6mPrYOPgFb7PkpYedoezfBSo2IhcKxSUxB11BM8Y2BzU9P+HnMXgtXz
odKWwfLVPlMdLFjUuN9f5ycW7x/poHB5Jqxr0hfMD1uyhFidsfV/hTR8Vee6sdEt
TdOcOt2EFQjuVL2031eRrErZmCvTaDvm1ghPNhBz2Ej0F22xc7RPhx0cXAyQjxcr
nsX44G5/eu8C4bOwpMbL7JIFam4WKcMcZj0TinKLHKJLXYXzC3rQPuRhq6enqNQq
U1449pPjWi6bzcGgSE9Hy31ua7szSXvM0wPQ8wmF3G6w2eOfFixW1OlgHpeMHUYX
D8EypFkoXZnmQYcQSQDcFtuCF4sM7Hg1WXmViGKwBfs3VnebQOhIokoG8UYyIKHU
zsL4tpyvU5wmtdLOheaOUIa/Fn/zoXUei1jRxgZ4HZV0Db+6cNLBj6mgwUSmn5sF
YKLMkCAI+h5r4Zq3xa9j58xX8D1Aan1tMvcYOw9/6HtwLpsAnAOTXa8vbsKTApW0
14iIpaiKiSPBnmpVYv5rnwYE8tz7A8jK1okU7s3AKpPxeTdkhMGoTvl7faXUb9+5
sVodR5AAawFUivNrk89jEYiawf9V+mCZGcUCAwEAAaOCAikwggIlMA4GA1UdDwEB
/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/
BAIwADAdBgNVHQ4EFgQU2ueOB46OgwMwhYgrQ+skLTQIxI0wHwYDVR0jBBgwFoAU
FC6zF7dYVsuuUAlA5h+vnYsUwsYwVQYIKwYBBQUHAQEESTBHMCEGCCsGAQUFBzAB
hhVodHRwOi8vcjMuby5sZW5jci5vcmcwIgYIKwYBBQUHMAKGFmh0dHA6Ly9yMy5p
LmxlbmNyLm9yZy8wMgYDVR0RBCswKYIIbWFpbHUuaW+CDnNldHVwLm1haWx1Lmlv
gg10ZXN0Lm1haWx1LmlvMBMGA1UdIAQMMAowCAYGZ4EMAQIBMIIBBAYKKwYBBAHW
eQIEAgSB9QSB8gDwAHYASLDja9qmRzQP5WoC+p0w6xxSActW3SyB2bu/qznYhHMA
AAGNwZtckQAABAMARzBFAiEAhA0n43Pk/VqxL9XKF3Vob1bExuyBm4HORBPIeV9y
SNwCIDOe93jpDgUPOUFIs4wHUxFPOLzDxp+Ihlc6Zrk8YwroAHYAouK/1h7eLy8H
oNZObTen3GVDsMa1LqLat4r4mm31F9gAAAGNwZtclAAABAMARzBFAiEAqp62nMR4
9lcdOfQYKyPuehqX9uYLRD0rjf39okQSdmsCICs7IB+sCMgsRVlMASg2d2XiC7Q4
3acid1F68YDn71UWMA0GCSqGSIb3DQEBCwUAA4IBAQBgZrlx36RaEXBf/MynUR9Z
Viaxd0OYznENBjdVJh44i3YAHESaySs40j39NpK3DsN0yiB7fLBkuyflu23hxdjf
grRleBdg47jZPzv8ElM9yY/cAHrQje4PM4+LNC7zz0G9KaBPg5ze+kxMqmxLA6fW
yRc9niOzm0xmsRyK4Lyt2xYhEIodNESiMZiVjUnIfMeZeDtwOsDt5XKWddmsng/n
xGImgilsxeyJQ8FFG2yUKka3H3+wic5RAsI6eFJHZwN1aA5o9qen4doMWbOyx8f9
c19qos53h0aM+LfBdF85G+sdlSkZMqSySsBva+JfzDjzzJv77uKCs9QK2owVtNjc
-----END CERTIFICATE-----
 1 s:C = US, O = Let's Encrypt, CN = R3
   i:C = US, O = Internet Security Research Group, CN = ISRG Root X1
   a:PKEY: rsaEncryption, 2048 (bit); sigalg: RSA-SHA256
   v:NotBefore: Sep  4 00:00:00 2020 GMT; NotAfter: Sep 15 16:00:00 2025 GMT
-----BEGIN CERTIFICATE-----
MIIFFjCCAv6gAwIBAgIRAJErCErPDBinU/bWLiWnX1owDQYJKoZIhvcNAQELBQAw
TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwHhcNMjAwOTA0MDAwMDAw
WhcNMjUwOTE1MTYwMDAwWjAyMQswCQYDVQQGEwJVUzEWMBQGA1UEChMNTGV0J3Mg
RW5jcnlwdDELMAkGA1UEAxMCUjMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
AoIBAQC7AhUozPaglNMPEuyNVZLD+ILxmaZ6QoinXSaqtSu5xUyxr45r+XXIo9cP
R5QUVTVXjJ6oojkZ9YI8QqlObvU7wy7bjcCwXPNZOOftz2nwWgsbvsCUJCWH+jdx
sxPnHKzhm+/b5DtFUkWWqcFTzjTIUu61ru2P3mBw4qVUq7ZtDpelQDRrK9O8Zutm
NHz6a4uPVymZ+DAXXbpyb/uBxa3Shlg9F8fnCbvxK/eG3MHacV3URuPMrSXBiLxg
Z3Vms/EY96Jc5lP/Ooi2R6X/ExjqmAl3P51T+c8B5fWmcBcUr2Ok/5mzk53cU6cG
/kiFHaFpriV1uxPMUgP17VGhi9sVAgMBAAGjggEIMIIBBDAOBgNVHQ8BAf8EBAMC
AYYwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMBMBIGA1UdEwEB/wQIMAYB
Af8CAQAwHQYDVR0OBBYEFBQusxe3WFbLrlAJQOYfr52LFMLGMB8GA1UdIwQYMBaA
FHm0WeZ7tuXkAXOACIjIGlj26ZtuMDIGCCsGAQUFBwEBBCYwJDAiBggrBgEFBQcw
AoYWaHR0cDovL3gxLmkubGVuY3Iub3JnLzAnBgNVHR8EIDAeMBygGqAYhhZodHRw
Oi8veDEuYy5sZW5jci5vcmcvMCIGA1UdIAQbMBkwCAYGZ4EMAQIBMA0GCysGAQQB
gt8TAQEBMA0GCSqGSIb3DQEBCwUAA4ICAQCFyk5HPqP3hUSFvNVneLKYY611TR6W
PTNlclQtgaDqw+34IL9fzLdwALduO/ZelN7kIJ+m74uyA+eitRY8kc607TkC53wl
ikfmZW4/RvTZ8M6UK+5UzhK8jCdLuMGYL6KvzXGRSgi3yLgjewQtCPkIVz6D2QQz
CkcheAmCJ8MqyJu5zlzyZMjAvnnAT45tRAxekrsu94sQ4egdRCnbWSDtY7kh+BIm
lJNXoB1lBMEKIq4QDUOXoRgffuDghje1WrG9ML+Hbisq/yFOGwXD9RiX8F6sw6W4
avAuvDszue5L3sz85K+EC4Y/wFVDNvZo4TYXao6Z0f+lQKc0t8DQYzk1OXVu8rp2
yJMC6alLbBfODALZvYH7n7do1AZls4I9d1P4jnkDrQoxB3UqQ9hVl3LEKQ73xF1O
yK5GhDDX8oVfGKF5u+decIsH4YaTw7mP3GFxJSqv3+0lUFJoi5Lc5da149p90Ids
hCExroL1+7mryIkXPeFM5TgO9r0rvZaBFOvV2z0gp35Z0+L4WPlbuEjN/lxPFin+
HlUjr8gRsI3qfJOQFy/9rKIJR0Y/8Omwt/8oTWgy1mdeHmmjk7j1nYsvC9JSQ6Zv
MldlTTKB3zhThV1+XWYp6rjd5JW1zbVWEkLNxE7GJThEUG3szgBVGP7pSWTUTsqX
nLRbwHOoq7hHwg==
-----END CERTIFICATE-----
---
Server certificate
subject=CN = mailu.io
issuer=C = US, O = Let's Encrypt, CN = R3
---
No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: RSA-PSS
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 3837 bytes and written 428 bytes
Verification: OK
---
New, TLSv1.3, Cipher is TLS_AES_256_GCM_SHA384
Server public key is 4096 bit
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
---
250 STARTTLS
DONE
```

## Observed behaviour

Only 2 certificates are returned : 
1. CN = mailu.io
2. C = US, O = Let's Encrypt, CN = R3

## Expected behaviour

Expect the full chain, including root (3 certificates)
1. CN = mailu.io
2. C = US, O = Let's Encrypt, CN = R3
3. C = US, O = Internet Security Research Group, CN = ISRG Root X1

## Suggestion ?

- https://github.com/Mailu/Mailu/commit/0816cb9497f31ca4ee71aebdee97b87e71870cc8 removed `add_DANE_pin` function, maybe should we restore this function ?
- BTW `/certs/letsencrypt/live/mailu/nginx-chain.pem` seems to not be used anywhere ? , at least nginx.conf refers to `fullchain`, not `nginx-chain` files

**Comment by nextgens** [comment]
Yes, that was working and for some reason it's now broken... I think certbot has changed what they store in fullchain.pem.

**Comment by nextgens** [comment]
@job-so try the following and report back please; it should fix it.

```
export MAILU_VERSION=mergify/bp/2.0/pr-3188
docker compose up -d
```

**Comment by job-so** [comment]
@nextgens thks, it works well for me.

may I suggest to use the cross-signed certificate for X2 (instead of the auto-signed one) to be sure that the X1 digest (DNS TLSA record) matchs for each cases.

-----BEGIN CERTIFICATE-----
MIIEYDCCAkigAwIBAgIQB55JKIY3b9QISMI/xjHkYzANBgkqhkiG9w0BAQsFADBP
MQswCQYDVQQGEwJVUzEpMCcGA1UEChMgSW50ZXJuZXQgU2VjdXJpdHkgUmVzZWFy
Y2ggR3JvdXAxFTATBgNVBAMTDElTUkcgUm9vdCBYMTAeFw0yMDA5MDQwMDAwMDBa
Fw0yNTA5MTUxNjAwMDBaME8xCzAJBgNVBAYTAlVTMSkwJwYDVQQKEyBJbnRlcm5l
dCBTZWN1cml0eSBSZXNlYXJjaCBHcm91cDEVMBMGA1UEAxMMSVNSRyBSb290IFgy
MHYwEAYHKoZIzj0CAQYFK4EEACIDYgAEzZvVn4CDCuwJSvMWSj5cz3es3mcFDR0H
ttwW+1qLFNvicWDEukWVEYmO6gbf9yoWHKS5xcUy4APgHoIYOIvXRdgKam7mAHf7
AlF9ItgKbppbd9/w+kHsOdx1ymgHDB/qo4HlMIHiMA4GA1UdDwEB/wQEAwIBBjAP
BgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBR8Qpau3ktIO/qS+J6Mz22LqXI3lTAf
BgNVHSMEGDAWgBR5tFnme7bl5AFzgAiIyBpY9umbbjAyBggrBgEFBQcBAQQmMCQw
IgYIKwYBBQUHMAKGFmh0dHA6Ly94MS5pLmxlbmNyLm9yZy8wJwYDVR0fBCAwHjAc
oBqgGIYWaHR0cDovL3gxLmMubGVuY3Iub3JnLzAiBgNVHSAEGzAZMAgGBmeBDAEC
ATANBgsrBgEEAYLfEwEBATANBgkqhkiG9w0BAQsFAAOCAgEAG38lK5B6CHYAdxjh
wy6KNkxBfr8XS+Mw11sMfpyWmG97sGjAJETM4vL80erb0p8B+RdNDJ1V/aWtbdIv
P0tywC6uc8clFlfCPhWt4DHRCoSEbGJ4QjEiRhrtekC/lxaBRHfKbHtdIVwH8hGR
Ib/hL8Lvbv0FIOS093nzLbs3KvDGsaysUfUfs1oeZs5YBxg4f3GpPIO617yCnpp2
D56wKf3L84kHSBv+q5MuFCENX6+Ot1SrXQ7UW0xx0JLqPaM2m3wf4DtVudhTU8yD
ZrtK3IEGABiL9LPXSLETQbnEtp7PLHeOQiALgH6fxatI27xvBI1sRikCDXCKHfES
c7ZGJEKeKhcY46zHmMJyzG0tdm3dLCsmlqXPIQgb5dovy++fc5Ou+DZfR4+XKM6r
4pgmmIv97igyIintTJUJxCD6B+GGLET2gUfA5GIy7R3YPEiIlsNekbave1mk7uOG
nMeIWMooKmZVm4WAuR3YQCvJHBM8qevemcIWQPb1pK4qJWxSuscETLQyu/w4XKAM
YXtX7HdOUM+vBqIPN4zhDtLTLxq9nHE+zOH40aijvQT2GcD5hq/1DhqqlWvvykdx
S2McTZbbVSMKnQ+BdaDmQPVkRgNuzvpqfQbspDQGdNpT2Lm4xiN9qfgqLaSCpi4t
EcrmzTFYeYXmchynn9NM0GbQp7s=
-----END CERTIFICATE-----

**Comment by nextgens** [comment]
I've considered it and decided against it: the cross signed version is only valid up to September next year.

IMHO it's much better to just add another TLSA record for X2 (that's what I do on my domain)

**Comment by nextgens** [comment]
> @nextgens thks, it works well for me.

Thank you for confirming, 2.0.39 is now out with the fix
