### ISSUE TITLE
Consider adding a code of conduct

### ISSUE THREAD

**Issue by HorayNarea** [Mailu/Mailu#319]
see https://help.github.com/articles/adding-a-code-of-conduct-to-your-project/

currently it doesn't seem necessary but better safe than sorry and it's nice to have some kind of "social guideline" when the community grows :)

**Comment by kaiyou** [comment]
I setup a very basic code of conduct, feel free to comment on it if you find something is irrelevant. I also added a ``CONTRIBUTING.md`` pointing to the proper documentation topics.
