### ISSUE TITLE
Move the DKIM keys to redis or a map

### ISSUE THREAD

**Issue by kaiyou** [Mailu/Mailu#320]
Rspamd supports storing the DKIM keys in redis or in a map, this will avoid sharing a volume between the admin container and the antispam container.

Overall design for redis : 

- keys are stored in database,
- during startup, a manage function pushes the keys to redis,
- upon change, keys are pushed to redis.

A migration script would need to parse the keys before the folder is removed. This will have to be handled before migrating to ``1.6``, so maybe publish the migration to the ``1.5`` branch beforehand.

Overall design for a map:

- keys are stored in database,
- an HTTP api is created for rspamd to access the keys,
- a map is configured and used by the DKIM signing module.

Currently I am leaning toward the map solution, as it is more generic and could be used for other purposes. We still would need to handle authentication aspects.

**Comment by HorayNarea** [comment]
If the keys are stored in redis, is it possible to force a dump to disk of the DB? Just to be safe.

**Comment by kaiyou** [comment]
It would be of course, but I would prefer that we do not rely on Redis for persistance :) instead, having them stored in the main database is well sounds good to me. Do you see any scenario where that would not be sufficient?
