### ISSUE TITLE
 Files infected with viruses - Warning

### ISSUE THREAD

**Issue by riyadhali** [Mailu/Mailu#3210]
Hello. When I downloaded the files to Windows and extracted them, the antivirus showed a warning for spyware files:
Among the infected files are eicar.com.txt and PotentiallyUnwanted!
![Files infected with viruses - Warning](https://github.com/Mailu/Mailu/assets/14304601/8cfa7a07-2071-41a1-83b3-08d7c660288f)

**Comment by Diman0** [comment]
https://en.wikipedia.org/wiki/EICAR_test_file
These are test files to test the response of  virus scanners. If your virus scanner did not find these files, then it is not a  proper virus scanner. We use these to test if clamav and oletools can successfully scan and report these files during CI/CD.
