### ISSUE TITLE
ERR_TO_MANY_REDIRECTS on /webmail

### ISSUE THREAD

**Issue by Denialll** [Mailu/Mailu#3217]
Hello,
I use microk8s. I did it according to this documentation: (https://github.com/Mailu/helm-charts/blob/master/mailu/README.md(
The admin panel works, everything is fine, but as soon as I want to go to email, I immediately get ERR_TO_MANY_REDIRECTS:

`"GET /webmail/ HTTP/1.1" 302 5 "https://mail.example.com/admin/webui_antispam" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"
Apr 03 11:12:20 imap-login: Info: Disconnected: Connection closed (auth failed, 1 attempts in 2 secs): user=<admin@example.com>, method=PLAIN, rip=10.1.158.123, rport=46186, lip=10.1.158.128, lport=10143, TLS
`

`
"GET /webmail/sso.php HTTP/1.1" 302 5 "https://mail.example.com/admin/webui_antispam" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"
Apr 03 11:12:23 imap-login: Info: Disconnected: Connection closed (auth failed, 1 attempts in 2 secs): user=<admin@examplecom>, method=PLAIN, rip=10.1.158.123, rport=46202, lip=10.1.158.128, lport=10143, TLS
`

`
"GET /webmail/sso.php HTTP/1.1" 302 5 "https://mail.example.com/admin/webui_antispam" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"
Apr 03 11:12:26 imap-login: Info: Disconnected: Connection closed (auth failed, 1 attempts in 2 secs): user=<admin@example.com>, method=PLAIN, rip=10.1.158.123, rport=46212, lip=10.1.158.128, lport=10143, TLS
`

`
"GET /webmail/sso.php HTTP/1.1" 302 5 "https://mail.example.com/admin/webui_antispam" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"
Apr 03 11:12:29 imap-login: Info: Disconnected: Connection closed (auth failed, 1 attempts in 2 secs): user=<admin@example.com>, method=PLAIN, rip=10.1.158.123, rport=54856, lip=10.1.158.128, lport=10143, TLS
`

`
"GET /webmail/sso.php HTTP/1.1" 302 5 "https://mail.example.com/admin/webui_antispam" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"
Apr 03 11:12:32 imap-login: Info: Disconnected: Connection closed (auth failed, 1 attempts in 2 secs): user=<admin@example.com>, method=PLAIN, rip=10.1.158.123, rport=54872, lip=10.1.158.128, lport=10143, TLS
`

**Comment by nextgens** [comment]
Ignore the template...
