### ISSUE TITLE
pre-defined dhparam

### ISSUE THREAD

**Issue by HorayNarea** [Mailu/Mailu#322]
[Mozilla and the IETF recommend](https://wiki.mozilla.org/Security/Server_Side_TLS#Pre-defined_DHE_groups) using pre-defined dhparam because it could be safer and is faster.

I don't know very much about crypto but if Mozilla/IETF say it's ok, I think Mailu can have an Option to choose these pre-defined dhparam instead of generating them on first run?

**Comment by kaiyou** [comment]
You are right, we should simply use the predefined groups recommended by the IETF instead of generated new ones. I would basically remove the generation part.

**Comment by HorayNarea** [comment]
I'm fine with that

**Comment by gregf** [comment]
When you say remove the generation part do you mean to have the user fetch or generate the cert by hand before `docker-compose up -d` or do you mean you are just going to fetch ffdhe4096 for the user?

**Comment by kaiyou** [comment]
We are just going to embed it inside the container.

**Comment by kaiyou** [comment]
This was merged.
