### ISSUE TITLE
ERROR: cannot start service front: driver failed programming external connectivity on endpoint mailu_front_1

### ISSUE THREAD

**Issue by DmitriyRyazanovsky** [Mailu/Mailu#3222]
Docker compose link: https://setup.mailu.io/2.0/file/61da9b61-d658-44dc-bcca-1933624979a9/docker-compose.yml

mailu link: https://setup.mailu.io/2.0/file/61da9b61-d658-44dc-bcca-1933624979a9/mailu.env

Error trace:
root@cv3704261:/mailu# docker-compose -p mailu up -d
mailu_resolver_1 is up-to-date
mailu_webdav_1 is up-to-date
Starting mailu_front_1 ... 
mailu_oletools_1 is up-to-date
mailu_redis_1 is up-to-date
mailu_antivirus_1 is up-to-date
mailu_admin_1 is up-to-date
Starting mailu_front_1 ... error
ERROR: for mailu_front_1  Cannot start service front: driver failed programming external connectivity on endpoint mailu_front_1 (c35381b69eaea6d708fb86d0950620dcda9941372671616f896e6ab1a86fdc74): Error starting userland proxy: listen tcp4 89.111.170.180:995: bind: cannot assign requested address
ERROR: for front  Cannot start service front: driver failed programming external connectivity on endpoint mailu_front_1 (c35381b69eaea6d708fb86d0950620dcda9941372671616f896e6ab1a86fdc74): Error starting userland proxy: listen tcp4 89.111.170.180:995: bind: cannot assign requested address
ERROR: Encountered errors while bringing up the project.

The server is completely clean, please tell me what to do! :(

**Comment by nextgens** [comment]
Disable the userland proxy.

in your ``/etc/docker/daemon.json``:
```
{
    "userland-proxy": false
}
```

Then:
```
sudo systemctl restart docker
docker compose up -d
```

You may also want to ensure you have nothing else listening on port 995

**Comment by DmitriyRyazanovsky** [comment]
> Disable the userland proxy.
> 
> in your `/etc/docker/daemon.json`:
> 
> ```
> {
>     "userland-proxy": false
> }
> ```
> 
> Then:
> 
> ```
> sudo systemctl restart docker
> docker compose up -d
> ```
> 
> You may also want to ensure you have nothing else listening on port 995

I did what you said, but apparently the error remained the same (although the error form now looks different)
Can you please help?

Error trace:
Creating mailu_front_1     ... error
WARNING: Host is already in use by another container
Creating mailu_oletools_1  ... done
Creating mailu_redis_1     ... done
56a165c7fdde77e3f6633617eec6c2e5b): listen tcp4 89.111.170.180:995: bind: cannotCreating mailu_antivirus_1 ... done
Creating mailu_admin_1     ... done

ERROR: for front  Cannot start service front: driver failed programming external connectivity on endpoint mailu_front_1 (bb94cef90bc4efeeb02f23256d48d1456a165c7fdde77e3f6633617eec6c2e5b): listen tcp4 89.111.170.180:995: bind: cannot assign requested address
