### ISSUE TITLE
The postgresql database cannot be configured for roundcube

### ISSUE THREAD

**Issue by liuhr-ncu** [Mailu/Mailu#3224]
## Environment & Version

- Docker Compose version: `v2.25.0`
- Version: `2.0`

## Description
I want to configure the postgresql database for roundcube. The mailu.env configuration is as follows:
```
SQLALCHEMY_DATABASE_URI_ROUNDCUBE=postgresql://mailu:123456@192.168.1.1:5432/roundcube
```
when I exec ` docker compose stop && docker compose up -d` and `docker compose logs webmail -f`, the following error occurs:
```
webmail-1  | Initializing database
webmail-1  | ERROR: Configuration error. Unsupported database driver: postgresql
```

**Comment by StephenSorriaux** [comment]
In your URI, you need to replace `postgresql://`with `pgsql://` (as per the Roundcube doc).
