### ISSUE TITLE
After disable email account, it still receive emails during the disable period

### ISSUE THREAD

**Issue by liuhr-ncu** [Mailu/Mailu#3231]
## Environment & Version

- Docker Compose version: `v2.25.0`
- Version: `2.0`

## Description

After disable email account, it still receive emails during the disable period, How can I configure not to receive mail during the disabled period

**Comment by nextgens** [comment]
That's a feature and not a bug.

The easiest is probably to use the [relocated(5)](https://www.postfix.org/relocated.5.html) feature of postfix with an override.
