### ISSUE TITLE
Statistics per container

### ISSUE THREAD

**Issue by HorayNarea** [Mailu/Mailu#327]
If I understand it correctly, only the admin-container can advertise to the DNS-tracking service, how about adding this feature to every container and getting an overview which (optional) services are really used?

Of course, this would mean adding a 3rd subdomain for the service-name

**Comment by kaiyou** [comment]
Currently, I do not see the need for this. The goal of the statistics service is not to have an idea of how many people are using Mailu or which service, but a general idea of when it is okay to stop backporting critical patches to old stable branches.

**Comment by HorayNarea** [comment]
My thought was: if you know nobody uses a specific service, you could sunset that service and remove it when it's too much work to keep it working

**Comment by kaiyou** [comment]
But that would require to send statistic requests from every container, which I am not yet comfortable about as I find it a bit more intrusive.

**Comment by HorayNarea** [comment]
I guess you're right… I would suggest keeping this proposal in mind but not doing anything as long as it's not a burden to maintain the whole package
