### ISSUE TITLE
System storage filled automatically and systematically

### ISSUE THREAD

**Issue by OwOchle** [Mailu/Mailu#3281]
## Environment & Version

- compose : `2.27.0`
- Version: `2.0` (latest)

## Description
Clamav (or rspamd i could not find what is this directory) is filling storage via the filter subdirectory at night (probably an issue with freshclam or something).

## Replication Steps
I dont really know, my server has nothing special to it, just the plain config generated using the mailu utility

## Observed behaviour
My file system is getting bloated with directories and file in the `/mailu/filter` directory, every one of them is named as `tmp-[hexa]` with a clamav testfile (i think) in them, making the server really unreliable.

## Logs
No logs provided by the container.

**Comment by nextgens** [comment]
In master we have switched to clamav's upstream image. I suggest you tweak the antivirus section of your ``docker-compose.yml`` to make it look like the following:

https://github.com/Mailu/Mailu/blob/2.0/setup/flavors/compose/docker-compose.yml#L178 (old)
https://github.com/Mailu/Mailu/blob/master/setup/flavors/compose/docker-compose.yml#L222 (new)

**Comment by OwOchle** [comment]
Okay, i'll let it sit there and see if the error occurs again. I'll let you know, should i regenerate a full docker compose file once the new setup is pushed or it's recommended to update ?

**Comment by nextgens** [comment]
Generate a new file but only keep the 'antivirus' section... merge it to your existing one
