### ISSUE TITLE
Radicale invalid configuration

### ISSUE THREAD

**Issue by aminb** [Mailu/Mailu#330]
Mailu's `radicale` container [uses](https://github.com/Mailu/Mailu/blob/89209822137c618fdc28d60d6fb4168a5a326abb/optional/radicale/Dockerfile) Alpine Linux's `radicale` package (version [`2.1.8-r1`](https://pkgs.alpinelinux.org/package/edge/testing/x86_64/radicale) at the moment). However, Mailu's current [Radicale config](https://github.com/Mailu/Mailu/blob/89209822137c618fdc28d60d6fb4168a5a326abb/optional/radicale/radicale.conf) isn't compatible with `radicale >= 2.0.0`, due to breaking changes in 2.0.0.

Namely, `docker-compose logs webdav` shows this error:

```
webdav_1     | ERROR: Invalid configuration: Invalid option 'base_prefix' in section 'server' in config
```

Moreover, `radicale >= 2.0.0` doesn't support IMAP authentication out of the box anymore (see Kozea/Radicale#672), but there seems to be a [RadicaleIMAP](https://github.com/Unrud/RadicaleIMAP) plugin we can use.

**Comment by kaiyou** [comment]
Thank you for creating the issue. I am aware of it and started rewriting the Radicale configuration and the authentication process. Radicale will now be authenticated the same way as Dovecot/Postfix/Rspamd: nginx requests the authentication directly to an API on the admin container.

**Comment by aminb** [comment]
Awesome. Cheers!
