### ISSUE TITLE
SMTP Auth Issue after 2024-06 version update

### ISSUE THREAD

**Issue by boralp** [Mailu/Mailu#3301]
After the upgrade 25-587 are closed as suggested in the documentation. However port 465 is giving the responses below:

2024-06-19 20:53:04	SERVER -> CLIENT: 220 mail.server.com Dovecot ready.
2024-06-19 20:53:04	CLIENT -> SERVER: EHLO localhost
2024-06-19 20:53:05	SERVER -> CLIENT: 250-mail.server.com
                   	                  250-8BITMIME
                   	                  250-AUTH PLAIN LOGIN
                   	                  250-BURL imap
                   	                  250-CHUNKING
                   	                  250-DSN
                   	                  250-ENHANCEDSTATUSCODES
                   	                  250-SIZE 50000000
                   	                  250-PIPELINING
                   	                  250 VRFY
2024-06-19 20:53:05	CLIENT -> SERVER: AUTH LOGIN
2024-06-19 20:53:05	SERVER -> CLIENT: 334 VXNlcm5hbWU6
2024-06-19 20:53:05	CLIENT -> SERVER: [credentials hidden]
2024-06-19 20:53:05	SERVER -> CLIENT: 334 UGFzc3dvcmQ6
2024-06-19 20:53:05	CLIENT -> SERVER: [credentials hidden]
2024-06-19 20:53:08	SERVER -> CLIENT: 454 4.7.0 Account is temporarily unavailable.
2024-06-19 20:53:08	SMTP ERROR: Password command failed: 454 4.7.0 Account is temporarily unavailable.
2024-06-19 20:53:08	SMTP Error: Could not authenticate.
2024-06-19 20:53:08	CLIENT -> SERVER: QUIT
2024-06-19 20:53:08	SERVER -> CLIENT: 221 2.0.0 Bye
2024-06-19 20:53:08	SMTP Error: Could not authenticate.
Message could not be sent. Mailer Error: SMTP Error: Could not authenticate.

Admin Logs

mailu_admin_1  | [2024-06-19 20:53:05,967] INFO in nginx: Login attempt for: user@domain.com/submission/465 from: x.x.x.x/25099: success: password
mailu_admin_1  | 192.168.x.x - - [19/Jun/2024:20:53:13 +0000] "GET /internal/auth/email HTTP/1.0" 200 0 "-" "-"

SMTP Logs

Jun 19 20:53:05 mx postfix/smtpd[393]: connect from mailu_front_1.mailu_default[192.168.x.x]
Jun 19 20:53:05 mx postfix/smtpd[393]: improper command pipelining after XCLIENT from mailu_front_1.mailu_default[x.x.x.x]: EHLO mail.server.com\r\n
Jun 19 20:53:05 mx postfix/smtpd[393]: disconnect from mailu_front_1.mailu_default[x.x.x.x] ehlo=1 xclient=0/1 commands=1/2

**Comment by baskinsy** [comment]
I have the same issue logs are saying this even when trying to send mails from Roundcuve

```
smtp-1  | Jun 21 17:04:19 mailu postfix/smtpd[497]: connect from mailu-front-1.mailu_default[192.168.203.3]
smtp-1  | Jun 21 17:04:19 mailu postfix/smtpd[497]: improper command pipelining after XCLIENT from mailu-front-1.mailu_default[172.18.0.3]: EHLO
``

**Comment by ndurchx** [comment]
I also had to revert to v2. Additional information, as it seems to be network related: Ports 80 and 443 are proxied over nginx. All other ports have been allowed with ufw-docker script

**Comment by baskinsy** [comment]
In my case there is no proxy, just a standard install with only one override for the TLS policy for a single recipient domain. I don't think that plays a role in the issue but the installation has no other extra settings. If it is a network issue seems it is between the docker created networks.

**Comment by boralp** [comment]
Mine are behind cloudflare but it is not proxied network. I had to revert back to v2 as well. It worked back without an issue.

**Comment by nextgens** [comment]
Can you retry with what I have put on PR3322 please?

``
export MAILU_VERSION=pr-3322
docker compose up -d
``

**Comment by nextgens** [comment]
2024.06.06 will fix the problem

**Comment by baskinsy** [comment]
I can confirm that everything is ok after re-trying the upgrade with the new version. Great work team.
