### ISSUE TITLE
2024.06 版本无法登录

### ISSUE THREAD

**Issue by snycloud** [Mailu/Mailu#3302]
版本 2024.06
webmail ： roundcube
docker 版本：Docker version 26.1.3, build b72abbb
docker-compose 版本：Docker Compose version v2.27.0

mailu.env 有配置如下内容
###################################
# Admin settings
###################################
INITIAL_ADMIN_ACCOUNT=admin
INITIAL_ADMIN_DOMAIN=xxx.cn
INITIAL_ADMIN_PW="xxxx"
INITIAL_ADMIN_MODE=update

也尝试直接通过命令设置密码
docker compose -p mailu exec admin flask mailu admin admin xxx.cn xxxxx

都会出现如下问题

访问 http://mail.xxx.cn 时，被系统追加了 sso 内容
http://mail.xxx.cn/sso/login?url=/webmail/?homepage

输入账号密码不提示任何报错信息，但是一直无法登录成功，如下：
![image](https://github.com/Mailu/Mailu/assets/18653890/fcad034d-11d5-4953-a4fd-1af127402deb)

但是输入错误的账号密码，如下：
![image](https://github.com/Mailu/Mailu/assets/18653890/0c80809a-22e2-468c-8177-2f92244b79fa)

**Comment by snycloud** [comment]
是不是跟我使用了nginx配置有关系

**Comment by snycloud** [comment]
nginx 配置如下：
server {
    listen 443 ssl;
    server_name mail.xxxx.cn;
    charset utf-8;

    # ssl
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:40m;
    ssl_session_timeout 5m;
    ssl_session_tickets off;
    ssl_certificate /etc/nginx/conf.d/certs/mail.xxx.cn/mail.xxx.cn.pem;
    ssl_certificate_key /etc/nginx/conf.d/certs/mail.xxx.cn/mail.xxx.cn.key;

    # OCSP stapling
    ssl_stapling on;
    ssl_stapling_verify on;

    add_header Strict-Transport-Security "max-age=63072000";

    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header WL-Proxy-SSL true;
        proxy_set_header X-Forwarded-For $remote_addr;
        client_max_body_size 64M;
        # proxy_pass https://10.110.1.32:9443;
        proxy_pass http://10.110.1.32:9080;
    }
}

**Comment by christf** [comment]
Wie ist denn das Symptom?

**Comment by dongshan3** [comment]
> 是不是跟我使用了nginx配置有关系

很可能。浏览器 Chrome 访问 webmail 页面提示是：ERR_TOO_MANY_REDIRECTS 。如果您是自行配置反向代理 proxy ，可参考一下：https://mailu.io/2024.06/reverse.html
