### ISSUE TITLE
Compose file for 2024.06 should not have port maps for 110, 143, 587

### ISSUE THREAD

**Issue by spomata** [Mailu/Mailu#3320]
I have generated a `docker-compose.yml` and `mailu.env` files from setup.mailu.io in order to upgrade to 2024.06 and I noticed that port mappings for deprecated STARTTLS ports are still listed under the nginx front container.

Is that a deliberate choice for backwards compatibility?

**Comment by nextgens** [comment]
Yes, this enables the config to be changed without having to go through setup again.
