### ISSUE TITLE
The attempt to read data from the server “(null)” failed.

### ISSUE THREAD

**Issue by SaiGonSeamus** [Mailu/Mailu#333]
Minor bug with Mac mail app

Doesn't affect deliverability, appears to resolve itself.

It presents when you launch the mail app

In the logs we see

`2017/11/25 15:53:30 [error] 9#9: *11124 auth http server 127.0.0.1:8000 did not send server or port while in http auth state, client: xxx.xxx.xxx.xxx, server: 0.0.0.0:993, login: "auser@ourdomain.com"`

Seems to relate to the IMAP config.
[](
https://discussions.apple.com/thread/2517855?start=0&tstart=0)

**Comment by kaiyou** [comment]
Still this is quite weird. It is related to the admin backend not replying with a proper configuration. Could you extract some of the ``admin`` logs as well?

**Comment by SaiGonSeamus** [comment]
[adminlogs.txt](https://github.com/Mailu/Mailu/files/1503236/adminlogs.txt)

**Comment by kaiyou** [comment]
Mmmh, this matches with a 429 (too many authentication requests). Maybe your mail client opens many IMAP connections at startup. Try increasing the authentication rate limit maybe?

**Comment by SaiGonSeamus** [comment]
Yeah, I have a lot of accounts for testing now on the one server. This is a feature not a bug. Just wanted to make sure it wasn't something needed attention.
