### ISSUE TITLE
is there a reason why a 9 month old clamav image is used? clamav/clamav-debian:1.2.0-6

### ISSUE THREAD

**Issue by Aaron-Ritter** [Mailu/Mailu#3347]
When looking at upgrading to 2024.06 i saw that the version for clamav is on 1.2.0-6 rather than e.g. [1.2.3-44](https://hub.docker.com/layers/clamav/clamav-debian/1.2.3-44/images/sha256-45e2c7790ab6e6f317f4ae19643786e79452792545cda66423e1a6c24d2d042a?context=explore) 

Would upgrading it break anything as its just a minor upgrade?

https://github.com/Mailu/Mailu/blob/d5bee885bfd5f965a3fd869cc60123f0ab660117/setup/flavors/compose/docker-compose.yml#L220

**Comment by Aaron-Ritter** [comment]
setting [1.2.3-44](https://hub.docker.com/layers/clamav/clamav-debian/1.2.3-44/images/sha256-45e2c7790ab6e6f317f4ae19643786e79452792545cda66423e1a6c24d2d042a?context=explore) seems to work just fine, at least on the relay i cant see any issues in the logs or so.

**Comment by Aaron-Ritter** [comment]
Looking at the different release notes there is some important fixes in the different patch versions 1.2.1/1.2.2/1.2.3:

https://blog.clamav.net/2024/04/clamav-131-123-106-patch-versions.html
https://blog.clamav.net/2023/11/clamav-130-122-105-released.html
https://blog.clamav.net/2023/10/clamav-121-113-104-010311-patch.html

**Comment by nextgens** [comment]
Please send a PR and update the release instructions so that we don't forget about it next time.

**Comment by Aaron-Ritter** [comment]
@nextgens sure! where can i find the release instructions?

**Comment by nextgens** [comment]
https://github.com/Mailu/Mailu/wiki/Release-workflow is what I had in mind

**Comment by Aaron-Ritter** [comment]
thanks a lot @nextgens for fixing it! Sorry, i was out and didn't have time till now for creating a PR.
