### ISSUE TITLE
Auto-forward Configuration error

### ISSUE THREAD

**Issue by wzy-wangge** [Mailu/Mailu#3349]
webadministration-> Settings  -> Auto-forward 

Version：docker compose 2024.06

## Turn off error reporting after enabling

Here is the error log:

admin-1            |     c = connection.execute(
admin-1            |         ^^^^^^^^^^^^^^^^^^^
admin-1            |   File "/app/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
admin-1            |     return meth(
admin-1            |            ^^^^^
admin-1            |   File "/app/venv/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
admin-1            |     return connection._execute_clauseelement(
admin-1            |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
admin-1            |   File "/app/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
admin-1            |     ret = self._execute_context(
admin-1            |           ^^^^^^^^^^^^^^^^^^^^^^
admin-1            |   File "/app/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1821, in _execute_context
admin-1            |     self._handle_dbapi_exception(
admin-1            |   File "/app/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2353, in _handle_dbapi_exception
admin-1            |     raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
admin-1            |   File "/app/venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1815, in _execute_context
admin-1            |     context = constructor(
admin-1            |               ^^^^^^^^^^^^
admin-1            |   File "/app/venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 1459, in _init_compiled
admin-1            |     flattened_processors[key](compiled_params[key])
admin-1            |   File "/app/venv/lib/python3.12/site-packages/sqlalchemy/sql/type_api.py", line 2044, in process
admin-1            |     return fixed_process_param(value, dialect)
admin-1            |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
admin-1            |   File "/app/mailu/models.py", line 90, in process_bind_param
admin-1            |     raise TypeError('Must be a list of strings')
admin-1            | sqlalchemy.exc.StatementError: (builtins.TypeError) Must be a list of strings
admin-1            | [SQL: UPDATE user SET forward_enabled=?, forward_destination=?, forward_keep=?, updated_at=?, email=? WHERE user.email = ?]
admin-1            | [parameters: [{'forward_destination': 'xxxxx@qq.com', 'forward_keep': False, 'forward_enabled': False, 'user_email': 'n3bk92@xxxxx.com'}]]

**Comment by nextgens** [comment]
dup of #3352
