### ISSUE TITLE
Generated docker-compose.yml (setup.mailu.io) contains wrong path to rspamd override directory

### ISSUE THREAD

**Issue by d-Rickyy-b** [Mailu/Mailu#3359]
## Environment & Version

- `docker compose version` - N/A
- Version: `master`

## Description

When using the config generator hosted on https://setup.mailu.io it produces a docker-compose.yml file where the rspamd overrides path is mapped to a wrong directory.

Related issue: https://github.com/Mailu/Mailu/issues/1566#issuecomment-2267528938

## Replication Steps

1. Generate a new docker-compose.yml file via setup.mailu.io
2. Check the volume path 

## Observed behaviour

The volume mapping for the override is `/mailu/overrides/rspamd:/overrides:ro`.

## Expected behaviour

The path should rather be `/mailu/overrides/rspamd:/etc/rspamd/override.d` as also supported by the config provided in this repo:

https://github.com/Mailu/Mailu/blob/5b5c6ba4f5d2cc78b04891bd010942d571fea25a/tests/compose/webmail/docker-compose.yml#L87

Also, with the read-only mapping the file cannot be edited via the web interface.

## Logs

N/A

**Comment by nextgens** [comment]
This is working as intended.

1) you are looking at the wrong file; setup's template is at https://github.com/Mailu/Mailu/blob/master/setup/flavors/compose/docker-compose.yml#L201
2) the files from ``/overrides/`` get copied in the startup script, see https://github.com/Mailu/Mailu/blob/master/core/rspamd/start.py

**Comment by d-Rickyy-b** [comment]
Thank you. Sadly, without the changes I couldn't get overrides working for rspamd. I followed the instructions on the mailu website (https://mailu.io/2.0/antispam.html).

The reason might be, that the instructions say to configure the blacklist like so: `map = "/etc/rspamd/override.d/blacklist.inc";`, while the startup script seems to write the files to a completely different location `/etc/rspamd/local.d`.

https://github.com/Mailu/Mailu/blob/5b5c6ba4f5d2cc78b04891bd010942d571fea25a/core/rspamd/start.py#L24

Also if I understood correctly, when adding the overrides via the startup script, changes to the map made via the rspamd web ui are not persistent, since it's not written back to the host, despite claimed otherwise in the instructions:

> When clicking on this map, you can live-edit the map via the GUI. Changes are effective immediately. Only changes made to maps in the overrides folder are persistent.

While this seems to be intended, it's at least worth changing the docs to better reflect the actual behavior.

**Comment by nextgens** [comment]
The documentation for the current stable version of Mailu is at https://mailu.io/2024.06/antispam.html#how-can-i-block-emails-from-a-domain

Is that incorrect or otherwise inaccurate?

**Comment by d-Rickyy-b** [comment]
Thanks, the 2.0 version of the documentation was the one I found via Google. I didn't switch to the 2024.06 manually.

> Is that incorrect or otherwise inaccurate?

There are still two mentions of the old path:

> The above example configuration will reject all emails send from domains that are listed in ‘/etc/rspamd/override.d/blacklist.inc’.

> 5. Check if the map is available. In rspamd webgui to to configuration. A map is available with the path: /etc/rspamd/override.d/blacklist.inc Senders domain part is on the local blacklist

Both these paths should be changed to `/overrides/blacklist.inc` to avoid confusion, right?

___

Also the screenshot after `5.` still shows the old path `/etc/rspamd/override.d/blacklist.inc`. Not really critical though.

___

The documentation says:

> When clicking on this map, you can live-edit the map via the GUI. Changes are effective immediately. Only changes made to maps in the overrides folder are persistent.

Since the docker volume is mounted as read only by default , the changes aren't persistent (= surviving a --force-recreate), are they?

`- "/mailu/overrides/rspamd:/overrides:ro"`

**Comment by d-Rickyy-b** [comment]
Thank you for the changes. While you're at it, there's also a typo I just found: `In rspamd webgui to to configuration, a map is available with the path`. That should probably say "go to" instead of "to to".

> IMHO the map name given in 5 ought to stay the same

Huh, why that? No files are copied to the `/etc/rspamd/override.d/` dir, so I am pretty sure the path should also be changed there. The start.py copies all overrides to the `/etc/rspamd/local.d` directory (where the blacklist.inc can also be found).

![image](https://github.com/user-attachments/assets/b9605ff9-3355-4403-a7af-d00c6305d430)

Also the blacklist shows up in the web UI as `/overrides/blacklist.inc`
![image](https://github.com/user-attachments/assets/6139f4c8-941b-4f05-b549-c87a62d31ab7)

**Comment by nextgens** [comment]
Indeed; I've pushed b359301c
