### ISSUE TITLE
Check incoming mail against Blacklist

### ISSUE THREAD

**Issue by morbidick** [Mailu/Mailu#336]
first of all mailu looks super nice im looking to use it in a production environment myself. Are you interested in using dnsbl to block known dynamic ips and known hosts sending spam?

I'ld have to look in which lists are free for everyone and post a PR. For example there is one provided by [iX a german computer newspaper](http://www.dnsbl.manitu.net/?language=en).

**Comment by kaiyou** [comment]
It would be interesting to be able to configure blacklists indeed. Multiple options here:
- provide configurable variables
- provide a configuration UI in the admin website
- use static lists
- document how to override the list in the override section

**Comment by morbidick** [comment]
I think as another environment variable would be easiest, ill have a look how to include it in the jinja config template.
