### ISSUE TITLE
WARNING in nginx: Received undecodable user/password from nginx: 'aaron@my.domain'/'password�password'

### ISSUE THREAD

**Issue by Aaron-Ritter** [Mailu/Mailu#3364]
## Environment & Version

- Docker Compose version v2.29.1
- Version: MAILU_VERSION:-2024.06

## Description
After upgrading to 2024.06 some users with % in their password generate an error:

```
WARNING in nginx: Received undecodable user/password from nginx: 'aaron@my.domain'/'password�password'
```
(FYI I've replaced the actual mail domain and password with password and left the special character in i got in the logs as example)

## Replication Steps
Set % in the password which generates special characters.

## Expected behaviour
It should not have issues with % in the password.

**Comment by nextgens** [comment]
Well I can't reproduce it on the test server... unless you can provide us with data that breaks it won't get fixed.

Try the following:
``
test@test.mailu.io
test%test%
on https://test.mailu.io
``

**Comment by Aaron-Ritter** [comment]
uff, sorry didn't think that far 🤦‍♂️ i will see if i have any other users with the same issue or reproduce it.

**Comment by Aaron-Ritter** [comment]
try `blub%e9blub` and where the error happens is with IMAP (The web UI SSO works)

**Comment by nextgens** [comment]
@Aaron-Ritter please try what's on the PR when the images are built

```
export MAILU_VERSION=pr-3366
docker compose pull
docker compose up -d
```

**Comment by ser** [comment]
MAILU_VERSION=pr-3366 tested, works correctly.

IMHO new release of mailu should be published ASAP as it's a massive bug.

**Comment by ser** [comment]
BTW, exposing clear-text password in logs is a big no-no!

**Comment by nextgens** [comment]
Thank you for confirming.

2024.06.9 was released 12 hours before your reply and has the fix.

We were exposing passwords in logs in case of errors; this has enabled us to fix this bug. We are not anymore.
