### ISSUE TITLE
Integrate with a mailing list server

### ISSUE THREAD

**Issue by morbidick** [Mailu/Mailu#337]
I'ld like to combine Mailu with Mailman which uses docker images itself since version 3. Would it be interesting for the project itself or would it be better do keep the modified docker-compose in a separate repo?

Steps to implement:
1. Use a separate subdomain that gets forwarded by postfix (e.g. lists.example.com)
2. Have postfix lookup valid mail adresses on the same domain and forward them to mailman
3. Integrate the mailman api in mailu admin interface (would depend on #56)

**Comment by kaiyou** [comment]
I think multiple people have been working on this already and are documenting it and preparing a PR as we speak. Depending on the result, a separate docker compose is an option, but I would like to keep configuration as straightforward as possible, so using the ``none`` container is still an option.

If anyone could step up here, or you could always come down on our chat and start discussing the matter :)

**Comment by morbidick** [comment]
Im currently playing around with [mailman 3 docker](https://github.com/maxking/docker-mailman/) and would be interested on working on a PR.

@kaiyou you got any links to the other works? I'll try to find the chat.

**Comment by Nebukadneza** [comment]
Hi There,

The `Mailu`-Project is currently in a bit of a bind! We are short on man-power, and we need to judge if it is possible for us to put in some work on this issue.

To help with that, we are currently trying to find out which issues are actively keeping users from using `Mailu`, which issues have someone who want to work on them — and which issues may be less important. These a less important ones could be discarded for the time being, until the project is in a more stable and regular state once again.

In order for us to better assess this, it would be helpful if you could put a **reaction on this post** (use the :smiley: icon to the top-right).
- 👍️ if you **need this** to be able to use Mailu. Ideally, you’d also be able to test this on your installation, and provide feedback …
- 🎉 if you find it a **nice bonus**, but no deal-breaker
- 🚀 if you want to **work on it yourself**!
We want to keep this **voting open for 2 weeks** from now, so please help out!

**Comment by Diman0** [comment]
Hi There,

we see this issue had only little attention 😟. As much as it pains us: In order to get the current issues a bit more manageable for us, we decided to close it. 👋👋

We hope that no one feels offended by doing so. Should the issue get really pressing in the future, please feel free to re-open it.

Thank you for your patience and understanding, 🙇
- Your Mailu Team
