### ISSUE TITLE
The latest version of port 587 does not work anymore

### ISSUE THREAD

**Issue by hudingwen** [Mailu/Mailu#3370]
I update the master version of the docker image regularly every month to synchronize the latest version. But since the 2.0 version updated the latest master version, my 587 port is no longer available and I can only use port 465.
The following is the program sending log.
Versions:
WordPress: 6.6.1
WordPress MS: No
PHP: 7.4.30
WP Mail SMTP: 4.1.0

Params:
Mailer: smtp
Constants: No
ErrorInfo: SMTP Error: Could not connect to SMTP host. Failed to connect to serverSMTP server error: Failed to connect to server SMTP code: 111 Additional SMTP info: Connection refused
Host: mail.xxxx.cn
Port: 587
SMTPSecure: tls
SMTPAutoTLS: bool(true)
SMTPAuth: bool(true)

Server:
OpenSSL: OpenSSL 1.1.1n 15 Mar 2022

Debug:
Email Source: WP Mail SMTP
Mailer: 其他 SMTP
SMTP Error: Could not connect to SMTP host. Failed to connect to serverSMTP server error: Failed to connect to server SMTP code: 111 Additional SMTP info: Connection refused

SMTP Debug:
2024-08-11 15:07:48 Connection: opening to mail.xxxx.cn:587, timeout=300, options=array()

2024-08-11 15:07:48 Connection failed. Error #2: stream_socket_client(): unable to connect to mail.xxxx.cn:587 (Connection refused) [/www/www.xxxx.cn/wordpress/wp-includes/PHPMailer/SMTP.php line 409]

2024-08-11 15:07:48 SMTP ERROR: Failed to connect to server: Connection refused (111)

SMTP Error: Could not connect to SMTP host. Failed to connect to server

**Comment by ghostwheel42** [comment]
This is described in the release notes: https://mailu.io/2024.06/releases.html#starttls-ports-disabled-by-default
You can re-enable the ports if you really need to.

**Comment by ser** [comment]
It's highly controversial, it's based on single research paper which is not widely discussed in literature and I don't know any client which uses plain SMTP on port 587.
