### ISSUE TITLE
Alternative Domain name not shown

### ISSUE THREAD

**Issue by Aaron-Ritter** [Mailu/Mailu#3375]
## Environment & Version

- Docker Compose version v2.29.1
- Version: 2024.06
- ghcr.io/mailu/admin 2024.06 66db387be14a 46 hours ago 244MB

## Description

The Screenshot mentioned in https://github.com/Mailu/Mailu/pull/3350 suggests there should be all alternative domain name listed in the detail overview of the domain:

> <img width="1191" alt="screenshot-alternative-domain-details" src="https://github.com/user-attachments/assets/e3d48e39-6c2e-429c-9186-aeb464a33e47">
> This is how the part for the alternative domains looks like on the domain details page.

_Originally posted by @Jumper78 in https://github.com/Mailu/Mailu/issues/3350#issuecomment-2242850770_

This does not work for my deployment, here one of the examples:

![image](https://github.com/user-attachments/assets/4d8b0c07-3624-4cba-8861-fe9e5b30e2f6)

but the details don't show alternative domain names

![image](https://github.com/user-attachments/assets/69a0b2b5-18c4-430c-8e72-83ca4616a31f)

**Comment by nextgens** [comment]
This PR got merged to master... and you are not running master.

Re-open if you can reproduce on our test server: https://mailu.io/master/demo.html
