### ISSUE TITLE
Managing of external certificates - frontend reload

### ISSUE THREAD

**Issue by jcz1** [Mailu/Mailu#3405]
In docs there is an example script for managing external (LE) certificates:

```
#!/bin/sh
cp /etc/letsencrypt/live/domain.com/privkey.pem /mailu/certs/key.pem || exit 1
cp /etc/letsencrypt/live/domain.com/fullchain.pem /mailu/certs/cert.pem || exit 1
docker exec mailu_front_1 nginx -s reload
```

https://mailu.io/master/maintain.html#external-certs

But there is not only nginx but also dovecot in the mailu_front container. So after certificate renew you have to reload dovecot:

`docker exec mailu_front_1 dovecot reload`

Without that you have still old certificate for dovecot services.

**Comment by nextgens** [comment]
Dovecot is not directly exposed and does not require certificates the way it's setup in Mailu.

**Comment by nextgens** [comment]
but the documentation does require updating...

**Comment by jcz1** [comment]
I had to reload dovecot today and there is nginx and dovecot process in front container and dovecot is listening on 993.
