### ISSUE TITLE
Creating User from Command Line Causes Web User to Logout

### ISSUE THREAD

**Issue by GoldenBookCover** [Mailu/Mailu#3411]
## Environment & Version

- `Docker Compose version v2.29.1`
- `Server: Docker Engine - Community Version: 27.1.2`
- Version: `ghcr.io/mailu/*:2024.06`

## Description

I have deployed a docker-compose environment with standalone mariadb service. When I login on the web page, and then generate a new user using command line, I will be forced to logout on the web page, and I have to access the login page again, and refresh for a few times before I can re-login.

## Replication Steps

I used the default docker compose setup, with an extra mariadb service:

```yaml
  mariadb:
    image: mariadb:10.11
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PW}"
    expose:
      - "3306"
    volumes:
      - "./mariadb:/var/lib/mysql"
    networks:
      - default
      - webmail
```

And edited the `mailu.env` file for database settings:

```
DB_FLAVOR=mysql
DB_USER=mailu
DB_PW="super_password"
DB_HOST=mariadb
DB_NAME=mailu
```

As I didn't make any further adjustments, the database is using the default settings.

Login on the web page, and hit Refresh, everything went well; then generated a new user in the command line

```bash
docker compose exec admin flask mailu user user1 example.domain 'super_password'
```

Then hit Refresh, I was already logged out and became an anonymous user.

## Observed behaviour

I was logged out and became an anonymous user. Thus refreshing the page would give me an error: `Server Error! (parsererror)`.

![image](https://github.com/user-attachments/assets/ecb36cee-a550-4803-900b-0fbec64e9a94)

## Expected behaviour

It should not affect already logged-in user.

![image](https://github.com/user-attachments/assets/74b4abfd-bdc1-443b-a7c5-cb31953912a7)

## Logs

Tried to print out some extra information, so I modified the source code:

```python
# mailu/internal/views/auth.py
@internal.route("/auth/user")
def user_authentication():
    """ Fails if the user is not authenticated.
    """
    print(f"{flask_login.current_user.is_anonymous = }")
    if (not flask_login.current_user.is_anonymous
          and flask_login.current_user.enabled):
        # ...
    return flask.abort(403)
```

The log before generating new user

```
admin-1  | flask_login.current_user.is_anonymous = False
admin-1  | 192.168.50.98 - - [07/Sep/2024:09:51:07 +0000] "GET /internal/auth/user HTTP/1.0" 200 0 "https://example.domain/webmail/?_task=mail&_mbox=INBOX" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36"
```

The log after generating new user

```
admin-1  | flask_login.current_user.is_anonymous = True
admin-1  | 192.168.50.98 - - [07/Sep/2024:09:51:40 +0000] "GET /internal/auth/user HTTP/1.0" 403 213 "https://example.domain/webmail/?_task=mail&_mbox=INBOX" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36"
```

I also noticed a warning message from mariadb

```
mariadb-1  | 2024-09-07  9:51:15 217 [Warning] Aborted connection 217 to db: 'mailu' user: 'mailu' host: '192.168.203.5' (Got an error reading communication packets)
```

It seems generating a new user would forcibly terminate the database connection, and cause the current logged-in user to become an anonymous user.

If you manually create a number of users in the command line, then it'd take forever for web users to login.

```
for i in `seq 1 200`; do
  sudo docker compose exec admin flask mailu user testuser$i example.domain 'test1234'
  sleep 1
done
```

**Comment by GoldenBookCover** [comment]
After some inspection, I found this issue is caused by this line of code:

```python
# /app/mailu/manage.py
def user(localpart, domain_name, password):
    """ Create a user
    """
    # ...
    user.set_password(password)
    # ...
```

So I modify it to become this

```python
def user(localpart, domain_name, password):
    """ Create a user
    """
    # ...
    # FIXME: Cause web users to become anonymous
    ##user.set_password(password)
    user.password = models.User.get_password_context().hash(password)
    # ...
```

Don't understand why, but this is the only solution I can find for now. Hope others can figure it out.

**Comment by ghostwheel42** [comment]
This is not a bug but a feature. Wehn you cheange the password all active sessions are invalidated.
Changing a password normally is done when the password got compromised, so it is a good practice to invalidate the existing sessions.

**Comment by nextgens** [comment]
Yes but not all sessions of all users... here I suspect that the commit() hasn't happened... so the username is unknown, there is no prefix, all the sessions of all users get nuked.
