### ISSUE TITLE
Mailman integration as LMTP relay failure

### ISSUE THREAD

**Issue by pgmillon** [Mailu/Mailu#3414]
## Environment & Version

- kubernetes 1.28.2
- Version: `1.8`

## Description
I've been using the traditional Mailman/postfix integration using regexp maps successfully for years:
```
relay_domains = regexp:/opt/mailman/var/data/postfix_domains, ${podop}transport
```
Recently I've been trying to have DMARC validation of emails sent by Mailman and I think using regexp maps rather than the "Relayed domain" features of Mailu is not helping, so I'm switching without any success so far with errors on postfix.

## Replication Steps
Setup a new relayed domain using lmtp: prefix as remote host

## Observed behaviour
Basic resolution & connectivity check from postfix service:
```
# telnet mailman 8024
Connected to mailman
220 mailman-9b5cd9d8b-fxq2z GNU Mailman LMTP runner 2.0
```
Various relayed domain configs:

Remote host: lmtp:mailman:8024
```
Sep 08 21:54:27 smtp postfix/smtp[622]: fatal: unknown service: mailman/tcp
Sep 08 21:54:28 smtp postfix/qmgr[376]: warning: private/smtp socket: malformed response
Sep 08 21:54:28 smtp postfix/qmgr[376]: warning: transport smtp failure -- see a previous warning/fatal/panic logfile record for the problem description
Sep 08 21:54:28 smtp postfix/master[374]: warning: process /usr/libexec/postfix/smtp pid 622 exit status 1
Sep 08 21:54:28 smtp postfix/master[374]: warning: /usr/libexec/postfix/smtp: bad command startup -- throttling
Sep 08 21:54:28 smtp postfix/error[624]: BC3A18258B: to=<news@lists.xyz>, relay=none, delay=1.8, delays=0.7/1.1/0/0.01, dsn=4.3.0, status=deferred (unknown mail transport error)
```
Remote host: lmtp:mailman.mail-system.svc.cluster.local:8024
```
Sep 08 22:03:57 smtp postfix/smtp[1687]: fatal: unknown service: mailman.mail-system.svc.cluster.local/tcp
Sep 08 22:03:58 smtp postfix/qmgr[376]: warning: private/smtp socket: malformed response
Sep 08 22:03:58 smtp postfix/qmgr[376]: warning: transport smtp failure -- see a previous warning/fatal/panic logfile record for the problem description
Sep 08 22:03:58 smtp postfix/master[374]: warning: process /usr/libexec/postfix/smtp pid 1687 exit status 1
Sep 08 22:03:58 smtp postfix/master[374]: warning: /usr/libexec/postfix/smtp: bad command startup -- throttling
Sep 08 22:03:58 smtp postfix/error[1688]: 32DFF82598: to=<news@lists.xyz>, relay=none, delay=3, delays=1.8/1.1/0/0.14, dsn=4.3.0, status=deferred (unknown mail transport error)
```
Remote host: lmtp:10.46.195.105:8024
```
Sep 08 22:07:14 smtp postfix/smtp[2058]: fatal: garbage after numerical service in server description: [lmtp]:10.46.195.105
Sep 08 22:07:15 smtp postfix/qmgr[376]: warning: private/smtp socket: malformed response
Sep 08 22:07:15 smtp postfix/qmgr[376]: warning: transport smtp failure -- see a previous warning/fatal/panic logfile record for the problem description
Sep 08 22:07:15 smtp postfix/master[374]: warning: process /usr/libexec/postfix/smtp pid 2058 exit status 1
Sep 08 22:07:15 smtp postfix/master[374]: warning: /usr/libexec/postfix/smtp: bad command startup -- throttling
Sep 08 22:07:15 smtp postfix/error[2059]: 241B781ABB: to=<news@lists.xyz>, relay=none, delay=1.6, delays=0.5/1.1/0/0.01, dsn=4.3.0, status=deferred (unknown mail transport error)
```

## Expected behaviour
After switching back from relayed domains to the regexp maps:
```
Sep 08 22:36:05 smtp postfix/lmtp[453]: 207538259F: to=<news@lists.xyz>, relay=100.64.1.71[100.64.1.71]:8024, delay=1.3, delays=1/0.02/0.01/0.27, dsn=2.0.0, status=sent (250 Ok)
Sep 08 22:36:05 smtp postfix/qmgr[369]: 207538259F: removed
```

**Comment by nextgens** [comment]
Highlighting the line that matters:
``
Sep 08 21:54:27 smtp postfix/smtp[622]: fatal: unknown service: mailman/tcp
``

This has nothing to do with Mailu.

**Comment by pgmillon** [comment]
Thank you for your quick reply but I this this issue IS related to mailu (or the podop component of mailu) since it is generating the relayed domain info postfix uses to forward emails.
I think there's something wrong in the relayed domain map generated by mailu, the service name should be mailman, not mailman/tcp.

**Comment by pgmillon** [comment]
The error complaining about "garbage after numerical service in server description" in the last example also demonstrates there's something wrong in whatever is generated by the mailu platform and the postfix server cannot consume it properly.

**Comment by nextgens** [comment]
Your custom configuration seems to have several, distinct problems.

Start by solving the 'unknown service: mailman/tcp' error; you are probably missing something in '/etc/postfix/master.cf' ... and no that has nothing to do with Mailu since it reads 'mailman'.

**Comment by nextgens** [comment]
If I had to venture a guess, you are missing a transport_map, as per:
https://docs.mailman3.org/projects/mailman/en/latest/src/mailman/docs/mta.html#regular-expression-tables

In any case, issues here are reserved for things that require code changes in Mailu. If you cannot identify a code-change required fill in a support request (not on this repo since you are not using docker-compose).

**Comment by pgmillon** [comment]
Following your recommendation, I updated my regex transport map from IP to hostname (mailman), and it works perfectly.  
There's no DNS resolution issue when specifying mailman hostname in a static transport map, also as demonstrated in my original message with a telnet from the postfix pod to the mailman LMTP.
As I described, I'm trying to move away from regex transport maps generated by mailman and use Mailu's "Relayed domain" that is generating the transport map, since as #257 describe, it's meant for forwarding to mailing list servers.

**Comment by nextgens** [comment]
what do your ``/opt/mailman/var/data/postfix_*`` look like?

**Comment by pgmillon** [comment]
```
# AUTOMATICALLY GENERATED BY MAILMAN ON 2024-08-29 21:27:20
#
# This file is generated by Mailman, and is kept in sync with the binary hash
# file.  YOU SHOULD NOT MANUALLY EDIT THIS FILE unless you know what you're
# doing, and can keep the two files properly in sync.  If you screw it up,
# you're on your own.

/^lists\.xyz\.fr$/ lists.xyz.fr
/^lists\.zyx\.net$/ lists.zyx.net
```

```
/^news@lists\.zyx\.net$/                  lmtp:[mailman]:8024
/^news-bounces(\+.*)?@lists\.zyx\.net$/   lmtp:[mailman]:8024
/^news-confirm(\+.*)?@lists\.zyx\.net$/   lmtp:[mailman]:8024
/^news-join@lists\.zyx\.net$/             lmtp:[mailman]:8024
/^news-leave@lists\.zyx\.net$/            lmtp:[mailman]:8024
/^news-owner@lists\.zyx\.net$/            lmtp:[mailman]:8024
/^news-request@lists\.zyx\.net$/          lmtp:[mailman]:8024
/^news-subscribe@lists\.zyx\.net$/        lmtp:[mailman]:8024
/^news-unsubscribe@lists\.zyx\.net$/      lmtp:[mailman]:8024
```

I'm trying to query the podop socket to compare the output but `curl -X GET --unix-socket /tmp/podop.socket http://transport` is just hanging up so far.

**Comment by nextgens** [comment]
``postmap -q $query socketmap:unix:/tmp/podop.socket:transport``

where transport can be replaced as per the suffix after ``${podop}``

**Comment by pgmillon** [comment]
I managed to make some progress on the analysis using postmap:
```
#postmap -q "news@lists.zyx.net" socketmap:unix:/tmp/podop.socket:transport
smtp:[lmtp]:mailman
```
I think it should be `lmtp:[mailman]:8024`

**Comment by nextgens** [comment]
Yeah so it's working as intended: the relay feature was meant to relay to other hosts using SMTP... here you want to relay using LMTP... which we could allow but currently don't.

File a feature request under the 'discussion' tab or send a PR with a patch. The relevant code is at https://github.com/Mailu/Mailu/blob/master/core/admin/mailu/internal/views/postfix.py#L40 ; it should be easy enough to implement.

**Comment by pgmillon** [comment]
Thank you for point out to the relevant code, the method content suggest supporting [both LMTP & SMTP](https://github.com/Mailu/Mailu/blob/master/core/admin/mailu/internal/views/postfix.py#L98) and is also [documented as such](https://github.com/Mailu/Mailu/blob/master/docs/webadministration.rst?plain=1#L240).
While I would be happy to open a feature request for something new, I think the feature is already supposed to be available but is currently broken.
I'd also be happy to open a PR to fix this bug if I have a chance but in the meantime, please reopen this issue.

**Comment by nextgens** [comment]
You still haven't convinced me that there is a bug anywhere here. A problem with your config? sure.

![image](https://github.com/user-attachments/assets/d247a8b5-5e26-4799-a386-92dd7933292f)
```
$ docker compose exec admin curl http://localhost:8080/internal/postfix/transport/admin@list.example.com
"lmtp:mailman:2024"
$ docker compose exec smtp postmap -q "admin@list.example.com" socketmap:unix:/tmp/podop.socket:transport
lmtp:mailman:2024
```

The only questionable part of the code (that will break with your fancy k8s setup) is line 75... and I'm not sure why that condition is there.

**Comment by pgmillon** [comment]
Thank you for testing on your side. After further research, the LMTP support was only added in [1.9](https://github.com/Mailu/Mailu/commit/a1fd44fced2c65a1c379b445fb65f2a5a24efd24) while I'm still running 1.8.
While I'll work on the upgrade, I'm curious why you keep saying I have a fancy setup since I only use the official helm chart with a /overrides/postfix.cf file that adds 2 postfix regex maps :thinking:

**Comment by nextgens** [comment]
I am glad that we agree on the path forward.

1.8 is three years old and unsupported.

Anything involving transport maps is fancy.
