### ISSUE TITLE
Whitespace not stripped from passwords

### ISSUE THREAD

**Issue by strugee** [Mailu/Mailu#3425]
## Environment & Version

`docker compose version`: `Version: Docker Compose version 2.24.6+ds1-0ubuntu1~22.04.1`
Mailu version: `2024.06.15` as reported by `cat /version` in `admin`

## Description

Basically what the title says - apparently a leading space in the password is fed into bcrypt.

The problem with this is that it's shockingly easy to copy a password with whitespace. In my case I did this by sending users a plaintext email with their temporary login password, then double-clicking on the line with their password (and only their password) to select the password for copying. In Firefox, Cmd-C on macOS adds a leading ` ` character to the pasteboard contents, and on Linux (Wayland), Ctrl-C does the same thing to the Wayland clipboard buffer. Users who either manually select the password and copy, or who type it in by hand, then receive very mysterious incorrect password errors. In short, this is incredibly confusing UX.

## Replication Steps

1. Set a user's password to ` foobarfoobar`
2. Try to log in with password `foobarfoobar`

## Observed behaviour

Incorrect username/password error is shown

## Expected behaviour

I'm let in, even though the password is _technically_ incorrect. This feels like a reasonable correction to make.

Unclear to me how much we care about existing accounts that may have leading/trailing whitespace - it seems like if this had happened to anyone before, they would have encountered the same problem I did and changed the password/reported a bug/given up?

## Logs

N/A (though if anyone thinks they're necessary, I can provide)

**Comment by nextgens** [comment]
That's a rabbit hole...

What about trailing white spaces? Or leading capitalization introduced by mobile/assisted virtual keyboards?

**Comment by strugee** [comment]
Fair enough. I'm not married to the suggested implementation. But at a minimum, I think the password change form should _disallow_ passwords with leading/trailing whitespace. I cannot emphasize enough how confusing this is if it happens to you. 

> Or leading capitalization introduced by mobile/assisted virtual keyboards?

Copying and pasting, like from a password manager, does not have this behavior. Neither does typing into an `<input type="password">` field.

**Comment by nextgens** [comment]
@strugee give #3434  a spin once the images are built and let me know your thoughts please.

```
export MAILU_VERSION=pr-3434
docker compose pull
docker compose up -d
```

**Comment by strugee** [comment]
Do you still want feedback given that this was merged?

**Comment by ghostwheel42** [comment]
Sure. Does it work for you?

@nextgens Hmm, now that I look again maybe a better test could be `field.data != field.data.strip(string.whitespace)` or `field.data != field.data.strip(' \t\n\r\v\f')`which would catch all kinds of whitespace. What do you think?

**Comment by nextgens** [comment]
> Do you still want feedback given that this was merged?

Yes please.

@ghostwheel42 feel free to improve upon it. This is the rabbit hole I had in mind. What about UTF BOM markers, RTL markers, ...
