### ISSUE TITLE
Build a setup page

### ISSUE THREAD

**Issue by kaiyou** [Mailu/Mailu#343]
A setup page could be exposed, that just asks a few questions and provides a custom compose/kubernetes/whatever configuration file. This requires a simple web app and a way to export configuration templates for various Git branches.

**Comment by kaiyou** [comment]
A very first version is available in the repository. The framework is ready, it basically lacks the actual configuration.

**Comment by muhlemmer** [comment]
@kaiyou 
cc: @ionutfilip 

Do you have some kind of todo for this?

We would like to work on the standard compose deployment a bit and later inclusion of swarm. Swarm would be much more complicated, as there are a lot of choises to be made. Hence we want to start simple to get familiar with the program.

**Comment by kaiyou** [comment]
I would say:

[ ] make sure the base python scripts run properly and maybe write some documentation for them
[ ] (probably replace the ``setup.py`` script with simply a build per branch, just like documentation, but we can discuss it later)
[ ] write the actual forms in ``steps/`` to ask the proper questions for a new server configuration to be generated
[ ] write the actual results in ``flavors/`` using jinja

**Comment by muhlemmer** [comment]
Transcript of our discussion on Matrix yesterday, for future reference.

> **muhlemmer:**
> kaiyou, We'll start work on the setup utility. Just a question: Do we want to get rid of variables in docker-compose.yml? Ask all the questions in the utility and provide a hard-coded version.
> This woudl make sence, since docker stack deploy does not support loading variables from .env to use in a docker-compose.yml.
>
> Second question: can we upgrade to Docker compose file version `>3?` Start with a common base for Docker Swarm
> **kaiyou:**
> Hardcoding sounds ok even if providing both options is possible using flavors.
> And of course yes we can (and should) update the compose format
**muhlemmer**:
kaiyou. We are having some hickups. At this moment the Dockerfile seems to pull everything from ``GitHub:master.`` Including the app itself?
> Unless we are missing something, there is no way we can test any local changes untill merged.
> So we want to take this out and just use the files relative to the Dockerfile
> **kaiyou**:
> As I was mentioning on the issue, currently the prepare script does the sane kind of complex job as was the docs versioning stuff before. I believe this can be removed altogether and replaced with multiple tags of the docker image.
> **muhlemmer**:
> Aha, clear :D

**Comment by muhlemmer** [comment]
@kaiyou. So we have a working example running at http://setup.usrpro.io:8000. The compose file and env files generated work well.

We didn't have time today to write up the pull request itself, that'll be tomorrow morning. There is still some outstanding and question. More on that tomorrow. The fun part is, is that we didn't have to touch a single line of python to get here :+1: 

Code at https://github.com/usrpro/Mailu/tree/feat-setup

**Comment by HorayNarea** [comment]
Would it be possible to make both webmailers selectable?

**Comment by muhlemmer** [comment]
From a setup point of view yes. But then also nginx config needs adaption to define an extra route. And perhaps they need separate volumes. Also the "webmail" service hostname is used in IMAP for authentication I believe. We will need different service declarations and subsequently update all code that is resolving against the "webmail" hostname.

There are more features I want to start developing once setup is there. Because we can create more complex compose files. But first I want to complete the works to provide same functionality as the regular docker-compose install. Then review, optimize and write documentation.

After we have a solid base, the setup utility is easily extended. So we can start to provide parallel webmail, unbound dns etc etc.

**Comment by kaiyou** [comment]
Just reviewed the pull request. I am honnestly prepared to host this at mailu.io as soon as a few cosmetic details are dealt with. You did an amazing job rushing this.

**Comment by muhlemmer** [comment]
Shall we close this issue?

**Comment by muhlemmer** [comment]
V2 is merged in PR #682. Any further cosmetic updates can be handled in new pull requests. Closing this to mark the milestone :smile:
