### ISSUE TITLE
Dovecot drops login attemps when limit of 100 concurrent imap sessions is reached

### ISSUE THREAD

**Issue by xvalen** [Mailu/Mailu#3450]
## Environment & Version

- Docker Compose version v2.29.2
- Version: 2024.06

## Description

Dovecot drops some login attempts.

## Replication Steps

Login with more than 100 mail clients over imap

## Observed behaviour
Login attempts are dropped after circumstances above. 

## Expected behaviour

Make it possible to override dovecot proxy.conf setting of front container.

## Logs

```
mailu-front[3011235]: Sep 11 11:50:10 master: Warning: service(imap-login): process_limit (100) reached, client connections are being dropped
```

## Workaround
copy proxy.conf template from container to host system:
```
cd /mailu
docker compose exec front cat /dovecot_conf/proxy.conf > proxy.conf
```

increase process_limit for service imap-login:
```
diff -u proxy.conf.orig proxy.conf
--- proxy.conf.orig     2024-09-11 15:12:29.898119459 +0200
+++ proxy.conf  2024-09-11 14:29:07.835583265 +0200
@@ -114,6 +114,7 @@
   inet_listener imap-webmail {
    port = 10143
   }
+  process_limit = 200
 }
 
 service pop3-login {
```
Here is my modification of docker-compose.yml to make proxy.conf modification persistent across container rebuilds.
```
# diff -u docker-compose.yml.orig docker-compose.yml
--- docker-compose.yml.orig     2024-09-11 15:18:22.271573663 +0200
+++ docker-compose.yml  2024-09-11 14:32:02.980379832 +0200
@@ -40,6 +40,7 @@
     volumes:
       - "/mailu/certs:/certs"
       - "/mailu/overrides/nginx:/overrides:ro"
+      - "/mailu/proxy.conf:/dovecot_conf/proxy.conf:ro"
     depends_on:
       - resolver
     dns:
```

and then restart front container:
```
docker compose restart front
```

**Comment by nextgens** [comment]
My understanding is that it's `client_limit` that you want to raise; `process_limit` should match the number of CPUs

**Comment by xvalen** [comment]
Actually not. There are two modes ([documentation](https://doc.dovecot.org/2.3/admin_manual/login_processes/))

1) High-security mode (default)
    - defined by service_count = 1
    - for each login attempt is forked new imap-login process which handle it
    - number of available logged in users at the same time is set by process_limit (default 100)
2) High-performance 
    - defined by service_count = 0
    - one imap-login process can handle up to client_limit (default 1000), so number of logged in imap users = process_limit * client_limit

It would be nice to have override option available for dovecot running in front container which handles authentication, but question is where should be placed?
 - overrides/dovecot/proxy.conf (bind mounted by imap and front container)
 -  or overrides/nginx/dovecot.conf (better but confusing)
 -  or overrides/proxy/proxy.conf (probably needed to make new release of mailu and describe override directory creation in upgrade guide)

Here is attached stripped output of `doveconf -a -c /etc/dovecot/proxy.conf` from inside of front container:

```
service {
  chroot = login
  client_limit = 0
  drop_priv_before_exec = no
  executable = imap-login
  extra_groups = 
  group = 
  idle_kill = 0
  inet_listener {
    address = 
    haproxy = no
    port = 10143
    reuse_port = no
    ssl = no
    name = imap-webmail
  }
  inet_listener {
    address = 
    haproxy = no
    port = 0
    reuse_port = no
    ssl = no
    name = imap
  }
  inet_listener {
    address = 
    haproxy = no
    port = 993
    reuse_port = no
    ssl = yes
    name = imaps
  }
  privileged_group = 
  process_limit = 200
  process_min_avail = 0
  protocol = imap
  service_count = 1
  type = login
  user = $default_login_user
  vsz_limit = 18446744073709551615 B
  name = imap-login
}
```
It's running in High security mode (service_count = 1) and only difference between this and default mailu is added line (process_limit = 200).

I hope it's more clear now.

**Comment by nextgens** [comment]
Yes thank you.

https://doc.dovecot.org/2.3/configuration_manual/proxy_settings/ says that we should enable 'high performance' mode on the proxy ... so that's what we will do.

The outstanding question is what to do on the imap container... since presumably we will hit a bottleneck there too when the above is done.

I'll ask on #mailu-dev and see if we can reach a consensus.

**Comment by nextgens** [comment]
@xvalen what about what's on #3463  ?

Once the images are built you can test using:
```
export MAILU_VERSION=pr-3463
docker compose pull
docker compose up -d
```

**Comment by xvalen** [comment]
Thank you, I can test new images in the evening.

From my point of view it is not necessary to switch everything to performance mode. I think this should be enough:
```
core/nginx/dovecot/proxy.conf
185 + 
186 + !include_try /overrides/dovecot.conf
```

I don't see anywhere in the documentation https://doc.dovecot.org/2.3/configuration_manual/proxy_settings/  that it is strictly required to set imap-login and pop3-login to performance mode. I understand this more as an example or maybe a recommendation assuming there will be thousands of connections.

**Comment by nextgens** [comment]
It's not strictly required... but spawning two processes (one on the proxy and one on the backend) for each connection is probably overkill.

My concern is DoS attacks: regardless of what the limit is, if we keep the high security mode it's trivial to hit.

FYI, I have changed the path, it's now ``/overrides/dovecot/proxy.conf``
