### ISSUE TITLE
No folders after upgrade to 2024.06.17

### ISSUE THREAD

**Issue by nazar-pc** [Mailu/Mailu#3467]
## Environment & Version

- Version: `2024.06`

## Description

I have following override in `overrides/dovecot/dovecot.conf`:
```
mail_location = maildir:/mail/%u:UTF-8:LAYOUT=fs
```

After upgrading to 2024.06.17 from what I believe was 2024.06.14 dovecot doesn't see directories anymore. I tried to roll back to 2024.06.14 without success.

Tried following command from upgrade guide to trigger reindexing without any effect:
```
docker compose exec imap doveadm user '*'|while read u; do echo "re-indexing $u";docker compose exec -T imap doveadm index -u $u '*'; done
```

Likely caused by https://github.com/Mailu/Mailu/pull/3463 that touched related configuration code.

## Logs

There are no errors or anything suspicious in logs.

**Comment by nazar-pc** [comment]
@nextgens thanks for quick fix!
Any suggestion on how do I recover my broken dovecot folder structure now (others affected might benefit from this as well)?

**Comment by nextgens** [comment]
Restore the backup you took before upgrading?
otherwise find -[cm]time ...

**Comment by nazar-pc** [comment]
Specifically after upgrading some (not all) directories are back, but they are messed up as if override is not applied :thinking:

**Comment by nazar-pc** [comment]
Interesting, after reindexing and a few more restarts directories are back, but unsubscribed, so that is an easy fix. Thanks again!
