### ISSUE TITLE
Add Relay Servers

### ISSUE THREAD

**Issue by rageOS** [Mailu/Mailu#348]
There should be the possibility to add server IPs for relaying.
Those IPs should be not checked against SPF, SPAM, URIBL etc. and all mails should be relayed.

This is usefull for acting as a smarthost for other servers.

**Comment by kaiyou** [comment]
That's actually the purpose of ``RELAY_HOSTS`` in the configuration, which is not yet managed through the Web ui

**Comment by kaiyou** [comment]
Closing, as this is too vague as is
