### ISSUE TITLE
RSA cert type is ecdsa

### ISSUE THREAD

**Issue by chanrray** [Mailu/Mailu#3531]
Hi,my mailu docker image tag is 2024.06
I deleted /certs/letsencrypt folder and restart mailu,mailu certbot will Apply for a  rsa certificate and a ecdsa certificate:
rsa cert in mailu/ and edcsa cert in mailu-ecdsa/.but the mailu/cert.pem shows edcsa type.
Then I check letsencrypt.py command = [
    "certbot",
    "-n", "--agree-tos", # non-interactive
    "-d", hostnames, "--expand", "--allow-subset-of-names",
    "-m", "{}@{}".format(os.environ["POSTMASTER"], os.environ["DOMAIN"]),
    "certonly", "--standalone",
    "--cert-name", "mailu",
    "--preferred-challenges", "http", "--http-01-port", "8008",
    "--keep-until-expiring",
    "--allow-subset-of-names",
    "--renew-with-new-domains",
    "--config-dir", "/certs/letsencrypt",
    "--post-hook", "/config.py"
]
does not define key-type and should be default rsa.While I find out renew/mailu.config has key_type = ecdsa,why?

cat ../../letsencrypt/renewal/mailu.conf
# renew_before_expiry = 30 days
version = 2.10.0
archive_dir = /certs/letsencrypt/archive/mailu
cert = /certs/letsencrypt/live/mailu/cert.pem
privkey = /certs/letsencrypt/live/mailu/privkey.pem
chain = /certs/letsencrypt/live/mailu/chain.pem
fullchain = /certs/letsencrypt/live/mailu/fullchain.pem

# Options used in the renewal process
[renewalparams]
allow_subset_of_names = True
account = 1fcd7fd4b6a2838dd3caba7eb54a5aad
http01_port = 8008
pref_challs = http-01,
post_hook = /config.py
config_dir = /certs/letsencrypt
authenticator = standalone
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa

cat ../../letsencrypt/renewal/mailu-ecdsa.conf
# renew_before_expiry = 30 days
version = 2.10.0
archive_dir = /certs/letsencrypt/archive/mailu-ecdsa
cert = /certs/letsencrypt/live/mailu-ecdsa/cert.pem
privkey = /certs/letsencrypt/live/mailu-ecdsa/privkey.pem
chain = /certs/letsencrypt/live/mailu-ecdsa/chain.pem
fullchain = /certs/letsencrypt/live/mailu-ecdsa/fullchain.pem

# Options used in the renewal process
[renewalparams]
allow_subset_of_names = True
account = 1fcd7fd4b6a2838dd3caba7eb54a5aad
http01_port = 8008
key_type = ecdsa
pref_challs = http-01,
post_hook = /config.py
config_dir = /certs/letsencrypt
authenticator = standalone
server = https://acme-v02.api.letsencrypt.org/directory

**Comment by nextgens** [comment]
Indeed, it looks like the default behavior of certbot has changed... we need to decide whether we keep both keytypes and fix that... or just keep ECC certs going forward
