### ISSUE TITLE
Adding Elestio as deployment option

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [Mailu/Mailu#3532]
Hey team,
I am Kaiwalya, Developer Advocate at Elestio. Elestio has been providing options of fully deploying and managing Mailu application as shown [here](https://elest.io/open-source/mailu). I think it would be a great idea if we can add it to official readme/documentation here.
🔔 In addition to this, if you are interested we provide partnership opportunities with tools we support by **revenue share** upon addition of this method in docs. If you would like to collaborate, just shoot me an email at [kaiwalya@elest.io](mailto:kaiwalya@elest.io) :)

**Comment by WebSpider** [comment]
This looks like a promotional item to me. Does this belong in the Mailu repository?

**Comment by nextgens** [comment]
> I think it would be a great idea if we can add it to official readme/documentation here.

You are not explaining why it would be a **great** idea.

> In addition to this, if you are interested ... upon addition of this method in docs

I do not speak for the project but I do not think we are. @Diman0 is that something we should consider?

**Comment by kaiwalyakoparkar** [comment]
Hey @nextgens, we feel it's a good idea because we have thousands of users using our services and many users like hosting Mailu on Elestio because of it's ease of management, upgrades, maintenance etc. So, I think if mailu readme is able to provide it's users with an option to use mailu without worrying about installations and stuff then it could add great value to its users. And whatever Elestio befits from it we share 30% of profits back to the project. So a collaborative addition to readme that benefits users sounds like good idea.

Also, regarding the misleading sentence `Elestio supports Mailu by providing revenue share`
in the PR. How we usually plan this is that maintainers merge the pull request after the partnership has been established making the statement I add their true and motivating users that they can actually support the project they use while saving their own efforts and time. 

Hope that answers the questions above (and in pr), happy to help if you want more information about anything :)
