### ISSUE TITLE
Add Lets Encrypt management for local domains

### ISSUE THREAD

**Issue by ripkens** [Mailu/Mailu#355]
After creating local domains, the admin should have the possibility to create Lets Encrypt certificates for A Records pointing to the mailu server.

Example:

Admin adds 5 domains to local domain table with mailboxes.
The clients use mail.domain.tld in their mail clients to access ther mailboxes or webmail.

In the domain settings, there should be a SAN field to enter subdomains to inlude in certificate creation for nginx.

Alternatively, a setting in the global settings to set SAN subdomains to include for all local domains.
During certificate creation, there should be dns lookups to make sure the subdomain points to mailu server, if not, do not inlude and check back later.

**Comment by kaiyou** [comment]
There already is a setting in global settings for this. It is named ``HOSTNAMES``. Domain check is actually preformed by letsencrypt when generating the certificate.

**Comment by ripkens** [comment]
I was thinking of a setting in the webinterface.
The people managing the domains not neccessarely have access to the config and not bale to update containers

**Comment by kaiyou** [comment]
So you mean being able to set some sort of "access hostname" per domain, that would be the hostname provided to the user in the configuration examples, and that could be included in letsencrypt.

The big question then is: should people who manage the domains be able to interfere with what hostnames are served on the server and what certificates are generated?

**Comment by kaiyou** [comment]
This is very probably never going to be implemented in the web ui since it is to tightly related to the platform.
