### ISSUE TITLE
Show Postfix / rSpamd logs in webinterface (Domain details)

### ISSUE THREAD

**Issue by ripkens** [Mailu/Mailu#357]
For admins, it would be good to see a list of postfix / rSpamd logfile lines (searchable with date/time filters) in the domain details for a local domain.

Clients call to ask why a specific mail did not get through the filters. So a searchable list would be a good tool for that.

MailCleaner has that as a main Feature called "Tracing"

**Comment by kaiyou** [comment]
There are two things here: some traces about what was filtered and why, and accessing technical logs. Technical logs are outside the scope of Mailu, they are handled by Docker and it should remain so.

What we could try though is documenting how to centralize these logs properly and some configuration files and patterns for log management toolkints (ELK, Splunk, Graylog).

**Comment by kaiyou** [comment]
We have taken a pretty different direction since. Closing here.

**Comment by Joeasaurus** [comment]
What was the direction? I have something like what sendgrid will display to me in mind.
