### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by gregf** [Mailu/Mailu#359]
Can someone explain to me how to test changes I make? I'm not super familiar with docker and I have some changes I would like to make but don't want to open any more pull requests without being able to test what I do. I would be willing to turn this issue into some documentation around it, if someone can just point me in the right direction.

**Comment by morbidick** [comment]
I'm not very fluent with docker myself. I booted a VM with docker.io and docker-compose installed. And there i used the docker-compose file with `cd docs/compose && docker-compose -f docker-compose.yml up`. To rebuild containers that i modified i replaced the corresponding `image: mailu/servicename:$VERSION` with `build: ../../core/servicename` and ran the previous command with the `--build` flag.

**Comment by kaiyou** [comment]
I'll try and write something more elaborate in the documentation :)

**Comment by kaiyou** [comment]
There you go: https://mailu.io/master/contributors/environment.html

**Comment by gregf** [comment]
Thanks!
