### ISSUE TITLE
RELAYNETS behavior

### ISSUE THREAD

**Issue by rgarrigue** [Mailu/Mailu#360]
Hello

I'ld like to know if the comma separated list is valid

    RELAYNETS=172.16.0.0/12,10.0.0.0/8,192.168.0.0/16

By the way, this example list is RFC1918, aka "all local network". Maybe this should be the default. Fact is, my Docker Swarm's overlay network is in the 10 range, not the 172.

And very nice jobs putting this mailu together, I'll definitively put it to works.

Regards,

**Comment by kaiyou** [comment]
The list is space separated, but it should work as you describe :)
