### ISSUE TITLE
rmilter deprecation from rspamd 1.6+

### ISSUE THREAD

**Issue by rgarrigue** [Mailu/Mailu#361]
Hi

I was wondering what rmilter is about, and https://rspamd.com/rmilter/ states RMILTER IS OBSOLETED SINCE RSPAMD 1.6. 

And mailu/rspamd:latest ship rspamd 1.6.

```
➜  ~ docker run -ti mailu/rspamd ash 
/ # apk version rspamd
WARNING: Ignoring APKINDEX.066df28d.tar.gz: No such file or directory
WARNING: Ignoring APKINDEX.b53994b4.tar.gz: No such file or directory
Installed:                                Available:
rspamd-1.6.5-r1        
```

Maybe you can save a docker now :-)

Regards,

**Comment by kaiyou** [comment]
Well, rmilter is not part of Mailu anymore actually, see https://github.com/Mailu/Mailu/commit/08b567e3d93b48442e451142c6d809f33830e4ee.

**Comment by rgarrigue** [comment]
Hell, I found out about Mailu less than a month ago. I dunno how I got the
docker-compose with rmilter... My bad, sorry about this.

-- 
Rémy GARRIGUE
