### ISSUE TITLE
All attachments are zero sized on forward

### ISSUE THREAD

**Issue by ebrahim** [Mailu/Mailu#365]
All attachments of an email are zero sized when I try to forward the email in RoundCube webmail. I get this error in /var/www/html/logs/errors on Mailu 1.5:

`PHP Error: abc@def.ghi can't read /tmp/rcmAttmnt0DXphm (not in temp_dir) in /var/www/html/plugins/filesystem_attachments/filesystem_attachments.php on line 216`

**Comment by kaiyou** [comment]
This might be related to the zip extension, will try once that is fixed.

**Comment by senilio** [comment]
Sending a new email with attachments from Roundcube is also broken (1.5.1). Probably related to this issue.

Email gets delivered OK, but attachments aren't sent.

**Comment by kaiyou** [comment]
This  was fixed both on master and 1.5
