### ISSUE TITLE
Internal Server Error when i try to save the modifications in: admin/user/settings Page.

### ISSUE THREAD

**Issue by murdantix** [Mailu/Mailu#3667]
Hello,

I have posted my Issue in: https://github.com/Mailu/Mailu/discussions/3665

i am using the version of heviat with OpenID Connect. The .env file looks like:

- DOCKER_ORG=ghcr.io/heviat
- MAILU_VERSION=master

I hope that someone can help me, i am testing Mailu to move from Zimbra.

**Comment by nextgens** [comment]
You use a fork, go get support there.

Unless you can reproduce the issue with a supported version of our code, we are just not interested.
