### ISSUE TITLE
Synchronize Mailu aliases with Roundcube identities

### ISSUE THREAD

**Issue by aminb** [Mailu/Mailu#367]
Mailu [used to](https://github.com/Mailu/Mailu/commit/8bf14dac87468ddc325c6bf7c9e62cbc1d40e037#diff-e8ccb084d968d3be8df04febf07d902cR8) allow adding identities in Roundcube but was disabled shortly after by setting `$config['identities_level'] = 3` (see [`identities_level` docs](https://github.com/roundcube/roundcubemail/wiki/Configuration#restricting-sender-identities)).

I propose we set `$config['identities_level'] = 1` and extend Mailu's alias configuration to create or delete a corresponding Roundcube identity as well. This way, users won't be able to create arbitrary identities that would let them send email as anyone on the domain, but when the admin creates an alias for the user in the admin interface, a Roundcube identity with the same name will be created for the user, which they can edit (except the identity's email address).

**Comment by kaiyou** [comment]
Unfortunately, Roundcube does not have and API or the ability to access any API to list identities or update identities. And I would really like to avoid updating the Rouncube database from the admin container.

I actually could be okay with simply setting ``$config['identities_level']`` to ``1`` as long as we check that the user is not able to impersonate anywone (which should not be the case on Mailu 1.5).

**Comment by aminb** [comment]
Sounds good; let's give that a shot then.

**Comment by kaiyou** [comment]
Any news about testing this?

**Comment by aminb** [comment]
Sorry I've been completely swamped by school work this semester, and haven't had a chance to try this out.

Any chance you could test it on your end?

**Comment by kaiyou** [comment]
Very little chance I will find the time in the next couple of days/weeks as I am already overwhelmed with the daily issues in Mailu.

**Comment by aminb** [comment]
Ok I finally got around to testing this tonight on my server running `master`.

I had to set `$config['identities_level'] = 0` in order to be able to create new identities with a different email address.

When trying to send from user `u1` to user `u3` with alias corresponding to another registered user (or alias) `u2`, roundcube shows the following error:

```
SMTP Error (553): Failed to add recipient "u3@aminb.org" (5.7.1 <u2@aminb.org>: Sender address rejected: not owned by user u1@aminb.org).
```

And when trying to send as a non-existing user (or non-registered alias) `u4`:

```
SMTP Error (550): Failed to add recipient "u3@aminb.org" (5.1.0 <u4@aminb.org>: Sender address rejected: User unknown in virtual mailbox table).
```

From that, it seems to me that Mailu indeed only allows sending as the current user or one of its registered aliases.

Feel free to test with more cases, but I think setting `$config['identities_level'] = 0` should be safe.

/cc @kaiyou @muhlemmer

**Comment by aminb** [comment]
ping? @muhlemmer @kaiyou

**Comment by muhlemmer** [comment]
Cc @ionutfilip

On 3 January 2019 22:02:42 EET, Amin Bandali <notifications@github.com> wrote:
>ping? @muhlemmer @kaiyou
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/Mailu/Mailu/issues/367#issuecomment-451260350

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
