### ISSUE TITLE
No incoming emails in Mailu

### ISSUE THREAD

**Issue by m0nhawk** [Mailu/Mailu#370]
I'm unable to receive emails on my installation of Mailu.

I can successfully send emails with proper DKIM & SPF and they successfully received (I've tested on Gmail, Outlook and work emails).

But when replying, nothing received in Mailu. `fetchmail` log is empty. There is also no bounce back.

How can I troubleshoot and fix this?

PS: I'm using a dedicated server from Hetzner.

**Comment by m0nhawk** [comment]
I have wrong `BIND_ADDRESS4` configuration. I've fixed everything.

**Comment by laserg** [comment]
@m0nhawk, hi.
 I have completely the same case.
Could you share how did you fix it in more detail.
