### ISSUE TITLE
Request Entity Too Large

### ISSUE THREAD

**Issue by mamdoohi** [Mailu/Mailu#371]
hi,
i have a question.
how to attach file above 1M in Mailu ? :)
Thanks.

**Comment by kaiyou** [comment]
You should actually be able to. Which version and which Webmail are you using?

**Comment by mamdoohi** [comment]
Version: 1.10.3.151

**Comment by kaiyou** [comment]
Sorry for the delays, but I meant what version of Mailu (1.4, 1.5 ?) and which Webmail (Roundcube, Rainloop) ?

**Comment by mamdoohi** [comment]
i use rainloop. but i can't find mailu version. i use from docker since 2017-09-02

**Comment by kaiyou** [comment]
Okay, I was able to reproduce the issue, looking at it right now.

**Comment by kaiyou** [comment]
Just pushed a fix to ``master``, I will backport it to stable once approved on the test server.

**Comment by mamdoohi** [comment]
Thanks a lot man :)

**Comment by kaiyou** [comment]
Sorry for the delay, you could simply use ``master`` temporarily for your frontend image, but it looks like you are using Mailu 1.4, aren't you? The version is specified in your ``.env``.

**Comment by kaiyou** [comment]
This was cherry-picked in stable.
