### ISSUE TITLE
Ports config in docker-compose.yml and admin ui url

### ISSUE THREAD

**Issue by GaetanVenuat** [Mailu/Mailu#372]
Hi,
I think i found a small bug with your admin ui.
When i try to use this port set up (because i will need my port 80)

front:
    image: mailu/nginx:$VERSION
    restart: always
    env_file: .env
    ports:
    - "$BIND_ADDRESS4:11223:80"
    - "$BIND_ADDRESS4:11224:443"
    - "$BIND_ADDRESS4:110:110" ...

The web mail seems work perfectly, but not all pages of admin ui.
The port is not pass in somes urls.

For example 
:11224/admin -> not working, redirect to /admin/ui
:11224/admin/iu -> not working, redirect to /login?next=ui.index 
:11224/login?next=ui.index -> working well

After somes searchs, i found this https://github.com/pallets/flask/issues/824
Maybe a problem with "url_for" in Mailu/core/admin/mailu/__init__.py ?

**Comment by kaiyou** [comment]
This is interesting as I did run the admin interface on a custom port once without facing the issue. Thank you for reporting, I will look into it.
