### ISSUE TITLE
New clamav version available (fixes vulnerabilities) 

### ISSUE THREAD

**Issue by hoellen** [Mailu/Mailu#374]
There is a new clamav version 0.99.3 available, which fixes many critical vulnerabilities (see [blog](http://blog.clamav.net/2018/01/clamav-0993-has-been-released.html)). 

Please update the container asap on docker hub. Alpine [haven't updated](https://bugs.alpinelinux.org/issues/8423), yet.

greetings
hoellen

**Comment by kaiyou** [comment]
This will be updated today. Thank you for reporting as i was not following much about ClamAV

**Comment by kaiyou** [comment]
Quick update : this is still not fixed though I hope it will be this week. The patch is sent to the Alpine review team and is currently in patchwork: http://patchwork.alpinelinux.org/patch/3847/

**Comment by kaiyou** [comment]
The update was merged yesterday in Alpine and the new clamav image should be available now.

**Comment by hoellen** [comment]
They updated the clamav package only in the `edge` branch. Maybe we should move the antivirus container to edge branch for short time. Or build clamav 0.99.3 by ourselve?
