### ISSUE TITLE
Non-user email forwarding

### ISSUE THREAD

**Issue by spoulson** [Mailu/Mailu#383]
I'm evaluating Mailu as a replacement for an old server.  So far it's slick and easy to setup.  But so far I have not been able to locate a way to define email forwards that are not user based.

I want to setup email forwards for some common addresses like: "admin@example.com", "domainadmin@example.com", "webmaster@example.com", and have them all forward to a central email account that may or may not reside on the Mailu server.

**Comment by hoellen** [comment]
You can create aliases in the admin panel. I think that is what you‘re looking for.

**Comment by spoulson** [comment]
No, aliases can only be forwarded to a local account.

I run several sites where there's "contact us" email addresses that forwards to everyone on the organization's board, and their email is managed on different systems.

**Comment by gregf** [comment]
recently been looking for this functionality myself. I think it would be a good one to have.

**Comment by hoellen** [comment]
Maybe I misunderstand you, but I have in my setup the following alias 
`alias@mydomain.com  => anotheraccount@gmail.com`
And this works just fine.

**Comment by spoulson** [comment]
My mistake, I didn't fully test before posting.

Yes, I can create aliases of arbitrary addresses on my hosted mail domain and specify 1 or more target email addresses.

However, what I didn't explain properly is that email is not actually going out to the external email addresses.  The aliases only work if the destination is local.

I'll create a new ticket with a proper description.

**Comment by spoulson** [comment]
#384
