### ISSUE TITLE
environment variable of EXPOSE_ADMIN may not be properly set

### ISSUE THREAD

**Issue by chxzqw** [Mailu/Mailu#389]
While in .env there is 'expose the admin interface'
![mailu1](https://user-images.githubusercontent.com/2109330/36460411-4bfbb3de-170c-11e8-8a16-a9103530b453.jpg)
where the value goes to the container and read by nginx via EXPOSE_ADMIN but results in
![mailu2](https://user-images.githubusercontent.com/2109330/36460436-6cf74da0-170c-11e8-82ad-dbbb9d292311.jpg)
so the value 'true' here may not be read properly, which is expected to be a 'yes'.
Thus I got 403 error while accessing /admin:
![mailu3](https://user-images.githubusercontent.com/2109330/36460502-c4d78fda-170c-11e8-9829-2a116f95acdc.jpg)

FYI I tried a workaround of adding following lines in .env:
```
environment:
  EXPOSE_ADMIN: 'yes'
```

which then works fine.

The 'webmail' part works just perfect.

**Comment by bernhardberger** [comment]
I can confirm that the variable is either missing or misspelled in the .env template.

**Comment by chxzqw** [comment]
I just did a fresh download of .env file from the link referred by https://mailu.io/master/_downloads/.env mentioned on https://mailu.io/master/compose/setup.html, which still shows
```
# Expose the admin interface (value: true, false)
ADMIN=false
```
I guess it may need to go with
```
# Expose the admin interface (value: yes, no)
EXPOSE_ADMIN=yes
```

**Comment by kaiyou** [comment]
I believe you are using `1.4` images with the latest `.env`. The front container definitely looks for the `ADMIN` environment variables since `1.5`: https://github.com/Mailu/Mailu/blob/91bb76ecd3ea0d88bf9b371fcc549777704ce9e0/core/nginx/conf/nginx.conf#L86

**Comment by chxzqw** [comment]
@kaiyou thanks for your information. Yep I am using the label 'stable' currently which is about 1.4 months ago on docker hub. I am sure it was from https://mailu.io/compose/setup.html somewhere which is now updated.

In the latest .env from the above link, it shows:
`VERSION=1.5.1`

while the docker hub tags tab shows:
![image](https://user-images.githubusercontent.com/2109330/37007151-1042bb0c-2130-11e8-9048-334e4555c8be.png)

So can you please let me know that which label should I use when I pull the image from docker hub? Currently it has got 'master', 'latest' and other version numbers and looks like 1.5 is newer than 1.5.1 ?
Manually changing version in .env may reduce maintainability.

**Comment by kaiyou** [comment]
Okay, I definitely need to tidy these repositories. Like a lot. The current version is ``1.5`` and should be used unless you wish to go unstable and use ``latest``.

**Comment by chxzqw** [comment]
Thanks mate I am gonna go with the `latest` which might be the most default one in Docker world and also I don't need to manually adjust the version number in `.env` in future.
