### ISSUE TITLE
Can't send from an email account that has forwarding

### ISSUE THREAD

**Issue by AdvancedStyle** [Mailu/Mailu#390]
I've setup an email account (for example  "myname@example.com").

I then turn on forwarding so that all emails to "myname@example.com" will be forwarded to "mygmail@gmail.com".

However when doing this I can no longer send emails from "myname@example.com", when doing (either via SMTP directly or roundcube) I get error such as:

> An error occurred while sending mail. The mail server responded:  
> 5.7.1 <myname@example.com>: Sender address rejected: not owned by user myname@example.com.
>  Please check the message recipient "someoneelse@yahoo.com" and try again.

**Comment by kaiyou** [comment]
Sorry for the delay. Indeed the sender restrictions will cause an issue with this. For the time being, try checking the box "keep a local copy".
The reasoning is: if your sender address does not have your username as destination, it is rejected. So keeping a local copy will make your local user a recipient of the messages and thus temporarily fix the issue.

I have to think about a long term fix, which will not be easy.

**Comment by kaiyou** [comment]
This can finally be fixed once we implement #420. Then we can finally specify any behavior for allowing impersonation, I will start with fixing the current ux.
