### ISSUE TITLE
Roundcube Enigma

### ISSUE THREAD

**Issue by AdvancedStyle** [Mailu/Mailu#391]
How would I go about enabling the "enigma" plugin for roundcube, in order to support PGP keys?

Should be able to just add "enigma" to the plugin list here i think:
https://github.com/Mailu/Mailu/blob/master/webmails/roundcube/config.inc.php#L13

But i'm not very familiar with docker, so not sure how to deploy with the edited config.

**Comment by kaiyou** [comment]
It should be pretty straightforward to enable indeed, just have to test it as I am not sure how it integrates with Roundcube.

**Comment by AdvancedStyle** [comment]
Enigma is working but I'm having one issue where sending a message it does not encrypt using your own pub key (so you can't read mail in the sent folder unless you CC the message to yourself).

The roundcube guys say Engima should already do this, but I'm not sure how to debug the issue seeing as Mailu is dockerize (not familiar with docker myself): https://github.com/roundcube/roundcubemail/issues/6210

Any tips on how to turned on enigma_debug inside the docker container?
