### ISSUE TITLE
EXPOSE ports in dockerfiles

### ISSUE THREAD

**Issue by wsy** [Mailu/Mailu#392]
Can you please include EXPOSE command in each Dockerfile so that I can know which port to open for each container when deploying manually.

**Comment by CptTZ** [comment]
I think the `dokcer-compose.yml` file (Download from: <https://mailu.io/_downloads/docker-compose.yml>) has already provided everything.

`front` expose all ports to public in this system.

```
    ports:
    - "$BIND_ADDRESS4:80:80"
    - "$BIND_ADDRESS4:443:443"
    - "$BIND_ADDRESS4:110:110"
    - "$BIND_ADDRESS4:143:143"
    - "$BIND_ADDRESS4:993:993"
    - "$BIND_ADDRESS4:995:995"
    - "$BIND_ADDRESS4:25:25"
    - "$BIND_ADDRESS4:465:465"
    - "$BIND_ADDRESS4:587:587"
    - "$BIND_ADDRESS6:80:80"
    - "$BIND_ADDRESS6:443:443"
    - "$BIND_ADDRESS6:110:110"
    - "$BIND_ADDRESS6:143:143"
    - "$BIND_ADDRESS6:993:993"
    - "$BIND_ADDRESS6:995:995"
    - "$BIND_ADDRESS6:25:25"
    - "$BIND_ADDRESS6:465:465"
    - "$BIND_ADDRESS6:587:587"
```

**Comment by wsy** [comment]
Thanks for your reply.

I know the service 'front' uses those ports you mentioned above and I know it's actually running nginx service.
Thus, when I access webmail through front, nginx tries to forward my HTTP request to rainloop's 80/tcp port.
What if I did not expose port 80/tcp of rainloop container? In this case, nginx wouldn't be able to forward my request to rainloop and how can I access webmail?

In this perticular case, of course I know I need to open port 80/tcp on rainloop container since it provides web service.
But how about antivirus service? How about Fetchmail service? What ports shall I open for them?

**Comment by CptTZ** [comment]
Take a look at files here: <https://github.com/Mailu/Mailu/tree/master/services/rspamd/conf>. Everything is in the source, or configuration files.

Some examples:

- Antvirus: 3310
- antispam: 11334

And so on.

However I can't see why you want to deploy Mailu in this way, as you have to change a lot of cinfigurations.

**Comment by kaiyou** [comment]
You are right, Dockerfiles should have exposed ports, marking this as an enhancement for the next versoin. Feel free to PR if you build your own list of ports :)
