### ISSUE TITLE
docs: setup still says stable is default

### ISSUE THREAD

**Issue by jcgruenhage** [Mailu/Mailu#393]
https://mailu.io/setup.html still claims that stable is the default version. I therefore changed my VERSION in .env to stable, only realising waaaay later during debugging that stable hasn't been updated in 5 months.

**Comment by Waester** [comment]
Usage of versions such as stable has been deprecated. You can find more info here.
https://mailu.io/releases.html

**Comment by jcgruenhage** [comment]
Yeah I know, this issue is about the docs still claiming stabile to be the default in the page I linkes above.

**Comment by kaiyou** [comment]
Damn, will fix :)
