### ISSUE TITLE
Can't send/receive emails probably due to incorrect milter settings in postfix

### ISSUE THREAD

**Issue by chxzqw** [Mailu/Mailu#394]
Hi I got issues when I send/receive emails to the newly built mail server.

I got following error message via `docker logs mailu_smtp_conatiner`:

![image](https://user-images.githubusercontent.com/2109330/36728085-aad9ae36-1c13-11e8-90fd-d270565fd3dd.png)

Then I grab the result of `postconf -n` from `docker exec -it mailu_smtp_container /bin/sh/` and got the following configuration settings which relates to above information:

![image](https://user-images.githubusercontent.com/2109330/36728234-313a8a72-1c14-11e8-95cc-dfb72de7a557.png)

So it looks like there should be some container named "milter" which listens on port 9900 to deal with incoming emails ? I find relative information neither in docker-compose.yml nor in online docs. Do I need to manually change postfix conf or just miss something here ? Help please.

Update:
Now I have just confirmed the `smtpd_milters` setting is the cause. Since I let it to be empty in postfix.cf which overrides the container's, email sending and receiving works fine. Spf and dmarc pass and dkim is failed though.

**Comment by kaiyou** [comment]
This sounds like a version mismatch between your images and your Compose file, what version are you using?

**Comment by chxzqw** [comment]
The error is gone since I pull the latest image. Cheers.

**Comment by gomin1d** [comment]
@chxzqw +1

Same. I also decided to disable rspamd by specifying the option:
```
          postfix:
            overrides:
              postfix.cf: |
                smtpd_milters =
```

And this resulted in DKIM not working. 

Did you find a way to disable rspamd but keep DRIM working?
