### ISSUE TITLE
Certificate renewal needs restart when TLS_FLAVOR=mail

### ISSUE THREAD

**Issue by xtianus** [Mailu/Mailu#395]
I have a setup with TLS_FLAVOR=mail, so the certificate is renewed outside mailu with certbot.
It is then copied to the /mailu/certs/ folder.
It seems that the new version is not picked up unless I issue a 

    docker-compose down && docker-compose up -d

**Comment by kaiyou** [comment]
Doesn't ``docker-compose restart smtp imap`` work?

**Comment by xtianus** [comment]
Well, it probably does. My point was that I expected it to load the new certificate automatically.
If the proper way of updating a certificate is to issue a restart, then there's no bug.
A line in the docs would help maybe.

**Comment by kaiyou** [comment]
It is indeed an expected behavior: it is the responsibiliy of whoever write a new certificate to restart services so it is taken into account. Most TLS-enabled services work that way anyway. I can add a line to the documentation I guess :)

**Comment by Waester** [comment]
@kaiyou I would like to confirm.

The correct command is `docker-compose restart front`, or am I wrong? As you use reverse proxy to manage all the connections and certificate.

**Comment by kaiyou** [comment]
You are right, my mistake :)
