### ISSUE TITLE
This Docker container doesn't works for me...

### ISSUE THREAD

**Issue by pirmax** [Mailu/Mailu#404]
I have a fresh installation of Debian 9 and I have installed this docker container.

But, when I access to my domain, the page doesn't start : ERR_CONNECTION_REFUSED

Could you help me please?

**Comment by OrkhanAlikhanov** [comment]
Check your firewall to see if the required ports are allowed.

**Comment by CptTZ** [comment]
It's probably generating a private key, which may take a long time. During that period of time, the whole system may be inaccessible.

**Comment by OrkhanAlikhanov** [comment]
I agree with @CptTZ. Same happened to me as well, I immediately checked the logs and saw a note from OpenSSL, saying `Generating DH parameters, 4096 bit long safe prime, generator 2 This is going to take a long time`

**Comment by Greek64** [comment]
Can confirm.
On mailu 1.5, the front container regenerates the DH parameters each time the container is restarted.
On my system that took around 1h30m, during which the whole mailu system was unavailable.
I always followed the DH parameter generation with top/htop, so I know when it's ready.

On the master branch this has been "fixed", as the front container no longer regenerates the costly DH parameters, and uses the existing ones.
