### ISSUE TITLE
[antivirus] clamav 0.99.4 is available

### ISSUE THREAD

**Issue by hoellen** [Mailu/Mailu#407]
There is an update for clamav (0.99.4) which [fix multiple vulnerable bugs](blog.clamav.net/2018/03/clamav-0994-has-been-released.html). 
As in [#374](https://github.com/Mailu/Mailu/issues/374#issuecomment-365198726) mentioned, Alpine Linux only update the clamav package in the `edge` branch. Maybe we should move the antivirus container to this branch?
I use it for a while and it works fine.

**Comment by kaiyou** [comment]
Agreed, I'll see that we change this tonight :)

**Comment by kaiyou** [comment]
This is pushed to master.

**Comment by kaiyou** [comment]
Backported to 1.5, closing the issue.

**Comment by hoellen** [comment]
Thanks!
