### ISSUE TITLE
Demo isn’t working 

### ISSUE THREAD

**Issue by proea** [Mailu/Mailu#408]
Hi, demo creditnails from https://mailu.io/master/demo.html are wrong

**Comment by proea** [comment]
The problem exists 2 days

**Comment by kaiyou** [comment]
Sorry, the demo is now restarted manually, so juts poke me when you need it to be reset. It should be fine now :)

**Comment by proea** [comment]
yes) Thanks!

**Comment by dawoodjee** [comment]
> just poke me when you need it to be reset

Can you please reset again
