### ISSUE TITLE
SSL protocol error roundcube/imap

### ISSUE THREAD

**Issue by willydee** [Mailu/Mailu#411]
## Steps to reproduce
* Set up a recent Debian 9.3 server
* Download `docker-compose.yml` and `.env` for `master`
* Configure `.env`
* Launch the compose project
* Create a user mail account
* Navigate to the webmail URL and try to log in

## Expected result
Login should succeed

## What happens instead
`⚠ Connection to storage server failed.`

## Log entries
```
imap_1       | Mar 14 09:15:02 imap-login: Fatal: Unknown ssl_protocols setting: Unrecognized protocol 'SSLv2'
imap_1       | Mar 14 09:15:02 master: Error: service(imap-login): command startup failed, throttling for 4 secs
```

According to `/webmails/roundcube/config.inc.php`, SSL should not be used at all for access to internal containers.

**Comment by kaiyou** [comment]
Should now be fixed thanks to the fix by @adi90x

**Comment by willydee** [comment]
Just pulled the master images, and problem is gone. Thanks @adi90x :+1:

**Comment by Gaurav7005** [comment]
What kind of changes I need to do to solve this, as I am a beginner so it some complicated for me to understand this.
Please help me.
Thank you in advance.
