### ISSUE TITLE
Moving from sqlite3

### ISSUE THREAD

**Issue by adi90x** [Mailu/Mailu#417]
Hello @kaiyou,
Is there any chance to move from sqlite3 to another DB storage ?
I am having crazy problem to make it work with NFS share... 

Regards,

**Comment by kaiyou** [comment]
There is indeed, once all database access is moved to the admin container. We still need to move postfix maps, dovecot quotas and fetchmail settings to APIs provided by the admin container.

**Comment by kaiyou** [comment]
Possibly a redis or memcache could be the intermediary, but I would rather avoid having many containers access the database. Then and only then we can use sqlalchemy to support multiple back ends.

**Comment by adi90x** [comment]
Would be nice, at the moment I am trying to deploy mailu to a cluster, and
nfs support is à requirement :&

**Comment by thejordanclark** [comment]
I'm actually was just about to ask the same thing.  I just started evaluating Mailu but a DB service in the backend would be preferable for a couple reasons in my case the most being I would need to integrate SoGo as that is what we have used for years.  SoGo needs LDAP or a DB (postgres, mysql) to authenticate users against.
