### ISSUE TITLE
Raspberry pi fork

### ISSUE THREAD

**Issue by MFAshby** [Mailu/Mailu#418]
I've forked this project to make a raspberry pi compatible version, happily running on my own little rpi 3.
Fork is at https://github.com/MFAshby/Mailu
I'm letting you know as per your contributor guidelines https://mailu.io/contributors/guide.html 

:)

**Comment by kaiyou** [comment]
This is pretty damn cool. Would you mind me pointing to your repo in the docs?

**Comment by MFAshby** [comment]
Sure thing!

**Comment by kaiyou** [comment]
This is now in the documentation, thank you so much :)

**Comment by ulm0** [comment]
Pre-built images would be great, speed up the deployment process

**Comment by MFAshby** [comment]
@ulm0 prebuilt images done, changed instructions to use them.

**Comment by MFAshby** [comment]
@curry684 it looks possible, based on https://stackoverflow.com/questions/33351864/docker-conditional-build-image. Feel free to have a go!

**Comment by ulm0** [comment]
@MFAshby Thank you so much! @curry684 Build args for the Dockerfile can be used. You can cross-build the ARMvX image on `amd64` machines with base images that include qemu binary (e.g: [multiarch/alpine](https://hub.docker.com/r/multiarch/alpine/) or [resin/rpi-raspbian](https://hub.docker.com/r/resin/rpi-raspbian/))
