### ISSUE TITLE
WEBADMIN redirect ignores host port

### ISSUE THREAD

**Issue by Greek64** [Mailu/Mailu#419]
If I bind the http port of the front container to some non standard port (e.g. localhost:8080), the admin container originating 301 redirects ignore the original requested port in their Location header.

Say front is listening to localhost:8080. 
An access to "localhost:8080/admin" results in a correct redirect to "localhost:8080/admin/ui", originating from the nginx proxy in front.
An access to "localhost:8080/admin/ui" results in a incorrect redirect to "http://localhost/admin/ui/", which originates from the admin container. (Port 8080 is ignored in the redirect response)

I tried to find the source of the issue, but I have zero flask/python experience.

**Comment by kaiyou** [comment]
I remember fixing this a couple weeks ago, which version are you running currently?

**Comment by Greek64** [comment]
Oh, I'm running 1.5.
Forgot to check the master before submitting the issue.
Let me check.

**Comment by Greek64** [comment]
So I tested it now with the updated 1.5 branch, and the master.
The problem still exists.

**Comment by Greek64** [comment]
Correction on the last one.
I tried master again, and the redirect problem is fixed.
My browser probably cached something wrong the last time I tested it.
Since that is the case, I'm closing this issue.

Sorry for the inconvenience.

**Comment by Greek64** [comment]
Will the fix be ported back to 1.5?
I'm not fond of running on the latest/master branch.
