### ISSUE TITLE
Support multiple database backends, ie. move database stuff to admin

### ISSUE THREAD

**Issue by kaiyou** [Mailu/Mailu#420]
The admin container should ultimately be responsible for everything related to the database (or, more specifically, the API container once we separate the ui from the API. This will also enable more complex behaviors with dynamic aliases, login maps, quotas, etc.

There are multiple valid ways we can remove a container dependency on the SQLite database, by decreasing priority:
- access an internal API from the admin container (see authentication for instance),
- have the admin container populate a short lived structure in a redis, memcached or any other intermediary structure,
- serve a socket with any specific protocol for loading maps, etc.

In case APIs are written in the admin container, that return sensitive information (e.g. a list of domains, or accounts), these APIs must be authenticated using at least the legitimate container source IP address, so a new authentication wrapper should be written for that purpose.

Here are the tasks at hand:
- [ ] write (if required) a new authentication decorator that checks the source ip among authorized internal containers
- [x] move Postfix alias maps to the admin container
- [x] move Postfix login maps to the admin container
- [x] move Dovecot quotas to the admin container
- [x] move current sive dictionaries used for redirect/vacation to the admin container
- [x] move fatchmail settings to the admin container
- [ ] move redis keys to the something else than files

**Comment by kaiyou** [comment]
This is related to #109, #177, #320, and #412

**Comment by adi90x** [comment]
Do we really need to move every map to the admin container ?
Can't we just add a mysql containers store everything in, use admin to make change to the DB container and get data for maps straight from the DB ?

**Comment by adi90x** [comment]
Another question : wouldn't it be better to merge redis and rspamd in the same image ? As they can't really be separate no ?

**Comment by fabiorauber** [comment]
Obrigado

Em 22 de mar de 2018 5:46 PM, "adi90x" <notifications@github.com> escreveu:

Another question : wouldn't it be better to merge redis and rspamd in the
same image ? As they can't really be separate no ?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Mailu/Mailu/issues/420#issuecomment-375451981>, or mute
the thread

**Comment by kaiyou** [comment]
The reasoning behind moving things to the admin container is the following.

We need to support multiple databases for power users that want to split Mailu across multiple servers, use shared storage like NFS, or use external authentication sources like LDAP. In order to accomplish this, we need all Mailu components to stop depending so strongly on SQLite.

However, what we want most of all is to keep supporting 99% users who are power-ish users, who barely understand how Docker really works and who want Mailu to be simple. By simple, I mean: simple to setup, simple to use, simple to manage. That includes, among other things, the ability to backup a Mailu instance by simply archiving the data directory, or the ability to quickly fire a graphical sqlite client on the ``main.db`` to tweak some accounts.

Therefore, SQLite must remain the default database. Which means we need multiple database support. So finally, we need to harness SQLAlchemy support for multiple backends, hence moving all the database queries to a single container, currently the admin container, eventually an "engine" controller which will provide proper APIs.

**Comment by kaiyou** [comment]
Regarding redis, I see no reason why we would need to install it in the antispam container. We need a plain default redis, which is what the official redis image provides. Why bother re-installing it? If our needs match existing widely used images, we should just use them.

Unfortunately I don't think this is the case for any other component atm.

**Comment by adi90x** [comment]
@kaiyou : make sense for redis/rspamd, understand your point eventhough I would find easier to have 1 container = 1 service !
Do you have an idea of how to handle connection between postfix and admin container ? Via a TCP service ? Or any other idea ?

**Comment by kaiyou** [comment]
Regarding Postfix and Dovecot to be honnest, I have looked at all possible sources for maps and dictionnaries, and I don't like any of them very much. I feel like we have multiple options. One of the best in my opinion would be to contribute a REST module to both these softwares, with similar APIs. This would benefit the e-mail hosting community in so much ways.

A more realistic first step would be to use a TCP connector or script connector and have either a small TCP daemon that translate things or a script that generates requests and parses responses.

**Comment by adi90x** [comment]
Yeah would be massive to be honest...
I am looking into a kind of server wrapper, postgres allow you to connect
to multiple DB ( even sqlite3)..
However, keep thinking that a mariadb containers would be more efficient to
maintain you can even process to a dump to folder on every update so it is
still easy for anyone to save it ! And if available it can be process on
container startup !
What do you think ?

**Comment by kaiyou** [comment]
So, as I was explaining in #445 is that Podop is the result of the work on this issue and is a generic framework for linking Postfix and Dovecot maps yo Python functions, hence to any Python-available api, including rest http.

The branch named ``feat-abstract-db`` contains experimental work for embedding this in Mailu. Last night I pushed commits that enable mail delivery through Postfix (dovecot auth and quota are already working). Any test is more than welcome.

While we test, I will remove the dependency from fetchmail as well so we can finally remove the database volume without harming features.

I will work on this until Saturday and hopefully get something ready for testing and merging into master in October. Then we can start pointing to mysql or postgresql instead of sqlite.

**Comment by kaiyou** [comment]
Now that #612 is merged, we are up for some testing and a couple things to merge for multiple database compatibilities. Good news is: I already have a working test server running MySQL!

**Comment by muhlemmer** [comment]
Heads up: I'm starting work on including a Postgresql option. The works will be based on a merge Pr's #670 and #682. I need the latest advancement in `admin`'s config manager and `setup` to make this work.

If all goes well, this will also provide scaffolding for MySQL, but I'm not so experienced with that it. So someone might need to step in for some details in that regards.

**Comment by muhlemmer** [comment]
@kaiyou:

from the original tasklist:
> write (if required) a new authentication decorator that checks the source ip among authorized internal containers

Is it still required? If yes can you be a bit more specific on what needs to be done in your opinion?

**Comment by kaiyou** [comment]
I do not think it is required until we switch to a full-sized API that we could expose as a whole. Then indeed we would need to check the source of a request for internal checks.

**Comment by kaiyou** [comment]
I am closing this since it it 95% implemented and remaining bullets should have their own issue.
