### ISSUE TITLE
Mailu 1.5.1 front service can't start

### ISSUE THREAD

**Issue by Looongcat** [Mailu/Mailu#422]
Hi guys! I have a strange trouble with running front module, hope you'll help to figure it out.

> ERROR: for front  Cannot start service front: driver failed programming external connectivity on endpoint mailu_front_1 (2d79de6fa24f4d21de1e49451cedc36c592e04ba1efa096699ef60b4d8345cf9): Bind for 0.0.0.0:995 failed: port is already allocated
> ERROR: Encountered errors while bringing up the project

It can't start with binding for 0.0.0.0, 127.0.0.1 and actual external IP. That port is definitely free (checked that with `netstat -pln`).

Software:
Debian Stretch 4.15.8-x86_64
Docker 18.03.0-ce
docker-compose version 1.8.0
docker-py version: 1.9.0
CPython version: 2.7.13
certbot 0.10.2

Hardware (instance):
1 CPU
1 GB RAM

Every actions running under root without sudo (it's an experimental server)

**Comment by Looongcat** [comment]
Stupid case, but I've found a trouble. Port binding was constantly failed because of IPv6 (tried actual IPv6 address, ::1 and ::). Replacing docker-compose with 1.20.1 didn't help a lot, so I've removed IPv6 bindings from front module and everything works fine.

If anyone have thoughts what possibly could go wrong with IPv6 on mentioned software - will be glad to test your ideas, for now I'm planning spend some more time to make IPv6 work.

**Comment by kaiyou** [comment]
It is nothing about Ipv6 per se, it is due to the fact that Docker binds to any address, including Ipv6, when you specify 0.0.0.0.

Therefore, you cannot additionally listen on a specific IPv6 address because the socket is already bound to it.
