### ISSUE TITLE
Postfix way of working 

### ISSUE THREAD

**Issue by adi90x** [Mailu/Mailu#423]
Hello @kaiyou , 

Quick question about postfix : do you think that it could be possible to route all outgoing trafic throught front container ? 
ATM , I have postfix container in one host and front on another one , as a result postfix is not able to correctly send email ! 
Any idea about this situation or way of dealing with that ? 

Regards,

**Comment by kaiyou** [comment]
It is very common in a mail setup to have separate incoming and outgoing paths. The most common way of dealing with it is to use SPF with the IP address of your outgoing host.
