### ISSUE TITLE
Unable to Receive emails

### ISSUE THREAD

**Issue by arpitgoyalhtmedia** [Mailu/Mailu#424]
First of all congratulations on an awesome project. Such an easy way to setup your own mail server with less hesitation and more output.

I have got this running. I have few issues that I faced and would like to share

1) While spinning off this on an AWS server it used to say that port 25 is already in use. I guess AWS spins SMTP services for SES on each and every server run (or so I feel, what is the exact issue if anyone can comment)

2) My initial mails where going to SPAM, I used let's encrypt for a TLS certificate (thinking that maybe security is the reason for this) but even after certificate installation and sending a message, the mails went as SPAM. (what might be the issue?)

3) I cannot receive emails and I just can't figure out why. IMAP services are running. Is there some setting I am missing? I use outlook to send a mail to a newly created mail id for my mailserver, I cannot see a mail in my inbox.

Thanks for the time!

**Comment by kaiyou** [comment]
I guess that 1. and 3. are strongly related, port 25 is the one used to receive email from remote servers. Does not matter if you have IMAP working to *read* the received emails, you won't see any of you don't have SMTP working to receive them in the first place 

I am not used to AWS, but I hope there is some documentation about disabling the local SMTP ses relay on a node.

Regarding point 2, most steps to gain reputation and avoid getting all your mails classified as spam by other providers, are in order :

-  setup SPF
- setup dkim and dmarc
- change your outgoing IP if yours has a really bad reputation (previously used for spam for instance).

Regarding SPF, dkim and dmarc, all can be configured from the domain detail page. You will need to insert some entries in your domain zone as well.

**Comment by kaiyou** [comment]
Closing here, feel free to reopen if the issue was not solved.
