### ISSUE TITLE
Add stable tag for nginx-no-https

### ISSUE THREAD

**Issue by darkblinded** [Mailu/Mailu#427]
If you try to run the mailu-rancher with `$VERSION=stable` and `$FRONTEND=nginx-no-https` it fails because there is no `stable` tag for `nginx-no-httpx`.

**Comment by kaiyou** [comment]
Well, what version are you using? To be honnest, I was expecting to remove that container completely by june, as it is bound to Mailu 1.4 and release 1.5 dates back to late 2017.
