### ISSUE TITLE
No DKIM Signature

### ISSUE THREAD

**Issue by Greek64** [Mailu/Mailu#435]
I somehow cannot make DKIM working.
I have generated the DKIM keys in the mail domain admin page, and added them to my DNS Entries.
But the problem is that the outgoing mails themselves are not signed with these keys.
I tried regenerating the keys and sending test mails from a different user, but no success.

Do I have to enable it somewhere else?

[I'm running with the `latest` tag]

**Comment by romracer** [comment]
You will need to make sure the dkim volume from the admin container is also available to the antispam/rspamd container.

You may also need to enable DKIM signing for some network ranges.  I had to enable this in the past and never checked to see if it was still required.  I use Kubernetes so I have a ConfigMap that looks like this:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: rspamd-config
  namespace: mail-server
data:
  greylist.conf: |
    whitelisted_ip = "/etc/rspamd/override.d/dkim_greylist_ip.map";
  dkim_signing.conf: |
    sign_networks = "/etc/rspamd/override.d/dkim_greylist_ip.map";
  dkim_greylist_ip.map: |
    10.12.0.0/14
    a.public.subnet/25
    another.public.subnet/26
    some.public.ip/32
```

Those 3 files are written to /etc/rspamd/override.d on container start.

You could accomplish the same thing with docker-compose by creating 3 files (dkim_signing.conf, greylist.conf and dkim_greylist_ip.map) in the same directory with the above contents (/mnt/docker/mailu/overrides/rspamd in the below example).  Then bind mount that directory into your container like so:

```
    volumes:
    - /mnt/docker/mailu/filter:/var/lib/rspamd
    - /mnt/docker/mailu/dkim:/dkim
    - /mnt/docker/mailu/overrides/rspamd:/etc/rspamd/override.d
```

Notice I also included the /dkim directory, the same as used by the admin container.

**Comment by Greek64** [comment]
@romracer 
Thanks for the response.
But your suggested configuration is not what I want (I don't want to sign mails from network ranges, but from authenticated users, which should be the default setting).
Nevertheless your answer pointed me into the right direction (Didn't knew that the antispam service was also responsible for the DKIM signing of outgoing mails...)

Since today I had more time to spend debugging, I started with enabling debug logging for the dkim_signing module of rspamd.
This was the result:
```
2018-04-08 15:44:07 #8(rspamd_proxy) <516031>; dkim_signing; lua_dkim_tools.lua:34: user is authenticated
2018-04-08 15:44:07 #8(rspamd_proxy) <516031>; dkim_signing; lua_dkim_tools.lua:103: use domain(header) for signature: mail.example.com
2018-04-08 15:44:07 #8(rspamd_proxy) <516031>; dkim_signing; lua_dkim_tools.lua:122: final DKIM domain: example.com
2018-04-08 15:44:07 #8(rspamd_proxy) <516031>; dkim_signing; dkim_signing.lua:121: file /dkim/example.com.dkim.key does not exists
```
As can be seen, the module correctly interprets the mail coming from an authenticated user, and wants to sign it, but during the "parsing" procedure it tries to sign against the bare domain, instead of the subdomain (for which the DKIM Key exists).

Further investigation reveals that this is happening because of the default setting `use_esld = true;`.
So, a simple setting of `use_esld = false;` fixes my problem, and mails are DKIM signed as expected.

But now comes my followup Question: @kaiyou 
Going by the recommendation suggested in the docs:
`For instance, if your main mail domain is mydomain.com (the one you setup in DOMAIN in your configuration file), then you could use mail.mydomain.com as a mail server hostname.`,
it seems like my Domain Name is using the recommended convention, and since the DKIM keys are generated for the subdomains (hostnames), shouldn't this be a default setting?
As I see it now, DKIM should not work by default.
