### ISSUE TITLE
rmilter docker image missing ?

### ISSUE THREAD

**Issue by outbackdingo** [Mailu/Mailu#439]
Error (Error response from daemon: pull access denied for mailu/rmilter, repository does not exist or may require 'docker login')

**Comment by kaiyou** [comment]
Which version of Mailu are you running? Rmilter has been deprecated since september in favor of rspamd, it had not received updates since.

It should still exist for 1.4 but is obviously not built for later versions.

**Comment by outbackdingo** [comment]
its still being called from the rancher catalog

**Comment by kaiyou** [comment]
Oh, I'll recreate it today and make sure that we update the rancher config. Any chance you get some time to help with this?

**Comment by outbackdingo** [comment]
yes i can help thats fine for me... i have it running on rancher now was
going to test deploy a second pod

**Comment by iMartyn** [comment]
Please please please don't delete images that people have running in existing systems.
My mail system is broken because of this now, and I don't have time to reconfigure using a later version of mailu at the minute!
@kaiyou you said you would recreate it 28 days ago but there's still no rmilter image in mailu repo on dockerhub.  Even if you could upload the image with a tag of :deprecated I could tweak my setup without complete reinstallation.

**Comment by kaiyou** [comment]
Ok, so here is the catch and I feel very sorry about it: rmilter is definitely deprecated and not even supported on Alpine anymore. Maybe I can be of assistance migrating to 1.5, which is not, to be honnest, a complete reinstallation (migration is handled automatically by admin scripts).

**Comment by christhomas** [comment]
I also ran into this issue, postfix is trying to use rmilter even though you've deleted the image.

**Comment by kaiyou** [comment]
Could you try and upgrade to 1.5? Rmilter is unfortunately completely deprecated, has unpatched vulnerabilities and is not in Alpine repos anymore. It would probably be a bad idea to keep using it anyways.

**Comment by christhomas** [comment]
But your postfix image is trying to use it. Or can I just configure milter to use the hostname of rspamd instead? Does is just slot in as a like for like replacement?

**Comment by kaiyou** [comment]
I have explicitly deprecated the stable branch and wish not to use it anymore. It is incompatible with automated upgrades since the compose file changes.

**Comment by kaiyou** [comment]
You should probably upgrade to 1.5 :)

**Comment by xuhui98** [comment]
> I have explicitly deprecated the stable branch and wish not to use it anymore. It is incompatible with automated upgrades since the compose file changes.

hehe,  So why is it still called stable?
