### ISSUE TITLE
^_^@domain.com is not recognized as a valid email

### ISSUE THREAD

**Issue by ikzk** [Mailu/Mailu#443]
I cannot login via webmail nor receive email. However ^_^@domain.com should be a valid email address.

**Comment by ikzk** [comment]
Also the email sent to ^_^@domain.com will be rejected even if I set %@domain.com alias.

**Comment by ikzk** [comment]
When I try to login, I got the following log:

```
front_1      | 2018/04/12 07:23:38 [info] 9#9: *672 upstream sent invalid response: "NO [AUTHENTICATIONFAILED] Authentication failed." while reading response from upstream, client: 172.18.0.5, server: 0.0.0.0:10143, login: "^_^@domain.com", upstream: 172.18.0.9:143
imap_1       | Apr 12 07:23:38 imap-login: Info: Disconnected (auth failed, 1 attempts in 2 secs): user=<^_^@domain.com>, method=PLAIN, rip=172.18.0.3, lip=172.18.0.9, session=<z+E7oqFpQIGsEgAD>
```

This only happens when the email contains `^`.

**Comment by kaiyou** [comment]
This us especially weird, since following release 1.5, dovecot does not check authentication anymore but trusts the front to do so..

**Comment by ikzk** [comment]
When there's an email sending to `^_^@domain.com`:

```
smtp_1       | postfix/smtpd[79]: NOQUEUE: reject: RCPT from forward100o.mail.yandex.net[37.140.190.180]: 450 4.1.1 <^_^@domain.com>: Recipie
nt address rejected: unverified address: Address lookup failure; from=<username@yandex.com> to=<^_^@domain.com> proto=ESMTP helo=<forward100o.mail.yandex.net>  
```

**Comment by kaiyou** [comment]
I will browse dovecot and nginx-mail documentation for constraints on the local part.

**Comment by ikzk** [comment]
I used `VERSION=master` in `.env` file. Will that cause any problem?

**Comment by kaiyou** [comment]
It is not especially recommended in production, unless you have enough time to test everything after an update and revert when required.

What is really discouraged is running master with automatic updates.

**Comment by ikzk** [comment]
By using the default `.env` I got 

```
Pulling front (mailu/nginx:1.5.1)...
ERROR: manifest for mailu/nginx:1.5.1 not found
```

That was the reason why I changed it to master.

**Comment by hoellen** [comment]
@ikzk On `master` the address `^_^@domain.tld` works, if you change the allowed chars for usernames in dovecot. So just add the following line to `overrides/dovecot.conf`:
```
auth_username_chars = abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ01234567890.-_@^
```
@muhlemmer So I think we can close this? Or do you think we should allow more username chars then default dovecot?

**Comment by muhlemmer** [comment]
It seems that `^_^` is a valid string and should be supported. So yeah, if you can please put it in a PR.
