### ISSUE TITLE
Remove all references to 1.5.1

### ISSUE THREAD

**Issue by kaiyou** [Mailu/Mailu#444]
Branch 1.5.1 was not a long term branch and merely meant to merge various sensitive patches without impacting 1.5.

Given the general confusion on the matter, I will try and remove all references to that branch and avoid similar mistakes it future releases.

If you find any remaining reference, please mention it so I can properly remove it.

**Comment by rgarrigue** [comment]
Here is one : https://mailu.io/1.5/_downloads/.env

**Comment by kaiyou** [comment]
Thanks, that one was just removed

**Comment by kaiyou** [comment]
I could not find any more. Closing.
