### ISSUE TITLE
IDNA support

### ISSUE THREAD

**Issue by sanduhrs** [Mailu/Mailu#446]
Since a while lots of TLDs support IDNA [1] (non ASCII chracters in domain names).
I tried creating a new domain, containing non-ASCII characters, in this case some german Umlauts (äöü).

**Created domain using Unicode notation:**
- New domain: dömäin.org
- Database: dömäin.org
- Mailfolder: n/a
- Admin UI login: 
  - test@xn--dmin-moa0i.org, Failure
  - test@dömäin.org, Success
- Admin UI display: dömäin.org
- Webmail login: 
  - test@xn--dmin-moa0i.org, Failed
  - test@dömäin.org, Failed
- Webmail UI display: n/a
- Testmail to:
  - test@xn--dmin-moa0i.org, Failed
  - test@dömäin.org, Failed

**Created domain using Punicode [2] notation:**
- New domain: xn--dmin-moa0i.org
- Database: xn--dmin-moa0i.org
- Mailfolder: test@xn--dmin-moa0i.org
- Admin UI login:
  - test@xn--dmin-moa0i.org
- Admin UI display: test@xn--dmin-moa0i.org
- Webmail login:
  - test@xn--dmin-moa0i.org, Success
  - test@dömäin.org, Success
- Webmail UI display: test@dömäin.org
- Testmail to:
  - test@xn--dmin-moa0i.org, Success
  - test@dömäin.org, Success

What I observed is, that the notation of the email address in the email source
code always is the Punicode one.

So I assume, whithout knowing anything about the inner workings of IDNA, that it is merely a admin frontend and admin cli issue and we could probably support this by:
1. Storing the IDNA in Punicode notation in the database
2. Converting the Punicode notated domain name to Unicode notation when displayed

[1] https://en.wikipedia.org/wiki/Internationalized_domain_name
[2] https://en.wikipedia.org/wiki/Punycode

**Comment by kaiyou** [comment]
I definitely agree, it is a matter of displaying and saving data in the proper format.

I guess that a simple salalchemy type that does on the fly conversion would suffice to get immediate and full idn support. This can surely be implemented very quickly.

**Comment by kaiyou** [comment]
This was merged and seems to work pretty good :)

**Comment by timoschwarzer** [comment]
@kaiyou 

I cannot send E-Mails from an account with an IDN domain.

```
postfix/smtpd[1443]: NOQUEUE: reject: RCPT from mailu_webmail_1.mailu_default[192.168.203.8]: 553 5.7.1 <someuser@xn--some-idn-6ob.de>: Sender address rejected: not owned by user someuser@xn--some-idn-6ob.de; from=<someuser@xn--some-idn-6ob.de> to=<someother@mail.de> proto=ESMTP helo=<mail.mymaildomain.com>
```
