### ISSUE TITLE
Add disable account action

### ISSUE THREAD

**Issue by sanduhrs** [Mailu/Mailu#449]
An admin option to disable an email account in addition to deleting it would be nice.

I really do not like deleting accounts, because any deleted account could be recreated for another person with the same localpart, potentially allowing the other person to restore access to web services that have been signed on with the email address by the initial owner.

I suggest to add a status field to the user table with possible values 0 or 1.
And respecting it in the authentication and email delivery procedures.
An action on the user list of the admin interface would be nice, too.

**Comment by kaiyou** [comment]
I guess it could be implemented as a simple "enabled" field on the User model. The field would be available in the user properties to global admins and domain admin.
