### ISSUE TITLE
IMAP in Outlook 2016

### ISSUE THREAD

**Issue by leogzl** [Mailu/Mailu#454]
The application is great, running well in Thunderbird, Apple Mail, IOS, Android and Office 365.

But on outlook 2016 mail client the IMAP configuration is not successful.
There is no useful message from outlook (only **something was wrong**)

Is there anyway to debug the IMAP in mailu, to check what exactly the request from outlook 2016?

Regards,

Leo

**Comment by romracer** [comment]
Nginx (the front container) proxies IMAP authentication to the admin server.  Authentication is performed by the admin container and the result is returned to Nginx.  The imap container (Dovecot) trusts authentication was performed by the front container, and uses its IP address to confirm this (in /etc/dovecot/dovecot-sql.conf.ext).

I would start by checking the front and admin container logs.  Assuming no problems there, you might confirm the IP in the above file matches the IP assigned to your front container.  As a last resort, you would have to capture the response returned by the admin container to the front container.  It contains the auth status, server and port Nginx should redirect to for actual IMAP.

**Comment by leogzl** [comment]
I am pretty sure that nothing wrong in mailu because using other client application, the IMAP works great.

I am curious on the request the outlook 2016 sent to the server that responses not accepted by that application.

Thanks anyway, will do your advice above.

**Comment by romracer** [comment]
You may be correct that nothing is wrong in Mailu.  I just wanted to outline the process of authentication so you had some ideas on where to look for logs, problems, etc :)  Understanding the flow of the login process should be helpful in knowing **where** to look for what Outlook 2016 is doing differently.

I'd start with the front/nginx log.  That will at least let you know whether nginx is succeeding in authentication and how to proceed from there (if nginx is succeeding, Outlook must not interpret the answer correctly.  if nginx is not succeeding, then you'd need to look deeper at what Outlook is doing differently [examples: no TLS, wrong username, etc]).

I can try Outlook 2016 on my home PC later this evening.  I don't have that access now.

**Comment by romracer** [comment]
IMAP in Outlook 2016 works fine for me.  I did fine one "error" but this is a known issue.  Outlook 2016 tries to send yourself an email and may get the following error from the smtp container:

```553 5.7.1 <romracer@example.com>: Sender address rejected: not owned by user romracer@example.com; from=<romracer@example.com> to=<romracer@example.com> proto=ESMTP helo=<ComputerName>```

This is known in #390 and there are two workarounds (disable forwarding or keep a local copy).  Once I disabled forwarding, I had no trouble adding my account to Outlook 2016.

**Comment by kevinlincg** [comment]
@romracer 
Is there has any great log analysis tool for docker-compose?
I only have docker-compose logs -f -t

**Comment by leogzl** [comment]
Thanks @romracer 

We still experience the issue. But have not checked the log yet. 
I will check to my team for further update.

Note: it is not for sending but for retrieving email.
Our workaround, SMTP provide by 3rdparty (not mailu) but IMAP/POP3 is on mailu.

Leo

**Comment by romracer** [comment]
@kevinlincg I think that depends on what you're after.  Not really the point of this issue.  You can also use `docker-compose logs -f smtp` to limit output to that container.  If you want true analysis, you'd need something like Stackdriver in GCP or something like logz.io or an ELK stack, Splunk, etc.

@leogzl If using an alternate SMTP server works, it definitely points to an issue with smtp config or perhaps that issue I noted earlier.  I know you were talking about receiving (IMAP account setup), but as I said, Outlook sends yourself an email as part of the setup process (its the Welcome to Outlook email that's in your inbox when you open the program the first time).  Anyway, glad you found a workaround.

**Comment by leogzl** [comment]
Hi @romracer 

A quick update, we are going to try to disable the setup wizard using this.
https://support.microsoft.com/en-us/help/3189194/how-to-disable-simplified-account-creation-in-outlook-2016

I will check to the user if this is successful.
This is not the bug of mailu, only the mail client need "special attention".

BTW, another reason we do not use SMTP from mailu, because the message is sent but never received by the recipient (e.g. sent to gmail address). We are still looking for this issue, and I will add to new issue if not resolved.

Thanks all.

**Comment by leogzl** [comment]
Hi @romracer 

The issue still exists.
May I  know how to enable debug mode to IMAP?

I would like to test the IMAP using telnet, port 143

Regards


Leo

**Comment by leogzl** [comment]
Hi @romracer again

I think I found out the issue in Outlook 2016

After telnet, the result of this command:
Mailu:
```
x CAPABILITY
* CAPABILITY IMAP4 IMAP4rev1 UIDPLUS STARTTLS LOGINDISABLED

```

Other Mail Server
```
CAPABILITY
CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE NAMESPACE STARTTLS AUTH=PLAIN AUTH=LOGIN

```

I do not know what makes the outlook just assume that the return of Mailu is not good enough.

**Comment by leogzl** [comment]
Hi All

Thank you to taking attention to my issue.
We kind of manage to solve the connection via outlook, but it is very dirty.

Please consult with your security advisor, before running this command.

1. edit the conf/nginx.conf
2. replace the following line
 ```
# All other protocols are disabled if TLS is failing
    {% if not TLS_ERROR %}
    server {
      listen 143;
      listen [::]:143;
#      {% if TLS %}
#      starttls only;
#      {% endif %}
      protocol imap;
#      imap_auth plain;
      smtp_auth plain;
    }

```

1. Disable TLS
2. Change the authentication from imap to smtp
