### ISSUE TITLE
Mailu clean install web access fails

### ISSUE THREAD

**Issue by Ricks-ha** [Mailu/Mailu#457]
I have got a clean install and a reverse proxy running. I installed it using the docker image provided. It is running on a Ubuntu box. My problem is that if i try to access /webmail or /admin on the mail server, I get the response 403 Forbidden nginx on a blank web page. I have roundcube set as a webmail.

**Comment by romracer** [comment]
Need more information please.  Check the `front` container logs when you make a request in your browser.  If there's no errors there, repeat the process for the `webmail` container.

**Comment by Ricks-ha** [comment]
I found the error I have symlinked the certificate files. The problem with that was the symlink is not working in the front container anymore.
