### ISSUE TITLE
Container missing tags

### ISSUE THREAD

**Issue by rgarrigue** [Mailu/Mailu#459]
Hi

I tried VERSION=stable, which end up failing because mailu/radicale is missing :stable tag.

While I'm on the VERSION topic, following the doc did the `wget .../.env` to get started, left the default VERSION=1.5.1, which failed since 1.5.1 is nowhere to be found in the various docker tags.

Best regards,

**Comment by hoellen** [comment]
Try to use tag `1.5`.
See #444

**Comment by kaiyou** [comment]
Working on switching to 1.5, this is a mistake when updating the configuration generator.

**Comment by kaiyou** [comment]
This is fixed now.
