### ISSUE TITLE
Letsencrypt HTTP challenge fails when Mailu is behind an external reverse proxy

### ISSUE THREAD

**Issue by steamedhams1** [Mailu/Mailu#460]
I'm running Mailu behind an external reverse proxy, following the instructions in the documentation, and the letsencrypt tls flavor never works. Everything is fine with no tls, but I don't really want to be sending/receiving email unsecured. The error I get is:

`Failed authorization procedure. mail.domain.com (http-01): urn:acme:error:unauthorized :: The client lacks sufficient authorization :: Invalid response from http://mail.domain.com/.well-known/acme-challenge/Gl3uPLgu75uTtvpcQBhNy10Gcd7o3odlrRgM1XY5cgs`

**Comment by Archie1978** [comment]
Hello,
     I did not do like documentation.

I use jrcs/letsencrypt-nginx-proxy-companion and jwilder/nginx-proxy for making a pool.
Then I mount certifcate generated by letsencrypt-nginx-proxy-companion on mailu / certs.

For example :
mount --bind  /docker/proxy-http/certs/mail.idesi.fr /docker/mail-server/mailu/certs.
After that, it is necessary to restart the mail service (mailu / postfix) after the generation of the certificates.

I do not know if it can help you, but it was at the time a simple solution.

**Comment by skupfer** [comment]
Try to add the following to your reverse proxy (if nginx). This is for the port 80 listener

  ```
 # select all port 80 acme requests o
    location ^~ /.well-known/acme-challenge/ {
        default_type "text/plain";
        root /var/www/html;
        allow all;
    }

    location = /.well-known/acme-challenge/ {
        return 404;
    }
```

**Comment by jkarlosb** [comment]
Next config worked for me. If you are using 1.5 version, try with this:

In docker-compose.yml, don't use bind address 127.0.0.1 in your .env like the documentation said, instead use 0.0.0.0 or your external IP:
```
front:
  # build: nginx
  image: mailu/nginx:$VERSION
  restart: always
  env_file: .env
  ports:
    - "$BIND_ADDRESS4:8080:80"
    - "$BIND_ADDRESS4:8443:443"
    ...
```
Then in your nginx conf file add:
```
server {
    listen 80;
    server_name mymailhost.tld;
    access_log /var/log/nginx/access.log;
    location / {
        proxy_pass http://mymailhost.tld:4480;
    }
}

server {
    listen 443;
    server_name mymailhost.tld;
    access_log /var/log/nginx/access.log;
    location / {
        proxy_pass https://mymailhost.tld:4443;
    }
}
```
Reload your nginx, recreate or reinstall your mailu if it's neccesary. Good luck!
