### ISSUE TITLE
Remove the Service Status page

### ISSUE THREAD

**Issue by kaiyou** [Mailu/Mailu#463]
Mailu was initially meant for Docker Compose only and expects the Docker socket to be mounted inside the admin container.

Now that the project has evolved to support other environments, and suspecting that the "Service Status" page is not actually useful, I would like to remove it. Any objection?

**Comment by sanduhrs** [comment]
Using it in rancher it did not work anyway 😉

**Comment by muhlemmer** [comment]
+1, it doesn't work in swarm mode.

**Comment by kaiyou** [comment]
This was implemented and merged
