### ISSUE TITLE
:995 bind: address already in use, orly ?

### ISSUE THREAD

**Issue by valkheim** [Mailu/Mailu#464]
Hi,

I can't start services using docker-compose file. I'm on a fresh debian install.
This is the error message I encounter on startup :
```
ERROR: for front  Cannot start service front: driver failed programming external connectivity on endpoint mailu_front_1 (625b381bf5dbbddc91758306afc0272a14b72fc6bd3eb45f4993ecd8a9cdf8f0): Error starting userland proxy: listen tcp 5.196.65.147:995: bind: address already in use
ERROR: Encountered errors while bringing up the project.
```
I tried to `apt-get autoremove --purge exim4 exim4-base`
I see nothin using netstat/ss

Any clue ?
Thanks

**Comment by CMclarty** [comment]
What was the resolution you found?

**Comment by luatnd** [comment]
Some here:
> listen tcp4 35.240.184.231:995: bind: cannot assign requested address

What is the solution?

**Comment by wjcroom** [comment]
me too on  DSM of synolyn docker......
