### ISSUE TITLE
Welcome to nginx, now what ?

### ISSUE THREAD

**Issue by FaZeBase** [Mailu/Mailu#472]
I have everything as explained in the docs and I get Welcome to nginx. I expected to hace a webmail. I've set this up as well... I am clueless as what is wrong at this point

**Comment by dgramop** [comment]
You probably have the wrong NGINX, that is, NGINX on the host machine is responding over NGINX in Mailu. Check which process is bound to port 80, that might help

**Comment by kaiyou** [comment]
Did you customize your env file? The default configuration has no webmail and no admin interface, so it will display nginx default welcome page.
