### ISSUE TITLE
RELAYNETS what is this function

### ISSUE THREAD

**Issue by leogzl** [Mailu/Mailu#473]
The default configuration is this

```
# Networks granted relay permissions, make sure that you include your Docker
# internal network (default to 172.17.0.0/16)
RELAYNETS=172.16.0.0/12

```

What is the usage of this configuration.
If I changed to 172.16.0.0/16, which is my default docker0 ip, the SMTP will be failed.

`fetchmail: SMTP error: 451 4.3.0 <xx@xx.xx>: Temporary lookup failure`

But leaving as default, SMPT is working well.
There is no 172.16.0.x in my network

**Comment by curry684** [comment]
Docker subnets are all created within the 172.16.0.0/12 IP space by default. If you use Docker Compose it may for example use 172.19.0.0/16 for that one, which would block relay (and therefore cause the SMTP error you mention) if using the smaller CIDR.

**Comment by leogzl** [comment]
Thank @curry684
