### ISSUE TITLE
Cannot set the "keep emails" for Fetched accounts

### ISSUE THREAD

**Issue by LaurentMox** [Mailu/Mailu#479]
Hello,

In the "Fetched accounts" page of the admin area, when editing or adding an account, i do not see any options to keep emails on server. But the boolean (default to false) is displayed in a column in the "Fetched accounts" list page.
Am i missing something ?

Thank you

**Comment by kaiyou** [comment]
The field is missing indeed, I will fix that when I have a proper editor.
