### ISSUE TITLE
rspamd lua errors after fixing worker-fuzzy.inc

### ISSUE THREAD

**Issue by 4nx** [Mailu/Mailu#485]
Hey everyone,

I pulled the latest release today and have multiple errors. One of them is already addressed under https://github.com/Mailu/Mailu/issues/481 but the other is related to rspamd. First of all I got the following error:

`#5(main) cfg; rspamd_config_read: ucl parser error: cannot open file /etc/rspamd/worker-fuzzy.inc: No such file or directory`

After digging through the changes of rspamd in here I found the workaround in the Dockerfile, which seems to be not build on docker hub yet. After manually commenting fuzzy worker out there are new error messages which may be a result of commenting out or not:

> antispam_1   | 2018-06-02 23:12:26 #6(main) lua; lua_cfg_transform.lua:263: unknown element in actions section: composites
> antispam_1   | 2018-06-02 23:12:26 #6(main) lua; lua_cfg_transform.lua:263: unknown element in actions section: actions
> antispam_1   | 2018-06-02 23:12:26 #6(main) lua; lua_cfg_transform.lua:263: unknown element in actions section: group
> antispam_1   | 2018-06-02 23:12:26 #6(main) lua; lua_cfg_transform.lua:299: nested section: metric { metric { ... } }, it is likely a configuration error
> antispam_1   | 2018-06-02 23:12:26 #6(main) lua; lua_cfg_transform.lua:299: nested section: actions { actions { ... } }, it is likely a configuration error
> antispam_1   | PANIC: unprotected error in call to Lua API (runtime code generation failed, restricted kernel?)
> antispam_1   | Killed

Nevertheless rspamd seems not to run anymore from images pulled from docker hub.

**Comment by kaiyou** [comment]
I believe this is fixed now
