### ISSUE TITLE
Automated Releases

### ISSUE THREAD

**Issue by HorayNarea** [Mailu/Mailu#487]
It would be great if images from master and current release branches would be build and released on hub.docker.com automatically… other projects use TravisCI for this.

This would remove the delay between commiting fixes and receiving fixes AND would allow easier testing of master (one could imagine setting up a mailu-master on a server that pulls updates every few hours and sends/receives test mails -> alerting goes off if mails don't work)

@kaiyou what do you think about this, if you like the idea I could try to supply a rudimentary .travis.yml where you just have to add credentials for hub.docker.com

**Comment by kaiyou** [comment]
Actually all images for all branches are built automatically on Docker hub already.

**Comment by HorayNarea** [comment]
Oh, I didn't know that… sorry for the confusion :D

And what about automated testing? Currently one can not see if a PR will break something because TravisCI only builds the documention

**Comment by kaiyou** [comment]
For automated testing we still need a proper testing system. I believe #47  is one of the oldest issues on the matter, that we need to close first.
