### ISSUE TITLE
mail-letsencrypt 

### ISSUE THREAD

**Issue by wessel1512** [Mailu/Mailu#489]
is it possible to have the web elements only use http
for easier revers proxy setup 

i have got Rainloop working. but the admin control panel doesn't work correctly

my test docker-compose file

 version: '2'

services:

  front:
    image: mailu/nginx:$VERSION
    restart: always
    env_file: .env
    ports:
    - "$BIND_ADDRESS4:8123:80"
    - "$BIND_ADDRESS4:8443:443"
    - "$BIND_ADDRESS4:110:110"
    - "$BIND_ADDRESS4:143:143"
    - "$BIND_ADDRESS4:993:993"
    - "$BIND_ADDRESS4:995:995"
    - "$BIND_ADDRESS4:25:25"
    - "$BIND_ADDRESS4:465:465"
    - "$BIND_ADDRESS4:587:587"
    volumes:
      - "$ROOT/certs:/certs"
    labels:
      - "traefik.frontend.rule=Host:$HOSTNAMES"
      - "traefik.port=80"
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - "$ROOT/redis:/data"

  imap:
    image: mailu/dovecot:$VERSION
    restart: always
    env_file: .env
    volumes:
      - "$ROOT/data:/data"
      - "$ROOT/mail:/mail"
      - "$ROOT/overrides:/overrides"
    depends_on:
      - front

  smtp:
    image: mailu/postfix:$VERSION
    restart: always
    env_file: .env
    volumes:
      - "$ROOT/data:/data"
      - "$ROOT/overrides:/overrides"
    depends_on:
      - front

  antispam:
    image: mailu/rspamd:$VERSION
    restart: always
    env_file: .env
    volumes:
      - "$ROOT/filter:/var/lib/rspamd"
      - "$ROOT/dkim:/dkim"
      - "$ROOT/overrides/rspamd:/etc/rspamd/override.d"
    depends_on:
      - front

  antivirus:
    image: mailu/$ANTIVIRUS:$VERSION
    restart: always
    env_file: .env
    volumes:
      - "$ROOT/filter:/data"

  webdav:
    image: mailu/$WEBDAV:$VERSION
    restart: always
    env_file: .env
    volumes:
      - "$ROOT/dav:/data"

  admin:
    image: mailu/admin:$VERSION
    restart: always
    env_file: .env 
    ports:
    - "$BIND_ADDRESS4:8000:80"
    labels:
    - traefik.enable=true
    - traefik.frontend.rule=Host:test.${DOMAIN}
    - traefik.port=80
    - traefik.frontend.entryPoints=http
    volumes:
      - "$ROOT/data:/data"
      - "$ROOT/dkim:/dkim"
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - redis

  webmail:
    image: "mailu/$WEBMAIL:$VERSION"
    restart: always
    env_file: .env
    ports:
    - "$BIND_ADDRESS4:8001:80"
    labels:
    - traefik.enable=true
    - traefik.frontend.rule=Host:wes.${DOMAIN}
    - traefik.port=80
    - traefik.frontend.entryPoints=http
    volumes:
      - "$ROOT/webmail:/data"

  fetchmail:
    image: mailu/fetchmail:$VERSION
    restart: always
    env_file: .env
    volumes:
      - "$ROOT/data:/data"

test .env file 
###################################
# Common configuration variables
###################################

# Set this to the path where Mailu data and configuration is stored
ROOT=/mailu

# Mailu version to run (1.0, 1.1, etc. or master)
VERSION=master

# Set to a randomly generated 16 bytes string
SECRET_KEY=kjdskjdhfkjsdh

# Address where listening ports should bind
BIND_ADDRESS4=192.168.2.102
BIND_ADDRESS6=::1

# Main mail domain
DOMAIN=domain.local

# Hostnames for this server, separated with comas
HOSTNAMES=mx.domain.local

# Postmaster local part (will append the main mail domain)
POSTMASTER=admin

# Choose how secure connections will behave (value: letsencrypt, cert, notls, mail)
TLS_FLAVOR=notls

# Authentication rate limit (per source IP address)
AUTH_RATELIMIT=10/minute;1000/hour

# Opt-out of statistics, replace with "True" to opt out
DISABLE_STATISTICS=False

###################################
# Optional features
###################################

# Expose the admin interface (value: true, false)
ADMIN=true

# Choose which webmail to run if any (values: roundcube, rainloop, none)
WEBMAIL=rainloop

# Dav server implementation (value: radicale, none)
WEBDAV=none

# Antivirus solution (value: clamav, none)
ANTIVIRUS=none

###################################
# Mail settings
###################################

# Message size limit in bytes
# Default: accept messages up to 50MB
MESSAGE_SIZE_LIMIT=50000000

# Networks granted relay permissions, make sure that you include your Docker
# internal network (default to 172.17.0.0/16)
RELAYNETS=172.16.0.0/12

# Will relay all outgoing mails if configured
RELAYHOST=

# Fetchmail delay
FETCHMAIL_DELAY=600

# Recipient delimiter, character used to delimiter localpart from custom address part
# e.g. localpart+custom@domain;tld
RECIPIENT_DELIMITER=+

# DMARC rua and ruf email
DMARC_RUA=admin
DMARC_RUF=admin

# Weclome email, enable and set a topic and body if you wish to send welcome
# emails to all users.
WELCOME=false
WELCOME_SUBJECT=Welcome to your new email account
WELCOME_BODY=Welcome to your new email account, if you can read this, then it is configured properly!

###################################
# Web settings
###################################

# Path to the admin interface if enabled
WEB_ADMIN=/admin

# Path to the webmail if enabled
WEB_WEBMAIL=/webmail

# Website name
SITENAME=wesselbogers.com

# Linked Website URL
WEBSITE=http://wesselbogers.com

###################################
# Advanced settings
###################################

# Docker-compose project name, this will prepended to containers names.
COMPOSE_PROJECT_NAME=mailu

# Default password scheme used for newly created accounts and changed passwords
# (value: SHA512-CRYPT, SHA256-CRYPT, MD5-CRYPT, CRYPT)
PASSWORD_SCHEME=SHA512-CRYPT

**Comment by Andrwe** [comment]
Hi,

did you try the possible solutions documented here https://mailu.io/reverse.html ?

For further help the following information are necessary:
1) Is your reverse proxy running in a docker container or on the docker host?
2) What is the error message / behaviour you get?
3) What is the configuration of your reverse proxy concerning /admin?

Regards,
Andrwe

**Comment by wessel1512** [comment]
i have had my isu resolved 

see understanding exchange of words   

is it possibly that lets encrypt only work on the mail interfaces an that the web interfaces like: web mail, admin, are reachable via http for easier setup for a reverse proxy

kaiyouMailu (+mailu:tedomum.net)
Yes, and that mode is named mail-letsencrypt. It is only available on master currently though.
Tuesday
W
wessel1512
any say when this is implemented in the stable release
Wednesday

kaiyouMailu (+mailu:tedomum.net)
wessel1512: i would say we are way overdue a release but I am waiting after the config wizard first. I hope in July.

conclusion i need to what for the stable release Thant includes  mail-letsencrypt feature
