### ISSUE TITLE
config password plugin for roundcube

### ISSUE THREAD

**Issue by InnerPeace080** [Mailu/Mailu#490]
hi everybody.
i try to setup password plugin for round cube , but i can not change password 

have anyone help me config this. As i found on google have some config like this 
$config['password_driver'] = 'directadmin';

but this project not use directadmin.

thank all

**Comment by mmoo9154** [comment]
I'm havong this problem as well.  DOes anyone know what the correct way is to add the ability for users to change their own password?

**Comment by InnerPeace080** [comment]
For now , user can change their own password by login to '/admin' page . i m not try to use plugin anymore.

Thank y
