### ISSUE TITLE
DMARC missing (Rainloop)

### ISSUE THREAD

**Issue by v1ru535** [Mailu/Mailu#494]
Hi,

I've a problem with DMARC on my domain, I explain.

Previously I also had trouble with DKIM, about this issue:
https://github.com/Mailu/Mailu/issues/435
Now ok for the DKIM with the fix "use_esld = false".

But same with DMARC, DNS entries are set-up, all tests online don't see DMARC signature.

Have you a fix for this please.

Thanks!

[I'm running under version 1.5 docker-compose setup]
https://mailu.io/compose/setup.html

**Comment by v1ru535** [comment]
Sorry, it's a PEBCAK :$
So, I close this "not" issue.

**Comment by Jacob-Edwards** [comment]
Where do I need to set use_esld to false at?
