### ISSUE TITLE
Implement support for ARC

### ISSUE THREAD

**Issue by curry684** [Mailu/Mailu#495]
One of my 'users' ran into an issue today with a mail not arriving in his mailbox that we are forwarding to his Gmail. Turns out the original sender quite rightfully (it's a bank) has a draconic DMARC reject policy in place, and Gmail is respecting it quite rightfully (again, it's a bank). Long story short - SPF can never validate a forwarded email properly, even if all DKIM headers are left intact during forwarding.

The [ARC specification is currently experimental and intended to remediate this](http://arc-spec.org/). 

> ARC preserves email authentication results across subsequent intermediaries (“hops”) that may modify the message, and thus would cause email authentication measures to fail to verify when that message reaches its final destination. But if an ARC chain were present and validated, a receiver who would otherwise discard the messages might choose to evaluate the ARC results and make an exception, allowing legitimate messages from these indirect mailflows to be delivered.

Luckily Google is first in the foray:

> Google has deployed ARC in their email services, code libraries and a test suite are freely available, one commercial MTA already includes ARC support, and patches for popular mailing list managers (MLMs) will be released shortly (early 2018). 

And most importantly for Mailu:

> The commercial MTA MailerQ incorporates ARC, and the milters authentication_milter and OpenARC can be used to deploy ARC with the **Postfix**, Oracle Communications Messaging Server, and Sendmail MTAs.

So well, Mailu should support it soon methinks  😉

**Comment by curry684** [comment]
Thanks @ofthesun9!

**Comment by mindrunner** [comment]
Sorry for digging this old stuff out. I am currently using [docker-mailserver](https://github.com/tomav/docker-mailserver) and I am hitting exactly the same issue. Also mentioned [](https://github.com/tomav/docker-mailserver/issues/1346) and [](https://www.reddit.com/r/email/comments/6ivppl/forwarding_emails_and_dkimspfdmarc_whats_correct/).

Is this proper implemented and working with Mailu? I really consider migrating....

I saw [this](https://github.com/trusteddomainproject/OpenARC/issues/66) bug in the OpenARC project. Does this affect us?

**Comment by kaiyou** [comment]
Not that I am aware of, but that should require some specific testing. Do you have step by step instructions to reproduce?

**Comment by mindrunner** [comment]
Not really, I am using OpenArc now in docker-mailserver and it's looking good :)

**Comment by kaiyou** [comment]
I will try and test, since we meet the requirement of using the same key for signing dkim and arc indeed.

**Comment by mindrunner** [comment]
See https://github.com/trusteddomainproject/OpenARC/issues/124 for some of my headers with ARC signature.

**Comment by SomeGeek** [comment]
Is it possible to sign messages coming from a mailing list manager (arc / dkim)? To do so, mailu needs to have a web interface to create keys for the specified domain, like lists.domain.tld, even if the mails are not delivered within mailu itself.
