### ISSUE TITLE
Hardening against Server-Side Request Forgery (SSRF)  similar to CSRF attacks

### ISSUE THREAD

**Issue by Thorsten1976** [Mailu/Mailu#496]
- https://medium.com/poka-techblog/server-side-request-forgery-ssrf-attacks-part-1-the-basics-a42ba5cc244a
- https://medium.com/poka-techblog/server-side-request-forgery-ssrf-attacks-part-2-fun-with-ipv4-addresses-eb51971e476d
- https://medium.com/poka-techblog/server-side-request-forgery-ssrf-part-3-other-advanced-techniques-3f48cbcad27e

**Comment by kaiyou** [comment]
Do you see any case where Mailu is vulnerable to SSRF? I do not believe we run any request server side, do we?

**Comment by JonathanWilbur** [comment]
@Thorsten1976 can you elaborate? Have you actually found something that needs fixing?

**Comment by muhlemmer** [comment]
Unless somebody has a real case of a SSRF vulnerability, I believe this issue should be closed. Please reopen if an example can be given.
