### ISSUE TITLE
Enable server-side mail filtering (sieve support)

### ISSUE THREAD

**Issue by Thorsten1976** [Mailu/Mailu#497]
Support sieve/milter support, so that an user can configure server-side filters to avoid redundant filter setups on different clients.

Supported clients (remote configuration via sieve protocol) are roundcube or Thunderbird (via sieve addon).

- http://www.linux-magazin.de/ausgaben/2007/06/ausgesiebt/ (German)
- Sieve: http://sieve.info
- RFC 3028, „Sieve: A Mail Filtering Language“: http://tools.ietf.org/html/rfc3028
- Managesieve Draft: http://www.ietf.org/internet-drafts/draft-martin-managesieve-07.txt
- RFC 2033, „Local Mail Transfer Protocol“: http://www.ietf.org/rfc/rfc2033.txt
- Dovecot: https://wiki.dovecot.org/Pigeonhole/Sieve
- Sieve examples by Marcel Holtmann: http://www.holtmann.org/email/sieve/ (German)
- Avelsieve: http://email.uoa.gr/projects/squirrelmail/avelsieve.php
- Websieve: http://sourceforge.net/projects/websieve
- Roundcube: http://www.smartdomotik.com/2015/09/04/how-to-set-filters-in-roundcube-with-sieve/
- Thunderbird Sieve Addon: https://github.com/thsmi/sieve
- Sieve-Support for Emacs: http://josefsson.org/sieve/
- Sieve-Support for Mulberry: http://www.bath.ac.uk/bucs/email/sieve/mulberry-sieve.shtml
- Sieve Extension Support Matrix: http://wiki.fastmail.fm/wiki/index.php/SieveExtensionsSupportMatrix

**Comment by kaiyou** [comment]
The main current issue with Sieve is Mailu fonrtend and poor long term support.
I definitely agree about having a server-side filtering system, unfortunately sive is not supported in nginx as a mail reverse proxy. Also, no server supports proxying sieve and having TLS. @mildred opened a PR #428 on the topic, but we still need to have a proper configuration wizard before we merge this.

Another approach I like is converging to a flexible filtering configuration interface in the admin UI.

**Comment by kaiyou** [comment]
I will start enabling this on top of #612

**Comment by benbucksch** [comment]
Thank you for this wonderful feature! :1st_place_medal:

**Comment by kshitijkurandwad211** [comment]
Hey, I'm trying to setup filter for my email. I have Snappy mail as my webclient but there is no direct filter option. Even after adding script its doest work. Can you please inform how to activate filters in snappy mail. As In roundcube on demo website it works

**Comment by nextgens** [comment]
@kshitijkurandwad211 file a user support ticket under 'discussion' if you need help.
