### ISSUE TITLE
User Changeable Passwords

### ISSUE THREAD

**Issue by mmoo9154** [Mailu/Mailu#503]
I am using the Roundcube webmail client.

There does not appear to be any way for regular users to change their password.  Currently, the only way to provide this capability is to make every user an administrator and allow them to go into the https//example.com/admin/ui/ page.

I have found a few mentions of pulgins that might provide this capability, but I don't see how to change the Roundcube configuration with .env or docker-copose.yml.

Does anyone know if the Rainloop webmail server allows users to change their password?

Does anyone know how to configure Roundcube to allow users to change their password?

Does anyone know how to specify Roundcube configurations through .env, docker-compose.yml, or some other mechanism I can use through docker-compose?  I'm not eager to reach into the containers directly and tweak them since that kind of configuration tends to be forgotten over time, and leads to trouble when upgrading or recovering from a crash in the future.

**Comment by mmoo9154** [comment]
This is a more detailed statement of #490, btw.  I opened this issue because my use case does not allow me to give admin privileges to all users.

**Comment by hoellen** [comment]
Users can change their password in in the /admin panel without being an administrator.
Rainloop also handles password changes with a plugin. But it has not been implemented for Mailu, yet. 
I never used Roundcube, so I don't know something about the other questions.

**Comment by mmoo9154** [comment]
@hoellen, that is **exactly** what I needed.  Thank you.
