### ISSUE TITLE
Add GPG plugins/options for Webmails (Roundcube, Rainloop)

### ISSUE THREAD

**Issue by v1ru535** [Mailu/Mailu#506]
Hi all,

Is it possible to add the choice to install the gpg plugin for webmails in.env?
Otherwise, is it possible to install it in base, and then set it or not directly in webmails configurations?

Thanks in advance.

**Comment by kaiyou** [comment]
Would you prefer to add plugins using an environment variable or be able to extend the roundcube configuration using overrides?

**Comment by v1ru535** [comment]
Thx @kaiyou.

I think add plugins using an environment variable is a good option.
But if it's easier for you to implement the possibility to extend the roundcube configuration using overrides, it's good too.

The goal is to be able to encrypt my mails directly from the webmail without passing by an external client.

Thanks for the work on this project!

**Comment by PMK** [comment]
+1

**Comment by ulm0** [comment]
Yep, using gpg might be a really nice feature to have.
