### ISSUE TITLE
How can I donate to you? Patreon? Bitcoin?

### ISSUE THREAD

**Issue by taoeffect** [Mailu/Mailu#508]
Hello, you seem to have created something really quite special here, and I've noticed that in some comments you've said that you haven't had time to implement certain features.

Have you considered the possibility of dedicating more time to this project through community support? It would be a real shame if it were abandoned.

I would be happy to donate monthly to support your work via Patreon, and also send donations via cryptocurrency if that is something that you think would work out, and I'm sure many others would too.

**Comment by curry684** [comment]
@kaiyou agreed, I'll also happily join a Patreon if you make one to support your excellent work!

**Comment by kaiyou** [comment]
I have considered that possibility, yet unfortunately I cannot manage any free time from work and am therefore not able to accept such donations myself.

However, if there is a platform where people can pay for features that anyonce may contribute, or if someone can step up and get some donations for spending time on Mailu, I would be more than happy to either merge more PR or even provide write access to the repository once a trust relationship is established :)

**Comment by HorayNarea** [comment]
On www.bountysource.com one can add issues/feature requests and people who want that get done can through money on that specific issue/request and the person who resolves it can claim the money, sounds like what you want, right?

**Comment by taoeffect** [comment]
> yet unfortunately I cannot manage any free time from work 

Have you considered the possibility of Mailu becoming your primary source of income? Is there some number/goal you'd need to reach for you to consider that? (Understand if you'd rather not say.)

**Comment by kaiyou** [comment]
I have but I do not believe I would like it. My day job is really diverse and enriching and I want it to remain this way while Mailu is a side project that I sometimes have much time to spend on and some other times less (or close to none unfortunately).

I am really open to both models though: adding bounty to important issues and maybe so some tidying among them so donators get a clear picture of what is in progress. Or guide someone motivated enough to spend more time on the project and get donations from his or her work.

**Comment by kaiyou** [comment]
What model sounds best to you? (I have very little experience on the matter)

**Comment by HorayNarea** [comment]
Maybe having something like a patreon and @kaiyou decides who (himself or a/multiple contributor/s) gets the donations for a particular month would be a way to fund Mailu-development without that much meta-work?

**Comment by taoeffect** [comment]
You might also want to look at [OpenCollective](https://opencollective.com), I've seen many projects using that too.

**Comment by curry684** [comment]
Right now I'd say just go for the patreon? There's no commitment involved whatsoever in both directions, it's just donations for work well done. [Ondrey Sury for example](https://www.patreon.com/oerdnj) gets a few hundred per month for doing the hard work on Debian/Ubuntu PHP packaging. It's not making him rich, it's just a bonus for doing what he's already doing, and nobody's bitching at him if he's not releasing a new package the same day because "they are paying him to". That's not how Patreon works. It's a lot of people paying a handful of $ per month because otherwise it'd cost them days or hundreds of $ to do it otherwise.

**Comment by kaiyou** [comment]
I did go for the Patreon and will expose it somewhere. You can access it at https://patreon.com/kaiyou. Closing here, we'll discuss on #593 how I can properly redistribute donations if any.
