### ISSUE TITLE
Move mail from old Dovecot server

### ISSUE THREAD

**Issue by jmsosso** [Mailu/Mailu#526]
Hi,

I have a postfix/dovecot mail server running for some domains and I want to move it to Mailu. Mailu is a very good choice to run a small server without having to do some complicate configuration tasks. I like it very much.

My first idea was to move all mail files from the old server to Mailu. The directories for each mailbox, the one that have the subdirectories cur, new, .Sent, etc.

This doesn't works. After copy the files from my dovecot into the mailu/data/mail/xxxx@xxxx directory I get an error when I try to log in with Roundcube.

The second plan was to use the Mailu built-in fetchmail feature. This works but only moves the inbox folder and not the other user folders. Also I want to move Sent, Draft, etc.

Any idea of how accomplish this?

Thanks.

**Comment by kaiyou** [comment]
Moving directories should work just fine if you are using the Maildir format. Could you elaborate on your error, probably some permission issue or format issue?
