### ISSUE TITLE
dovecot is not building anymore (master  & 1.5)

### ISSUE THREAD

**Issue by ofthesun9** [Mailu/Mailu#528]
Sending build context to Docker daemon  19.97kB
Step 1/7 : FROM alpine:edge
 ---> 5c4fa780951b
Step 2/7 : RUN echo "@testing http://nl.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories  && apk add --no-cache      dovecot dovecot-sqlite dovecot-pigeonhole-plugin dovecot-pigeonhole-plugin-extdata      rspamd-client@testing python py-jinja2
 ---> Running in 46c5496fc0b3
fetch http://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
fetch http://nl.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  dovecot-pigeonhole-plugin-extdata (missing):
    required by:
                 world[dovecot-pigeonhole-plugin-extdata]
The command '/bin/sh -c echo "@testing http://nl.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories  && apk add --no-cache      dovecot dovecot-sqlite dovecot-pigeonhole-plugin dovecot-pigeonhole-plugin-extdata      rspamd-client@testing python py-jinja2' returned a non-zero code: 1

**Comment by InnerPeace080** [comment]
hi there. 

I meet problem when build mailu too. 
I when i use alpine:3.7 
everything seem fine . I thing have some thing break change in alpine:lastest image 

i must change every alpine in mailu project to alpine:3.7

hope it will help you

**Comment by ofthesun9** [comment]
Thanks @InnerPeace080 , dovecot is now building !

**Comment by kaiyou** [comment]
Indeed, will change this right away until we get rid of the extdata dependency (soon). Unfortunately someone at Alpine decided that the extension we contributed a year ago was too much work to maintain and just removed it.

**Comment by christhomas** [comment]
This recently bit my ass because I wanted to use ARGON2I password encryption and I needed dovecot 2.3.x and that meant I had to use the edge repository, but that meant I couldn't install this dependency also :(
