### ISSUE TITLE
Binding ipv6 to all interfaces

### ISSUE THREAD

**Issue by 4integration** [Mailu/Mailu#537]
HI,

I am setting up Mailu with docker-compose and it is behind a NAT. Therefore I want to listen on all interfaces and https://mailu.io/compose/setup.html#set-the-common-configuration-values recommends 0.0.0.0 on ipv4.
But tried some different on ipv6 like

```
# Address where listening ports should bind
BIND_ADDRESS4=0.0.0.0
BIND_ADDRESS6=2002:0:0:0:0:0:0:0
```

But get:

```
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.front.ports is invalid: Invalid port "2002:0:0:0:0:0:0:0:110:110", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
services.front.ports is invalid: Invalid port "2002:0:0:0:0:0:0:0:143:143", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
services.front.ports is invalid: Invalid port "2002:0:0:0:0:0:0:0:25:25", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
services.front.ports is invalid: Invalid port "2002:0:0:0:0:0:0:0:443:443", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
services.front.ports is invalid: Invalid port "2002:0:0:0:0:0:0:0:465:465", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
services.front.ports is invalid: Invalid port "2002:0:0:0:0:0:0:0:587:587", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
services.front.ports is invalid: Invalid port "2002:0:0:0:0:0:0:0:80:80", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
services.front.ports is invalid: Invalid port "2002:0:0:0:0:0:0:0:993:993", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
services.front.ports is invalid: Invalid port "2002:0:0:0:0:0:0:0:995:995", should be [[remote_ip:]remote_port[-remote_port]:]port[/protocol]
```

How shall I properly define BIND_ADDRESS6?

**Comment by hoellen** [comment]
Hey, which version of *docker-compose* do you use? I think you need a newer version of it. Then it should work. 
Or as a workaround you can comment the lines with `$BIND_ADDRESS6` in the `docker-compose.yml`file in.

**Comment by 4integration** [comment]
Hi,
Ahhh, that could be the reason.
Running Ubuntu 16.04 LTS and installed it as in https://docs.docker.com/install/linux/docker-ce/ubuntu/

```
$ sudo docker version
Client:
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:11:02 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.0-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       0ffa825
  Built:            Wed Jul 18 19:09:05 2018
  OS/Arch:          linux/amd64
  Experimental:     false

$ sudo docker-compose version
docker-compose version 1.8.0, build unknown
docker-py version: 1.9.0
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
```

Will try out with your workaround - or try to a way to run a newer version.
Thanks for your tip!

**Comment by hoellen** [comment]
According to [this](https://stackoverflow.com/questions/39649458/how-to-assign-ipv6-address-with-docker-compose) you need at least docker-compose 1.9
But I think I had some trouble with this version too. I am running currently version 1.22 
Maybe you can upgrade it with pip?

**Comment by 4integration** [comment]
Tried the workaround and got an error message that port 443 was occupied - which it is due to a Nginx reverse proxy.

Also went for a newer docker-compose and then it complained about 995 being occupied which it isn't?!?
Now running:
```
docker-compose version 1.18.0, build 8dd22a9
docker-py version: 2.6.1
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
```

So kept the workaround with commented BIND_ADDRESS6 and changed the port mappings:
```
    - "$BIND_ADDRESS4:8880:80"
    - "$BIND_ADDRESS4:8443:443"
```
It seems to start but cannot access the admin UI

**Comment by 4integration** [comment]
For now I went for poste.io - works well with my other setup.
But will take another round with Mailu later when I have more time - since I like the project
