### ISSUE TITLE
Increase attachment size limit

### ISSUE THREAD

**Issue by bilyboy785** [Mailu/Mailu#542]
Hello, 

How can web change the max file limit of attachment in Roundcube ?

Version 1.5

**Comment by kaiyou** [comment]
Currently you can't, you could mount a new ``php.ini`` with a different ``upload_max_filesize`` and ``post_max_size``. Ideally, you would need to generate a dynamic ``php.ini``. The best way to go is probably to create the same kind of ``start.py`` as for other containers and compile a ``php.ini`` that uses the max mail size environment variable.

**Comment by muhlemmer** [comment]
@ionutfilip
