### ISSUE TITLE
Contact Database

### ISSUE THREAD

**Issue by felipelpm** [Mailu/Mailu#550]
Is possible to implement a contact database for the admin e-mail, and all the others e-mails under the same domain inherit those contacts?

**Comment by christhomas** [comment]
I think that functionality is not part of the MTA/MDA setup, this is just a wrapper around postfix/dovecot with a few things like rspam/clamav. But what you're talking about is a contact manager with account management, like a full on exchange like suite. 

It's probably a good idea to look into FOSS solution for that and try to implement it next to your email server. Hopefully figuring it out and coming back here with a solution for everybody to share.

**Comment by kaiyou** [comment]
Agreed with @christhomas this is currently out of the scope of Mailu, which focuses on implementing the mail server part. Will reopen if someone wants to contribute some documentation about setting it up though.

**Comment by benyanke** [comment]
Note: this may be something Radicale can do with just a bit of tweaking.
