### ISSUE TITLE
[docker swarm] - Hostname resolving in start.py should retry on failure

### ISSUE THREAD

**Issue by muhlemmer** [Mailu/Mailu#555]
During testing of PR #551, some containers enter in failed state. Docker attempts a few restarts and eventually gets everything to run. This behavior is random and only during deploy phase.

```
[root@sun mailu]# docker stack ps mailu
ID                  NAME                IMAGE                 NODE                       DESIRED STATE       CURRENT STATE               ERROR                       PORTS
kzpw16he8ztk        mailu_fetchmail.1   mailu/fetchmail:1.5   sun.mohlmann.solutions     Running             Running 5 seconds ago
3wya1wokuc3c        mailu_antispam.1    mailu/rspamd:1.5      sun.mohlmann.solutions     Running             Running 8 seconds ago
vjopeoeppfzn        mailu_smtp.1        mailu/postfix:1.5     sun.mohlmann.solutions     Running             Running 15 seconds ago
pzk3t3izd1j5        mailu_imap.1        mailu/dovecot:1.5     mars.mohlmann.solutions    Running             Running 19 seconds ago
c6hnjkkre9r0        mailu_front.1       mailu/nginx:1.5       venus.mohlmann.solutions   Running             Running 21 seconds ago                                  *:143->143/tcp,*:25->25/tcp,*:80->80/tcp,*:443->443/tcp,*:993->993/tcp,*:110->110/tcp,*:995->995/tcp,*:587->587/tcp,*:465->465/tcp
cs4qmo5i4u3p        mailu_webdav.1      mailu/none:1.5        venus.mohlmann.solutions   Running             Running 28 seconds ago
9h3l7o65w4c5        mailu_admin.1       mailu/admin:1.5       mars.mohlmann.solutions    Running             Running 26 seconds ago
wclsbcrrpte2        mailu_antivirus.1   mailu/clamav:1.5      mars.mohlmann.solutions    Running             Running 32 seconds ago
shf4gl4udqso        mailu_redis.1       redis:alpine          sun.mohlmann.solutions     Running             Running 32 seconds ago
l8h44qiaqx7y        mailu_admin.1       mailu/admin:1.5       mars.mohlmann.solutions    Shutdown            Failed 32 seconds ago       "task: non-zero exit (1)"
z09y2mb3b6ru        mailu_smtp.1        mailu/postfix:1.5     sun.mohlmann.solutions     Shutdown            Failed 37 seconds ago       "task: non-zero exit (1)"
yny7l9cepjv6         \_ mailu_smtp.1    mailu/postfix:1.5     sun.mohlmann.solutions     Shutdown            Failed about a minute ago   "task: non-zero exit (1)"
x06zokhxaira         \_ mailu_smtp.1    mailu/postfix:1.5     sun.mohlmann.solutions     Shutdown            Failed 2 minutes ago        "task: non-zero exit (1)"
xyzroke6fwhv         \_ mailu_smtp.1    mailu/postfix:1.5     sun.mohlmann.solutions     Shutdown            Failed 2 minutes ago        "task: non-zero exit (1)"
ngii9d0j6xl4        mailu_webmail.1     mailu/roundcube:1.5   sun.mohlmann.solutions     Running             Running 3 minutes ago
```

After investigating the logs, all the failed containers have a log entry as such:

```
[root@sun mailu]# docker logs 2f08ab912617
Traceback (most recent call last):
  File "/start.py", line 12, in <module>
    os.environ["FRONT_ADDRESS"] = socket.gethostbyname("front")
socket.gaierror: [Errno -2] Name does not resolve
```

The culprit is in the image's `start.py`. Example from postfix:

```
# Actual startup script
os.environ["FRONT_ADDRESS"] = socket.gethostbyname(os.environ.get("FRONT_ADDRESS", "front"))
os.environ["HOST_ANTISPAM"] = os.environ.get("HOST_ANTISPAM", "antispam:11332")
os.environ["HOST_LMTP"] = os.environ.get("HOST_LMTP", "imap:2525")
```

This failures seem to be caused by the fact, that the script tries to resolve to a service which is not up yet. 

~~But it exposes a deeper problem. Fellow hosts are resolved only once and to a single IP. This means that if the application is scaled up to more containers, those additional containers will never be resolved to and thus completely ignored. This will also prevent docker from _round robin_ resolving to balance network requests between service instances. From the [docs:](https://docs.docker.com/docker-cloud/apps/service-links/#using-service-and-container-names-as-hostnames)~~

> ~~A container `proxy-1` on the same stack could discover all `webapp` containers by using the service name `webapp` as hostname. Connecting to the service name resolves as an A round-robin record, listing all IPs of all containers on the service `webapp`.~~

~~In my humble opinion, the resolving in `start.py` should be taken out. The configuration of the daemons should be set up to use the Docker host-name instead.~~

~~@kaiyou, where there any special considerations when the resolving was setup in `start.py`? If there are no mayor objections, I would like to start experimenting to get this to work in a more dynamic way.~~

**Comment by muhlemmer** [comment]
It actually resolves to the VIP. So shouldn't be an issue. We just have to prevent early startup failure by re-trying and/or delaying.

**Comment by muhlemmer** [comment]
Note: above mentioned PR does not yet solve #530

**Comment by kaiyou** [comment]
Should we close this?
