### ISSUE TITLE
Split frontend and backend

### ISSUE THREAD

**Issue by curry684** [Mailu/Mailu#56]
First of all - great job on this project. I've actually been looking for months for a future proof alternative to a simple mail solution and all the stock solutions like Axigen and Zimbra are terrible overkill for my use case. Poste.io showed up on my radar and I really like what it's doing, but it's too obviously developed closed source by a single developer to rely on it with a business regrettably, besides $349 being terribly overpriced for a beta product. It's also fundamentally flawed in trying to put all services into one big container instead of deploying scalable microservices. Your project has great potential and I think with some proper exposure it could really gain traction as a de facto Dockerized mail stack.

I do however also think the current approach is too monolithic. I have no Python developers in my company, and that blocks us from customizing and extending the admin, while I would love to help there. It would be great if, instead of an admin, you would expose a REST API instead so anyone can write their own admin instead. Same kinda goes for Roundcube, I don't think it belongs in the mail stack itself (I'd prefer Rainloop myself which is also FOSS if unbranded). It would be good to separate webmail and the current admin to optional 'extension' packages.

An added advantage would be that it would become pretty trivial to add a CLI interface for the hardcore sysadmins as well in another container.

**Comment by kaiyou** [comment]
Thank you for the analysis, and you are making some very good points.

Regarding the Webmail and individual components, I implemented some variable-based configuration to make it easy for us to ship any other Webmail than Roundcube. It should be just as easy to use your own if you modify the ``docker-compose.yml`` file or host the Webmail separately. I plan on providing Rainloop and Squirrel pretty soon as drop-in replacements for Roundcube.

Regarding the API, I do agree that having a simple REST API and a Javascript application on top of it would be amazing. It is a lot of work however and was not an option in the past months. Now that the project has a couple users and contributors, we should seriously consider it.

It involves a lot of work however and will probably not be available in a near future unless someone motivated enough contributes it.

**Comment by curry684** [comment]
Am I correct in assuming all configuration currently managed by the admin is in the Sqlite database, and it's not modifying or reading anything else right now?

**Comment by kaiyou** [comment]
That would be ideal. If you have a look at models.py, you will notice that it does also read and write DKIM key files for now as I wasn't able to configure rmilter to read from sqlite.

**Comment by curry684** [comment]
That's not bad per se. Everything in DB would be ideal indeed, but not every options is ever going to be compatible with that. I think you're fine if you expose 2 folders to the outside world, being config and data, with the DB in the first, as it makes backups and scalability easiest. Having a subfolder 'DKIM' in config isn't harmful imho, as I can still restore the server from a tarball of that directory.

**Comment by kaiyou** [comment]
Log parsing and aggregation would be nice to have, did not have time to implement it yet. At least some statistics and access to the latest log lines from the admin panel would be nice. I will create some issues.

Regarding rainloop, I just implemented it, see #58

**Comment by kaiyou** [comment]
I have been working on this for a couple days now. The current design is based on Hug for the backend and React+Redux for the frontend. It should be available in a couple weeks and will push as soon as I have all the (unfinished) pieces together.

**Comment by muratcorlu** [comment]
Do you have any progress about that? I'm also looking for an email server solution with a rest api support. This project seems very promising but with lack of API support. When I have a quick look to your code, I thought that, it could be not so hard to create a rest api with the current admin ui views. For example, this is current implementation:

```python
# /core/admin/mailu/ui/views/users.py

@ui.route('/user/list/<domain_name>', methods=['GET'])
@access.domain_admin(models.Domain, 'domain_name')
def user_list(domain_name):
    domain = models.Domain.query.get(domain_name) or flask.abort(404)
    return flask.render_template('user/list.html', domain=domain)
```

Just adding another route for an REST endpoint and defining template response depending on requested content type, without changing logical part, it can be easy to add REST endpoints to the admin.

```python
# /core/admin/mailu/ui/views/users.py

@ui.route('/user/list/<domain_name>', methods=['GET'])
@ui.route('/users/<domain_name>', methods=['GET'])
@access.domain_admin(models.Domain, 'domain_name')
def user_list(domain_name):
    domain = models.Domain.query.get(domain_name) or flask.abort(404)
    template_name = 'user/list.html'
    if request_wants_json():
        template_name = 'user/list.json'
    return flask.render_template(template_name, domain=domain)
```

If this can be a way to have a REST API in this project, I can try to help with a pull request.

**Comment by kaiyou** [comment]
My initial goal was to only expose a REST API and then write the admin interface as a static web app. Current problem is I do not have enough time to focus on learning about static web app libraries and stacks.

**Comment by muratcorlu** [comment]
If you can handle the API part, someone else can help about FrontEnd as a second phase. I also can help about FrontEnd.

**Comment by kaiyou** [comment]
I'll close this issue as many more precise issues cover the topic already.
