### ISSUE TITLE
[rspamd] Preserve antispam history on container restart

### ISSUE THREAD

**Issue by sam2kb** [Mailu/Mailu#561]
Is there any reason why we don't keep the history? I tried enabling it with the following override, but it didn't work.
Do I need to enable **history_redis** module first or is there anything else I'm missing?

overrides/rspamd/history_redis.inc
```
history_redis {
  servers = "redis";
}
```

**Comment by hoellen** [comment]
According to the config file `/etc/rspamd/modules.d/history_redis.conf` rspamd search the override for the module history_redis in `override.d/history_redis.conf`. 
And you should remove the `history_redis {` part, otherwise he complains about nested config. 

So you should try a file `overrides/rspamd/history_redis.conf` with just 
```servers = "redis";```

**Comment by sam2kb** [comment]
I changed that, the log shows the following, but the history is still empty after **docker-compose down**

```
 #1(main) <sq4g18>; lua; lua_redis.lua:193: using default redis server for module history_redis
#1(main) <sq4g18>; cfg; rspamd_init_lua_filters: init lua module history_redis
```

**Comment by hoellen** [comment]
I changed it in my instance too  and if I do a configdump of the running redis container the override is working. Also in my redis instance are now keys which start with `rs_history*`.

You can check with the following, wether the override has worked:
`docker exec mailu_antispam_1 rspamadm configdump history_redis`

**Comment by sam2kb** [comment]
Ah, that's why. I used .inc instead of .conf
The history is still not restored after `docker-compose down `

```
*** Section history_redis ***
nrows = 600;
key_prefix = "rs_history";
subject_privacy = false;
servers = "redis";
compress = true;
*** End of section history_redis ***
```

**Comment by khannurien** [comment]
Has anyone figured it out?

Shouldn't keeping the history be default behavior?

**Comment by kaiyou** [comment]
It should be, marking this as an enhancement to be made pretty soon, using redis sounds like the right option.

**Comment by FlatKey** [comment]
Fixed it for me by setting the hostname of the container explictly, cause history_redis uses it as part of the redis key. Now the is shown after a **docker-compose down**.

**Comment by Waester** [comment]
@muhlemmer I think this should be reopened as it is not entirely fixed yet.

As mentioned by @FlatKey it works only if the container has a explicit hostname (https://rspamd.com/doc/modules/history_redis.html).

But this is not the case yet, containers use their randomly generated container id on creation as hostname.

To fix this, I did something like this in my docker-compose.yml.

  _antispam:
    **hostname: ${COMPOSE_PROJECT_NAME}_antispam**
    image: mailu/rspamd:$VERSION
    restart: always
    env_file: .env
    volumes:
      - "$ROOT/filter:/var/lib/rspamd"
      - "$ROOT/dkim:/dkim"
      - "$ROOT/overrides/rspamd:/etc/rspamd/override.d"
    depends_on:
      - front_

**Comment by Waester** [comment]
@muhlemmer I think this should be reopened as it is not entirely fixed yet.

As mentioned by @FlatKey it works only if the container has a explicit hostname (https://rspamd.com/doc/modules/history_redis.html).

But this is not the case yet, containers use their randomly generated container id on creation as hostname.

To fix this, I did something like this in my docker-compose.yml.

  _antispam:
    **hostname: rspamd**
    image: mailu/rspamd:$VERSION
    restart: always
    env_file: .env
    volumes:
      - "$ROOT/filter:/var/lib/rspamd"
      - "$ROOT/dkim:/dkim"
      - "$ROOT/overrides/rspamd:/etc/rspamd/override.d"
    depends_on:
      - front_

**Comment by Waester** [comment]
@kaiyou @muhlemmer I think this should be reopened as it is not entirely fixed yet.

As mentioned by @FlatKey it works only if the container has a explicit hostname (https://rspamd.com/doc/modules/history_redis.html).

But this is not the case yet, containers use their randomly generated container id on creation as hostname.

To fix this, I did something like this in my docker-compose.yml.

  _antispam:
    **hostname: rspamd**
    image: mailu/rspamd:$VERSION
    restart: always
    env_file: .env
    volumes:
      - "$ROOT/filter:/var/lib/rspamd"
      - "$ROOT/dkim:/dkim"
      - "$ROOT/overrides/rspamd:/etc/rspamd/override.d"
    depends_on:
      - front_

**Comment by Diman0** [comment]
It is not possible to configure a static key for history_redis?

**Comment by Waester** [comment]
@Diman0 
It does not seem so, according to the storage model mentioned [here](https://rspamd.com/doc/modules/history_redis.html) the hostname is always appended.
```
Storage model
This module stores keys as following:
1. Get key prefix
2. Append hostname
3. Append _zst if history is compressed
```
The only thing that is modifiable is the key prefix. which can be set by **key_prefix** option.

**Comment by Diman0** [comment]
That is a pity. To handle this limitation I think at least the docker-compose.yml templates must be modified under:
https://github.com/Mailu/Mailu/tree/master/setup/flavors
For kubernetes it is most likely this template that must be modified:
https://github.com/Mailu/Mailu/blob/master/docs/kubernetes/mailu/security.yaml .
But we need to confirm this with someone who is familiar with kubernetes

**Comment by Diman0** [comment]
I know what files and what to edit for setting a static hostname for the setup utility (docker-compose ).

Can someone confirm if this is the correct edit for kubernetes?
Could I simply add a line with "hostname: rspamd" to set a fixed hostname here?
https://github.com/Mailu/Mailu/blob/5d1264e381590a14b547b81e8292398acacdc5c2/docs/kubernetes/mailu/security.yaml#L17
