### ISSUE TITLE
Creating a FAQ

### ISSUE THREAD

**Issue by muhlemmer** [Mailu/Mailu#564]
Just a suggestion, there are a number of issues open marked as `question`. It clobbers the issues list with items that are not really important.

We could transfer them to a FAQ page on the website, mailu.io and close them off here once answered and migrated.

**Comment by kaiyou** [comment]
Agreed, we just need a simple documentation page for these, which is as simple as creating an md file. Then we need to list interesting issues that need integration in the faq.

**Comment by muhlemmer** [comment]
So by creating a md file, you mean it will be Github hosted and not included in the documentation site? (Which is .rst file based).

As for nominating: on the issue which would be interesting for inclusion, just mention this issue. This can then work as a meta-issue. People can then collaborate to do the conversion. It can be helpful to reopen nominated issues until inclusion is done.

We can work of this query link: https://github.com/Mailu/Mailu/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Aquestion. The link itself might also be included in the FAQ for reference.

**Comment by kaiyou** [comment]
Ok for mentioning this issue. And I meant a rst file indeed, for proper inclusion in the docs and website :)

**Comment by khannurien** [comment]
Is there a public repo where we can contribute to this FAQ?

**Comment by muhlemmer** [comment]
It is in my intention to provide a FAQ page as scaffolding in the near future, here in the GitHub repository. It will be a .rst document as part of the main documentation package.


On September 29, 2018 12:18:47 PM GMT+02:00, Vincent <notifications@github.com> wrote:
>Is there a public repo where we can contribute to this FAQ?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Mailu/Mailu/issues/564#issuecomment-425633981

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by muhlemmer** [comment]
I've started work on the documentation. Just have a small list of docs remarks I want to resolve first, then I will work on the FAQ.

**Comment by muhlemmer** [comment]
Due to the tag migration, some tags were lost. Today I've went through:
- All open and closed issues without tags
- All issues with tag ``topic/docs``
- All issues with tag ``type/question``

All the issues I see fit for inclusion in the FAQ are labeled ``faq/include``. Some of them are related and might be condensed to a single entry. I'll remove the tags from issues I'm done with.

Issues related to troubleshooting I've labeled as ``faq/troubleshooting``. So this means errors that resulted out of miss-configuration where the user received a solution in the issue conversation. In the faq I will include a link to list all this issues, so users have the ability to see if their problems already have a solution.

If I missed something, please add one of the tags ;).

**Comment by muhlemmer** [comment]
The first part is written: the informational chapter. @kaiyou , if you have some time can you please read it and let me know if there are any comments.

https://github.com/usrpro/Mailu/blob/feat-faq/docs/faq.rst

**Comment by kaiyou** [comment]
This is a very good start indeed, and I think that even your *todo* is not a required change for a first merged version of the faq.
