### ISSUE TITLE
[k8s] Specs required

### ISSUE THREAD

**Issue by xaviablaza** [Mailu/Mailu#566]
I'm running a 4-node cluster with these specs on DigitalOcean:
![image](https://user-images.githubusercontent.com/25378966/43988339-438b693e-9d66-11e8-9c13-7eb9aed4e3af.png)

I can't seem to boot following the instructions outlined on: eb9649db4e1daa59271d51cc34ea4ee478cc2294

My containers are failing to schedule due to:
`0/4 nodes are available: 4 Insufficient cpu, 4 Insufficient memory.`

Any tips or advice would be greatly appreciated!

**Comment by briantopping** [comment]
It would appear that more than one CPU and 1GB of RAM are required, yes? 

Use `kubectl get pods --all-namespaces` and `kubectl describe pod <name>` to see more concrete information.

**Comment by xaviablaza** [comment]
I've figured this out. Thanks Brian.

**Comment by briantopping** [comment]
Great! Did you make any changes to the `kubernetes-mailu.yaml` that you can share?
