### ISSUE TITLE
mailu/clamav - docker image is missing data volume

### ISSUE THREAD

**Issue by hordijk** [Mailu/Mailu#568]
The docker image mailu/clamav expects `/data` to be present.
If this image is used on its own without the [Mailu docker compose configuration](https://mailu.io/compose/setup.html), the user should know the /data volume must be created. 

The Mailu docker compose does create a  the data volume inside the container in: https://github.com/Mailu/Mailu/blob/f506966abc5ec5452f7db599a11e16d7cc497e80/docs/compose/docker-compose.yml#L69-L75

If the /data volume is added to the [dockerfile](https://github.com/Mailu/Mailu/blob/master/optional/clamav/Dockerfile) of mailu/clamav it will be created automatically or can be mapped using the volume mapping, just like the docker-compose configuration.

If the Dockerfile cannot be changed the read me/instruction for the mailu/clamav can be improved to clarify a /data volume must be created. 

Let me know the preferred way to solve this so I can make a PR.

**Comment by muhlemmer** [comment]
Moving this to the Dockerfile, will probably break `.env` evaluation and will make the location static.

Please read the [development guidelines](https://mailu.io/contributors/guide.html) on the philosophy of this project:

> ## Philosophy
> 
> The mailserver is designed as a whole, some images are therefore **not best suited for reuse outside this project**. All images should however follow Docker best practices and be as generic as possible :
> 
> - even if not suited for reuse, they should be simple enough to fit as base images for other projects,
> - interesting settings should be available as **environment variables**
> - base images should be well-trusted (officiel Alpine or Debian for instance).

If you want to run ClamAV as a stand alone container, just copy have a look at the Dockerfile. It will be extremely simple to implement for yourself. Meanwhile, I'm voting to close this issue.
