### ISSUE TITLE
Auto-reply body empty with multiline messages

### ISSUE THREAD

**Issue by kaiyou** [Mailu/Mailu#57]
When the configured auto-reply body is a multiline string, the resulting reply email has an empty body.

**Comment by kaiyou** [comment]
After some investigation, it appears that the message is empty when leaving dovecot. There is no body send to postfix for the vacation message. Will investigate furter.

**Comment by kaiyou** [comment]
I finally traced back the issue to the dict access to SQLite, the root cause sounds close.

**Comment by kaiyou** [comment]
I was not yet able to disable the proxy and access the dict directly from the Dovecot process running sieve scripts. Sounds like the fix is going to be even trickier than expected.

**Comment by kaiyou** [comment]
After some more digging, it seems that despite my previous message and some warnings on the Dovecot IRC channel, the dictionary protocol is escaping data using ``t_str_tabescape`` and ``t_str_tabunescape``.

Using strace and a debugger, I was able to confirm that the string container tabs and new lines is properly escaped by the server when sent over the proxy socket, then properly unescaped, the bug seems to be located somewhere in Dovecot. I will try and find the root cause then solve it upstream with the Dovecot team.

**Comment by kaiyou** [comment]
Here is the current status of the work upstream : http://www.dovecot.org/list/dovecot/2016-October/105700.html

**Comment by kaiyou** [comment]
This was fixed in https://github.com/dovecot/core/commit/4f051c3082080b9d69ef12c3720c683cff34b0da

The patch will be included in Dovecot 2.2.26. I am working on a new Alpine package for Dovecot and will try to backport the patch to 2.2.25.

**Comment by kaiyou** [comment]
The patch was not included in 2.2.26-rc1. I will check that it is really going to be included in 2.2.26.

**Comment by kaiyou** [comment]
2.2.26 is finally there. Waiting for Alpine, maybe I will post tonight to patchwork : 

 http://www.dovecot.org/list/dovecot/2016-October/105867.html

**Comment by extremeshok** [comment]
Most excited about those 2.

- fts: fts_autoindex=yes was broken in 2.2.25 unless
fts_autoindex_exclude settings existed.

- fts-solr: Fixed searching multiple mailboxes (patch by x16a0)

__________________________________.    https://eXtremeSHOK.com     .__________________________________

**Comment by kaiyou** [comment]
Alpine patch is awaiting review: http://patchwork.alpinelinux.org/patch/2508/

**Comment by kaiyou** [comment]
The patch is out, ready for tagging 1.3 tonight.
