### ISSUE TITLE
Stats With AWStats

### ISSUE THREAD

**Issue by bilyboy785** [Mailu/Mailu#571]
It'll be great to integrate AWStats in Mailu to get info about how many mails, and size per day / week ;)

**Comment by benyanke** [comment]
I've been wondering about this as well. Perhaps even generating a daily report to send to an admin could be useful, so that you quickly know if your server's mail volume dramatically changes.

**Comment by bilyboy785** [comment]
Or just mount the maillog files and scan them with [pflogsumm](https://linux.die.net/man/1/pflogsumm) ?

**Comment by kaiyou** [comment]
Closing in favor of #1059
