### ISSUE TITLE
Using SMTP and POP

### ISSUE THREAD

**Issue by ManicPumpkin** [Mailu/Mailu#577]
Hey,

I have set up a virtual machine with some docker container running inside. Those containers are mainly Mailu containers. I set them up like mentioned on the Mailu website. My problem is, that I don't know how to set up the SMTP and POP for using the Mailu server with Outlook.
On the main website there is nothing mentioned like that.

Is there a manual or something where I can read, how the SMTP or POP settings have to be and how/where I have to set them?
Did I forget something before running my server?

Currently my sever is only reachable via an IP address on port 80.

Thank you and best regards,
Manic.

**Comment by christhomas** [comment]
The web admin is served from port 80.
The SMTP/POP for the MTA/MDA ports are 25, 143, 993, 465, 587
So I think you're not trying to right ports maybe? It could help to read up on the net how MTA/MDA work together to transfer and deliver email. I would suggest starting there.

**Comment by kaiyou** [comment]
I am closing this issue, feel free to reopen if you have any more questions
