### ISSUE TITLE
signup submit show The response parameter is missing

### ISSUE THREAD

**Issue by ahkui** [Mailu/Mailu#578]
![image](https://user-images.githubusercontent.com/14049597/44628410-dd0fd100-a971-11e8-9962-002865f4a2d5.png)

**Comment by kaiyou** [comment]
This is a bug when not enabling recaptcha.

**Comment by ahkui** [comment]
okay 
i fixed after add recaptcha client id and secret

**Comment by muhlemmer** [comment]
@ionutfilip. you know how to play with validation in Flask now ;).
