### ISSUE TITLE
Don't install nginx-ingress-controller as part of setup

### ISSUE THREAD

**Issue by christhomas** [Mailu/Mailu#579]
https://github.com/Mailu/Mailu/blob/f506966abc5ec5452f7db599a11e16d7cc497e80/docs/kubernetes/stable/kubernetes-nginx-ingress-controller.yaml#L31

I think its a mistake to install nginx-ingress-controller as part of mailu, it should be noted as an external dependency and instructions given to install it. The reason for this is because I've already got it installed, therefore to attempt to install your software will fail cause of that.

If you don't install it and I don't have it already installed, the worst that can happen is that I have an unreachable installation. Then if I read the instructions properly, I can see the part where I'm supposed to install it and do that myself.

Also, if you're on AWS, you already get ELB/ALB/NLB, so installing this "system" component, just means the setup is not really generic enough to be useful everywhere.

**Comment by muhlemmer** [comment]
@christhomas , can you please check your setup with the latest kubernetes documentation. Not a k8s user myself, but hopefully you'll get it to work using that.

Sorry, its not uploaded to the site yet, so you'll have to poke around GitHub for now.

**Comment by muhlemmer** [comment]
Closing due to no response. If this documentation update is simple to implement, feel free to open a PR.

**Comment by hacor** [comment]
Hello,

The Nginx Controller is not only a dependency, but it's a dependency especially configured to only handle the mail ports needed by Mailu.
The Nginx Ingress Controller (let's call it the Front Nginx Ingress Controller) is only routing the mail service ports to the correct service. So it's not just the standard Nginx Ingress Controller (who listens to Web input traffic) which listens on port 80 and 443. 

I'm using both together on my cluster for the moment and it works perfectly. The Front Ingress controller only reacts on the mail specific ports and the standard Nginx Ingress controller routes the traffic on ports 80 and 443. 
This option was chosen to make the installation of Mailu as simple as possible without the need to adapt each and everyones standard web traffic input configuration. 
I must say that I have no experience with AWS (I run a bare metal cluster) so I have no practical clue on how ELB works, but when it does route the e-mail ports as well, you just don't need to start the Front Nginx Controller.

Let me know if you have any more comments

Best regards.

**Comment by micw** [comment]
Closing (outdated, does neither apply to k8s yamls in 1.7 nor to 1.8 helm chart)
