### ISSUE TITLE
Cannot connect with Outlook 2016 (365)

### ISSUE THREAD

**Issue by bilyboy785** [Mailu/Mailu#582]
I tried to modify the nginx.conf and all SMTP / IMAP ports with and without security, and i cant find a way to add my account to Outlook. It's really strange ...

![Image](https://img.bouillaudmartin.fr/Pig5zQff/RFM6B0jb.png)

**Comment by zxpower** [comment]
It's known issue of Outlook - they don't support TLS auth out of the box.

You can try this: https://my.kualo.com/knowledgebase/33_windows---configuring-email/1403_how-to-enable-tls-v1.1v1.2-for-windows-78-and-outlook-200720102013.html

**Comment by muhlemmer** [comment]
The image suggests you setup outlook for POP3. But the description of your issue mentions IMAP.

Did you follow the documentation? By default there is no need to change nginx.conf.

Second, how long since you deployed the service? It can take some time for the `front` container to generate DH-keys. I found also that sometimes the process gets stuck and you need to remove and re-deploy.

```
docker-compose rm
docker-compose up -d
```

Please, also inspect the logs for any errors:

```
docker-compose logs
```

**Comment by muhlemmer** [comment]
I didn't know about the known issue. Try to follow @zxpower suggestion first.

**Comment by bilyboy785** [comment]
@muhlemmer i tried IMAP too, it's the same error. And my DH-keys are OK ;)
I can't find the base configuration for IMAP and SMTP, is it : 
 - IMAP : 143 TLS
 - SMTP : 587 TLS ?

**Comment by bilyboy785** [comment]
I tried your method @zxpower but not working.

**Comment by muhlemmer** [comment]
Are the Docker `iptables` setup correctly? Are the ports forwarded? Try polling `iptables -L` and inspect if you find the Mailu ports forwarded. Is your server behind a NAT? Then also make sure the router is forwarding correctly.

Maybe use tools like _nmap_ to see if there is something listening on the ports.

I use the same ports as you, no problems. (Not outlook)

**Comment by bilyboy785** [comment]
I block all but opened standard mail server ports and nmap is ok : 

nmap -sV -p 143,587 mx1.dcliccholet.com
Starting Nmap 7.70 ( https://nmap.org ) at 2018-08-27 15:17 CEST
Nmap scan report for mx1.dcliccholet.com (51.15.99.181)
Host is up (0.025s latency).
rDNS record for 51.15.99.181: mx1.frenchchill.com

PORT    STATE SERVICE    VERSION
143/tcp open  imap-proxy nginx imap proxy
587/tcp open  smtp       Postfix smtpd

**Comment by muhlemmer** [comment]
The screenshot response mentions "Authentication required".

1. Did you setup an user account in Mailu?
2. Did you provide a password in outlook config? (Select remember password) Or some option like: "Server requires authentication"
3. Did you provide the full mail address as username in outlook? (user@example.com)

**Comment by bilyboy785** [comment]
- I've got many user in Mailu, all ok in Webmail (user / password)
 - I use password in Outlook config with "Remember password" and Require Authentification
 - I provide the full mail address 

Thank's for your help !! ;)

**Comment by muhlemmer** [comment]
My last best guess: is the computer that is running outlook owned by a company and therefore managed by their IT department? I've had such a situation years ago where I could not use my employer's laptop to connect to any other mail server outside the company network.

Are users from other computers / other programs able to connect? Did you try something like Mozilla Thunderbird?

**Comment by muhlemmer** [comment]
Did you inspect the logs, as I suggested earlier? You can pas the `-f` options to follow the log life, as you are trying to log in from outlook. Maybe this would give you a clue of what is going on:

```
docker-compose logs -f
```

**Comment by bilyboy785** [comment]
Hello, it’s OK with these settings :
IMAP : 993 SSL No auth 
SMTP : 465 SLL With auth

This issue can be closed
