### ISSUE TITLE
Access logfile for Fail2ban

### ISSUE THREAD

**Issue by bilyboy785** [Mailu/Mailu#584]
Can we mount a volume for logs to use Fail2Ban ?

**Comment by v1ru535** [comment]
Same here, so I extract some lines from the docker-compose follow to be able to do the bans afterwards.
If one or more logs (front,smtp...) can be set up it would be great.
Thx

**Comment by bilyboy785** [comment]
Nice idea @v1ru535  !! 
Waiting for this feature <3

**Comment by oz123** [comment]
It turns out it's not only about `ufw` but some modifications on docker networking are needed:

https://askubuntu.com/questions/652556/uncomplicated-firewall-ufw-is-not-blocking-anything-when-using-docker

**Comment by v1ru535** [comment]
Personally I extract some strings from the docker logs and put everything in a log.

After that I extract IPs and null routing using ip command like that "ip route add blackhole <IP>".

It's waiting to do better naturally, but with that I already have over 2000 banned IPs.

Hope this helps you

**Comment by oz123** [comment]
I found a useful post about the issue:

http://blog.amigapallo.org/2016/04/14/configuring-fail2ban-and-iptables-to-get-along-with-docker/

**Comment by muhlemmer** [comment]
See above PR. I was annoyed I couldn't write something useful for the FAQ, so wrote an actual solution.

I'm looking into suitable regex for documentation, but that is not my field of sport. So help would be appreciated. The standard Nginx regex supplied by Fail2Ban don't catch the login fails for Mailu.

**Comment by muhlemmer** [comment]
Attempt 2, using Docker logging drivers. Please have a look.

**Comment by muhlemmer** [comment]
Implemented in #661, we can close this.

**Comment by v1ru535** [comment]
Thanks for this!

I went from version 1.5 to master to get these options, then added the necessary modifications on env and docker-compose.yml.
I added a jail and a rule to ban IPs on this pattern for fail2ban:
`client login failed: "Authentication credentials invalid" while in http auth state, client: [IP], server: 0.0.0.0:25, login: "someshit@domain.io"`
I filter on "client login failed" and get the IP, then all you have to do is adjust the number of failed login before the ban in fail2ban rule.
Now it works like a charm, thanks for the work.

_If you wish I can provide the jail for the faq._

**Comment by hoellen** [comment]
It would be nice if you could share the complete fail2ban rules here, so we can add it to the FAQ for other users.

**Comment by v1ru535** [comment]
For my environment, I put the log to syslog, so in env:
`LOG_DRIVER=journald`

For the jail, I've set blackhole route, but it's possible with iptable with:
`banaction = %(banaction_allports)s`
in replace on
`action = route[name=auth-ban]`

Jail with maxretry to be adapted according to needs:
```
# 3 ban in 1 hour > Ban for 1 hour
[auth-ban]
enabled = true
filter = bad-auth
logpath = /var/log/syslog
maxretry = 3
findtime = 3600
action = route[name=auth-ban]
bantime = 3600
```

Action fail2ban: "action.d/route.conf"
`blocktype = blackhole`

Filter fail2ban: "filter.d/bad-auth.conf"
```
# Fail2Ban configuration file
[Definition]

# Option: failregex
# Filter "client login failed" in the Syslog

failregex = .* client login failed: .+ client:\ <HOST>

# Option: ignoreregex
# Notes.: regex to ignore. If this regex matches, the line is ignored.
# Values: TEXT
#
ignoreregex =
```

It may also be useful to adjust the bantime of the recidive jail to fine-tune the configuration.

**Comment by flayks** [comment]
> For my environment, I put the log to syslog, so in env:
> `LOG_DRIVER=journald`
> 
> For the jail, I've set blackhole route, but it's possible with iptable with:
> `banaction = %(banaction_allports)s`
> in replace on
> `action = route[name=auth-ban]`
> 
> Jail with maxretry to be adapted according to needs:
> 
> ```
> # 3 ban in 1 hour > Ban for 1 hour
> [auth-ban]
> enabled = true
> filter = bad-auth
> logpath = /var/log/syslog
> maxretry = 3
> findtime = 3600
> action = route[name=auth-ban]
> bantime = 3600
> ```
> 
> Action fail2ban: "action.d/route.conf"
> `blocktype = blackhole`
> 
> Filter fail2ban: "filter.d/bad-auth.conf"
> 
> ```
> # Fail2Ban configuration file
> [Definition]
> 
> # Option: failregex
> # Filter "client login failed" in the Syslog
> 
> failregex = .* client login failed: .+ client:\ <HOST>
> 
> # Option: ignoreregex
> # Notes.: regex to ignore. If this regex matches, the line is ignored.
> # Values: TEXT
> #
> ignoreregex =
> ```
> 
> It may also be useful to adjust the bantime of the recidive jail to fine-tune the configuration.

I figured out that I have a lot of connections attempts from weird IPs and wanted to add a jail to fail2ban to block it, but I don't have much knowledge with it. Would you mind share your process to achieve that? That would be super useful! Thanks
