### ISSUE TITLE
Kubernetes FailedMount volume "certs" : secrets "letsencrypt-certs-all" not found

### ISSUE THREAD

**Issue by chansanto** [Mailu/Mailu#586]
Hi Team,

:( I'm checking with stable version 1.5 mailu and not using nginx but when i run kubectl apply -f kubernetes-mailu.yaml

Some pod can't complete because :
Warning  FailedMount            7s (x6 over 23s)  kubelet, ip-10-22-33-211.ap-southeast-1.compute.internal  MountVolume.SetUp failed for volume "certs" : secrets "letsencrypt-certs-all" not found

Could you help me :(

**Comment by muhlemmer** [comment]
@chansanto, can you please check your setup with the[ latest kubernetes documentation](https://github.com/Mailu/Mailu/tree/master/docs/kubernetes). Not a k8s user myself, but hopefully you'll get it to work using that.

Sorry, its not uploaded to the site yet, so you'll have to poke around GitHub for now.

**Comment by muhlemmer** [comment]
I am going to close this due to inactivity.
