### ISSUE TITLE
Feature Request: Disable an Account

### ISSUE THREAD

**Issue by benyanke** [Mailu/Mailu#595]
Sometimes, it is nice to disable an account without deleting it. That is - block all authentication and access, but keep it intact for later enabling.

**Comment by kaiyou** [comment]
Well, this is actually already possible in ``master``. Every user has a checkbox named "Enabled", which unchecked will disable the user completely.

**Comment by benyanke** [comment]
Looks like it's done in Master, so I'll close out.
