### ISSUE TITLE
CI / Automated Testing

### ISSUE THREAD

**Issue by benyanke** [Mailu/Mailu#596]
I am not sure how well this would work for a mailserver, but I could see real value in some sort of automated testing on build. At the very least, perhaps some simple checks like syntax checks of docker-compose.yml and Dockerfiles could be a good start.

Just putting the issue here so it's tracked.

**Comment by hoellen** [comment]
There are already issues for automated testing: #47 #487

**Comment by benyanke** [comment]
Mea culpa!
