### ISSUE TITLE
how to install 1.5.1 and/or updates

### ISSUE THREAD

**Issue by diresi** [Mailu/Mailu#598]
I'm currently running 1.5.1 via docker compose and was looking for updates.
However, it seems that only master images are available on docker hub.

What happened to the old images, and which should be available?
Are there no updates since 1.5.1?

**Comment by muhlemmer** [comment]
> Maybe this was the biggest mistake in the projects life, but indeed 1.5.1 was a temporary branch meant for backporting and testing large fixes for 1.5 after it was published.

Maybe in the future, we should use tags for releases. This fixes a release and in case of bugfixes, increment the the minor version in a tag. eg: 1.5 is update development and 1.5.x are tagged releases.

**Comment by kaiyou** [comment]
The issue is we want to build images including the fixes under the same tag as the original image so that a docker pull actually pulls the update. Branching is the only simple approach I found for this.

**Comment by diresi** [comment]
Ok, thanks. I'll try and downgrade.

About the docker tags, other projects add new patch versions (image:1.5.x) and also provide minor versioned images (image:1.5) pointing to the latest patch version. But I'm pretty sure you already knew that ;)

**Comment by diresi** [comment]
ftr: the downgrade from 1.5.1 to 1.5 and subsequent updates via docker pull went without any noticable problems. thanks!
