### ISSUE TITLE
Add fetchmail keep option

### ISSUE THREAD

**Issue by fabolhak** [Mailu/Mailu#60]
Hey,

thank you for this great project :). This makes my life a lot easier setting up a personal mail server.

I was wondering if it is possible to add the **keep** option for the fetchmail command. Similarly to the SSL option the user should be able to decide, whether to keep the emails on the remote server or not. I think this is not a lot of work todo and I would volunteer to provide a pull request in the next week.

However I wanted to check with you first, before digging in the code.

What do you think? :)

**Comment by kaiyou** [comment]
That should be really straightforward to add. Simply add a column with the proper migration script and implement the behaviour in the Fetchmail script. Thank you for the idea and your implication!

**Comment by kaiyou** [comment]
I just pushed 2cb4a44b5a476316367d5cf4a4fc2dedb8e6c84e which might help imlement this. Be careful when merging this with your changes.

**Comment by fabolhak** [comment]
ok cool. I will be careful.

**Comment by fabolhak** [comment]
Hey, just wanted to let you know that I'm kinda busy these days (studying for exams). So I will probably not be able to look into the issue before October :(. Just to give a short update. Sorry

**Comment by kaiyou** [comment]
No worries, that's the basis of free software: people contribute to the extent they feel is reasonable. Should it be in a week or a year, your contribution will always be welcome. If anyone is expecting the feature and cannot wait that long can simply implement it.

**Comment by kaiyou** [comment]
@fabolhak Will you have time to write this before late november?

**Comment by fabolhak** [comment]
hmmm I'm still kinda busy these days. Maybe I have time on the weekend. Sorry :(

**Comment by kaiyou** [comment]
No worries. Just that the feature will not be included in 1.3.
