### ISSUE TITLE
Roundcube / Rainloop restarts 

### ISSUE THREAD

**Issue by pwFoo** [Mailu/Mailu#600]
Webmail container enduring restarts. Can't find out why.
```
8b4782eaf83e        mailu/rainloop:master                                "docker-php-entryp..."   40 seconds ago      Restarting (1) 7 seconds ago
```

Logs
```
AH00534: apache2: Configuration error: No MPM loaded.
AH00534: apache2: Configuration error: No MPM loaded.
AH00534: apache2: Configuration error: No MPM loaded.
AH00534: apache2: Configuration error: No MPM loaded.
AH00534: apache2: Configuration error: No MPM loaded.
AH00534: apache2: Configuration error: No MPM loaded.
AH00534: apache2: Configuration error: No MPM loaded.
AH00534: apache2: Configuration error: No MPM loaded.
AH00534: apache2: Configuration error: No MPM loaded.
```

Same with roundcube each time I re-/deploy mailu.

Any idea why?

**Comment by kaiyou** [comment]
Do you have earlier logs for the container? Could you dump the first log lines when starting a container?

**Comment by pwFoo** [comment]
Log lines repeating
```
AH00534: apache2: Configuration error: No MPM loaded.
```
No more information from log. Is it possible to enable debugging information?

**Comment by yokane** [comment]
@pwFoo 
I have the same trouble as you had.
I've tried blow anyway, then it runs.

In mailu:rainloop's `Dockerfile`

```
RUN echo 'LoadModule mpm_prefork_module /usr/lib/apache2/modules/mod_mpm_prefork.so' >> /etc/apache2/apache2.conf \
 && echo 'LoadModule php5_module /usr/lib/apache2/modules/libphp5.so' >> /etc/apache2/apache2.conf
```

try it :)

**Comment by pwFoo** [comment]
Because of vacation I'm away the next two weeks. But if it's apache module dependent. Will there an updated image to fix it?

**Comment by kaiyou** [comment]
The image is running properly on my side, which is weird. I need to investigate this afternoon. Do you have the sha256 of the culprit image?

**Comment by yokane** [comment]
Here is sha256
[mailu/rainloop@sha256:340c692c3aa82a97d2ce8e12ff20959a3b768d2eb15d7b9bafbabaf151b906ac]

But in fact, I had same problem several times.
example, Wordpress Official Dockerimage.
(this is also mailu, others could run it)
I think two cause to occur it.

One. Using jwilder/nginx-proxy(with jrcs/letsencrypt-nginx-proxy-companion)
It was often cause to show message  ‘default.conf not found’. 
I don’t know much about reverse proxy. But that container have affected by that images I think.
Two. Using devicedriver is overlay2, not devicemapper.
I forgot which image is. some trouble shooting shows when container failed, change device driver to device mapper.

I’m sorry for I can’t try that because docker on using machine runs product now.
for your information.

**Comment by pwFoo** [comment]
I used it without reverse proxy in my first test, but if I'll use it it should run behind a ssl offloading reverse proxy.
At the moment I can't test it the next two weeks. If there is a update / fix all test it after I'm back again.

**Comment by muhlemmer** [comment]
Hi, in the test suite we are running on the master branch, container restart is disabled. This means a run failure should be permanent and fail the test. The first use of this tests was build number 398. At time of writing there we are at build number 594. This is almost 200 tests, where this bug did not expose itself.

Now, this is on the `master` branch. So if you are using `1.5`, this might have fixed itself through upgrades. In `docker-compose.yml` you can change the version of only the webmail. Eg:

```
  webmail:
    image: "mailu/$WEBMAIL:master"
    restart: always
    env_file: .env
    volumes:
      - "$ROOT/webmail:/data"
```
I'm too running webmail from `master`, with the rest on `1.5`, without issues. (My motivations are different). So you don't have to worry breakage.

Run `docker-compose up -d` for the change to take effect. Please check if the problems still persist.

**Comment by muhlemmer** [comment]
Cleaned up the priority and bug labels, as I believe this is no longer relevant. Also, I vote to close this issue.
