### ISSUE TITLE
FreeIPA integration

### ISSUE THREAD

**Issue by briantopping** [Mailu/Mailu#605]
It would be very interesting if this integrated against FreeIPA. There's a lot of areas of interest:

- User, RBAC, user certificates and 2FA could be managed by FreeIPA
- Access points (IMAP, SMTP) could be easily kerberized / GSSAPI
- User certificates (and CRL) managed by FreeIPA
- Would help scale mid-sized implementations where FreeIPA access is a highly protected thing
- DNS integration would be automatic

It would be a distraction to build each feature internally as well as integration with FreeIPA. FreeIPA uses a lot of Python internally though, so it might help guide the code abstractions in Mailu (things like object formats and controller relationships) and make integration a lot easier over time.

**Comment by rakshith-ravi** [comment]
I'll take a look into this. Do you have any guide or tutorial recommendations from your side that I should look at for integrating FreeIPA?

**Comment by briantopping** [comment]
Cool, please let me know how I can be of assistance. The JSON API is solid and designed for long-term compatibility. That would be your best bet for interfacing with it. Google has a lot of great references for it.

**Comment by kaiyou** [comment]
Closing, since this is discussed in #783
