### ISSUE TITLE
Create a configuration table in database

### ISSUE THREAD

**Issue by kaiyou** [Mailu/Mailu#610]
Now that a lot of configuration variables are actually used by Flask, it makes sense to make them available in the admin ui.

In the meanwhile, I want to be able to load configuration from a config file or environment variable. So we have two main options.

1. Use the database as the main configuration source and read environment or config file at startup to update the config table. This gives precedence to the environment variables but might be irritating when customized variables are overwritten at startup)

2. Use layered config, so that missing values in database are searched for in environment variables.

Any idea?

**Comment by Nebukadneza** [comment]
Hi There,

The `Mailu`-Project is currently in a bit of a bind! We are short on man-power, and we need to judge if it is possible for us to put in some work on this issue.

To help with that, we are currently trying to find out which issues are actively keeping users from using `Mailu`, which issues have someone who want to work on them — and which issues may be less important. These a less important ones could be discarded for the time being, until the project is in a more stable and regular state once again.

In order for us to better assess this, it would be helpful if you could put a **reaction on this post** (use the :smiley: icon to the top-right).
- 👍️ if you **need this** to be able to use Mailu. Ideally, you’d also be able to test this on your installation, and provide feedback …
- 🎉 if you find it a **nice bonus**, but no deal-breaker
- 🚀 if you want to **work on it yourself**!
We want to keep this **voting open for 2 weeks** from now, so please help out!

**Comment by Diman0** [comment]
Hi There,

we see this issue had only little attention 😟. As much as it pains us: In order to get the current issues a bit more manageable for us, we decided to close it. 👋👋

We hope that no one feels offended by doing so. Should the issue get really pressing in the future, please feel free to re-open it.

Thank you for your patience and understanding, 🙇
- Your Mailu Team

p.s. PR1604 will add the functionality to load config from config file.
