### ISSUE TITLE
Front container does not forward credentials to rspamd

### ISSUE THREAD

**Issue by khannurien** [Mailu/Mailu#618]
Hi,

I'm using Mailu 1.5.
After upgrading using these commands:

```
docker-compose down --remove-orphans
docker-compose pull
docker-compose up -d
```

rspamd admin UI repeatedly asks me for my password (while I'm already logged in from the main admin UI), and displays a list of errors in its History:

```
Time | Worker type | PID | Module | Internal ID | Message
-- | -- | -- | -- | -- | --
29/09/2018 à 17:55:53 | rspamd_proxy | 7 | map | mb4rmx | /var/lib/rspamd/spf_dkim_whitelist.inc.local: map file is unavailable for reading
29/09/2018 à 17:55:53 | rspamd_proxy | 7 | map | rp5tkn | /var/lib/rspamd/dmarc_whitelist.inc.local: map file is unavailable for reading
29/09/2018 à 17:55:53 | controller | 8 | map | rp5tkn | /var/lib/rspamd/dmarc_whitelist.inc.local: map file is unavailable for reading
29/09/2018 à 17:55:53 | rspamd_proxy | 7 | map | zcfokz | /var/lib/rspamd/mime_types.inc.local: map file is unavailable for reading
29/09/2018 à 17:55:53 | controller | 8 | map | mb4rmx | /var/lib/rspamd/spf_dkim_whitelist.inc.local: map file is unavailable for reading
29/09/2018 à 17:55:53 | rspamd_proxy | 7 | map | 35rhob | /etc/rspamd/local.d/mid.inc: map file is unavailable for reading
29/09/2018 à 17:55:53 | controller | 8 | map | zcfokz | /var/lib/rspamd/mime_types.inc.local: map file is unavailable for reading
29/09/2018 à 17:55:53 | controller | 8 | map | 35rhob | /etc/rspamd/local.d/mid.inc: map file is unavailable for reading
29/09/2018 à 17:55:53 | rspamd_proxy | 7 | map | hhqhwh | /var/lib/rspamd/surbl-whitelist.inc.local: map file is unavailable for reading
29/09/2018 à 17:55:53 | controller | 8 | map | hhqhwh | /var/lib/rspamd/surbl-whitelist.inc.local: map file is unavailable for reading
```

I can confirm those files are missing from the container.

Any clue?

Thanks!

**Comment by kaiyou** [comment]
The first part, missing maps, is absolutely normal. Those maps are optional for overriding and we do not override them.

rspamd asking for the password is an issu ethough: this should be properly handled by the front container forwarding the request. I have the same issue and yet have to investigate. Could you rename the issue to make it more about the password?

**Comment by khannurien** [comment]
Haha it does actually. You can input any (incorrect) password, this is just the form being displayed for no good reason:

https://github.com/rspamd/rspamd/issues/2553

Fixed per https://github.com/moisseev/rspamd/commit/626fe0339c3dee9c9a909fa4f42bd4c92cb851b5 @ rspamd.
