### ISSUE TITLE
user create/admin

### ISSUE THREAD

**Issue by WWE-Corey** [Mailu/Mailu#619]
I installed and have successfully sent and received emails using Mailu. I cannot however seem to find where in the GUI to add new users or to manage contacts. I added radicale to the .env file and have the admin page allowed.

![image](https://user-images.githubusercontent.com/24246957/46251422-c7317800-c417-11e8-94ee-23ae6d5a05e0.png)

![image](https://user-images.githubusercontent.com/24246957/46251228-dc57d800-c412-11e8-9f0c-6a3fdf6d45cc.png)
![image](https://user-images.githubusercontent.com/24246957/46251231-f1346b80-c412-11e8-953b-1719af9fa4c0.png)

**Comment by muhlemmer** [comment]
In the admin page, go to "mail domains" there you can select the domain and add users and/or aliases to it.

On September 30, 2018 2:10:35 AM GMT+03:00, Corey Johnson <notifications@github.com> wrote:
>I installed and have successfully sent and received emails using Mailu.
>I cannot however seem to find where in the GUI to add new users or to
>manage contacts.
>
>![image](https://user-images.githubusercontent.com/24246957/46251228-dc57d800-c412-11e8-9f0c-6a3fdf6d45cc.png)
>![image](https://user-images.githubusercontent.com/24246957/46251231-f1346b80-c412-11e8-953b-1719af9fa4c0.png)
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Mailu/Mailu/issues/619

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by aminb** [comment]
Radicale comes with a simple web interface that lets you create addressbooks and calendars. You can access it on `DOMAIN/webdav/.web/` where `DOMAIN` is the domain you run Mailu on. As of now it doesn't support inserting/editing entries (i.e. contacts and events) though.

Alternatively, you can use DAVdroid or other clients to do the same.
