### ISSUE TITLE
[Test suite] - Rspamd fails occasionaly

### ISSUE THREAD

**Issue by muhlemmer** [Mailu/Mailu#627]
cc: @ionutfilip

While developing the test suite, we had random failures on the `anitspam` service. It would usually end in:
```
2018-10-05 12:09:48 #7(controller) <3nxzfe>; monitored; rspamd_monitored_dns_cb: DNS query blocked on multi.uribl.com (127.0.0.1 returned), possibly due to high volume
```

This is most probably related to the freshclam issues I've been seeing (#625). It seems this is fixed in the Alpine git repository, only the `alpine:edge` image has not been rebuild yet. We've been able to run our test suite successful a number of times without errors on `rspamd`.

I'm opening this issue as other users that are using `mailu:master` might find themselves in this situation.

Links to the travis build logs:
- `rspamd` fail: https://travis-ci.org/usrpro/Mailu/builds/437588016#L3883
- `rspamd` success: https://travis-ci.org/usrpro/Mailu/builds/437594682#L4062
**Note:** Build still fails on fetchmail, which we are investigating.

The issues seems to originate from `musl` which is the standard C library used in Alpine and should be fixed in the following [commit](https://git.alpinelinux.org/cgit/aports/log/main/musl):
```
* | main/musl: backport fix for getaddrinfo regression | Natanael Copa | 2018-09-20 | 2 | -1/+55
```

Rebuild of `alpine:edge` had been requested in gliderlabs/docker-alpine#447

**Comment by ofthesun9** [comment]
"DNS query blocked on multi.uribl.com" could be also related to:
https://rspamd.com/doc/faq.html#what-is-the-meaning-of-the-uriblblocked-symbol
see #385

**Comment by muhlemmer** [comment]
We are also seeing segfaults and other kinds of failures when on `alpine:edge`. I don't want to bother too much in debugging, since on `alpine:3.8` everything seems fine. We've done a number of forced re-tests at Travis and it seems okay.

So hopefully a simple rebuild will help.
