### ISSUE TITLE
Where to ask questions ? (in developing a sympa plugin)

### ISSUE THREAD

**Issue by c-holtermann** [Mailu/Mailu#629]
Hello !

I'm working on a sympa docker image that works with the mailu system. It's on my gitlab at the moment. I'm happy to share/contribute when it's working. I've got some questions how to best interface with the existing stack. Is this the right place to ask questions or is there a mailing list ?

regards,

Christoph Holtermann

**Comment by muhlemmer** [comment]
Hi, we are on [Matrix](https://matrix.to/#/#mailu:tedomum.net) for discussions.

**Comment by kaiyou** [comment]
Well, this place is pretty good, there is also a Matrix channel #mailu:tedomum.net :)

**Comment by muhlemmer** [comment]
I believe the origin of this question was answered and therefor closing.
