### ISSUE TITLE
 554 5.7.1 error

### ISSUE THREAD

**Issue by SJS28092018** [Mailu/Mailu#656]
Mailu is up and running :=)
Have one issue though. Email's sent from gmail to the server get delivered but email's sent from my work email get rejected with  554 5.7.1 
_smtp_1       | postfix/smtpd[56]: NOQUEUE: reject: RCPT from unknown[companyIPAddress]: 554 5.7.1 <myemail@mycompany.com>: Sender address rejected: Access denied; from=<myemail@mycompany.com> to=<stephen@bonfaru.org> proto=ESMTP helo=<mx0a-001b2d01.pphosted.com>_.
I never have any issue sending emails from my company account to other companies so there must be an issue with my setup.

**Comment by muhlemmer** [comment]
Hi, apologies for not getting back to you. I think I've missed this issue somehow. Is this problem still current? Since the posting of this issue, we have published a [faq](https://mailu.io/1.6/faq.html). Can you double check if that has any suggestions to fixing your problem?

**Comment by Al2Klimov** [comment]
Faced the same issue. Changed SMTP port to 587. Now it works.

**Comment by Al2Klimov** [comment]
By the way: Top job, guys! Mailu rocks... if the admin (I) knows the SMTP port to actually use. 😉

**Comment by kaiyou** [comment]
Fwiw the port is specified explicitely in the section named "client config" 😅
