### ISSUE TITLE
Set "port" to admin/ui?

### ISSUE THREAD

**Issue by MikkelDK** [Mailu/Mailu#659]
Hello,

I will hear, about there is someway possible to adding port?

As example:
mail.domain.eu:8443/admin
Everytime i'm trying to visit: https://mail.domain.eu:8443/admin 
it will forces to: https://mail.domain.eu/admin/ui

What can i do?

**Comment by odensc** [comment]
I was able to work around this by navigating directly to `/admin/ui/login?next=ui.index`, however it would still be nice to set the port as some things are still broken.

**Comment by MikkelDK** [comment]
> I was able to work around this by navigating directly to `/admin/ui/login?next=ui.index`, however it would still be nice to set the port as some things are still broken.

Yeah me2. but.. it's a issue for me. since i'm running "nginx" standalone. (with domains) and i want to make possible, for i can "login" on the admin-page via port 
As example: https://mail.domain.eu:8443/admin but it only forces back to https://mail.domain.eu/admin/ui...

And i don't know, what i can do! :-(

**Comment by HorayNarea** [comment]
Why do you even need to include a port? Why not leaving the https service on the default 443?

**Comment by MikkelDK** [comment]
@HorayNarea > Why do you even need to include a port? Why not leaving the https service on the default 443?

Because i'm running normal nginx web-server. and 8443 is SSL for letsencrypt
and i'm using cloudflare SSL on normal nginx-web-server. ;)

Thats why i want it to ported to port. ^^

**Comment by HorayNarea** [comment]
I'm running a similar setup without port-problems:

* change the https port-forwarding in docker-compose.yml to 127.0.0.1:8443:443
* in nginx proxy_pass to https://localhost:8443

The Let's Encrypt request get's through without problems, you just have 2 Certs for the same domains

**Comment by odensc** [comment]
In my case I have Nextcloud already running on port 80/443 and would just like to simply setup Mailu on port 8080 without having to reverse-proxy everything through nginx.

**Comment by jtullett** [comment]
I'm not sure I'd want the admin interface exposed publicly at all on a production server. Can't you restrict to localhost, then connect via an SSH tunnel?

**Comment by muhlemmer** [comment]
> I'm not sure I'd want the admin interface exposed publicly at all on a production server. Can't you restrict to localhost, then connect via an SSH tunnel?

Yes, you can. In fact, this functionality is provided when using the new setup utility (on the `master` branch). When the user chooses not to expose the admin interface, the `docker-compose.yml` file generated by setup will contain the settings to bind admin to the `127.0.0.1:8080`.

https://github.com/Mailu/Mailu/blob/5c2439011413a114c470862f95206f8487fa4568/setup/flavors/compose/docker-compose.yml#L47
```
admin:
    image: mailu/admin:{{ version }}
    env_file: {{ env }}
    {% if not admin_enabled %}
    ports:
      - 127.0.0.1:8080:80
    {% endif %}
    volumes:
      - "{{ root }}/data:/data"
      - "{{ root }}/dkim:/dkim"
    depends_on:
- redis
```

If you want this functionality in a Compose file V2, just modify it manually to contain the ports section.

**Comment by vityafx** [comment]
On my instance going to `domain.com/admin` redirects me to `domain.com/webmail` instead so I can not simply login to the admin panel. However, if I go to `domain.com/admin/ui` the admin panel opens fine and asks me to log in.
