### ISSUE TITLE
Mac Mail Integration

### ISSUE THREAD

**Issue by jethroguce** [Mailu/Mailu#673]
has anyone tried to use mailu with mac mail client or other mail clients.

I was able to set up the mailu, and use it with roundcube, wondering if there's an easy way to use mailu with the mac mail client

**Comment by ofthesun9** [comment]
The following is working for me:
imap on port 143 and SSL
smtp on port 587 and SSL

If you have any error, please share the details (logs, which mailu version, which OSX version)

**Comment by jethroguce** [comment]
I am using a self signed SSL, will that cause problem with the mail client?

**Comment by jethroguce** [comment]
do i need to add entries on DNS server?

**Comment by muhlemmer** [comment]
Self signed definitely is an issue, as you mail client will never trust the certs. And yes, you need DNS entries to be set to your server.

Please the read the docs on how to do this: https://mailu.io/dns.html

After DNS is set up correctly, all you need to do is set `TLS_FLAVOR=letsencrypt` and Mailu will obtian signed certificates for you. No other action needed.
