### ISSUE TITLE
Does admin (master) require the vol /var/run/docker.sock:/var/run/docker.sock:ro ?

### ISSUE THREAD

**Issue by ofthesun9** [Mailu/Mailu#675]
in the  Mailu/docs/compose/docker-compose.yml , we have in the admin part the definition for the volume:
`  - var/run/docker.sock:/var/run/docker.sock:ro`

If I remember well, this volume had been removed once in a while. Do we still need it ?

**Comment by kaiyou** [comment]
It does not anymore, since we do not provide the Docker status page iirc.
