### ISSUE TITLE
"Authentication rate limit from one source exceeded"

### ISSUE THREAD

**Issue by chrisch-hh** [Mailu/Mailu#686]
I'm checking ~10 mailboxes via IMAP with Thunderbird. On some mailboxes Thunderbird complains about a failed login. In the log of the mailu_front container I'm getting:

`2018/10/25 10:06:04 [info] 8#8: *4503 client login failed: "Authentication rate limit from one source exceeded" while in http auth state, client: 80.xxx.xxx.xxx, server: 0.0.0.0:993, login: "webmaster@xxxxx.xx" `

But I'm not sure from which component this error come from? dovecot? 

I've tried `mail_max_userip_connections = 50` in `overrides/dovecot.conf` but that doesn't solve the problem.

**Comment by hoellen** [comment]
If you're using the `latest` version, you can change the rate limit in your .env file:
https://github.com/Mailu/Mailu/blob/5a9f01d47358c15a039b4706053a7bf6e183b54e/config/flavors/compose/mailu.env#L28

**Comment by chrisch-hh** [comment]
Thank you, I've missed this setting in the .env file. Seems to work.

**Comment by jc565** [comment]
i have this same problem.  could someone tell me... is there a way to change this with the system running, or should I stop the container, change the ENV file, and then restart the container?  or should i do a down command and start over from the beginning?   ive never had to change an env variable on a container before.

**Comment by vinanrra** [comment]
> 
> 
> i have this same problem. could someone tell me... is there a way to change this with the system running, or should I stop the container, change the ENV file, and then restart the container? or should i do a down command and start over from the beginning? ive never had to change an env variable on a container before.

You need to change variable and them start the container again u can even use the same command, because docker-compose will detect the changes and change container variables.
