### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by oz123** [Mailu/Mailu#693]
There have been a lot of changes since 1.5.1. Currently installing from the master branch,
means also building a lot of images locally.
Can you please tag a release a new version and build public images ?

**Comment by muhlemmer** [comment]
This is already under discussion in the [project management](https://github.com/Mailu/Mailu/issues/593#issuecomment-427640887) thread. Same thing was discussed [here](https://github.com/Mailu/Mailu/issues/593#issuecomment-427640887).

Also, we still have a number of open bugs which need love and attention. Preferably before release.
https://github.com/Mailu/Mailu/issues?utf8=✓&q=is%3Aissue+label%3Atype%2Fbug+is%3Aopen

I will close this issue, as it is kind of a duplicate question.
