### ISSUE TITLE
Verify DANE when sending emails and use STARTTLS when possible.

### ISSUE THREAD

**Issue by jcgruenhage** [Mailu/Mailu#707]
According to https://ssl-tools.net/mailservers/jcg.re, mailu seems to not use StartTLS when sending emails. Additionally, https://havedane.net/ indicates that when a DANE record is available but an invalid certificate is used, mailu will still deliver the mail. It makes sense, since it doesn't use StartTLS there is no certificate to validate.

**Comment by muhlemmer** [comment]
Up for testing and submitting tomorrow.

**Comment by jcgruenhage** [comment]
I'm currently running 1.5, what would be the best way to test that?

**Comment by muhlemmer** [comment]
I will test it myself (now actually). I'll use the links you've provided.

**Comment by jcgruenhage** [comment]
So, how did your tests go?

**Comment by jcgruenhage** [comment]
Related to this, there is also MTA-STS that should be checked.

**Comment by muhlemmer** [comment]
> So, how did your tests go?

Not successful. I've set DANE checking on Postfix, but it's still sending mail to a server with broken certs. I've halted work on this for the moment, because some more urgent issues popped up.

You can try it for yourself if you use the following commit: https://github.com/usrpro/Mailu/commit/5b275f1745a41b9e2aa8315cf568507f34dfafb4.

**Comment by jcgruenhage** [comment]
I'm afraid I have more urgent things to do right now too, but thanks for starting to work on this!

**Comment by ofthesun9** [comment]
I started also some tests (reading https://tech.feedyourhead.at/content/postfix-verified-tls-with-dane)
and also found that it is still sending to server with broken certs.

Anyway it seems that some mail domain have a broken implementation of DANE, which prevents mail delivery (if DANE is activated on mail side). There is a "dane fail list" at https://github.com/danefail/list
Before activating DANE on mailu, we shall consider whether we want to incorporate the "fail list" or not...

**Comment by jcgruenhage** [comment]
If this won't be fixed any time soon, then the docs should state it. Currently mailu.io says that TLS is enforced, which while technically true, doesn't give any benefit if people can MitM those connections trivially anyway.

**Comment by vchoi** [comment]
> Before activating DANE on mailu, we shall consider whether we want to incorporate the "fail list" or not...

From the commit history, this list is frequently updated.(https://github.com/danefail/list/commits/master)

If this ever gets implemented, I suggest there should be an automated process to fetch and update the list.

**Comment by jcgruenhage** [comment]
I don't think that such a list is a good idea. If people mess up their TLSA records, they should expect not to receive mail. Just overriding security in case people make mistakes is no solution.

**Comment by ofthesun9** [comment]
I finally have DANE working, but I needed to switch to an ubuntu image for the postfix container.
In Posfix [documentation](http://www.postfix.org/TLS_README.html), there is the following requirements:

> The pre-requisites for DANE support in the Postfix SMTP client are:
> - A compile-time OpenSSL library that supports the TLS SNI extension and "SHA-2" message digests.
> - A compile-time DNS resolver library that supports DNSSEC. Postfix binaries built on an older system will not support DNSSEC even if deployed on a system with an updated resolver library.
> - The "smtp_dns_support_level" must be set to "dnssec".
> - The "smtp_host_lookup" parameter must include "dns".
> - A DNSSEC-validating recursive resolver (see note below). 

I also built an alpine container to use [tlsa](https://github.com/letoams/hash-slinger) to further test my environnement, and I get warning about "Answer was not DNSSEC-secure", although working Ok on my host or within an ubuntu container.

My (simple) guess is that alpine is currently missing some bits around DNSSEC.

**Comment by alexanderadam** [comment]
> I finally have DANE working, but I needed to switch to an ubuntu image for the postfix container.

Would it be worth a PR to Mailu? :thinking:

**Comment by ofthesun9** [comment]
It seems that alpine:3.12 has solved the issue I encountered with DANE :-)
My following tests are Ok:
when the destination is not supporting DANE:
```
mailu_smtp.1.e8y5yz9tw277@rpi3-01    | Jun 16 12:14:10 mail postfix/smtp[361]: Anonymous TLS connection established to dont.havedane.net[5.79.70.105]:25: TLSv1.2 with cipher ADH-AES256-GCM-SHA384 (256/256 bits)
```

when the destination is supporting DANE and DANE check is Ok:
```
mailu_smtp.1.e8y5yz9tw277@rpi3-01    | Jun 16 12:13:29 mail postfix/smtp[361]: Verified TLS connect```ion established to do.havedane.net[5.79.70.105]:25: TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits)
```
when the destination is supporting DANE and DANE check is NOk:
```
mailu_smtp.1.e8y5yz9tw277@rpi3-01    | Jun 16 12:12:09 mail postfix/smtp[361]: Untrusted TLS connection established to wrong.havedane.net[5.79.70.105]:25: TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits)
mailu_smtp.1.e8y5yz9tw277@rpi3-01    | Jun 16 12:12:09 mail postfix/smtp[361]: 2915B18052: Server certificate not trusted
```
In the latter case, the email will remain in postfix mailqueue

For those willing to test:
- use images provided through #1541 
- create an overrides/postfix.cf:

> smtp_host_lookup = dns 
> smtp_tls_security_level = dane 
> smtp_tls_loglevel = 1 
> smtp_tls_CAfile = /etc/ssl/certs/ca-certificates.crt
> smtp_dns_support_level = dnssec

**Comment by Nebukadneza** [comment]
Hi There,

The `Mailu`-Project is currently in a bit of a bind! We are short on man-power, and we need to judge if it is possible for us to put in some work on this issue.

To help with that, we are currently trying to find out which issues are actively keeping users from using `Mailu`, which issues have someone who want to work on them — and which issues may be less important. These a less important ones could be discarded for the time being, until the project is in a more stable and regular state once again.

In order for us to better assess this, it would be helpful if you could put a **reaction on this post** (use the :smiley: icon to the top-right).
- 👍️ if you **need this** to be able to use Mailu. Ideally, you’d also be able to test this on your installation, and provide feedback …
- 🎉 if you find it a **nice bonus**, but no deal-breaker
- 🚀 if you want to **work on it yourself**!
We want to keep this **voting open for 2 weeks** from now, so please help out!

**Comment by nextgens** [comment]
I've submitted #1902 recently that is kind of related; It will configure the system CAs by default and will allow for easier overrides of the tls_policy on specific domains.

@ofthesun9 are you still working on this?

**Comment by ofthesun9** [comment]
> I've submitted #1902 recently that is kind of related; It will configure the system CAs by default and will allow for easier overrides of the tls_policy on specific domains.
> 
> @ofthesun9 are you still working on this?

My current setup is to create  overrides/postfix.cf with the following:
```
smtp_host_lookup = dns 
smtp_tls_security_level = dane 
notify_classes = resource, software, delay 
delay_warning_time = 5m
smtp_tls_loglevel = 1 
smtp_tls_CAfile = /etc/ssl/certs/ca-certificates.crt
smtp_dns_support_level = dnssec
```
I am using this since my original comment and this is working ok.
Messages are sent when an DANE error is encountered (to postmaster and the sender if my memory serves me well), but then manual action is needed.
Would your PR allow the postmaster to override the policy in order to not use DANE for specific domains ? (that could be filled by the postmaster when he assesses that this is only due to an incorrect configuration)

**Comment by nextgens** [comment]
> Would your PR allow the postmaster to override the policy in order to not use DANE for specific domains ? (that could be filled by the postmaster when he assesses that this is only due to an incorrect configuration)

Yes. One can even pin a specific certificate fingerprint instead if required

**Comment by nextgens** [comment]
@ofthesun9 please have a look to #1961

It's not perfect: TLSA records can be stripped ... and postfix will fallback... if we want better than that we should implement a new policy daemon that would run before mta-sts and force "dane-only" as required. It's non-trivial to do it in python as it requires to validate the DNSSEC records...

**Comment by nextgens** [comment]
@ofthesun9 I've updated #1961 with "full-blown" DANE support, it should now work as expected
