### ISSUE TITLE
Cannot retrieve or send email

### ISSUE THREAD

**Issue by DevLander** [Mailu/Mailu#710]
Hi,

This is a new docker-compose setup. Everything seems fine (webmail & admin sites accessible, ports are bound and verified accessible through nmap on another machine) apart from Thunderbird cannot send or retrieve emails on the server.

The log from docker outputs a single line every time I try to retrieve via IMAP, there are no logs when attempting SMTP. 

```
front_1_54eb26cc0438 | 2018/11/20 00:18:40 [info] 14#14: *1 client <redacted>:46528 connected to 0.0.0.0:993
front_1_54eb26cc0438 | 2018/11/20 00:18:46 [info] 14#14: *2 client <redacted>:46532 connected to 0.0.0.0:993
front_1_54eb26cc0438 | 2018/11/20 00:20:05 [info] 14#14: *3 client <redacted>:46536 connected to 0.0.0.0:993
```

When I choose `normal password` in Thunderbird it keeps asking for a password, when I set it to anything else, it does not keep asking for a password and does not otherwise complain about not being able to perform actions.

What is likely happening? Thanks.

**Comment by muhlemmer** [comment]
Looking at the container names in the logs, are you running in Docker swarm mode? Which version are you running?

**Comment by DevLander** [comment]
I am using docker-compose `1.21.2, build a133471`. Docker `18.06.1-ce, build e68fc7a` is also installed.

I am running the command `docker-compose up`, I am not specifying swam mode, perhaps this version defaults to swarm mode. I will read up on the topic.

**Comment by HorayNarea** [comment]
> Looking at the container names in the logs, are you running in Docker swarm mode?

docker-compose/docker uses this naming-scheme in the latest version

**Comment by DevLander** [comment]
Fixed, there were a number of issues with my configuration:

1. iptables needed to be cleared and possibly a misconfiguration on 2nd ip binding
1. passwords needed to be plain
1. VM host blocked SMTP by default
1. VPN blocked SMTP
