### ISSUE TITLE
Fetchmail only syncs the INBOX folder

### ISSUE THREAD

**Issue by Nuxij** [Mailu/Mailu#711]
I enabled the fetchmail feature to migrate from an old mail-in-a-box setup, but it seems to have only pulled in the INBOX items. All the other IMAP folders are still present in the source mailbox and missing from my Mailu mailbox. I am using 1.5 so I don't have the feature to disable "remove mails" yet; The source INBOX is empty, but the other folders are still there indicating they haven't even been seen?

**Comment by muhlemmer** [comment]
Hi, I'm afraid that this is a 100% fetch-mail issue. We can't do much about it. Folders are non-recursive. Every folder should be hard-coded in the config or fetchmail command line.

We could think of an enhancement where every user can specify the folders to retrieve, but it's going to be tricky to implement properly I'm afraid.

**Comment by fxnn** [comment]
From the [fetchmail docs](http://www.fetchmail.info/fetchmail-man.html#8) it seems, that fetchmail allows a comma separated list of folders (only if `idle` is not set, but Mailu doesn't set it anyways).

A simple input field for a list of folder names would already be a huge improvement, as currently, nothing else than `INBOX` can be synced.

In theory, I can imagine to retrieve the list of folders from the remote server and display it with check boxes, but to me, that wouldn't be necessary.

**Comment by Nebukadneza** [comment]
Hi There,

The `Mailu`-Project is currently in a bit of a bind! We are short on man-power, and we need to judge if it is possible for us to put in some work on this issue.

To help with that, we are currently trying to find out which issues are actively keeping users from using `Mailu`, which issues have someone who want to work on them — and which issues may be less important. These a less important ones could be discarded for the time being, until the project is in a more stable and regular state once again.

In order for us to better assess this, it would be helpful if you could put a **reaction on this post** (use the :smiley: icon to the top-right).
- 👍️ if you **need this** to be able to use Mailu. Ideally, you’d also be able to test this on your installation, and provide feedback …
- 🎉 if you find it a **nice bonus**, but no deal-breaker
- 🚀 if you want to **work on it yourself**!
We want to keep this **voting open for 2 weeks** from now, so please help out!

**Comment by t-lie** [comment]
can anyone help me finding out where to manually do some config changes for fetchmail?
I really need the possibiliy to sync multiple folders from fetched accounts.
Where can I set the values (list) for the --folder parameter?

Thanks

**Comment by archont00** [comment]
Same problem here. 

Users use fetchmail to move all messages from multiple external IMAP servers to Mailu.

Unfortunately, if the external IMAP server decides the incoming message is a spam, users will never see that message unless they directly login to the external IMAP server.

P.S. Many public e-mail services do not allow to turn off SPAM filtering fully.
