### ISSUE TITLE
outgoing port 25 traffic blocked by VPS provider

### ISSUE THREAD

**Issue by andresmrm** [Mailu/Mailu#712]
After setting up the server, I've just find out that the VPS provider blocks outgoing traffic from port 25.
I tested and I can receive e-mail, but not send. Docker smtp log shows many:

    postfix/smtp[133]: connect to ...[...]:25: Operation timed out

The VPS provider says I can use another port to send e-mail instead of 25. Is it true? If so, how do I configure Mailu for doing so? We don't have money to contract a relay...

**Comment by andresmrm** [comment]
Would port 587 be an alternative? How to configure Mailu to send e-mail by it?

**Comment by andresmrm** [comment]
[This page](https://www.jscape.com/blog/smtp-ports) helped me to understand the difference between ports 25 and 587. So it seems it must be port 25. I found free relay server options for the low volume of e-mail my server will have. Configured using [these instructions](https://github.com/Mailu/Mailu/issues/387) with Sendgrid.

**Comment by andresmrm** [comment]
We discovered it only after contracting 1 year of hosting.
Besides, it's a restriction imposed by our government. So we would have to
contract a foreigner hosting...

**Comment by ripkens** [comment]
Do you need a VPS in Germany?

**Comment by andresmrm** [comment]
Thanks! I already use one for another project. But for this project we already paid for one hosting, and we have no money to change to another...
