### ISSUE TITLE
Admin whitelist_webmail hard coded

### ISSUE THREAD

**Issue by jbmolle** [Mailu/Mailu#716]
Hi,
I'm trying to send transactional email with Mailu SMTP from a backend server and it takes more than 15s.
I tracked down one problem in core/admin/mailu/internal/__init__.py:
def whitelist_webmail() uses socket.gethostbyname("webmail")

In my docker configuration there is no "webmail" host so the function socket.gethostbyname return nothing after 5s which slows down a lot the request /internal/auth/email
When I set "webmail" to a fake ip on the admin server the /internal/auth/email returns immediately.

Maybe it would be better to define a list of hostnames in the configuration file instead of using a hard coded "webmail" value. What do you think?

Thanks Mailu for the great work!
JB

**Comment by muhlemmer** [comment]
https://github.com/Mailu/Mailu/blob/d3a5c7058927698cf66b9105bfb4daa95da33b85/core/admin/mailu/internal/__init__.py#L25-L26
@ionutfilip, so there is still a cheeky `gethostbyname` hidden somewhere. Can you please rewrite this snippet to use the resolved addresses, like you implemented with `mailustart` in PR #886.
