### ISSUE TITLE
nginx: [emerg] BIO_new_file("/certs/dhparam.pem") failed (SSL: error:02FFF002:system library:func(4095):No such file or directory:fopen('/certs/dhparam.pem', 'r') error:20FFF080:BIO routines:CRYPTO_internal:no such file)

### ISSUE THREAD

**Issue by mnooblet** [Mailu/Mailu#734]
after installing and switching from notls to letsencrypt my frontend container crashes und keeps restarting with this error..

I can't even attach a console to look into the container

I noticed that the dhparam.pem file is missing in /mailu/certs/letsencrypt/live/mailu

Any ideas?

**Comment by muhlemmer** [comment]
#735 is merged. Image on Docker Hub. Please do:
```
docker-compose pull
docker-compose up -d
```
This should pull the new Nginx image and recreate front.

**Comment by mnooblet** [comment]
yey just pulled the image, seems to work now, thx
