### ISSUE TITLE
what is diffrent domain and hostname at .env docker-compose 

### ISSUE THREAD

**Issue by nuved** [Mailu/Mailu#742]
I use mailu version 1.5.

It seems Domain parameter  is used by letsencrypt and hostname is used for MX record so I put this value but I can just open the webmail with untrusted certificate, it seems letsencrypt just got ssl for smtp.domain.com not mail.domain.com 

DOMAIN=mail.domain.com
HOSTNAMES=smtp.domain.com

**Comment by muhlemmer** [comment]
#747 is also related to this
