### ISSUE TITLE
Fetchmail Connection error for this poll + IPv6 not working.

### ISSUE THREAD

**Issue by vparres** [Mailu/Mailu#780]
Hello !
I'm new in Mailu, and i freshly set-up an instance for me few days ago. But i'm running into few issues where i'm stuck without any solutions. I'm not sure, but i think my issues are related, so i opened a "2in1" to ask you help.

My first problem is with Fetchmail, who is unable to work properly and still showing the same error message repeately (i've just redacted my DN for the moment):

```
fetchmail_1  | fetchmail: Connection errors for this poll:
fetchmail_1  | name 0: connection to mail.domain.net:993 [91.121.xxx.xxx/993] failed: Operation timed out.
fetchmail_1  | name 1: connection to mail.domain.net:993 [2001:41d0:xxxx:xxxx::1/993] failed: Address not available.
fetchmail_1  | IMAP connection to mail.domain.net failed: Address not available
```

I don't really know what fetchmail does exactely, but i'm unable to move messages to a folder, and i suspect this fetchmail problem to be the origin of the issue.

My second problem is that i canot join my mail server throught IPv6 (except admin interface, which i handle throught my nginx as reverse proxy)

When i try to telnet my external IPv6 on a mail port on the server, it works, but outside of it, connection times out. I tried to open the corresponding ports in `ip6tables` without success

I've set the `BIND_ADDRESS6` variable accordingly, and modified the `docker-compose` file to bind 80 & 443 for both v4 and v6 to localhost for proxying.

Also, i'm currently able to recieve/send mail through all my domains, and to/from external senders as Microsoft, Google, Apple and Orange.

Here's the interesting technical info about my server :

System version :
```
Ubuntu 18.04.1 LTS x64 up-to-date running on a Kimsufi (OVH) dedicated box
nginx for proxying Admin interface
IPv4 and IPv6 enabled and functional for all the other services
```

Docker-compose version :
```
docker-compose version 1.17.1, build unknown
docker-py version: 2.5.1
CPython version: 2.7.15rc1
OpenSSL version: OpenSSL 1.1.1a  20 Nov 2018
```

Docker version :
```
Containers: 10
 Running: 10
 Paused: 0
 Stopped: 0
Images: 11
Server Version: 18.06.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version:  (expected: 468a545b9edcd5932818eb9de8e72413e616e86e)
runc version: N/A (expected: 69663f0bd4b60df09991c08812a60108003fa340)
init version: v0.18.0 (expected: fec3683b971d9c3ef73f284f176672c44b448662)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-24-generic
Operating System: Ubuntu 18.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.57GiB
Name: oneill
ID: TAEB:ELIG:6GSP:55GI:FEPY:K4XJ:WSEB:7URY:SOSR:SS4P:QRUN:FHEM
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

Using mailu tag `1.5`

Please let me know if you need any extra information to help me solve this :-D

I also would thanks the team for their awesome work ;-)

Thanks by advance for help !

**Comment by muhlemmer** [comment]
Fetchmail is used to retrieve mail from a remote imap server and retransmission to the user's mailbox over smtp. In the admin interface this is called "fetched accounts". Appearantly there is something wrong with the remote server you are trying to fetch from?

The inability of moving mails to other directories has nothing to do with that. This completely happens in the `imap` container. Try inspecting the log on that:

```
docker-compose logs -f imap
```

This will "follow" the logs as they are produced. Now try to do the same move operation and observe the produced logs. Please post back the logs here.

For IPv6, you need to be sure to have set up docker for it correctly. https://docs.docker.com/v17.09/engine/userguide/networking/default_network/ipv6


On 29 December 2018 14:00:53 EET, Vincent PARRES <notifications@github.com> wrote:
>Hello !
>I'm new in Mailu, and i freshly set-up an instance for me few days ago.
>But i'm running into few issues where i'm stuck without any solutions.
>I'm not sure, but i think my issues are related, so i opened a "2in1"
>to ask you help.
>
>My first problem is with Fetchmail, who is unable to work properly and
>still showing the same error message repeately (i've just redacted my
>DN for the moment):
>
>```
>fetchmail_1  | fetchmail: Connection errors for this poll:
>fetchmail_1  | name 0: connection to mail.domain.net:993
>[91.121.xxx.xxx/993] failed: Operation timed out.
>fetchmail_1  | name 1: connection to mail.domain.net:993
>[2001:41d0:xxxx:xxxx::1/993] failed: Address not available.
>fetchmail_1  | IMAP connection to mail.domain.net failed: Address not
>available
>```
>
>I don't really know what fetchmail does exactely, but i'm unable to
>move messages to a folder, and i suspect this fetchmail problem to be
>the origin of the issue.
>
>My second problem is that i canot join my mail server throught IPv6
>(except admin interface, which i handle throught my nginx as reverse
>proxy)
>
>When i try to telnet my external IPv6 on a mail port on the server, it
>works, but outside of it, connection times out. I tried to open the
>corresponding ports in `ip6tables` without success
>
>I've set the `BIND_ADDRESS6` variable accordingly, and modified the
>`docker-compose` file to bind 80 & 443 for both v4 and v6 to localhost
>for proxying.
>
>Also, i'm currently able to recieve/send mail through all my domains,
>and to/from external senders as Microsoft, Google, Apple and Orange.
>
>Here's the interesting technical info about my server :
>
>System version :
>```
>Ubuntu 18.04.1 LTS x64 up-to-date running on a Kimsufi (OVH) dedicated
>box
>nginx for proxying Admin interface
>IPv4 and IPv6 enabled and functional for all the other services
>```
>
>Docker-compose version :
>```
>docker-compose version 1.17.1, build unknown
>docker-py version: 2.5.1
>CPython version: 2.7.15rc1
>OpenSSL version: OpenSSL 1.1.1a  20 Nov 2018
>```
>
>Docker version :
>```
>Containers: 10
> Running: 10
> Paused: 0
> Stopped: 0
>Images: 11
>Server Version: 18.06.1-ce
>Storage Driver: overlay2
> Backing Filesystem: extfs
> Supports d_type: true
> Native Overlay Diff: true
>Logging Driver: json-file
>Cgroup Driver: cgroupfs
>Plugins:
> Volume: local
> Network: bridge host macvlan null overlay
>Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk
>syslog
>Swarm: inactive
>Runtimes: runc
>Default Runtime: runc
>Init Binary: docker-init
>containerd version:  (expected:
>468a545b9edcd5932818eb9de8e72413e616e86e)
>runc version: N/A (expected: 69663f0bd4b60df09991c08812a60108003fa340)
>init version: v0.18.0 (expected:
>fec3683b971d9c3ef73f284f176672c44b448662)
>Security Options:
> apparmor
> seccomp
>  Profile: default
>Kernel Version: 4.15.0-24-generic
>Operating System: Ubuntu 18.04.1 LTS
>OSType: linux
>Architecture: x86_64
>CPUs: 4
>Total Memory: 15.57GiB
>Name: oneill
>ID: TAEB:ELIG:6GSP:55GI:FEPY:K4XJ:WSEB:7URY:SOSR:SS4P:QRUN:FHEM
>Docker Root Dir: /var/lib/docker
>Debug Mode (client): false
>Debug Mode (server): false
>Registry: https://index.docker.io/v1/
>Labels:
>Experimental: false
>Insecure Registries:
> 127.0.0.0/8
>Live Restore Enabled: false
>```
>
>Using mailu tag `1.5`
>
>Please let me know if you need any extra information to help me solve
>this :-D
>
>I also would thanks the team for their awesome work ;-)
>
>Thanks by advance for help !
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Mailu/Mailu/issues/780

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by vparres** [comment]
Hi !
Happy New Year (A bit late, but so ...)

**I finally managed to resolve all my problems :** 
In fact the IPv6 problem was caused by my server's Kernel configuration ; The kernel forwarding option was disabled for an unknown reason, breaking muktiples things working with v6, even ICMP-v6 !
```
net.ipv6.conf.eth0.accept_ra = 2
net.ipv6.conf.all.forwarding = 1
net.ipv6.conf.default.forwarding = 1
```

Setting `sysctl` options to this solved my v6 problem.

About my fetchmail issue, i checked all e-mail accounts, and one of my friend set up his own account on the server throught the admin interface as an external account, causing the problem (But i don't know why it caused an issue, as fetchmail was trying to fetch the local server)

I think this issue can be closed, and i'm sorry bothering you :-)
