### ISSUE TITLE
Cannot delete/edit user with path characters in name

### ISSUE THREAD

**Issue by d-Rickyy-b** [Mailu/Mailu#794]
While playing with some security things I learned I found that if a username contains special path characters (especially `../`), it's not possible to edit or delete the user, since the path  
`https://example.com/admin/ui/user/delete/../example-user%40example.com` gets resolved to  
`https://example.com/admin/ui/user/example-user%40example.com`

### Steps to reproduce
1) Create a user with special path characters, such as `../example-user`
2) Try to get that user deleted/edited

### Expected behaviour
1) Either the user with such a name cannot be created or
2) The special path characters get escaped to get to the desired page
And the user can be edited/deleted just fine

### Actual behaviour
A 404 page pops up. There is no way to edit or remove the user.
Sadly escaping the special character won't work in the current implementation as well. Getting a 404 for `https://example.com/admin/ui/user/delete/..%2Fexample-user%40example.com`. 

Tested with latest `master` docker-compose setup.

**Comment by Nebukadneza** [comment]
Quick note: The Flask `path` converter, like described on http://flask.pocoo.org/snippets/76/ at least helps in some cases. However, quick testing revealed that, when trying:
```
-@ui.route('/user/delete/<user_email>', methods=['GET', 'POST'])
+@ui.route('/user/delete/<path:user_email>', methods=['GET', 'POST'])
```
The result is:
* `one/slash@...` works
* `dot../slash@...` works
* `../atbegin@...` does not work
* `slash/../dotslash@...` does not work

Not sure yet how a nice and complete encoding scheme could look like … :/ .

**Comment by hoellen** [comment]
We have to fix two different things here: 
- E-Mail addresses where the localpart is starting or ending with a dot `.` and double dots `..` are not valid 
- a slash in the username is not working because of the invalid path

So with `<path:user_email>` in the route and fixing the email validation everything should work.
