### ISSUE TITLE
Bundle a DNS server

### ISSUE THREAD

**Issue by dzervas** [Mailu/Mailu#80]
I found [PowerDNS-Admin](https://github.com/ngoduykhanh/PowerDNS-Admin) which looks like a vey promising admin panel for PowerDNS and uses Flask and AdminLTE2 too. I don't know how easy it would be to "port" it to freeposte, but it would be really nice to have a DNS server bundled with freeposte.

I searched for similar issues but did not find anything. Is a DNS server against the KISS principle you follow?

**Comment by kaiyou** [comment]
Pros:
- DKIM and DMARC records could be set easily
- A single Web interface to rule them all

Cons:
- Converging administration interfaces is not the purpose of Freepose, maybe cPanel or Webmin
- Safety, a single bug could take down both the mail server and the DNS infrastructure that is supposed to take over and serve alternate MX for instance
- Security, a single vulnerability could help an attacker get access not only to mails but also to the entire DNS infrastructure
- Managing DNS is a lot (orders of magnitude) more complex than managing mails (at least on a small-scale infrastructure), code for managing DNS would rapidly grow bigger than the mail management part which is the original purpose of Freeposte

For these reasons I think it would be simpler, cheaper and safer to run a separate DNS server.

**Comment by dzervas** [comment]
Why don't you add these on the wiki (I guess a lot of users will be coming from MiaB)

**Comment by kaiyou** [comment]
For now I was simply thinking out loud. Maybe there are pros that I don't see or cons that could be circumvented. What do you think?

**Comment by dzervas** [comment]
Oh forgot to express my opinion :tongue: 
About the security I fully agree, I'm very security-considered myself so yes, a "simple" flask security issue would mean the death of almost the entire infrastructure.

I thought that we could use PowerDNS-Admin as-is, as a different service, but that makes no sense as this could hapily be implemented in a different docker-compose which just authenticates over IMAP.

THOUGH, we could remove the "user" part from `/admin` and add a password change plugin in both rainloop and roundcube. So the only left are domain managers and super admins, which SHOULD know their way around and what security means and hide the admin panel from the web (VPN/SSH/etc.) which would make sense to have DNS administration too.

**Comment by curry684** [comment]
To most system administrators I think DNS is out of scope from the perspective of email. Yes, with SPF and DKIM there is some intertwining, but one could make the same case for a webserver that it's heavily intertwined with DNS, and you don't see those bundled afaik. Another argument against is that the vast majority of the target audience of FreePoste is likely not going to use it. Either they're small and they just use the DNS provided by their domain registrar (and rightfully so - it likely does have geographically distributed DNS clusters) or they're large enough to run their own geographically distributed DNS cluster. My own use case is a medium large internet bureau, and we are in the first group - we simply cannot compete with the infrastructure provided for free by our registrars.

Summing up - I think this is the wrong solution to the right problem. It **does** make sense for FreePoste to somehow be able to automatically manage DNS records elsewhere. It just makes more sense in general to make it pluggable via webhooks or another eventing system. Then the sysadmin can trivially either update it automatically in PowerDNS, or via APIs at Enom, GoDaddy, Route53 or whatever their DNS infra of choice is.

**Comment by kaiyou** [comment]
I was about to make the same point as @curry684 : it sounds much more interesting to be able to push DNS entries to some providers, and why not to PowerDNS and other DNS servers that expose APIs.

**Comment by dzervas** [comment]
Well, I maintain my own DNS/Mail/Git/etc. although I'm alone (not even a business). I think freeposte would be an interesting one-shop-stop for more people like me out there.

Well, if you implement DNS entry management through API, why not include a "basic" PowerDNS dockerfile, which will be disabled by default.

I'm still concerned though about the security of the whole idea...

**Comment by curry684** [comment]
@dzervas this discussion is closely related to https://github.com/kaiyou/freeposte.io/issues/64#issuecomment-254077525. What I describe there would solve this issue right away.

**Comment by kaiyou** [comment]
@dzervas security is indeed still an issue, but putting this aside for now.

The ideas being discussed in #64 could indeed lead to something similar to what you are trying to achieve. A default ``docker-compose.yml`` with a standard configuration enabled, some environment variables for most obvious and frequent changes/additions, plus documentation and additional images or recommended ones from third party to play with.

**Comment by hadifarnoud** [comment]
I prefer to have integration with popular DNS services rather than a DNS server. I could pitch in to add support for Rackspace DNS, Route53 (AWS), and Digitalocean DNS. using your own DNS server like MiaB has its own disadvantages.
