### ISSUE TITLE
Mixed content violation with certain WEBROOT_REDIRECT setting

### ISSUE THREAD

**Issue by d-Rickyy-b** [Mailu/Mailu#801]
When having the WEBROOT_REDIRECT setting point to `/admin` where the admin console is running on, then

![grafik](https://user-images.githubusercontent.com/5798157/50729794-22be8080-1140-11e9-89bb-78db31a0c0fd.png)

### Steps to reproduce
1) In your `.env` file set the `WEBROOT_REDIRECT=/admin`
2) Open the admin console

### Expected behaviour
All the content should be loaded via HTTPS

### Actual behaviour
Somehow there is a 301 redirect to http - see also attached screenshot. It seems to happen when the favicon is requested.

### Additional information
I am using the latest `master` docker containers with an **apache2 webserver using ProxyPass** on the host machine.

**Comment by d-Rickyy-b** [comment]
Also have a look at the capitalized `MOVED PERMANENTLY`, when the redirect to HTTP occurs.

![grafik](https://user-images.githubusercontent.com/5798157/50729927-b4c78880-1142-11e9-8e25-ae571d53ff64.png)
___

![grafik](https://user-images.githubusercontent.com/5798157/50729899-5e5a4a00-1142-11e9-951d-f82369ca61ba.png)
___

![grafik](https://user-images.githubusercontent.com/5798157/50729908-7b8f1880-1142-11e9-9122-f1e909df13fa.png)

**Comment by muhlemmer** [comment]
I've used the same Mailu settings and I'm not seeing the mixed context violation. All redirects point to the `https://` address in Firefox.

I've rerun the favicon request in `wget`:
```
wget http://mail.usrpro.io/favicon.ico
--2019-01-06 14:26:33--  http://mail.usrpro.io/favicon.ico
Resolving mail.usrpro.io (mail.usrpro.io)... 5.189.138.127, 2a02:c207:2019:6443::1
Connecting to mail.usrpro.io (mail.usrpro.io)|5.189.138.127|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://mail.usrpro.io/favicon.ico [following]
--2019-01-06 14:26:34--  https://mail.usrpro.io/favicon.ico
Connecting to mail.usrpro.io (mail.usrpro.io)|5.189.138.127|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /admin [following]
--2019-01-06 14:26:34--  https://mail.usrpro.io/admin
Reusing existing connection to mail.usrpro.io:443.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /admin/ui [following]
--2019-01-06 14:26:34--  https://mail.usrpro.io/admin/ui
Reusing existing connection to mail.usrpro.io:443.
HTTP request sent, awaiting response... 301 MOVED PERMANENTLY
Location: https://mail.usrpro.io/admin/ui/ [following]
--2019-01-06 14:26:34--  https://mail.usrpro.io/admin/ui/
Reusing existing connection to mail.usrpro.io:443.
HTTP request sent, awaiting response... 302 FOUND
Location: https://mail.usrpro.io/admin/ui/login?next=ui.index [following]
--2019-01-06 14:26:34--  https://mail.usrpro.io/admin/ui/login?next=ui.index
Reusing existing connection to mail.usrpro.io:443.
HTTP request sent, awaiting response... 200 OK
Length: 4377 (4.3K) [text/html]
Saving to: ‘favicon.ico’
```
We can see a correct redirect from `http` to `https` and every subsequent redirect is to `https`.

Looking in the server logs, we are never redirecting to a full address, only relative to the webroot:
```
front_1      | <ip> - - [06/Jan/2019:12:26:33 +0000] "GET /favicon.ico HTTP/1.1" 301 178 "-" "Wget/1.19.5 (linux-gnu)"
front_1      | <ip> - - [06/Jan/2019:12:26:34 +0000] "GET /favicon.ico HTTP/1.1" 301 178 "-" "Wget/1.19.5 (linux-gnu)"
front_1      | <ip> - - [06/Jan/2019:12:26:34 +0000] "GET /admin HTTP/1.1" 301 178 "-" "Wget/1.19.5 (linux-gnu)"
front_1      | <ip> - - [06/Jan/2019:12:26:34 +0000] "GET /admin/ui HTTP/1.1" 301 271 "-" "Wget/1.19.5 (linux-gnu)"
front_1      | <ip> - - [06/Jan/2019:12:26:34 +0000] "GET /admin/ui/ HTTP/1.1" 302 265 "-" "Wget/1.19.5 (linux-gnu)"
front_1      | <ip> - - [06/Jan/2019:12:26:34 +0000] "GET /admin/ui/login?next=ui.index HTTP/1.1" 200 4377 "-" "Wget/1.19.5 (linux-gnu)"
```
So most probably it's Apache prepending the server name and protocol, or a browser bug.

Besides that, we don't have a `favicon.ico` anywhere. So we could serve a proper 404 for this case. (or provide a favicon).

At this moment we have a "magic" redirect where everything gets redirected to a certain path. In `1.5` the default was to always redirect to `/webmail`. In `master` we made it optional to any path the user wants. (including disabling it). Personally, I'm against using "redirect everything" since it can lead to this kind of issues. Hence, I've disabled it on my servers.

So there should be a debate: should be start providing 404 rules for exotic cases like `/favicon.ico`? Or, if the user is annoyed by this, he can just disable the redirect option altogether.

**Comment by d-Rickyy-b** [comment]
More information found from debugging another issue [here](https://github.com/Mailu/Mailu/issues/802#issuecomment-451752059).

**Comment by d-Rickyy-b** [comment]
I tried connecting from the host machine to the local webserver in the docker container via curl and this is what I got.

![grafik](https://user-images.githubusercontent.com/5798157/50741242-a0df5d80-11fa-11e9-8c74-0c0b4e62cd17.png)

You see the fully qualified path `http://localhost:5001/admin/ui`? It's also where the caps "MOVED PERMANENTLY" comes from. This has nothing to do with the apache I use as a proxy.

Digging into it further, I went in the admin docker container and it seems that gunicorn is responsible for this. At least it is producing CAPS headers as you can see here:

![grafik](https://user-images.githubusercontent.com/5798157/50741572-311fa180-11ff-11e9-8581-127799dad785.png)

Now the question is, where this is coming from.

**Comment by d-Rickyy-b** [comment]
I changed my `.env` settings to

```
# Path to redirect / to
#WEBROOT_REDIRECT=/admin

# Path to the admin interface if enabled
WEB_ADMIN=/admin

# Path to the webmail if enabled
#WEB_WEBMAIL=/webmail
```

That way I don't get any mixed content warning, because the favicon gets a *proper 404*!

But sadly I still get redirected to http for `/admin/ui` - mind that `/admin/ui/` works fine!

![grafik](https://user-images.githubusercontent.com/5798157/50742818-48b35600-1210-11e9-8311-7da6be44c2af.png)

It seems to be somewhat related to [this issue](https://github.com/pallets/flask/issues/1783) of Flask. This is where the http redirects are coming from.

**Comment by muhlemmer** [comment]
I honestly have no idea what's going on. I have no experience myself ever setting up Apache. But here are some suggestions:

- Admin only serves **http**, always. **https** in handled by the `front` container.
- Your reverse proxy should always point to the `front` container
- The `front` container needs valid certs to serve TLS and https.
- The reverse proxy needs to be setup properly to only serve https, forwarding any http request to https.

Have you looked to the suggestion in: https://mailu.io/master/reverse.html. There are some different techniques used by different Proxy front-ends. Maybe you'll find the solution there.

**Comment by d-Rickyy-b** [comment]
Thanks for your time.

I have an apache which serves as my main web frontend. I have several applications running as docker containers as backend. I use Apache to proxy the requests with `ProxyPass` (mod_proxy). That means that the apache also handles all https connections to the clients, while internally it uses http to the containers.

When accessing `/admin/ui` Flask is redirecting me to a fully qualified url such as `http://mailing.example.com/admin/ui/`

You can see that this has nothing to do with my apache, when I do the request from localhost to the `front` container via curl:

![grafik](https://user-images.githubusercontent.com/5798157/50764591-78477a00-1273-11e9-8f7b-dd2177fbd080.png)

Can you please try to reproduce this? I am still trying to find the exact source of the issue. Also if possible check out the issue of Flask I mentioned - maybe that helps.

I also checked out the FAQ - but it wasn't really helpful since this is the setup I am using, but with Apache & it's very likely not an apache issue. I'll try one thing from that article and report if it helped.

**Comment by d-Rickyy-b** [comment]
Okay - I guess I found what causes the issue.

My apache config was basically

```
ProxyPass / http://localhost:5001/
ProxyPassReverse / http://localhost:5001/
```

while my docker config read

```
front:
  ports:
    - "127.0.0.1:5001:80"
```

That probably lead to the issue that flask, which is making the redirect I am talking about, redirected to the fully qualified URL with the same protocol the request came in.
___
**Solution:**
After switching to the apache config (_changed protocol to https_):

```
ProxyPass / https://localhost:5001/
ProxyPassReverse / https://localhost:5001/
```

and the docker-compose config (_changed container port to 443_):

```
front:
  ports:
    - "127.0.0.1:5001:443"
```

It works now. BUT the fully qualified redirect from flask is still happening. Even on your testserver.
___
**Suggestion:** In the [article you sent me](https://mailu.io/master/reverse.html) it says `In practice, you only need to point to the HTTPS port (as the HTTP port simply redirects there)`. This is a bit misleading, since in order to have a clean HTTPS site (with no redirect to HTTP in between & no mixed content) you need to use the latter config I posted and hence can not use the port 80. That could be better explained in the documentation.

Than you guys for your time and for the great product. I am really in love with it.

**Comment by muhlemmer** [comment]
The mentioned article is mostly written up by people with certain experiences. For instance there is also a Traefik example which connects to port 80 of the front and takes care of the HTTPS stuff on the proxy end, with the `TLS_FLAVOR=mail`. There are more roads that lead to Rome. Anybody is free to add their experiences to the documentation.

As for flask, we are not affected by a bug here. Requests are redirected to https on the first request and after that remain stick to that. Nginx as a reverse proxy is making sure of that:
```
wget http://test.mailu.io
--2019-01-07 12:53:27--  http://test.mailu.io/
Resolving test.mailu.io (test.mailu.io)... 173.249.45.89
Connecting to test.mailu.io (test.mailu.io)|173.249.45.89|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://test.mailu.io:443/ [following]
--2019-01-07 12:53:27--  https://test.mailu.io/
Connecting to test.mailu.io (test.mailu.io)|173.249.45.89|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /webmail [following]
--2019-01-07 12:53:28--  https://test.mailu.io/webmail
Reusing existing connection to test.mailu.io:443.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /webmail/ [following]
--2019-01-07 12:53:28--  https://test.mailu.io/webmail/
Reusing existing connection to test.mailu.io:443.
HTTP request sent, awaiting response... 200 OK
Length: 1485 (1.5K) [text/html]
Saving to: ‘index.html’
```

**Comment by d-Rickyy-b** [comment]
> As for flask, we are not affected by a bug here

The bug is that flask is redirecting to a fully qualified URL here. It's not about http/https. If flask would have redirected to a relative path, the issue wouldn't have happened in the first place.

Check `Location: https://test.mailu.io:443/ [following]` in your server's response.

Same for ` curl -i https://test.mailu.io/admin/ui -IX GET` which leads to `Location: https://test.mailu.io/admin/ui/`
