### ISSUE TITLE
Redirect loop on certain WEBROOT_REDIRECT settings

### ISSUE THREAD

**Issue by d-Rickyy-b** [Mailu/Mailu#802]
On certain WEBROOT_REDIRECT settings it happens that the browser is stuck in a loop.

![grafik](https://user-images.githubusercontent.com/5798157/50729958-48995480-1143-11e9-87a2-4bcf9e0d932b.png)

![grafik](https://user-images.githubusercontent.com/5798157/50730020-22c07f80-1144-11e9-9858-157828063115.png)

![grafik](https://user-images.githubusercontent.com/5798157/50730045-57343b80-1144-11e9-96a3-12eb472b4aa1.png)

### Steps to reproduce
1) Set `WEBROOT_REDIRECT=/webmail`
2) Open the admin interface

**\*EDIT\***: I have the webmail interface disabled for my server.

### Expected behaviour
Site loads accordingly - no loops happening

### Actual behaviour
The site loads accordingly, but there are several HTTP Requests which lead to a loop

### Additional information
I am using the latest `master` docker containers with an apache2 webserver using ProxyPass on the host machine.

**Comment by muhlemmer** [comment]
I'm unable to reproduce the infinite redirect loop, using Firefox. I see a single redirect to /webmail, which is consistent with the "redirect everything" behavior as explained in #801. It is strange that your browser is trying to load `webmail` and not `/webmail`

Also, ran this query in `wget`:
```
wget https://mail.usrpro.io/favicon.ico
--2019-01-06 14:58:29--  https://mail.usrpro.io/favicon.ico
Resolving mail.usrpro.io (mail.usrpro.io)... 5.189.138.127, 2a02:c207:2019:6443::1
Connecting to mail.usrpro.io (mail.usrpro.io)|5.189.138.127|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /webmail [following]
--2019-01-06 14:58:29--  https://mail.usrpro.io/webmail
Reusing existing connection to mail.usrpro.io:443.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /webmail/ [following]
--2019-01-06 14:58:29--  https://mail.usrpro.io/webmail/
Reusing existing connection to mail.usrpro.io:443.
HTTP request sent, awaiting response... 200 OK
Length: 1485 (1.5K) [text/html]
Saving to: ‘favicon.ico.2’
```
On the server:
```
front_1      | <ip> - - [06/Jan/2019:12:58:29 +0000] "GET /favicon.ico HTTP/1.1" 301 178 "-" "Wget/1.19.5 (linux-gnu)"
front_1      | <ip>- - [06/Jan/2019:12:58:29 +0000] "GET /webmail HTTP/1.1" 301 178 "-" "Wget/1.19.5 (linux-gnu)"
front_1      | <ip> - - [06/Jan/2019:12:58:29 +0000] "GET /webmail/ HTTP/1.1" 200 1485 "-" "Wget/1.19.5 (linux-gnu)"
```

Just as #801, I suspect Apache doing the funny stuff. Not saying this behavior is correct, we should still have the favicon discussion. But the infinite loop is most probably not caused by Mailu config.

**Comment by d-Rickyy-b** [comment]
> It is strange that your browser is trying to load `webmail` and not `/webmail`

It indeed is trying to load `/webmail` - the firefox network analyzer just displays `webmail` in the "File" column. In the details (check the third screenshot) it shows the full address it requested which was `https://domain.tld/webmail`

 This is what I get for wget.
![grafik](https://user-images.githubusercontent.com/5798157/50736408-9488df80-11bd-11e9-95a1-572943d3346d.png)
`20 redirections exceeded.`

Apache access log (host):
```
xxx.xxx.xxx.xxx - - mailing.xxx.tld:443 [06/Jan/2019:14:13:29 +0100] "GET /favicon.ico HTTP/1.1" 301 3914 "-" "Wget/1.18 (linux-gnu)"
xxx.xxx.xxx.xxx - - mailing.xxx.tld:443 [06/Jan/2019:14:13:29 +0100] "GET /webmail HTTP/1.1" 301 654 "-" "Wget/1.18 (linux-gnu)"
xxx.xxx.xxx.xxx - - mailing.xxx.tld:443 [06/Jan/2019:14:13:29 +0100] "GET /webmail HTTP/1.1" 301 654 "-" "Wget/1.18 (linux-gnu)"
xxx.xxx.xxx.xxx - - mailing.xxx.tld:443 [06/Jan/2019:14:13:29 +0100] "GET /webmail HTTP/1.1" 301 654 "-" "Wget/1.18 (linux-gnu)"
...
```

Docker logs (`docker-compose logs -f --tail=5`)
```
admin_1      | 127.0.0.1 - - [06/Jan/2019:14:03:19 +0000] "GET /ui/login?next=ui.index HTTP/1.1" 200 4316 "-" "curl/7.61.1"
front_1      | 172.19.0.1 - - [06/Jan/2019:14:03:24 +0000] "GET /favicon.ico HTTP/1.1" 301 178 "-" "Wget/1.19.4 (linux-gnu)"
front_1      | 172.19.0.1 - - [06/Jan/2019:14:03:24 +0000] "GET /webmail HTTP/1.1" 301 178 "-" "Wget/1.19.4 (linux-gnu)"
front_1      | 172.19.0.1 - - [06/Jan/2019:14:03:24 +0000] "GET /webmail HTTP/1.1" 301 178 "-" "Wget/1.19.4 (linux-gnu)"
front_1      | 172.19.0.1 - - [06/Jan/2019:14:03:24 +0000] "GET /webmail HTTP/1.1" 301 178 "-" "Wget/1.19.4 (linux-gnu)"
front_1      | 172.19.0.1 - - [06/Jan/2019:14:03:24 +0000] "GET /webmail HTTP/1.1" 301 178 "-" "Wget/1.19.4 (linux-gnu)"
...
```

Can you maybe spot where this is originating from?

**Comment by muhlemmer** [comment]
If WEBMAIL is set to 'none', then that path is no longer defined in nginx.conf. This means you are redirecting to a non existing path, which will indeed trigger the next redirect, and yes it will loop.

The WEBROOT_REDIRECT setting redirects everything not defined or found. It should be pointing to an existing path or ommited. If ommited, redirecting will be disabled altogether. 

On 6 January 2019 16:29:13 EET, Rico <notifications@github.com> wrote:
>I tried several settings. This is the one I took the screenshots with:
>
>![graphic](https://user-images.githubusercontent.com/5798157/50737291-b38c6f00-11c7-11e9-81e9-615981912de7.png)
>
>So yes, it's with the leading slash. Mind that I do not use the webmail
>interface. I should have mentioned that! So it's basically a 404.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/Mailu/Mailu/issues/802#issuecomment-451745817

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by d-Rickyy-b** [comment]
Thank you very much. I appreciate your help a lot. With the following settings it works like a charm. No more redirects.

```
# Path to redirect / to
WEBROOT_REDIRECT=/admin

# Path to the admin interface if enabled
WEB_ADMIN=/admin

# Path to the webmail if enabled
#WEB_WEBMAIL=/webmail
```

**BUT** now I get the issue #801 again. Related to that I just found:

![grafik](https://user-images.githubusercontent.com/5798157/50738219-cc9a1d80-11d1-11e9-9dec-4ea1a0eecbaa.png)

<details>
  <summary>Code to copy</summary>
<pre>
rico@Anonymous:~$ wget https://mailing.example.de/favicon.ico
Will not apply HSTS. The HSTS database must be a regular and non-world-writable file.
ERROR: could not open HSTS store at '/home/rico/.wget-hsts'. HSTS will be disabled.
--2019-01-06 16:28:38--  https://mailing.example.de/favicon.ico
Resolving mailing.example.de (mailing.example.de)... xxx.xxx.xxx.xxx
Connecting to mailing.example.de (mailing.example.de)|xxx.xxx.xxx.xxx|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /admin [following]
--2019-01-06 16:28:38--  https://mailing.example.de/admin
Reusing existing connection to mailing.example.de:443.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /admin/ui [following]
--2019-01-06 16:28:38--  https://mailing.example.de/admin/ui
Reusing existing connection to mailing.example.de:443.
HTTP request sent, awaiting response... 301 MOVED PERMANENTLY
Location: http://mailing.example.de/admin/ui/ [following]
--2019-01-06 16:28:38--  http://mailing.example.de/admin/ui/
Connecting to mailing.example.de (mailing.example.de)|xxx.xxx.xxx.xxx|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://mailing.example.deadmin/ui/ [following]
--2019-01-06 16:28:38--  https://mailing.example.deadmin/ui/
Resolving mailing.example.deadmin (mailing.example.deadmin)... failed: Name or service not known.
wget: unable to resolve host address 'mailing.example.deadmin'
</pre>
</details>
