### ISSUE TITLE
Cannot send mail from external application (PHP) trough SMTP

### ISSUE THREAD

**Issue by tahonaPL** [Mailu/Mailu#807]
Hi, 

I'm trying to use "Mailu" to send emails for my application in PHP. As a specific user.

I use PHPMailer with : 
-username  
-password 
- port 25 

And I getting - SMTP Error: Could not authenticate. I think it have something with SMTP and AUTH LOGIN. I tried to invoke action using telnet :

220 hostname.com ESMTP ready
EHLO local
250 hostname.com
AUTH LOGIN
334 VXNlcm5hbWU6 // username
echo "xxx@mail.com"| base64 
334 UGFzc3dvcmQ6 //password
echo "pass"| base64
535 5.7.8 Authentication credentials invalid

Note: 
Application (PHP) is not in docker network. 
I use docker-compose (all in one).

**Comment by tahonaPL** [comment]
Found issue :
Nginx "smtp_auth none" needs to change to "smtp_auth plain". 

How to override this ?  I tried: 

FROM mailu/nginx:1.5

CMD /start.py && \
    sed -i "s/smtp_auth none/smtp_auth plain/g" /etc/nginx/nginx.conf && \
    nginx -s reload

And it is not working.

**Comment by HorayNarea** [comment]
Port 25 is for server-to-server communication only, you should submit mails on port 587 and use TLS

**Comment by tahonaPL** [comment]
> Port 25 is for server-to-server communication only, you should submit mails on port 587 and use TLS

Well I would need to setup certs and so on, and mail configuration for me is one of the worst thing. It is very difficult.

**Comment by muhlemmer** [comment]
Certs are easy. If you have a `hostname.com` set in the `HOSTNAMES` variable, and you set `TLS_FLAVOR=letsencrypt` you'll have certs within 1 minute, automatically.

**Comment by tahonaPL** [comment]
> Certs are easy. If you have a `hostname.com` set in the `HOSTNAMES` variable, and you set `TLS_FLAVOR=letsencrypt` you'll have certs within 1 minute, automatically.

Getting 403 when using own subdomain like: mail.xxx.com (A record), and TLS_FLAVOR=letsencrypt. If it is notls. working as it should. 

env: 

DOMAIN=mail.xxx.com
HOSTNAMES=mail.xxx.com

TLS_FLAVOR=letsencrypt
WEBSITE=https://mail.xxx.com

**Comment by tahonaPL** [comment]
Ohh just refreshed page on server - and it's starts to working. Can someone explain this to me? I did not have any change.

**Comment by HorayNarea** [comment]
Is your installation up-to-date? …in 1.5 before commit e2ce62cbd0908e9aabf3fe953d8044d29b25de19 we generated dh-params on the containers first run (and only if TLS is enabled) which could take a long time, depending on available randomness
