### ISSUE TITLE
Move roundcube out of webroot

### ISSUE THREAD

**Issue by senilio** [Mailu/Mailu#82]
Keeping it directly in the webroot causes issues when fronting with a reverse proxy running in a subdir. Running roundcube from /var/www/html/webmail will make it more proxy friendly.

**Comment by kaiyou** [comment]
I do not see any idea why not. It would simply things with external reverse proxies and even make it possible to host other content in other subdirectories. I will also have the front nginx serve the Webmail as ``/webmail`` and redirect ``/`` to ``/webmail``.
