### ISSUE TITLE
OpenId connect module

### ISSUE THREAD

**Issue by pierreozoux** [Mailu/Mailu#823]
Linked to my https://github.com/Mailu/Mailu/issues/783#issuecomment-451759039 , I'd like to discuss if upstream would like this feature to happen so that I can start to think on how to implement it.

For the WebUI, I think OpenId connect is the best to have a central login system., but then with technologies like OpenID connect, it works great for everything web, but for things not web, it doesn't.
If you look at solutions for this specific problem, there is one that come to my mind, and this is the strategy of Google or Nextcloud.

--> App password.

Once the user is connected to the webUI, you let the user generate app password to be able to create them, revoke them and use them from their traditional mail client.

I'd be really interested in this feature.

**Comment by kaiyou** [comment]
Application password is already available, these are named "authentication tokens", you can restrict them to a given client IP and revoke them at any time from the admin UI.

**Comment by vchoi** [comment]
> Application password is already available, these are named "authentication tokens", you can restrict them to a given client IP and revoke them at any time from the admin UI.

About the feature name... For me, it makes sense to name them auth token internally, so they're not confused with user passwords. However the term app password is so popular that I can't think of a reason not to use it in the documentation and UI.

I'm really interested in this feature and I've spent a moment reading the commits in PR #292. From that, it seems to me that the only way to manage the app passwords is from the admin interface, is that right? 

This feature would be more accessible with a new name and more useful if the user had access to create their own app passwords. What are your thoughts on these, @kaiyou ?

**Comment by hoellen** [comment]
> This feature would be more accessible with a new name and more useful if the user had access to create their own app passwords.

@vchoi Authentication tokens are also available for users. I don't know if that confuses you a bit: the admin ui is not only for the server administrator. A user can set there a new password, authentication tokens, auto response settings, etc...

**Comment by vchoi** [comment]
Thanks for the clarification, @hoellen.

**Comment by pierreozoux** [comment]
To give more background, let me detail our workflow.

As a user, I want to self register to https://indie.host.

Here the implementation detail is that the user self register to keycloack.

As a user I want to self serve my email address.

Here the implementation detail is that the user pays, and we modify a flag in keycloack to let mailu OpenId connect client access this user.

As a user, I want to access mailu admin interface with my SSO.

Here the implementation detail is that, the user goes to https://mail.indie.host, click on login, gets redirected to Keycloack, fills the details, and is authN into mailu with it's email.

Most of OpenIdconnect implementations out there, create users on first login, and sync data on each login (in this case the Displayname I guess).
But if mailu has an API, the admin can decide to create the user (hence the mailbox) whener they feel necessary.
Deletion is the same, it is left as an exercise to the admin.
Then about authZ, I'd keep it simple at first, meaning it is not implemented, and this happens in mailu only.(we could pass some group, roles info, but let's keep it for later)

As a user I want to configure my email client.

The instruction will tell the user to use an authN token.

Then, the only remaining story is the admin story.

As a mailu admin, I want to configure an OpenId connect server.

From the top of my head, you need to configure at least 2 things:
- the token
- the endpoint

The only remaining question is where you find the email and the display name.
In the wild client implementors provide easy way to configure popular providers (google, Facebook) and so the client is already configured to find the right info in the right place.(OIdC is not opinionated about the json).
I personally don't care about these providers, and not sure it makes sense in this context. I propose that we start to implement a "generic" provider.
To do so, it has to be flexible on where to find the info in the json, and I propose the following templating mechanisme.:
Given the following json:
```
{
 user: {
    firstname: "Pierre",
    lastname: "Ozoux",
    username: "pierre.ozoux"
  },
  realm: {
    domainname: "example.org"
  }
}

Displayname: `#{user.firstname} #{user.lastname}`
Email: `#{user.username}@#{realm.domainname}`

I think this is flexible for most of.people out there.

Hope it clarifies my needs, feel free to comment if it was not clear, or there is something I missed?

**Comment by kaiyou** [comment]
I am closing in favor of #783
