### ISSUE TITLE
Add support to openldap

### ISSUE THREAD

**Issue by thiagoalmeidasa** [Mailu/Mailu#83]
Would be nice to integrate this stack with an external openldap to auth smtp and imap.
Have you thought about it?

**Comment by kaiyou** [comment]
I did, and I dismissed the idea at first, the spirit was to get a simple mail server up and running. Most database structures are thus based on SQLite and are pretty much *-SQL compatible but OpenLDAP compatibility is another story.

Using Openldap only for authentication would be an option, but then Dovecot could inherit the responsibility of authenticating users or so. For this to work properly, I believe that a central service - let's say a central API - would have to provide the authentication socket to all services and then handle external authentication if required, plus all domain-specific data structures.

It is technically possible, but I would not expect it to be available any time soon, the first strong requirement is a clean central API service. Let's keep the issue open for discussion.

**Comment by jcgruenhage** [comment]
Is there any progress in decoupling authentication? I want to migrate my mail server to mailu, but I really don't want to maintain multiple account stores.

**Comment by benyanke** [comment]
Would also appreciate LDAP integration. Don't have a ton of time to help implement, but would help test and use it when it hits prod.

**Comment by benyanke** [comment]
I'd also like to throw in a plug for the project I maintain, [glauth](https://github.com/glauth/glauth). It has a docker image, and could perhaps be integrated in.

**Comment by BirgerK** [comment]
I'm also very interested into this feature.

I took a look into the code. Do I get it right, there is already the "admin-internal"-service which provides - at least for dovecot - the auth-mechanism.
I think the LDAP-integration could be implemented in that service. If that's all I would do it.

Am I right?

**Comment by jcgruenhage** [comment]
@BirgerK If you just want to use LDAP for authenticating users that are already known to mailu, then that should be nearly all yes. The one missing thing would be config through the UI.

**Comment by BirgerK** [comment]
What did you mean by "config through UI"?

- are the mailu-config-params set through UI? (I thought it's configured through Env-aprams)
or
- do you mean how the UI authenticates itself?

**Comment by jcgruenhage** [comment]
I mean that currently accounts are managed using the UI. The UI should still be able to manage things about user accounts that are not done by LDAP, and managing the LDAP configuration itself could also be done through the web UI

**Comment by BirgerK** [comment]
Hi again,
I'm currently implementing the LDAP-auth-mechanism into the admin-internal-service. By that, every service which authenticates by the admin-internal-service, will be authenticated against LDAP.

By doing this, the UI will still be able to configure some "mail-server-local" users. I will care about the LDAP-users which are using the UI.

@jcgruenhage I'm not sure, if the UI is the right spot to configure LDAP. After a quick googling I think that, Roundcube e.g. can't pass any Configuration to anywhere. Or is there a way to pass params from e.g. Roundcube?
It's even hackish how Roundcube authenticates itself... against a SQLite... Which has "randomly" the same schema which the admin-internal-service uses... Mailu is using the Microservice-architecture, but not on that spot. Two services which are using the same database - and are strong coupled by that - is not really MicroService'ish. ...But that's out of this issue!

**Comment by jcgruenhage** [comment]
I don't mean the web mail client, the admin container itself serves a web interface. mailu serves that on /admin by default, see https://mail.jcg.re/admin for example. That is used to configure mail domains, and IMO should also be used to configure LDAP.

**Comment by muhlemmer** [comment]
Hi guys, the current authentication process for dovecot and smtp is working through podop. A podop server is run inside the containers and send queries to the admin container. Inside the admin container, the podop queries are mapped to flask/sqlalchemy functions. The same flask ORM is used for the management functions in the admin UI. Also, model (table) definitions are in sqlalchemy/albemic.

It will be hard to crack open this mechanism to support ldap. And probably near-impossible to keep the Mailu models and data in sync with the ldap server. (How will you handle if we decide to add or modify a table column?)

There are more viable solutions:
- ldap supports using sql database back-end. So you could map ldap to use the Mailu DB. If you need something performant, We are working on postgresql support as we speak.
- use postgresql and set up foreign data wrappers to create an sql shell on top of ldap.

Good luck with your quest ;)

On November 27, 2018 10:33:04 PM GMT+01:00, "Jan Christian Grünhage" <notifications@github.com> wrote:
>I don't mean the web mail client, the admin container itself serves a
>web interface. mailu serves that on /admin by default, see
>https://mail.jcg.re/admin for example. That is used to configure mail
>domains, and IMO should also be used to configure LDAP.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Mailu/Mailu/issues/83#issuecomment-442225158

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by muhlemmer** [comment]
Hi guys, the current authentication process for dovecot and smtp is working through podop. A podop server is run inside the containers and send queries to the admin container. Inside the admin container, the podop queries are mapped to flask/sqlalchemy functions. The same flask ORM is used for the management functions in the admin UI. Also, model (table) definitions are in sqlalchemy/albemic.

It will be hard to crack open this mechanism to support ldap. And probably near-impossible to keep the Mailu models and data in sync with the ldap server. (How will you handle if we decide to add or modify a table column?)

There are more viable solutions:
- ldap supports using sql database back-end. So you could map ldap to use the Mailu DB. If you need something performant, We are working on postgresql support as we speak.
- use postgresql and set up foreign data wrappers to create an sql shell on top of ldap.

Good luck with your quest ;)

On November 27, 2018 10:33:04 PM GMT+01:00, "Jan Christian Grünhage" <notifications@github.com> wrote:
>I don't mean the web mail client, the admin container itself serves a
>web interface. mailu serves that on /admin by default, see
>https://mail.jcg.re/admin for example. That is used to configure mail
>domains, and IMO should also be used to configure LDAP.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Mailu/Mailu/issues/83#issuecomment-442225158

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by muhlemmer** [comment]
Hi guys, the current authentication process for dovecot and smtp is working through podop. A podop server is run inside the containers and send queries to the admin container. Inside the admin container, the podop queries are mapped to flask/sqlalchemy functions. The same flask ORM is used for the management functions in the admin UI. Also, model (table) definitions are in sqlalchemy/albemic.

It will be hard to crack open this mechanism to support ldap. And probably near-impossible to keep the Mailu models and data in sync with the ldap server. (How will you handle if we decide to add or modify a table column?)

There are more viable solutions:
- ldap supports using sql database back-end. So you could map ldap to use the Mailu DB. If you need something performant, We are working on postgresql support as we speak.
- use postgresql and set up foreign data wrappers to create an sql shell on top of ldap.

Good luck with your quest ;)

On November 27, 2018 10:33:04 PM GMT+01:00, "Jan Christian Grünhage" <notifications@github.com> wrote:
>I don't mean the web mail client, the admin container itself serves a
>web interface. mailu serves that on /admin by default, see
>https://mail.jcg.re/admin for example. That is used to configure mail
>domains, and IMO should also be used to configure LDAP.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Mailu/Mailu/issues/83#issuecomment-442225158

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by BirgerK** [comment]
@jcgruenhage thanks for that, I'll keep that in my mind!

@muhlemmer I'm not going to include the LDAP-data into the SQLite-file. That would be "complicated".
The authentication happens by calling a Flask-URL. I'm going to add a second authentication-provider beneath the SQL-auth-queries, which will be processed on that Flask-URL.
By that the SQL-stuff works like it ever did. And LDAP-users can authenticates themself.

**Comment by BirgerK** [comment]
I provided the PR: https://github.com/Mailu/Mailu/pull/715

The code works. I would like to get your feedback to that. :)

**Comment by muhlemmer** [comment]
Partial solution / code of PR #715 is now stored in a branch: https://github.com/Mailu/Mailu/tree/feat-ldap-auth. Anybody that is willing to pick this up than start from there. Thanks to @BirgerK for the effort so far.

**Comment by kaiyou** [comment]
Most of this is now documented. Official support might come as part of #783, closing here.
