### ISSUE TITLE
External reverse proxy leads to ERR_SSL_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by DCsunset** [Mailu/Mailu#848]
Mailu version: 1.6 or master

When I'm using an external reverse proxy, I follow the instructions at https://mailu.io/1.6/reverse.html.
I just setup the reverse proxy and add `proxy_pass` to it.
Without the reverse proxy, the TLS works fine.
After adding the reverse proxy, I get an ERR_SSL_PROTOCOL_ERROR error in browser visiting /webmail.

My external nginx also runs in docker, so I add a network connecting it and mailu's front.
So the reverse proxy can visit mailu's front directly.
Is there anything wrong with this configuration?

Thanks in advance.

**Comment by ofthesun9** [comment]
Hello,
Did you see the various TLS_FLAVOR (https://mailu.io/1.6/compose/setup.html#tls-certificates) ?
I guess you need the mail flavor

**Comment by DCsunset** [comment]
Thanks for your reply.
After configuring it for a whole day,
I have finally made it work.

First, the TLS_FLAVOR should be set to mail.
But I don't know whether it's enough to make it work.
Then, I use the external proxy to accomplish tls,
and change

```
proxy_pass https://container:443
```

into

```
proxy_pass http://container:80
proxy_set_header Host $http_host;
```

After these steps, it finally work.

**Comment by vinanrra** [comment]
> 
> 
> Thanks for your reply.
> After configuring it for a whole day,
> I have finally made it work.
> 
> First, the TLS_FLAVOR should be set to mail.
> But I don't know whether it's enough to make it work.
> Then, I use the external proxy to accomplish tls,
> and change
> 
> ```
> proxy_pass https://container:443
> ```
> 
> into
> 
> ```
> proxy_pass http://container:80
> proxy_set_header Host $http_host;
> ```
> 
> After these steps, it finally works.

Can u share your config becuase im trying to get works and its giving me errors
