### ISSUE TITLE
Cannot create admin password on kubernetes

### ISSUE THREAD

**Issue by xelfe** [Mailu/Mailu#849]
I cannot do python manage.py admin root domain.ltd passw0rd.
Once into the pod I had to switch to the /app/mailu path.
python command is not available but I tried with python3, pythin3.6 and python3.6m and each time I got the message; 

```
Traceback (most recent call last):
  File "manage.py", line 1, in <module>
    from mailu import models
ModuleNotFoundError: No module named 'mailu'
```

**Comment by hoellen** [comment]
You need to use `flask mailu admin root domain.tld password` to create an admin account (see [docker-compose doc](https://mailu.io/1.6/compose/setup.html#start-mailu)). 
The Kubernetes part is outdated. I will fix it. Thanks for reporting.

**Comment by xelfe** [comment]
Allright. I will wait for your update. There are several things that do not work even using flask for creating admin password. I would really like to use mailu on my kubernetes infrastructure

**Comment by roman009** [comment]
Any updates on this? Seems something is not working properly. I get 404s while accessing the the `admin` and `webmail` containers. 

Also there is this issue with the `webmail` igress
```
2019/02/05 09:35:49 [emerg] 2537#2537: unknown "proxy_x_forwarded_proto" variable
nginx: [emerg] unknown "proxy_x_forwarded_proto" variable
```

which causes the `ingress-controller` to crash

**Comment by johnae** [comment]
Same here. I just get 404:s and the above mentioned nginx error.

**Comment by xelfe** [comment]
Same for me guys. after using the right way to create admin user  I got error 404 too

**Comment by dsayan154** [comment]
is this issue resolved? after following the documentation for kubernetes setup I am getting 404 on all ingress paths including  . the webmail is also throwing 404 and the ingress logs say : 
2019/06/17 04:08:08 [emerg] 31420#31420: unknown "proxy_x_forwarded_proto" variable

the above is also coming for antispam, antivirus
