### ISSUE TITLE
Modularize authentication

### ISSUE THREAD

**Issue by pierreozoux** [Mailu/Mailu#855]
Based on [this comment](https://github.com/Mailu/Mailu/issues/783#issuecomment-453734907) we need to modularize authentication.

This will then allow to be able to build and let the admin select various authentication modules, like:

- OpenId Connect https://github.com/Mailu/Mailu/issues/823
- FrreIPA https://github.com/Mailu/Mailu/issues/605.
- OpenLdap https://github.com/Mailu/Mailu/issues/83

**Comment by glego** [comment]
Instead of building everything within Mailu, why not connect to an sts like [keycloak ](https://www.keycloak.org/)and let it handle the directory services like LDAP and Active Directory. It can also broker OpenID Connect and SAML 2.0.

**Comment by kaiyou** [comment]
Mostly because it does not handle the email concepts natively. How would you proceed when the idp returns an email that is on no known domain?

**Comment by kaiyou** [comment]
I am closing this in favor of #783 for redesigning the authentication model.
