### ISSUE TITLE
persistent volume claim readWriteMany vs readWriteOnce

### ISSUE THREAD

**Issue by sonamsamdupkhangsar** [Mailu/Mailu#863]
On DigitalOcean the PersistentVolumeClaim can only use for accessModes as ReadWriteOnce not ReadWriteMany as it's defined in your pvc.yaml.  
Is that okay?

**Comment by muhlemmer** [comment]
Pvc.yaml? I'm afraid I have no idea what you are talking about... 

On 22 January 2019 22:43:10 EET, Sonam Samdupkhangsar <notifications@github.com> wrote:
>On DigitalOcean the PersistentVolumeClaim can only use for accessModes
>as ReadWriteOnce not ReadWriteMany as it's defined in your pvc.yaml.  
>Is that okay?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Mailu/Mailu/issues/863

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by sonamsamdupkhangsar** [comment]
yes, in the pvc.yaml (https://github.com/Mailu/Mailu/blob/782c686ea29b3c45528283bf5e383fe3cb7f3803/docs/kubernetes/mailu/pvc.yaml#L24) it uses ReadWriteMany.  I am on DigitalOcean managed Kubernetes service.  Their PVC support only ReadWriteOnce access mode only.

I ran all the yamls. Some pods stayed in pending state.

**Comment by muhlemmer** [comment]
Okay clear. I personally can't help you with that, sorry.

Kubernetes is a kind of "experimental" way of running Mailu. There is only a small user base for this, and the documentation is updated by those users. So if you found something that didn't work, best is to find a fix and send a PR.

**Comment by sonamsamdupkhangsar** [comment]
ok thanks.

**Comment by d0ku** [comment]
On GKE you can use [NFS server]( https://medium.com/platformer-blog/nfs-persistent-volumes-with-kubernetes-a-case-study-ce1ed6e2c266) to enable ReadWriteMany PVs. I believe something similar should be possible on DigitalOcean.
