### ISSUE TITLE
Renaming the project

### ISSUE THREAD

**Issue by kaiyou** [Mailu/Mailu#87]
Following a discussion in #63, the project was renamed from Freeposte.io to Mailu.

Still, there is some work to do:

- rename the project inside the repository
- use the new Docker Hub organization
- update the Website with the new name
- redirect the old Website

**Comment by curry684** [comment]
As https://github.com/MAILU is actually a completely inactive user you can request Github support to release the username to you as 'Mailu', consistent with casing et al for the main project.

**Comment by kaiyou** [comment]
Thank you for the tip. I will do it today, before this repository gains any more traction.

**Comment by curry684** [comment]
Refer to https://help.github.com/articles/name-squatting-policy/  :)

**Comment by kaiyou** [comment]
Yep, I just posted a support request. Thank you!

**Comment by kaiyou** [comment]
The organization was just renamed. I will push the website as a separate repo instead of a branch.

**Comment by aminb** [comment]
Congrats for the new name!

I guess I'm a bit late to the party, but I was going to suggest **Forte** (or ForteMail), which would be a mash up of Free, Poste, and Fortress. And for icon we could use these as a source of inspiration:

- http://www.shutterstock.com/pic-458851798/stock-vector-castle-mail-logo-template-design-vector-message-icon.html
- http://www.shutterstock.com/pic-460073593/stock-vector-castle-mail-logo-template-design-vector-message-icon.html
- http://www.shutterstock.com/pic-460073605/stock-vector-castle-mail-logo-template-design-vector-message-icon.html

**Comment by kaiyou** [comment]
A bit late indeed, but thanks ! Still, I do not like Forte just as much as Mailu.

**Comment by kaiyou** [comment]
The old website now redirects.
