### ISSUE TITLE
fetchmail not working (solved)

### ISSUE THREAD

**Issue by oschreibke** [Mailu/Mailu#88]
Apologies for the formatting - Github's editor seems to do what it wants, not what I want it to.

I was having a problem logging in to my provider's server with a test account with both the 'Stable' and 'Latest' versions. Retrieving mails from the account works with my current but aging setup. 

Response to telnet mail@mysite.ch from the provider's mail system:
> 220 smtp-in-165.livemail.co.uk ESMTP Postfix

I solved the problem by modifying the Poll command in fetchmail.py from

```
    RC_LINE = """

    poll "{host}" proto {protocol} port {port}

        user "{username}" password "{password}"

        smtphost "smtp"

        smtpname "{user_email}"

        {options}

 """
```

to

```
    RC_LINE = """

    poll "{host}" proto {protocol}  port {port}

        user "{username}" password "{password}"

        is "{user_email}"

        smtphost "smtp"

        {options}

        sslproto 'AUTO'

    """
```

Seems connecting to my provider needs the sslproto clause.

Another issue was the logging. Messages with 'No mail...' were being logged as errors.
I changed fetchmail.py
from
```
        try:

            print(fetchmail(fetchmailrc))

            error_message = ""

        except subprocess.CalledProcessError as error:

            error_message = error.output.decode("utf8")

            print(error.output)
```

to

```
        try:

            print(fetchmail(fetchmailrc))

            error_message = ""

        except subprocess.CalledProcessError as error:

            error_message = error.output.decode("utf8")

            # No mail is not an error

            if not (error_message.startswith("fetchmail: No mail")): 

                print(fetchmailrc)

                print(error_message)

```

Finally, I received the following message in the log:
> fetchmail: WARNING: Running as root is discouraged.

This is resolved by adding

>  USER fetchmail

to the Dockerfile

My now working set up is as follows:
Modified fetchmail container:
Dockerfile: (~/fetchmail.Dockerfile)

```
 FROM ab77d96fd9ba 

 MAINTAINER Otto Schreibke <otto@mysite.ch>

 COPY fetchmail.py /fetchmail.py

 USER fetchmail

 CMD ["/fetchmail.py"]
```

fetchmail.py: (~/fetchmail.fetchmail.py)

```
 #!/usr/bin/env python

 import sqlite3

 import time

 import os

 import tempfile

 import shlex

 import subprocess


 FETCHMAIL = """

 fetchmail -N \

     --sslcertck --sslcertpath /etc/ssl/certs \

     -f {}

 """

 RC_LINE = """

 poll "{host}" proto {protocol}  port {port}

     user "{username}" password "{password}"

     is "{user_email}"

     smtphost "smtp"

     {options}

     sslproto 'AUTO'

 """

 def escape_rc_string(arg):

     return arg.replace("\\", "\\\\").replace('"', '\\"')


 def fetchmail(fetchmailrc):

     with tempfile.NamedTemporaryFile() as handler:

         handler.write(fetchmailrc.encode("utf8"))

         handler.flush()

         command = FETCHMAIL.format(shlex.quote(handler.name))

         output = subprocess.check_output(command, shell=True)

         return output



 def run(connection, cursor):

     cursor.execute("""

         SELECT user_email, protocol, host, port, tls, username, password

         FROM fetch

     """)

     for line in cursor.fetchall():

         fetchmailrc = ""

         user_email, protocol, host, port, tls, username, password = line

         options = "options fetchall antispam 501, 504, 550, 553, 554"

         options += " ssl" if tls else ""

         fetchmailrc += RC_LINE.format(

             user_email=escape_rc_string(user_email),

             protocol=protocol,

             host=escape_rc_string(host),

             port=port,

             username=escape_rc_string(username),

             password=escape_rc_string(password),

             options=options

         )

         try:

             print(fetchmail(fetchmailrc))

             error_message = ""

         except subprocess.CalledProcessError as error:

             error_message = error.output.decode("utf8")

             # No mail is not an error

             if not (error_message.startswith("fetchmail: No mail")): 

                 print(fetchmailrc)

                 print(error_message)

         finally:

             cursor.execute("""

                 UPDATE fetch SET error=?, last_check=datetime('now')

                 WHERE user_email=?

             """, (error_message.split("\n")[0], user_email))

             connection.commit()



 if __name__ == "__main__":

     db_path = os.environ.get("DB_PATH", "/data/freeposte.db")

     connection = sqlite3.connect(db_path)

     while True:

         cursor = connection.cursor()

         run(connection, cursor)

         cursor.close()

         time.sleep(int(os.environ.get("FETCHMAIL_DELAY", 60)))

```

Build with
> sudo docker build -t osc/fetchmail:latest .

Modified docker-compose.yml
```
  fetchmail:

    # build: fetchmail

    #image: freeposte/fetchmail:$VERSION

    image: osc/fetchmail:$VERSION

    restart: always

    env_file: .env

    environment:

      - PYTHONUNBUFFERED=1

      - FETCHMAIL_DELAY=60

    volumes:

      - "$ROOT/freeposte:/data"

```

**Comment by kaiyou** [comment]
I took the liberty of editing your message, you can simply use triple backquotes for multiline monospace output. I will handle this tonight however. Thank you for reporting!

**Comment by oschreibke** [comment]
Thanks for cleaning up, the post looks much better now.

**Comment by kaiyou** [comment]
Thanks for your fix, which actually enables STARTTLS for fetchmail. I also appreciate the logging and user part.

Could you commit these and create a pull request? If not, I will try and commit tomorrow.

**Comment by oschreibke** [comment]
I put the change to fetchmail.py in a new branch 'fetchmail-osc' then tried to push my change back, but got the following errors.
```
git push --set-upstream origin fetchmail-osc
Username for 'https://github.com': oschreibke
Password for 'https://oschreibke@github.com': 
remote: Permission to mail-u/Mailu.git denied to oschreibke.
fatal: unable to access 'https://github.com/mail-u/Mailu.git/': The requested URL returned error: 403
```

BTW: I'm not totally happy with the test  ```if not (error_message.startswith("fetchmail: No mail")): ```. I suspect it will fail in another image.

**Comment by kaiyou** [comment]
You are probably trying to push to this repository, for which you do not have commit privileges. I recommend that you read Github documentation on the matter of forking and creating pull requests. If you feel ready for it, I will wait for your pull request instead of commiting your changes myself.

- About forking : https://help.github.com/articles/fork-a-repo/
- About pull requests : https://help.github.com/articles/about-pull-requests/
- Git documentation on branching workflow : https://git-scm.com/book/en/v2/Git-Branching-Branching-Workflows
- Linus Torvalds on Git at Google about the politics of it all among other topics : https://www.youtube.com/watch?v=4XpnKHJAok8

Regarding the test, it sure is ugly to test for a string I did not check the return code, but I believe it is identical in both cases.

**Comment by kaiyou** [comment]
I just merged your PR. Thank you!
