### ISSUE TITLE
mysql 8 connection issue with password and caching_sha2_password. Please add to docs.

### ISSUE THREAD

**Issue by cr1st1p** [Mailu/Mailu#881]
I had the problem mentioned in https://mailu.io/master/database.html#external-mysql-mariadb
regarding 'caching_sha2_password' but unfortunately the suggested fix did not work.

What *did* work, was to change the way the user is created, adding "WITH mysql_native_password" like:
CREATE USER IF NOT EXISTS 'mailu'@'%' IDENTIFIED WITH mysql_native_password BY 'somepassword'

It would be good to update the doc?
Thank you!
-- Cristi

**Comment by muhlemmer** [comment]
If a SQL update failed on a user, that has most probably to do with permissions or MySQL bug, not necessarily an error of the documentation. The syntax provided worked fine on our side.
