### ISSUE TITLE
HOST_* Variables not working

### ISSUE THREAD

**Issue by Greek64** [Mailu/Mailu#884]
Changing the `HOST_*` variables described in the [docs](https://mailu.io/1.6/configuration.html#infrastructure-settings) is not working as expected.

I did not test all of them individually (to see which specific `HOST_*` will produce errors), but I know for a fact that `HOST_REDIS` does not.
I changed `HOST_REDIS=mailu_redis` and got following error(s):
```
mailu_admin| [2019-01-25 14:15:37,610] ERROR in app: Exception on /internal/auth/email [GET]
mailu_admin| Traceback (most recent call last):
mailu_admin|   File "/usr/lib/python3.6/site-packages/redis/connection.py", line 493, in connect
mailu_admin|     sock = self._connect()
mailu_admin|   File "/usr/lib/python3.6/site-packages/redis/connection.py", line 520, in _connect
mailu_admin|     socket.SOCK_STREAM):
mailu_admin|   File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
mailu_admin|     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
mailu_admin| socket.gaierror: [Errno -2] Name does not resolve

mailu_admin| During handling of the above exception, another exception occurred:
mailu_admin| Traceback (most recent call last):
mailu_admin|   File "/usr/lib/python3.6/site-packages/redis/client.py", line 754, in execute_command
mailu_admin|     connection.send_command(*args)
mailu_admin|   File "/usr/lib/python3.6/site-packages/redis/connection.py", line 619, in send_command
mailu_admin|     self.send_packed_command(self.pack_command(*args))
mailu_admin|   File "/usr/lib/python3.6/site-packages/redis/connection.py", line 594, in send_packed_command
mailu_admin|     self.connect()
mailu_admin|   File "/usr/lib/python3.6/site-packages/redis/connection.py", line 498, in connect
mailu_admin|     raise ConnectionError(self._error_message(e))
mailu_admin| redis.exceptions.ConnectionError: Error -2 connecting to redis:6379. Name does not resolve.
```

This error is somehow expected, since the `core/admin/mailu/configuration.py` alone hardcodes the `RATELIMIT_STORAGE_URL` and `QUOTA_STORAGE_URL` to `redis` ignoring the `HOST_REDIS` variable.

DOCUMENTATION UPDATE
-----------------------------
Also the [Infrastructure settings](https://mailu.io/1.6/configuration.html#infrastructure-settings) section in the docs needs updating.
A quick *grep* shows that `HOST_HOSTIMAP` does not exist in the source code at all.
The **default** parenthesis should also be updated to show only ports on the variables that needs them (i.e. `HOST_LMTP` and `HOST_WEBDAV`), else a user (e.g me) might think he also needs to explicitly set it like `HOST_IMAP=mailu_imap:143`.

RENAME DOCKER-COMPOSE SERVICE NAMES?
-------------------------------------------------
Lastly more of an semi-related question:
Why does `mailu` use service names like `front`, `database`, `admin`, `front`, etc?
Since I reckon most users will integrate the mailu YML configuration into their existing docker-compose.yml file, this name convention guarantees name conflicts. In my case I had to rename my existing services (since mailu does not (yet) support renaming its services).
Whouldn't it make sense to name the services per default with a `mailu_`-prefix to avoid service name collisions?

**Comment by muhlemmer** [comment]
Thanks for the report. We'll check it out.

As for service names, you can separate projects in multiple docker-compose.yml files. Prefixing is already managed by docker-compose. If you check `docker ps`, you'll find something like `mailu_front_1` for container names. If you need network connectivity between the projects, you can use docker external networks.

**Comment by dustindauncey** [comment]
Same issue here.

**Comment by dustindauncey** [comment]
Same issue on master build too. Originally tried 1.6.

**Comment by Greek64** [comment]
@dustindauncey 
Well, the PR #940 is not yet merged anywhere, so I wouldn't expect it to work yet.
