### ISSUE TITLE
Admin UI gives me 404?

### ISSUE THREAD

**Issue by hanoii** [Mailu/Mailu#885]
I just installed this through docker-composer on a newly created Droplet on DigitalOcean.

I can't seem to access the admin. I didn't expose it, but instead wanted to access it to http://localhost:8080 through an SSH tunnel, but It just gives me 404.

If I access it within the server through an ssh tunnel it also gives me 404.

I am not about to try exposing it, but LE is failing because DNS has not propagated yet, but I don't really want to have it exposed, just accessible through ssh.

Everything looks more or less fine.

Any pointers?

**Comment by hanoii** [comment]
This from https://setup.mailu.io

confused me:


<img width="1180" alt="screen shot 2019-01-25 at 14 31 54" src="https://user-images.githubusercontent.com/677879/51762263-01e9ab00-20ae-11e9-9fec-d0c45b65ba0e.png">

I just saw on the log something and try `/ui/login` and now at least loads

**Comment by upMKuhn** [comment]
could it be related to what I see logged in the admin container?
OR is the problem that I use a host mounted volume instead of a Azure Disk or something like that :thinking:  

>   File "/usr/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
>     cursor.execute(statement, parameters)
> sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked [SQL: '\nCREATE TABLE _alembic_tmp_alias (\n\tcreated_at DATE NOT NULL, \n\tupdated_at DATE, \n\tcomment VARCHAR(255), \n\tlocalpart VARCHAR(80) NOT NULL, \n\tdestination VARCHAR(1023) NOT NULL, \n\tdomain_name VARCHAR(80) NOT NULL, \n\temail VARCHAR(255) NOT NULL, \n\twildcard BOOLEAN DEFAULT 0 NOT NULL, \n\tCHECK (wildcard IN (0, 1))\n)\n\n'] (Background on this error at: http://sqlalche.me/e/e3q8)
> [2019-01-28 23:10:02 +0000] [12] [INFO] Starting gunicorn 19.9.0
> [2019-01-28 23:10:02 +0000] [12] [INFO] Listening at: http://0.0.0.0:80 (12)
> [2019-01-28 23:10:02 +0000] [12] [INFO] Using worker: sync
