### ISSUE TITLE
antispam url on admin UI not working

### ISSUE THREAD

**Issue by hanoii** [Mailu/Mailu#887]
I have not exposed the admin UI and I am accessing through an SSH tunnel. Everything works under `/ui` but the link to AntiSpam goes to `/antispam` which gives 404. I tried `/ui/antispam` and also fails.

Related to #885

**Comment by kaiyou** [comment]
This is not a bug, since accessing directly the web ui will indeed generate absolute URLs that are meant for the front container. Closing here.
