### ISSUE TITLE
kubernetes: antispam not working; possible fix suggested

### ISSUE THREAD

**Issue by cr1st1p** [Mailu/Mailu#893]
Running inside kubernetes. From admin, if I go to the Antispam url (/admin/antispam) I get a http 500 error.
After digging through it, having the following setup in the ingress definition for security ingress helps:
```
  annotations:
    ingress.kubernetes.io/rewrite-target: "/"
    ingress.kubernetes.io/auth-url: http://admin.mailu-mailserver.svc.cluster.local/internal/auth/admin
    ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header Password "mailu";

  labels:

```
The rewrite-target and the auth-url are solving the http 500 problem. Nginx did not like at all the initial 'auth-request /internal/auth/admin;' part.

The last part with the Password header is to make rspamd not prompt me for a login password since I'm already checked for authorization against admin code. And I do not want to type the 'mailu' password.
Although I do not like too much that fix - a better one would be combined with some changes to the rspamd setup (worker-controller.inc)

Hope that helps.
-- Cristi

**Comment by micw** [comment]
@cr1st1p @hacor Can this be closed?

**Comment by kaiyou** [comment]
I am closing as stale, since this should work with the latest config and the suggested fix raises the issue of exposing a service outside the front pod.
