### ISSUE TITLE
Maximum number of connections from user+IP exceeded (mail_max_userip_connections=10):

### ISSUE THREAD

**Issue by AdvancedStyle** [Mailu/Mailu#894]
Can't figure out how to increase the dovecot mail_max_userip_connections.
I have .env set with:

`AUTH_RATELIMIT=100/minute;5000/hour`

But still get this error below (so clearly it's still set to 10 instead of 100):

`Maximum number of connections from user+IP exceeded (mail_max_userip_connections=10):`

**Comment by Nebukadneza** [comment]
Hi,

there is a dovecot override config in `overrides/dovecot.conf` which is included from the original config inside the container. IMO you should be able to adjust that value there.

Please briefly report back if this already helps you …

Best,
-Dario

**Comment by AdvancedStyle** [comment]
`overrides` directory is empty except for an empty `rspamd` subdirectory.

**Comment by Nebukadneza** [comment]
Sorry, i was somehow under the impression that you knew you wanted to increase `mail_max_userip_connections`. 

I’m not 100% sure as i haven’t tried myself yet, but I think
```
protocol imap {
   mail_max_userip_connections = 100
}
```

Should do the trick for you (assuming you’re seeing this problem with IMAP, not POP).

**Comment by muhlemmer** [comment]
It is unnecessary to use overrides for this. Just modify `.env` or `mailu.env` (depending on mailu version).

After any modification to the `env` file, you need to
```
docker-compose down
docker-compose up -d
```
Only during an `up`, `env` files are parsed by docker-compose. Not with `restart`.

https://mailu.io/1.6/faq.html#changes-in-env-don-t-propagate

**Comment by Aaron-Ritter** [comment]
.env wont fix the IP connection limit, check following for solution: https://github.com/Mailu/Mailu/issues/1364
