### ISSUE TITLE
antispam question

### ISSUE THREAD

**Issue by hanoii** [Mailu/Mailu#897]
I am confused on something related to the rspamd 

From https://github.com/Mailu/Mailu/pull/859#issuecomment-456293075 I learned that it's not optional, but then, on each user edit account you have an option to disable it:

<img width="412" alt="screen shot 2019-01-28 at 12 03 34" src="https://user-images.githubusercontent.com/677879/51844741-c1c83980-22f4-11e9-9cd5-2e52031204b7.png">

However, on rspamd history which I could access from #887 I still see actions taken on mails on the accounts I disabled antispam, how does that work?

**Comment by muhlemmer** [comment]
All mails go through antispam, which sets some headers to the mail. It is up to Dovecot to decide what to do with the actual mail. So the setting is checked in the `default.sieve` script template (served by admin):
https://github.com/Mailu/Mailu/blob/211136f9b16895e485cb1b8605c7d0eadd80d049/core/admin/mailu/internal/templates/default.sieve#L21-L23

**Comment by Nebukadneza** [comment]
Mh … something just came to my mind while reading that — does that mean that antispam hard-drops, where rspamd doesn’t even hand the mail further to dovecot, still affect users with `spam_enabled = False`?

**Comment by hanoii** [comment]
@Nebukadneza yes, exactly. There are hard drops -  I noticed specially while doing a few telnet smtp tests.

**Comment by kaiyou** [comment]
Indeed, we should make more clear that disabling the antispam will actually stop mails from being moved to the spam directory. It does not disable the dirst-trashing part of rspamd, which simply drops the mail before it can even reach Dovecot.
