### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by hanoii** [Mailu/Mailu#898]
I also wanted to thank you/congratulate you for this.

I've managed several custom servers for side projects in the last 10+ years and mail was always an annoying part of the setup. I did different things as paying for some of the remote managed mail services were out of the question for those emails.

Last time I setup just some useful forwarding with authenticated smtp so I can still use that email address from gmail, but it was I found it difficult to keep gmail happy with these forwards.

I installed yours and although I took a tiny bit of figuring out, it just worked. Now I can keep this running on a $5/m instance on DO and leave it there.

So Thanks again! I hope you keep maintaining this!

**Comment by muhlemmer** [comment]
You are very welcome! Maintenance is a community effort. We've set up automation around pull requests so that a group of people can approve and merge, so there is no single person we depend on. The contributro base also seems to grow slowly. So were kinda solid here.
