### ISSUE TITLE
Consider moving the admin interface to its own repo

### ISSUE THREAD

**Issue by extremeshok** [Mailu/Mailu#90]
This would allow us to fork the admin interface without having to pull the entire repo.

**Comment by kaiyou** [comment]
As discussed in #63, there are pros and cons to splitting repositories. One major con is that issues are split into multiple repositories while most of the time related to multiple images/subprojects. Also, the admin interface is tightly bound to the other images and I see no definitive advantage to using a separate repository.

As mentionned by @curry684 in that same thread however, we plan on having read-only repositories of all the images for people that plan on forking to separate projects, but not as part of our development workflow.
