### ISSUE TITLE
Cannot configure PGP in Roundcube.

### ISSUE THREAD

**Issue by cooperaj** [Mailu/Mailu#901]
Trying to access the "PGP Keys" menu option in Mailu 1.6's Roundcube gives the error:

```
Application Error (600): Enigma plugin: GPG binary not found. If you are sure the GPG binary is installed, please specify the location of the GPG binary using the 'binary' driver option.
```

To be honest, I'm assuming this means it's not working. I've not attempted to progress further though I am able to click the "+" button after dismissing the dialog. 

As an aside, how do I import a preexisting PGP key?

**Comment by muhlemmer** [comment]
An enhancement request is already open for that: #506. Closing this as duplicate.
