### ISSUE TITLE
ClamAv is failing and making mail slow

### ISSUE THREAD

**Issue by mvaled** [Mailu/Mailu#908]
I have configured a server not to use clamav (I use antivirus) at another MTA.  However, I still see lots of logs with `CLAMAV_FAIL(0.00){retransmits exceed}`.   These logs show that mails can be delayed up to 45s in this server.

I tried to run clamav to see if I could lower the delay.  But the same log appears, as if the `antivirus.lua` could not talk with clamav.

I created PR #907 to address the first issue, but the second seems to be another pain point.

**Comment by muhlemmer** [comment]
I'm afraid I don't fully understand the problem in the second point:

> I tried to run clamav to see if I could lower the delay. But the same log appears, as if the antivirus.lua could not talk with clamav.

**Comment by mvaled** [comment]
The problem is that I deploy in k8s. In that case the name of the clamav service is not antivirus. The PR solved the first issue (we shouldn't try to reach the antivirus if none is configured). The second is related to k8s configuration.El 12 feb. 2019 11:23 AM, Tim Möhlmann <notifications@github.com> escribió:I'm afraid I don't fully understand the problem in the second point:

I tried to run clamav to see if I could lower the delay. But the same log appears, as if the antivirus.lua could not talk with clamav.

**Comment by Nebukadneza** [comment]
Hi There,

The `Mailu`-Project is currently in a bit of a bind! We are short on man-power, and we need to judge if it is possible for us to put in some work on this issue.

To help with that, we are currently trying to find out which issues are actively keeping users from using `Mailu`, which issues have someone who want to work on them — and which issues may be less important. These a less important ones could be discarded for the time being, until the project is in a more stable and regular state once again.

In order for us to better assess this, it would be helpful if you could put a **reaction on this post** (use the :smiley: icon to the top-right).
- 👍️ if you **need this** to be able to use Mailu. Ideally, you’d also be able to test this on your installation, and provide feedback …
- 🎉 if you find it a **nice bonus**, but no deal-breaker
- 🚀 if you want to **work on it yourself**!
We want to keep this **voting open for 2 weeks** from now, so please help out!

**Comment by mvaled** [comment]
@Nebukadneza 

After #907 was accepted I haven't tried to use ClamAV again in this server.  I don't have much time to test again.

**Comment by Diman0** [comment]
Ok. that is fair. I'll close this issue.
