### ISSUE TITLE
Migrate Docker images to Mailu

### ISSUE THREAD

**Issue by kaiyou** [Mailu/Mailu#91]
For release 1.3, I would like to move Docker images to `mailu/`. Also, a few steps are required:
- setup automated builds for `mailu/`
- push a specific version of the admin interface to `freeposte/admin` that will ask users to refresh their `docker-compose.yml` (banner ?)
- retire the `freeposte/` namespace in a couple months

**Comment by curry684** [comment]
Did you already pick up the organization on Docker hub?

**Comment by kaiyou** [comment]
I did ! https://hub.docker.com/r/mailu/

**Comment by curry684** [comment]
Good job  👍    My username on Docker Hub is the same 😆

**Comment by kaiyou** [comment]
All automated builds are setup on Docker Hub

**Comment by curry684** [comment]
Good news: I've managed to create a successful subtree split. Bad news: it's a hell to properly script this to be zero maintenance. More work to be done hehe.

**Comment by kaiyou** [comment]
Nice! I think you have commit access to ```Mailu/Automation``, feel free to start pushing bits down there if you feel it's worth sharing.

**Comment by curry684** [comment]
I'm testing it on a work project I need similar functionality in. Once I have it stable I'll port the scripting to Mailu. We'll also be needing a splitting server though and some push hooks. I do have access to the Automation project, and I can also create new repositories in the organization, so that should be enough for now.

**Comment by kaiyou** [comment]
For the task server, does Travis CI fit our requirements?

**Comment by curry684** [comment]
Don't think it can push back to different repos, also storage would be an issue. Don't worry though, I have more than enough servers, we can look at structural solutions later.

**Comment by kaiyou** [comment]
I do worry, I would prefer that all tasks are run on a publicly available platform. I can setup a Webhook on this repository, where would you like it to point?

**Comment by curry684** [comment]
The tasks can't run entirely public as they need a machine user SSH key to push to the repositories. With the no worry part I meant I have enough servers for initial development, we'll look into the structural solution and hosting of it  :)

As for the webhook I'll get back on that when the scripts are working properly. As you can see the splits are working in the lowest branch, they get messed up right now with higher branches and tags hehe. Getting there...

**Comment by kaiyou** [comment]
Thanks for the nice work, yes, it's starting to look good. We will get to the structural part later then.

**Comment by kaiyou** [comment]
I just pushed an image to the Freeposte, tagged ``latest``, ``1.2`` and ``stable``, that will display a top banner telling people to migrate to Mailu.

Closing this issue, we will create a separate one regarding the automation process.
