### ISSUE TITLE
wishlist: command to list users and aliases

### ISSUE THREAD

**Issue by tgpfeiffer** [Mailu/Mailu#912]
It would be great to have a command `mailu users` (likewise, `mailu aliases`) or so to show users (and aliases, respectively) that have already been created. That would allow for some simple scripting or congfiguration management tools to only create these users that do not yet exist. It would also be great to have an option like `--format=text|json|yaml` for easier processing.

**Comment by Nebukadneza** [comment]
Hi There,

The `Mailu`-Project is currently in a bit of a bind! We are short on man-power, and we need to judge if it is possible for us to put in some work on this issue.

To help with that, we are currently trying to find out which issues are actively keeping users from using `Mailu`, which issues have someone who want to work on them — and which issues may be less important. These a less important ones could be discarded for the time being, until the project is in a more stable and regular state once again.

In order for us to better assess this, it would be helpful if you could put a **reaction on this post** (use the :smiley: icon to the top-right).
- 👍️ if you **need this** to be able to use Mailu. Ideally, you’d also be able to test this on your installation, and provide feedback …
- 🎉 if you find it a **nice bonus**, but no deal-breaker
- 🚀 if you want to **work on it yourself**!
We want to keep this **voting open for 2 weeks** from now, so please help out!

**Comment by Diman0** [comment]
This will be possible once PR #1604 has been reviewed and merged.
It will allow you to create a dump file in yaml format with all information from the mailu database. This includes all users.
This CLI command will also allow you to add new users which must be provided in a yaml file.

**Comment by ghostwheel42** [comment]
You can do this since release 1.9 using the `config-export` action like this:
```
flask mailu config-export user.email
flask mailu config-export alias.email
flask mailu config-export user
flask mailu config-export --json alias
```
You can find more options in the [manual](https://mailu.io/1.9/cli.html#config-export)
