### ISSUE TITLE
Improved Spam Handling w/ Fetchmail

### ISSUE THREAD

**Issue by benyanke** [Mailu/Mailu#913]
Currently, fetchmail does exactly what I need to cover 80% of what I do. Most of my mail comes into existing accounts, and mailu allows me to use my mailu address alongside all my existing mail.

However, when spam gets caught in my gmail spam filters, it never gets caught by me for quite a while, because I never log into gmail.

I'd like to propose an option for fetchmail to fetch a specified spam folder, which then would place the mail in mailu's spam folder. Perhaps this could even be implemented more generically as multifolder source-destination fetching.

**Comment by muhlemmer** [comment]
> Perhaps this could even be implemented more generically as multifolder source-destination fetching.

This is already mentioned in #711. I've proposed an enhancement of setting multiple folders for fetchmail there. So I'll close this as a duplicate. Feel free to re-open if you don't agree.

**Comment by benyanke** [comment]
This would absolutely be handled by #711. Thanks!
