### ISSUE TITLE
Security/antispam test results comparison

### ISSUE THREAD

**Issue by hacor** [Mailu/Mailu#915]
Hello,

I wanted to ask if any enthousiast could take the following test as well against their Mailu mailservers:
`https://www.emailsecuritycheck.net/index.html`
It just tries to sent you rubbish and hopefully the antispam server will block (most of) it.

In my case 5 out of the 7 mails reached my inbox (only mails `2/7` and `3/7` were deleted by the antispam filter) I would love to make some comparisons here with your results. Maybe we can use this results in order to finetune configurations? 

I'm currently using Mailu on top of Kubernetes

I'm curious!
Best regards,

Hacor

**Comment by firvida** [comment]
Hey!! I have run the test in my production Kubernetes, I have received only mail 4,6 and 7.

**Comment by muhlemmer** [comment]
## 1K mails
Rspamd is in "learning" mode untill 1.000 mails are processed. Until everything just goes through. If you've past 1K mails then keep reading.

## Spam header
Can you check if there is a spam header set?

I had a problem in the past with one of my users, where a lot of spam was getting through. In the end I added a server-side sieve script (filter option in webmail) to put everything in Junk.

An example header from that mailbox:
```
Delivered-To: <------------->
Return-Path: <dukanmfon@verizon.net>
Received: from mailu01.usrpro.com ([192.168.203.7])
	by mailu01.usrpro.com with LMTP
	id 4uyaKr/ZY1zlTwAAXlEaSA
	(envelope-from <dukanmfon@verizon.net>)
	for <------------>; Wed, 13 Feb 2019 08:47:59 +0000
Received: from rubberflooringinc.com (unknown [23.130.96.162])
	by ----------- (Postfix) with ESMTP id 8C2B45BE701
	for <------------>; Wed, 13 Feb 2019 08:47:58 +0000 (UTC)
To: ---------
Subject: Hand Zyklon Sauger
Message-ID: <dcbcc3d106b2643660ca37e5065c67bd@spectrumfloors.com>
Date: Wed, 13 Feb 2019 05:47:46 +0100
From: "Adele Frey" <dukamofon@verizon.net>
Reply-To: grepanse@aliyun.com
MIME-Version: 1.0
Content-Type: text/plain; format=flowed; charset="UTF-8"
Content-Transfer-Encoding: 8bit
X-Spamd-Bar: +++++++++++
X-Spam-Level: ***********
Authentication-Results: --------------;
	dmarc=fail reason="No valid SPF, No valid DKIM" header.from=verizon.net (policy=none);
	spf=neutral smtp.mailfrom=dukanmfon@verizon.net
X-Spam: Yes
```

I've created to filter on the `X-Spam: Yes` field to move everything to Junk. Currently the default:
https://github.com/Mailu/Mailu/blob/211136f9b16895e485cb1b8605c7d0eadd80d049/core/dovecot/conf/dovecot.conf#L144-L147

The spam-level of the spam messages is "only" 11 and does not get moved to the spam folder. I'm not sure if this settings should trigger the move to spam, but perhaps they are too light?

## Rspamd
In Rspamd the spam threshold is also set to 15. Anything that exceeds this score gets rejected. (hard-bounce). I can see on our production server that 4 exceeds this score and does get bounced. 34% is probable spam and gets delivered with the `X-Spam: Yes`, but not automatically Junked without custom sieve.

This gives to wonder, if level 15 gets rejected, there is nothing that will trigger the Dovecot rule at `sieve_spamtest_max_value = 15 `

I'll research more.... (suggestions are welcome)

**Comment by hacor** [comment]
@muhlemmer Thanks for this in dept review.
I must say that I probably didn't pass the 1000 mail barrier yet.
So I must sit out a little bit longer.

Thanks!

**Comment by muhlemmer** [comment]
Ok, I was is-understanding the config here. 15 is the max score a message can ever have. (Everything above 15 gets rejected by Rspamd). And the percentage slider in the admin sets the percentage of 15. Everything above the resulting value gets sent to the Junk folder. Default is 80%. So a score of 12.

- < 12 gets delivered to inbox
- 12 <> 15 delivered to Junk
- \> 15 Rejected.

@Nebukadneza pointed out on matrix that even with <1K mails the spam filter should still work. It's just training some learning vectors.

Have you inspected the headers of the mails that got through? Any spam levels?
