### ISSUE TITLE
Add Icelandic language. 

### ISSUE THREAD

**Issue by evil4u** [Mailu/Mailu#916]
Hi.

I would like to translate MailU to Icelandic, I have an account at poeditor but I have no clue how to create new lang file and translate.

Could some one assist me on this please.

**Comment by muhlemmer** [comment]
@Mailu/contributors, there are a couple of guys that did translations.Have you read https://mailu.io/1.6/contributors/localization.html?

**Comment by evil4u** [comment]
Yes I have and there's not Icelandic lang file a poeditor.com.

Could you add lang file for Icelandic.

Thanks

**Comment by muhlemmer** [comment]
The point is, Ive never worked with poeditor.com myself and have no idea how to do that.

**Comment by muhlemmer** [comment]
Perhaps @kaiyou?

**Comment by kaiyou** [comment]
I am switching over to Weblate today, Poeditor is a pain.

**Comment by kaiyou** [comment]
Here you go, I also added Icelandic: https://translate.tedomum.net/projects/mailu/admin/
