### ISSUE TITLE
When using images in Kubernetes the dashboard shell does not work.

### ISSUE THREAD

**Issue by firvida** [Mailu/Mailu#918]
**Expected behavior**: When click in the Exec button of the Pods view in the Kubernetes dashboard we expected to get a shell inside the pod.

**What is wrong**: For all Alpine based Mailu images this button does not work because Exec function expects **/bin/bash** to exists in the pod.

Posible fix: Install /bin/bash in Alpine based images.

**Comment by jonasdkhansen** [comment]
You can use sh instead of bash.
kubectl exec -it POD_NAME sh

**Comment by firvida** [comment]
Yes indeed. That's the solution I'm using right now. But in some cases I have access to the pods only from the Kubernetes' dashboard and I need the shell to work with them. Thanks
