### ISSUE TITLE
Internal Error with setup

### ISSUE THREAD

**Issue by Setsuneh** [Mailu/Mailu#924]
Hi,

Thanks for the work !

I want to try the new version with setup.mailu.io + Docker stack. However I have already this when I want to generate my compose:

> Internal Server Error
> The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

Is it normal?

**Comment by muhlemmer** [comment]
Stack is experimental-ish. I hope you've seen the warning on setup?

>Setup is capable of generating a somewhat decent docker-compose.yml, for the docker stack flavor. However its usage is for advanced users an is experimental. Expect many challenges is shared mail storage and fail-over scenarios! Some user experiences have been shared on GitHub.

You kinda have to fiddle with the config to make it work. Or be more specific to us on the error, (like log output).

**Comment by Pelado-Mat** [comment]
Hi, This is not only an issue with swarm. I got the same error generating a regular docker-compose.
![image](https://user-images.githubusercontent.com/16164175/53271141-462b9380-36cc-11e9-83f2-d47a81690294.png)
