### ISSUE TITLE
docs: config-update command requires -T option for docker-compose

### ISSUE THREAD

**Issue by tgpfeiffer** [Mailu/Mailu#926]
The example command for `config-update` on https://mailu.io/1.6/cli.html looks like

    cat mail-config.yml | docker-compose exec admin flask mailu config_update --delete_objects

but running this fails with

    the input device is not a TTY

Adding the `-T` flag to `docker-compose exec` fixes the issue. Documents should be updated accordingly.

**Comment by muhlemmer** [comment]
#877 merged, so this can be closed.
