### ISSUE TITLE
Mailu vs cPanel

### ISSUE THREAD

**Issue by evil4u** [Mailu/Mailu#930]
Hi you all.

It was really surprising that Mailu just works. After I have setup the server added the DNS records that MailU created for my domain and with in 30 sec I could send emails to Gmail, yahoo, outlook etc and all of my emails go to inbox.

For the MailU box I have new domain name that has never been used before to send emails and it simply works and the IP that I use for that box does not have that good Reputation to send emails but still MailU will deliver all emails to the inbox. 

Now I have another VPS server that has cPanel and I am in the biggest battles of my life, all emails goes to spam folder when I email to Gmail, Yahoo and Outlook, and the same I have new domain for that server and a dedicated IP.

Now at talosintelligence.com reputation center I did a IP lookup to see what was going on and what I saw is that both servers ( IP's ) dose not have good reputation in fact MailU IP does has the worst reputation for delivering emails but my cPanel IP is better.

MailU server IP 
EMAIL REPUTATION | Neutral
WEB REPUTATION | Poor
WEIGHTED REPUTATION | Poor

cPanel server IP
EMAIL REPUTATION | Neutral
WEB REPUTATION | Neutral
WEIGHTED REPUTATION | Neutral

None of my servers IP are blacklisted so that could not be the problem.

And I have not whitelisted any of my domains at Gmail, yahoo, Outlook so that's not the case why MailU can deliver the emails straight to the inbox.

So what I'm asking is could some one please explain to me why MailU delivers my emails to the inbox but cPanel delivers the emails to the spam.

What is MailU secret :)

This is making me nuts hehehe

Thank you for your time.

**Comment by muhlemmer** [comment]
There is no real secret. But what's important:
- Reverse DNS should be set withing the server `DOMAIN` (in `mailu.env`). So `DOMAIN=mail.com`, then the reverse DNS should be `mail.com` or a sub-domain like `host01.mail.com`.
- SPF should point to one of the host-names or IP's of the server
- Setting DKIM keys really helps.

In Mailu, these settings are proposed in the domain overview. But perhaps with C-Panel you'll have to figure this manually? Not sure if it supports DKIM signing of messages?

Note that if you've setup DKIM in the DNS and C-Panel is sending on behalf of the same domain as Mailu and not signing the messages, the mails should get rejected.

**Comment by evil4u** [comment]
Hi and thank you for the reply.

cPanel has this option at WHM Enable DKIM/SPF Globally I always click on this after installing cPanel. The only record I need to create is DMARC and I use this DNS DMARC record.

"v=DMARC1; p=reject; sp=reject; rua=mailto:c61c3ba379ea009@rep.dmarcanalyzer.com; ruf=mailto:c61c3ba379ea009@for.dmarcanalyzer.com; pct=100; fo=1"

This is what cPanel creates for SPF "v=spf1 +a +mx +ip4:MY.SERV.ER.IP ~all"

I will have to investigate this more to see if that's the case if cPanel is sending the emails as server.domain.com or domain.com

Thank you for this.

This will get me further in to what I am looking for.

**Comment by muhlemmer** [comment]
If cPanel is generating DKIM, you also need to set a DKIM public key on the DNS.

DNS record looks something like:

```
dkim._domainkey.email.com. IN 600 TXT "v=DKIM1; k=rsa; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDAy3DTLUDwiz/0idhgVR+E0hMQMFg+nzCN9Hs83x+DYfUN05OsFmn3PmM+EjCC+UEq/hYyNLl/eSx72CopV/AWRzg0P8Rgtz0S1m2taS4JyFAuX0u7QUZqGzDfeHi/2qL07NsT5b/4b+ijOoNMlBkG4fIVl7N5Hs4vO233432455QIDAQAB"
```

If not, cPanel will sign the mail but receivers will not be able to verify.

**Comment by evil4u** [comment]
Yes I have this as cPanel creates this at the beginning of the install.

What cPanel creates is default._domainkey.domain.com 14400 | IN | TXT    v=DKIM1; k=rsa; p=

**Comment by kaiyou** [comment]
I am closing this since it looks answered
