### ISSUE TITLE
everything looks fine ,  mail sent/received in log , but no messages in webmail/thunderbird

### ISSUE THREAD

**Issue by changchichung** [Mailu/Mailu#935]
I just run mailu from docker 10 mins ago
but I see no messages in webmail/thunderbird , but I can sent mail from webmail/thunderbird
and rspamd shows that mail indeed sent/recv by server , but mail had never been sent ..
![rspamd logs](http://i.imgur.com/4KeQO1X.png)

any suggestions ??

**Comment by hoellen** [comment]
1. Did you read the [FAQ](https://mailu.io/1.6/faq.html)? There are some hints why it could not work.
2. We need more information: docker-compose, env file and mot of all logs from your mailu instance.
