### ISSUE TITLE
postfix.cf is not read

### ISSUE THREAD

**Issue by flopes89** [Mailu/Mailu#941]
I want to replace my current mail server (hosted on shared webhosting) with a mailu instance on my own server. So far everything looks dandy (awesome work!), however for the time being I want to copy all mails from "mailu-server" to my "old mail-server" for some time until I'm confident to switch.

For this, I figured I'd add an `always_bcc` address to postfix that points to an email on my old server so I can be sure to catch all emails if something goes wrong (along with an `MX` record with lower priority).

I added the `always_bcc` to `~/mailu/mounted/overrides/postfix.cf` and recreated the container from scratch (deleted image and ran `docker-compose up -d smtp`).

I can see that the file is mounted correctly:

```
$ docker-compose exec smtp cat /overrides/postfix.cf
always_bcc=mail@old-server.example.com
```

However, checking `postconf` reveils the configuration is not read:

```
$ docker-compose exec smtp postconf | grep bcc
always_bcc =
recipient_bcc_maps =
sender_bcc_maps =
```

What am I missing / doing wrong  here?

**Comment by flopes89** [comment]
Just checked, executing

```
$ docker-compose exec smtp postconf -e 'always_bcc=mail@old-server.example.com'
```

in the running container works as expected:

```
$ docker-compose exec smtp postconf | grep bcc
always_bcc = mail@old-server.example.com
recipient_bcc_maps =
sender_bcc_maps =
```

I suspect it has something to do with the setup. However there are no errors in the startup logs. Not sure how to proceed here.

**Comment by flopes89** [comment]
Further investigation revealed the error to be in `/etc/postfix/main.cf`. This file ends like so:

```
$ docker-compose exec smtp cat /etc/postfix/main.cf | tail -n 10
###############

smtpd_milters = inet:antispam:11332
milter_protocol = 6
milter_mail_macros = i {mail_addr} {client_addr} {client_name} {auth_authen}
milter_default_action = tempfail

###############
# Extra Settings
###############
```

Notice that there is **no final blank line**. However as I see that `Mailu/core/postfix/conf/main.cf` does in fact contain empty lines in the end.

I suspect that the jinja conversion somehow removes these empty lines, but I'm not sure yet why...

**Comment by flopes89** [comment]
As expected, it's related to jinja, which strips newlines at the end of templates unless configured with 

> `keep_trailing_newline`
> Preserve the trailing newline when rendering templates. The default is False, which causes a single newline, if present, to be stripped from the end of the template.

So I see two possible solutions: either add a second newline to `conf/main.cf` or set the `keep_trailing_newline` option.

**Comment by kaiyou** [comment]
This is fixed, thank you!
