### ISSUE TITLE
gen DKIM Internal Server Error

### ISSUE THREAD

**Issue by it-toppp** [Mailu/Mailu#943]
When generaters key dkim - error Internal Server Error in https://test.mailu.io - too

**Comment by it-toppp** [comment]
in rus lang-pak admin panel. In eu - all ok)

**Comment by fote** [comment]
How to change lang-pack?

**Comment by Evald24** [comment]
> in rus lang-pak admin panel. In eu - all ok)

Does anyone know the answer?

**Comment by ashat1701** [comment]
You need to change language of your browser to eng. Then it'll work.

**Comment by kaiyou** [comment]
Just had as look at the code, this is a 1-char fix. I'll try and edit from mobile.

**Comment by kaiyou** [comment]
Pending build, this should now be fixed on master. Could anyone confirm?
