### ISSUE TITLE
Suggested override to enable TLSv1 doesn't work

### ISSUE THREAD

**Issue by amarburg** [Mailu/Mailu#944]
Existing issues https://github.com/Mailu/Mailu/issues/698 and https://github.com/Mailu/Mailu/issues/363 are in reference to IMAP mail clients (e.g. Mac OS X Mail from El Capitan and earlier) which don't support TLSv1.2.   The suggestion is to reconfigure the nginx frontend to allow TLSv1 on the TLS-enabled IMAP ports via a file in `overrides/nginx/` as discussed here in the FAQ [here](https://github.com/Mailu/Mailu/blob/1.6/docs/faq.rst#is-there-a-way-to-support-more-older-ciphers).

The suggested approach does not work, on a couple of counts.  First, the `/overrides/*.conf` files are included in the nginx.conf within the `http { }` block [here](https://github.com/Mailu/Mailu/blob/1.6/core/nginx/conf/nginx.conf#L89), not within the `mail { }` block.

Second, Nginx produces "directive is duplicate" errors if the `ssl_protocols` or `ssl_ciphers` directives are given twice (once in tls.conf and once in the override).  The former is a warning, though it breaks TLS.  The latter is fatal.

The only correct way to change TLS parameters is to change the params in the **template** file [tls.conf](https://github.com/Mailu/Mailu/blob/1.6/core/nginx/conf/tls.conf) and mount this to `/conf/tls.conf` within the nginx image.     You have to rewrite the template because `/etc/nginx/tls.conf` is auto-generated to fill in the paths to the certificates.

**Comment by daveb92** [comment]
I am also having this issue
