### ISSUE TITLE
Autotest for Rainloop admin console

### ISSUE THREAD

**Issue by muhlemmer** [Mailu/Mailu#948]
In relation to #947, we should create a small script in the test suite which checks if the Rainloop admin interface is indeed disabled by default. Just to be safe for any future changes in config parsing of Rainloop.

A simple implementation would be testing the HTTP return code, however Rainloop still returns 200, OK even when the page is prompting "Access Denied". See RainLoop/rainloop-webmail#1838. If that gets not solved, we might resort to parsing the result page. THat would be more error prone if they ever choose to change the layout of the error page.

**Comment by Nebukadneza** [comment]
Hi There,

The `Mailu`-Project is currently in a bit of a bind! We are short on man-power, and we need to judge if it is possible for us to put in some work on this issue.

To help with that, we are currently trying to find out which issues are actively keeping users from using `Mailu`, which issues have someone who want to work on them — and which issues may be less important. These a less important ones could be discarded for the time being, until the project is in a more stable and regular state once again.

In order for us to better assess this, it would be helpful if you could put a **reaction on this post** (use the :smiley: icon to the top-right).
- 👍️ if you **need this** to be able to use Mailu. Ideally, you’d also be able to test this on your installation, and provide feedback …
- 🎉 if you find it a **nice bonus**, but no deal-breaker
- 🚀 if you want to **work on it yourself**!
We want to keep this **voting open for 2 weeks** from now, so please help out!

**Comment by lub** [comment]
I've opened a rainloop PR for this:
https://github.com/RainLoop/rainloop-webmail/pull/2029
