### ISSUE TITLE
Adding netdata in docker-compose stack ?

### ISSUE THREAD

**Issue by sanjiyan** [Mailu/Mailu#952]
Hi,

I normally run netdata on my cloud VMs, and attempted to install it on my docker VM running Mailu, but have come across issues with it failing.

So, looking around I can see it was requested/questioned a few months back: https://github.com/Mailu/Mailu/issues/567

Would it be possible to add this to the docker-compose stack ?

I am new to docker, but that has not stopped me trying to add it myself, but after nuking my mailu install several times over the past 24 hours, I thought to ask here :)

Thanks

**Comment by kaiyou** [comment]
Netdata is cool but is really meant to run on the host. More specifically there is no simple setup that will work in a container across all runtimes.
