### ISSUE TITLE
IMAP Server side mail rules?

### ISSUE THREAD

**Issue by sanjiyan** [Mailu/Mailu#953]
Hi,

I have migrated from hMailserver on Windows to Mailu within Docker, and so far loving it.

But one of the things I use a lot are IMAP server-side mail rules, I can not see where rules can be created within the admin panel, do they exist within this version of Mailu, if not are they on the roadmap?

Regards,

**Comment by kaiyou** [comment]
This is mostly handled in #497 and sieve support. I am closing as duplicate.
