### ISSUE TITLE
Websiter answers with 404 page not found

### ISSUE THREAD

**Issue by tuxBurner** [Mailu/Mailu#954]
When openening https://mailu.io/ I get a 404 page not found page.

**Comment by ahwebd** [comment]
same goes for the setup utility https://setup.mailu.io/  ----> 404

**Comment by hoellen** [comment]
Everything should be working again. Sorry for the inconvenience.

**Comment by ahwebd** [comment]
Worked for a little while, and now back again 404

**Comment by tuxBurner** [comment]
@hoellen still broken

**Comment by hoellen** [comment]
@muhlemmer is currently working on it. Thanks for your patience.

**Comment by hoellen** [comment]
Everything should be all right now (again). If it doesn't work, you'll probably have to wait for the DNS to update the IP address.
