### ISSUE TITLE
Allow selection of key length for DKIM Key generation

### ISSUE THREAD

**Issue by TLFTobiNary** [Mailu/Mailu#959]
Only 1024 bit keys can be generated for DKIM while 2048 would be preferable for RSA (since 1024 are known to be breakable in a reasonable amount of time).

While there might be performance considerations for using 1024 bit keys, this shouldn't be the default.

Ideally, one could select whether 1024 bit oder 2048 bit keys should be (re)generated.

**Comment by kaiyou** [comment]
That could be cool indeed. We need to take care of properly providing dns entries as well then, since they won't fit in a single record.

**Comment by evil4u** [comment]
+1 for this

**Comment by evil4u** [comment]
With 1024-bit I can't send emails to Office 360, Outlook and Hotmail, but I'm able to send to gMail.

**Comment by kaiyou** [comment]
This is solved by #1319
