### ISSUE TITLE
Fetched accounts not working

### ISSUE THREAD

**Issue by n3m3s1s** [Mailu/Mailu#961]
Hi everyone,
I setup accounts to be fetched but it never happens.
The list in /ui/fetch/list/accountname shows the details perfectly except "last check" and "status" keep empty (or "-" in fact).
Is there any special thing to do to enable fetching or actually perform a fetch?
Thanks

**Comment by kaiyou** [comment]
What version of Mailu are you running?

Could you check that the fetchmail container is running?

Could you export some logs from that container?
