### ISSUE TITLE
Zombie process [postgres] <defunct>

### ISSUE THREAD

**Issue by GitHubGeek** [Mailu/Mailu#969]
My Mailu instance tends to have zombie process after it's been running for a couple of days:

```
$ ps aux | grep 'Z'
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
70        3058  0.0  0.0      0     0 ?        Z    Mar10   0:00 [postgres] <defunct>
$ pstree -p -s 3058
systemd(1)───containerd(1023)───containerd-shim(2552)───start.py(2575)───postgres(3058)
```

The Mailu postgres image version is `d2893241a656`, Up 33 hours (healthy); Running Ubuntu 18.04.

Thanks!

**Comment by kaiyou** [comment]
Do you have any errors in your dmesg, like memory outages? Otherwise could you provide logs from that container?
