### ISSUE TITLE
Mailu documentation IPv6 bindings and DNS/Letsencrypt explanation

### ISSUE THREAD

**Issue by Culsu** [Mailu/Mailu#971]
Hey there!
First of all thanks to everyone for the awesome "mailserver & whatever you need for mailing" bundle Mailu.
Setting it up was pretty easy.

Still I ran into 2 problems while setting up mailu:
1. IPv6 binding caused mailu_front to fail starting
Fixing that was not that big of a deal, I just had to remove the IPv6 bindings in the docker-compose.yml, after that it worked like a charm.
But it would have been nice if there was a way to disable IPv6 binding in the Mailu setup form (https://setup.mailu.io/1.6/).

2. Using Letsencrypt as TLS CA
After reading the documentation of mailu (https://mailu.io/1.6/dns.html), and setting DNS records (A/MX) properly, I was still unable to connect to the mailu admin / webmail interface. It seems like this was caused by the letsencrypt TLS certification failing due to not opened ports at the firewall & router in front of my webserver.
This caused me running into the rate-limits of letsencrypt, which is a little annoying - but not that big of a deal.
Would've been nice if it is mentioned in the docu or setup form that the connection to the webserver on 80/tcp and 443/tcp should be tested before.

I'm aware that these problems are caused by my lack of experiene - still I do think there is some room for improvement in the docs.

**Comment by Nebukadneza** [comment]
Hi There,

The `Mailu`-Project is currently in a bit of a bind! We are short on man-power, and we need to judge if it is possible for us to put in some work on this issue.

To help with that, we are currently trying to find out which issues are actively keeping users from using `Mailu`, which issues have someone who want to work on them — and which issues may be less important. These a less important ones could be discarded for the time being, until the project is in a more stable and regular state once again.

In order for us to better assess this, it would be helpful if you could put a **reaction on this post** (use the :smiley: icon to the top-right).
- 👍️ if you **need this** to be able to use Mailu. Ideally, you’d also be able to test this on your installation, and provide feedback …
- 🎉 if you find it a **nice bonus**, but no deal-breaker
- 🚀 if you want to **work on it yourself**!
We want to keep this **voting open for 2 weeks** from now, so please help out!

**Comment by Diman0** [comment]
Hi There,

we see this issue had only little attention 😟. As much as it pains us: In order to get the current issues a bit more manageable for us, we decided to close it. 👋👋

We hope that no one feels offended by doing so. Should the issue get really pressing in the future, please feel free to re-open it.

Thank you for your patience and understanding, 🙇
- Your Mailu Team
