### ISSUE TITLE
imap error

### ISSUE THREAD

**Issue by magiquej** [Mailu/Mailu#972]
Hi,

I installed mailu with docker-compose and I can't connect to imap.  
nginx is ok : ports 993, 143 are open and accessible from outside (no firewall error). 

`909bd1585a48        mailu/nginx:1.6         "/bin/sh -c /start.py"   About an hour ago   Up About an hour (healthy)        127.0.0.1:25->25/tcp, ::1:25->25/tcp, 127.0.0.1:110->110/tcp, ::1:110->110/tcp, 80/tcp, 127.0.0.1:143->143/tcp, ::1:143->143/tcp, 127.0.0.1:465->465/tcp, ::1:465->465/tcp, 127.0.0.1:587->587/tcp, ::1:587->587/tcp, 127.0.0.1:993->993/tcp, ::1:993->993/tcp, 443/tcp, 10025/tcp, 127.0.0.1:995->995/tcp, ::1:995->995/tcp, 10143/tcp`

Login and password are the same like in admin but I have a "connection refused" in client Outlook 2013.

I checked the front logs, nothing about theconnection : 
```
front_1          | 2019-03-15T12:39:32.838206536Z 127.0.0.1 - - [15/Mar/2019:12:39:32 +0000] "GET /health HTTP/1.1" 204 0 "-" "curl/7.61.1"
front_1          | 2019-03-15T12:39:32.848499869Z 2019/03/15 12:39:32 [info] 735#735: *105 client 127.0.0.1 closed keepalive connection
```

the imap logs : 

imap             | 2019-03-15T12:33:52.791340358Z Traceback (most recent call last):
imap             | 2019-03-15T12:33:52.791350265Z   File "/start.py", line 44, in <module>
imap             | 2019-03-15T12:33:52.791425297Z     os.environ["REDIS_ADDRESS"] = resolve(os.environ.get("REDIS_ADDRESS", "redis"))
imap             | 2019-03-15T12:33:52.791437617Z   File "/usr/lib/python3.6/site-packages/tenacity/__init__.py", line 292, in wrapped_f
imap             | 2019-03-15T12:33:52.791447985Z     return self.call(f, *args, **kw)
imap             | 2019-03-15T12:33:52.791458181Z   File "/usr/lib/python3.6/site-packages/tenacity/__init__.py", line 358, in call
imap             | 2019-03-15T12:33:52.791469085Z     do = self.iter(retry_state=retry_state)
imap             | 2019-03-15T12:33:52.791479230Z   File "/usr/lib/python3.6/site-packages/tenacity/__init__.py", line 332, in iter
imap             | 2019-03-15T12:33:52.791490785Z     six.raise_from(retry_exc, fut.exception())
imap             | 2019-03-15T12:33:52.791501061Z   File "<string>", line 3, in raise_from
imap             | 2019-03-15T12:33:52.791512205Z tenacity.RetryError: RetryError[<Future at 0x7fd501a160b8 state=finished raised gaierror>]
imap             | 2019-03-15T12:39:43.221478883Z Traceback (most recent call last):
imap             | 2019-03-15T12:39:43.221717030Z   File "/usr/lib/python3.6/site-packages/tenacity/__init__.py", line 361, in call
imap             | 2019-03-15T12:39:43.221729520Z     result = fn(*args, **kwargs)
imap             | 2019-03-15T12:39:43.221733003Z   File "/start.py", line 40, in resolve
imap             | 2019-03-15T12:39:43.221736423Z     return socket.gethostbyname(hostname)
imap             | 2019-03-15T12:39:43.221739458Z socket.gaierror: [Errno -2] Name does not resolve

imap             | 2019-03-15T12:16:26.058791424Z The above exception was the direct cause of the following exception:
imap             | 2019-03-15T12:16:26.058793962Z
imap             | 2019-03-15T12:16:26.058796626Z Traceback (most recent call last):
imap             | 2019-03-15T12:16:26.058798916Z   File "/start.py", line 44, in <module>
imap             | 2019-03-15T12:16:26.058802072Z     os.environ["REDIS_ADDRESS"] = resolve(os.environ.get("REDIS_ADDRESS", "redis"))
imap             | 2019-03-15T12:16:26.058805012Z   File "/usr/lib/python3.6/site-packages/tenacity/__init__.py", line 292, in wrapped_f
imap             | 2019-03-15T12:16:26.058807566Z     return self.call(f, *args, **kw)
imap             | 2019-03-15T12:16:26.058809829Z   File "/usr/lib/python3.6/site-packages/tenacity/__init__.py", line 358, in call
imap             | 2019-03-15T12:16:26.058812447Z     do = self.iter(retry_state=retry_state)
imap             | 2019-03-15T12:16:26.058814709Z   File "/usr/lib/python3.6/site-packages/tenacity/__init__.py", line 332, in iter
imap             | 2019-03-15T12:16:26.058817211Z     six.raise_from(retry_exc, fut.exception())
imap             | 2019-03-15T12:16:26.058819532Z   File "<string>", line 3, in raise_from
imap             | 2019-03-15T12:16:26.058822111Z tenacity.RetryError: RetryError[<Future at 0x7f0102a0f0f0 state=finished raised gaierror>]

I checked the hosts conf of imap:

```
127.0.0.1       localhost
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
192.168.64.2    909bd1585a48
```

I applied the nginx.conf solution indicated here :  https://github.com/Mailu/Mailu/issues/454
It didn't change anything. What can I do ? I don't want to apply a solution that will break after I restart docker...

thanks for answering

**Comment by dsiggi** [comment]
Hi,
have you found a solution to the problem?

I installed mailu about 2 weeks ago and played something with it and everything worked so far. Then I stopped the container.

When I start the container now I get the same errors as you do with the containers smtp, imap and antispam.

**Comment by kaiyou** [comment]
Could you check that your redis container is running? And provide some logs for that container?

**Comment by arveen-ponniah** [comment]
Hi,
we had a migration with over 5000 mail accounts to our mailu server. most of the user are using imap and pop without encryption and thats why we need a fix for it.
as a temporary fix we also changed the nginx.conf:
server {
  listen 143;
  listen [::]:143;

  starttls on; #instead of only

  protocol imap;
  smtp_auth plain login; #instead of imap_auth plain
}

server {
  listen 110;
  listen [::]:110;

  starttls on; #instead of only

  protocol pop3;
  smtp_auth plain login; #instead of pop3_auth plain
}

also related with #454
is there a possibility from your side to implement it? that we don't need to change the nginx.conf file after every container reload

**Comment by kaiyou** [comment]
The override file is included so you would not he able to change this.

I cannot see how your fix is related to the issue? Can you confirm it is the same as the author issue and provide some details?

Also, no, we will not change the starttls behavior, you should enable starttls on the client instead.

**Comment by marienfressinaud** [comment]
I had the same error: Redis received a SIGTERM signal and stopped. It was impossible to restart it so I removed the container and rebuilt it (well, I did it for all the services with `docker-compose down` and `docker-compose up`)

**Comment by kaiyou** [comment]
I don't believe we will be getting news from the original author, I'll close
