### ISSUE TITLE
Make Mailu available as a CapRover one-click app

### ISSUE THREAD

**Issue by pSnehanshu** [Mailu/Mailu#973]
# What's CapRover ?
[CapRover ](https://caprover.com/)is an extremely easy to use app/database deployment & web server manager for your NodeJS, Python, PHP, ASP.NET, Ruby, MySQL, MongoDB, Postgres, WordPress (and etc...) applications!

## One-click apps
CapRover [one-click apps](https://github.com/caprover/one-click-apps) makes it easy to deploy an app from a Web UI.
More help can be found [here](https://caprover.com/docs/one-click-apps.html).

## Request
Please make Mailu available as a CapRover one-click app by creating a configuration file and creating a pull request at [caprover/one-click-apps](https://github.com/caprover/one-click-apps).

**Comment by vanekj** [comment]
Hi! Thank you for the request. I was trying to build the configuration file from the generated docker-compose file, but I am stuck on using the right environment variables for each mailu/x image as the generated file is using `env_file`.  It would be great so setup the whole mailserver on the CapRover by just using the one-click-app!

**Comment by pSnehanshu** [comment]
Hey @vanekj, thanks for responding. I'm not a pro sysadmin, so an one click app would definitely help. That's why I've opened this issue for help. I wished I could have done it myself, but I lack appropriate knowledge in this domain, I am just a developer. So help is needed.

**Comment by vanekj** [comment]
Neither am I, so it would be great if the setup will be made by someone who is more into this stuff.

**Comment by kaiyou** [comment]
CapRover is probably not a deployment target we want to aim at, because it is mostly meant for web applications. Also, we are focusing on helm, which makes one-click deployment possible in many frontends nowadays, including Rancher. Closing as stale, feel free to reopen.

**Comment by IntrovertedFL** [comment]
Caprover already has a one-click app for Iredmail and Post.io, would be really nice to see a one-click deployment for Mailu :)

**Comment by nileshtrivedi** [comment]
+1 for being able to run Mailu in CapRover easily. It's meant for all kind of Dockerized services, not just web applications.
