### ISSUE TITLE
Urgently update RSPAMD Version to at least 1.8.2

### ISSUE THREAD

**Issue by ripkens** [Mailu/Mailu#975]
RSPAMD has a major bug regarding SURBL, it checks the whole sender ip chain down to the private dynamic ip of the originating client (SPAMHAUS-PBL).

It must only check the last IP in the chain from the server it has received the mail from to work properly.

RSPAMD 1.8.2 has a fix for that obviously and that needs to be pullable as soon as possible please.

"Critical fixes in SURBL module

SURBL module could insert absurd scores and skip group symbol limit in some cases."

**Comment by hoellen** [comment]
This is fixed with #1052
```
rspamd --version
Rspamd daemon version 1.9.4
```
