### ISSUE TITLE
CLI : how to disable mail adress ?

### ISSUE THREAD

**Issue by fldu** [Mailu/Mailu#976]

**Comment by kaiyou** [comment]
What do you mean with disable? That it won't receive email? That you cannot connect to it?

**Comment by fldu** [comment]
disable the login on this account, not the reception of emails

**Comment by kaiyou** [comment]
You can already disable IMAP and Pop, maybe we could add disabling SMTP and access to the admin ui.

**Comment by fldu** [comment]
@kaiyou thanks for your answer ! thinking about that : is it planned to add an ldap integration ?

**Comment by kaiyou** [comment]
It is not specifically but we are planning on refactoring the authentication globally sometime.

The general idea will probably be to provide bindings to an idp and let it manage back end bindings.
