### ISSUE TITLE
rewrite or internal redirection cycle while internally redirecting to "/webmail"

### ISSUE THREAD

**Issue by psytechno604** [Mailu/Mailu#977]
I used mailu setup utility, which generated .yml and .env files for my ip, domain and hostname. I set up DNS. But every time I do the request to my server (mail.basic-algorithm.org), I get the above message in front log (docker logs mailu_front_1) and error 500 in browser.

Here are my config files:
[docker-compose.yml.txt](https://github.com/Mailu/Mailu/files/2997473/docker-compose.yml.txt)
[mailu.env.txt](https://github.com/Mailu/Mailu/files/2997474/mailu.env.txt)

(currently set to 'notls', but the same situation is with 'letsencrypt')

**Comment by psytechno604** [comment]
just realized it is because of WEBMAIL=none... now set to WEBMAIL=rainloop and got:

2019/03/22 17:30:54 [error] 7#7: *5 webmail could not be resolved (3: Host not found), client: 89.255.94.229, server: , request: "GET /webmail/ HTTP/2.0", host: "mail.basic-algorithm.org"
89.255.94.229 - - [22/Mar/2019:17:30:54 +0000] "GET /webmail/ HTTP/2.0" 502 166 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:64.0) Gecko/20100101 Firefox/64.0"

**Comment by dani909** [comment]
Could you try again with `WEBMAIL=none` and `WEBROOT_REDIRECT=/admin`?

**Comment by psytechno604** [comment]
> Could you try again with `WEBMAIL=none` and `WEBROOT_REDIRECT=/admin`?

admin ui opens and I can even log in... seems like something wrong with webmail service?

**Comment by psytechno604** [comment]
this was because 'webmail' section in docker-compose.yml was missing, I forgot to include it in the first step (setup utility), and simply switching from 'none' after that is not enough

for future usability, it will be better to show some kind of message that necessary container is not running or so..
