### ISSUE TITLE
Should `antispam` be hardcoded?

### ISSUE THREAD

**Issue by ajgon** [Mailu/Mailu#978]
I'm in a middle of setting up my own mailu instances, however I'm using namespaced container names (i.e. `mailu-admin`, `mailu-front` etc.). Everything works pretty well so far, however I have some problems with imap and antispam. After some investigation I noticed, that files `core/dovecot/conf/bin/ham` and `core/dovecot/conf/bin/spam` have antispam host hardcoded instead of using `HOST_ANTISPAM`. 

I'm happy to provide PR, but firstly want to be sure - is it in fact oversight, or is this by design?

**Comment by kaiyou** [comment]
Nope, it should not be hardcoded, any PR on the matter is more than welcome :)
