### ISSUE TITLE
How to use DKIM

### ISSUE THREAD

**Issue by RaymondSchnyder** [Mailu/Mailu#98]
Hi Mailu!

First i wanna thank you for this amazing software!
I love it already and im very happy :D

But i have one problem, in your features there is this point:
"Security, enforced TLS, **outgoing DKIM**, anti-virus scanner"

But i dont see any option where I can activate DKIM or use it.

Is this feature not built in yet or didnt i found it?

Greetings

Raymond

**Comment by RaymondSchnyder** [comment]
Found it! Sorry for this issue, but im posting a tutorial!

First go to the email domains under administration
http://i.imgur.com/Iuqn8IF.png

Then click on the Icon on the left on the desired domain.
http://i.imgur.com/cHEooKH.png

Click now in the top right corner on "Regenerate keys", you will be asked to confirm this. confirm it.
http://i.imgur.com/ZeRSAUM.png

and taadaaaa you see the DKIM keys! 
http://i.imgur.com/o4CCZqM.png

**Comment by BoW2EviL** [comment]
this might just be a fluke but i was tring to setup the dkim and ran into some issues mainly the "DNS DKIM entry" adds spaces and quotes.
IE:
```
dkim._domainkey.example.com. 600 IN TXT "v=DKIM1; k=rsa; p=MIIXto" "CfdQAB"
```
I do believe this is correct for txt based dns setups they will automatically parse the quotes and combine.
BUT if you are using a GUI DNS like godaddy or ionos it must not contain the quotes or the space like shown in the "DKIM public key"
IE:
```
v=DKIM1; k=rsa; p=MIIXtoCfdQAB
```
hopefully this will save somebody some time

this site helped me the most to determine the issue
just simple validation. 
https://dkimcore.org/c/keycheck
for some reason mxtoolbox said it was vaild even though it was not.
they used to offer a mail header service that helped me find this issue years ago the last time i setup a mail server lol 
but they dont now. so i couldnt figure out why it was getting spamed. i read the google dmarc xml file and it said the DKIM was rejected. so i started debuging and this is what i came up with. figured i would share

**Comment by TheOnlyWayUp** [comment]
Thank you @BoW2EviL!

mail-tester.com is great and checks deliverability in general. 3 per day
