### ISSUE TITLE
sieve filtering based on recipient_delimiter no longer works in 1.6

### ISSUE THREAD

**Issue by bsx** [Mailu/Mailu#982]
I have a sieve rule setup to automatically sort mails into folders based on the part after the recipient delimiter, so mail to `foo+bar@example.com` would get sorted into folder `bar` provided it exists.
The rule for this is as follows:
```
require ["envelope","fileinto","subaddress","variables"];
if envelope :detail :matches "to" "*"
{
	fileinto "${1}";
}
```

This worked fine in Mailu 1.5, but ever since upgrading to 1.6 all those mails get filed just into `INBOX`. Sieve evaluation itself is working, as other rules get applied properly.

**Comment by bsx** [comment]
I did some further digging and the recipient address in the envelope gets rewritten to the canonical user address when the mail is forwarded via LMTP to dovecot.

Relevant header in 1.5:
```
Received: from mail.example.com ([172.18.0.10])
        by mail.example.com with LMTP id mOZHIEl4i1zFRgAAkeXSCA
        for <foo+bar@example.com>; Fri, 15 Mar 2019 10:02:49 +0000
...
To: foo+bar@example.com
```

Header after the upgrade to 1.6:
```
Received: from mail.example.com ([172.18.0.12])
        by mail.example.com with LMTP
        id wG8HKAluj1zCXAAAfVZfzA
        (envelope-from <redacted>)
        for <foo@example.com>; Mon, 18 Mar 2019 10:08:09 +0000
...
To: foo+bar@example.com
```

I think that rewrite was introduced in #778 to fix #755. Is there a way to pass the envelope information to dovecot again to allow the aforementioned filtering based on the detail part?

**Comment by RobertMe** [comment]
I'm setting up a new Mailu installation (so running 1.7) and migrating over some Sieve scripts from a previous mail setup (not Mailu). And I still seem to be able to confirm this? At least it's not working and I'm seeing the same in the mail headers where the address extension / recipient delimiter is removed in the last part (LMTP delivery from Postfix to Dovecot).

**Comment by kaiyou** [comment]
It is very probable indeed that this stopped working when switching to Podop. We would need to return the suffix after rewriting the address

**Comment by kaiyou** [comment]
Oh I just read about #1299, I will review :)
