### ISSUE TITLE
(Docs) Patreon link is 404

### ISSUE THREAD

**Issue by pquerner** [Mailu/Mailu#983]
In the docs [1] the link to the patreon page is a 404.

[1] https://mailu.io/1.6/faq.html#i-would-like-to-donate-for-a-feature

**Comment by Angedestenebres** [comment]
@kaiyou could you please check that? :)

**Comment by kaiyou** [comment]
I removed the Patreon link that was to me personally after stopping working on the project altogether. I will remove it from the faq, and i suggest we add Patreon link along with contributors for people who wish it, directly in AUTHORS.md.
