### ISSUE TITLE
Add SUBNET to Rancher Catalog

### ISSUE THREAD

**Issue by wabu** [Mailu/Mailu#986]
I'm missing the option to set the SUBNET variable when setting up Mailu from the rancher catalog. Without setting SUBNET dovecot will recheck IMAP logins (on my rancher 1.6.26), so I did add the variable `SUBNET=10.42.0.0/16` manually inside the services, but it would be good to have this option inside the catalog setup.

**Comment by kaiyou** [comment]
Rancher catalog is now deprecated in favor of helm charts. I am closing this as stale, feel free to reopen.
