### ISSUE TITLE
🕆 Hallelujah - Admin interface on Phone will not show menu

### ISSUE THREAD

**Issue by loveJesus** [Mailu/Mailu#988]
God be praised - thanks for a great product, first of all i hope to encourage us to seek [Jesus](https://www.jesusfilm.org/watch/jesus.html/english.html).  (I have seen Him do miracles even healing a dog we had from cataracts by the morning after praying for her).

The administrator will not show the menu while on the phone, there is no straightforward way for a user to change their password.

**Comment by Angedestenebres** [comment]
In fact, you can easily reproduce that issue on your PC with your internet browser by reducing the size of the window:

![Capture d'écran du 2019-04-13 10 38 45](https://user-images.githubusercontent.com/21110485/56077111-907de680-5dd8-11e9-9f44-aed8f902fa6c.png)

So, yes usage is really limited on smartphone and a button to have access on the menu should be great :)

**Comment by hoellen** [comment]
This is now merged with #1048
