### ISSUE TITLE
[Wishlist] Allow to configure all Mailu components without web interface

### ISSUE THREAD

**Issue by tgpfeiffer** [Mailu/Mailu#990]
I am trying to install Mailu (docker-compose setup) in a "infrastructure as code"-like approach, where all configuration lives in files in a git repository and I would be able to get the server running on a vanilla server just by copying the configuration files and executing `docker-compose up`. However, I could not find out how to configure various aspects of Mailu (in particular fetchmail and DKIM) without logging into the web interface.

I would love to see some support for the configuration of all parts of Mailu without going through an interactive interface. (I guess just appropriate configuration files need to be placed in some directories, but I don't know which files need to go where.)

**Comment by kaiyou** [comment]
This will probably not happen, as Mailu is not the proper product for this kind of thing. The web admin app is wired at the core of the system and especially meant for admins that do not wish to use command line every day.
