### ISSUE TITLE
Spammers spoofing user's email addresses not being rejected

### ISSUE THREAD

**Issue by Mechazawa** [Mailu/Mailu#995]
I'm having issues with spammers pretending to have hacked into user's inboxes. They will pretend that the email was sent by the user to their own account as "proof" they have their password. 

**Attachment:** [Mail headers](https://github.com/Mailu/Mailu/files/3107151/headers.txt) (I've replaced my own email with hidden-email@ioexception.at)

**Comment by kaiyou** [comment]
I noticed this also, recently.

**Comment by karimhm** [comment]
**postfix-policyd-spf-python** should solve the issue, though not available on Alpine Linux packages repository yet.

**Comment by kaiyou** [comment]
Actually, sender maps should already deal with this, this is why I labelled this as a p0: something is possibly broken in our config.

**Comment by kaiyou** [comment]
I am closing since my own comment was misguided and we have not heared about it since.
