### ISSUE TITLE
How to find number of email sent by a user?

### ISSUE THREAD

**Issue by alizowghi** [Mailu/Mailu#996]
Hi
Is there any way to track number of emails  sent by a specific user?

**Comment by Pentiva** [comment]
`find <path-to-mailu> -type f | grep <email-address>/.Sent/cur | wc -l` 
returns the current number of emails sent by the specified user.

**Comment by alizowghi** [comment]
Thank you very much @Pentiva

**Comment by kaiyou** [comment]
Should I close?
