### ISSUE TITLE
notls does not work (forces front to restart)

### ISSUE THREAD

**Issue by lexusburn** [Mailu/Mailu#999]
I would like to create a test setup on my local machine and therefore i don't want to use letsencrypt for certificates. I had choosen notls but now the front service hangs in a restart loop

```
Attaching to mailu_front_1
front_1      | nginx: [emerg] invalid number of arguments in "location" directive in /etc/nginx/nginx.conf:76
```

can you help please?

**Comment by qm78** [comment]
Duplicate of #856 
Fixed in #889
